- src/diffusers/utils/logging.py
Removes mentions of 🤗Transformers with 🤗Diffusers equivalent in `utils/logging.py`.
This includes comments and environmental variables.
This was mentioned in issue #12
> changes comments and env vars in `utils/logging.py`

- src/diffusers/schedulers/scheduling_ddpm.py
Changed from alpha_prod_t to alphas_cumprod
If I'm not mistaken it's a type from [this commit](https://github.com/huggingface/diffusers/commit/2b8bc91cf8f4d33a1b62fc7010a1a598e03c8e63#diff-5014bf116e54d20c980d805dc58ac83ac75b2976a2d785978632f14d8fb53ea9) when 
get_alpha_prod method was removed
> fix alphas_cumprod

- src/diffusers/modeling_utils.py
- src/diffusers/models/resnet.py
- src/diffusers/models/unet.py
- src/diffusers/models/unet_glide.py
- src/diffusers/models/unet_grad_tts.py
- src/diffusers/models/unet_ldm.py
- src/diffusers/models/unet_rl.py
- src/diffusers/models/unet_sde_score_estimation.py
- src/diffusers/models/vae.py
- src/diffusers/pipelines/bddm/pipeline_bddm.py
- tests/test_layers_utils.py
Move `FirUpsample` and `FirDownsample` to `resnet.py` class - should maybe go into a `sampler.py` at some point but not stay in the `unet_...py` files.
Most importantly make upsamplers and downsamplers 1D and 2D specific
> Downsample / Upsample - clean to 1D and 2D

- examples/train_unconditional.py
- src/diffusers/training_utils.py
Currently the EMA model stepping is done such that you need to pass a global step so that the decay can be calculated and used to perform the EMA. So the EMA step is called as `ema_model.step(model, global_step)`. 
With this PR, the current step is stored in the `EMAModel` class under the variable `self.optimization_step` so now we only need to call `ema_model.step(model)` and the current step is updated.
> EMA model stepping updated to keep track of current step

- examples/train_unconditional.py
- src/diffusers/models/attention.py
- src/diffusers/training_utils.py
- tests/test_modeling_utils.py
This fixes a shape mismatch in `proj_out.weight` during an EMA step, and adds an EMA test to catch it in the future.
To reproduce the bug:
```python
import torch
from diffusers import UNetModel
from diffusers.training_utils import EMAModel
unet = UNetModel(resolution=32)
ema = EMAModel(unet)
outputs = unet(torch.randn((1, 3, 32, 32)), torch.ones(1))
ema.step(unet, 1)
```
```python
File "/diffusers/src/diffusers/training_utils.py", line 81, in step
ema_param.add_(param.data.to(dtype=ema_param.dtype), alpha=1 - self.decay)
RuntimeError: output with shape [128, 128, 1, 1] doesn't match the broadcast shape [128, 128, 128, 1]
```
> Fix mutable proj_out weight in the Attention layer

- scripts/convert_ldm_original_checkpoint_to_diffusers.py
This adds a conversion script for the LDM models.
Tested on `fusing/unet-ldm-dummy` and `fusing/latent-diffusion-celeba-256`.
*There is still an issue with the QKV layer, see below for reproducer*.
<details>
<summary>Running with <code>fusing/unet-ldm-dummy</code></summary>
```python
import json
from diffusers import UNetUnconditionalModel
from scripts.convert_ldm_original_checkpoint_to_diffusers import convert_ldm_checkpoint
from huggingface_hub import hf_hub_download
import torch
original_checkpoint = torch.load(hf_hub_download('fusing/unet-ldm-dummy', 'diffusion_model.pt'))
config_path = hf_hub_download('fusing/unet-ldm-dummy', 'config.json')
with open(config_path) as f:
config = json.load(f)
checkpoint = convert_ldm_checkpoint(original_checkpoint, config)
def …
```
> LDM conversion script

- scripts/convert_ddpm_original_checkpoint_to_diffusers.py
- scripts/convert_ldm_original_checkpoint_to_diffusers.py
- tests/test_modeling_utils.py
Adds a conversion script for DDPM.
It currently still prints out errors for the `mid` variable, but IIUC that's normal as this variable will be removed soon.
See below for code which allows to check equivalence. Replace with any checkpoint that contains `ddpm`.
<details>
<summary>Running with <code>fusing/ddpm-celeba-hq-ema</code></summary>
```python
import json
from diffusers import UNetUnconditionalModel
from scripts.convert_ddpm_original_checkpoint_to_diffusers import convert_ddpm_checkpoint
from huggingface_hub import hf_hub_download
import torch
repo_id = 'fusing/ddpm-celeba-hq-ema'
original_checkpoint = torch.load(hf_hub_download(repo_id, 'diffusion_model.pt'))
config_path = hf_hub_download(repo_id, 'config.json')
with open(config_path) as f:
config = json.load(f)
checkpoint = …
```
> DDPM Conversion

- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- src/diffusers/schedulers/scheduling_utils.py
- tests/test_scheduler.py
A couple weird things / things to double check in here:
- I needed to init sigmas in the `init` function for the `ScoreSdeVeScheduler`, much how other models need to have timesteps init.
- I removed `test_from_pretrained_save_pretrained` for this scheduler
- I added a `seed` arg for the prediction here, in order to make tests deterministic, its much less elegant than when `eta` is an option
- a big a regression on how easy it will be to make numpy == pytorch
Anyways, 🤗
> Fix VE SDE tests, clean API

- src/diffusers/configuration_utils.py
- src/diffusers/models/unet_conditional.py
- src/diffusers/models/unet_unconditional.py
- src/diffusers/models/vae.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- src/diffusers/schedulers/scheduling_sde_vp.py
- src/diffusers/schedulers/scheduling_utils.py
- tests/test_modeling_utils.py
This PR adds a decorator to avoid duplicating the list of arguments of all classes inheriting from `ConfigMixin`. Once decorated, the init:
- automatically ignores all private arguments
- sends all parameters to `self.register_to_config`, except for the arguments listed in the `ignore_for_config` class variable.
> Add a decorator for register_to_config

- src/diffusers/models/vae.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
- src/diffusers/pipelines/pndm/pipeline_pndm.py
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
- tests/test_modeling_utils.py
Refactored the pipelines so that their outputs are always:
* numpy arrays
* rescaled and clamped to [0., 1.]
* with channels last: shape = [size, size, channels]
Then all of our demos can be shrunk down to:
```python
images = pipeline(...)["sample"]
image = (images[0] * 255).round().astype('uint8')  # or just leave as [0, 1] for matplotlib/opencv/etc
image = Image.fromarray(image)
```
The tests are modified accordingly with `expected_slice = expected_slice / 2 + 0.5 `
> Refactor pipeline outputs, return LDM guidance_scale

- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_utils.py
- tests/test_scheduler.py
cc @patrickvonplaten. Will let you know if I fix this before bed today. Numpy not having a generator makes this tricky. 
Some easy fixes are in this, such as `get_variance` in `DDPMTesterClass` needs to be changed to `_get_variance` (what should the common terminology on this be)
Then this change also broke the `ve sde test` for the full loop, which is very sensitive to changes in `randn_like`. This is a common problem for these tests.
> fixing tests for numpy and make deterministic (ddpm)

- examples/README.md
In https://github.com/huggingface/diffusers/issues/124 I incorrectly suggested that the image set creation process was undocumented.  In reality, I just hadn't located it.  @patrickvonplaten did so for me.
This PR places a hotlink so that people like me can be shoehorned over where they needed to be.
> Documentation cross-reference

- src/diffusers/__init__.py
- src/diffusers/training_utils.py
- tests/test_modeling_utils.py
- tests/test_training.py
At the moment we have a bug somewhere that leads to poor model convergence with the DDIMScheduler.
These tests didn't help to point out that bug, but they're useful to have anyway
> Add training and batched inference test for DDPM vs DDIM

- scripts/convert_ddpm_original_checkpoint_to_diffusers.py
- src/diffusers/__init__.py
- src/diffusers/models/resnet.py
- src/diffusers/models/unet_blocks.py
- src/diffusers/models/vae.py
- src/diffusers/training_utils.py
- tests/test_modeling_utils.py
This PR cleans the VAE and AutoencoderKL class to adhere to the new and cleaner weight naming structure
> [Vae and AutoencoderKL] Final clean of LDM checkpoints

- src/diffusers/schedulers/scheduling_ddpm.py
This is an implementation of the [Improved Denoising Diffusion Probabilistic Models](https://arxiv.org/pdf/2102.09672.pdf)
which added the ability to learn the variance instead of just predicting the noise.
It is assumed that the step method receives a tensor shape (B, C, ...) when predicting noise.
At the moment, it only implements variance. In order to use it fully, the user needs to write the additional loss function from the paper into their training loop.
For future contribution, I think it would be beneficial to implement a losses module with different loss functions like the VB loss in the Improved Diffusion paper or other loss functions used in different diffusion papers (and maybe a trainer object). If needed, I can make new PRs with the relevant additions, or this can be an …
> Allow DDPM scheduler to use model's predicated variance

- examples/README.md
- examples/train_unconditional.py
Linked to https://github.com/huggingface/diffusers/issues/145
> Support training with a local image folder

- src/diffusers/models/unet_2d_condition.py
- src/diffusers/models/unet_blocks.py
The `cross_attention_dim` is hardcoded to `1280` in cross attention blocks
This PR adds `cross_attention_dim` argument to `UNet2DConditionModel` init so that this value can be provided by the user.  
Also what should be the name ? `cross_attention_dim` look good, but in the `SpatialTransformer` class it's called `context_dim`.  Think we should refactor these names and unify them. Wdyt @patrickvonplaten @anton-l .
> [UNet2DConditionModel] add cross_attention_dim as an argument

- src/diffusers/models/vae.py
- tests/test_modeling_utils.py
The VAE `encoder` is currently broken, as we don't pass `downsample_padding` to `get_down_block`, so it defaults to `None` in `DownEncoderBlock2D`. This PR fixes this by passing `downsample_padding=0` in `get_down_block` in the `Encoder`.
This issue was not caught in tests as the dummy models in test uses only one up/down sampling block, and the VAE models don't add the Up/Down sampling in the last block which in this case is the first block. 
@anton-l @patrickvonplaten Let's make sure to add at least two blocks when creating dummy models for tests.
> [VAE] fix the downsample block in Encoder. 

- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
The `LDMBertModel` was hardcoded to return the `last_hidden_state` as text conditioning. This PR updates the model to return the `BaseModelOutput` so ideally any text model from `transformers` can be used here.
Also thinking more about this, `bert` and `vqvae` are wrong names here, they should be `text_model` and `vae`. `vae` because the ldm-txt2img model uess `AutoencoderKL` not `VQModel`.
> [LDMTextToImagePipeline] make text model generic

- src/diffusers/models/unet_blocks.py
Our current VAE does not support having `attention` in `encoder/decoder` block as none of the pre-trained models had one. But looking at the stable-diffusion upscaling and RDM config
https://github.com/pesser/stable-diffusion/blob/693e713c3e72e72b8e2b97236eb21526217e83ad/configs/stable-diffusion/upscaling/upscale-v1-with-f16.yaml#L96
https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/configs/retrieval-augmented-diffusion/768x768.yaml#L62
It seems some new VAE are going to have `attention` in `encoder/decoder`. This PR adds `AttnDownEncoderBlock2D` and `AttnUpDecoderBlock2D` to suppor this.
> add attention up/down blocks for VAE

- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_pndm.py
This PR adds `scaled_linear` schedule in `PNDM` and `DDPM` schedulers so those could be used with latent/stable diffusion models.
> add scaled_linear schedule in PNDM and DDPM

- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/schedulers/scheduling_pndm.py
The Stable diffusion model uses PNDM as the main scheduler. Right now it's not possible to use PNDM scheduler in `LDMText2ImagePipeline` as the `eta` for DDIM is always passed to `step` method. The `PNDMScheduler` does not have this argument.
This PR adds `**kwargs` in `PNDMScheduler.step` and passes `eta` as kwarg in `LDMText2ImagePipeline`, so that the pipeline can be used with both schedulers. Since both LDM and stable diffusion model can be used with both these schedulers it's important to allow this interoperability.
> allow pndm scheduler to be used with ldm pipeline

- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
- src/diffusers/schedulers/scheduling_pndm.py
This PR updates the `LDMTextToImagePipeline` and `LDMPipeline` to determine wether the `scheduler.step` accepts  the `eta` arg using `inspect.signature`. And removes the unused `kwargs` from `PNDMScheduler`
> [PNDM in LDM pipeline] use inspect in pipeline instead of unused kwargs

- src/diffusers/__init__.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stochatic_karras_ve/pipeline_stochastic_karras_ve.py
- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/utils/dummy_transformers_objects.py
- tests/test_modeling_utils.py
This PR adds `StableDiffusionPipeline`
> Stable diffusion pipeline

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
This PR shows how to generate images with custom height and width, for example can be used to generate recatngular images.
```python
pipe(prompt, height=512, width=256,  guidance_scale=7.5)["sample"]
```
> allow custom height, width in StableDiffusionPipeline

- src/diffusers/models/embeddings.py
- src/diffusers/models/resnet.py
- src/diffusers/models/unet_2d.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/schedulers/scheduling_ddim.py
- tests/test_modeling_utils.py
This PR fixes a couple of things to allow stable diffusion to give 1-to-1 the same results as the [original implementation](https://github.com/CompVis/stable-diffusion)
Changes include:
- Make sure group norm is run always in fp32
- Change ordering of how time embeddings are computed -> for some reason this makes a big difference for stable diffusion but not really for other models it seems
- Make sure time embeddings are expanded if batch size > 1
- Adapt DDIM sampler to allow to be 1-to-1 compatible with stable diffusion
Both DDIM and PNDM work with the following script:
```python
#!/usr/bin/env python3
from diffusers import StableDiffusionPipeline, DDIMScheduler
from time import time
from einops import rearrange
import torch
from torch import …
```
> [Half precision] Make sure half-precision is correct

- src/diffusers/schedulers/scheduling_pndm.py
- tests/test_modeling_utils.py
This PR allows to use the PNDM scheduler without the prk steps so that it matches 1-to-1 @crowsonkb implementation as shown [here](https://github.com/CompVis/latent-diffusion/pull/51). 
As soon as a new diffusers version is released, we have to add a flag "skip_prk_ steps" to all stable diffusion configs.
> [PNDM] Stable diffusion

- src/diffusers/schedulers/scheduling_ddim.py
- tests/test_modeling_utils.py
`set_alpha_to_one` is indeed better naming - thanks @pcuenca !
> [Naming] correct config naming of DDIM pipeline

- src/diffusers/pipeline_utils.py
- tests/test_modeling_utils.py
Addresses #183.
Override modules are recognized and replaced in the pipeline. However, no check is performed about mismatched classes yet. This is because the override module is already instantiated (see https://github.com/huggingface/diffusers/blob/main/src/diffusers/configuration_utils.py#L223), and `init_dict` in https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipeline_utils.py#L151 no longer has a `library_name` or a `class_name` - just the instantiated module.
I'm looking at a way to detect a class mismatch so we can fail more gracefully.
> Allow passing non-default modules to pipeline

- tests/test_modeling_utils.py
The `test_from_pretrained_hub_pass_model` test initializes `ddpm_from_hub_custom_model` twice. This PR loads the pipeline just ones.
> fix test_from_pretrained_hub_pass_model

- README.md
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
This PR sets `guidance_scale` to `7.5` in `StableDiffusionPipeline` as per the official defaults.
> [StableDiffusionPipeline] use default params in __call__

- Makefile
- setup.py
- src/diffusers/dependency_versions_table.py
- src/diffusers/optimization.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/ddim/__init__.py
- src/diffusers/pipelines/ddpm/__init__.py
- src/diffusers/pipelines/latent_diffusion/__init__.py
- src/diffusers/pipelines/latent_diffusion_uncond/__init__.py
- src/diffusers/pipelines/pndm/__init__.py
- src/diffusers/pipelines/score_sde_ve/__init__.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stochatic_karras_ve/__init__.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/utils/dummy_scipy_objects.py
- tests/test_layers_utils.py
This cleans up unused imports and code, and adds flake flags where needed.
As a result, `make quality` will work now, similar to `transformers`.
:warning: Make sure to `pip install -e ".[dev]" ` to install `hf-doc-builder` for the upcoming docs overhaul :) 
cc @patil-suraj @patrickvonplaten @pcuenca @natolambert
> Revive `make quality`

- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- tests/test_modeling_utils.py
Fixes #211
Makes sure that `LDMTextToImagePipeline` can be called with `pipe("some prompt")`, similar to `StableDiffusionPipeline`
> Support one-string prompts and custom image size in LDM

- src/diffusers/__init__.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/safety_checker.py
This PR adds `StableDiffusionSafetyChecker` to filter out NSFW content in `StableDiffusionPipeline`.
The `StableDiffusionSafetyChecker` contains the clip vision model, vision projection. The nsfw concept embeddings are pre-computed and part of the state_dict. The module takes images and replaces nsfew image if detected with a black image.
It's added as a new required attribute in `StableDiffusionPipeline` so it'll always be loaded.
> Add safety module

- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
- src/diffusers/pipelines/pndm/pipeline_pndm.py
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stochatic_karras_ve/pipeline_stochastic_karras_ve.py
The following will run the pipeline in `cuda:1` (not `cuda:0`) as would be expected:
```Python
pipe = StableDiffusionPipeline.from_pretrained(
"CompVis/stable-diffusion-v1-3-diffusers",
use_auth_token=True).to("cuda:1")
pipe("Some prompt")
```
However, passing a device to `__call__` will still move the pipeline to that device.
The implementation of `DiffusionPipeline.to()` does nothing if the device is `None`. This is to preserve the same semantics as PyTorch, where AFAIK if you use `to(None)` the object is not moved anywhere.
If we were to forgo that behaviour, we could make `DiffusionPipeline.to(None)` select `cuda` by default (when available). This would make for much simpler code in all pipeline implementations, as they'd just need to invoke `self.to`, but might break the expectations …
> Pipeline to device

- src/diffusers/utils/__init__.py
Otherwise attempting to import `hub_utils` (in training scripts, for example), fails.
This was removed during the refactor in df90f0c.
> Restore `is_modelcards_available` in `.utils`

- tests/test_scheduler.py
Quick fix for failing `PNDMSchedulerTests`
TLDR: we are calling `set_timesteps` after setting the `ets` manually, which clears the `ets` resulting in `ValueError` in `step_pmls`
> hotfix for pdnm test

- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
This PR adds the `add_noise` method in `LMSDiscreteScheduler` and `PNDMScheduler`. This method is required for image2image pipeline.
> add add_noise method in LMSDiscreteScheduler, PNDMScheduler

- examples/inference/image_to_image.py
This PR adds a check for `strength` value in `StableDiffusionImg2ImgPipeline` example pipeline
> [example/image2image] raise error if strength is not in desired range

- examples/inference/readme.md
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
I created a simple notebook to demonstrate how it works.
TODO:
> Reproducible images by supplying latents to pipeline

- examples/inference/inpainting.py
This script is a copy of https://github.com/huggingface/diffusers/blob/main/examples/inference/image_to_image.py but for inpainting.
example usage
```
from examples.inference.inpainting import StableDiffusionInpaintingPipeline
pipeimg = StableDiffusionInpaintingPipeline.from_pretrained(
"CompVis/stable-diffusion-v1-4",
revision="fp16", 
use_auth_token=True,
cache_dir="/content/drive/MyDrive/AI/StableDiffusion"
).to("cuda")
num_samples = 1
def infer(prompt, init_image, mask_image, strength=0.75):
if init_image != None:
init_image = init_image.resize((512, 512))
init_image = preprocess(init_image)
with autocast("cuda"):
images = pipeimg([prompt] * num_samples, init_image=init_image,mask_image=mask_image,strength=strength, guidance_scale=7.5)["sample"]
else: 
with …
```
> add inpainting example script

- examples/inference/inpainting.py
- examples/inference/readme.md
This PR fixes the inpainting script and adds it in readme with colab
cc @nagolinc
> Fix inpainting script 

- examples/inference/readme.md
thanks for the work on diffusers. Here's a minor fix to the code in readme
> Adds missing torch imports to inpainting and image_to_image example

- src/diffusers/schedulers/scheduling_lms_discrete.py
The formulation of add noise is LMSDiscreteScheduler is wrong  (see crowsonkb/k-diffusion#4). This PR fixes that
> [BugFix]: Fixed add_noise in LMSDiscreteScheduler

- src/diffusers/schedulers/scheduling_pndm.py
- tests/test_scheduler.py
Before this fix, the concerned attributes were lists, and lists don't get formatted in `self.set_format`
> [PNDM Scheduler] format timesteps attrs to np arrays

- .github/workflows/push_tests.yml
Setting `pytest -n 1` should help with GPU OOMs, but if it doesn't then we can do something like this in another PR for each large test suite:
```python
def tearDown(self):
super().tearDown()
gc.collect()
```
> Fix GPU tests (token + single-process)

- tests/test_pipelines.py
Takes 12 seconds to run the whole test class locally. 
All tests are fast integration tests and should yield correct results on CPU.
> [Tests] Add fast pipeline tests

- src/diffusers/models/resnet.py
Per issue #198 , changed variable name from "h" to "hidden_states" in the forward function only. I am happy to change any other variable names, please advise recommended new names.
> Changed variable name from "h" to "hidden_states"

- src/diffusers/configuration_utils.py
- src/diffusers/modeling_utils.py
Currently the expression below will download the main branch of the "CompVis/stable-diffusion-v1-4" model repo. The PR fixes so it correctly downloads the fp16 branch.
`UNet2DConditionModel.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="unet", revision="fp16", torch_dtype=torch.float16, use_auth_token=True)`
> Allow downloading of revisions for models.

- setup.cfg
- src/diffusers/__init__.py
- src/diffusers/models/__init__.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/schedulers/__init__.py
- src/diffusers/utils/__init__.py
Turns out that the F401 issue has been solved quite a while ago, so now it can be fixed with a single config line for every `__init__.py` in the project :slightly_smiling_face: 
Closes #300
> Fix flake8 F401 imported but unused

- tests/test_pipelines.py
- tests/test_training.py
This ensures that:
* Stable Diffusion **fast** tests only run on CPU due to a device-dependent `Generator`
* Training tests only run on CPU, to avoid setting extra determinism environment flags for CUBLAS and CUDA>10.2 which might affect other tests
> Fix nondeterministic tests for GPU runs

- .github/workflows/pr_quality.yml
- .github/workflows/pr_tests.yml
This will drop any running or pending jobs for a PR if a new commit is pushed, freeing the queue for a fresh test run.
This won't affect jobs running on the `main` branch like the slow GPU tests.
> [CI] Cancel pending jobs for PRs on new commits

- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
Fixes **37.** and **38.** of issue #287 
@anton-l would you mind checking it? Thanks!
> [Type hint] Score SDE VE pipeline

- README.md
The code examples use `v1-4`, but the license text was referring to `v1-3`.
> README: stable diffusion version v1-3 -> v1-4

- tests/test_pipelines.py
Adding a bunch of `set_progress_bar_config(disable=None)` to disable tqdm in non-interactive console outputs (i.e. in our CI logs)
*Sorry for merging that with GPU tearDowns, happy to branch out into a different PR if necessary :)
> [CI] try to fix GPU OOMs between tests and excessive tqdm logging

- src/diffusers/models/unet_2d.py
- src/diffusers/models/unet_2d_condition.py
Unfortunately `tile` could not be used either, it's still not compatible with ONNX.
This is the method proposed by @harishanand95 in https://github.com/harishanand95/diffusers/commit/8dd4e822f87e1b4259755a2181218797ceecc410.
Addresses the first (easy) part of #284.
> Use ONNX / Core ML compatible method to broadcast

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- tests/test_pipelines.py
Re-adding @anton-l PRs here: https://github.com/huggingface/diffusers/pull/270/commits/4e48cf40d9acfd3aadddea16b96347b75b044805 with some tests. 
Sorry I accidentally removed the functionality in this PR: https://github.com/huggingface/diffusers/pull/257
> [Img2Img2] Re-add K LMS scheduler

- src/diffusers/models/unet_2d.py
- src/diffusers/models/unet_2d_condition.py
Adds type hint to init in 1. and 2. for issue #287
> [Type Hint] Unet Models

- src/diffusers/schedulers/scheduling_pndm.py
Based on 24, 25, and 26 of issue https://github.com/huggingface/diffusers/issues/287
@anton-l could you check it? 
Thanks :)
> [Type hint] PNDM schedulers

- examples/textual_inversion/textual_inversion.py
Use `tokenizer.add_tokens` method to add the `placeholder_token` in `tokenizer`, this way we can detect if the token is already in the `tokenizer` and raise an error.
> [textual_inversion] use tokenizer.add_tokens to add placeholder_token

- setup.py
- src/diffusers/__init__.py
package `version` on main should have `.dev0` suffix, which is the convention followed in transformers [here](https://github.com/huggingface/transformers/blob/main/setup.py#L403)
Currently, there [are no docs](https://github.com/huggingface/doc-build/tree/main/diffusers) for the `main` version of diffusers because of this convention. This PR should fix the issue
> package `version` on main should have `.dev0` suffix

- tests/test_pipelines.py
* Moving the img2img and inpainting pipelines to fp16
* Updating DDIM reference values (checked with 50 steps and the results look fine, so should be ok with 2 steps too)
TODO: check the DDIM output against the original repo
> [Tests] Fix SD slow tests

- src/diffusers/models/unet_2d_condition.py
As suggested by @bes-dev. According to the documentation this shouldn't take any memory - it just plays with the strides.
> Use `expand` instead of ones to broadcast tensor

- README.md
- src/diffusers/models/attention.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/models/unet_blocks.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- tests/test_pipelines.py
100% of the credit goes to the amazing thread here: https://github.com/basujindal/stable-diffusion/pull/117
By doing:
```py
pip.set_attention_chunk()
```
VRAM can be reduced from 4.6GB to 3.4GB at only 10% slower inference. Try it out:
```python
import torch
from torch import autocast
pipe = StableDiffusionPipeline.from_pretrained(
"CompVis/stable-diffusion-v1-4", 
revision="fp16", 
use_auth_token=True
)
prompt = "a photo of an astronaut riding a horse on mars"
pipe.set_attention_chunk()
with autocast("cuda"):
image = pipe(prompt).images[0] 
```
> Efficient Attention

- examples/textual_inversion/textual_inversion.py
This PR fixes saving the `learned_embeds`, the embeds are detached and put on CPU before saving, this brings down the size to 3.7KB
> [textual-inversion] fix saving embeds

- docs/source/api/pipelines/score_sde_ve.mdx
- docs/source/training/text_inversion.mdx
- examples/textual_inversion/README.md
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
> Score sde ve doc

- docs/source/using-diffusers/conditional_image_generation.mdx
- docs/source/using-diffusers/unconditional_image_generation.mdx
> [Docs] Pipelines for inference

- README.md
**Use GPU and improve code**
Original Code:
```
model_id = "CompVis/ldm-text2im-large-256"
ldm = DiffusionPipeline.from_pretrained(model_id)
prompt = "A painting of a squirrel eating a burger"
images = ldm([prompt], num_inference_steps=50, eta=0.3, guidance_scale=6).images
for idx, image in enumerate(images):
image.save(f"squirrel-{idx}.png")
```
Generates an error (This PR fixes it):
`AttributeError: 'dict' object has no attribute 'images'`
> Improve latent diff example

- examples/textual_inversion/textual_inversion.py
- setup.py
- src/diffusers/dependency_versions_table.py
- src/diffusers/models/unet_blocks.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_sde_vp.py
- src/diffusers/utils/logging.py
> [Black] Update black

- src/diffusers/models/attention.py
This PR use `torch.matmul` for attention comupation instead of `einsum` to allow exporting to coreML
> use torch.matmul instead of einsum in attnetion.

- src/diffusers/models/attention.py
Based on issue #198 
Renamed single-letter variables to more explicit variables.
- q -> query
- k -> key
- v -> value
- b -> batch
- c -> channel
- h -> height
- w -> weight
- x -> hidden_states
- x_in -> residual
@patil-suraj could you check it?
Thanks :)
> Renamed variables from single letter to better naming

- tests/test_modeling_common.py
Small rename. The function is called `test_scheduler_outputs_equivalence` in both the scheduler and the model tests, this change renames the model one.
> Rename test_scheduler_outputs_equivalence in model tests.

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- src/diffusers/schedulers/scheduling_sde_vp.py
Addressed some open TODO's, mentioned in #444.
> Scheduler docs update

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_pndm.py
- tests/test_scheduler.py
Discussing in #444.
More verification to do on the unclear number of iterations vs `num_inference_steps`
Solution inspired by this [discussion](https://github.com/CompVis/stable-diffusion/issues/111) in original SD repo, thanks @ryanirl.
> Fix scheduler inference steps error with power of 3

- tests/test_models_vae.py
Since the generators are seeded on the model's device their output due to the gaussian prior is different.
> Fix vae tests for cpu and gpu

- docs/source/quicktour.mdx
There were a few broken links in [quickstart](https://huggingface.co/docs/diffusers/quicktour) and this is trying to fix those links.
> docs: bocken doc links for relative links

- src/diffusers/models/resnet.py
While investigating performance improvements, the main culprit I found was
`autocast` which actually adds a LOT of copies of tensors a bit everywhere
to cast to `float16`. I added a lot of custom made casts for now in an offbranch.
This PR tries to check 1 of the changes which is this `.float()` cast which break
in `fp16` mode (because the model is in fp16, while the tensor is now in `float`.
> Removing `.float()` (`autocast` in fp16 will discard this (I think)).

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
This affects `add_noise`, so the image to image tasks.
See #358.
> Fix MPS scheduler indexing when using `mps`

- examples/textual_inversion/textual_inversion.py
- examples/unconditional_image_generation/train_unconditional.py
- src/diffusers/__init__.py
- src/diffusers/modeling_flax_utils.py
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
- src/diffusers/schedulers/__init__.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/schedulers/scheduling_karras_ve_flax.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_lms_discrete_flax.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- src/diffusers/schedulers/scheduling_sde_ve_flax.py
- src/diffusers/utils/dummy_flax_objects.py
- tests/test_scheduler.py
- tests/test_training.py
> Karras VE, DDIM and DDPM flax schedulers

- src/diffusers/modeling_flax_utils.py
[Here](https://github.com/mishig25/stable-diffusion-jax/blob/70f384f1dcd6f7ea11a10cd5e48e69722fb38990/stable_diffusion_jax/modeling_unet2d.py#L689-L699) is an example:
```py
class UNet2D(nn.Module, FlaxModelMixin, ConfigMixin):
def init_weights(self, rng: jax.random.PRNGKey) -> FrozenDict:
sample_shape = (1, self.config.sample_size, self.config.sample_size, self.config.in_channels)
sample = jnp.zeros(sample_shape, dtype=jnp.float32)
timestpes = jnp.ones((1,), dtype=jnp.int32)
encoder_hidden_states = jnp.zeros((1, 1, self.config.cross_attention_dim), dtype=jnp.float32)
params_rng, dropout_rng = jax.random.split(rng)
rngs = {"params": params_rng, "dropout": dropout_rng}
return self.init(rngs, sample, timestpes, encoder_hidden_states)["params"]
```
Unlike …
> Add `init_weights` method to `FlaxMixin`

- src/diffusers/utils/import_utils.py
Fix: If user install onnxruntime-gpu, is_onnx_available() will return False.
> Fix is_onnx_available

- src/diffusers/models/__init__.py
- tests/test_layers_utils.py
Added blackbox tests for AttentionBlock and SpatialTransformer - #201. A question - since BasicTransformerBlock, CrossAttention and FeedForward classes are all used within SpatialTransformerBlock, is it required to test them separately? Or testing SpatialTransformer is enough, since any change in them would cause the SpatialTransformerBlockTests to fail.
> [Tests] Test attention.py

- src/diffusers/testing_utils.py
- tests/test_pipelines.py
Solving both the datasets caching and the GPU inconsistency issues
> Finally fix the image-based SD tests

- tests/test_pipelines.py
Follow-up to https://github.com/huggingface/diffusers/pull/509: img2img is still flaky inside the CI container, so I'm opting for MAE there.
> Quick fix for the img2img tests

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
This PR updates `StableDiffusionInpaintPipeline` to accept both `torch.FloatTensor` and `PIL.Image.Image` for `init_image` and `mask_image`.
Fixes #370
> [StableDiffusionInpaintPipeline] accept tensors for init and mask image

- src/diffusers/models/unet_2d_condition_flax.py
Closes #528
If I'm not mistaken, there is no change requireed to [BaseOutput](https://github.com/huggingface/diffusers/blob/43c585111d9b6841236ea13c9763265849d48991/src/diffusers/utils/outputs.py#L41). Could anyone confirm that?
Thanks!
> FlaxUNet2DConditionOutput @flax.struct.dataclass

- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_lms_discrete_flax.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
- src/diffusers/schedulers/scheduling_sde_ve_flax.py
updated schedulers with fixes from issue #479
> [Flax] fix Flax scheduler

- src/diffusers/modeling_flax_utils.py
This makes it possible to save weights and configuration files.
> Flax: ignore dtype for configuration

- src/diffusers/models/resnet.py
Fix `FirUpsample2D._upsample_2d` is not working, it copies the syntax from TensorFlow 😆 
FirUpsample2D is never used with `use_conv=True`, that's why we don't catch it.
> Fix `_upsample_2d`

- tests/test_models_unet.py
This will save ~50sec out of 2m10s on the PR tests.
> [Tests] Mark the ncsnpp model tests as slow

- examples/community/README.md
- examples/community/clip_guided_stable_diffusion.py
This PR adds a community example for doing CLIP guidance with Stable Diffusion.
This implementation is based on the following two amazing repos:
- https://github.com/Jack000/glid-3-xl
- https://github.com/crowsonkb/guided-diffusion
- https://github.dev/crowsonkb/k-diffusion
> add CLIPGuidedStableDiffusion

- src/diffusers/models/attention.py
Fix `CrossAttention._sliced_attention`. See the review comment.
```python
from diffusers.models.attention import CrossAttention
import torch
N, T_query, T_context, query_dim, context_dim, heads, dim_head = (2, 5, 3, 8, 4, 2, 8)
sample = np.random.default_rng().standard_normal(size=(N, T_query, query_dim), dtype=np.float32)
context = np.random.default_rng().standard_normal(size=(N, T_context, context_dim), dtype=np.float32)
pt_sample = torch.tensor(sample, dtype=torch.float32)
pt_context = torch.tensor(context, dtype=torch.float32)
pt_layer = CrossAttention(query_dim=query_dim, context_dim=context_dim, heads=heads, dim_head=dim_head)
pt_layer._slice_size = 1
with torch.no_grad():
pt_output = pt_layer(pt_sample, context=pt_context)
```
which gives
```bash
Traceback (most …
```
> Fix `CrossAttention._sliced_attention`

- src/diffusers/models/vae_flax.py
This PR makes weight names in flax vae consistent with PT to make autoconversion work.
> [FlaxAutoencoderKL] rename weights to align with PT

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- tests/test_pipelines.py
It's been a long time :) 
The changes are mostly ported from the img2img pipeline.
Closes #341
Closes #272
Closes #562
Closes #582
> Add the K-LMS scheduler to the inpainting pipeline + tests

- src/diffusers/pipelines/stable_diffusion/safety_checker_flax.py
This PR updates `FlaxStableDiffusionSafetyChecker` to use `transformers.FlaxPreTrainedModel` for saving and loading to align with PT.
> [flax safety checker] Use `FlaxPreTrainedModel` for saving/loading

- src/diffusers/models/embeddings_flax.py
- src/diffusers/models/unet_2d_condition_flax.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
```python
from diffusers import FlaxStableDiffusionPipeline
from jax import pmap
import jax
import jax.numpy as jnp
import torch
from flax.jax_utils import replicate
from flax.training.common_utils import shard
def safety_checker(images=None, clip_input=None):
return images, False
prng_seed = jax.random.PRNGKey(0)
num_inference_steps = 2
pipeline_torch = StableDiffusionPipeline.from_pretrained("hf-internal-testing/tiny-stable-diffusion-pipe")
pipeline_torch.safety_checker = safety_checker
pipeline, params = FlaxStableDiffusionPipeline.from_pretrained("hf-internal-testing/tiny-stable-diffusion-pipe")
latents_torch = torch.rand(1, 4, pipeline_torch.unet.config.sample_size, pipeline_torch.unet.config.sample_size)
latents = …
```
> [Flax] Fix unet and ddim scheduler

- src/diffusers/pipeline_flax_utils.py
Small fix to be able to test the current pipeline with the dummy checker. The dummy params could not be replicated.
> Fix params replication when using the dummy checker

- src/diffusers/configuration_utils.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
This replaces #581, which was reviewed by @patil-suraj.
> Allow dtype to be specified in Flax pipeline

- src/diffusers/modeling_flax_utils.py
The implementation was mostly copied from `transformers.FlaxPreTrainedModel` & I think there was an error (made PR https://github.com/huggingface/transformers/pull/19133 as well)
cc: @younesbelkada github is not letting me add you as reviwer
```py
from diffusers import FlaxUNet2DConditionModel
model, params = FlaxUNet2DConditionModel.from_pretrained("{PT_PATH}")
model, params = FlaxUNet2DConditionModel.from_pretrained("{PT_PATH}", from_pt=True)
```
> Fix flax from_pretrained pytorch weoghts check

- src/diffusers/modeling_flax_utils.py
- src/diffusers/modeling_utils.py
- src/diffusers/onnx_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/utils/__init__.py
- tests/test_pipelines.py
Moving weights names consts, such as `WEIGHTS_NAME`, to `utils.__init__.py` (common file that is not dependent on pt or flax)
https://github.com/huggingface/diffusers/blob/560e1460c66fac3cea992c72c67228fec7d0bfa2/src/diffusers/utils/__init__.py#L50-L52
The reason being: currently on `main`, when `modeling_flax_utils` import `WEIGHTS_NAME`, it will throw an error if `pytorch` is not available in the env
https://github.com/huggingface/diffusers/blob/d934d3d79519653ad4db5b63a7665c1536b4187c/src/diffusers/modeling_flax_utils.py#L31
And transformers is solving the issue by putting the weight name consts into common utils file [here](https://github.com/huggingface/transformers/blob/0e24548081f8b1c933e3f5f9d8abac8c5a471117/src/transformers/utils/__init__.py#L151-L155)
> Mv weights name consts to diffusers.utils

- src/diffusers/models/vae_flax.py
An attempt to fix https://github.com/huggingface/diffusers/pull/589/files#r975810155, this is probably not the best fix as it will break the consistency assumption between PT and Flax, but will enable consistent parameters naming for all Flax classes
Using `self.dropout = Dropout(self.dropout)` leads to the error
```
self.dropout = nn.Dropout(self.dropout)
flax.errors.SetAttributeInModuleSetupError: Module construction attributes are frozen. (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.SetAttributeInModuleSetupError)
```
cc @patil-suraj @patrickvonplaten @mishig25
Can confirm the PT->Flax equivalency test pass with this PR, which means that the FlaxVAE model is created correctly
> Replace `dropout_prob` by `dropout` in `vae`

- .github/workflows/push_tests.yml
- examples/conftest.py
- examples/test_examples.py
Checks whether the models and model cards get saved after a (successful) training run, nothing more!
To run locally, run `python -m pytest -s -v ./examples` from the root dir.
> Add smoke tests for the training examples

- src/diffusers/configuration_utils.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
This was initially done as part of #583.
The way to set up a custom scheduler, as discussed offline, is:
```Python
scheduler, scheduler_state = FlaxPNDMScheduler.from_config(...)
pipeline, params = FlaxStableDiffusionPipeline.from_pretrained(
model_id,
scheduler=scheduler,
)
params["scheduler"] = scheduler_state
```
> Return Flax scheduler state

- scripts/convert_stable_diffusion_checkpoint_to_onnx.py
- setup.py
- src/diffusers/dependency_versions_table.py
- tests/test_pipelines.py
The 400+ external weight files for the UNet are now collated into one file, making `StableDiffusionOnnxPipeline.from_pretrained` orders of magnitude faster. 
Also removing the conversion step from the ONNX test, speeding up our CI.
> [ONNX] Collate the external weights, speed up loading from the hub

- setup.py
- src/diffusers/dependency_versions_table.py
Context: PIL deprecates PIL.Image.BILINEAR etc. in favor of PIL.Image.Resampling.BILINEAR in 10.0 (currently 9.2):
https://github.com/python-pillow/Pillow/blob/488589b4b69ab7729a059b3f1512398d717d2eda/docs/deprecations.rst#constants
As Pillow 10.0 is not yet officially released, and `transformers` still use `PIL.Image.BILINEAR` for our CLIP dependency (https://github.com/huggingface/transformers/blob/cdaed367b005d2a88a70a1e3c2cc5ec151e68fed/src/transformers/models/clip/feature_extraction_clip.py#L67), I'm capping the PIL version at 10.0 until its release. 
Fixes #586
> Handle the PIL.Image.Resampling deprecation

- src/diffusers/modeling_flax_utils.py
```py
from diffusers import FlaxUNet2DConditionModel
model, params = FlaxUNet2DConditionModel.from_pretrained("/home/mishig/sd-v1-4-flax", subfolder="unet")
```
on `main`, this would raise an error saying that `/home/mishig/sd-v1-4-flax/{FLAX_MODEL} does not exist` because it was not respecting argument `subfolder` when checking locally
Pytorch version already handled it correctly:
https://github.com/huggingface/diffusers/blob/8685699392cfaa79c9c9ab0e16fca49b0f0574f3/src/diffusers/modeling_utils.py#L297-L300
> Make flax from_pretrained work with local subfolder

- src/diffusers/configuration_utils.py
We are not saving `dtype` inside config dict at the moment
> [flax] 'dtype' should not be part of self._internal_dict

- docs/source/api/pipelines/overview.mdx
- docs/source/using-diffusers/configuration.mdx
- docs/source/using-diffusers/unconditional_image_generation.mdx
- src/diffusers/pipelines/README.md
Small readability fixups in `.md*` files.
> docs: `.md` readability fixups

- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/safety_checker.py
readability cleanup -- including var renaming -- in `src/diffusers/pipelines/stable_diffusion/`
`offsensive` -> `offensive`
`Pytorhc` -> `Pytorch`
`safety_cheker_input` -> `safety_checker_input`
`concet_idx` -> `concept_idx`
I was able to go through your `venv` setup and run `make style` and `make quality` (nothing recommended), but still am not 100% sure this will match your CI runner yet. I've been having problems matching my machines black/isort lint with your make script(versions), hopefully there are no linting issues here or moving forward.
-r
> refactor: pipelines readability improvements

- src/diffusers/onnx_utils.py
- src/diffusers/pipeline_utils.py
ONNXRuntime accepts a `session_options` during session creation. It enables a lot of configuration and tuning.
To use it, for example, enable verbose level log
```py
import onnxruntime as ort
ort.set_default_logger_severity(args.log_severity)
sess_options = ort.SessionOptions()
sess_options.log_severity_level = 0  # Verbose 
pipe = StableDiffusionOnnxPipeline.from_pretrained(
"<the-model>",
provider=args.provider,
session_options=sess_options,
)
```
> Allow passing session_options for ORT backend

- src/diffusers/modeling_flax_utils.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/utils/logging.py
Remaining one-off readability fixups in `src/diffusers`
Comments and docstrings
> docs: `src/diffusers` readability improvements

- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/schedulers/scheduling_karras_ve_flax.py
- tests/test_pipelines.py
Closes #590 
- Add missing square into the formula for noise levels in Karras schedulers (torch and flax versions), so that now it's aligned with [the paper](https://arxiv.org/abs/2206.00364) (VE column of Table 1)
- Adjust tests
> Fix formula for noise levels in Karras scheduler and tests

- setup.py
Currently `onnxruntime` can get installed after `onnxruntime-gpu` resulting in a timeout bug for onnx tests
> [CI] Fix onnxruntime installation order

- examples/README.md
the link points to an old location of the train_unconditional.py file
> Fix docs link to train_unconditional.py

- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
- src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
- src/diffusers/pipelines/pndm/pipeline_pndm.py
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stochastic_karras_ve/pipeline_stochastic_karras_ve.py
This was flagged for removal in `0.3.0`, but I'm happy to defer it to a future release if we want to be more cautious.
> Remove deprecated `torch_device` kwarg

- utils/custom_init_isort.py
Readability fixups in `utils/custom_init_isort.py`
- `_import_structu[` -> `_import_structure[`
- `reorderded_blocks` -> `reordered_blocks`
> refactor: `custom_init_isort` readability fixups

- src/diffusers/models/attention.py
```python
hidden_states = hidden_states.permute(0, 2, 3, 1).reshape(batch, height * weight, channel)
```
should be
```python
hidden_states = hidden_states.permute(0, 2, 3, 1).reshape(batch, height * weight, -1)
```
where `-1` is `inner_dim` instead of the channels in the initial `hidden_states`, as it is already projected by
```python
hidden_states = self.proj_in(hidden_states)
```
> Fix `SpatialTransformer`

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_pndm.py
This PR fixes the `add_noise` in DDPM and DDIM schedulers. It makes sure that the alphas are on the same device as the original sample.
> [DDIM, DDPM] fix add_noise

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- src/diffusers/schedulers/scheduling_sde_vp.py
- src/diffusers/schedulers/scheduling_utils.py
> [Pytorch] add dep. warning for pytorch schedulers

- src/diffusers/dependency_versions_table.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- tests/test_scheduler.py
This mostly copies my changes from #637 to fix the LMS inpainting integration tests
> Fix the LMS pytorch regression

- examples/community/clip_guided_stable_diffusion.py
There was a major bug in the `CLIPGuidedStableDiffusion` pipeline. While doing CLIP guidance it was using the uncond embeddings if classifier free guidance was turned on. This PR fixes it. Thanks a lot for spotting this @keturn
Fixes: #596
> [CLIPGuidedStableDiffusion] take the correct text embeddings

- examples/dreambooth/README.md
- examples/dreambooth/requirements.txt
- examples/textual_inversion/README.md
- examples/textual_inversion/requirements.txt
This PR updates the minimum version of `transformers` to `4.21.0` as the `subfolder` argument is not supported in previous versions.
Fixes #579
> [examples] update transfomers version 

- tests/test_models_unet.py
This PR lowers the tolerance for gradient checkpointing test.
> [gradient checkpointing] lower tolerance for test

- src/diffusers/modeling_flax_utils.py
Originally removed in 73e0bc692c5761e55faff39c80a26d7a3cfc748c.
Surfaced by @ryanrussell in https://github.com/huggingface/diffusers/pull/629/files#r979252084
> Flax `from_pretrained`: clean up `mismatched_keys`.

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_lms_discrete_flax.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
Hello
I was going through the code repo and I observed how the `self.betas` is being assigned. I don't know if what I observed is correct, so I wanted to raise this PR to clarify this.
Without the changes made in this PR, it seems the following code is not useful 
```
if trained_betas is not None:
self.betas = np.asarray(trained_betas)
```
This is because `self.betas` is assigned again as part of the if-statement below. And if `beta_schedule` doesn't exist then an error is raised. So it doesn't matter if `self.betas` is assigned to `trained_betas`.
As a note, certain schedulers such as [FlaxDDIMScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddim_flax.py#L124), [DDPMScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers …
> `trained_betas` ignored in some schedulers

- src/diffusers/models/resnet.py
Based on the issue https://github.com/huggingface/diffusers/issues/198
Renamed x -> hidden_states in resnet.py
@patil-suraj could you check it?
Thanks :)
> Renamed x -> hidden_states in resnet.py

- docs/source/optimization/fp16.mdx
Table currently looks like this
> [docs] fix table in fp16.mdx

- src/diffusers/models/attention.py
Fixes slow tests after the PR https://github.com/huggingface/diffusers/pull/371
> Fix slow tests

- examples/dreambooth/train_dreambooth.py
Fix gradient clipping when doing gradient accumulation. The gradients needs to clipped after they are synchronized when doing accumulation. cf https://github.com/huggingface/accelerate/issues/641#issuecomment-1219910080
fixes #668
Although not sure why it only got triggered only in half-precision.
> [dreambooth] fix applying clip_grad_norm_

- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_karras_ve_flax.py
- src/diffusers/schedulers/scheduling_lms_discrete_flax.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
- src/diffusers/schedulers/scheduling_sde_ve_flax.py
There was a discussion in #583 and/or Slack about sending the latents shape to the Flax scheduler, because `PNDM` requires it to properly initialize the state. We agreed to send the shape to all of them (until we maybe find a better solution), but I only ever added it to PNDM. Therefore, the stable diffusion pipeline was failing with other schedulers. For example, with the default weights that were uploaded to the repo for testing.
> Flax: add shape argument to `set_timesteps`

- src/diffusers/__init__.py
- src/diffusers/modeling_flax_utils.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/schedulers/__init__.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_karras_ve_flax.py
- src/diffusers/schedulers/scheduling_lms_discrete_flax.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
- src/diffusers/schedulers/scheduling_sde_ve_flax.py
- src/diffusers/schedulers/scheduling_utils.py
- src/diffusers/schedulers/scheduling_utils_flax.py
> Fix import with Flax but without PyTorch

- src/diffusers/pipelines/stable_diffusion/safety_checker.py
Let's try to not force high PyTorch versions if we can avoid it.
Inference mode was only introduced in PyTorch 1.9. The safety checker is used in many different other libraries (mainly `ComVis/stable-diffusion`) and we don't want to force these libraries to use higher PyTorch versions.
cc @anton-l
> [Support PyTorch 1.8] Remove inference mode

- .github/workflows/pr_tests.yml
- .github/workflows/push_tests.yml
- setup.py
- src/diffusers/dependency_versions_table.py
- tests/test_pipelines.py
* Use a local Hub cache instead of NFS
* Less ONNX pipeline steps, use CPU runtime (needs a custom docker image for CUDA to work)
> [CI] Speed up slow tests

- examples/conftest.py
- examples/test_examples.py
- src/diffusers/dependency_versions_table.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- src/diffusers/schedulers/scheduling_sde_vp.py
- src/diffusers/schedulers/scheduling_utils.py
- src/diffusers/utils/__init__.py
- src/diffusers/utils/deprecation_utils.py
- src/diffusers/utils/outputs.py
- src/diffusers/utils/testing_utils.py
- tests/conftest.py
- tests/test_layers_utils.py
- tests/test_modeling_common.py
- tests/test_models_unet.py
- tests/test_models_vae.py
- tests/test_models_vq.py
- tests/test_pipelines.py
- tests/test_training.py
- tests/test_utils.py
We are introducing multiple deprecation cycles already and currently are missing structure on how to handle this exactly and by adding `**kwargs` to the scheduler config init we have lost functionality. More specifically:
- 1. We do not keep track when functionality should be removed as we forget to remove the deprecation cycle and the functionality (this happened twice now)
- 2. Right now when you pass a incorrect argument, e.g. `PNDMScheduler(num_inference_steps=5)` nothing happens because it's swallowed by **kwargs. **However** we should, just as before https://github.com/huggingface/diffusers/pull/651 throw a TypeError in this case.
=> This PR solves this by introducing a `deprecate` function (which should be mainly used by maintainers) that automatically forces us to remove …
> [Utils] Add deprecate function and move testing_utils under utils

- examples/unconditional_image_generation/train_unconditional.py
Fix gradient clipping when doing gradient accumulation. The gradients needs to clipped after they are synchronized when doing accumulation. cf huggingface/accelerate#641 (comment)
fixes #499
Although not sure why it only got triggered only in half-precision.
> [train_unconditional] fix applying clip_grad_norm_

- examples/dreambooth/train_dreambooth.py
Literally created 2 lines before. DRY etc
> [dreambooth] Using already created `Path` in dataset

- scripts/convert_original_stable_diffusion_to_diffusers.py
A stable diffusion checkpoint might have a CLIPTextModel with trained weights (this is how textual inversion works).
This change copies over the weights from the given checkpoint instead of using the default "openai/clip-vit-large-patch14" weights so that a model trained with textual inversion can be converted for use with diffusers library too.
> Include CLIPTextModel parameters in conversion

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
The original lines cause the following error for tensors.
```
At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 
```
The same operation is done here.
https://github.com/huggingface/diffusers/blob/f1484b81b0b763aa010fd2083df933305afb1812/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L253-L258
(Probably related to #551 )
> Avoid negative strides for tensors

- .github/workflows/push_tests.yml
- src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_onnx.py
- src/diffusers/pipelines/stochastic_karras_ve/pipeline_stochastic_karras_ve.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_karras_ve.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_sde_ve.py
- tests/test_scheduler.py
This schedulers API redesign addresses concerns raised in #336 and starts to make the schedulers interchangeable without making scheduler class-dependent customizations to pipelines.
1) Now every scheduler contains an `init_noise_sigma` parameter to scale the normal distribution of the initial noise. While it is just `1.0` for DDPM, DDIM and PNDM, it *is* customized for the VE and K-LMS schedulers.
Example usage:
```python
sample = torch.randn(*shape, generator=generator) * self.scheduler.init_noise_sigma
```
2) Every scheduler needs to implement the `scale_model_input(sample, timestep)` (even if it just returns the `sample`) that scales the denoising model's input based on the current `timestep`. The method should be called before every `model()` call.
Example usage:
```python
sample = …
```
> [Scheduler design] The pragmatic approach

- README.md
- docs/source/api/pipelines/overview.mdx
- docs/source/optimization/fp16.mdx
- docs/source/optimization/mps.mdx
- docs/source/optimization/onnx.mdx
- docs/source/using-diffusers/img2img.mdx
- docs/source/using-diffusers/inpaint.mdx
- examples/unconditional_image_generation/train_unconditional.py
- scripts/convert_stable_diffusion_checkpoint_to_onnx.py
- setup.py
- src/diffusers/configuration_utils.py
- src/diffusers/dependency_versions_table.py
- src/diffusers/dynamic_modules_utils.py
- src/diffusers/modeling_flax_utils.py
- src/diffusers/modeling_utils.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/README.md
- src/diffusers/pipelines/stable_diffusion/README.md
- tests/test_pipelines.py
> No more use_auth_token=True

- src/diffusers/dynamic_modules_utils.py
This was part of #733, I was too slow to review :)
> Replace messages that have empty backquotes

- README.md
- docs/source/api/pipelines/overview.mdx
- docs/source/optimization/fp16.mdx
- docs/source/training/text_inversion.mdx
- docs/source/using-diffusers/img2img.mdx
- docs/source/using-diffusers/inpaint.mdx
- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
- examples/textual_inversion/README.md
Removes the use of autocast whenever we are already in fp16 as it slows down computation and doesn't seem to improve results really
> [Docs] Advertise fp16 instead of autocast

- examples/test_examples.py
The `test_textual_inversion` test was failing because it was passing the `--use_auth_token` arg, which is now removed.
> remove use_auth_token from for TI test

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- tests/test_pipelines.py
To generate multiple images for a prompt currently we need to repeat the prompts before calling the pipeline. 
```
pipe = StableDiffusionPipeline.from_pretrained(
"CompVis/stable-diffusion-v1-4", 
revision="fp16", 
)
prompt = "a photo of an astronaut riding a horse on mars"
images = pipe([prompt] * 2).images
```
Because of this the text embeddings and uncond embeddings are computed multiple times for the same prompt. 
This PR adds `num_images_per_prompt` argument to stable diffusion pipelines to allow returning multiple images per prompt without repeating them. With this the text embeddings and uncond embeddings for each prompt are computed once and repeated according to the value of `num_images_per_prompt`.
```
prompt = "a photo of an …
```
> allow multiple generations per prompt

- src/diffusers/schedulers/scheduling_lms_discrete.py
Now the legacy pipelines that support LMS won't break because of the integer timesteps :) 
For instance: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/CLIP_Guided_Stable_diffusion_with_diffusers.ipynb
> Add back-compatibility to LMS timesteps

- src/diffusers/pipeline_utils.py
- tests/test_pipelines.py
Since our default now is to recommend `fp16` models instead of using `autocast`, the cryptic CPU+fp16 errors might become more frequent among unsuspecting users:
`RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`
This PR adds an error when `pipe.to("cpu")` is used with an `fp16` model:
```
ValueError: Cannot use `pipeline.to('cpu')` with a pipeline loaded with `torch_dtype=torch.float16` due to the lack of support for `float16` operations on CPU in PyTorch.
```
> Raise an error when moving an fp16 pipeline to CPU

- scripts/convert_stable_diffusion_checkpoint_to_onnx.py
The opset argument should be an `int` but was set as a `str`. This caused torch.onnx.export to fail when users specified a non-default opset version.
> Fix ONNX conversion script opset argument type

- tests/test_pipelines.py
This ensures that the latents stay somewhat consistent as more new changes are introduced into the library. All four tests passed on my side, but it would be great to have someone else to double-confirm.
This PR builds upon the callback function feature in the Stable Diffusion pipelines and, in a way, serves as an improvement to PR #521. This new PR was opened following the request by @patrickvonplaten in [this comment](https://github.com/huggingface/diffusers/pull/697#issuecomment-1267614344).
Signed-off-by: James R T <jamestiotio@gmail.com>
> Add final latent slice checks to SD pipeline intermediate state tests

- src/diffusers/schedulers/scheduling_ddim.py
Otherwise, it crashes when eta > 0 with float16.
Follow-up to #511.
> fix(DDIM scheduler): use correct dtype for noise

- tests/test_models_unet.py
@patil-suraj - I updated the test a bit and now everything seems to work just fine
> Fix gradient checkpointing test

- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
Add instructions on how to enable DeepSpeed in DreamBooth example to allow training on under 8 GB VRAM. I was able to train a working network using this on 8 GB VRAM GPU.
It did not work out of the box with fp16 mixed precision and I had to add some explicit casts to make it run. Without them it raises Exception: `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same`.
> DreamBooth DeepSpeed support for under 8 GB VRAM training

- src/diffusers/models/resnet.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/safety_checker.py
Currently stable diffusion (or diffusers in general) doesn't work with `bf16` as  nearest upsampling in torch is not supported in `bf16`. 
Minimal code to reproduce:
```python
import torch
import torch.nn.functional as F
image = torch.randn(1, 4, 32, 32).to(device="cuda", dtype=torch.bfloat16)
out = F.interpolate(image, size=(64, 64), mode="nearest")
```
Addinatly, in `pipelines` we need to cast the images to `fp32` as `bf16` is not yet supported in `numpy`.
This is a draft PR to enable `bf16` training/inference for stable diffusion by casting `input` to `fp32` where `bf16` is not supported.
Not sure if this is the right way, curious to you hear your feedback @patrickvonplaten @NouamaneTazi 
fixes #771
> support bf16 for stable diffusion

- src/diffusers/models/vae_flax.py
- src/diffusers/utils/testing_utils.py
- tests/test_modeling_common_flax.py
- tests/test_models_vae_flax.py
Addresses #621
Trickle down `norm_num_groups` and use it to replace hardcoded values in `GroupNorm`.
This PR makes the following changes:
- Replaces hardcoded value of `num_groups` param passed to `GroupNorm`
- Adds a param to specify number of norm groups to the following classes:
- `FlaxResnetBlock2D`
- `FlaxAttentionBlock`
- `FlaxDownEncoderBlock2D`
- `FlaxUpDecoderBlock2D`
- `FlaxUNetMidBlock2D`
- Set a default value if param is `None`
- Creates `FlaxModelTesterMixin` class with `test_output` and `test_forward_with_norm_groups` tests
- Creates `FlaxAutoencoderKLTests` class and sets up tests for model
- Creates `require_flax` testing util decorator
- Fixes typos:
- Rename class `FlaxUpEncoderBlock2D` => `FlaxUpDecoderBlock2D`
- Fix docstring for param `add_downsample` => …
> Flax: Trickle down `norm_num_groups`

- docs/source/optimization/mps.mdx
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
Fixes #760.
`repeat_interleave` was slowing things down, but not causing wrong outputs. Something between `v0.3.0` and `v0.4.0` (possibly some of the optimization changes) broke generation in `mps`. Fortunately, the latest `mps` version of PyTorch nightly (released today) works fine 😅, so I'm updating the documentation to recommend it.
> `mps`: Alternative implementation for `repeat_interleave`

- MANIFEST.in
- README.md
1. Add `LICENSE` to the pip wheel (thanks to the conda CI for picking up on that https://github.com/conda-forge/diffusers-feedstock/pull/12)
2. Use an absolute url for the diffusers image to make it show up on pypi: https://pypi.org/project/diffusers/
> Minor package fixes

- src/diffusers/pipeline_utils.py
- src/diffusers/utils/dummy_flax_and_transformers_objects.py
- src/diffusers/utils/dummy_flax_objects.py
- src/diffusers/utils/dummy_pt_objects.py
- src/diffusers/utils/dummy_torch_and_scipy_objects.py
- src/diffusers/utils/dummy_torch_and_transformers_and_onnx_objects.py
- src/diffusers/utils/dummy_torch_and_transformers_objects.py
- tests/test_pipelines.py
- utils/check_dummies.py
This PR adds `from_config` and `from_pretrained` dummy class methods to all dummy classes.
Running:
```
pytest -sv tests/test_pipelines.py::PipelineFastTests::test_stable_diffusion_k_lms
```
without `scipy` installed now yields:
```
E           ImportError: 
E           LMSDiscreteScheduler requires the scipy library but it was not found in your environment. You can install it with pip: `pip install
E           scipy`
```
as expected. Thanks for flagging @pcuenca
> [Dummy imports] Better error message

- src/diffusers/modeling_flax_utils.py
- src/diffusers/modeling_utils.py
- src/diffusers/pipeline_utils.py
This will let us know which versions and pipelines are used the most, which in turn informs the deprecation cycles and maintenance priority. Kudos to @LysandreJik for the tip!
> Add diffusers version and pipeline class to the Hub UA

- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_pndm_flax.py
Align Flax scheduler API with PyTorch
> update flax scheduler API

- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- tests/test_pipelines.py
This allows people to disable the safety checker. **Note**: This is never recommended in the eyes of the `diffusers` team, but we also don't want people to have to fork the repository in order to disable the safety checker if they deem it necessary in their eyes. 
For more information, please have a look at: https://github.com/huggingface/diffusers/pull/254#issuecomment-1275670003 .
The safety checker can be disabled by doing:
```python
pipeline = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", safety_checker=None)
```
> Give more customizable options for safety checker

- examples/community/README.md
- examples/community/one_step_unet.py
> [Community] One step unet

- examples/community/README.md
- examples/community/interpolate_stable_diffusion.py
Adds `interpolate_stable_diffusion.py`, which is a pipeline that lets you generate images as you interpolate between different prompts/seeds.
Its `__call__` fn is the same as `StableDiffusionPipeline`, but with the added `text_embeddings` kwarg. The `walk` function is where the logic happens. Fine with renaming these if need be so that `walk` becomes `__call__`. 
Here's how I have been using it (from within `examples/community` dir)
```python
from interpolate_stable_diffusion import StableDiffusionWalkPipeline
import torch
pipe = StableDiffusionWalkPipeline.from_pretrained(
"CompVis/stable-diffusion-v1-4",
revision='fp16',
safety_checker=None,  # Very important for videos...lots of false positives while interpolating
).to('cuda')
frame_filepaths = pipe.walk( …
```
> Add Stable Diffusion Interpolation Example

- examples/unconditional_image_generation/train_unconditional.py
This resulted in repos with no model files such as: https://huggingface.co/pcuenq/ddpm-ema-faces-64-50/tree/main
> Fix training push_to_hub (unconditional image generation): models were not saved before pushing to hub

- examples/community/interpolate_stable_diffusion.py
Frame filename right now is `frame_{frame_idx}.png`, which leads to frames like `frame_1.png`, `frame_10.png`, etc. This is an issue if you end up wanting to ffmpeg them together later. 
This pr updates to do `frame_{frame_idx:06d}.png` so frame filenames will be friendlier with glob patterns, keeping files sorted: `frame_000001.png`, `frame_000010.png`, etc.
> Rename frame filename in interpolation community example

- tests/test_models_vae.py
I broke it trying to fix a failing `mps` test.
> Fix autoencoder test

- src/diffusers/__init__.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
- src/diffusers/utils/dummy_torch_and_transformers_and_onnx_objects.py
- tests/test_pipelines.py
This makes the class naming consistent with other framework-specific classes, e.g. `FlaxStableDiffusionPipeline`
`OnnxStableDiffusionImg2ImgPipeline` and `OnnxStableDiffusionInpaintPipeline` will also follow from https://github.com/huggingface/diffusers/pull/552/
> Rename StableDiffusionOnnxPipeline -> OnnxStableDiffusionPipeline

- src/diffusers/schedulers/scheduling_ddim.py
Same fix as already in pndm - https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_pndm.py#L190
> Fix DDIM on Windows not using int64 for timesteps

- .github/workflows/push_tests.yml
- scripts/convert_stable_diffusion_checkpoint_to_onnx.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
- tests/test_pipelines.py
This is an intermediate fix, ONNX reproducibility issues need to be investigated further later on.
Notes: disabling onnxruntime optimizations, setting the onnx seed and enabling onnxruntime determinism didn't affect the test, so that wasn't it.
> Improve ONNX img2img numpy handling, temporarily fix the tests

- scripts/convert_stable_diffusion_checkpoint_to_onnx.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
- src/diffusers/utils/dummy_torch_and_transformers_objects.py
- tests/test_pipelines.py
This replaces the unsupervised pipeline with a pipeline based on a model finetuned for inpainting
> ONNX supervised inpainting

- examples/community/README.md
- examples/community/speech_to_image_diffusion.py
Solves [Community Pipeline] Speech to Image #871
> [Examples] add speech to image pipeline example

- examples/dreambooth/README.md
- examples/dreambooth/requirements.txt
- examples/dreambooth/train_dreambooth.py
> [dreambooth] dont use safety check when generating prior images

- examples/dreambooth/train_dreambooth.py
> Dreambooth class image generation: using unique names to avoid overwriting existing image

- tests/test_pipelines.py
Handle device and use `StableDiffusionInpaintPipelineLegacy` for `test_components`
> fix test_components

- src/diffusers/utils/testing_utils.py
Fixes #892
`diffusers` 0.4.0+ currently assumes that torch >= 1.12.0 has MPS registered as a backend, but this does not seem to be the case in nvidia's NGC pytorch containers.
This PR makes the MPS availability check a little more robust.
P.S. Wasn't sure how/if to add a test for this. If a maintainer could point me in the right direction I'd be happy to update the PR.
> Fix Compatibility with Nvidia NGC Containers

- src/diffusers/modeling_flax_utils.py
Remove the warning in `FlaxModelMixin` when weights are in `fp16` or `bf16`, to improve the UX a bit.
> [Flax] dont warn for bf16 weights

- tests/test_models_vae.py
- tests/test_pipelines.py
fixed vae test as well as torch.generator() call.
> [MPS] fix mps failing tests

- src/diffusers/utils/testing_utils.py
- tests/pipelines/ddim/test_ddim.py
- tests/pipelines/ddpm/test_ddpm.py
- tests/pipelines/karras_ve/test_karras_ve.py
- tests/pipelines/latent_diffusion/test_latent_diffusion.py
- tests/pipelines/latent_diffusion/test_latent_diffusion_uncond.py
- tests/pipelines/pndm/test_pndm.py
- tests/pipelines/score_sde_ve/test_score_sde_ve.py
- tests/pipelines/stable_diffusion/test_onnx_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_onnx_stable_diffusion_img2img.py
- tests/pipelines/stable_diffusion/test_onnx_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint_legacy.py
- tests/test_pipelines.py
- tests/test_pipelines_common.py
- tests/test_pipelines_flax.py
- tests/test_pipelines_onnx_common.py
This PR sorts the pipeline-specific tests from `test_pipelines.py` into their individual directories.
Partially solves #913
Note: this doesn't touch the flax tests yet
> Reorganize pipeline tests

- .github/workflows/pr_tests.yml
- tests/pipelines/ddim/test_ddim.py
`DDIMPipelineFastTests.test_inference` fails the first time it's launched with `pytest -n 4`, but passes the second time. This PR makes sure that the tests run in a single process
> [Tests] Fix `mps` reproducibility issue when running with pytest-xdist

- scripts/convert_stable_diffusion_checkpoint_to_onnx.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
Hello. I add support for  half-precision  and fix bugs in onnx pipelines. @anton-l could you take a look here?
> [Onnx] support half-precision and fix bugs for onnx pipelines

- src/diffusers/models/unet_1d.py
- src/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py
- tests/pipelines/dance_diffusion/test_dance_diffusion.py
> [Dance Diffusion] FP16

- examples/dreambooth/train_dreambooth.py
This simple change enables the DataLoader to prefetch the next data async. More info in the [docs](https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading).
This resulted in a 35% speedup for me and utilizes the GPU power better (as the data loading is not blocking the GPU):
*(green = new, blue = old)*
The same can probably also be applied to all the other DataLoaders but I do not have the time to test them.
> Enable multi-process DataLoader for dreambooth

- examples/dreambooth/train_dreambooth.py
This change enables dreambooth training to be called by an external script. This makes it much easier to write wrappers around training for GUI's or batch processing scripts. This change does not break existing usage.
> Small modification to enable usage by external scripts

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/test_pipelines.py
The tests:
```
FAILED tests/test_pipelines.py::PipelineSlowTests::test_stable_diffusion_accelerate_load_reduces_memory_footprint
FAILED tests/test_pipelines.py::PipelineSlowTests::test_stable_diffusion_pipeline_with_unet_on_gpu_only
```
are currently failing on main. 
Also this PR renames:
`cuda_with_minimal_gpu_usage` to `enable_sequential_cpu_offload` as it's a more fitting name and disentangled `enable_attention_slicing` from `cpu_offload`
Related original PR: https://github.com/huggingface/diffusers/pull/850
@piEsposito does this work for you?
> [Accelerate model loading] Fix meta device and super low memory usage

- examples/text_to_image/README.md
- examples/text_to_image/train_text_to_image_flax.py
- Add Flax example for finetuning Stable Diffusion. 
- Ran well on Tesla A100 (40GB) with max batch size = 3. 
- EMA is not added because my 1-line tree_map implementation for EMA make training much slower, and it did not show a visible improvement on the result.  
How to run (76% faster than PyTorch example with same args on Tesla A100)
```
export MODEL_NAME="duongna/stable-diffusion-v1-4-flax"
export dataset_name="lambdalabs/pokemon-blip-captions"
python train_text_to_image_flax.py \
--pretrained_model_name_or_path=$MODEL_NAME \
--dataset_name=$dataset_name \
--resolution=512 --center_crop --random_flip \
--max_train_steps=15000 \
--learning_rate=1e-05 \
--max_grad_norm=1 \
--output_dir="sd-pokemon-model" 
```
Prompt: `robotic cat with wings`
cc @patrickvonplaten …
> [Flax] Add finetune Stable Diffusion

- docs/source/optimization/fp16.mdx
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
Changes:
- Adds docstring to `StableDiffusionPipeline.enable_sequential_cpu_offload`
- Adds docs to StableDiffusionPipeline.enable_sequential_cpu_offload on https://github.com/huggingface/diffusers/blob/main/docs/source/optimization/fp16.mdx
@patrickvonplaten as discussed in https://github.com/huggingface/diffusers/pull/850#issuecomment-1292320430 and here https://github.com/huggingface/diffusers/pull/850#issuecomment-1293254974 , I've just documented the sequential CPU offloading feature for Stable Diffusion Pipelines.
> Document sequential CPU offload method on Stable Diffusion pipeline

- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
This fixes the error when trying to convert single-channel arrays to PIL
```python
images = np.random.rand(2, 32, 32, 1)
numpy_to_pil(images)  
```
Before: 
> TypeError: Cannot handle this data type: (1, 1, 1), |u1
After: 
> [<PIL.Image.Image image mode=L size=32x32 at 0x7FCF8F8FE690>,
> <PIL.Image.Image image mode=L size=32x32 at 0x7FCF8F8FE6D0>]
Closes #488
> Support grayscale images in `numpy_to_pil`

- src/diffusers/models/resnet.py
Fixes https://github.com/huggingface/diffusers/issues/984.
It seems that `F.interpolate(hidden_states, scale_factor=2.0, mode="nearest")` breaks for batch sizes > 64 when `hidden_states` uses channels last format. See https://github.com/pytorch/pytorch/issues/81665 and https://github.com/huggingface/diffusers/issues/984
This PR proposes to force a contiguous format for hidden states when `bsz > 64`. Credits to @pcuenca for the find.
The following now works (after applying the [memory efficient PR](https://github.com/huggingface/diffusers/pull/532) + this PR)
```python
pipe = StableDiffusionPipeline.from_pretrained(
"CompVis/stable-diffusion-v1-4", 
use_auth_token=True,
revision="fp16",
).to("cuda")
batch_size = 32
with torch.inference_mode():
image = …
```
> fix `F.interpolate()` for large batch sizes

- examples/community/README.md
- examples/community/seed_resize_stable_diffusion.py
Part of https://github.com/huggingface/diffusers/issues/875 and bigger story https://github.com/huggingface/diffusers/issues/841 
The code is 1:1 with core stable_diffusion pipeline, the only difference starting around line [265](https://github.com/huggingface/diffusers/compare/main...MarkRich:add-seed-resizing-to-community-pipelines?expand=1#diff-ac7c362a216180c8d26d7a11ecee1ed81ca1de9eb8bb472c7f5c16c00cc7909aR265) in the pipeline file. 
In order to achieve seed stability, we simply generate the original 512 x 512 seed, generate a second seed of arbitrary size, and then paste the first seed into the second seed. This yields greater stability.
As an example, generating: "A painting of a futuristic cop", we get
**Reference image, 512 x 512:**
**Stable seed image, 512 x 592:**
**Non stable …
> Add seed resizing to community pipelines

- .github/workflows/push_tests.yml
Otherwise the cuda versions of torch and torchvision mismatch, and examples tests fail. We were requesting cuda 11.6 for PyTorch, and the default torchvision (via setup.py).
Another option would be to include torchvision in the same pip install line as torch.
> Tests: upgrade PyTorch cuda to 11.7 to fix examples tests.

- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/safety_checker_flax.py
Currently a part of the safety checker is outside the model forward pass and is run separately without jitting. This PR merges it into the model call by vectorizing the relevant loops.
See https://github.com/huggingface/diffusers/pull/558#discussion_r1004294795.
I tested that the concept scores before and after this change are the same, and that 2 unsafe among 4 total images are still properly detected.
> Move safety detection to model call in Flax safety checker

- .github/workflows/pr_tests.yml
- .github/workflows/push_tests.yml
- src/diffusers/hub_utils.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/utils/import_utils.py
* Makes sure that the pipeline class takes priority over `_class_name` (so that we count `StableDiffusionImg2Img` too)
* Adds UA logging to the Flax pipeline
* Adds a flag for CI requests to filter them out
* Formats the UA string similarly to `transformers` to fix a weird additional `none/None` inserted into the request
> Fix pipelines user_agent, ignore CI requests

- utils/stale.py
Let's close issues after too much inactivity - otherwise we won't be able to handle new issues => too much activity on the repo
> [GitBot] Automatically close issues after inactivitiy

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
Otherwise an exception is raised.
> Allow `safety_checker` to be `None` when using CPU offload

- src/diffusers/configuration_utils.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
> [Tests] Fix slow tests

- src/diffusers/models/unet_2d_blocks.py
Very minor change but the `downsample_padding` parameter does not seem to be used in `CrossAttnUpBlock2D` (or by any up block for that matter) so removing it.
> Remove some unused parameter in CrossAttnUpBlock2D

- docs/source/optimization/fp16.mdx
- src/diffusers/models/attention.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/utils/import_utils.py
While stable diffusion democratized the access to text to image generative models, it can still be relatively long to generate an image on consumer GPUs. The GPU memory requirements are also hindering the use of diffusion on small GPUs. 
Recent work on optimizing the bandwitdh in the attention block have generated huge speed ups and gains in GPU memory usage. The most recent being Flash Attention (from @tridao, [code](https://github.com/HazyResearch/flash-attention), [paper](https://arxiv.org/pdf/2205.14135.pdf)) . 
In this PR we use the MemoryEfficientAttention implementation from [xformers](https://github.com/facebookresearch/xformers) (cc. @fmassa, @danthe3rd, @blefaudeux) to both speedup the cross-attention speed and decrease its GPU memory requirements. 
The memory efficient …
> Up to 2x speedup on GPUs using memory efficient attention

- docs/source/api/pipelines/stable_diffusion.mdx
- docs/source/api/schedulers.mdx
This PR
- Adds the new euler schedulers in the doc.
- Adds a section in stable diffusion doc to explain how to use different schedulers wih the pipeline using the new API.
> [docs] add euler scheduler in docs, how to use differnet schedulers 

- examples/dreambooth/README.md
> fix typo in examples dreambooth README.md

- src/diffusers/models/attention.py
fix a typo of `SpatialTransformer` in `models/attention.py`.
weight -> width
> Fix a small typo of a variable name

- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/schedulers/scheduling_ddim.py
- tests/test_pipelines.py
Closes #553 
DDIM and DDPM pipelines are equivalent only if `DDIM` scheduler is called with `use_clipped_model_output=True`. Currently it's not possible to pass this argument from the pipeline, and so `test_ddpm_ddim_equality_batched` was [failing](https://github.com/huggingface/diffusers/blob/95414bd6bf9bb34a312a7c55f10ba9b379f33890/tests/test_pipelines.py#L471). The unbatched version `test_ddpm_ddim_equality` was also failing if one changed the random seed (e.g. to 4), as described in the issue.
This PR:
- allows passing `use_clipped_model_output` from DDIM pipeline to the scheduler
- calls DDIM with `use_clipped_model_output=True` in `test_ddpm_ddim_equality_batched` and `test_ddpm_ddim_equality`
As a result, both tests are passing  (each runs for 2 values of the seed)
> Fix tests for equivalence of DDIM and DDPM pipelines

- examples/dreambooth/train_dreambooth.py
Fix padding in dreambooth as it is done in inference.
https://github.com/huggingface/diffusers/blob/de00c632174704d6d92405120f171e58b38e0ee8/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L231-L236
- [Reference by kohya_ss](https://note.com/kohya_ss/n/nee3ed1649fb6) (in Japanese):
- They say this is one of the difference between https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/ and https://github.com/huggingface/diffusers and padding like this PR made better results
> Fix padding in dreambooth

- examples/unconditional_image_generation/train_unconditional.py
- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
changed training example to add option to train model that predicts x0 (instead of eps), changed DDPM pipeline accordingly
> Training to predict x0 in training example

- .github/workflows/pr_tests.yml
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/test_config.py
Since PRs from forks can't access private models, we need to replace them with public dummy ones
> Fix hub-dependent tests for PRs

- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
This fixes an error when trying to save SD pipelines with `safety_checker=None`
> Allow saving `None` pipeline components

- src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
Use the correct device when using `randn` in Euler step cf https://github.com/huggingface/diffusers/pull/1019#issuecomment-1302243448
Thanks a lot for catching this @andrea-gatto
> handle device for randn in euler step

- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
The following tests have had their precision increased and they all pass by downloading numpy files from a dataset I made myself: 
```bash
pytest tests\pipelines\stable_diffusion\test_stable_diffusion.py -k test_stable_diffusion_text2img_pipeline_default
pytest tests\pipelines\stable_diffusion\test_stable_diffusion_img2img.py -k test_stable_diffusion_img2img_pipeline_k_lms
pytest tests\pipelines\stable_diffusion\test_stable_diffusion_img2img.py -k test_stable_diffusion_img2img_pipeline_default
```
I have added two PRs to add the exact same files to the testing repo [here](https://huggingface.co/datasets/hf-internal-testing/diffusers-images/discussions/5) and [here](https://huggingface.co/datasets/hf-internal-testing/diffusers-images/discussions/4).
This is a follow on from PR #1052
> Test precision increases 

- examples/community/lpw_stable_diffusion.py
- examples/community/lpw_stable_diffusion_onnx.py
Add xformers_memory_efficient_attention and sequential_cpu_offload to lpw_stable_diffusion pipeline.
> [Community Pipeline] lpw_stable_diffusion: add xformers_memory_efficient_attention and sequential_cpu_offload 

- src/diffusers/models/embeddings_flax.py
This was assumed in the previous implementation, but now (0b61cea347e9b464fb03506cb78a49d38e1c74ee) the default is the opposite.
Fixes #1145.
> Flax: Flip sin to cos in time embeddings

- src/diffusers/models/attention.py
Cast `hidden_states` returned by `memory_efficient_attention_xformers` to the `dtype` of input, as it seems some versions of `xformers` return output in `fp32`
Fixes #1195
> handle dtype xformers attention 

- tests/test_pipelines_flax.py
This makes it possible to test on CPU/GPU. However, expected slices are only checked when there are 8 devices.
> Flax tests: don't hardcode number of devices

- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/schedulers/scheduling_ddpm.py
Trying to keep this a small PR that just adds necessary changes in DDPM scheduler to support v diffusion. I have a supporting example script using the butterflies dataset I can add either here or as a separate PR
> DDPM changes to support v diffusion

- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
This PR makes sure that for PyTorch and ONNX there exists only one text encoding function that each inherits from the original text2image pipeline respectively.
> Factor out encode text with Copied from

- .github/workflows/push_tests.yml
- examples/unconditional_image_generation/train_unconditional.py
- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/schedulers/scheduling_ddpm.py
- tests/pipelines/ddim/test_ddim.py
- tests/pipelines/ddpm/test_ddpm.py
- tests/pipelines/latent_diffusion/test_latent_diffusion_superresolution.py
- tests/test_pipelines.py
Alternative to https://github.com/huggingface/diffusers/pull/1215
Generates the initial and variance noise for `DDPM` and `DDIM` on the same device as the models. 
This is a breaking change in terms of reproducibility, but makes the pipelines behave the same way as `StableDiffusion`
> Match the generator device to the pipeline for DDPM and DDIM

- README.md
- docs/source/api/schedulers.mdx
- Facilitate people that are familiar with the name samplers to understand that we call that schedulers
- Better SEO if people are googling for samplers to find our library as well
> Add a reference to the name 'Sampler'

- docs/source/using-diffusers/img2img.mdx
1. In [img2img example](https://huggingface.co/docs/diffusers/v0.7.0/en/using-diffusers/img2img#textguided-imagetoimage-generation). This code force change input image ratio. This is not a good practice, since the init image [will be preprocessed and keep aspect ratio](https://github.com/huggingface/diffusers/blob/555203e1faa32cfa07c6128c09a8352031d7a969/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L29).
2. Use `init_image.thumbnail()` can resize the image and keep its original aspect ratio, which avoid `CUDA out of memory` runtime error for large input image.
> [Docs] improve img2img example

- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
This should fix the padding issue remarked in https://github.com/huggingface/diffusers/issues/1165 . 
Still need to add tests, but maybe you could already give it a quick review @anton-l @pcuenca @patil-suraj
> [Stable Diffusion] Fix padding / truncation

- src/diffusers/models/attention.py
Older versions of xformers require query, key, value to be contiguous, this calls .contiguous() on q/k/v before passing to xformers.
Tested with 0.14 version of xformers built by [metrolobo](https://github.com/metrolobo), specifically, [this release](https://github.com/metrolobo/xformers_wheels/releases/tag/1d31a3ac_various_6), on T4 GPU and torch==1.12.0+cu113. It seemed this problem isn't encountered on other versions. 
Testing with the 'official' release on pip isn't possible, as the 0.13 version currently on pip cannot be installed, regardless of gpu/version. 
Edit: I did not run test with the other versions of prebuilt wheels, or other GPU but T4. Let me know if it fails on other versions.
> Edited attention.py for older xformers

- docs/source/training/text2image.mdx
The documentation for text2img fine-tuning [here](https://huggingface.co/docs/diffusers/training/text2image) has the wrong link to the script on GitHub, it directs to the textual inversion script.
I've updated it with the correct link in this PR.
> Fix wrong link in text2img fine-tuning documentation

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
Multiply the `batch_size` by `num_images_per_prompt` when preparing `mask` and `masked_image`.
Fixes #1274
> [StableDiffusionInpaintPipeline] fix batch_size for mask and masked latents

- scripts/convert_models_diffuser_to_diffusers.py
- src/diffusers/models/embeddings.py
- src/diffusers/models/resnet.py
- src/diffusers/models/unet_1d.py
made a couple of naming/convention changes per Patrik's latest comments on the main PR
> changes per Patrik's comments

- src/diffusers/models/unet_2d.py
- src/diffusers/models/unet_2d_condition.py
Documentation says `flip_sin_to_cos` defaults to False, when it actually defaults to True
> Fix documentation typo for `UNet2DModel` and `UNet2DConditionModel`

- examples/dreambooth/README.md
fixes https://github.com/huggingface/diffusers/issues/1207
> add 'conda install cudatoolkit' to dreambooth 'training on 16GB' example

- setup.py
- src/diffusers/dependency_versions_table.py
- tests/pipelines/altdiffusion/test_alt_diffusion.py
- tests/pipelines/altdiffusion/test_alt_diffusion_img2img.py
This PR adds tests for `AltDiffusionPipeline` and AltDiffusionImg2ImgPipeline`
> [AltDiffusion] add tests 

- docs/source/api/pipelines/latent_diffusion.mdx
- docs/source/api/pipelines/overview.mdx
- docs/source/index.mdx
- examples/community/imagic_stable_diffusion.py
- examples/community/lpw_stable_diffusion.py
- examples/community/lpw_stable_diffusion_onnx.py
- examples/textual_inversion/textual_inversion.py
- examples/textual_inversion/textual_inversion_flax.py
- setup.py
- src/diffusers/dependency_versions_table.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion_superresolution.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/utils/__init__.py
- src/diffusers/utils/pil_utils.py
- tests/pipelines/latent_diffusion/test_latent_diffusion_superresolution.py
Should solve the deprecation problem with PIL:
- https://github.com/huggingface/diffusers/pull/788
- https://github.com/huggingface/diffusers/issues/784
- https://github.com/huggingface/diffusers/pull/1259
Co-authored-by: @michellemoorre
Co-authored-by: @kashif
Co-authored-by: @allo-
Co-authored-by: @Thomas-MMJ
> Add improved handling of pil

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
cpu offloading defaults to 'cuda'. Specifying what cuda device gives the user more freedom
If accepted, then all pipelines would need these minor changes
> cpu offloading: mutli GPU support

- src/diffusers/pipeline_utils.py
- tests/fixtures/custom_pipeline/what_ever.py
- tests/test_pipelines.py
Fixes: https://github.com/huggingface/diffusers/issues/1141
Now it's much easier to load custom pipelines locally.
```python
pipeline = DiffusionPipeline("CompVis/stable-diffusion-v1-4", custom_pipeline="/path/to/custom_pipe_in_wip.py")
```
> [Custom pipeline] Easier loading of local pipelines

- docs/source/api/pipelines/alt_diffusion.mdx
- docs/source/api/pipelines/stable_diffusion.mdx
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
Just a typo - thanks for spotting @WASasquatch
> img2text Typo

- README.md
- docs/source/_toctree.yml
- docs/source/api/experimental/rl.mdx
- docs/source/using-diffusers/audio.mdx
- docs/source/using-diffusers/multi_modal.mdx
- docs/source/using-diffusers/other-modalities.mdx
- docs/source/using-diffusers/rl.mdx
closes #54, should be merged with #105.
> add docs for multi-modal examples

- src/diffusers/schedulers/scheduling_utils_flax.py
The `subfolder` was not passed to the `load_config`
> [Flax] Fix loading scheduler from subfolder

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- utils/check_copies.py
Continuation of #1326
This fixes the corner case that we've hit with `AltDiffusion` where `make fix-copes` copied the `# Copied from` comments from the original SD pipeline, which messed up the copy logic a bit.
> Avoid nested fix-copies

- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
Added negative prompt support to jax pipeline.
For example.
prompt : `a colorful photo of a castle in the middle of a forest with trees and bushes, by Ismail Inceoglu, shadows, high contrast, dynamic shading, hdr, detailed vegetation, digital painting, digital drawing, detailed painting, a detailed digital painting, gothic art, featured on deviantart`
With negative prompt: `fog, grainy, purple`
> Jax infer support negative prompt

- examples/community/README.md
Missing dir causes an error when running the example code.
> Update README.md: Minor change to Imagic code snippet, missing dir error

- src/diffusers/models/attention.py
Restores the `baddbmm()` which was reverted in https://github.com/huggingface/diffusers/pull/689.  
_the original attempt was reverted due to its regressing the performance of the `tests/test_pipelines.py::PipelineTesterMixin::test_stable_diffusion_memory_chunking ` test.  
testing is more mature now, so let's have another try and see whether the problem reproduces._
Implements [this optimization](https://twitter.com/Birchlabs/status/1588703520433541120), motivated by the following benchmarks of matmul strategies (on MPS backend):
batched matmul with scale factor  
https://gist.github.com/Birch-san/8f3eb99deffdc3541595e46a01605dea
batched matmul  
https://gist.github.com/Birch-san/cba16789ec27bb20996a4b4831b13ce0
adds fast-path to attention in Decoder when `num_heads=1`.  
most of the …
> perf: prefer batched matmuls for attention

- examples/community/README.md
- examples/community/sd_text2img_k_diffusion.py
This PR adds a pipeline that supports k-diffusion
> [Community Pipelines] K-Diffusion Pipeline

- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
- examples/text_to_image/README.md
- examples/text_to_image/train_text_to_image.py
Currently the `--mixed_precision`  argument overrides the value of accelerate config and the default is `no`. So if the accelerate config has `mixed_precision` set to `fp16` and the default arg is `--mixed_precision="no"`, then no mixed precision is performed as the config value is overridden. 
This PR sets the default value to `None`, to always fall back to the value of `accelerate config`.
Also update examples command to pass `--mixed_precision` to `accelerate launch` instead of the script.
Fixes #1272
> [examples] fix mixed_precision arg

- src/diffusers/models/attention.py
This PR allows to enable `memory_efficient_attention` by default if xformers is correctly installed.
Fxies #1343
> use memory_efficient_attention by default

- examples/community/img2img_inpainting.py
- examples/community/interpolate_stable_diffusion.py
- examples/community/lpw_stable_diffusion.py
- examples/community/multilingual_stable_diffusion.py
- examples/community/sd_text2img_k_diffusion.py
- examples/community/speech_to_image_diffusion.py
- examples/community/text_inpainting.py
- examples/community/wildcard_stable_diffusion.py
- src/diffusers/modeling_utils.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion_safe/pipeline_stable_diffusion_safe.py
- src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
This PR replaces the deprecated `logger.warn` by `logger.warning` everywhere it was used.
> Replace logger.warn by logger.warning

- src/diffusers/models/attention.py
the `hidden_states` were normalized twice when using `use_linear_projection`. This PR fixes that.
> [Transformer2DModel] don't norm twice

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
This PR adds v-prediction for DDIM and Euler scheduler.
> add v prediction

- src/diffusers/models/attention.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
This PR adapts the `UNet2DConditionModel` for Stable diffusion 2 upscaler.
> Adapt UNet2D for supre-resolution

- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
The UNet blocks are copied from their 2D counterparts, hence the new arguments that `get_down_block()` wasn't expecting.
This fixes a bunch of slow VD tests failing on `main` due to unexpected arguments.
https://github.com/huggingface/diffusers/actions/runs/3541156272/jobs/5945067949
> Add the new SD2 attention params to the VD text unet

- src/diffusers/configuration_utils.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep_flax.py
- tests/test_modeling_common.py
- tests/test_modeling_common_flax.py
- tests/test_scheduler.py
- tests/test_scheduler_flax.py
@pcuenca - I think this is the cleaner way:
- 1) First save all configs
- 2) Then run init
Since the two are very independent, I don't see a reason why this could break anything. Also note that we're already doing this in Flax: https://github.com/huggingface/diffusers/blob/d52388f48660de5776d9129945d5e960cad59d63/src/diffusers/configuration_utils.py#L598
> Allow to set config params directly in init

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion_safe/pipeline_stable_diffusion_safe.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
This PR speeds up the test by correcting the function argument and removes `kwargs` from all pipelines which are never used
> Speed up test and remove kwargs from call

- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
- examples/text_to_image/README.md
- examples/text_to_image/train_text_to_image.py
- examples/textual_inversion/README.md
- examples/textual_inversion/textual_inversion.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
This PR adds support for v-prediction training in 
- textual-inversion
- dreambooth
- text-to-image fine-tuning
This allows fine-tuning the SD2 768x768 model with these scripts.
To enable this, it adds `get_velocity` method to DDPM and DDIM scheduler to get the target during training. The type of training is automatically detected inside script using the `noise_scheduler.config.prediction_type` argument.
Users will just have set the right `resolution` in the command, 512 for all models except the 768 one. And 768 for the `stable-diffusion-2` model.
> v-prediction training support

- src/diffusers/modeling_flax_utils.py
- src/diffusers/pipeline_flax_utils.py
It worked for models but not for pipelines.
Accidentally broken in #1107.
> Fix Flax `from_pt`

- examples/community/README.md
- Corrects example usage (see #1114 , thanks @socathie !)
- Adds example inputs and results
> Updates Image to Image Inpainting community pipeline README

- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- tests/test_scheduler.py
The following code fails for the new `DPMSolverMultistepScheduler` when used in half precision due to `torch.quantile()` expecting inputs to be in full precision. This slight patch fixes this bug and allows for the following use case:
```
pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", custom_pipeline="stable_diffusion_mega",
scheduler=DPMSolverMultistepScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule='scaled_linear'),
torch_dtype=torch.float16, revision="fp16", safety_checker=None, use_auth_token=True).to('cuda')
pipe.text2img('a picture of a stealth fighter', num_images_per_prompt=10, num_inference_steps=50, output_type='numpy')
```
> Fix bug in half precision for DPMSolverMultistepScheduler

- src/diffusers/utils/import_utils.py
Adds another flavor of ORT to the list. `ort_nightly_directml` is usually installed manually from a nightly wheel, but it supports the latest DirectML improvements for Stable Diffusion.
Fixes https://github.com/huggingface/diffusers/issues/1316
> Add `ort_nightly_directml` to the `onnxruntime` candidates

- src/diffusers/configuration_utils.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
- src/diffusers/schedulers/scheduling_heun.py
- src/diffusers/schedulers/scheduling_ipndm.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- tests/test_scheduler.py
This PR allows one to save trained betas.
Solves: https://github.com/huggingface/diffusers/issues/1367
> Allow saving trained betas

- src/diffusers/modeling_utils.py
- tests/models/test_models_unet_1d.py
- tests/pipelines/versatile_diffusion/test_versatile_diffusion_mega.py
- tests/test_modeling_common.py
- tests/test_pipelines.py
- tests/test_scheduler.py
- tests/test_scheduler_flax.py
Makes sure weights are always loaded in the correct format
> Fix dtype model loading

- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
This PR makes the dreambooth training script more general by allowing all kinds of pipelines - e.g. it adds support for AltDiffusion and should be easier to maintain then: https://github.com/huggingface/diffusers/pull/1390
> [Dreambooth] Make compatible with alt diffusion

- docs/source/_toctree.yml
- docs/source/optimization/habana.mdx
This PR adds a page in the documentation that briefly shows how to use Stable Diffusion on Habana Gaudi.
> Add doc for Stable Diffusion on Habana Gaudi

- src/diffusers/utils/deprecation_utils.py
- tests/test_utils.py
Corrects the stacklevel of `deprecate` to make it easier for users to adapt their code. Thanks for the issue @keturn
> [Deprecate] Correct stacklevel

- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_heun.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- tests/test_scheduler.py
This PR adds v-prediction support to `PNDMScheduler`, `LMSDiscreteScheduler` and `EulerAncestralDiscreteScheduler`.
> support v prediction in other schedulers

- scripts/convert_original_stable_diffusion_to_diffusers.py
The values from Lightning configs aren't used durign training, so they might be wrong. E.g. `v2-inference-v.yaml` lists 64 instead of 96 for the UNet sample size: https://github.com/Stability-AI/stablediffusion/blob/main/configs/stable-diffusion/v2-inference-v.yaml#L13
> Add an explicit `--image_size` to the conversion script

- src/diffusers/schedulers/scheduling_heun.py
This PR fixes a subtle bug in `HeunScheduler`
- When computing the `pred_original_sample` in 2nd order, we need to use `sigma_next` instead of `sigma_hat`. 
cf https://github.com/crowsonkb/k-diffusion/blob/5b3af030dd83e0297272d861c19477735d0317ec/k_diffusion/sampling.py#L180
```python
denoised_2 = model(x_2, sigmas[i + 1] * s_in, **extra_args)
```
note the `sigmas[i + 1]` which is passed to the model call. That's `sigma_next` in our implementation.
- Also when computing the derivative in 2nd order step, we need to divide by `sigma_next` as that's the input sigma in that step.
cf  https://github.com/crowsonkb/k-diffusion/blob/5b3af030dd83e0297272d861c19477735d0317ec/k_diffusion/sampling.py#L181
```python
d_2 = to_d(x_2, sigmas[i + 1], denoised_2)
```
Not the `sigmas[i + 1]` passed to …
> fix heun scheduler

- examples/dreambooth/README.md
Add docs for writing accelerate config when environment doesn't support an interactive shell
re: https://github.com/huggingface/diffusers/issues/1228
> [docs] [dreambooth training] accelerate.utils.write_basic_config

- examples/community/lpw_stable_diffusion.py
- examples/community/sd_text2img_k_diffusion.py
- examples/community/text_inpainting.py
- src/diffusers/models/attention.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- src/diffusers/pipelines/stable_diffusion_safe/pipeline_stable_diffusion_safe.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_dual_guided.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_image_variation.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_text_to_image.py
- move the enable/disable call to being part of the base DiffusionPipeline (removes a bunch of duplicates)
- make the call recursive across all the modules in the model graph, so that exposing `set_use_memory_efficient_attention_xformers` in a leaf module is all it takes for it to be picked up (important for some pipelines, like superres, which are not properly covered right now - see for instance #1492 )
cc @patrickvonplaten, discussed a couple of days ago. Note that there does not seem to be unit tests covering this part, unless I missed them
> [refactor] Making the xformers mem-efficient attention activation recursive

- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
Fixes #1056.
Another option is to unconditionally use `torch.float32` in all platforms (both `int` and `float` are accepted as inputs), what do you think?
> Do not use torch.long in mps

- examples/community/README.md
- Fixed torch typo
- Removed `num_inference_steps` and `guidance_scale` arguments from pipe.train() and added to pipe()
> Fix Imagic example

- examples/community/README.md
- examples/community/checkpoint_merger.py
The checkpoint merger pipeline based on the discussion at #877.
Tested the checkpoint merger for the case with two checkpoints.
> [Community Pipeline] Checkpoint Merger based on Automatic1111

- examples/textual_inversion/textual_inversion.py
The textual inversion example now saves by default only the learned embeddings, unless the command line arguments --save_full_model or --push_to_hub are used. (Implements #759)
> [textual_inversion] Add an option for only saving the embeddings

- examples/dreambooth/train_dreambooth.py
- examples/dreambooth/train_dreambooth_inpaint.py
- examples/text_to_image/train_text_to_image.py
- examples/textual_inversion/textual_inversion.py
This PR uses the `from_pretrained` method to load schedulers in examples as the `from_config` won't support loading from path in v1
> [examples] use from_pretrained to load scheduler

- examples/dreambooth/train_dreambooth.py
> [dreambooth] make collate_fn global

- src/diffusers/models/attention.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
This PR adds a new config argument `upcast_attention` to `UNet2DConditionModel`. If it's `True` then the query and key in cross attention will be up casted to fp32 and the qk matmul and softmax operation will happen in fp32.
> [UNet2DConditionModel] add an option to upcast attention to fp32

- examples/community/lpw_stable_diffusion.py
- examples/community/lpw_stable_diffusion_onnx.py
Make it works on diffusers < 0.10.0
Fixes: #1604 , #1616
> Fix lpw stable diffusion pipeline compatibility

- src/diffusers/__init__.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/versatile_diffusion/__init__.py
- src/diffusers/utils/import_utils.py
As seen on the forums, some libraries can force-reinstall `transformers` on startup: https://discuss.huggingface.co/t/i-need-help-with-a-transformers-error/27485/
> Adapt to forced transformers version in some dependent libraries

- examples/dreambooth/train_dreambooth.py
- examples/text_to_image/train_text_to_image.py
- examples/textual_inversion/textual_inversion.py
The `True` causes an exception and then xformers is not enabled.
Reported in discord: https://discord.com/channels/879548962464493619/1014556809928904794/1050863595086434435
Fixes #1643.
> Remove spurious arg in training scripts

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
K samplers expand the sigmas to match the batch dimension of the input sample, for example here: https://github.com/crowsonkb/k-diffusion/blob/master/k_diffusion/sampling.py#LL128
However, we later expand the input inside `model_fn` to account for cfg, but the `t` remained untouched. This fails for batch sizes > 1.
Initially reported in the forums: https://discuss.huggingface.co/t/how-do-i-set-up-multiple-samples-to-display-in-a-colab-notebook-with-k-diffusion/27567
> Allow k pipeline to generate > 1 images

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
This PR removes the offset as it's never used actually.
> Remove unnecessary offset in img2img

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
Since no deprecate() call was done, the typos were silently ignored.
> Remove unnecessary kwargs in depth2img

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion_superresolution.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
Currently one has to pass `image=...` because it is a required argument. This doesn't correctly deprecate the use of `init_image` though.
> Deprecate init image correctly

- scripts/convert_original_stable_diffusion_to_diffusers.py
I was running into issues converting a .ckpt to Diffusers format where the model didn't have the `global_step` key. The model I was converting was merged via the WebUI's checkpoint merger.
If `global_step` isn't present then just set it to `None` and let the checks on line 833 figure out what to do.
Also, check if the config file exists before downloading it and skip downloading it if it does.
> Handle missing global_step key in scripts/convert_original_stable_diffusion_to_diffusers.py

- examples/textual_inversion/textual_inversion.py
This PR fixes: https://github.com/huggingface/diffusers/issues/507
Essentially we are just copy-pasting the original embeddings after every step to be 100% certain that they are not changed. 
I've checked this PR by running the following script:
```
#!/usr/bin/env bash
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export DATA_DIR="/home/patrick_huggingface_co/images/a_magical_forest"
accelerate launch /home/patrick_huggingface_co/diffusers/examples/textual_inversion/textual_inversion.py \
--pretrained_model_name_or_path=$MODEL_NAME \
--train_data_dir=$DATA_DIR \
--learnable_property="object" \
--placeholder_token="<cat-toy>" --initializer_token="toy" \
--gradient_accumulation_steps=4 \
--max_train_steps=3000 \
--learning_rate=5.0e-04 …
```
> [Textual Inversion] Do not update other embeddings

- scripts/convert_diffusers_to_original_stable_diffusion.py
This fixes the `text_enc_dict: dict[str, torch.Tensor]` that is erroring out:
```
File "convert_diffusers_to_original_stable_diffusion.py", line 212, in <module>
def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable
``` 
Another solution would be to add a `from typing import Dict`, but since we don't type check anywhere I think removing the `dict[str, torch.Tensor]` as done in this PR makes more sense.
cc @lawfordp2017
> Fix wrong type checking in `convert_diffusers_to_original_stable_diffusion.py` 

- setup.py
- src/diffusers/__init__.py
- src/diffusers/pipelines/ddim/pipeline_ddim.py
- src/diffusers/pipelines/ddpm/pipeline_ddpm.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep_flax.py
- tests/pipelines/ddpm/test_ddpm.py
- tests/test_config.py
- tests/test_scheduler.py
- tests/test_scheduler_flax.py
`predict_epsilon` deprecation is pushed one more time into the future given the fast release cycles at the moment.
> [Version] Bump to 0.11.0.dev0

- _
- src/diffusers/dynamic_modules_utils.py
- src/diffusers/pipeline_utils.py
- tests/test_pipelines.py
Community pipelines can now be versioned with a `custom_revision` input to `from_pretrained`. If nothing is specified it will default to what is currently installed locally.
> [Community pipeline] Add github mechanism

- examples/dreambooth/train_dreambooth.py
As logger requires an `Accelerator`.
Fixes #1673.
> Dreambooth: use warnings instead of logger in parse_args()

- src/diffusers/utils/import_utils.py
If the version of the torch is less than 1.12, the version comparison will throw a TypeError exception.
torch 1.11:
```python
TypeError: '<' not supported between instances of 'TorchVersion' and 'Version'
```
torch 1.9.1+cu102:
```python
TypeError: '<' not supported between instances of 'str' and 'Version'
```
> Fix the bug that torch version less than 1.12 throws TypeError

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
This is basically a one-line change to the file `pipeline_stable_diffusion_inpaint_legacy.py`.
I allow the possibility of replacing
`init_latents_proper = self.scheduler.add_noise(init_latents_orig, noise, torch.tensor([t]))`
by
`init_latents_proper = self.scheduler.add_noise(init_latents_orig, noise_pred_uncond, torch.tensor([t]))`
with the argument `add_predicted_noise` now default to `True` (i.e., use the latter option by default). 
(Maybe it is better to keep the default argument as `False`, and maybe we can find a better name for this argument.)
What I am doing here is that I use the unconditionally predicted noise instead of the initial noise to create the diffused samples used in the reverse diffusion process, and as argued in [this …
> Improve pipeline_stable_diffusion_inpaint_legacy.py

- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py
I had some issues with a previous version of running img2img, it looks like that was fixed in a [previous commit](https://github.com/peterto/diffusers/commit/a40095dd226ac129e834ec4f709b998ae9ac4e90), but that commit removed code to set generator to a value if it is "None" thereby causing img2img generation to fail. Adding these lines back in fixes it for me (in combination of the previous commit).
> Fix ONNX img2img preprocessing

- src/diffusers/pipelines/unclip/pipeline_unclip.py
This PR fixes a bug `num_images_per_prompt` > 1. The attention maks also need to be duplicated along with the embeddings. (essentially all inputs should be duplicated)
> [UnCLIPPipeline] fix num_images_per_prompt

- docs/source/api/pipelines/overview.mdx
- docs/source/api/pipelines/stable_diffusion_2.mdx
- docs/source/optimization/fp16.mdx
- docs/source/using-diffusers/custom_pipeline_examples.mdx
- docs/source/using-diffusers/img2img.mdx
- docs/source/using-diffusers/inpaint.mdx
- examples/community/README.md
- examples/community/wildcard_stable_diffusion.py
- src/diffusers/pipelines/README.md
- tests/pipelines/altdiffusion/test_alt_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint_legacy.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_upscale.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_v_pred.py
- tests/test_pipelines.py
We should not recommend using the "fp16" revision anymore since most model checkpoints don't have such a branch and also because it's quite an unintuitive behavior.
> [Revision] Don't recommend using revision

- src/diffusers/pipelines/unclip/__init__.py
- src/diffusers/utils/import_utils.py
Same reason as https://github.com/huggingface/diffusers/pull/1638
Not sure if it's still breaking, but just to be safe
> Transformers version req for UnCLIP

- examples/dreambooth/train_dreambooth_flax.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
> [Dreambooth] flax fixes

- examples/dreambooth/train_dreambooth.py
- src/diffusers/optimization.py
to get_scheduler func, 
* add it to the train_dreambooth.py
> expose polynomial:power and cosine_with_restarts:num_cycles params

- .github/workflows/nightly_tests.yml
- .github/workflows/pr_tests.yml
- .github/workflows/push_tests.yml
- src/diffusers/pipelines/unclip/pipeline_unclip.py
Use `repeat_interleave` instead of `repeat` to duplicate the attention masks.
fixes #1785
This PR also adpats the test envs to use released `accelerate` version rather than `main`, as `test_from_save_pretrained_dtype` tests are faling with `accelerate` main as a result of https://github.com/huggingface/accelerate/pull/920
> Fix num images per prompt unclip

- examples/unconditional_image_generation/train_unconditional_ort.py
Fixes return_dict bug and resolves the following pickling error when using UNet2DModel in instantiation of ema_model:
```
File "train_unconditional_ort.py", line 452, in <module>
main(args)
File "train_unconditional_ort.py", line 327, in main
ema_model = EMAModel(
File "/home/prathikrao/diffusers/src/diffusers/training_utils.py", line 69, in __init__
self.averaged_model = copy.deepcopy(model).eval()
File "/opt/conda/envs/ptca/lib/python3.8/copy.py", line 172, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/opt/conda/envs/ptca/lib/python3.8/copy.py", line 270, in _reconstruct
state = deepcopy(state, memo)
File "/opt/conda/envs/ptca/lib/python3.8/copy.py", line 146, in deepcopy
y = copier(x, memo)
File "/opt/conda/envs/ptca/lib/python3.8/copy.py", line …
```
> reorder model wrap + bug fix

- examples/textual_inversion/textual_inversion.py
For mult-gpu training, the model should be unwrapped before calling any method on it. This PR fixes the call to `text_encoder.get_input_embeddings()` by first unwrapping the `text_encoder`.
cc @patrickvonplaten @williamberman @pcuenca
> [textual_inversion] unwrap_model text encoder before accessing weights

- src/diffusers/pipeline_utils.py
Duplication happens when there are safetensors versions of _some_ files in the repo but not all.
Ideally, we should just download safetensors files when they are available, and fallback to PyTorch when they are not. This could be done by retrieving the list of files in the repo using `list_repo_files` (or `model_info`) and filtering them to keep the ones we want. A similar mechanism could be applied to download `fp16` versions when they exist.
Addresses #1811.
> Avoid duplicating PyTorch + safetensors downloads.

- src/diffusers/models/attention.py
I believe this variable was meant to represent the Width of a continuous input, but was typo'd throughout this file as "Weight". This leads to some confusion as it's not clear what a weight dimension would represent in an original 2D input. 
Additionally, you can see from the docstring that the original author intended this to be width! 
```
hidden_states ( When discrete, `torch.LongTensor` of shape `(batch size, num latent pixels)`.
When continous, `torch.FloatTensor` of shape `(batch size, channel, height, width)`)
```
> Width was typod as weight

- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_flax.py
The example train_text_to_image* scripts incorrectly passed a tuple with the specified resolution in both width **and** height, which causes TorchVision resize transform to resize directly to the target size instead of properly preserving the aspect ratio.
This would have also caused the subsequent CenterCrop transform to be redundant.
https://pytorch.org/vision/main/generated/torchvision.transforms.functional.resize.html
> fix: resize transform now preserves aspect ratio

- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
- examples/text_to_image/README.md
- examples/text_to_image/train_text_to_image.py
- examples/textual_inversion/README.md
- examples/textual_inversion/textual_inversion.py
Problem:
xformers being available doesn't always mean it should be used. For example, I install xformers because it makes inference fast but I find xformers make my dreambooth training slower.
Solution:
Require explicit flag to enable xformers when running training scripts.
Related recent change: https://github.com/huggingface/diffusers/pull/1640
> Make xformers optional even if it is available

- examples/dreambooth/train_dreambooth.py
Now the precision type for Dreambooth class images generation can be set with `mixed_precision` as well.
Fixes #1831
> Allow selecting precision to make Dreambooth class images

- docs/source/api/pipelines/unclip.mdx
- scripts/convert_unclip_txt2img_to_image_variation.py
- src/diffusers/__init__.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/unclip/__init__.py
- src/diffusers/pipelines/unclip/pipeline_unclip_image_variation.py
- src/diffusers/utils/dummy_torch_and_transformers_objects.py
- tests/pipelines/unclip/test_unclip.py
- tests/pipelines/unclip/test_unclip_image_variation.py
Adds an unclip image variation pipeline
I uploaded the pipeline to https://huggingface.co/fusing/karlo-image-variations-diffusers if you want to skip this
From the diffusers root directory:
```bash
$ python scripts/convert_unclip_txt2img_to_image_variation.py --dump_path <path to save model>
```
```python
import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
from diffusers import UnCLIPImageVariationPipeline
import torch
import random
import PIL
def set_seed(seed: int):
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
set_seed(0)
torch.backends.cuda.matmul.allow_tf32 = False
torch.use_deterministic_algorithms(True)
torch.set_printoptions(precision=40)
def image_grid(imgs, rows, cols):
assert …
```
> unCLIP image variation

- examples/community/README.md
- examples/community/magic_mix.py
Community pipeline based on [my implementation](https://github.com/daspartho/MagicMix) of the [MagicMix: Semantic Mixing with Diffusion Models](https://arxiv.org/abs/2210.16056) paper. 
This Diffusion Pipeline allows for the semantic mixing of an image and a text prompt to create a new concept while preserving the spatial layout and geometry of the subject in the image.
Here are some examples I reproduced from the paper using my implementation-
@patrickvonplaten could you please take a look at it, looking forward to any comments! 
Thanks :)
Reference: #841
> [Community Pipeline] MagicMix

- tests/pipelines/stable_diffusion_2/test_stable_diffusion_inpaint.py
It seems like cpu_offload + `device_map="auto"` currently doesn't work well with `accelerate`. Remove `device_map="auto"`.
> [StableDiffusionInpaint] Correct test

- examples/textual_inversion/textual_inversion.py
This PR is a continuation of #687 by @Ttl . This PR
- Adds an argument `--gradient_checkpointing` to enable gradient checkpointing. The gradient checkpointing is enabled for the `text_encoder` and `unet`. For this, the `unet` is kept in train mode and as the dropout is 0 it should not affect the results.
- Remove `freeze_params` and instead use `requires_grad_` to disable grads.
- Remove the redundant call to  `accelerator.wait_for_everyone()` after every epoch, it's only needed before saving the pipeline.
> [textual inversion] add gradient checkpointing and small fixes.

- src/diffusers/modeling_flax_utils.py
- src/diffusers/models/unet_2d_condition_flax.py
- src/diffusers/models/vae_flax.py
- src/diffusers/pipeline_flax_utils.py
- src/diffusers/pipeline_utils.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/safety_checker_flax.py
- Fixes for flax img2img
- Other misc changes
- Re-aligned the img2img pipe with the normal pipe (mostly copy paste)
> Flax: Fix img2img and align with other pipeline

- examples/text_to_image/train_text_to_image.py
> Fix ema decay

- docs/source/api/diffusion_pipeline.mdx
- docs/source/api/pipelines/alt_diffusion.mdx
- docs/source/api/pipelines/audio_diffusion.mdx
- docs/source/api/pipelines/cycle_diffusion.mdx
- docs/source/api/pipelines/dance_diffusion.mdx
- docs/source/api/pipelines/ddim.mdx
- docs/source/api/pipelines/ddpm.mdx
- docs/source/api/pipelines/latent_diffusion.mdx
- docs/source/api/pipelines/latent_diffusion_uncond.mdx
- docs/source/api/pipelines/paint_by_example.mdx
- docs/source/api/pipelines/pndm.mdx
- docs/source/api/pipelines/repaint.mdx
- docs/source/api/pipelines/score_sde_ve.mdx
- docs/source/api/pipelines/stable_diffusion.mdx
- docs/source/api/pipelines/stable_diffusion_safe.mdx
- docs/source/api/pipelines/stochastic_karras_ve.mdx
- docs/source/api/pipelines/unclip.mdx
- docs/source/api/pipelines/versatile_diffusion.mdx
- docs/source/api/pipelines/vq_diffusion.mdx
Make sure docs always show all methods. 
Here some very nice documentation of how the `doc-builder` behaves: https://github.com/huggingface/doc-builder#writing-api-documentation
See differences between:
- https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline (new) and
- https://huggingface.co/docs/diffusers/v0.11.0/en/api/diffusion_pipeline#diffusers.DiffusionPipeline (old)
Using:
```
- all
```
is important to not "suppress" other methods. So by default, we should just always use:
```
- all
- __call__
```
> [Docs] Improve docs

- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
NumPy 1.24 had removed the "float" scalar alias as it was deprecated in v1.20.
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations
> Update ONNX Pipelines to use np.float64 instead of np.float

- src/diffusers/pipelines/unclip/__init__.py
This makes sure that we don't get an import error when `transformers` aren't installed and we run a script like `diffusers-cli env` or `make fix-copies`, as seen in https://github.com/huggingface/diffusers/issues/1895
```
diffusers/src/diffusers/pipelines/__init__.py", line 57, in <module>
from .unclip import UnCLIPImageVariationPipeline, UnCLIPPipeline
ImportError: cannot import name 'UnCLIPImageVariationPipeline' from 'diffusers.pipelines.unclip' (diffusers/src/diffusers/pipelines/unclip/__init__.py)
```
cc @williamberman
> Add UnCLIPImageVariationPipeline to dummy imports

- src/diffusers/schedulers/scheduling_sde_ve.py
This PR adds `add_noise` method to `scheduling_sde_vp.py` (addresses issues https://github.com/huggingface/diffusers/issues/1642)
My implementation is derived from the below author's codebase 
https://github.com/yang-song/score_sde_pytorch/blob/ef5cb679a4897a40d20e94d8d0e2124c3a48fb8c/losses.py#L109-L117
> [addresses issue #1642] add add_noise to scheduling-sde-ve 

- examples/research_projects/intel_opts/textual_inversion/textual_inversion_bf16.py
- examples/textual_inversion/textual_inversion.py
- examples/textual_inversion/textual_inversion_flax.py
- scripts/convert_kakao_brain_unclip_to_diffusers.py
- src/diffusers/models/modeling_flax_pytorch_utils.py
- src/diffusers/pipelines/unclip/pipeline_unclip.py
- src/diffusers/pipelines/unclip/pipeline_unclip_image_variation.py
- src/diffusers/schedulers/scheduling_unclip.py
- src/diffusers/utils/__init__.py
- src/diffusers/utils/torch_utils.py
- tests/pipelines/unclip/test_unclip.py
- tests/pipelines/unclip/test_unclip_image_variation.py
- utils/custom_init_isort.py
This PR adds a new helper function `torch_randn` that has three purposes:
- Allow fully deterministic generation by creating the tensors on CPU as also demanded here: https://github.com/huggingface/diffusers/issues/1514
- Avoids lots of duplicated code, as the same 5,6 lines are implemented in 10,20+ pipeline files.
- Helps us to better tests models by always creating tensors on CPU
This is the first PR of a two PR series to see if this helps to make UnCLIP deterministic across different CUDA, GPUs. In a follow-up PR, I'd then like to replace all existing `torch.randn` functions with this function as well as add a `reproducibility.md` guide.
> [Deterministic torch randn] Allow tensors to be generated on CPU

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
It fixes the issue originally described in #1835 
Redone because I messed up the commit history. Sorry about that.
@patil-suraj 
> fix: DDPMScheduler.set_timesteps()

- examples/dreambooth/train_dreambooth_flax.py
- examples/text_to_image/train_text_to_image_flax.py
- examples/textual_inversion/textual_inversion_flax.py
- src/diffusers/schedulers/scheduling_ddim_flax.py
- src/diffusers/schedulers/scheduling_ddpm_flax.py
- src/diffusers/schedulers/scheduling_utils_flax.py
Mostly involves supporting a v_prediction scheduler.
The implementation in #1777 doesn't take into account a recent refactor of `scheduling_utils_flax`, so this should be used instead.
> Support training SD V2 with Flax

- examples/community/tiled_upscaling.py
Hey AI Trainers and other peculiarities.
This is my first PR to Diffusers (I think, at least the first with an actual new feature). It's an upscaling feature that trades VRAM for compute and allows virtually infinite upscaling, being able to go as big as 8k in a matter of minutes on a single 3080 with little noticeable artifacts.
Started as a [research project with its own model](https://github.com/peterwilli/Diff2X), I managed to port this feature to Stable Diffusion 2 upscaling, with very cool results in return.
It was first introduced in my own [Discord bot](https://github.com/peterwilli/thingy) as a testing feature, but in the meantime I learned how pipelines worked and to my best knowledge I tried to make it available for Diffusers.
This is my first pipeline, so please be gentle with …
> New Pipeline: Tiled-upscaling with depth perception to avoid blurry spots

- examples/dreambooth/train_dreambooth.py
re: https://github.com/huggingface/diffusers/issues/1246
training/fine tuning shouldn't be done with fp16 weights[^1], fp16 inputs are ok with amp + gradient scaling. fp16 weights throw an error when used with amp + gradient scaling. We should check the dtype of the loaded model and throw an informative error before training begins.
We add a guard checking the datatype of the unet. We also add a guard checking the datatype of the text encoder if we are training the text encoder.
[^1]: precision issues when adding small gradient updates to fp16 weights. Reason why training with amp [recommends](https://developer.nvidia.com/blog/mixed-precision-training-deep-neural-networks/#:~:text=Training%C2%A0paper.-,FP32%20Master%C2%A0Copy%20of%20Weights,-Each%20iteration%20of) to keep weights as fp32 …
> [dreambooth] low precision guard

- examples/community/imagic_stable_diffusion.py
changed named arg to `self.tokenizer` from `truncaton` to `truncation` according to Tokenizer docs (https://huggingface.co/docs/tokenizers/api/tokenizer#tokenizers.Tokenizer.truncation)
> fix typo in imagic_stable_diffusion.py

- scripts/convert_original_stable_diffusion_to_diffusers.py
Make sure that also exoticly ordered original dicts are correctly converted.
Discovered when converting this checkpoint: https://huggingface.co/darkstorm2150/Protogen_v5.8_Official_Release/discussions/1
> [Conversion SD] Make sure weirdly sorted keys work as well

- docs/source/en/optimization/fp16.mdx
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
Correct a bug related to CPU offload as discovered by @Sanster here: https://github.com/huggingface/diffusers/issues/1934
> [CPU offload] correct cpu offload

- scripts/convert_original_stable_diffusion_to_diffusers.py
`upcast_attn` flag was introduced in this PR https://github.com/huggingface/diffusers/pull/1559/files#diff-575959cae6329573c802ceca78d9a160b9d25948817a9ff37feb37585f819b05R842, however the flag is actually not used.
This PR:
* fixes it by setting `upcast_attention` to what's specified by the flag.
* rename the flag to make it consistent with the rest of the code.
> Fix unused upcast_attn flag in convert_original_stable_diffusion_to_diffusers script

- scripts/convert_diffusers_to_original_stable_diffusion.py
Support direct transfer from diffusers to safetensors.
> [Conversion] Support convert diffusers to safetensors

- src/diffusers/models/cross_attention.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/unclip/pipeline_unclip.py
- src/diffusers/pipelines/unclip/pipeline_unclip_image_variation.py
- src/diffusers/schedulers/scheduling_unclip.py
- tests/pipelines/unclip/test_unclip.py
- tests/pipelines/unclip/test_unclip_image_variation.py
- tests/test_pipelines_common.py
re: https://github.com/huggingface/diffusers/issues/1857
We relax some of the checks to deal with unclip reproducibility issues. Mainly by checking the average pixel difference (measured w/in 0-255) instead of the max pixel difference (measured w/in 0-1).
> Use pipeline tests mixin for UnCLIP pipeline tests + unCLIP MPS fixes

- src/diffusers/pipelines/pndm/pipeline_pndm.py
Fixes #1918. 
Loading DDPMs in a `PNDMPipeline` (shown in the code below) will produce noisy results as the scheduler is not a `PNDMScheduler`.
```python
from diffusers import PNDMPipeline
model_id = "google/ddpm-cifar10-32"
pndm = PNDMPipeline.from_pretrained(model_id)
images = pndm(num_inference_steps=50, batch_size=3).images
```
Changing the scheduler after creating the pipeline will give the expected results.
```python
from diffusers import PNDMPipeline, PNDMScheduler
model_id = "google/ddpm-cifar10-32"
pndm = PNDMPipeline.from_pretrained(model_id)
pndm.scheduler = PNDMScheduler.from_config(pndm.scheduler.config)
images = pndm(num_inference_steps=50, batch_size=3).images
```
The fix is similar to #1932, where the scheduler is manually set in the constructor of the pipeline.
> Change PNDMPipeline to use PNDMScheduler

- README.md
- src/diffusers/__init__.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion_inpaint.py
- src/diffusers/utils/dummy_flax_and_transformers_objects.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_flax_inpaint.py
Flax version of stable diffusion inpainting model. 
Demo:
```python
import jax
from flax.jax_utils import replicate
from flax.training.common_utils import shard
import PIL
from diffusers import FlaxStableDiffusionInpaintPipeline
def download_image(url):
return PIL.Image.open(BytesIO(response.content)).convert("RGB")
img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"
init_image = download_image(img_url).resize((512, 512))
mask_image = download_image(mask_url).resize((512, 512)) …
```
> [Flax] Add Flax inpainting impl

- docs/source/en/api/pipelines/dit.mdx
The link in the main heading needs to be rendered on the doc page. It displays the text as is. cc @kashif
> fix dit doc header

- tests/pipelines/dit/test_dit.py
- tests/test_pipelines_common.py
DiT tests were constantly failing on the CPU fast tests (see here: https://github.com/huggingface/diffusers/actions/runs/3953793829) because the model architecture was too exotic. This PR fixes this. 
Let's try to make model dimensions not too small to avoid super extreme values that can lead to Nan going forward :-)
> [Dit] Fix dit tests

- examples/dreambooth/train_dreambooth_lora.py
This PR automatically creates a nice model card for LoRA: https://huggingface.co/patrickvonplaten/lora_dreambooth_dog_example
> [Lora] Model card

- src/diffusers/models/modeling_utils.py
When converting from pytorch_model.bin to safetensors format, currently pytorch_model.bin files can be deleted because diffusers confuses the "sharded" folder structure with the always present folder saving format.
Since we don't have sharded checkpointing (yet) in diffusers, we will delete the code for now.
> [Save Pretrained] Remove dead code lines that can accidentally remove pytorch files

- examples/dreambooth/README.md
- `.unet` was missing.
- The model name in `patrickvonplaten/lora` doesn't match with what the latest code expects.
> Minor fix in the documentation of LoRA

- examples/dreambooth/train_dreambooth.py
- examples/dreambooth/train_dreambooth_flax.py
- examples/dreambooth/train_dreambooth_lora.py
- examples/research_projects/colossalai/train_dreambooth_colossalai.py
- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py
- examples/research_projects/intel_opts/textual_inversion/textual_inversion_bf16.py
- examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py
- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_flax.py
- examples/textual_inversion/textual_inversion.py
- examples/textual_inversion/textual_inversion_flax.py
- examples/unconditional_image_generation/train_unconditional.py
- examples/unconditional_image_generation/train_unconditional_ort.py
Create repository on the Hub before cloning. In latest version of `hfh`, `Repository` will not handle repo creation anymore which will make these examples obsolete. This PR fixes this.
Similar to https://github.com/huggingface/transformers/pull/21158 in `transformers`.
Related to [slack message](https://huggingface.slack.com/archives/C02V5EA0A95/p1674208967703329?thread_ts=1674207561.296969&cid=C02V5EA0A95) (internal).
> Create repo before cloning in examples

- tests/pipelines/stable_diffusion/test_stable_diffusion_instruction_pix2pix.py
This PR updates the slow tests for `StableDiffusionInstructPix2PixPipeline` to use CPU generator for deterministic behaviour.
> [StableDiffusionInstructPix2Pix] use cpu generator in slow tests

- docs/source/en/api/pipelines/stable_diffusion/pix2pix.mdx
- no advertisement of revision -> it'll be deprecated soon
- by default safety checker should be used
> Correct Pix2Pix example

- scripts/convert_diffusers_to_original_stable_diffusion.py
The `convert_diffusers_to_original_stable_diffusion.py` script currently only supports loading SD diffusers models in pytorch format. An update has been made to check to see if `safetensors` versions of the files exist before deserialization takes place. If safetensors versions exist, these are deserialized. If not, the pytorch version is attempted to be deserialized.
No changes to the command line options are made. The detection happens behind the scenes.
> Safetensors loading in "convert_diffusers_to_original_stable_diffusion"

- examples/dreambooth/train_dreambooth.py
- examples/dreambooth/train_dreambooth_lora.py
- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_lora.py
- examples/textual_inversion/textual_inversion.py
This PR adds the `--dataloader_num_workers` argument to training scripts to let user choose the number of workers for dataloaders. In dreambooth script, this value was hardcoded to `1`, which breaks the script on windows, so changing it back to the torch default of `0`. 
Fixes #2041
> [examples] add dataloader_num_workers argument

- examples/textual_inversion/textual_inversion.py
Also, allow `--resume_from_checkpoint` to be used when the checkpoint does not yet exist (a normal training run will be started).
Fixes #2052.
> [textual_inversion] Fix resuming state when using gradient checkpointing

- examples/dreambooth/train_dreambooth.py
- examples/dreambooth/train_dreambooth_lora.py
- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py
- examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py
- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_lora.py
- examples/unconditional_image_generation/train_unconditional.py
- examples/unconditional_image_generation/train_unconditional_ort.py
Also, allow `--resume_from_checkpoint` to be used when the checkpoint does not yet exist (a normal training run will be started).
Same as #2072, but for all the other training scripts.
> Fix resume epoch for all training scripts except textual_inversion

- examples/dreambooth/train_dreambooth.py
When using multi GPU, the `model` becomes an instance of `DistributedDataParallel`, and we need to unwrap the model to access any property/methods of the model. This PR unwraps the model before accessing `dtype` arg. 
cc @williamberman
> [dreambooth] fix multi on gpu.

- examples/dreambooth/train_dreambooth_lora.py
- Run inference only when ``args.validation_prompt is not None`` and ``args.num_validation_images > 0``
- The argument of `manual_seed` should not be `None`
> Run inference on a specific condition and fix call of manual_seed()

- docs/source/en/_toctree.yml
- docs/source/en/training/lora.mdx
- docs/source/en/training/overview.mdx
- examples/text_to_image/README.md
> [docs] Adds a doc on LoRA support for diffusers

- examples/dreambooth/train_dreambooth_lora.py
Currenctly due to an indentation mistake, training Lora without validation (to be able to run at 6.5GB VRAM as mentioned [here](https://github.com/huggingface/diffusers/pull/1884#issuecomment-1387426047)) throws `UnboundLocalError: local variable 'images' referenced before assignment`.
This should be fixed by this PR.
> [lora] Fix bug with training without validation

- examples/dreambooth/train_dreambooth.py
This PR moves the low-precision guard before preparing the models. Because when using `deepspeed` with `mixed_precision`, the `model` is cast to `fp16/bf16` and the script raises an error because of the guard. 
Fixes #2084
> [dreambooth] check the low-precision guard before preparing model

- src/diffusers/pipelines/pipeline_utils.py
see actual docstring here: https://github.com/huggingface/diffusers/blob/048d4d35b4a061871b3bce6776d0ebf4f7823566/src/diffusers/pipelines/pipeline_utils.py#L311
> [nit] torch_dtype used twice in doc string

- src/diffusers/models/cross_attention.py
- tests/models/test_models_unet_2d_condition.py
As very nicely stated by @jorgemcgomes in https://github.com/huggingface/diffusers/issues/2124#issuecomment-1405447527 it's currently not possible to "disable" LoRA attention processors. 
This PR fixes this by hacking a bit into PyTorch's module dict (think it's fine & safe though :-))
> [LoRA] Make sure LoRA can be disabled after it's run

- src/diffusers/models/cross_attention.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
Should allow the following:
```python
import torch
model_path = "sayakpaul/sd-model-finetuned-lora-t4"
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
pipe.unet.load_attn_procs(model_path)
prompt = "A pokemon with blue eyes."
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5, cross_attention_kwargs={"scale": 0.5}).images[0]
image.save("pokemon.png")
```
Also cc @sayakpaul @apolinario
> Allow lora from pipeline

- src/diffusers/pipelines/pipeline_utils.py
Fixes: https://github.com/huggingface/diffusers/issues/1970
cc @lstein @keturn
> Don't call the Hub if `local_files_only` is specifiied

- src/diffusers/pipelines/pipeline_utils.py
In the path where we remotely load from the hub, we've already loaded the config here
https://github.com/huggingface/diffusers/blob/a89576925eec43963fa8694ba45863cd12f3297c/src/diffusers/pipelines/pipeline_utils.py#L461
Checked with, from diffusers root:
```bash
cd ..
git lfs clone https://huggingface.co/runwayml/stable-diffusion-v1-5
cd diffusers
```
```py
import torch
pipe = StableDiffusionPipeline.from_pretrained('runwayml/stable-diffusion-v1-5', torch_dtype=torch.float16)
pipe.to('cuda')
images = pipe('a horse riding inside a rocketship', num_images_per_prompt=4).images
for idx, image in enumerate(images):
image.save(f"./image-{idx}.png")
pipe = StableDiffusionPipeline.from_pretrained('../stable-diffusion-v1-5', torch_dtype=torch.float16) …
```
> [from_pretrained] only load config one time

- docs/source/en/_toctree.yml
- docs/source/en/using-diffusers/using_safetensors
- docs/source/en/using-diffusers/using_safetensors.mdx
Written with https://github.com/huggingface/diffusers/pull/2123 in mind.
This is optional but makes the actual inner working more explicit for users.
> Adding some `safetensors` docs.

- examples/unconditional_image_generation/train_unconditional.py
Otherwise an exception is raised when using fp16.
Seen while testing #2048. `train_text_to_image` doesn't have it either.
> Don't copy when unwrapping model

- examples/dreambooth/train_dreambooth_lora.py
I think it would be useful if it was possible to programmatically get what instance prompt was used in training in the case of LoRA DreamBooth example.
What do you think?
> Add instance prompt to model card of lora dreambooth example

- src/diffusers/schedulers/scheduling_ddpm.py
- tests/pipelines/audio_diffusion/test_audio_diffusion.py
- tests/pipelines/ddpm/test_ddpm.py
- tests/test_scheduler.py
DDPM allegedly supports evaluation with lower count of steps than in the train -
It allows to set infer timesteps count, and then space them based on the train timesteps
(For example for 1000 train steps and 100 infer steps it make time steps from the form 0, 10, 20, 30...).
Practically, It uses the previous timestep as "t - 1" to calculate the alphas, betas and variance, 
which is incorrect in case of different timesteps count in infer (for example, for 1000 train steps and 100 infer
steps, it should be "t - 10" and not "t - 1").
This is a bug, which cause the result image to be just noise in any case of lower count of timesteps in the infer.
Our fix sets the previous timestep to be the correct one (previous step in the current timesteps array), in those cases, while keeping the backward …
> [Bug]: fix DDPM scheduler arbitrary infer steps count.

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint_legacy.py
Follow up to https://github.com/huggingface/diffusers/pull/2096
PR addresses the following issues in the stable diffusion legacy inpaint pipeline:
When passing the inpainting mask as a tensor, the pipeline does not scale the mask to the latent size, causing a shape mismatch during the denoising loop.
Fix: Modified the `preprocess_mask` function to resize the mask tensor to the latent size with torch interpolate. Expected mask tensor shapes are `(B, H, W, C)` or `(B, C, H, W)`, where C is 1 or 3 (in which case channel dimension is reduced to 1 by averaging)
Noise is added to the unmasked latents after the denoising loop, causing noticeable image corruption with certain schedulers/low inference steps
Fix: Restore original latents corresponding to unmasked portions of the image after …
> [Breaking change] fix legacy inpaint noise and resize mask tensor

- src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
-- This commit adopts `requests` in place of `wget` to fetch config `.yaml`
files as part of `load_pipeline_from_original_stable_diffusion_ckpt` API.
-- This was done because in Windows PowerShell one needs to explicitly ensure
that `wget` binary is part of the PATH variable. If not present, this leads
to the code not being able to download the `.yaml` config file.
Signed-off-by: Abhishek Varma <abhishek@nod-labs.com>
> Use `requests` instead of `wget` in `convert_from_ckpt.py`

- src/diffusers/models/cross_attention.py
Maybe I am mistaken but it looks like the rank is not passed to LoRALinearLayer and is always 4?
> Pass LoRA rank to LoRALinearLayer

- src/diffusers/models/transformer_2d.py
The dimension does not match when `inner_dim` is not equal to `in_channels`.  Just swap them to make the dimension match.
> Fix a dimension bug in Transform2d

- src/diffusers/models/modeling_utils.py
- tests/test_modeling_common.py
diffusers uses accelerate loading by default which means that when weights are missing the error messages aren't great. 
This PR improves the error messages when running into cases as mentioned here: https://github.com/huggingface/diffusers/pull/2059#issuecomment-1411131741
cc @yiyixuxu
> [Loading] Better error message on missing keys

- src/diffusers/schedulers/scheduling_ddpm.py
In the case of learned_range variance type, there are missing logs and exponent comparing to the theory (see "Improved Denoising Diffusion Probabilistic Models" section 3.1 equation 15:
https://arxiv.org/pdf/2102.09672.pdf).
> [Bug] scheduling_ddpm: fix variance in the case of learned_range type.

- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint_legacy.py
This fixes the same issue as #2116 (which was the same patch as suggested in [OnnxDiffusersUI](https://github.com/azuritecoin/OnnxDiffusersUI#inpainting-fix)), but I think this is more robust and copies the structure in the text2img, img2img, and inpaint ONNX pipelines.
test_onnx_stable_diffusion_inpaint_legacy seems to pass with about the same frequency as otherwise in my setup (with the DML execution provider instead of CUDA).
> Fix timestep dtype in legacy inpaint

- examples/textual_inversion/textual_inversion.py
Fixed the bug I mentioned [here[(https://github.com/huggingface/diffusers/issues/2182) where textual inversion logging wasn't using the tokenizer with placeholder token. So, the logging displays the wrong images.
> Hotfix textual inv logging

- src/diffusers/models/cross_attention.py
Related to #2124 
The current implementation is throwing a shape mismatch error. Which makes sense, as this line is obviously missing, comparing to XFormersCrossAttnProcessor and LoRACrossAttnProcessor.
I don't have formal tests, but I compared `LoRACrossAttnProcessor` and `LoRAXFormersCrossAttnProcessor` ad-hoc, and they produce the same results with this fix.
> Fixes LoRAXFormersCrossAttnProcessor

- src/diffusers/schedulers/scheduling_ddpm_flax.py
The problem was introduced in 60438389.
An alternative would have been to modify all pipelines to forward the PRNG Key.
> [Flax DDPM] Make `key` optional so default pipelines don't fail

- src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py
Needed to convert `timesteps` to `float32` a bit sooner.
Fixes #1537
Thanks @keturn for identifying the solution.
`make test` reports failures, but they are the same failures as on `main` - not sure what this means:
```
======================================================================================= short test summary info =======================================================================================
FAILED tests/pipelines/ddim/test_ddim.py::DDIMPipelineFastTests::test_save_load_local - AssertionError: 0.45593053 not less than 0.0001
FAILED tests/pipelines/ddim/test_ddim.py::DDIMPipelineFastTests::test_save_load_optional_components - AssertionError: 0.45593053 not less than 0.0001
FAILED tests/pipelines/paint_by_example/test_paint_by_example.py::PaintByExamplePipelineFastTe …
```
> Fix k_dpm_2 & k_dpm_2_a on MPS

- examples/community/composable_stable_diffusion.py
- examples/community/imagic_stable_diffusion.py
- examples/community/interpolate_stable_diffusion.py
- examples/community/lpw_stable_diffusion.py
- examples/community/multilingual_stable_diffusion.py
- examples/community/sd_text2img_k_diffusion.py
- examples/community/seed_resize_stable_diffusion.py
- examples/community/speech_to_image_diffusion.py
- examples/community/wildcard_stable_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/paint_by_example/pipeline_paint_by_example.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- src/diffusers/pipelines/stable_diffusion/safety_checker.py
- src/diffusers/pipelines/stable_diffusion_safe/pipeline_stable_diffusion_safe.py
- src/diffusers/pipelines/stable_diffusion_safe/safety_checker.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_dual_guided.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_image_variation.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_text_to_image.py
I'm totally not sure if this is useful or just pollutes the history.
If you prefer, I can split this into 28 commits or even 28 separate PR's
> Fix a typo: bfloa16 -> bfloat16

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
Allows providing prompt_embeds instead of the prompt, which is not currently possible as the first check fails. This becomes the same as the function found in https://github.com/huggingface/diffusers/blob/8267c7844504b55366525169187767ef92d1f499/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L393
> Fixes prompt input checks in StableDiffusion img2img pipeline

- examples/research_projects/onnxruntime/unconditional_image_generation/README.md
- examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py
- examples/unconditional_image_generation/README.md
- examples/unconditional_image_generation/train_unconditional.py
Accidentally closed #2217 when syncing the fork. Given that #2042 moved ONNX-related files to a different directory, I have updated the code based on the new implementation.
Reuse the same code in `the train_text_to_image.py` script to enable/disable center crop or horizontal flip when training unconditional image generation. This comes in handy when training on character-based images that are facing a particular direction.
The training commands in the `README.md` will now include `center_crop` and `random_flip` arguments explicitly.
```
accelerate launch train_unconditional.py \
--dataset_name="huggan/flowers-102-categories" \
--resolution=64 --center_crop --random_flip \
...
```
> Make center crop and random flip as args for unconditional image generation

- examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py
- examples/unconditional_image_generation/train_unconditional.py
#2259 cause code to crash due to naming clash between `torchvision.transforms` and `transforms` function
https://github.com/huggingface/diffusers/blob/b1dad2e9d33b9c70bdadcc1263be47ed11699dc1/examples/unconditional_image_generation/train_unconditional.py#L389-L395
This PR rename the `transforms` function to `transforms_images`.
> Fix torchvision.transforms and transforms function naming clash

- src/diffusers/models/cross_attention.py
Found while testing #1791.
The pipeline doesn't crash, but it still doesn't work.
> mps cross-attention hack: don't crash on fp16

- .github/workflows/pr_tests.yml
- examples/test_examples.py
- examples/unconditional_image_generation/train_unconditional.py
- src/diffusers/utils/__init__.py
- src/diffusers/utils/import_utils.py
This PR accelerates the tests for:
- textual inversion 
- unconditional 
and adds new tests for
- dreambooth
- text_to_image
and makes sure those tests are also run on PRs on CPU. In my local test they should take around ~1min which is ok IMO.
> [Examples] Test all examples on CPU

- scripts/convert_original_stable_diffusion_to_diffusers.py
- src/diffusers/pipelines/audio_diffusion/mel.py
- src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_unclip.py
- src/diffusers/utils/testing_utils.py
- tests/pipelines/unclip/test_unclip.py
- tests/test_pipelines_common.py
> misc fixes

- examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py
- examples/unconditional_image_generation/train_unconditional.py
Resolves ValueError: `num_inference_steps`: 1000 cannot be larger than `self.config.train_timesteps`: 50 as the unet model trained with this scheduler can only handle maximal 50 timesteps.
Triggered when running with --ddpm_num_steps set to less than 1000.
> Run same number of DDPM steps in inference as training

- .github/workflows/push_tests.yml
Make sure fast tests also run when merging to "main"
> Fast CPU tests should also run on main

- examples/text_to_image/train_text_to_image_lora.py
- tests/pipelines/ddpm/test_ddpm.py
This test runs for the full 1000 steps on the cpu and causes timeouts. We already have an integration test for the ddpm pipeline which will run the whole 1000 steps on gpu
> remove ddpm test_full_inference

- src/diffusers/models/cross_attention.py
- tests/models/test_models_unet_2d_condition.py
#2247 
#2124 
```python
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1")
pipe.unet.load_attn_procs(lora_dir)
pipe.to('cuda:2')
prompt = 'a cute cat'
image = pipe(prompt, guidance_scale=9, num_inference_steps=25).images[0]
image.save('1.png')
pipe.enable_xformers_memory_efficient_attention()
image = pipe(prompt, guidance_scale=9, num_inference_steps=25).images[0]
image.save('2.png')
pipe.disable_xformers_memory_efficient_attention()
image = pipe(prompt, guidance_scale=9, num_inference_steps=25).images[0]
image.save('3.png')
```
> Fix running LoRA with xformers

- examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py
- examples/unconditional_image_generation/train_unconditional.py
Matching the support for Tensorboard to WandB for Unconditional Image Generation Examples.
> Log Unconditional Image Generation Samples to W&B

- docs/source/en/api/schedulers/overview.mdx
> [Docs] initial docs about KarrasDiffusionSchedulers

- src/diffusers/schedulers/scheduling_utils.py
- src/diffusers/schedulers/scheduling_utils_flax.py
follow up from https://github.com/huggingface/diffusers/pull/2346
> KarrasDiffusionSchedulers type note

- docs/source/en/conceptual/ethical_guidelines.mdx
There isn't a space between the "Scope" paragraph and "Ethical Guidelines", here: https://huggingface.co/docs/diffusers/main/en/conceptual/ethical_guidelines , yet I can't see that in the preview. In this PR, I'm simply adding some spaces in the hopes that it resolves the issue.....
> Funky spacing issue

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_deis_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
- src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
- src/diffusers/schedulers/scheduling_heun_discrete.py
- src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_repaint.py
- src/diffusers/schedulers/scheduling_unclip.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_latent_upscale.py
While testing schedulers for https://github.com/huggingface/diffusers/pull/2297
Adding the glide noising schedule to schedulers which don't support it yet.
I also added prediction_type "sample" to a few of the schedulers.
> schedulers add glide noising schedule

- examples/dreambooth/train_dreambooth.py
- examples/dreambooth/train_dreambooth_lora.py
- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py
- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py
- examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py
- examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py
- examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py
- examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py
- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_lora.py
- examples/textual_inversion/textual_inversion.py
- examples/unconditional_image_generation/train_unconditional.py
re: https://github.com/huggingface/diffusers/issues/1297
> add total number checkpoints to training scripts

- src/diffusers/schedulers/scheduling_pndm.py
Reset `cur_model_output` in `set_timesteps`. 
Thanks for spotting this @fxmarty
> [SchedulingPNDM ] reset cur_model_output after each call

- docs/source/en/_toctree.yml
- docs/source/en/api/schedulers/overview.mdx
- docs/source/en/api/schedulers/unipc.mdx
- src/diffusers/__init__.py
- src/diffusers/schedulers/__init__.py
- src/diffusers/schedulers/scheduling_deis_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
- src/diffusers/schedulers/scheduling_unipc_multistep.py
- src/diffusers/schedulers/scheduling_utils.py
- src/diffusers/utils/dummy_pt_objects.py
- tests/test_scheduler.py
Add a multistep UniPC. UniPC is a training-free framework designed for the fast sampling of diffusion models, which consists of a corrector (UniC) and a predictor (UniP) that share a unified analytical form and support arbitrary orders.
For more details about the method, please refer to the [[paper]](https://arxiv.org/abs/2302.04867) and the [[code]](https://github.com/wl-zhao/UniPC).
This implementation also supports passing another scheduler as the `solver_p` to UniPC, which will instead perform the sampling through `solver_p + UniC`.
https://github.com/huggingface/diffusers/issues/2311
> add the UniPC scheduler

- src/diffusers/models/cross_attention.py
`torch.concat` is simply an alias, we can directly call torch.cat.
Reference: https://pytorch.org/docs/stable/generated/torch.concat.html
torch.concat raises warning for the ONNX export: https://github.com/pytorch/pytorch/issues/90691#issuecomment-1354976791
> Replace torch.concat calls by torch.cat

- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py
onnx pipeline will throw error when batch size > 1. 
There is one line shall be removed. It tried to call safety checker on all images (but the exported safety checker only supports batch_size == 1).  Code below this line calls safety checker on each image so this line is not needed any more.
Note that a better solution is to update onnx export script to allow safety checker onnx model support batch_size >1. That could achieve better performance.
> Fix stable diffusion onnx pipeline error when  batch_size > 1

- src/diffusers/schedulers/scheduling_unipc_multistep.py
- fix some typos in UniPC docs
- use solver_type `bh2` as default, since it is better for conditional sampling.
> [Docs] Fix UniPC docs

- tests/pipelines/stable_diffusion/test_stable_diffusion_pix2pix_zero.py
Lesson learned:
Always run append `RUN_SLOW=1` when running an individual test.
> [Pix2Pix Zero] Fix slow tests

- src/diffusers/utils/accelerate_utils.py
We should not parse `accelerate.__version__` if accelerate is not available :)
> apply_forward_hook simply returns if no accelerate

- tests/pipelines/stable_unclip/test_stable_unclip.py
- tests/pipelines/stable_unclip/test_stable_unclip_img2img.py
Fixes integration tests oom'ing
This fixes all of the integration tests that were failing as the first test oom'ing would cause the cuda memory cache to not actually empty when calling torch.cuda.empty_cache
> stable unclip integration tests turn on memory saving

- src/diffusers/pipelines/pipeline_utils.py
Deprecation warning should only hit at version 0.15
As explained in https://github.com/huggingface/diffusers/pull/2305 we will soon switch to using "variant" instead of "revision" to load fo16, but will only do it in the some future versions as we don't want to clutter people's cache.
> Fix deprecation warning

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py
fix a bug in `get_indices` function
currently this function doesn't return correct results for tokens appear more than once in the prompt 
for example, for "a cat and a frog"
```python
{'<|startoftext|>' :0 , 
'a</w>' :4 , 
'cat</w>': 2, 
'and</w>', 3: 
'frog</w>' :5 , 
'<|endoftext|>': 6}
```
we use the unique index as key instead
> fix the get_indices function

- src/diffusers/pipelines/pipeline_utils.py
"not installed" cannot be parsed with `version.parse(...)`
> fix transformers naming

- tests/models/test_models_unet_1d.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py
- tests/test_pipelines_common.py
Addresses https://github.com/huggingface/diffusers/actions/runs/4214039605/jobs/7314220521
> `mps` test fixes

- src/diffusers/models/modeling_utils.py
When loading devices with `device_map="auto"` and safetensors, accelerate expects that the safetensors weights have a "pytorch" format, see: https://github.com/huggingface/accelerate/blob/907a86d145cc62521ea0281eb24465f537480e2d/src/accelerate/utils/modeling.py#L670
Let's make sure we save this format when saving with `safe_serialization`.
> [Safetensors] Make sure metadata is saved

- docs/source/en/using-diffusers/using_safetensors.mdx
@Narsil I've added an improved space to `diffusers` (that also works if only part of the weights have not yet been converted). Also added some lines on how to test the PR online.
> [Docs] Improve safetensors

- src/diffusers/utils/testing_utils.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_pix2pix_zero.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py
tests were writing to local filesystem to download data
de-duped data downloads so they're not ran every test
moved test data from github/personal datasets to diffusers dataset
> pix2pix tests no write to fs

- docs/source/en/api/pipelines/stable_diffusion/pix2pix_zero.mdx
- docs/source/en/using-diffusers/controlling_generation.mdx
This PR edits the ["Controlling generation" doc](https://huggingface.co/docs/diffusers/main/en/using-diffusers/controlling_generation) to include several details on memory, distinct differences between the methods like InstructPix2Pix and Pix2PixZero (that may not be very obvious to the readers).
> [Docs] Include more information in the "controlling generation" doc

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py
- tests/test_pipelines_common.py
Otherwise inference fails if the safety checker runs.
Fixes #2500.
> Sequential cpu offload: require accelerate 0.14.0

- src/diffusers/models/attention_flax.py
Addresses #1992 for consistency with PyTorch (without bringing the cross-attention processor infrastructure to Flax).
> Bring Flax attention naming in sync with PyTorch

- .github/workflows/pr_tests.yml
- .github/workflows/push_tests.yml
- .github/workflows/push_tests_fast.yml
- src/diffusers/pipelines/pipeline_utils.py
`ONNX_WEIGHTS_NAME` and `ONNX_EXTERNAL_WEIGHTS_NAME` should go hand in hand when adding file filters, as one is an ONNX model definition (`model.onnx`) and the other is an external weight binary (`weights.pb`) that stores 2GB+ checkpoints.
This PR makes sure that `weights.pb` is not filtetered out when downloading an onnx checkpoint
> Fix ONNX checkpoint loading

- examples/unconditional_image_generation/train_unconditional.py
> adds `xformers` support to `train_unconditional.py`

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
Hi!
It seems like there is no more need to resize the init image and mask so rough - it's possible to use resolutions that are not multiples of 32. 
It works well on my side
> Update pipeline_stable_diffusion_inpaint_legacy.py resize to integer multiple of 8 instead of 32 for init image and mask

- docs/source/en/_toctree.yml
- docs/source/en/tutorials/basic_training.mdx
This PR migrates the relevant content from the Training with Diffusers [notebook](https://github.com/huggingface/notebooks/blob/main/diffusers/training_example.ipynb) into a new Tutorial section in the docs. It edits out some of the more background information so we don't bog the user down with these details, and focuses on just showing them the steps to train their own model!
> Training tutorial

- src/diffusers/loaders.py
- tests/models/test_models_unet_2d_condition.py
Fix #2448
This will try to load safetensors from filename, only if the extension
matches `.safetensors`.
> Fix regression introduced in #2448

- docs/source/en/optimization/onnx.mdx
- src/diffusers/__init__.py
- src/diffusers/pipelines/__init__.py
- src/diffusers/pipelines/stable_diffusion/__init__.py
- src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_upscale.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- src/diffusers/utils/dummy_torch_and_transformers_and_onnx_objects.py
- tests/pipelines/stable_diffusion/test_onnx_stable_diffusion_upscale.py
I think I have a working implemention of an `OnnxStableDiffusionUpscalePipeline`, which extends `StableDiffusionUpscalePipeline` to be compatible with `OnnxRuntimeModel`. I'm hoping to get some feedback on whether this is the right approach, and if so, what else I need to do before this can be merged besides writing tests. There are a few spots in the code that I have questions about, marked with `# TODO`s and noted at the bottom here.
Running the current `StableDiffusionUpscalePipeline` on a machine without CUDA acceleration can be pretty slow, even with relatively small 128x128 input images. I am writing [a web UI for running ONNX pipelines](https://github.com/ssube/onnx-web) that allows you to run a series of upscaling models (or one model repeatedly), but running …
> add OnnxStableDiffusionUpscalePipeline pipeline

- README.md
- scripts/convert_lora_safetensor_to_diffusers.py
This PR hanldes https://github.com/huggingface/diffusers/issues/2363 and part of https://github.com/huggingface/diffusers/issues/2326.
In summary, given a LoRA weight in safetensors format, we can merge it into a stable diffusion model in diffusers. It is quite easy to use as below. I have tested it with civitai models.
`python convert_lora_safetensor_to_diffusers.py --base_model_path runwayml/stable-diffusion-v1-5 --checkpoint_path  xxx.safetensors --dump_path ./outputs`
> Support convert LoRA safetensors into diffusers format

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py
fix for https://github.com/huggingface/diffusers/issues/2471
This PR add `attn_res` variable to `StableDiffusionAttendAndExcitePipeline.__call__`  so the user can adjust the resolution for attention maps based on the input image size 
It now works with image sizes other than `512 x 512`, however the generated image quality seems worse based on my quick experiment 
```python
import torch
from diffusers import StableDiffusionAttendAndExcitePipeline
pipe = StableDiffusionAttendAndExcitePipeline.from_pretrained(
"CompVis/stable-diffusion-v1-4",
).to("cuda")
prompt = "a cat and a frog"
indices = [2, 5]
seed = 6141
g = torch.Generator("cuda").manual_seed(seed)
images = pipe(
prompt=prompt,
token_indices=indices,
guidance_scale=7.5,
generator=g,
num_inference_steps=50, …
```
> allow Attend-and-excite pipeline work with different image sizes

- examples/dreambooth/train_dreambooth.py
tested logging with wandb in this run https://wandb.ai/yiyixu/dreambooth/runs/f89j7zmo?workspace=user-yiyixu
based on https://github.com/huggingface/diffusers/pull/2178#pullrequestreview-1298450036
should fix https://github.com/huggingface/diffusers/pull/1714
> add  intermediate logging for dreambooth training script

- examples/community/stable_diffusion_controlnet_inpaint.py
- examples/community/stable_diffusion_controlnet_inpaint_img2img.py
These are community controlnet pipelines inspired by https://github.com/haofanwang/ControlNet-for-Diffusers/
They are not exhaustively tested but I ran through a few examples manually and they seem to work ok. Please note that they will not be officially supported. Feel free to open issues and I can get to them when I have time but they won't be prioritized.
I do not know how sound the img2img pipeline is. I haven't thought too hard about if noising the encoded latents as such + using the additional controlnet conditioning works as intended.
note that community pipelines can also be loaded as such https://huggingface.co/docs/diffusers/v0.14.0/en/using-diffusers/custom_pipeline_overview#loading-official-community-pipelines
```py
import torch
from …
```
> community controlnet inpainting pipelines

- docs/source/en/_toctree.yml
- docs/source/en/training/text2image.mdx
This PR moves the relevant training code/examples for text-to-image from its [folder](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image) on GitHub to the docs so users can easily access all the essential info without bouncing back and forth between the docs and GitHub. 
I'm also trying out the framework-specific code blocks for PyTorch/Flax training, let me know what you think!
> [docs] Move relevant code for text2image to docs

- docs/source/en/_toctree.yml
- docs/source/en/training/dreambooth.mdx
This PR moves relevant DreamBooth training materials from its current GitHub folder to the docs as part of the docs consolidation efforts.
> [docs] Move DreamBooth training materials to docs

- docs/source/en/_toctree.yml
- docs/source/en/training/lora.mdx
This PR moves the relevant code example for text-to-image training with LoRA from the blog to the docs. To get it to fit in with the existing docs on LoRA, I had to rearrange the structure a bit, so now it shows training and inference for both text-to-image and DreamBooth. Let me know if I've forgotten anything!
> [docs] Move text-to-image LoRA training from blog to docs

- examples/text_to_image/README.md
It appears that the original link is invalid. The dataset has been officially published on hugging face.
> [Docs]Fix invalid link to Pokemons dataset

- examples/community/stable_diffusion_controlnet_img2img.py
Community pipeline for StableDiffusionControlNetImg2img 
Very similar to https://github.com/huggingface/diffusers/pull/2561 
@williamberman Tagging you since you did #2561 and I would appreciate your feedback.
> community stablediffusion controlnet img2img pipeline

- docs/source/en/training/text_inversion.mdx
This PR moves relevant Textual Inversion training materials (mostly Flax implementation) from its current GitHub folder to the docs and updates it with how to upload to the Hub and save/resume checkpoints.
> [docs] Move Textual Inversion training examples to docs

- docs/source/en/using-diffusers/img2img.mdx
This PR is the first example of how we can integrate the notebook into the doc page itself
for https://huggingface.co/docs/diffusers/using-diffusers/img2img
there are a lot of other doc pages that have a link to a colab notebook - plan to integrate them all after I get feedback for this one (so that we don't have to maintain these notebooks separately) 
for example 
https://huggingface.co/docs/diffusers/stable_diffusion
https://huggingface.co/docs/diffusers/using-diffusers/inpaint
https://huggingface.co/docs/diffusers/using-diffusers/rl
https://huggingface.co/docs/diffusers/using-diffusers/other-modalities
> Add notebook doc img2img

- docs/source/en/api/pipelines/stable_diffusion/img2img.mdx
- docs/source/en/api/pipelines/stable_diffusion/inpaint.mdx
- docs/source/en/api/pipelines/stable_diffusion/text2img.mdx
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion_inpaint.py
This PR:
1. add flax pipelines to API doc (text2img, img2img, inpaint)
2. add the flax example in the main README page as docstring examples to respective flax pipelines
> add flax pipelines to api doc + doc string examples 

- docs/source/en/_toctree.yml
- docs/source/en/using-diffusers/write_own_pipeline.mdx
This PR migrates the [Writing your own inference pipeline](https://huggingface.co/blog/stable_diffusion#writing-your-own-inference-pipeline) to the docs as part of the efforts to consolidate our docs sources. I added some light edits here and there for clarification and included section headers to give it structure.
The biggest thing here for me is how we use the term `pipeline` which I think can be a little ambiguous. To me, the pipeline has a very specific connotation (the `DiffusionPipeline` and all the pipeline classes that inherit from it). Here, we're showing how to use models and a scheduler to replicate what a pipeline does, but we don't actually use the `DiffusionPipeline` class. Maybe we can clarify that when we're talking about a `pipeline` here, we're talking about a complete …
> Migrate blog content to docs

- .github/workflows/build_documentation.yml
- docs/source/_config.py
Reverts huggingface/diffusers#2570
@stevhliu and @yiyixuxu reverting this PR for now until the problem with Flax is solved.
Currently the docs are not updated on "main" because they can't be build. 
Both not having Flax colabs or adding Flax as a framework to the builder work for me. It might be faster to just not include Flax in the beginning.
> Revert "[docs] Build notebooks from Markdown"

- .github/workflows/build_documentation.yml
- docs/source/_config.py
`doc-builder` supports building Jax notebooks (enabled in https://github.com/huggingface/doc-builder/pull/359) so I think we can add back building notebooks to Diffusers!
> [docs] Build Jax notebooks for real

- src/diffusers/models/attention.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
Make sure that we don't pass `attention_mask` (which is only intended for self attention) to the cross attention class. This was incorrectly implemented in terms of naming and luckly isn't used yet. This PR introduces a new `encoder_attention_mask` function argument that should be used instead when using attention masks for Stable Diffusion's text embeddings.
> [attention] Fix attention

- src/diffusers/models/autoencoder_kl.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
Prevents out-of-bounds indexing in blend_h and blend_v in AutoencoderKL when using tiled_decode.
Fix for #2646
> AutoencoderKL: clamp indices of blend_h and blend_v to input size

- src/diffusers/loaders.py
Should correct: https://github.com/huggingface/diffusers/issues/2616
> [Lora] correct lora saving & loading

- examples/community/README.md
- examples/community/ddim_noise_comparative_analysis.py
The [P2 weighting (CVPR 2022)](https://arxiv.org/abs/2204.00227) paper proposed an approach to answer this question, which is their second contribution.  
The approach consists of the following steps:
1. The input is an image x0.
2. Perturb it to xt using a diffusion process q(xt|x0).
- `strength` is a value between 0.0 and 1.0, that controls the amount of noise that is added to the input image. Values that approach 1.0 allow for lots of variations but will also produce images that are not semantically consistent with the input.
3. Reconstruct the image with the learned denoising process pθ(ˆx0|xt).
4. Compare x0 and ˆx0 among various t to show how each step contributes to the sample.
The authors used [openai/guided-diffusion](https://github.com/openai/guided-diffusion) model to denoise …
> Add ddim noise comparative analysis pipeline

- tests/test_ema.py
Ran with
```python
RUN_SLOW=1 pytest tests/test_ema.py
```
> [Tests] fix: slow serialization test

- docker/diffusers-pytorch-cuda/Dockerfile
--extra_url is not needed anymore since PyTorch 1.13 & CUDA 11.7
> Update Dockerfile CUDA

- src/diffusers/models/cross_attention.py
- tests/models/test_models_unet_2d_condition.py
Added support for implementing T5Attention to processors. Needed for #1044 
Tested on pytorch 2.0 RC
> T5Attention support for cross-attention

- docs/source/en/index.mdx
This PR updates the main docs landing page with better navigation around the docs (some of the buttons link to the `Overview` pages which aren't merged yet), and removes links to Colab notebooks in the table of supported pipelines.
> [docs] Create better navigation on index

- examples/unconditional_image_generation/train_unconditional.py
re: https://github.com/huggingface/diffusers/issues/2321
> train_unconditional save restore unet parameters

- src/diffusers/models/cross_attention.py
Improve the error message when using outdated `cross_attention` module.
> Improve deprecation error message when using cross_attention import

- tests/models/test_models_unet_2d.py
- tests/pipelines/dit/test_dit.py
- tests/pipelines/latent_diffusion/test_latent_diffusion_superresolution.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_pix2pix_zero.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_upscale.py
- tests/pipelines/versatile_diffusion/test_versatile_diffusion_dual_guided.py
- tests/pipelines/versatile_diffusion/test_versatile_diffusion_mega.py
- tests/test_ema.py
- tests/test_modeling_common.py
- tests/test_pipelines.py
This PR corrects a bunch of tests related to precision failures due to PyTorch 2.0 release.
> [Tests] Correct PT2

- examples/community/stable_diffusion_controlnet_img2img.py
This pull request adds optional parameters `controlnet_guidance_start` and `controlnet_guidance_end` to the `StableDiffusionControlNetImg2ImgPipeline` (#2584), which was recently added by @mikegarts.
The purpose of these parameters is to enable users to control when the ControlNet is activated and deactivated during the denoising process. I noticed that this option was missing from the pipeline, and I believe it will help to provide more room for structural changes in the output.
These parameters are similar to those in [Mikubill's WebUI extension for ControlNet](https://github.com/Mikubill/sd-webui-controlnet#weight-and-guidance-strengthstartend), which have proven to be very useful. 
The testing code included in this pull request is similar to that in #2584. You can specify the new …
> Add guidance start/end parameters to StableDiffusionControlNetImg2ImgPipeline

- src/diffusers/pipelines/pipeline_utils.py
- tests/test_pipelines_common.py
Adds an option to set pipeline dtype along with the device using the pipeline `to()` method. I added some basic tests to check it does not affect the results, and that the device and dtype can be set individually as well as together in a single `to()` call.
> Add option to set dtype in pipeline.to() method

- docs/source/en/optimization/mps.mdx
- tests/models/test_models_vae.py
- tests/models/test_models_vq.py
- tests/pipelines/ddpm/test_ddpm.py
- tests/pipelines/latent_diffusion/test_latent_diffusion_uncond.py
- tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py
- tests/test_modeling_common.py
- tests/test_pipelines_common.py
> `mps`: remove warmup passes

- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_lora.py
As title.
Offset noise is a recent training trick introduced by [crosslabs](https://www.crosslabs.org/blog/diffusion-with-offset-noise).
> Support for Offset Noise in examples

- src/diffusers/models/unet_3d_condition.py
Adding this functionality also fixes:
```
FAILED tests/models/test_models_unet_3d_condition.py::UNet3DConditionModelTests::test_from_save_pretrained - AssertionError: 0.04317846894264221 not less than or equal to 5e-05 : Models give different forward passes
FAILED tests/models/test_models_unet_3d_condition.py::UNet3DConditionModelTests::test_from_save_pretrained_variant - AssertionError: 0.04441814497113228 not less than or equal to 5e-05 : Models give different forward passes
```
> [UNet3DModel] Fix with attn processor

- examples/community/clip_guided_stable_diffusion.py
- examples/community/clip_guided_stable_diffusion_img2img.py
Enabled DPMSolverMultistepScheduler in CLIP-guided pipeline.
Issue: #2737
Here is code to test the changes:
```
import torch
DiffusionPipeline,
DPMSolverMultistepScheduler,
LMSDiscreteScheduler,
)
from transformers import CLIPFeatureExtractor, CLIPModel
feature_extractor = CLIPFeatureExtractor.from_pretrained(
"laion/CLIP-ViT-B-32-laion2B-s34B-b79K"
)
clip_model = CLIPModel.from_pretrained(
"laion/CLIP-ViT-B-32-laion2B-s34B-b79K", torch_dtype=torch.float16
)
guided_pipeline = DiffusionPipeline.from_pretrained(
"runwayml/stable-diffusion-v1-5",
custom_pipeline="/home/njindal/diffusers/examples/community/clip_guided_stable_diffusion.py",
clip_model=clip_model,
feature_extractor=feature_extractor,
)
guided_pipeline.scheduler = …
```
> [2737]: Add DPMSolverMultistepScheduler to CLIP guided community pipeline

- docs/source/en/api/pipelines/text_to_video.mdx
Summary of the changes:
* Included paper link
* Included paper abstract (to keep it in line with the other pipelines) 
* Included Spaces link (the official one that uses Diffusers)
* Fixed the pipeline doc generation (see [internal link](https://huggingface.slack.com/archives/C0502NEQ0BB/p1679538400022489))
> [Docs] small fixes to the text to video doc.

- docs/source/en/_toctree.yml
- docs/source/en/using-diffusers/conditional_image_generation.mdx
- docs/source/en/using-diffusers/depth2img.mdx
- docs/source/en/using-diffusers/img2img.mdx
- docs/source/en/using-diffusers/inpaint.mdx
- docs/source/en/using-diffusers/unconditional_image_generation.mdx
This PR adds the `[[open-in-colab]]` tag to all the inference pipeline tasks and embeds a Spaces at the end so users can directly interact with the pipeline and see what happens when they change parameters.
I couldn't find a functional Spaces for the image-to-image task, so I built my own [here](https://huggingface.co/spaces/stevhliu/ghibli-img2img). ~It works from a GPU-backed [Colab](https://colab.research.google.com/drive/1NoJZ-QvEptNITmYOc4dCEXBw1srD-Nk2?usp=sharing) for sure, but I don't know about a CPU (still running after 700 seconds 🥲). Would it be possible to request a GPU for this demo?~
> [docs] Add Colab notebooks and Spaces

- src/diffusers/utils/import_utils.py
For onnxruntime ROCm EP, two python package will be used.
1. The official python package is training package(`onnxruntime-training`). 
2. Build from souce and generate inference package(`onnxruntime-rocm`). 
For onnxruntime Cuda EP, `ort_nightly_gpu` is needed for inference nightly python package.
> Update onnxruntime package candidates

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py
Discussion: https://github.com/huggingface/diffusers/issues/2704
I would prefer to not support multiple batches when multiple conditionings are passed, preferably to keep the API design simple. This is what I have tried doing in the PR. 
@takuma104 could you also take a look?
> add: better warning messages when handling multiple conditionings.

- examples/controlnet/README.md
- examples/controlnet/train_controlnet_flax.py
wandb test run here: https://wandb.ai/yiyixu/train_controlnet_flax/runs/jye8xcs9?workspace=user-yiyixu
```
wget https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/controlnet_training/conditioning_image_1.png
```
```bash
export MODEL_DIR="runwayml/stable-diffusion-v1-5"
export OUTPUT_DIR="control_out"
python3 train_controlnet_flax.py \
--pretrained_model_name_or_path=$MODEL_DIR \
--dataset_name=fusing/fill50k \
--learning_rate=1e-5 \
--validation_image "./conditioning_image_1.png"  \
--validation_prompt "red circle with blue background" \
--validation_steps=1000 \
--revision="flax"\
--report_to="wandb"
```
> [WIP]Flax training script for controlnet

- src/diffusers/pipelines/stochastic_karras_ve/pipeline_stochastic_karras_ve.py
`KarrasVePipeline` crashes when `output_type="pil"`
```python
sample = (sample / 2 + 0.5).clamp(0, 1)
image = sample.cpu().permute(0, 2, 3, 1).numpy()
if output_type == "pil":
image = self.numpy_to_pil(sample)
```
should be 
```python
sample = (sample / 2 + 0.5).clamp(0, 1)
image = sample.cpu().permute(0, 2, 3, 1).numpy()
if output_type == "pil":
image = self.numpy_to_pil(image)
```
> fix KarrasVePipeline bug

- src/diffusers/optimization.py
All learning rate schedulers in the `optimization` module support the argument `last_epoch` which allows specifying the index of the last epoch when resuming training.
Currently, `optimization.get_scheduler` (as a unified API to the schedulers) does not support this. However, the docstring for the argument was already added which seems like an oversight.
This PR adds the argument `last_epoch` to `get_scheduler` according to the pre-existing docstring and passes it along when calling a factory method for a learning rate scheduler.
> Add `last_epoch` argument to `optimization.get_scheduler`

- docs/source/en/api/pipelines/stable_unclip.mdx
- tests/pipelines/stable_unclip/test_stable_unclip_img2img.py
Context: https://github.com/huggingface/diffusers/pull/2845#issuecomment-1485595739
> [Tests] Adds a test to check if `image_embeds` None case is handled properly in `StableUnCLIPImg2ImgPipeline`

- docs/source/en/api/pipelines/stable_unclip.mdx
- examples/controlnet/README.md
- examples/controlnet/train_controlnet_flax.py
Potentially closes https://github.com/huggingface/diffusers/issues/2840.
Example command:
```bash
python3 train_controlnet_flax.py \
--pretrained_model_name_or_path=$MODEL_DIR \
--dataset_name=multimodalart/facesyntheticsspigacaptioned \
--streaming \
--conditioning_image_column=spiga_seg \
--image_column=image \
--caption_column=image_caption \
--max_train_samples 50 \
--max_train_steps 5 \
--learning_rate=1e-5 \
--validation_steps=2 \
--revision="flax" \
--report_to="wandb"
```
> [Examples] Add streaming support to the ControlNet training example in JAX

- src/diffusers/loaders.py
Textual inversion doesn’t produce expected results, I tried [commenting on the PR](https://github.com/huggingface/diffusers/pull/2009#discussion_r1152398766) but it got merged without the fix.
Basically it looks like when the embedding’s shape has more than one dimension we take the full embedding but if it has only one we take the first value of it, resulting in a tensor of a single value. This ends up not changing the images generated at all.
For example:
- Embedding shape is [3, 768]: embedding is considered multi vector and 3 embeddings of shape [768] are added.
- Embedding shape is [1, 768]: At the moment the full tensor is being loaded, we should load a single embedding of shape [768].
- Embedding shape is [768]: At the moment the first value of the tensor is being loaded, we should …
> Fix textual inversion loading

- examples/research_projects/intel_opts/README.md
- examples/research_projects/intel_opts/inference_bf16.py
Modify example with intel optimization
> Modify example with intel optimization

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
Issue: [#2884](https://github.com/huggingface/diffusers/issues/2884)
Fixing cross_attention_kwargs in img2img pipeline.
Please use below code to reproduce the bug:
```
import torch
from diffusers import StableDiffusionImg2ImgPipeline
device = "mps"
model_path = "sayakpaul/sd-model-finetuned-lora-t4"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16).to(
device
)
pipe.unet.load_attn_procs(model_path)
url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"
init_image = Image.open(BytesIO(response.content)).convert("RGB")
init_image.thumbnail((768, 768))
prompt = "A …
```
> [2884]: Fix cross_attention_kwargs in StableDiffusionImg2ImgPipeline

- docs/source/en/_toctree.yml
- docs/source/en/stable_diffusion.mdx
The existing check for opencv only covers the main package `opencv-python`. However, there exist four different packages for opencv:
- `opencv-python` - main package
- `opencv-contrib-python` - full package (comes with contrib/extra modules)
- `opencv-python-headless` - main package without GUI
- `opencv-contrib-python-headless` - full package without GUI
This PR ensures that `diffusers` will not raise import error when using cv2-related functions as long as they have installed any of the packages above.
> Check for all different packages of opencv

- examples/controlnet/train_controlnet.py
- examples/controlnet/train_controlnet_flax.py
When working with the provided example PNG images, which have 4 channel (RGBA), the images cause problems when we stack the input and generated images during logging to tensorboard
https://github.com/huggingface/diffusers/blob/8c530fc2f6a76a2aefb6b285dce6df1675092ac6/examples/controlnet/train_controlnet.py#L139
> Ensure validation image RGB not RGBA

- examples/controlnet/train_controlnet.py
- examples/controlnet/train_controlnet_flax.py
- examples/dreambooth/train_dreambooth.py
- examples/dreambooth/train_dreambooth_lora.py
- examples/instruct_pix2pix/train_instruct_pix2pix.py
- examples/research_projects/colossalai/train_dreambooth_colossalai.py
- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py
- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py
- examples/research_projects/intel_opts/textual_inversion/textual_inversion_bf16.py
- examples/research_projects/lora/train_text_to_image_lora.py
- examples/research_projects/mulit_token_textual_inversion/textual_inversion.py
- examples/research_projects/mulit_token_textual_inversion/textual_inversion_flax.py
- examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py
- examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py
- examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py
- examples/text_to_image/train_text_to_image.py
- examples/text_to_image/train_text_to_image_flax.py
- examples/text_to_image/train_text_to_image_lora.py
- examples/textual_inversion/textual_inversion.py
- examples/textual_inversion/textual_inversion_flax.py
Related to #2860.
Updated some training scripts to use `upload_folder` instead of `Repository.push_to_hub`. The two advantages are upload speed (x1.5?) and UX (progress bars).
As said in https://github.com/huggingface/diffusers/issues/2860#issuecomment-1490666923, `upload_folder` does not support `blocking=False` (see https://github.com/huggingface/huggingface_hub/issues/939). This means I did not update the scripts that are pushing weights while training (`train_dreambooth_flax.py`, `./research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py` and `./unconditional_image_generation/train_unconditional.py`).
Worth mentioning that this is not ISO-feature with the previous scripts. In particular, `upload_folder` does not take into account if there is a `.gitignore` …
> Use `upload_folder` in training scripts

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
fix https://github.com/huggingface/diffusers/issues/2871#issuecomment-1492041635
> fix post-processing

- examples/controlnet/train_controlnet_flax.py
This PR makes a few modifications to the flax controlnet training script in order to run with larger dataset:
* allow load dataset with `load_from_disk`
* add intermediate checkpointing
* add a workaround for `ValueError: Decompressed Data Too Large` error that I got from torch dataloader 
* add `CenterCrop` to image transformation so that batching will work for images with different sizes and different width/ height
> update flax controlnet training script

- src/diffusers/schedulers/scheduling_euler_discrete.py
- src/diffusers/schedulers/scheduling_utils.py
- tests/schedulers/test_scheduler_euler.py
Discussion: #2905, #2064
This pull request allows for the utilization of karras_sigmas in the Euler Discrete scheduler. Additionally, happy to get feedback as we refine a set of guidelines as we expand this functionality to all the schedulers. This update introduces two key components:
- The inclusion of karras-based sigma.
- The mapping of sigmas to the timestamp, which will be used as input for UNET.
Also, I apologize if I overstepped any boundaries, as I was working on #2064, I realized to better setup the guidelines with a simpler scheduler.
**Euler Discrete Test**
```
from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler
import torch 
seed = 33
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipe = pipe.to("mps")
pipe.scheduler = …
```
> [2905]: Add Karras pattern to discrete euler

- src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py
when use nvidia gpu, the dtype of timesteps is float64 and the dtype of timesteps_interpol is float32, but they will be pushed into same torch.stack. This bug will make some optimization failed. For example, when I use oneflow to mock torch, torch.stack will push timesteps_interpol and timesteps which has different dtype, and then oneflow will clash.
> [scheduler] fix some scheduler dtype error

- examples/controlnet/README.md
- examples/controlnet/train_controlnet_flax.py
this PR:
1. add the step to install `wandb` in step by step guide (since it's not in the requirement file)
2. fix a bug: currently the script will fail if you choose `push_to_hub` not run `log_validation `
> minor fix in controlnet flax example

- CONTRIBUTING.md
As pointed out by @Birch-san: https://github.com/huggingface/diffusers/pull/2634#issuecomment-1496517210
> Explain how to install test dependencies

- examples/controlnet/README.md
- examples/controlnet/train_controlnet_flax.py
(a very short) wandb experiment here 
https://wandb.ai/yiyixu/train_controlnet_flax?workspace=user-yiyixu
> add Min-SNR loss to Controlnet flax train script 

- src/diffusers/models/attention_processor.py
- src/diffusers/pipelines/unclip/text_proj.py
- tests/pipelines/unclip/test_unclip_image_variation.py
I accidentally flipped the sequence and hidden dimensions of the encoder hidden states in the text projection model for the unclip pipeline. This will standardize all attention processors to use `(batch, seq len, hidden dimension)`.
The `encoder_hidden_states.transpose(1,2)` in the added kv attention processor is extraneous. I ran a script against the hub and confirmed that the karlo pipelines are the only pipelines which use the simple attention blocks, so this is a safe change to make.
I separately ran the unclip integration tests and confirmed it works 👍
> fix simple attention processor encoder hidden states dimension ordering

- src/diffusers/schedulers/scheduling_ddim.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/schedulers/scheduling_deis_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
- src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
- src/diffusers/schedulers/scheduling_heun_discrete.py
- src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
- src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py
- src/diffusers/schedulers/scheduling_lms_discrete.py
- src/diffusers/schedulers/scheduling_pndm.py
- src/diffusers/schedulers/scheduling_unipc_multistep.py
We pretty frequently overwrite the instance variables in the scheduler add_noise and get_velocity methods. 
The parameters of the noising schedule are very precision sensitive (the original ldm codebase uses 64 bit precision). 
Downcasting them and overwriting the instance variables can cause later calculations based off of them to be incorrect (all alphas cumprod for t < ~5 will round to 1) and can cause subtle errors in the denoising process (alpha_prod_t == 1 -> beta_prod_t == 0 -> pred_original_sample_coeff and current_sample_coeff divide by zero).
I'm assuming that there was no actual requirement for the instance variables to be permanently cast. If there is a need for them to be permanently cast, that should be done explicitly.
> do not overwrite scheduler instance variables with type casted versions

- src/diffusers/models/resnet.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
On the resnet:
add flag to skip the activation function on the time embedding
pass the output scale factor down through the encoder and decoder in the unet
> resnet skip time activation and output scale factor

- docs/source/en/_toctree.yml
- docs/source/en/optimization/coreml.mdx
Initially opened as #2489. Very much interested in getting feedback from @yiyixuxu, @stevhliu; I adapted the text from the blog post and added some recent stuff, but not fully happy about the flow yet.
> Initial draft of Core ML docs

- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py
- examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py
ref https://github.com/huggingface/diffusers/blob/dcfa6e1d20d9dc14f2dd652010bf251150aca843/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py#L415
Wrong parameter name will raise error : `TypeError: __init__() got an unexpected keyword argument 'accelerator_project_config'`
> fix wrong parameter name for accelerate

- src/diffusers/schedulers/scheduling_deis_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_unipc_multistep.py
- tests/schedulers/test_scheduler_dpm_multi.py
- tests/schedulers/test_scheduler_unipc.py
reported in slack by @kashif. When using same number of inference steps as training steps,  We're using np.linspace with number of samples greater than the stop - start. This leads to duplicates
```
>>> np.linspace(0, 99, 101)
array([ 0.  ,  0.99,  1.98,  2.97,  3.96,  4.95,  5.94,  6.93,  7.92,
8.91,  9.9 , 10.89, 11.88, 12.87, 13.86, 14.85, 15.84, 16.83,
17.82, 18.81, 19.8 , 20.79, 21.78, 22.77, 23.76, 24.75, 25.74,
26.73, 27.72, 28.71, 29.7 , 30.69, 31.68, 32.67, 33.66, 34.65,
35.64, 36.63, 37.62, 38.61, 39.6 , 40.59, 41.58, 42.57, 43.56,
44.55, 45.54, 46.53, 47.52, 48.51, 49.5 , 50.49, 51.48, 52.47,
53.46, 54.45, 55.44, 56.43, 57.42, 58.41, 59.4 , 60.39, 61.38,
62.37, 63.36, 64.35, 65.34, 66.33, 67.32, 68.31, 69.3 , 70.29,
71.28, 72.27, 73.26, 74.25, 75.24, 76.23, 77.22, 78.21, 79.2 , …
```
> [bug fix] dpm multistep solver duplicate timesteps

- tests/pipelines/stable_unclip/test_stable_unclip_img2img.py
I get a different result each time I run. See failing run for example here: https://github.com/huggingface/diffusers/actions/runs/4654137047/jobs/8235613948?pr=3034
> mps: skip unstable test

- .github/workflows/pr_tests.yml
- .github/workflows/push_tests_fast.yml
Let's make sure to not accidentally overwrite the fast test duration
> fix report tool

- examples/community/composable_stable_diffusion.py
Fixes #2703
Relative imports were breaking the pipeline
This pipeline also only works as composable diffusion with a narrow use case (num_images_per_prompt=1, prompt as a string). I was unable to figure out how to make it work with num_images_per_prompt > 1.
> Fix imports for composable_stable_diffusion pipeline

- examples/community/sd_text2img_k_diffusion.py
- src/diffusers/pipelines/audio_diffusion/pipeline_audio_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
- tests/pipelines/audio_diffusion/test_audio_diffusion.py
few quick fixes for integration tests after we removed setting config attrs on self
> config fixes

- src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
When doing generation manually instead of using `__call__`, and using guidance_scale as a static argument.
See #3039 for a discussion.
> Fix scheduler type mismatch

- tests/test_pipelines_flax.py
I saw this while working on the test for #2889.
We use `__call__` rather than pmapping the generation function ourselves because the number of static arguments is different now.
I also saw precision differences in other slow tests, but did not modify them in case the results are different in the CI TPU because of specific software versions.
> Fix invocation of some slow Flax tests

- src/diffusers/models/attention_processor.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- tests/models/test_attention_processor.py
This PR allows the added kv attention processor blocks to skip their self attention and only do cross attention
We also pass the only_cross_attention argument through the "simple" unet blocks
> add only cross attention to simple attention blocks

- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
> unet time embedding activation function

- src/diffusers/models/attention_processor.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
This lets the cross attention norm use both a group norm block or a
layer norm block.
The group norm operates along the channels dimension
and requires input shape (batch size, channels, *) where as the layer norm with a single
`normalized_shape` dimension only operates over the least significant
dimension i.e. (*, channels).
The channels we want to normalize along are the hidden dimension of the encoder hidden states.
By convention, the encoder hidden states are always passed as (batch size, sequence
length, hidden states).
This means the layer norm can operate on the tensor without modification, but the group
norm requires flipping the last two dimensions to operate on (batch size, hidden states, sequence length).
All existing attention processors will have the same logic and we can …
> Attention processor cross attention norm group norm

- src/diffusers/models/attention_processor.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- tests/pipelines/unclip/test_unclip_image_variation.py
rebased on top of https://github.com/huggingface/diffusers/pull/3021 and https://github.com/huggingface/diffusers/pull/3011
https://github.com/huggingface/diffusers/pull/3023/commits/200a8c73a2d220ae28ecb979e0ac3e511b4a4da3 and on is the main commit
> Attn added kv processor torch 2.0 block

- src/diffusers/models/unet_3d_blocks.py
- src/diffusers/models/unet_3d_condition.py
- tests/models/test_models_unet_2d_condition.py
- tests/models/test_models_unet_3d_condition.py
> [WIP] implement rest of the test cases (LoRA tests)

- src/diffusers/schedulers/scheduling_deis_multistep.py
- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- src/diffusers/schedulers/scheduling_euler_discrete.py
- tests/schedulers/test_scheduler_dpm_multi.py
Discussion: #2064 
Adding karras sigmas schedule to DPMSolverMultistepScheduler based on [PR](https://github.com/huggingface/diffusers/pull/2956).
As I mentioned earlier in #2064, the sample_dpmp_sde is not equivalent to DPM Multistep + karras which is something I confirmed after running the test. There is another bug in the kdiffusion code where `BrownianTreeNoiseSampler` is not being passed the seed, so the run for `sample_dpmp_sde` gives back different results each time, fixed after giving the seed though.
I believe we can still merge this PR as it's needed but the #2064 needs a new scheduler.
Let me know your thoughts.
DPM Multistep + Karras Sigma
```
import diffusers
import torch
from diffusers import DPMSolverMultistepScheduler
seed = 33
pipe = …
```
> [2064]: Add Karras to DPMSolverMultistepScheduler

- tests/models/test_models_unet_3d_condition.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py
- tests/test_pipelines_common.py
Summary of the changes: 
* Reduced the kinds of batch sizes for testing methods like `test_inference_batch_consistent()`, `test_inference_batch_single_identical()`.
* Reduced the size of the UNet.
* Reduced the number of inference steps.
> [Tests] Speed up panorama tests

- examples/controlnet/README.md
- examples/controlnet/train_controlnet_flax.py
List of small changes accumulated over the weekend:
1. Added profiling flags `--profile_steps`, `--profile_validation`, and `--profile_memory`, removed unused `--logging_dir`. Updated `--output_dir` to default to `runs/{timestamp}`.
1. Updated commands in README to store model in `runs/` subdirectory with timestamp, so they ignored by Git (`runs/` is in `.gitignore`), and multiple runs land automatically in different directories. Also setting `--tracker_project_name=$HUB_MODEL_ID`, and mention dataset for both commands to avoid mixing up different dataset runs in the same `wandb` project.
1. Changed `--num_train_epochs=11` for the `fusing/fill50k` dataset, since I noticed that models don't actually converge before this many epochs (see runs with different number of epochs here: …
> Adds profiling flags, computes train metrics average.

- src/diffusers/pipelines/pipeline_utils.py
The config should not save classes / functions that are not saveable. This is now possible due to: https://github.com/huggingface/diffusers/pull/2849
> [Pipelines] Make sure that None functions are correctly not saved

- src/diffusers/schedulers/scheduling_ddpm.py
- tests/schedulers/test_scheduler_ddpm.py
Many diffusion codebases allow configuring timesteps with varying spacing. This is a snippet that I have been copy and pasting in for testing purposes. 
Our standard method of calculating the previous timestep is using the constant step size. When using custom timesteps, we have to search in the tensor for the previous index.
> ddpm custom timesteps

- src/diffusers/models/controlnet.py
For: https://huggingface.co/lllyasviel/control_v11e_sd15_shuffle
> Add global pooling to controlnet

- src/diffusers/pipelines/stable_diffusion/safety_checker.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
Accidentally bug introduced by https://github.com/huggingface/diffusers/pull/2617
> [Bug fix] Fix img2img processor with safety checker

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
Fixes https://github.com/huggingface/diffusers/issues/3116 and adds a test. Tested on all 2nd order schedulers.
> [Bug fix] Make sure correct timesteps are chosen for img2img

- src/diffusers/pipelines/pipeline_utils.py
- tests/models/test_lora_layers.py
Fixing the following deprecation warnings:
```
src/diffusers/pipelines/pipeline_utils.py:204                                                                                          
/home/patrick/diffusers/src/diffusers/pipelines/pipeline_utils.py:204: DeprecationWarning: invalid escape sequence '\d'               
transformers_index_format = "\d{5}-of-\d{5}"                                                                                                                                                                                                                                
src/diffusers/pipelines/pipeline_utils.py:209                                                                                          
src/diffusers/pipelines/pipeline_utils.py:209 …
```
> Improve deprecation warnings

- examples/community/unclip_image_interpolation.py
- examples/community/unclip_text_interpolation.py
- src/diffusers/configuration_utils.py
- src/diffusers/models/autoencoder_kl.py
- src/diffusers/models/controlnet.py
- src/diffusers/models/modeling_utils.py
- src/diffusers/models/unet_1d.py
- src/diffusers/models/unet_2d.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/pipeline_utils.py
- src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_zero.py
- src/diffusers/pipelines/unclip/pipeline_unclip.py
- src/diffusers/pipelines/unclip/pipeline_unclip_image_variation.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_dual_guided.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_image_variation.py
- src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_text_to_image.py
- src/diffusers/schedulers/scheduling_ddpm.py
- src/diffusers/utils/deprecation_utils.py
- tests/models/test_modeling_common.py
- tests/pipelines/unclip/test_unclip.py
- tests/pipelines/unclip/test_unclip_image_variation.py
- tests/schedulers/test_schedulers.py
Gracefully deprecates https://github.com/huggingface/diffusers/pull/2849 .
Partly solves: https://github.com/huggingface/diffusers/issues/3096 and https://github.com/huggingface/diffusers/pull/2849#discussion_r1167803014 . 
Some context to better understand why the PR is seemingly so complicated:
- https://stackoverflow.com/questions/2405590/how-do-i-override-getattr-without-breaking-the-default-behavior
- https://docs.python.org/3/reference/datamodel.html#object.__getattr__
- https://docs.python.org/3/reference/datamodel.html#object.__getattribute__
The logic to overwrite was copied from PyTorch: https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module (CTRL + F "def __setattr__")
I'm testing the changes here with the following script and everything seems to work …
> Fix config deprecation

- docs/source/en/training/controlnet.mdx
- docs/source/en/training/instructpix2pix.mdx
- docs/source/en/training/text2image.mdx
- docs/source/en/training/unconditional_training.mdx
- examples/controlnet/README.md
- examples/instruct_pix2pix/README.md
- examples/text_to_image/README.md
- examples/text_to_image/train_text_to_image.py
- examples/unconditional_image_generation/README.md
Closes: https://github.com/huggingface/diffusers/issues/2997
Also related https://github.com/huggingface/diffusers/issues/2981
This PR adds necessary notes and/or modifications to get the following examples up and running on a multi-GPU machine:
* ControlNet
* Text to image
* Unconditional training 
InstructPix2Pix was already verified in https://github.com/huggingface/diffusers/pull/2978.
> feat: verfication of multi-gpu support for select examples.

- examples/controlnet/train_controlnet_flax.py
* Extracts `pipeline` from `log_validation` to avoid recompilation every time the function is called.
> Optimize log_validation in train_controlnet_flax

- examples/textual_inversion/README.md
Textual inversion is one of our most used examples, we should make sure the README stays up to date here.
> Correct textual inversion readme

- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
Adding act fn config to the unet timestep class embedding and conv activation.
The custom activation defaults to silu which is the default activation function for both the conv act and the timestep class embeddings so default behavior is not changed.
The only unet which use the custom activation is the stable diffusion latent upscaler https://huggingface.co/stabilityai/sd-x2-latent-upscaler/blob/main/unet/config.json (I ran a script against the hub to confirm).
The latent upscaler does not use the conv activation nor the timestep class embeddings so we don't change its behavior.
> Add unet act fn to other model components

- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
This mimics the dtype cast for the standard time embeddings
https://github.com/huggingface/diffusers/blob/703307efcc49fbc3f1362344dc5d577e4c4595c8/src/diffusers/models/unet_2d_condition.py#L651-L654
> class labels timestep embeddings projection dtype cast

- src/diffusers/models/transformer_2d.py
> Correct `Transformer2DModel.forward` docstring

- examples/controlnet/train_controlnet.py
re: https://github.com/huggingface/diffusers/issues/3101
The pipeline code resizes inputs to multiples of 8. Not doing this resizing in the training script is causing the encoded image to have different height/width dimensions than the encoded conditioning image (which uses a separate encoder that's part of the controlnet model)
> controlnet training resize inputs to multiple of 8

- src/diffusers/schedulers/scheduling_heun_discrete.py
- tests/schedulers/test_scheduler_heun.py
Discussion: #2905 #2064 
This pull request allows for the utilization of karras_sigmas in the Heun Discrete scheduler and builds upon the valuable contributions made in PR #2956. This update introduces two key components:
- The inclusion of karras-based sigma.
- The mapping of sigmas to the timestamp, which will be used as input for UNET.
**Heun Discrete Test**
```python
from diffusers import StableDiffusionPipeline, HeunDiscreteScheduler
import torch 
seed = 33
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipe = pipe.to("cpu")
pipe.scheduler = HeunDiscreteScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
prompt = "an astronaut riding a horse on mars"
generator = torch.Generator(device="cpu").manual_seed(seed)
image = pipe(prompt, …
```
> Add `Karras sigmas` to HeunDiscreteScheduler

- src/diffusers/pipelines/audioldm/pipeline_audioldm.py
Fixes #3091 by always upcasting float16/bfloat16 waveforms to float32, as we do in stable diffusion with the output images:
https://github.com/huggingface/diffusers/blob/3045fb276352681f6b9075956e599dd8ef571872/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L446
> [AudioLDM] Fix dtype of returned waveform

- src/diffusers/models/attention.py
- tests/models/test_models_vae.py
This PR cleans up the deprecated attention a bit and adds Torch 2.0 attention (which is from now **always** preferred).
This also allows to run https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler on 256x256 images much more easily.
Also cc @williamberman @hysts FYI
> Make sure VAE attention works with Torch 2_0

- src/diffusers/models/attention.py
Fixes bug: https://github.com/huggingface/diffusers/issues/3207 which was introduced in: https://github.com/huggingface/diffusers/commit/425192fe15f0b7a3fb6f72368246eed0264a36c2.
> [Bug fix] Fix batch size attention head size mismatch

- examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py
at the moment, If we select --mixed_precision on this script we get an error of mixing floats and half.
This cast fixes it
> fix mixed precision training on train_dreambooth_inpaint_lora

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py
enable_vae_tiling and disable_vae_tiling functions were not present in the StableDiffusionControlNetPipeline, added them by copying from StableDiffusionPipeline #3202 
@yiyixuxu please verify this
> adding enable_vae_tiling and disable_vae_tiling functions

- src/diffusers/loaders.py
- tests/pipelines/test_pipelines.py
When the token used for textual inversion does not have any special symbols (e.g. it is not surrounded by <>), the tokenizer does not properly split the replacement tokens.  Adding a space for the padding tokens fixes this.
> Fix issue in maybe_convert_prompt

- src/diffusers/utils/hub_utils.py
Resolve racing on `version_diffusers_cache.txt` between multiple processes.
From https://github.com/huggingface/transformers/blob/8a817e1ecac6a420b1bdc701fcc33535a3b96ff5/src/transformers/utils/hub.py#L1085
> Sync cache version check from transformers

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
Hot fix for now that allows the x4 Upscaler to return pt embeddings as well
> Allow return pt x4

- src/diffusers/models/vae.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
Make sure that fp16 can be run in fp16
> Allow fp16 attn for x4 upscaler

- docs/source/en/api/pipelines/audioldm.mdx
It's recommended to use the updated version of the AudioLDM checkpoint, which is the same size as the original one but trained for more steps: https://huggingface.co/cvssp/audioldm-s-full-v2#checkpoint-details
> [AudioLDM] Update docs to use updated ckpt

- tests/schedulers/test_scheduler_dpm_sde.py
Fix slow CUDA test introduced in #3020.
The different results in every architecture is because of Brownian Tree noise sampler from torchsde.
> [Stochastic Sampler][Slow Test]: Cuda test fixes

- examples/controlnet/train_controlnet.py
A small thing, but as observed by @off99555 in https://github.com/huggingface/diffusers/issues/2695#issuecomment-1470755050, that argument already has a default value. I experienced the same thing when testing controlnet and it was mildly annoying.
> Remove required from tracker_project_name

- docs/source/en/training/text_inversion.mdx
The pipeline is built as `pipe` but then used as `pipeline`.
> Fix typo in textual inversion JAX training script

- docs/source/en/optimization/fp16.mdx
re: https://github.com/huggingface/diffusers/issues/2907
Ideally we should fully fix this properly, but such issues with the statefulness of offloading don't seem to be that frequent so lets just document it for now
> [docs] add notes for stateful model changes

- examples/community/stable_diffusion_controlnet_inpaint.py
Discussed in https://github.com/huggingface/diffusers/issues/3104, this following draft works with the following code.
This pull request adds multiple conditions to `StableDiffusionControlNetInpaintPipeline`.
```
from stable_diffusion_controlnet_inpaint import StableDiffusionControlNetInpaintPipeline 
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
import torch
controlnet = [
ControlNetModel.from_pretrained("fusing/stable-diffusion-v1-5-controlnet-depth", torch_dtype=torch.float16),
ControlNetModel.from_pretrained("fusing/stable-diffusion-v1-5-controlnet-seg", torch_dtype=torch.float16),
]
pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
"runwayml/stable-diffusion-inpainting", controlnet=controlnet, …
```
> Add multiple conditions to StableDiffusionControlNetInpaintPipeline

- docs/source/en/training/dreambooth.mdx
- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth.py
We should make use of the Hub as much as possible and always default to uploading to the Hub
> Let's make sure that dreambooth always uploads to the Hub

- src/diffusers/optimization.py
You can write rule to control constant lr
Ex:
lr="0.0005"
rules="1:10,0.1:20,0.01:30,0.005"
it means that the learning rate is multiple 1 for the first 10 steps, mutiple 0.1 for the next 20 steps, multiple 0.01 for the next 30 steps and multiple 0.005 for the other steps.
lr = 0.0005 from step 0 ~ 9
lr = 0.00005 from step 10 ~ 19
lr = 0.000005 from step 20 ~ 29
lr = 0.0000025 after step 30
> add constant learning rate with custom rule

- docs/source/en/training/controlnet.mdx
- docs/source/en/training/custom_diffusion.mdx
- docs/source/en/training/instructpix2pix.mdx
I'm adding all the missing links from the doc to the training scripts
> [doc] add link to training script

- src/diffusers/pipelines/stable_diffusion/README.md
A pipeline object stores the results in `images` not in `sample`. Current code blocks don't work.
> Changed sample[0] to images[0]

- src/diffusers/models/controlnet.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img.py
- src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img_superresolution.py
- src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting.py
- src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py
- src/diffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_controlnet.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
Follow-up PR from: https://github.com/huggingface/diffusers/pull/3286
It would be great if we could benchmark the following scripts
for both torch 2.0.0 and torch nightly.
**NOTE: ALL THE FOLLOWING SCRIPTS CAN EASILY BE ACCESSED HERE: https://huggingface.co/diffusers/tools/tree/main/benchmark**
```py
import torch
path = "runwayml/stable-diffusion-v1-5"
run_compile = True  # Set True / False
pipe = DiffusionPipeline.from_pretrained(path, torch_dtype=torch.float16)
pipe = pipe.to("cuda:0")
pipe.unet.to(memory_format=torch.channels_last)
if run_compile:
print("Run torch compile")
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
prompt = "ghibli style, a fantasy landscape with castles"
for _ in range(3):
images = …
```
> [Torch 2.0 compile] Fix more torch compile breaks

- docs/source/en/training/lora.mdx
- examples/dreambooth/README.md
- examples/dreambooth/train_dreambooth_lora.py
1. Fixes: https://github.com/huggingface/diffusers/issues/3224
2. Keeps the example README and the doc in sync. 
3. Adds an elaborate of example of using `load_lora_weights()` during inference.
> fix: scale_lr and sync example readme and docs.

- docs/source/en/_toctree.yml
- docs/source/en/training/controlnet.mdx
- docs/source/en/training/create_dataset.mdx
- docs/source/en/training/custom_diffusion.mdx
- docs/source/en/training/dreambooth.mdx
- docs/source/en/training/instructpix2pix.mdx
- docs/source/en/training/lora.mdx
- docs/source/en/training/text2image.mdx
- docs/source/en/training/text_inversion.mdx
- docs/source/en/training/unconditional_training.mdx
Fixes some of the issues in #3219:
- describes the implications of LoRA support to provide more context and removes the link to the discussion on the PR because it can be difficult for users to know what to focus on in the PR
- create a separate create your own dataset guide for more visibility (instead of being only in the Unconditional generation guide), and add a link to it from each training guide
- clarify what `instance_prompt` is in the DreamBooth guide
- describes what files the LoRA training creates and adds some numbers to how long training takes for text-to-image LoRA
I'll create a separate PR to improve the readability of the training scripts since this is already kind of a lot.
> [docs] Improve LoRA docs

- docs/source/en/using-diffusers/controlling_generation.mdx
Closes https://github.com/huggingface/diffusers/issues/2807.
> update controlling generation doc with latest goodies.

- src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
- tests/schedulers/test_scheduler_dpm_multi.py
Theoretically speaking, I don't think the implementation of the SDE-variant of DPM-Solver / DPM-Solver++ in `k-diffusion` or in `DPMSolverSDEScheduler` is corresponding to the reverse diffusion SDE, though it can provide beautiful images (IMO, I think it is because diffusion models are "tolerant" to SDE solvers).
I've implemented the DPM-type SDE solver in this PR, which is an SDE solver for the reverse diffusion SDE. 
I recommend using the 2nd-order "sde-dpmsolver++" for guided sampling (such as stable-diffusion and deepfloyd-if). In my own experience, it can generate better images than DDPM under the same inference step. Moreover, for larger steps (such as 50 to 100), it can generate better images than ODE-type solvers such as "dpmsolver++".
> Add the SDE variant of DPM-Solver and DPM-Solver++

- examples/textual_inversion/textual_inversion.py
Due to how the option is named, it makes more sense to behave like this.
> Rename --only_save_embeds to --save_as_full_pipeline

- scripts/convert_original_audioldm_to_diffusers.py
Fixes #3255 by generalising the AudioLDM conversion script to make it easier to convert the medium and large checkpoints by allowing the user to override `model_channels`/`num_head_channels` without specifying an entirely updated config as input.
> [AudioLDM] Generalise conversion script

- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py
- src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_model_editing.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip.py
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py
- src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- Fixed issue that `StableDiffusionPipeline.__call__()` causes `TypeError` when both `prompt_embeds` and `negative_prompt` (not `negative_prompt_embeds`) are given as arguments.
This is my first PR so if there is problems please inform me.
> Fix TypeError when using prompt_embeds and negative_prompt

- src/diffusers/pipelines/pipeline_utils.py
Fixes the mixed up parameters for the [`download`](https://huggingface.co/docs/diffusers/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.download) method.
> [docs] Fix docstring

- src/diffusers/loaders.py
- src/diffusers/models/modeling_utils.py
- src/diffusers/pipelines/pipeline_utils.py
Improves the `use_safetensors` docstring to make it clearer by leading with the default (`None`) and what it means.
> [docs] Improve safetensors docstring

- src/diffusers/models/attention_processor.py
See https://github.com/huggingface/diffusers/pull/3312#issuecomment-1536648693.
In addition to this, I think it makes sense to add PT 2.0 variant of attention processors for the following classes:
* `SlicedAttnProcessor`
* `SlicedAttnAddedKVProcessor`
* `LoRAAttnProcessor`
* `CustomDiffusionAttnProcessor`
Follow classes already have their PT 2.0 counterparts:
* `AttnProcessor` => `AttnProcessor2_0`
* `AttnAddedKVProcessor` => `AttnAddedKVProcessor2_0`
I can take care of it but wanted to check if @williamberman wants to do this as part of his attention refactor.
> add: a warning message when using xformers in a PT 2.0 env.

- src/diffusers/pipelines/kandinsky/multiclip.py
- src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py
Adds CLIP based image encoder, and Multi-CLIP based text encoder and tokenizer as part of #3308 
To-do
> [WIP] add Kandinsky image encoder and Multi-clip model 

- docs/source/en/_toctree.yml
- docs/source/en/using-diffusers/using_safetensors.mdx
Introduces several updates to the safetensors docs:
- moves under Loading section for more visibility
- show how to load safetensors with `use_safetensors=True`
- include `from_ckpt` for loading safetensors
- embed safetensors convert Spaces
> [docs] Load safetensors

- docs/source/en/installation.mdx
Fixes #3349 and adds some minor improvements.
> [docs] Add transformers to install

- examples/text_to_image/train_text_to_image.py
Fixes:
```bash
AttributeError: 'AcceleratorState' object has no attribute 'zero3_init_context_manager'
```
from our [CI](https://github.com/huggingface/diffusers/actions/runs/4955138459/jobs/8864271403?pr=3397).
> fix: deepseepd_plugin retrieval from accelerate state

- .github/workflows/push_tests.yml
Our docker images already install newest transformers and accelerate versions, no need to overwrite them with main
> Don't install transformers and accelerate from source

- .github/workflows/pr_tests.yml
Improve fast tests.
Our docker images already install newest transformers and accelerate versions, no need to overwrite them with main. 
This make sure we don't always install from source which can be brittle
> Improve fast tests

- .github/actions/setup-miniconda/action.yml
Resolve  #3408 
Update `.github/actions/setup-miniconda/action.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')d"
```
**TO-BE**
```yml
run: echo "today=$(/bin/date -u '+%Y%m%d')d" >> $GITHUB_OUTPUT
```
> Replace deprecated command with environment file

- examples/community/README.md
- examples/community/stable_diffusion_tensorrt_img2img.py
Highlights of changes:
1. Add TensorRT Accelerated Image to Image pipeline along with a section in the README
2. Updates to Text2Image pipeline include optimizations and enabling build preview as a configurable parameter
> add stable diffusion tensorrt img2img pipeline

- src/diffusers/models/resnet.py
Docstrings of some Upsampling and Downsampling layers were incomplete or missing.
I didn't know exactly what format to use for the docstrings since it doesn't seem to be specified in [`CONTRIBUTING.md`](https://github.com/huggingface/diffusers/blob/8c5c30f3b17eb227561c8d6827a53aef9fbdcc37/CONTRIBUTING.md)
Overall, the various docstrings in the project don't all seem to be very consistent (some are formatted like Google's convention, some others look like Numpy's convention). Would it be a good idea to enable [pydocstyle](https://beta.ruff.rs/docs/settings/#pydocstyle) in ruff to overcome some of these issues ?
Like so (in [pyproject.toml](https://github.com/huggingface/diffusers/blob/1d7b4b60b7b7e19a0347da5a04ec76c045d8dbf0/pyproject.toml)):
```diff
[tool.ruff]
-ignore = ["C901", "E501", …
```
> [Docs] Fix incomplete docstring for resnet.py

- src/diffusers/models/autoencoder_kl.py
This PR addresses bad tiled blending in the tiled vae due to the forced blend extent range from ([#2660](https://github.com/huggingface/diffusers/pull/2660)).
Although the fixed range for tiled vae blend from ([#2660](https://github.com/huggingface/diffusers/pull/2660)) prevents out-of-bounds indexing, it causes issues with bad tile blending with certain resolution, such as 768x468, as shown in the bottom of the image below:
This issue arose when the tile blend range changed to minimal tile dimension while the blend process still started from `blend_extent`.
To resolve this, this PR updates `blend_extent` to match the blend range from `min(...)`, which addresses the problem as follows:
> fix tiled vae blend extent range

- docs/source/en/stable_diffusion.mdx
- PyTorch 2 is recommended over xFormers.
- Updated improvement figures according to latest benchmark.
Fixes #3412.
> Small update to "Next steps" section

- src/diffusers/pipelines/pipeline_utils.py
> [WIP] Bugfix - Pipeline.from_pretrained is broken when the pipeline is partially downloaded

- src/diffusers/models/attention_processor.py
Hi,
The change is quite simple, but it results in a big reduction in peak VRAM usage in pre-torch 2.0 installations. Especially for larger images.
For e.g. it reduces peak VRAM usage by 2 GB for a 1024x1024 image, even with attention slicing. And the savings scale up quickly with larger images.
`baddbmm_input`, `attention_scores` and `attention_probs` are 2 GB *each* for a 1024x1024 image (with attention slices == 4). And they're 4x bigger without attention slicing.
Keeping a reference to `baddbmm_input` (till the end of the function) means `attention_probs` will allocate an additional 2 GB of VRAM, which increases the peak VRAM usage. This reference is unnecessary, and freeing it up means `attention_probs` does not allocate an additional 2 GB of VRAM.
This allows larger images to be …
> Reduce peak VRAM by releasing large attention tensors (as soon as they're unnecessary)

- src/diffusers/loaders.py
- src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
This PR fixes two issues: https://github.com/huggingface/diffusers/issues/3390 and https://github.com/huggingface/diffusers/issues/3450
This PR should now work correctly with both the following 
1.) cc @takuma104 
```py
pipeline = StableDiffusionPipeline.from_ckpt(
'https://huggingface.co/gsdf/Counterfeit-V3.0/blob/main/Counterfeit-V3.0_fp16.safetensors', 
)
pipeline.to("cuda")
images = pipeline("a car")
```
and:
2.) cc @alexblattner
- Download: https://civitai.com/models/7371/rev-animated
- and load & run:
```py
pipeline = DiffusionPipeline.from_pretrained("revAnimated_v122.safetensors",torch_dtype=torch.float16,use_safetensors=True)
pipeline.to("cuda")
pipeline("a car").images[0]
```
> [From ckpt] Fix from_ckpt

- examples/dreambooth/train_dreambooth.py
- examples/test_examples.py
- src/diffusers/models/unet_2d_blocks.py
This updates the full dreambooth script to work with IF
To train the XL IF model using 8bit adam, you need ~48 GB of VRAM.
I also found it required very low learning rates or model quality would degrade.
Training command
```sh
export MODEL_NAME="DeepFloyd/IF-I-XL-v1.0"
export INSTANCE_DIR="dog"
export OUTPUT_DIR="dreambooth_if"
accelerate launch train_dreambooth.py \
--report_to="wandb" \
--pretrained_model_name_or_path=$MODEL_NAME  \
--instance_data_dir=$INSTANCE_DIR \
--instance_prompt="a photo of sks dog" \
--resolution=64 \
--train_batch_size=4 \
--gradient_accumulation_steps=1 \
--learning_rate=1e-7 \
--max_train_steps=150 \
--validation_prompt "a photo of sks dog" \
--validation_steps 25 \
--text_encoder_use_attention_mask \
--tokenizer_max_length 77 \ …
```
> Update full dreambooth script to work with IF

- tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py
These tests are still failing in the integration tests because the config is ran once on module load. Note that if it was ran at test time, it would turn off determinism for all following tests in all other modules that didn't set their own config. We should avoid this sort of mutative global config in individual test modules.
> attend and excite tests disable determinism on the class level

- examples/dreambooth/README.md
re: https://github.com/huggingface/diffusers/issues/3461#issuecomment-1551129345
> dreambooth docs torch.compile note

- docs/source/en/training/dreambooth.mdx
> add: if entry in the dreambooth training docs.

- src/diffusers/models/unet_1d_blocks.py
To fix this error in the integration tests:
```
FAILED tests/pipelines/dance_diffusion/test_dance_diffusion.py::DanceDiffusionPipelineFastTests::test_dict_tuple_outputs_equivalent - RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == expandedValue.numel() INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cuda/Indexing.cu":389, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor: 256 vs 8
```
Someone who knows this block better, please double check this logic :) 
My understanding is that the assignment requires[^1]  the highest dim in kernel to match the number of flattened indices, and the indices are flattened pair wise (i.e. arr[[1,2,3], [4,5,6]] -> 3 number of flattened indices, not 9). So we can just unsqueeze the …
> [{Up,Down}sample1d] explicit view kernel size as number elements in flattened indices

- src/diffusers/models/attention_processor.py
Related to https://github.com/huggingface/diffusers/issues/3441. 
@wfng92, would you mind looking into this PR? 
I added specific debugging statements in the branches of `use_memory_efficient_attention_xformers()` to check if we fall back to `AttnProcessor2_0` when a user specifies to use a particular attention processor like LoRA. 
To me, it seems like we DON'T fall back to `AttnProcessor2_0` when using:
```python
pipe.unet.load_attn_procs("patrickvonplaten/lora_dreambooth_dog_example")
pipe.enable_xformers_memory_efficient_attention()
```
(The debugging statement outputs confirm that)
Here's my Colab Notebook for verification:
https://colab.research.google.com/gist/sayakpaul/57687aefcddde15bcf2f35e536b2a449/scratchpad.ipynb
I agree that the current warning message is confusing as it …
> [Attention processor] Better warning message when shifting to `AttnProcessor2_0`

- src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
- tests/schedulers/test_scheduler_dpm_single.py
This PR fixes an edge case with the DPMSingleStep solver. For more info see #1866 .
cc @LuChengTHU would be incredible if you could also take a look here
> Fix DPM single

- src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
When loading a **_local_** `ckpt` file with the `download_from_original_stable_diffusion_ckpt` function, `convert_ldm_clip_checkpoint` is called, which in turn calls `CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")` and this forces a connection to huggingface.
When the user is offline this causes the code to hang and the ckpt file is never loaded. 
This pull request adds a `local_files_only` boolean to `convert_ldm_clip_checkpoint` and `download_from_original_stable_diffusion_ckpt` functions. 
When this boolean is set to `True` ckpt files can be loaded offline.
> Adds local_files_only bool to prevent forced online connection

- src/diffusers/models/attention.py
- src/diffusers/models/attention_processor.py
- src/diffusers/models/embeddings.py
- src/diffusers/models/transformer_2d.py
- src/diffusers/models/unet_2d_blocks.py
- src/diffusers/models/unet_2d_condition.py
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
- tests/models/test_models_unet_2d_condition.py
Resolves https://github.com/huggingface/diffusers/issues/1890.
Why do we want masking?
In stable-diffusion, our prompt may be 10 tokens long, but CLIP segments are padded to 77 tokens long.  
Attention is forced to attend over our useless PAD word embeddings.  
_This is incidentally a mistake that seeped into the core of stable-diffusion's training -- uncond is supposed to be 2 tokens long, but SD trained _without a mask_, attending accidentally to 75 extraneous PAD/EOS word embeddings._  
This is also useful for CLIP stitching (splicing multiple CLIP segments together to attend to a longer context) -- you can avoid attending to the duplicate BOS embeddings that each CLIP segment contributes.  
More generally: _language_ transformers benefit from _causal masks_, to _only attend to …
> Support for cross-attention bias / mask

- examples/controlnet/train_controlnet.py
re: https://github.com/huggingface/diffusers/issues/3467
This makes sense because we only update the global step every gradient accumulation steps times
> do not scale the initial global step by gradient accumulation steps when loading from checkpoint

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py
Related issue: #3494 
- Fix PanoramaPipeline which generates corrupted images when using dpmsolver scheduler.
In dpmsolver scheduler, `self.model_outputs` is used to save diffusion model output in previous and current timestep, and calculate `prev_sample`.
https://github.com/huggingface/diffusers/blob/49ad61c2045a3278ea0b6648546c0824e9d89c0f/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L634-L659
However, since we crop panorama image into several blocks and use `scheduler.step` in loop, `self.model_outputs` became outputs in previous and current blocks.
As a result, when using dpmsolver scheduler in PanoramaPipeline, we should collect rematch `self.model_outputs` in each block to right order to generate normal image.
```python
import torch
from diffusers import …
```
> Fix bug in panorama pipeline when using dpmsolver scheduler

- examples/community/README.md
- examples/community/stable_diffusion_controlnet_reference.py
Refer to https://github.com/Mikubill/sd-webui-controlnet/discussions/1236 and https://github.com/Mikubill/sd-webui-controlnet/discussions/1280 .
ControlNet version of https://github.com/huggingface/diffusers/pull/3435 .
Bugfix based for https://github.com/huggingface/diffusers/pull/2634 .
Reference Image
Output Image
> [Community] ControlNet Reference

- src/diffusers/pipelines/pipeline_utils.py
- tests/pipelines/test_pipelines.py
This PR refactors the way pipelines are loaded and thus solves: #3231
> Allow custom pipeline loading

- src/diffusers/pipelines/pipeline_utils.py
- tests/pipelines/test_pipelines.py
Still need to add tests and check that PR indeed makes sure `diffusers` still works when Hub is down. Should resolve: #3372 
Thanks a lot for the design idea @Wauplin 
@sayakpaul @pcuenca  wdyt about the design?
> Make sure Diffusers works even if Hub is down

- .github/workflows/push_tests.yml
- src/diffusers/utils/testing_utils.py
- tests/models/test_modeling_common.py
- tests/pipelines/controlnet/test_controlnet.py
- tests/pipelines/stable_diffusion/test_stable_diffusion.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
- tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
- tests/pipelines/test_pipelines.py
`torch.compile()` spawns several subprocesses and the GPU memory used was not reclaimed after the test ran.
This solution was taken from `transformers`: https://github.com/huggingface/transformers/blob/3658488ff77ff8d45101293e749263acf437f4d5/src/transformers/testing_utils.py#L1787
> Run `torch.compile` tests in separate subprocesses
