src/diffusers/models/resnet.py
Fixing more errors from assignments with explicit broadcasts
```
FAILED tests/pipelines/stable_diffusion_2/test_stable_diffusion_latent_upscale.py::StableDiffusionLatentUpscalePipelineFastTests::test_cpu_offload_forward_pass - RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == expandedValue.numel() INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cuda/Indexing.cu":389, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor: 512 vs 16
```
=> explicit broadcasts for assignments

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py
Currently, our DreamBooth PyTorch scripts (LoRA and non-LoRA) support both Stable Diffusion and IF pipelines. 
However, the `save_model_card` utility always includes `stable-diffusion` and `stable-diffusion-diffusers` tags even when the underlying pipeline is not of the `StableDiffusionPipeline` type. 
This PR fixes that. 
With this PR, the following two repositories were created:
* https://huggingface.co/sayakpaul/dreambooth-sd-dog
* https://huggingface.co/sayakpaul/dreambooth-if-dog
As one would expect, the tags are corrected:
=> [Examples/DreamBooth] refactor save_model_card utility in dreambooth examples

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py, tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py
- Refactor some code and support all schedulers including `PNDMScheduler` for panorama pipeline.
Similar to #3499, make all schedulers sync with blocks sampling. This can solve most of the issues about failed images generation in panorama pipeline.
```python
import torch
from diffusers import StableDiffusionPanoramaPipeline, PNDMScheduler
seed = 76
model_ckpt = "stabilityai/stable-diffusion-2-base"
prompt = "a photo of the dolomites"
pipe = StableDiffusionPanoramaPipeline.from_pretrained(model_ckpt, torch_dtype=torch.float16).to("cuda")
pipe.scheduler = PNDMScheduler.from_config(pipe.scheduler.config)
generator = torch.Generator(device="cuda").manual_seed(seed)
image = pipe(prompt, generator=generator, num_inference_steps=25,width=1024,height=512).images[0]
display(image) …
```
=> Fix panorama to support all schedulers

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/paint_by_example/pipeline_paint_by_example.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py, tests/pipelines/controlnet/test_controlnet_inpaint.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
This PR allows to use **`StableDiffusionControlNetInpaintPipeline`** and **`StableDiffusionInpaintPipeline`** for both inpainting models and normal text-to-image models. This has two purposes:
We can completely remove `**StableDiffusionInpaintLegacyPipeline**`. People will still want to use one and the same model weights for text2img, img2img, and inpainting so we need to allow the following scenario:
```py
StableDiffusionPipeline,
StableDiffusionImg2ImgPipeline,
StableDiffusionInpaintPipeline,
)
text2img = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
img2img = StableDiffusionImg2ImgPipeline(**text2img.components)
inpaint = StableDiffusionInpaintPipeline(**text2img.components)
```
It's also stated in our official docs, here: …
=> [Stable Diffusion Inpainting] Allow standard text-to-img checkpoints to be useable for SD inpainting

src/diffusers/loaders.py
The below check fails when `token` is provided for loading textual inversion from a file (e.g. safetensors) as `loaded_token` variable is not defined.
```python
if token is not None and loaded_token != token:
logger.info(f"The loaded token: {loaded_token} is overwritten by the passed token {token}.")
else:
token = loaded_token
```
Fails with:
```
File "/zzzzz", line 699, in load_textual_inversion
if token is not None and loaded_token != token:
│                                     └ 'zzzz'
└ 'zzzz'
UnboundLocalError: cannot access local variable 'loaded_token' where it is not associated with a value
=> Fix loaded_token reference before definition

src/diffusers/models/resnet.py
fixing first 2 of this [issues](https://github.com/huggingface/diffusers/issues/198#issuecomment-1262272521)
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py#L37
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py#L54
@patil-suraj Please have a look thanks.
=>  renamed variable to input_ and output_

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py
Corrects some docs for controlnet inpainting
=> Correct inpainting controlnet docs

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, tests/pipelines/controlnet/test_controlnet.py
This PR fixes controlnet in guess mode for 2nd order schedulers that require scaling. The difficulty was by no means to fix it, but to find out about the bug. So 100% of the credit goes to @off99555 from #3544
=> Fix controlnet guess mode euler

docs/source/en/_toctree.yml, docs/source/en/api/attnprocessor.mdx, docs/source/en/api/models.mdx, src/diffusers/models/attention_processor.py
Adds the `AttnProcessor` and `AttnProcessor2_0` to the API docs.
=> [docs] Add AttnProcessor to docs

src/diffusers/loaders.py, tests/models/test_lora_layers.py
Discussed in #3551. This is a fix for the issue where xFormers gets deactivated when LoRA is loaded in an environment where xFormers is enabled. As a solution, I have made it so that the `LoRAXFormersAttnProcessor` is used instead of the `LoRAAttnProcessor` when xFormers is enabled.
Todo:
=> Fix to apply LoRAXFormersAttnProcessor instead of LoRAAttnProcessor when xFormers is enabled

docker/diffusers-pytorch-cuda/Dockerfile, src/diffusers/models/attention_processor.py, src/diffusers/utils/testing_utils.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py
Fixes: https://github.com/huggingface/diffusers/issues/3576
=> Fix temb attention

tests/pipelines/unidiffuser/test_unidiffuser.py
W.r.t the UniDiffusers failing [here](https://github.com/huggingface/diffusers/actions/runs/5108261909/jobs/9181910494#step:7:11856).
This PR fixes some UniDiffuser tests. 
I first reproduced the environment in which our test suite is run following https://github.com/huggingface/diffusers/blob/main/.github/workflows/push_tests.yml. It's as simple as:
* First, run the Docker containing (`diffusers/diffusers-pytorch-cuda`).
* Clone `diffusers` from the PR branch. 
* Install the dependencies. 
Then I ran:
```bash
RUN_SLOW=1 python -m pytest -n 1 --max-worker-restart=0 --dist=loadfile tests/pipelines/unidiffuser/test_unidiffuser.py
```
On an A100, with the changes introduced in this PR all the tests from `test_unidiffuser.py` passed including the SLOW ones. 
But on a V100, it failed with:
``` …
```
=> [UniDiffuser Tests] Fix some tests

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
This PR contains the following additions: 
- fixes #3487 where latent scaling could break the process when strength < 1.
- inpainting pipeline now throws a value error if `num_inference_steps` < 1 due to strength adjustment.
- added a fast unit test to ensure value error is thrown when `num_inference_steps` < 1.
=> #3487 Fix inpainting strength for various samplers

examples/research_projects/onnxruntime/text_to_image/README.md, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/research_projects/onnxruntime/textual_inversion/README.md, examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py, examples/research_projects/onnxruntime/unconditional_image_generation/README.md, examples/research_projects/onnxruntime/unconditional_image_generation/requirements.txt, examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py
updates code to reflect latest changes as of May 30th
=> update code to reflect latest changes as of May 30th

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py
rebased on top of https://github.com/huggingface/diffusers/pull/3560
=> Full Dreambooth IF stage II upscaling

src/diffusers/loaders.py, tests/pipelines/test_pipelines.py
Unfortunately I could not find and issues referencing this behavior, but this PR fixes an issue where repeating a token corresponding to a multi-vector embedding is not handled properly. 
As an example, if we have a 4-vector embedding stored as `bad_quality.pt`
```python
pipe.load_textual_inversion('bad_quality.pt', token='bad_quality')
pipe.tokenizer.added_tokens_encoder 
pipe.maybe_convert_prompt('saturated, bad_quality, blurry, soft')
pipe.maybe_convert_prompt('saturated, bad_quality, blurry, bad_quality, soft')
```
The reason this occurs is because `TextualInversionLoaderMixin._maybe_convert_prompt` attempts to find and expand tokens that represent multi-vector embeddings with a token per vector. In the example above, this equates to:
```python
prompt.replace('bad_quality', …
```
=> Iterate over unique tokens to avoid duplicate replacements for multivector embeddings

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
fix https://github.com/huggingface/diffusers/issues/3631#issuecomment-1572549584
=> fix inpainting pipeline when providing initial latents

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/test_pipelines.py
If you passed a compiled module to the pipeline constructor, this would silently strip the compilation and set the uncompiled module on the pipeline
Before:
```py
from diffusers import UNet2DConditionModel
import torch
unet = UNet2DConditionModel.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="unet")
print(unet.__class__)
unet = torch.compile(unet)
print(unet.__class__)
pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", unet=unet)
print(pipe.unet.__class__)
```
Now:
```py
>>> from diffusers import UNet2DConditionModel
>>> import torch
>>> from diffusers import DiffusionPipeline
>>>
>>> unet = UNet2DConditionModel.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="unet")
>>>
>>> print(unet.__class__) …
```
=> set config from original module but set compiled module on class

docs/source/en/training/dreambooth.mdx, examples/dreambooth/README.md
More fleshed out docs we can link to in model cards and IF readme
=> dreambooth if docs - stage II, more info

src/diffusers/optimization.py
Currently, schedule_func() calls get_piecewise_constant_schedule() with wrongly named kwarg. This fixes that.
=> Set step_rules correctly for piecewise_constant scheduler

examples/textual_inversion/textual_inversion.py
Expose `num_cycles` kwarg of `get_schedule()` through `args.lr_num_cycles`. This is similar to the [implementation](https://github.com/huggingface/diffusers/blob/c6ae8837512d0572639b9f57491d4482fdc8948c/examples/controlnet/train_controlnet.py#L360) in current controlnet training script and other training scripts.
Note: different from [the current controlnet training script](https://github.com/huggingface/diffusers/blob/c6ae8837512d0572639b9f57491d4482fdc8948c/examples/controlnet/train_controlnet.py#LL906C18-L906C18), I scale `args.lr_num_cycles` by `gradient_accumulation_steps`, which seems to give the correct behavior.
=> Allow setting num_cycles for cosine_with_restarts lr scheduler

docs/source/en/using-diffusers/other-formats.mdx
A guide for how to load and use an A1111 LoRA checkpoint with `load_lora_weights` (to be merged after the ongoing PR that adds support for it).
=> [docs] Load A1111 LoRA

docs/source/en/training/dreambooth.mdx, examples/dreambooth/README.md, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py
re: https://github.com/huggingface/diffusers/issues/3658
Also added some docs re: recent much more successful run doing full fine tuning for stage II with larger batch sizes.
https://wandb.ai/williamberman/dreambooth/runs/4bwrpro7/overview?workspace=user-williamberman 
I didn't have as much success with LoRA for larger batch sizes but the docs note we recommend full finetuning stage II for faces anyway
https://wandb.ai/williamberman/dreambooth-lora/runs/cdtpa4l7?workspace=user-williamberman 
Unfortunately the docs are a bit "here's all the information" rather than "here's how to do a successful training run". But I think that's the best they can be right now
=> dreambooth upscaling fix added latents

src/diffusers/models/activations.py, src/diffusers/models/attention.py, src/diffusers/models/embeddings.py, src/diffusers/models/resnet.py, src/diffusers/models/unet_1d_blocks.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py, tests/models/test_activations.py
re: https://github.com/huggingface/diffusers/pull/3302
=> move activation dispatches into helper function

docs/source/en/using-diffusers/other-formats.mdx
Fixes the link to the `load_lora_weights` function.
=> [docs] Fix link to loader method

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_latent_upscale.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
refactored stable diffusion 4x upscaler( see discussion here https://github.com/huggingface/diffusers/issues/3654)
test
```python
from diffusers import StableDiffusionUpscalePipeline
import torch
model_id = "stabilityai/stable-diffusion-x4-upscaler"
pipeline = StableDiffusionUpscalePipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipeline = pipeline.to("cuda")
url = "https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd2-upscale/low_res_cat.png"
low_res_img = Image.open(BytesIO(response.content)).convert("RGB")
low_res_img = low_res_img.resize((128, 128))
prompt = "a white cat"
generator = torch.Generator(device="cuda").manual_seed(0) …
```
=> refactor Image processor for x4 upscaler

src/diffusers/loaders.py
Closes: https://github.com/huggingface/diffusers/issues/3688
=> feat: when using PT 2.0 use LoRAAttnProcessor2_0 for text enc LoRA.

src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_prior.py
- use the correct Prior hub model id
- use the new names in KandinskyPriorPipelineOutput
closes #3693
=> Fix the Kandinsky docstring examples

src/diffusers/loaders.py
Fix #3661 
This is because `from_ckpt` uses `FrozenCLIPEmbedder` for `StableDiffusionPipeline` but it should be `FrozenOpenCLIPEmbedder`  in Stable Diffusion 2.x.
The original `download_from_original_stable_diffusion_ckpt` uses a layer that only presents in Stable Diffusion 2.x checkpoint to infer the `model_type`, which is not work with `from_ckpt` because it overrides the param. I think we can just leave the `model_type` empty for Stable Diffusion pipelines and then it will be inferred correctly.
By the way, this PR also fixes some invalid assignments for `model_type`.
=> Fix from_ckpt for Stable Diffusion 2.x

.github/workflows/push_tests.yml
This is just a suspicion, feel free to close.
Both "Slow PyTorch CUDA tests on Ubuntu" and "Slow ONNXRuntime CUDA tests on Ubuntu" use the same runner (`docker-gpu`), and there is 1 machine configured to run those tests. My understanding is that the CI environment will run tests in a matrix in parallel by default, which could be the reason for the weird oom issues.
If this is actually the case, we could maybe reorganize the tests differently so that the "Slow Flax TPU tests", which use a different runner, run in parallel with any of these.
=> [Tests] Run slow matrix sequentially

examples/text_to_image/train_text_to_image_lora.py
If you run the LoRA training script without specifying a seed, the run will crash during the validation stage when it creates a PRNG generator. This is just because `generator.manual_seed(...)` can't take `None` as input, so this PR just checks whether it is not `None`.
Error you get without this fix:
```
Steps:  22%|████████▌                             | 4500/20000 [2:12:18<7:35:53,  1.76s/it, lr=1e-5, step_loss=0.0717]06/05/2023 20:33:40 - INFO - accelerate.accelerator - Saving current state to sd-snoopy-model/checkpoint-4500
06/05/2023 20:33:40 - INFO - accelerate.checkpointing - Model weights saved in sd-snoopy-model/checkpoint-4500/pytorch_model.bin
06/05/2023 20:33:40 - INFO - accelerate.checkpointing - Optimizer state saved in sd-snoopy-model/checkpoint-4500/optimizer.bin …
```
=> Fixes eval generator init in `train_text_to_image_lora.py`

examples/controlnet/train_controlnet.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py, examples/research_projects/intel_opts/textual_inversion/textual_inversion_bf16.py, examples/research_projects/intel_opts/textual_inversion_dfq/textual_inversion.py, examples/research_projects/lora/train_text_to_image_lora.py, examples/research_projects/mulit_token_textual_inversion/textual_inversion.py, examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py, examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, examples/unconditional_image_generation/train_unconditional.py
Applies deprecation on `logging_dir` which have been slated since December of last year, and really should've been removed two versions ago in Accelerate but got pushed to the latest release.
=> Apply deprecations from Accelerate

docs/source/en/api/pipelines/kandinsky.mdx
remove the seeds in the doc because the images are generated with DDPM scheduler and currently not reproducible (will add next week)
also update `prior_guidance_scale=1.0` and `height=768`, `width=768` for better default image generation quality
=> remove seed

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
Investigating it seems like taking the next timestep to generate the noise works better. Investigating after comment here:
- https://github.com/huggingface/diffusers/issues/3730
and very old PR here:
- https://github.com/huggingface/diffusers/pull/328
Conclusion is that the timesteps for adding noise for SD inpainting indeed need to be changed. This was incorrectly implemented in https://github.com/huggingface/diffusers/pull/3533
=> [Stable Diffusion Inpaint & ControlNet inpaint] Correct timestep inpaint

README.md
Replace the dead link to the Flax installation guide by a working one: https://flax.readthedocs.io/en/latest/#installation
=> [Documentation] Replace dead link to Flax install guide

.github/workflows/upload_pr_documentation.yml, src/diffusers/pipelines/controlnet/multicontrolnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_img2img.py, tests/pipelines/controlnet/test_controlnet_inpaint.py
This PR allows **local** saving and loading of multiple controlnets. The following code snippet now works:
```py
#!/usr/bin/env python3
import diffusers
import torch
import os
hugging_face_token = "<insert hugging face token>"
controlnet_dir = f"./edit-anything-v0-4-sd15/"
controlnet_inpaint_dir = f"./control_v11p_sd15_inpaint/"
sd_dir = f"./stable-diffusion-v1-5/"
edit_anything_controlnet = diffusers.ControlNetModel.from_pretrained(
"shgao/edit-anything-v0-4-sd15",
cache_dir=controlnet_dir,
)
edit_anything_controlnet.save_pretrained(controlnet_dir, safe_serialization=True)
inpaint_controlnet = diffusers.ControlNetModel.from_pretrained(
"lllyasviel/control_v11p_sd15_inpaint",
cache_dir=controlnet_inpaint_dir,
) …
```
=> [MultiControlNet] Allow save and load

scripts/convert_kandinsky_to_diffusers.py
update the conversion script for Kandinsky unet - remove the ` KandinskyTextProjModel` to unet (https://github.com/huggingface/diffusers/pull/3308#issuecomment-1543901510)
=> update conversion script for Kandinsky unet

docs/source/en/quicktour.mdx, docs/source/en/training/dreambooth.mdx, docs/source/en/training/lora.mdx, docs/source/en/training/text_inversion.mdx, docs/source/en/tutorials/basic_training.mdx, docs/source/en/using-diffusers/custom_pipeline_examples.mdx, docs/source/en/using-diffusers/custom_pipeline_overview.mdx, docs/source/en/using-diffusers/img2img.mdx, docs/source/en/using-diffusers/loading.mdx, docs/source/en/using-diffusers/other-formats.mdx, docs/source/en/using-diffusers/reproducibility.mdx, docs/source/en/using-diffusers/reusing_seeds.mdx, docs/source/en/using-diffusers/schedulers.mdx, docs/source/en/using-diffusers/stable_diffusion_jax_how_to.mdx, docs/source/en/using-diffusers/using_safetensors.mdx, docs/source/en/using-diffusers/weighted_prompts.mdx, docs/source/en/using-diffusers/write_own_pipeline.mdx
Fixes some Colab cells where the code example doesn't run out of the box because it was a `bash` snippet. Now users just have to uncomment the cell to run it. I've also added notebooks for several other pages that were missing it, and removed the `[[open-in-colab]]` cell from the Training guides because those are mostly focused on using the training script.
=> [docs] Fix Colab notebook cells

.github/ISSUE_TEMPLATE/bug-report.yml
Helps to reduce the initial frictions of tagging specific people from the team. This is something we follow in `transformers`, `peft`, etc. 
Thanks @younesbelkada for this awesome [PR](https://github.com/huggingface/peft/pull/562) as a reference.
=> [Bug Report template] modify the issue template to include core maintainers.

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
This fixes the error thrown when using the legacy inpainting pipeline (after enabling cpu-offloading): `Cannot copy out of meta tensor; no data!`
The error is due to an incorrect reference to `self.device`, instead of the `device` variable calculated from `self._execution_device` (which is already used for other tensors).
I've tested that this successfully generates images with and without cpu-offloading.
Thanks!
=> Fix broken cpu-offloading in legacy inpainting SD pipeline

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, tests/models/test_models_unet_3d_condition.py
Fixes: https://github.com/huggingface/diffusers/issues/3354
=> Fix some bad comment in training scripts

examples/community/unclip_image_interpolation.py
This change is more in line with the DallE-2 paper which describes: 
> The second option (for image interpolation) involves fixing the DDIM latent to a randomly-sampled value for all interpolates in the trajectory. This results in an infinite number of trajectories between x1 and x2, though the endpoints of these trajectories will generally no longer coincide with the original images.
=> UnCLIP Image Interpolation -> Keep same initial noise across interpolation steps

examples/controlnet/train_controlnet.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/test_examples.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, examples/unconditional_image_generation/train_unconditional.py
re: https://github.com/huggingface/diffusers/issues/2466 and https://github.com/huggingface/diffusers/pull/3652 and https://github.com/huggingface/diffusers/issues/3802
see PR comments
=> manual check for checkpoints_total_limit instead of using accelerate

src/diffusers/models/attention_processor.py, src/diffusers/models/modeling_utils.py, tests/models/test_attention_processor.py
re: https://github.com/huggingface/diffusers/issues/3740
this is not ideal but afaik this is the only way to solve this without exposing functionality in accelerate
=> device map legacy attention block weight conversion

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_2.mdx, docs/source/en/api/schedulers/ddim.mdx, docs/source/en/using-diffusers/control_brightness.mdx, docs/source/en/using-diffusers/reusing_seeds.mdx, tests/pipelines/stable_diffusion_2/test_stable_diffusion_v_pred.py
Documents how to enable the new zero SNR parameter (and others from the paper) in the `DDIMScheduler` to generate images with better lighting quality. I added it to this [page](https://huggingface.co/docs/diffusers/v0.17.1/en/using-diffusers/reusing_seeds) as a more general doc on how to improve image quality since it felt a little too specific (as I understand, its only limited to the `DDIMScheduler` for now) to include [here](https://huggingface.co/docs/diffusers/v0.17.1/en/stable_diffusion) as suggested by @sayakpaul. Let me know what you think!
=> [docs] Zero SNR

docs/source/en/api/pipelines/stable_diffusion/ldm3d_diffusion.mdx, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py
Typo in the LDM3D pipeline - fixed
=> [ldm3d] Fixed small typo

examples/text_to_image/README.md, examples/text_to_image/train_text_to_image.py
Currently, our training examples include limited information in the model cards. For example, one doesn't know how the code should be run with the model artifact(s) from the training examples just by taking a look at the corresponding model repository (such as [this one](https://huggingface.co/sayakpaul/lora-trained)).
We can improve this.  
So, to that end, this PR modifies the `train_text_to_image.py` to include a code snippet in the model card that we create from the example itself. Additionally, it includes the following things in the model card for a better developer experience which can be enabled directly from the Hub:
* Info on key training hyperparameters
* Dataset (and properly links that to the model card metadata)
* Weights and Biases run page when available (which discloses …
=> [Examples] Improve the model card pushed from the `train_text_to_image.py` script

docs/source/en/api/pipelines/overview.mdx, docs/source/en/api/pipelines/stable_diffusion/overview.mdx
This PR adds the missing pipelines from the overview pages that we have under the docs for our pipelines.
=> [Docs] add missing pipelines from the overview pages and minor fixes

src/diffusers/models/controlnet.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
I'd like to be able to load [TemporalNet2](https://huggingface.co/CiaraRowles/TemporalNet2) into a ControlNetModel.
This ControlNet concatenates the previous image in a video and the optical flow together to form a 6-channel tensor as the control image.
At the moment the [`convert_original_controlnet_to_diffusers.py`](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_controlnet_to_diffusers.py) script does not support converting the checkpoint, raising the following error due to the control image having more channels than expected:
<details>
<summary>Traceback</summary>
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/jcbgb/anaconda3/envs/maua/lib/python3.10/runpy.py:196 in _run_module_as_main …
```
=> Support ControlNet models with different number of channels in control images

docs/source/en/api/pipelines/kandinsky.mdx, src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py, src/diffusers/schedulers/scheduling_ddpm.py
This PR will refactor Kandinsky pipelines to work with both ddpm and ddim scheduler 
@sayakpaul @patrickvonplaten 
currently the scheduler config in Kandinsky repo is for ddim, is there anyway we can also save ddpm scheduler config some where? instead having to manually create the ddpm config when user wants swap it the scheduler? 
```python
from diffusers import KandinskyPipeline, KandinskyPriorPipeline, DDPMScheduler
import torch
device = "cuda"
prompt= "red cat, 4k photo"
pipe_prior = KandinskyPriorPipeline.from_pretrained("kandinsky-community/kandinsky-2-1-prior")
pipe_prior.to("cuda")
generator = torch.Generator(device=device).manual_seed(0)
out = pipe_prior(prompt, num_inference_steps=5, generator=generator, )
image_emb = out.image_embeds
zero_image_emb = …
```
=> Add ddpm kandinsky

src/diffusers/training_utils.py
Fixes: https://github.com/huggingface/diffusers/actions/runs/5322349636/jobs/9638675888#step:7:13247
```
FAILED tests/others/test_training.py::TrainingTests::test_training_step_equality - AttributeError: 'builtin_function_or_method' object has no attribute 'seed'
```
Tested on V100 and the environment as configured in https://github.com/huggingface/diffusers/blob/main/.github/workflows/push_tests.yml.
=> fix: random module seeding

docs/source/en/optimization/habana.mdx
=> Update Habana Gaudi doc

src/diffusers/models/unet_2d_condition.py
Fix problem introduced here (`aug_emb` may be undefined): https://github.com/huggingface/diffusers/commit/50df26c1411c7f5c3c7973815b367ea5f31071a7#diff-82dc116be034805ec08e24069d853854b00fe559f5178b87269653fa43d1e7c8R825
The alternative is to go back to running `emb = emb + aug_emb` inside all the `if` branches. Which one do you like better @patrickvonplaten?
=> Fix embeddings for classic models

src/diffusers/models/resnet.py
Fixes #198 
Request for Review: @patrickvonplaten
=> feat: rename single-letter vars in `resnet.py`

examples/text_to_image/train_text_to_image_lora.py
・Add LoRA rank and network_alpha args in train_text_to_image_lora.py
=> [Enhance] Add LoRA rank args in train_text_to_image_lora

src/diffusers/models/attention.py, src/diffusers/models/attention_processor.py, src/diffusers/models/unet_3d_condition.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py, tests/models/test_models_unet_3d_condition.py
This PR allows to run https://huggingface.co/cerspense/zeroscope_v2_XL with ~12 GB VRAM by adding **feed-forward-chunking** (see [here](https://huggingface.co/blog/reformer#chunked-feed-forward-layer-in-reformer)).
This can be very useful for extremely memory-intensive use cases such as video-to-video and text-to-video but could in the future also make sense for text-to-image.
With this PR I can generate **36 frames** with https://huggingface.co/cerspense/zeroscope_v2_XL using less than 13GB aof VRAM.
The following works on a 50% fraction of a 24GB RTX4090:
```py
import torch
from diffusers import DiffusionPipeline, DPMSolverMultistepScheduler
torch.cuda.set_per_process_memory_fraction(0.5)
pipe = …
```
=> Improve memory text to video

docs/source/en/api/pipelines/text_to_video.mdx, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py
As noted by  in https://github.com/huggingface/diffusers/pull/3930#issuecomment-1618916506 automatically enabling forward chunking significantly hurts inference speed so it should **not** be enabled by default.
=> revert automatic chunking

src/diffusers/configuration_utils.py, src/diffusers/schedulers/scheduling_ddim.py, src/diffusers/schedulers/scheduling_ddim_parallel.py, src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_parallel.py, src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, src/diffusers/schedulers/scheduling_pndm.py, src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/others/test_config.py, tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py, tests/pipelines/stable_diffusion/test_stable_diffusion_pix2pix_zero.py, tests/schedulers/test_scheduler_euler.py, tests/schedulers/test_scheduler_euler_ancestral.py, tests/schedulers/test_scheduler_lms.py, tests/schedulers/test_scheduler_unipc.py, tests/schedulers/test_schedulers.py
Refer to previous discussions in #3929.
=> Add `timestep_spacing` and `steps_offset` to schedulers

src/diffusers/models/unet_2d_condition.py, tests/models/test_models_unet_2d_condition.py
This PR addresses [previous concerns](https://github.com/huggingface/diffusers/issues/3327) that the output of the UNet's forward pass is not copy-able. The root cause appears to be because [copy fails on collections.OrderedDict dataclass with required args](https://github.com/python/cpython/issues/105736). The solution presented sets a default value for `sample` such that is it no longer a required parameter of the output class while still erroring when missing since the default setting is `None` ([link](https://github.com/huggingface/transformers/pull/8989) to similar solution for different model).
Reproduction Instructions:
```python
from diffusers.utils import BaseOutput
from dataclasses import dataclass
import copy
@dataclass
class NetParams(BaseOutput):
sample: torch.FloatTensor
m = …
```
=> Make `UNet2DConditionOutput` pickle-able

src/diffusers/models/unet_3d_blocks.py, src/diffusers/models/unet_3d_condition.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py
Fixes https://github.com/huggingface/diffusers/issues/3915
`torch.compile()` for the `repeat_interleave()` function was added in a nightly build. See: https://github.com/pytorch/pytorch/issues/99929.
So, once I upgraded to Torch 2.1 nightly, the issue went away. However, there were other issues which are fixed in this PR. The PR takes inspiration from https://github.com/huggingface/diffusers/pull/3313/. 
Even though we're able to successfully compile the model, it takes a hefty amount of time after `torch.compile()` is called on the UNet:
```python
import torch
pipe = DiffusionPipeline.from_pretrained("cerspense/zeroscope_v2_576w", torch_dtype=torch.float16) …
```
=> [Text-to-video] Add `torch.compile()` compatibility

src/diffusers/models/unet_2d_condition.py, src/diffusers/models/unet_2d_condition_flax.py, src/diffusers/models/unet_3d_condition.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
For now let's disable the use of number of attention heads. This will need further investigation for a future release.
=> disable num attenion heads

docs/source/en/using-diffusers/loading.mdx
=> fix/doc-code: import torch and fix the broken document address

src/diffusers/loaders.py, src/diffusers/models/modeling_utils.py, src/diffusers/pipelines/pipeline_utils.py
typo in safetensors (safetenstors)
#3975 
=> typo in safetensors (safetenstors)

examples/dreambooth/train_dreambooth_lora.py
Fixes #3944, similiar to the already landed #3866.
=> Add 'rank' parameter to Dreambooth LoRA training script

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Replaces bare prints in some modules with logger.warning. Why?
- Gives end user more control over the output of their program
- Gives more information about the source of the message
- There's literally no reason not to use logger
=> Don't use bare prints in a library

src/diffusers/pipelines/stable_diffusion_xl/__init__.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
Make sure prompt embeddings can be passed to SD-XL.
Fixes #3970
=> Add sdxl prompt embeddings

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Make sure torch compile works for SDXL on different devices. On some GPU (like T4), PyTorch's compile changes the unet object to a function, which means it can't access the config anymore
=> Make sure torch compile doesn't access unet config

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/test_pipelines.py
Thanks for pointing out this problem @vladmandic . Upon thinking about it, I don't think we should even allow default to fp32 when trying to load "fp16" variants. Added a deprecation warning now.
Note that one can very easily test with this function if the variant is present: https://github.com/huggingface/diffusers/pull/4011/files#r1257526906
So ideally this should be done before downloading - e.g. via:
```py
from huggingface_hub import model_info
info = model_info("<your/repo/id>")
filenames = {sibling.rfilename for sibling in info.siblings}
```
We can however also very easily check post-download what variants have been downloaded as shown here: https://github.com/huggingface/diffusers/pull/4011#discussion_r1257526906
=> [DiffusionPipeline] Deprecate not throwing error when loading non-existant variant

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
This is a continuation of #3979 
@xiaohu2015 noticed this bug, but I'm not seeing memory savings in my system for SDXL (maybe it's a cuda cache problem). @williamberman do you remember how you tested it on the upscale pipeline?
=> Correctly keep vae in `float16` when using PyTorch 2 or xFormers

docs/source/en/index.mdx
Currently, the Reference button on `v0.18` is broken, but it works on the `main` version of the docs.
=> [docs] Fix index page 

docs/source/en/training/dreambooth.mdx, examples/dreambooth/README.md, examples/dreambooth/README_sdxl.md, examples/dreambooth/requirements_sdxl.txt, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/test_examples.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
Adds a training script to support fine-tuning SDXL with DreamBooth and LoRA. On top of https://github.com/huggingface/diffusers/pull/3896. Since the conflicts are brutal this PR exists. 
* No support for text encoder yet as the modifications are reasonably sized.
* The training artifacts are available here: https://huggingface.co/diffusers/lora-trained-xl (private, only visible to the diffusers team members for now).
Used the following command to do a test run:
```bash
export MODEL_NAME="diffusers/stable-diffusion-xl-base-0.9"
export INSTANCE_DIR="dog"
export CLASS_DIR="dog-class"
export OUTPUT_DIR="lora-trained-xl"
accelerate launch train_dreambooth_lora_sdxl.py \
--pretrained_model_name_or_path=$MODEL_NAME  \
--instance_data_dir=$INSTANCE_DIR \ …
```
=> [Examples] Add a training script for SDXL DreamBooth LoRA

src/diffusers/pipelines/pipeline_utils.py
In https://github.com/huggingface/diffusers/pull/2515, the implementation to load models has being refactored to make loading faster. However, the `force_download` parameter is not respected anymore. This PR fixes it.
Though `force_download` is a very niche use case, it is still useful when one wants to be sure to restart from scratch, no matter if there cache system got corrupted. It also ease things when debugging (for context: https://github.com/huggingface/huggingface_hub/issues/1549)
=> FIX `force_download` in download utility

src/diffusers/configuration_utils.py, tests/others/test_config.py
Changes the type of _use_default_values kwarg from set to list in register_to_config decorator
Fixes https://github.com/huggingface/diffusers/issues/4039
=> keep _use_default_values as a list type

src/diffusers/pipelines/audioldm/pipeline_audioldm.py
This PR fixes a small typo in the example docstring of the __call__ method of the AudioLDMPipeline class, that made the example give an error.
Specifically:
```
>>> audio = pipe(prompt).audio[0]
```
should be 
```
>>> audio = pipe(prompt).audios[0]
```
@sanchit-gandhi
=> Typo fix in example docstring in audioldm pipeline

src/diffusers/models/README.md
@stevenliu and @yiyixu,
Corrected the link to the models documentation in the README. Previously, the link was pointing to an incorrect URL. Now, the link directs users to the correct documentation page for more details on the models.
Thanks! 🙌
=> 📝 Fix broken link to models documentation

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.mdx
=> Correct sdxl docs

docs/source/en/api/pipelines/panorama.mdx, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py, tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py
This pull request addresses the issue mentioned in https://github.com/huggingface/diffusers/issues/4024. The proposed solution aims to achieve artifact-free panorama generation by seamlessly **aligning the content on the left and right sides of the generated image**, creating a proper “panorama”, viewable in 360 panoramas viewers.
In the existing MultiDiffusion approach, the image is cropped from left to right with a specified stride. To enable circular padding and support the desired 360-degree scenario, this PR introduces additional crops after the rightmost point of the image. **Circular padding allows the model to “see” the transition from the rightmost part of the image to the leftmost part, maintaining consistency in 360-sense**.
Furthermore, modifications are made to the decoding …
=> Add circular padding for artifact-free StableDiffusionPanoramaPipeline

.github/workflows/pr_tests.yml
Similar to the config in [transformers](https://github.com/huggingface/transformers/blob/fabe17a726bbf6081cfbcc975d8ac451a81f3e2d/.github/workflows/self-push.yml#L11) and [datasets](https://github.com/huggingface/datasets/blob/d6a61a1af1502677a6f2333896a6ffeede9ca21b/.github/workflows/ci.yml#L10). The goal is to trigger the tests without having to create a dumb PR (like [this one](https://github.com/huggingface/diffusers/pull/3633#issuecomment-1571773934)). Will be helpful for future pre-releases of `huggingface_hub`.
=> Trigger CI on ci-* branches

examples/controlnet/train_controlnet.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py, examples/research_projects/intel_opts/textual_inversion/textual_inversion_bf16.py, examples/research_projects/intel_opts/textual_inversion_dfq/textual_inversion.py, examples/research_projects/lora/train_text_to_image_lora.py, examples/research_projects/mulit_token_textual_inversion/textual_inversion.py, examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py
Fixes #3954.
@sayakpaul @muellerzr
=> Multiply lr scheduler steps by `num_processes`.

examples/community/README.md, examples/community/iadb.py
This PR is for the implementation of a new community pipeline.
It is for the implementation of the [α-(de)Blending: a Minimalist Deterministic Diffusion Model](https://arxiv.org/abs/2305.03486) paper.
It is a simple and minimalist diffusion model.
The following code shows how to use the IADB pipeline to generate images using a pretrained celebahq-256 model.
```python
pipeline_iadb = DiffusionPipeline.from_pretrained("thomasc4/iadb-celebahq-256", custom_pipeline='iadb')
pipeline_iadb = pipeline_iadb.to('cuda')
output = pipeline_iadb(batch_size=4,num_inference_steps=128)
for i in range(len(output[0])):
plt.imshow(output[0][i])
plt.show()
```
Sampling with the IADB formulation is easy, and can be done in a few lines (the pipeline already implements it):
```python
def sample_iadb(model, x0, …
```
=> [Community] Implementation of the IADB community pipeline

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
This PR forces `accelerate` to be installed to fix: https://github.com/huggingface/diffusers/pull/4041#discussion_r1262169123
=> [From Single File] Force accelerate to be installed

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.mdx, src/diffusers/__init__.py, src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/__init__.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/utils/dummy_torch_and_transformers_and_invisible_watermark_objects.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py
This PR solves: https://github.com/huggingface/diffusers/issues/4080 and is ready for a review.
Inpainting works well for both the vanilla case and the "Ensemble of Expert Denoisers case".
You can try the following to see for yourself:
```py
import torch
from diffusers import StableDiffusionXLInpaintPipeline
pipe = StableDiffusionXLInpaintPipeline.from_pretrained(
"stabilityai/stable-diffusion-xl-base-0.9", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_ …
```
=> [SD-XL] Add inpainting

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
This PR makes sure `accelerate` doesn't need to be installed to load models locally to fix: https://github.com/huggingface/diffusers/pull/4041#discussion_r1262913121
=> [From single file] Make accelerate optional

setup.py
This PR makes `setup.py` compatible with `pipenv`. Currently, installation of `diffusers` from source using `pipenv` is broken (see: https://github.com/pypa/pipenv/issues/5167#issuecomment-1349316531) and fails with the error:
`AttributeError: 'Subscript' object has no attribute 's'`
The same fix was recently merged in https://github.com/huggingface/transformers/pull/24789
=> Make setup.py compatible with pipenv

examples/dreambooth/train_dreambooth_lora.py
`rank` didn't work after [this PR](https://github.com/huggingface/diffusers/pull/3778).
=> [Enhance] Add rank in dreambooth

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fixes https://github.com/huggingface/diffusers/issues/4108
When loading a SDXL model using `from_single_file()`, the returned pipeline is always an instance of `StableDiffusionXLPipeline`. This means that if you try to load a model into a `StableDiffusionXLImg2ImgPipeline` the returned pipeline is always `StableDiffusionXLPipeline` instead. This fix now respects the passed in `pipeline_class` argument to allow the user to pick which SDXL pipeline they would like to use with the model.
@patrickvonplaten 
Anyone in the community is free to review the PR once the tests have …
=> Fixed SDXL single file loading to use the correct requested pipeline class

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, tests/pipelines/controlnet/test_controlnet.py
Hey @patrickvonplaten and @sayakpaul!
In the latest implementation that added `control_guidance_start` and `control_guidance_end`, the code that computes `controlnet_keep` uses `len(keeps) == 1` to decide whether to `controlnet_keep` should be a list of floats or list of lists.
But ControlNetPipelines supplied with a **list of one ControlNetModel** initializes a MultiControlNetModel as well.
This causes a bug when a ControlNetPipeline is supplied with a **list of one ControlNetModel** because that initializes a MultiControlNetModel but `controlnet_keep` is computed as a list of floats.
On runtime an error will be raised when computing `cond_scale` at each timestep - `TypeError: can't multiply sequence by non-int of type 'float'`.
This fix changes the following in the 3 ControlNetPipeline …
=> Fix bug in ControlNetPipelines with MultiControlNetModel of length 1

src/diffusers/loaders.py, src/diffusers/models/attention_processor.py, tests/models/test_lora_layers.py
Fixes #4178. The unloading lora logic now respects `LoRAXFormersAttnProcessor` and I also consolidated all lora related attention processors in a single place so they can be referenced from other parts of the codebase (already found 2 sites that needed it and replaced them).
=> Fix unloading of LoRAs when xformers attention procs are in use

setup.py, src/diffusers/dependency_versions_table.py
Following `transformers`, let's make `safetensors` a required dependency: https://github.com/huggingface/transformers/pull/23254/files
=> [Safetensors] make safetensors a required dep

src/diffusers/pipelines/pipeline_utils.py
This PR make `enable_sequential_cpu_offload` more generic for third-party devices.
---
I noticed that in https://github.com/huggingface/diffusers/pull/4114,   `enable_sequential_cpu_offload` has been refactored to be more generic for other devices.
But inside the function `enable_sequential_cpu_offload`, we use `torch.cuda.empty_cache` to release all unoccupied cache memory, which has no effect for other devices (such as `xpu`)
https://github.com/huggingface/diffusers/blob/7a47df22a5db7366f83a943ea5f56f509a9a0330/src/diffusers/pipelines/pipeline_utils.py#L1128-L1130
We could change `torch.cuda.empty_cache()` with another from outside, like
```diff
+ torch.cuda.empty_cache = torch.xpu.empty_cache
device = torch.device("xpu")
pipeline.enable_sequential_cpu_offload(device=device)
```
but it …
=> make enable_sequential_cpu_offload more generic for third-party devices

examples/controlnet/train_controlnet_sdxl.py
Fixes the issues from https://github.com/huggingface/diffusers/pull/4038:
* https://github.com/huggingface/diffusers/pull/4038#discussion_r1266078401
* https://github.com/huggingface/diffusers/pull/4038#discussion_r1266079209
Related to: https://github.com/huggingface/diffusers/issues/4089
=> [SDXL ControlNet Training] Follow-up fixes

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_img2img.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_inpaint.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_controlnet.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_controlnet_img2img.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_img2img.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_inpainting.py, src/diffusers/pipelines/shap_e/pipeline_shap_e.py, src/diffusers/pipelines/shap_e/pipeline_shap_e_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/pipelines/kandinsky/test_kandinsky_img2img.py, tests/pipelines/test_pipelines_common.py
had the same bug in all Kandinsky pipelines when we disabled classifier free guidance. 
Fixed for all the Kandinsky pipelines in this PR. Also added a test to `PipelineTesterMixin` so this won't happen again. I think it's something very often not tested but nonetheless, a mistake we do not want. 
this PR fix https://github.com/huggingface/diffusers/issues/4183
also will replace this one that I had forgotten about https://github.com/huggingface/diffusers/pull/3845
=> fix no CFG for kandinsky pipelines

src/diffusers/pipelines/pipeline_utils.py
This PR fixes the workflow when loading a diffusers pipeline. Since https://github.com/huggingface/diffusers/pull/3447, if any error happens while fetching model metadata (i.e. the `model_info(...)` call), we force `local_files_only=True` to try to load the model from cache even if the Hub is down. The side effect of this is that if a valid error happens (repository not found or gated repo error), it is silently ignored and the user gets a non-explicit _"file not found"_ error.
This PR fixes this by re-raising the initial error when the model is not found locally. A custom message is added to let the user know that we tried to fetch the model locally but it's not there.
(initially reported by @osanseviero in [private slack](https://huggingface.slack.com/archives/C03V11RNS7P/p16901858821060 …
=> Raise initial HTTPError if pipeline is not cached locally

src/diffusers/pipelines/pipeline_utils.py
Makes sure `from_pretrained(...)` for pipeline utils is correctly displayed cc @stevhliu
=> [Docs] Fix from pretrained docs

examples/controlnet/train_controlnet_sdxl.py, examples/test_examples.py, src/diffusers/models/controlnet.py, tests/pipelines/controlnet/test_controlnet_sdxl.py
Fixes https://github.com/huggingface/diffusers/issues/4206. Additionally
* adds a test for SDXL ControlNet training. 
* adds licensing to the model card so that repos can have public visibility be default
=> [ControlNet SDXL training] fixes in the training script

src/diffusers/loaders.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fixes: https://github.com/huggingface/diffusers/issues/4194
=> [From Single File] Allow vae to be loaded

docs/source/en/training/lora.mdx, src/diffusers/loaders.py, src/diffusers/models/attention.py, src/diffusers/models/attention_processor.py, src/diffusers/models/lora.py, src/diffusers/models/transformer_2d.py, tests/models/test_layers_utils.py, tests/models/test_lora_layers.py
This PR is a revival of the original #3756 (as discussed in https://github.com/huggingface/diffusers/pull/3756#issuecomment-1640399984). Majority of the credits goes to @takuma104  on making the original PR as well as  explaining the impacts/changes in detail. On top of that work, I've moved the text encoder patching parts to a modular notion (as done in #3778), added support for `unload_loras()` with the auxiliary parts, as well as general cleanups / test fixes.
Fixes #3725
On a LoRA model for a [random pet](https://civitai.com/models/24380/minty-doges-doge-style-lora), the current revision of diffusers produces a related although not super precise image:
And with this PR, it now looks like the original "pet" that the LoRA trained with:
=> Load Kohya-ss style LoRAs with auxilary states

src/diffusers/models/lora.py, src/diffusers/models/transformer_2d.py
For some reason one cannot create a parent class of `nn.Conv2d` and then call `super().forward(...)` in it with `torch.compile`.
See issue: https://github.com/huggingface/diffusers/issues/4305
=> [Torch.compile] Fixes torch compile graph break

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Hi, long time no see. Great progress here.
I noticed a small bug that prevented the successful conversion of SDXL. 
```
File "scripts/convert_original_stable_diffusion_to_diffusers.py", line 138, in <module>
pipe = download_from_original_stable_diffusion_ckpt(
File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1545, in download_from_original_stable_diffusion_ckpt
pipe = pipeline_class(
TypeError: __init__() got an unexpected keyword argument 'text_encoder_2'
```
cc: @patrickvonplaten @sayakpaul
=> Fix SDXL conversion from original to diffusers

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_upscale.py
fix a bug described here
https://github.com/huggingface/diffusers/issues/4249#event-9910237695
this example currently fails but will work with this fix
```python
from diffusers import StableDiffusionUpscalePipeline
import torch
model_id = "stabilityai/stable-diffusion-x4-upscaler"
pipeline = StableDiffusionUpscalePipeline.from_pretrained(
model_id, revision="fp16", torch_dtype=torch.float16
)
pipeline = pipeline.to("cuda")
url = "https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd2-upscale/low_res_cat.png"
low_res_img = Image.open(BytesIO(response.content)).convert("RGB")
low_res_img = low_res_img.resize((128, 128))
prompt = "a white cat"
prompt_embeds = …
```
=> fix a bug in StableDiffusionUpscalePipeline when `prompt` is `None`

src/diffusers/pipelines/pipeline_utils.py, tests/models/test_lora_layers.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_instruction_pix2pix.py, tests/pipelines/test_pipelines.py, tests/pipelines/test_pipelines_common.py
This PR fixes both #4307 and #4311 and adds a test so that such an error does not happen again.
Also let's make sure to not add `local_files_only=True` to our regular slow tests since this would mean the test unnecessarily break for people that don't have access to the internet cc @sayakpaul @yiyixuxu
=> [Local loading] Correct bug with local files only

src/diffusers/loaders.py
Removes the assumption of fixed middle blocks (e.g. there are SDXL Kohya-SS style LoRAs with one middle layer). Also treats block ids as they are present in the state dict, not sequentially ordered keys. E.g. with a state dict that only modified input blocks 6, 8, 5, 4 the previous mapping treated them as if they were 0, 1, 2, 3.  
Based on top of PR #4287
=> fix: dynamic SGM block mapping for SDXL kohya loras

src/diffusers/loaders.py, src/diffusers/models/transformer_2d.py
Uses lora compatible layers for proj_in/proj_out processors for #4287 which helps loading Kohya-SS style SDXL loras that modify those layers.
=> Use lora compatible layers for linear proj_in/proj_out

examples/community/composable_stable_diffusion.py
Correct doc string for the default value of guidance_scale=5.0
=> correct doc string for default value of guidance_scale

examples/instruct_pix2pix/README_sdxl.md
Previously was asked to provide more information about the findings when training the Instruct Pix2Pix SDXL version, which has now been updated in the README_sdxl.md document.
=> [SDXL-IP2P] Add gif for demonstrating training processes

src/diffusers/pipelines/stable_diffusion_xl/__init__.py
This PR fixes a "file not found" error when transformers and/or torch is not installed as reported in https://github.com/huggingface/diffusers/issues/4356
=> doing a patch release for 0.19.3
=> [SDXL] Fix dummy imports incorrect naming

src/diffusers/models/unet_1d.py
highlighting the way the modules are actually fed in the main code as the order matters because no skip block attaches time embeds whilst others do not
reflects the order of the modules as fed in unet1d as the order in the original doc is wrong will give an error when used as default args. the order matters as time step embeds are used in noskip blocks but not in the other blocks.
@sayakpaul @patrickvonplaten
=> Update docs of unet_1d.py

docs/source/en/api/pipelines/kandinsky.md, src/diffusers/pipelines/auto_pipeline.py
correct incorrect naming of `AutoPipelineForText2Image`
=> [AutoPipeline] Correct naming

tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py
Address precision issues with some flaky slow tests in the `stable diffusion` module. 
1. Set `pipe.unet.set_default_attn_processor()` to use default attention on failing tests. 
2. Update expected slices where necessary. And use float32 numpy arrrays when comparing slices.    
3. Lower precision on `panorama` pipeline after inspecting output arrays. 
=> Cleanup pass for flaky Slow Tests for Stable diffusion

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
This PR adds support to use from_single_file for `StableDiffusionXLInpaintPipeline`
fix 
https://github.com/huggingface/diffusers/issues/4402
and 
https://github.com/huggingface/diffusers/issues/4354
```python
from diffusers import StableDiffusionXLInpaintPipeline, StableDiffusionXLPipeline
import torch
img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"
init_image = load_image(img_url).convert("RGB")
mask_image = load_image(mask_url).convert("RGB")
prompt = "A majestic tiger sitting on a bench"
pipe = …
```
=> support from_single_file for SDXL inpainting 

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Fixes #4391 where the `guidance_scale` should be 5.0 instead of 7.5.
https://github.com/huggingface/diffusers/blob/de9c72d58c3eb4bcd50901d0c23c7c46f0cec29b/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L567
=> [docs] Fix SDXL docstring

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_diffedit.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_model_editing.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_paradigms.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py
re: https://github.com/huggingface/diffusers/issues/4349
=> can call encode_prompt with out setting a text encoder instance variable

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
- Bypass requests with config files option added to download_from_original_stable_diffusion_ckpt
- Adds local_files_only flags to all from_pretrained requests
Adds `local_files_only` flag to all from_pretrained calls within `download_from_original_stable_diffusion_ckpt` function and allows config files to be passed to the function in order to prevent online access via requests when no config file is provided. 
This allows developers to take advantage of logic within the function which sorts what model type is being loaded and choose the appropriate config file without requiring online access via `requests` call.
=> Prevent online access when desired when using download_from_original_stable_diffusion_ckpt

src/diffusers/pipelines/controlnet/pipeline_controlnet.py
Default value of `control_guidance_start` and `control_guidance_end` in `StableDiffusionControlNetPipeline.check_inputs` function causes `TypeError: object of type 'float' has no len()`
Proposed fix: 
Convert `control_guidance_start` and `control_guidance_end` to type list if float
Fixes #4269
@holwech
=> auto type conversion

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
Fix handling of `MultiControlNetModel`s that contain only one control net.
The code will run into `TypeError: can't multiply sequence by non-int of type 'float'` when trying to compute the conditioning scale for a `MultiControlNetModel` with a single ControlNet.
@patrickvonplaten @williamberman
=> Fix typerror in pipeline handling for MultiControlNets which only contain a single ControlNet

examples/dreambooth/train_dreambooth_lora_sdxl.py
Adds the LoRa rank argument to the SDXL Dreambooth LoRa training script.
@sayakpaul
=> Add rank argument to train_dreambooth_lora_sdxl.py

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/distilled_sd.md
Adds a guide comparing inference times for original Stable Diffusion, distilled Stable Diffusion, and distilled Stable Diffusion + Tiny AutoEncoder based on @sayakpaul's notebook.
=> [docs] Distilled SD

Makefile
Currently, when you type `make test-examples`, the associated test cases cannot be run.
This PR fixes this issue.
=> fix typo to ensure `make test-examples`  work correctly

examples/community/stable_diffusion_tensorrt_inpaint.py
This PR support examples/community/stable_diffusion_tensorrt_inpaint.py to run in different strength (0~1).
=> Support different strength for Stable Diffusion TensorRT Inpainting pipeline

src/diffusers/pipelines/kandinsky/pipeline_kandinsky_combined.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py, tests/pipelines/kandinsky/test_kandinsky_combined.py, tests/pipelines/kandinsky_v22/test_kandinsky_combined.py
this PR:
* add `enable_sequential_cpu_offload` and `enable_xformers_memory_efficient_attention` to combined pipelines
* test xformer for combined pipelines
should fix 
https://github.com/huggingface/diffusers/issues/4332
=> a few fix for kandinsky combined pipeline 

tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
Another pass at some flaky precision related test issues in the stable diffusion module. 
1. Use `pipe.unet.set_default_attn_processor` 
2. Lower precision where it makes sense
=> Cleanup Pass on flaky slow tests for Stable Diffusion

examples/textual_inversion/textual_inversion.py
While there was an implementation of multi-token textual inversion that initialized more than one word embedding, the training prompts only used the initial placeholder token string, resulting in only one embedding being trained. My solution was to simply concatenate all the placeholder tokens in the prompts used during training, so when e.g. "A photo of a \<cat-toy\>" would be used, now it will be "A photo of a \<cat-toy\>\<cat-toy\>_1\<cat-toy\>_2", as per the already implemented multi-token scheme.
To test if this method fixes the problem, I tracked the cosine similarity of the trainable embeddings to their initialized embedding as the training progressed, and saw that only the first one was changing. After the proposed PR, all embeddings were changing (see screenshots).
Before PR: …
=> Fixed multi-token textual inversion training

examples/dreambooth/train_dreambooth.py
In the examples, file `train_dreambooth.py`, we can see that `log_validation` function is called only if `global_step % args.validation_steps == 0`. But the method `write_images` takes an epoch instead of global_step, which can be not unique for each global_step(if validation_steps less than epoch).
=> Log global_step instead of epoch to tensorboard

tests/pipelines/audioldm/test_audioldm.py, tests/pipelines/kandinsky/test_kandinsky_img2img.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_diffedit.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_flax.py, tests/pipelines/unidiffuser/test_unidiffuser.py
Moving certain slow tests from important pipelines to nightly. This PR attempts to keep only 1-2 slow tests per pipeline in the push tests while moving others to nightly. 
=> Moving certain  pipelines slow tests to nightly 

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md
Introduce minimalistic reimplementation of SDXL on the SDXL doc. @sayakpaul has generously proposed this idea for diffuser's documentation.
@sayakpaul
=> introduce minimalistic reimplementation of SDXL on the SDXL doc

examples/text_to_image/train_text_to_image_lora_sdxl.py
Fixes push to hub action in `train_text_to_image_lora_sdxl.py` example
- in the last step it failed on missing `instance_prompt`, it seem the function call didn't match parameters
- 
```python
def save_model_card(
repo_id: str,
images=None,
base_model=str,
dataset_name=str,
train_text_encoder=False,
repo_folder=None,
vae_path=None,
)
```
- Training examples: @sayakpaul and @patrickvonplaten
=> Fix push_to_hub in train_text_to_image_lora_sdxl.py example

docs/source/en/using-diffusers/write_own_pipeline.md
Some weeks ago i had a [PR](https://github.com/huggingface/notebooks/pull/411) merged **on the notebooks repo.** It had some changes to the write_your_own_pipeline notebook, but the hf docs builder bot has overwritten the changes in this [commit](https://github.com/huggingface/notebooks/commit/cf3fdd7ad566325a6ec5283f3d2f748381ece393)
you can check the [commit history](https://github.com/huggingface/notebooks/commits/main/diffusers_doc/en/write_own_pipeline.ipynb) 
To me it seems that changing the notebooks on the notebooks repo does nothing, because you have to change to "source code" here in these markdown files. [citation required] If this is the case maybe this should be mentioned in the notebooks repo readme.md so it's clear.
Hello, this PR rewrites two cells in the …
=> Changed code that converts tensors to PIL images in the write_your_own_pipeline notebook

tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py, tests/pipelines/stable_diffusion/test_stable_diffusion_pix2pix_zero.py, tests/pipelines/text_to_video/test_text_to_video.py
Move certain slow tests to nightly. The following modules are not present in this [list of important pipelines](https://github.com/huggingface/diffusers/pull/4431#issuecomment-1662018064) and are some of the slowest tests in the CI/CD pipeline. 
```
tests/pipelines/stable_diffusion/test_stable_diffusion_pix2pix_zero.py
tests/pipelines/stable_diffusion/test_stable_diffusion_panorama.py
```
The `test_full_model` test in `tests/pipelines/text_to_video/test_text_to_video.py` is a similar test to `test_two_step_model` except that it runs for a greater number of inference steps. I propose moving the long running test to nightly and keeping the shorter 2 step test in `SlowTests`  
[here are …
=> Move slow tests to nightly

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md
Reverts huggingface/diffusers#4532
Any chance we can put this on a non-API doc? We should really try to keep API docs clean for diffusers code only
=> Revert "introduce minimalistic reimplementation of SDXL on the SDXL doc"

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/weighted_prompts.md
Adds `.blend()`, `.and()`, and some more syntax examples to the prompt weighting docs to show more interesting use cases.
=> [docs] Expand prompt weighting

examples/community/checkpoint_merger.py, scripts/convert_original_audioldm_to_diffusers.py, scripts/convert_tiny_autoencoder_to_diffusers.py, src/diffusers/commands/fp16_safetensors.py, src/diffusers/loaders.py, src/diffusers/models/modeling_utils.py, src/diffusers/pipelines/pipeline_utils.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py, src/diffusers/utils/__init__.py, src/diffusers/utils/import_utils.py, tests/models/test_modeling_common.py, tests/pipelines/test_pipelines.py
Fixes #4243 
Some tests failing on running `make test`, since I did not add my own tests. 
`make test` summary:
```
================================================== 116 failed, 1941 passed, 1145 skipped, 1098 warnings in 1420.89s (0:23:40) ===================================================
```
@patrickvonplaten @DN6
=> Remove code snippets containing `is_safetensors_available()`

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
Fixes #4578 to use `vae` and `StableDiffusionXLControlNetPipeline`.
=> [docs] Fix ControlNet SDXL docstring

scripts/convert_original_stable_diffusion_to_diffusers.py
Fixed invalid pipeline_class_name parameter.
In the original convert script, the pipeline_class_name argument is not working. I found this problem when I tried to convert the sdxl model. If I don't try to change the pipeline type, I'll get TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'. Change the code is passed to pipeline_class_name =" StableDiffusionXLPipeline " it can work normally.
https://github.com/huggingface/diffusers/issues/4562
Anyone in the community is free to review the PR once the tests have …
=> Fixed invalid pipeline_class_name parameter.

docs/source/en/using-diffusers/loading.md
Fixes missing hyphen in "git-lfs" in diffusers tutorial docs. 
The current docs say "git lfs", which does not use the `git-lfs` library and is not a valid git command which may confuse users.
@stevenliu and @yiyixu
=> Fix git-lfs command typo in docs 

docs/source/en/api/pipelines/controlnet_sdxl.md, examples/research_projects/controlnet/train_controlnet_webdataset.py
This PR adds a brief guide for combining and using multiple conditioning inputs with SDXL.
=> [docs] MultiControlNet

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Currently, loading a custom text encoder with the `from_single_file` method will fail (see linked issue). This PR introduces a fix for the issue. 
cc: @sayakpaul @yiyixuxu Wondering if I should add explicit tests for this case?
#4446
=> fix loading custom text encoder when using `from_single_file`

src/diffusers/loaders.py, tests/models/test_lora_layers.py
Bug: when calling `pipe.load_lora_weights(lora_model_path)` with `lora_model_path` of something like `pytorch_lora_weights.bin` and safetensors is installed, there is a codepath that produces an `UnboundLocalError`:
```
File "/home/diffusers/run_cross_model_evals.py", line 79, in <module>
run_evaluations()
File "/home/diffusers/run_cross_model_evals.py", line 63, in run_evaluations
images_by_model[model_name] = take_samples(lora_file)
File "/home/diffusers/run_cross_model_evals.py", line 42, in take_samples
pipe.load_lora_weights(lora_model_path)                                                                                                                   
File "/home/diffusers/src/diffusers/loaders.py", line 937, in load_lora_weights …
```
=> Fix `UnboundLocalError` during LoRA loading

src/diffusers/models/lora.py, tests/models/test_lora_layers.py
Removes the now moot check which prevented higher rank/dimensional LoRAs used with diffusers.
Fixes #4593
@patrickvonplaten and @sayakpaul
=> Support higher dimension LoRAs

examples/community/README.md, examples/community/lpw_stable_diffusion_xl.py, tests/models/test_lora_layers.py
replace PR:https://github.com/huggingface/diffusers/pull/4629 
This PR added pipeline accepts unlimited size prompt and negative prompt string compatible with A1111 prompt weighting format. 
Fixes: https://github.com/huggingface/diffusers/issues/4559 
@sayakpaul  I recreate a complete new fork and add the new code in this PR, hope no additional commits are coming along, will update the document and provide sample codes once this PR is done. Thanks
```python 
import torch …
```
=> Add SDXL long weighted prompt pipeline (replace pr:4629)

docs/source/en/api/pipelines/unidiffuser.md
This PR modifies the `UniDiffuserPipeline` docs to add a note regarding the fact that the UniDiffuser pipeline currently has numerical stability issues on PyTorch 1.X, which causes the output images to become all `NaN`s or all black. This issue can be mitigated by switching to PyTorch 2.X.
I will try to open a PR to address this issue in the near future, but in the meantime I think it makes sense to note this in the docs until the issue is fixed.
Addresses #3951. …
=> [docs] Add note in UniDiffusers Doc about PyTorch 1.X numerical stability issue

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, tests/pipelines/controlnet/test_controlnet_sdxl.py
Fixes https://github.com/huggingface/diffusers/issues/4664.
Additionally, adds SLOW tests for SDXL ControlNets.
=> [Core] enable lora for sdxl controlnets too and add slow tests.

src/diffusers/loaders.py
Internal thread: https://huggingface.slack.com/archives/C03UQJENJTV/p1692343210344049
=> [LoRA] ensure different LoRA ranks for text encoders can be properly handled

src/diffusers/loaders.py
Fixes: https://github.com/huggingface/diffusers/issues/4697. 
As discussed via Slack, with this (#4697 just popped up) and #4669 merged, I will reflect on https://github.com/huggingface/diffusers/pull/4669/files#r1300597764 in a new PR.
=> [LoRA] default to None when fc alphas are not available.

src/diffusers/utils/testing_utils.py
This is a better method than comparing against a list of supported backends as it allows for supporting any number of backends provided they are installed on the user's system. This should have no effect on the behaviour of tests in Huggingface's CI workers. See transformers#25506 where this approach has already been added.
Changes method of verifying provided test device (via `DIFFUSERS_TEST_DEVICE`) is valid by simply trying to create the device. This approach is now also used in transformers#25506.
@patrickvonplaten @sayakpaul
=> Replaces `DIFFUSERS_TEST_DEVICE` backend list with trying device

scripts/convert_diffusers_to_original_sdxl.py
Fixes # ([4494](https://github.com/huggingface/diffusers/issues/4494))
=> add convert diffuser pipeline of XL to original stable diffusion

tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_img2img.py, tests/pipelines/controlnet/test_controlnet_inpaint.py
This reverts commit 7b07f9812a58bfa96c06ed8ffe9e6b584286e2fd.
These tests should not go to nightly, they need to stay in slow. 
ControlNet is a very important model and [all the original checkpoints](https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main) such as this ones are in non-diffusers format. 
Note that all UIs essentially work with the original format (InvokeAI and SD.Next), so that it's very important that single file loading gives 1-to-1 the expected result.
Let me know if this doesn't make sense cc @sayakpaul @DN6 
Can we revert this PR?
=> Revert "Move controlnet load local tests to nightly (#4543)"

src/diffusers/models/autoencoder_tiny.py, src/diffusers/models/vae.py, tests/models/test_models_vae.py
* Add [-1, 1] -> [0, 1] rescaling to `EncoderTiny`
* Move [0, 1] -> [-1, 1] rescaling from `AutoencoderTiny.decode` to `DecoderTiny` (i.e. immediately after the final conv, as early as possible)
* Fix missing [0, 255] -> [0, 1] rescaling in `AutoencoderTiny.forward`
* Update `AutoencoderTinyIntegrationTests` to protect against scaling issues. The new test constructs a simple image, round-trips it through `AutoencoderTiny`, and confirms the decoded result is approximately equal to the source image. This test checks behavior with and without tiling enabled. This test will fail if new `AutoencoderTiny` scaling issues are introduced.
Raw TAESD weights expect images in [0, 1], but diffusers' convention represents images with zero-centered values in [-1, 1], so `AutoencoderTiny` needs to scale …
=> Fix AutoencoderTiny encoder scaling convention

examples/test_examples.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, tests/models/test_lora_layers.py
Fixes https://github.com/huggingface/diffusers/issues/4566
Fixes #4619 
The checkpointing bug is also evident in #4566. Once this PR is merged will reflect that changes in the LoRA DreamBooth SDXL script too.
=> [Examples] fix checkpointing and casting bugs in `train_text_to_image_lora_sdxl.py`

docs/source/en/api/pipelines/audioldm.md
The PR #3905 updated the pipeline docs for AudioLDM, including adding a section on the output type. This PR corrects the output type from a `StableDiffusionPipelineOutput`, to an `AudioPipelineOutput`.
=> [AudioLDM Docs] Fix docs for output

src/diffusers/pipelines/audioldm/pipeline_audioldm.py
Fixes the [`return_type`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/audioldm#diffusers.AudioLDMPipeline.__call__.return_dict) in the AudioLDM docstring, as per @stevhliu's suggestion: https://github.com/huggingface/diffusers/pull/4737#pullrequestreview-1591936365
=> [AudioLDM Docs] Update docstring

examples/dreambooth/README.md, examples/dreambooth/train_dreambooth.py
Fixes #4313
cc @sayakpaul and @williamberman for dreambooth
=> change validation scheduler for train_dreambooth.py when training IF

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py, src/diffusers/schedulers/scheduling_consistency_models.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_ipndm.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, tests/schedulers/test_scheduler_ipndm.py, tests/schedulers/test_schedulers.py
this pr adds a global `step_index` counter 
for #3950
=> add a step_index counter

tests/models/test_modeling_common.py, tests/models/test_models_unet_2d_condition.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_img2img.py, tests/pipelines/controlnet/test_controlnet_inpaint.py, tests/pipelines/test_pipelines.py, tests/pipelines/test_pipelines_common.py, tests/pipelines/versatile_diffusion/test_versatile_diffusion_dual_guided.py, tests/pipelines/versatile_diffusion/test_versatile_diffusion_mega.py, tests/pipelines/versatile_diffusion/test_versatile_diffusion_text_to_image.py
Certain Mixin Classes and Tests use the sum of the absolute differences between two an expected and output tensor to check if the models/pipelines are behaving as expected. e.g
```
max_diff = (image - new_image).abs().sum()
assert max_diff < 1e-5
```
Using sum leads to more flaky testing behaviour due since small differences over many individual values in the tensors accumulate. Proposing to move this to use the maximum absolute difference between tensors instead. 
e.g
```
max_diff = (image - new_image).abs().max()
assert max_diff < 1e-5
```
Additionally, the `PipelineTesterMixin` has a some tests: `test_from_save_pretrained,  test_from_save_pretrained_variant, test_save_load_float16` etc that tests against precision tolerances but do not currently allow the pipelines inheriting from them …
=> Clean up flaky behaviour on Slow CUDA Pytorch Push Tests 

src/diffusers/pipelines/paint_by_example/image_encoder.py
This PR fixes the currently failing fast test due to a bug in `diffusers` but discovered by `accelerate=0.22.0` - see: https://github.com/huggingface/accelerate/issues/1883
=> [Tests] Fix paint by example

src/diffusers/models/adapter.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py
re: https://github.com/huggingface/diffusers/issues/4427
=> [fix] multi t2i adapter set total_downscale_factor

examples/text_to_image/README_sdxl.md
This PR adds the `madebyollin` VAE, along with an explanation of why it's a good idea to replace the original VAE with it in the SDXL LoRA example, as discussed in #4736.
@sayakpaul
=> [Examples] Add madebyollin VAE to SDXL LoRA example, along with an explanation

examples/community/lpw_stable_diffusion_xl.py
Fix lpw_stable_diffusion_xl empty negative prompt error issue
@sayakpaul I submitted a PR to fix the empty negative prompt throw error issue for `lpw_stable_diffusion_xl.py`.  please help review, Thanks. 
reflect the discussion from: https://github.com/huggingface/diffusers/pull/4661#issuecomment-1690291494
=> fix sdxl_lwp empty neg_prompt error issue

src/diffusers/pipelines/pipeline_utils.py
Make sure no error is triggered in edge-case when `torch_device` is None and pipeline is offloaded. Fixes: #4362 .
=> Torch device

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_upscale.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py
Below script currently fails but will be fixed with this PR (see more details about the error here  https://github.com/huggingface/diffusers/issues/4686
) 
```python
import torch
from diffusers import StableDiffusionUpscalePipeline
model_id = "stabilityai/stable-diffusion-x4-upscaler"
cache_path = "/home/yiyi_huggingface_co/cache"
pipe = StableDiffusionUpscalePipeline.from_pretrained(
model_id,
)
pipe.save_pretrained(cache_path)
pipe = StableDiffusionUpscalePipeline.from_pretrained(
pretrained_model_name_or_path=cache_path,
)
```
currently, when we call `from_pretrained()`,  optional components are treated same as optional kwargs - they are passed to the `init()` directly, but they should be handled as …
=> fix a bug in `from_pretrained` when load optional components

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/pipelines/controlnet/test_controlnet_sdxl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py
Fixes: https://github.com/huggingface/diffusers/issues/4208. 
I don't think we need to immediately support dropping out embeddings as it only affects fine-tuning workflows. 
Testing code:
```python
from diffusers import StableDiffusionXLPipeline
import torch
pipe = StableDiffusionXLPipeline.from_pretrained(
"stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
).to("cuda")
prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
generator = torch.manual_seed(1000)
negative_conditions = {
"original_size": (512, 512),
"target_size": (1024, 1024),
"crops_coords_top_left": (0, 0)
}
image_with_neg_cond = pipe(
prompt=prompt, generator=generator, num_inference_steps=25, negative_conditions=negative_conditions …
```
=> [Core] Support negative conditions in SDXL

docs/source/en/using-diffusers/weighted_prompts.md
Corrects usage for the `.and()` operator.
=> [docs] Fix syntax for compel

src/diffusers/models/controlnet.py
The previous release accidentally broke `torch.compile` for ControlNet for SD 1.5 as discovered in https://github.com/huggingface/diffusers/issues/4731
This PR fixes it. We should probably do a patch release here since the last PR broke functionality that was previously possible. 
cc @sayakpaul
=> [Torch compile] Fix torch compile for controlnet

src/diffusers/loaders.py, tests/models/test_lora_layers.py
=> [SDXL Lora] Fix last ben sdxl lora

docs/source/en/api/pipelines/auto_pipeline.md
Fix docs typo in PipelineForImageToImage name
This PR fix #4792
https://github.com/huggingface/diffusers/issues/4792
I only change
```python
pipe_i2i = PipelineForImageoImage.from_pretrained("runwayml/stable-diffusion-v1-5")
```
to
```python
pipe_i2i = PipelineForImageToImage.from_pretrained("runwayml/stable-diffusion-v1-5")
```
- [√] This PR fixes a typo or improves the docs
@stevhliu and @yiyixuxu
=> Fix docs typo in PipelineForImageToImage name

examples/text_to_image/requirements_sdxl.txt, examples/text_to_image/train_text_to_image_lora_sdxl.py
As discussed in issue #4736, this PR tackles the following tasks:
* Increases the minimum required version of `accelerate` from 0.16.0 to 0.22.0. This prevents unnecessary peaks in GPU memory consumption during checkpointing with mixed-precision.
* Removes casting to float32 before saving to avoid unnecessary increases in GPU memory consumption.
* Removes redundant instantiation of the VAE at the end (already present).
* Deletes unused models before creating the final pipeline.
The command `make test-examples` completed successfully.
The following images were generated using the weights saved in `fp32`:
The following images were generated using the same weights as above, but saved in `fp16`:
Previously, peak memory consumption was borderline on an RTX 4090 during checkpoint and final …
=> [Examples] Save SDXL LoRA weights with chosen precision

src/diffusers/pipelines/auto_pipeline.py, tests/pipelines/test_pipelines_auto.py
This PR fix https://github.com/huggingface/diffusers/issues/4727
We now pass relevant kwargs to `load_config()` when we retrieve the config file 
I only updated for Text2Image here, will update other auto pipelines too if it's ok
=> fix auto_pipeline: pass kwargs to load_config

scripts/convert_original_stable_diffusion_to_diffusers.py
Fix method call signature
```
(ds2) alex@big ~/d/d/scripts (main) [1]> python convert_original_stable_diffusion_to_diffusers.py --from_safetensors --checkpoint_path /home/alex/devel/civtai-checkpoints/ --dump_path /home/alex/devel/civtai-checkpoints
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 1.13.1+cu117 with CUDA 1107 (you have 2.1.0.dev20230318+cu118)
Python  3.10.9 (you have 3.10.10)
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
Memory-efficient attention, SwiGLU, sparse and more won't be available.
Set XFORMERS_MORE_DETAILS=1 for more details
File "/home/alex/devel/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 154, in …
```
=> Fix convert_original_stable_diffusion_to_diffusers script

src/diffusers/models/adapter.py, tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py
Implements the save_pretrained and from_pretrained functions for MultiAdapter models. It follows a similar implementation as in diffusers/pipelines/controlnet/multicontrolnet.py 
Tests that were previously skipped in test_stable_diffusion_adapter.py are now added.
Fixes #4768 
members/contributors who may be interested in your PR. @williamberman
=> Support saving multiple t2i adapter models under one checkpoint

src/diffusers/loaders.py, src/diffusers/models/lora.py, tests/models/test_lora_layers.py
This PR fixes the unfusing issue as discovered by @apolinario [here](https://github.com/huggingface/diffusers/pull/4473#discussion_r1308399705)
=> Fix Unfuse Lora

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
SDXL inpainting rarely works well with `strength=1.0` which surprises many users. The default was copied from SD v1-5. This PR changes the default to 0.9999, to make sure at least some part of the original image is kept in the masked area.
=> [SDXL Inpaint] Correct strength default

tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py
Changing the default strength value for sdxl-inpainting broke the tests (https://github.com/huggingface/diffusers/pull/4858); fixing it here!
=> fix sdxl-inpaint fast test

src/diffusers/pipelines/auto_pipeline.py, tests/pipelines/test_pipelines_auto.py
This PR adds a feature request in https://github.com/huggingface/diffusers/issues/4545
You can now turn regular pipelines into a ControlNet pipeline with `AutoPipeline.from_pipe()`, or vice versa. 
* to create a `StableDiffusionControlNetPipeline` from a `StableDiffusionPipeline`
```python
from diffusers import AutoPipelineForText2Image, AutoPipelineForImage2Image, ControlNetModel
import torch
controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16)
pipe_text2img = AutoPipelineForText2Image.from_pretrained(
"runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16
)
pipe_controlnet =AutoPipelineForText2Image.from_pipe(pipe_text2img, controlnet=controlnet)
```
* to convert it back to `StableDiffusionPipeline` , pass `controlnet=None` …
=> support AutoPipeline.from_pipe between a pipeline and its ControlNet pipeline counterpart

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
The StableDiffusionXLPipeline's `save_lora_weights` method includes unet_lora_layers as a keyword argument, but does not check if it is non-null before attempting to include it in the state dict to be saved:
Curent implementation:
```
def save_lora_weights(
self,
save_directory: Union[str, os.PathLike],
unet_lora_layers: Dict[str, Union[torch.nn.Module, torch.Tensor]] = None,
text_encoder_lora_layers: Dict[str, Union[torch.nn.Module, torch.Tensor]] = None,
text_encoder_2_lora_layers: Dict[str, Union[torch.nn.Module, torch.Tensor]] = None,
is_main_process: bool = True,
weight_name: str = None,
save_function: Callable = None,
safe_serialization: bool = True,
):
state_dict = {}
def pack_weights(layers, prefix):
layers_weights = layers.state_dict() if isinstance(layers, torch.nn.Module) else …
```
=> check for unet_lora_layers in sdxl pipeline's save_lora_weights method

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/test_pipelines_combined.py
As I'm working on the fine tune training script for Kandinsky, I noticed when we use the combined pipeline to load both prior and decoder pipelines together, we can't pass the prior pipeline's components, e.g. we will not be able to do this 
```python
pipe = AutoPipelineForText2Image.from_pretrained(
"kandinsky-community/kandinsky-2-2-decoder", 
prior_image_encoder = image_encoder)
```
Below test currently fails, but will be fixed with this PR 
```python
from diffusers import AutoPipelineForText2Image, DDPMScheduler, UnCLIPScheduler
import torch
pipe = AutoPipelineForText2Image.from_pretrained(
"kandinsky-community/kandinsky-2-2-decoder", 
torch_dtype=torch.float16)
assert pipe.prior_scheduler.__class__.__name__ == "UnCLIPScheduler"
scheduler = …
```
=> allow passing components to connected pipelines when use the combined pipeline

tests/models/test_lora_layers.py
This PR fixes our slow tests currently failing due to the following test consuming too much CPU RAM.
> worker 'gw0' crashed while running 'tests/models/test_lora_layers.py::LoraIntegrationTests::test_sdxl_1_0_fuse_unfuse_all'
Here we should reduce the peak CPU RAM from ~36 GB to something like 15 GB by loading the models only in float16 precision at the expense of a slightly lower precision test.
cc @DN6
=> [Test] Reduce CPU memory

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
This PR fix a bug reported in https://github.com/huggingface/diffusers/issues/4073#issuecomment-1704703623
as described in https://github.com/huggingface/diffusers/issues/4073#issuecomment-1704703623, the input for run_safety_checker for this pipeline is always a pytorch tensor, not a numpy array
=> fix a bug in StableDiffusionUpscalePipeline.run_safety_checker

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md, docs/source/en/using-diffusers/sdxl.md, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
Adds a stronger warning in the Tips, guide, and docstrings that setting `height` and `width` to anything below 512 produces poor results and is not recommended.
=> [docs] Add stronger warning for SDXL height/width

src/diffusers/loaders.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
This PR makes it easier to use textual inversion embeddings with SDXL.
For example:
```py
import hf_image_uploader as hiu
from safetensors.torch import load_file
from huggingface_hub import snapshot_download
import torch
import json
import os
model_id = "fofr/sdxl-2004"
folder = snapshot_download(model_id)
with open(os.path.join(folder, "special_params.json"), 'r') as json_file:
data = json.load(json_file)
token, token_2 = data["TOK"][:4], data["TOK"][4:]
state_dict = load_file(os.path.join(folder, "embeddings.pti"))
text_encoder_sd = state_dict["text_encoders_0"]
text_encoder_2_sd = state_dict["text_encoders_1"]
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16) …
```
=> [Textual inversion] Relax loading textual inversion

docs/source/en/using-diffusers/inpaint.md
This PR fixes a typo in the inpainting example for forcing the unmasked area to be unchanged in `docs/source/en/using-diffusers/inpaint.md`.
This issue was noticed in https://github.com/huggingface/diffusers/commit/5f740d0f55adec63ee2453f83f1c0d7d984e01e4#commitcomment-126159665. Follow up to #4536.
@williamberman
@tin2tin
=> [docs] Fix typo in Inpainting force unmasked area unchanged example

examples/controlnet/train_controlnet.py, examples/controlnet/train_controlnet_sdxl.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py, examples/research_projects/controlnet/train_controlnet_webdataset.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py, examples/unconditional_image_generation/train_unconditional.py
re internal conversation accelerate save/load model hooks execute on every process and have to be guarded if io requires guarding -- i.e. saving models
=> guard save model hooks to only execute on main process

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/test_pipelines.py
The test failure is due to an edge case of this repo: https://huggingface.co/hf-internal-testing/tiny-stable-diffusion-lms-pipe/blob/7a9063578b325779f0f1967874a6771caa973cad/model_index.json#L2
As you can see the repo contains both Flax and PyTorch weights, but Flax weights are exceptionally the principal weights here. Therefore the `model_index.json` has `FlaxStableDiffusionPipeline` as the main class. 
To allow loading such a pipeline in PyTorch we need to make sure that we never try to import a Flax pipeline class.
=> Make sure Flax pipelines can be loaded into PyTorch

src/diffusers/loaders.py
As read the code 
https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py#L2384
```
if torch_dtype is not None:
vae.to(torch_dtype=torch_dtype)
```
it should calling the torch from 
https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L1141
```
device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
```
it seems trying to destructor as `dtype` but we pass the `torch_dtype=torch_dtype` in. should we change it to 
`vae.to(dtype=torch_dtype)`
otherwise it will cause error
Anyone in the …
=> [Bug Fix] Should pass the dtype instead of torch_dtype 

examples/community/lpw_stable_diffusion_xl.py, examples/community/stable_diffusion_xl_reference.py, src/diffusers/experimental/rl/value_guided_sampling.py, src/diffusers/pipelines/audio_diffusion/pipeline_audio_diffusion.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, tests/pipelines/consistency_models/test_consistency_models.py, tests/pipelines/unidiffuser/test_unidiffuser.py
This PR fixes the use of comparing types and instead uses `isinstance()`
=> fix E721 Do not compare types, use `isinstance()`

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_diffedit.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen_text_image.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_model_editing.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_paradigms.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
Fixes issue related to sequential cpu offload in SD pipeline slow tests 
```
tests/pipelines/stable_diffusion/test_stable_diffusion.py::StableDiffusionPipelineSlowTests::test_stable_diffusion_pipeline_with_sequential_cpu_offloading - KeyError: 'vision_model.vision_model.embeddings.position_ids'
```
=> Fix safety checker seq offload

examples/t2i_adapter/train_t2i_adapter_sdxl.py
Fixes:
```
examples/test_examples.py::ExamplesTestsAccelerate::test_t2i_adapter_sdxl
```
which is currently failing on main.
@patil-suraj @sayakpaul any reason why we wouldn't pass the data loader to prepare?
=> examples fix t2i training

docs/source/en/training/lora.md, tests/models/test_lora_layers.py
This PR adds:
* a test ensuring pipelines with components containing fused LoRA modules can be serialized correctly. 
* documentation 
This has been quite a requested feature from the community I think. 
@DN6 okay for you if we added this test?
=> [Tests and Docs] Add a test on serializing pipelines with components containing fused LoRA modules

src/diffusers/loaders.py, src/diffusers/models/lora.py, tests/models/test_lora_layers.py
Fixes sequentially fusing & unfusing LoRAs.
Fixes: https://github.com/huggingface/diffusers/issues/5000
=> [Lora] fix lora fuse unfuse

docs/source/en/api/pipelines/auto_pipeline.md
The link for `ControlNet` is broken on [this page](https://huggingface.co/docs/diffusers/api/pipelines/auto_pipeline). This PR fixes it.
**Current url:** https://huggingface.co/docs/diffusers/api/pipelines/api/pipelines/controlnet
**New url:** https://huggingface.co/docs/diffusers/api/pipelines/controlnet
=> Fix broken link in docs

src/diffusers/pipelines/pipeline_utils.py
This PR fixes an issue with `enable_model_cpu_offload` when a key isn't present in a checkpoint on the hub 
#5026
=> Fix model offload bug when key isn't present

src/diffusers/loaders.py
Fixes https://github.com/huggingface/diffusers/issues/5022
=> [Import] Don't force transformers to be installed

scripts/convert_original_stable_diffusion_to_diffusers.py, src/diffusers/loaders.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fixes outstanding critical request that diffusers can use `from_single_file` method to load safetensors file  
without needing to download yaml config file from github
This allows loading of safetensors to be done while offline.
Without this, any attempt to load safetensors model requires connection to github
(e.g. <https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml>)
Note that `download_from_original_stable_diffusion_ckpt` already has defined `model_files` param and its fully documented,  
but it was never actually implemented. this PR completes the implementation in existing code.
Tested in SD.Next:
```python
diffusers_load_config['config_files'] = {
'v1': 'configs/v1-inference.yaml',
'v2': 'configs/v2-inference-768-v.yaml',
'xl': …
```
=> allow loading of sd models from safetensors without online lookups using local config files

src/diffusers/models/transformer_2d.py
As discussed offline, scale is an optional argument so we should pass it explcitily, this PR makes things compatible with PEFT together with https://github.com/huggingface/peft/pull/933
cc @patrickvonplaten @sayakpaul 
This should at least fix current issues with diffusers + PEFT for inference, for merge_and_unload we can investigate further
=> [`LoRA`] Make optional arguments explicit

src/diffusers/models/unet_2d_condition.py
=> Remove logger.info statement from Unet2DCondition code to ensure torch compile reliably succeeds

examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py
Fixes type error in default config of  args, in example/instruct_pix2pix/train_instruct_pix2pix_sdxl.py
=> [FIX BUG] type of args in train_instruct_pix2pix_sdxl.py

examples/community/lpw_stable_diffusion_xl.py, examples/community/pipeline_prompt2prompt.py, examples/community/stable_diffusion_reference.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
Fixes #4864 
tagging: @stevhliu for the review
=> fix guidance_rescale docstring

docs/source/en/training/lora.md
Adds documentation for fusing multiple LoRAs. Presenting cyborg pikachu (thanks to @apolinario):
=> add doc around fusing multiple loras.

src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py
The adapter class doesn't take these in the constructor. If anyone was passing them in it would have been erroring. I think this snuck its way through PR review because I remember it was part of an earlier version of the initial PR
=> remove unused adapter weights in constructor

examples/community/pipeline_prompt2prompt.py
The function `get_word_inds` in `pipeline_prompt2prompt` is taking a string of text and either a word (str) or a word index (int) and returned the indices of token(s) the word would be encoded to.
However, there was a typo, in which in the second `if` branch the word was checked to be a `str` **again**, not `int`, which resulted in an [example code from the docs](https://github.com/huggingface/diffusers/tree/main/examples/community#prompt2prompt-pipeline) to result in an error
=> Fixed `get_word_inds` mistake/typo in P2P community pipeline (breaking code examples)

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
Currently the following does not work: 
```py
import hf_image_uploader as hiu
import torch
from compel import Compel, ReturnedEmbeddingsType
)
pipe2 = DiffusionPipeline.from_pretrained(
"stabilityai/stable-diffusion-xl-refiner-1.0",
)
pipe2.enable_model_cpu_offload()
compel = Compel(
tokenizer=[pipe.tokenizer, pipe.tokenizer_2] ,
text_encoder=[pipe.text_encoder, pipe.text_encoder_2],
returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
requires_pooled=[False, True]
)
compel2 = Compel(
tokenizer=pipe.tokenizer_2, …
```
=> [SDXL] Make sure multi batch prompt embeds works

tests/pipelines/audioldm2/test_audioldm2.py, tests/pipelines/kandinsky/test_kandinsky_combined.py, tests/pipelines/kandinsky/test_kandinsky_img2img.py, tests/pipelines/kandinsky_v22/test_kandinsky_combined.py, tests/pipelines/kandinsky_v22/test_kandinsky_inpaint.py
Fixes failing CUDA fast tests related to precision issues in Kandinsky
=> Fix precision related issues in Kandinsky Pipelines

scripts/convert_original_stable_diffusion_to_diffusers.py
https://github.com/huggingface/diffusers/blob/8263cf00f832399bca215e29fa7572e0b0bde4da/scripts/convert_original_stable_diffusion_to_diffusers.py#L157C9-L157C40
I added it because there was no config_files parser.
```python
parser.add_argument(
"--config_files",
default=None,
type=str,
help="The YAML config file corresponding to the architecture.",
)
```
Fixes #5114 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag members/contributors who may be interested in your PR.
=> [FIX BUG] add config_files parser #5114

src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py
This PR fixes a bug in StableDiffusionXLAdapterPipeline when using MultiAdapter
https://github.com/huggingface/diffusers/issues/5108
this script should work now
```python
import torch
from diffusers import StableDiffusionXLAdapterPipeline, MultiAdapter, T2IAdapter, EulerAncestralDiscreteScheduler, AutoencoderKL
from controlnet_aux import OpenposeDetector
open_pose = OpenposeDetector.from_pretrained("lllyasviel/Annotators")
url = "https://huggingface.co/TencentARC/t2iadapter_openpose_sd14v1/resolve/main/images/openpose_input.png"
image = load_image(url)
image = open_pose(
image, 
image_resolution=1024,
)
image = np.array(image)[:, :, ::-1]           
image = Image.fromarray(np.uint8(image)) 
cond_keypose = …
```
=> add multi adapter support to StableDiffusionXLAdapterPipeline

docs/source/en/using-diffusers/img2img.md
Part of #4758 to refresh the image-to-image guide to be more extensive and in-depth.
To do:
=> [docs] Improved image-to-image guide

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
My PR to refactor schedulers https://github.com/huggingface/diffusers/pull/4986 broke img2img pipelines :(
I updated the `add_noise` incorrectly and never tested it with img2img and it was not caught by our current tests 
this PR update`add_noise` to use `sigmas`
I compared outputs from this branch vs the output from a branch where I reverted the commit that introduced this bug https://github.com/huggingface/diffusers/pull/4986
I used a single strength value `0.8`, and I tested both `use_karras_sigma=True` and `use_karras_sigma=False` config. The results are identical. 
```python
import torch
StableDiffusionImg2ImgPipeline,
DPMSolverSinglestepScheduler,
DPMSolverMultistepScheduler, …
```
=> fix the add_noise function for dpm-multi et al 

src/diffusers/pipelines/blip_diffusion/pipeline_blip_diffusion.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_blip_diffusion.py
Currently `enable_model_cpu_offload` does not work for BLIPDiffusion. 
This PR:
1. Adds the `mode_cpu_offload_seq` string to the `BLIPDIffusionPipeline` and `BLIPDiffusionControlnetPipeline`
2. Makes some changes to the device used in the pipeline call to avoid device mismatch errors.  
=> Model CPU offload fix for BLIPDiffusion

src/diffusers/pipelines/wuerstchen/pipeline_wuerstchen.py, src/diffusers/pipelines/wuerstchen/pipeline_wuerstchen_combined.py
This adds `callback` and `callback_steps` arguments to `WuerstchenDecoderPipeline`. This behaves the same as in `WuerstchenPriorPipeline`.
`prior_callback`/`callback` and `prior_callback_steps`/`callback_steps` were also added to `WuerstchenCombinedPipeline`. It forwards these arguments to the `prior_pipe` or `decoder_pipe`.
In the [Dream Textures](https://github.com/carson-katri/dream-textures) addon, we display a progress indicator when generating. It also provides options for previewing in-progress generations. To provide this functionality we need a `callback` argument, which was only available on the `WuerstchenPriorPipeline`. …
=> Add callbacks to `WuerstchenDecoderPipeline` and `WuerstchenCombinedPipeline`

src/diffusers/schedulers/scheduling_dpmsolver_multistep_flax.py
We never implemented `timestep_spacing` for Flax schedulers (except for Euler Discrete).
=> timestep_spacing for FlaxDPMSolverMultistepScheduler

src/diffusers/models/unet_2d_condition_flax.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_flax_stable_diffusion_xl.py
Make sure Flax init is correct for different model sizes
=> [SDXL Flax] fix SDXL flax init

docs/source/en/optimization/memory.md, docs/source/en/optimization/torch2.0.md
This PR clarifies how xfromers is used and refers to PT 2.0 benchmarks for inference.
=> [Docs] Improve xformers page

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_diffedit.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_v_pred.py, tests/pipelines/text_to_video/test_video_to_video.py
A lot of the memory issues in tests can be solved by 
1. Enabling model cpu offload
2. Using a different (smaller) model
This PR makes the necessary changes for these tests to pass. Additionally, it fixes a small bug in `enable_model_cpu_offload` when `self._offload_gpu_id` is not properly set. 
=> Fix memory issues in tests

examples/dreambooth/train_dreambooth.py, examples/kandinsky2_2/text_to_image/train_text_to_image_decoder.py, examples/kandinsky2_2/text_to_image/train_text_to_image_lora_decoder.py, examples/kandinsky2_2/text_to_image/train_text_to_image_lora_prior.py, examples/kandinsky2_2/text_to_image/train_text_to_image_prior.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py, src/diffusers/training_utils.py
Fixes: https://github.com/huggingface/diffusers/issues/5138.
=> [Examples] add `compute_snr()` to training utils.

src/diffusers/pipelines/stable_diffusion_xl/pipeline_flax_stable_diffusion_xl.py
Make sure SDXL zeros out prompt_embeds and pool_embeds correctly in Flax. The following now gives identical results:
**Flax**:
```py
from diffusers import FlaxStableDiffusionXLPipeline
import jax.numpy as jnp
import jax
path = "hf-internal-testing/tiny-stable-diffusion-xl-pipe"
pipe, params = FlaxStableDiffusionXLPipeline.from_pretrained(path)
prompt = "An astronaut riding a green horse on Mars"
steps = 3
batch_size, height, width, ch = 1, 32, 32, 4
num_elems = batch_size * height * width * ch
rng = jax.random.PRNGKey(0)
latents = (jnp.arange(num_elems) / num_elems)[:, None, None, None].reshape(batch_size, ch, width, height)
print("latents", np.abs(np.asarray(latents)).sum())
prompt_embeds = pipe.prepare_inputs(prompt)
image = pipe(prompt_embeds, params, rng, …
```
=> [Flax SDXL] fix zero out sdxl

src/diffusers/loaders.py
Fixes a typo when importing `BaseTunerLayer` module
pointed out by @kashif 
cc @patrickvonplaten @sayakpaul
=> [`PEFT`] Fix typo for import

src/diffusers/utils/state_dict_utils.py
Currently if a user uses peft main + transformers main + diffusers main, generating images with kohya checkpoints does not work.
The script below:
```python
import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
pipeline = StableDiffusionPipeline.from_pretrained(
"gsdf/Counterfeit-V2.5", torch_dtype=torch.float16, safety_checker=None
).to("cuda")
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(
pipeline.scheduler.config, use_karras_sigmas=True
)
pipeline.load_lora_weights(
"sayakpaul/civitai-light-shadow-lora", weight_name="light_and_shadow.safetensors"
)
prompt = "masterpiece, best quality, 1girl, at dusk"
negative_prompt = ("(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), "
"bad composition, inaccurate eyes, extra …
```
=> [`PEFT` / `LoRA` ] Kohya checkpoints support

docs/source/en/quicktour.md, src/diffusers/pipelines/pipeline_flax_utils.py
Addresses questions raised in this Slack [thread](https://huggingface.slack.com/archives/C03UQJENJTV/p1695735577276939) from @osanseviero 
> Should we showcase a lighter repo that does not contain so many different weights? Maybe ddpm?
Do you mean showcasing a repo that'll be faster to download or are you worried about the complexity of so many different weights in Stable Diffusion v1.5?
In the case of the latter, I think it may be ok to keep the current repo for continuity with the section above it and because it is the most popular model users that are probably interested in trying. I don't think they'll care too much about all the different weights in the repo since all they have to know right now is just how they can load the model using `from_pretrained`.
=> [docs] Quicktour fixes

src/diffusers/utils/outputs.py, tests/others/test_outputs.py
Unpickling pipeline outputs currently produces an error (because the output is both a `@dataclass` and an `OrderedDict`)
This PR fixes this by setting a custom `__reduce__` method on the `BaseOutput` class
=> Make `BaseOutput` dataclasses picklable

src/diffusers/pipelines/pipeline_flax_utils.py
The following will download safetensors and onnx files:
```Python
from diffusers.pipelines import FlaxStableDiffusionXLPipeline
_ = FlaxStableDiffusionXLPipeline.from_pretrained(
revision="refs/pr/95",
)
```
Ideally we should bring over some of the logic we've been adding to `pipeline_utils.py`, but this PR does the trick for now.
=> Flax: Ignore PyTorch, ONNX files when they coexist with Flax weights

src/diffusers/loaders.py
For a lot of functionality we're seeing deprecation warnings without a clear message on how to prevent them. Let's make postpone the deprecation warnings for PEFT here into the future for two minor releases
=> [PEFT warnings] Only sure deprecation warnings in the future

src/diffusers/models/adapter.py
Added docstrings to the forward methods of all the classes in adapter models describing the type of parameter, operations performed by the function, and the return value.
Fixes #5231 
@patrickvonplaten , @stevhliu and @yiyixuxu
=> Add docstrings in forward methods of adapter model

src/diffusers/models/autoencoder_kl.py
=> Add docstring for the AutoencoderKL's decode

src/diffusers/models/autoencoder_kl.py
=> Add a docstring for the AutoencoderKL's encode

docs/source/en/using-diffusers/img2img.md, docs/source/en/using-diffusers/inpaint.md, src/diffusers/schedulers/scheduling_unipc_multistep.py
Part of #4758 to update the inpainting guide to be more extensive and in-depth
=> [docs] Improved inpaint docs

docs/source/en/using-diffusers/write_own_pipeline.md
It's so minor that it is immediately obvious by looking at the file changes.
Anyone
=> Minor fixes

examples/custom_diffusion/train_custom_diffusion.py
fix inference in custom diffusion
inference codes should be in the loop of dataloader
=> fix inference in custom diffusion

tests/pipelines/controlnet/test_controlnet.py
=> make-fast-test-for-StableDiffusionControlNetPipeline-faster

setup.py
Fixes #5325 
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation). *not required*
=> Add py.typed for PEP 561 compliance

examples/unconditional_image_generation/train_unconditional.py
fix #5338 
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation). _not required_
=> fix problem of 'accelerator.is_main_process' to run in mutiple GPUs

docs/source/en/using-diffusers/img2img.md, docs/source/en/using-diffusers/inpaint.md
Fixes an issue with incorrect section levels and missing parameter
=> [docs] Minor fixes

.github/workflows/build_docker_images.yml, .github/workflows/push_tests.yml, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile, tests/lora/test_lora_layers_old_backend.py, tests/lora/test_lora_layers_peft.py, tests/models/test_modeling_common.py
xformers breaks cuDNN drivers with torch 2.1. This PR 
1. Creates a separate runner for xformer related tests with a pinned torch version
2. Updates a few tests that had entangled xformers tests
=> New xformers test runner

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_latent_upscale.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py
Adds FreeU to SD and SDXL derivative pipelines as well as video-to-video.
=> [Core] Add FreeU to all the core pipelines and their (mostly-used) derivatives

docs/source/en/_toctree.yml, docs/source/en/tutorials/using_peft_for_inference.md
Now that we're nearing the end of integrating natively with `peft`, it's important for us to not forget about documenting all the cool things. 
This is the first PR from this series.
Colab Notebook: https://colab.research.google.com/drive/1V-uOlPGjpih1pw1VIWhy4zvdxbjNhBdf?usp=sharing
Initially worked out by @pacman100 and @younesbelkada. I just acted as a janitor. 
~❌ This PR should not be merged before #5151 ❌~
Cc: @BenjaminBossan @apolinario
=> [Docs] add docs on peft diffusers integration

CONTRIBUTING.md, docs/source/en/api/pipelines/diffedit.md, docs/source/en/api/pipelines/kandinsky.md, docs/source/en/api/pipelines/kandinsky_v22.md, docs/source/en/conceptual/contribution.md, docs/source/en/optimization/torch2.0.md, docs/source/en/training/custom_diffusion.md, docs/source/en/training/text_inversion.md, docs/source/en/using-diffusers/controlnet.md, docs/source/en/using-diffusers/shap-e.md, examples/community/run_onnx_controlnet.py, examples/community/run_tensorrt_controlnet.py, examples/custom_diffusion/README.md, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/research_projects/colossalai/README.md, examples/research_projects/multi_subject_dreambooth/README.md, examples/research_projects/sdxl_flax/README.md, src/diffusers/pipelines/shap_e/renderer.py, src/diffusers/pipelines/unidiffuser/modeling_text_decoder.py, utils/custom_init_isort.py, utils/release.py
Hi, this is my first PR to the project. It fixes some minor typos.
=> chore: fix typos

docs/source/en/tutorials/basic_training.md, docs/source/ko/tutorials/basic_training.md, examples/dreambooth/train_dreambooth_flax.py, examples/research_projects/intel_opts/textual_inversion_dfq/textual_inversion.py, examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py, examples/unconditional_image_generation/train_unconditional.py
Fixes: https://github.com/huggingface/diffusers/issues/5383. 
@stevhliu cc for the doc change. 
@Wauplin for visibility and awareness.
=> [Examples] Update with HFApi

tests/pipelines/stable_diffusion/test_stable_diffusion.py
Tested locally (skipping slow runs), faced some assertion errors due to model changes.
Fixes #5262 
=> changed channel parameters for UNET and VAE. Changed configs parameters of CLIPText

docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile
We're seeing failures in the CUDA tests runners with Torch 2.1 due to driver issues that are caused by the fact that the base image is still using CUDA 11.7
This PR updates the base docker image for all runners using Torch 2.1 to use CUDA 12.1 
=> Update base image for slow CUDA tests

src/diffusers/loaders.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fixes https://github.com/huggingface/diffusers/issues/5390.
In favor of closing: https://github.com/huggingface/diffusers/pull/5439. Copying over what I said in #5439: 
TL;DR: It's a must for the user to locally save the tokenizers and configurations under the same paths (such as "openai/clip-vit-large-patch14") to ensure local_files_only=True works in the right manner.
Here is an end-to-end demonstration of how this should be done:
https://colab.research.google.com/gist/sayakpaul/b086a1089f6723d3aa01b67f77f1ebbc/scratchpad.ipynb
=> [`from_single_file()`]fix: local single file loading.

examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
Original size of image will be passed into SDXL pipeline. The order of it should be width, height according to StableDiffusionXLPipeline, but the training script has it in the order of height, width. This PR fixes that. 
=> Fix the order of width and height of original size in SDXL training script

src/diffusers/models/unet_2d.py
UNet2DModel ignores class_labels parameter when class_embedding is not initialized and does not give any error. This causes users to give pass a parameter that does not change anything. I changed the code so that it gives error and user becomes aware that they have to initialize class_embeddings. I opened an issue about this before: https://github.com/huggingface/diffusers/issues/5330
=> fix une2td ignoring class_labels

src/diffusers/models/adapter.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py
Fixes #5377 
This PR updates the padding behavior of the T2I-Adapter down blocks to more closely mirror the padding behavior of the UNet model.
Prior to this change, the T2I-Adapter pipelines only worked with input/output image dimensions that were multiples of the T2I-Adapter's total downscale factor (64 for SD1 and 32 for SDXL). After this change, the same pipelines can be run with input/output dimensions that are multiples of the T2I-Adapter's initial pixel unshuffling downscale factor (8 for SD1 and 16 for SDXL).
The change is covered by unit tests, but the following script can be used as a visual regression test for this feature. This script is adapted from [this comment on the original issue](https://github.com/huggingface/diffusers/issues/5377#issuecomment-1764510314).
```python …
```
=> Make T2I-Adapter downscale padding match the UNet

src/diffusers/models/adapter.py, src/diffusers/models/controlnet.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
Fixes graph break problems for T2I Adapters (both SD and SDXL).
~ControlNets are still failing. I am trying to get to the bottom of it.~
@DN6, if you want to double-check the fixes proposed in this PR, I'd appreciate it.
=> [torch.compile] fix graph break problems partially

docs/source/en/using-diffusers/controlnet.md
In [ControlNet with SDXL docs](https://huggingface.co/docs/diffusers/using-diffusers/controlnet#controlnet-with-stable-diffusion-xl), I found a typo in code example.
If you don't fix this code, you'll get an error:
```
Traceback (most recent call last):s: 100%|███████████████████████████████| 335M/335M [00:16<00:00, 22.4MB/s]
File "/home/khwankim_dc/workspace/TIL/diffusers/controlnet/sdxl.py", line 49, in <module>7<00:26, 275MB/s]
output = pipe(model.safetensors: 100%|█████████████████████████████▉| 10.2G/10.3G [00:54<00:00, 195MB/s]
File "/home/khwankim_dc/anaconda3/envs/diffusers/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/home/khwankim_dc/anaconda3/envs/diffusers/lib/python3.10/site-packages/diffusers/pipeli …
```
=> Fix typo in controlnet docs

src/diffusers/models/transformer_temporal.py
Fixes Bugs
Fix bugs in [transformer_temporal.py line 174](https://github.com/huggingface/diffusers/blob/bc7a4d4917456afd70913be85bd25c556c25862c/src/diffusers/models/transformer_temporal.py#L174) 
```python
hidden_states = self.proj_out(hidden_states)
hidden_states = (
hidden_states[None, None, :]
.reshape(batch_size, height, width, channel, num_frames)
.permute(0, 3, 4, 1, 2)
.contiguous()
)
hidden_states = hidden_states.reshape(batch_frames, channel, height, width)
```
It should be 
```python
hidden_states = self.proj_out(hidden_states)
hidden_states = ( …
```
=> [BUG] in transformer_temporal Fix Bugs

docs/source/en/api/pipelines/controlnet_sdxl.md, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py
this PR:
1. fix a bug in `StableDiffusionXLControlNetInpaintPipeline` reported in https://github.com/huggingface/diffusers/issues/5463
2. add missing API doc for `StableDiffusionXLControlNetInpaintPipeline`
3. fix a mistake in doc string example for both `StableDiffusionXLControlNetInpaintPipeline` and `StableDiffusionControlNetInpaintPipeline`
=> fix a few issues in controlnet inpaint pipelines

docs/source/en/stable_diffusion.md
I believe that this was a typo, it should have been 'autoencoder' and not 'autodecoder'.
members/contributors who may be interested in your PR. @stevhliu
=> Fixed autoencoder typo

docs/source/en/_toctree.yml, docs/source/en/api/activations.md, docs/source/en/api/normalization.md, src/diffusers/models/activations.py, src/diffusers/models/attention.py, src/diffusers/models/normalization.py, src/diffusers/models/resnet.py, src/diffusers/models/unet_2d_blocks.py, src/diffusers/pipelines/unidiffuser/modeling_uvit.py
Internal Slack thread (internal to Diffusers maintainers):
https://huggingface.slack.com/archives/C04DBJ0HLH1/p1697859469537249
@stevhliu docs look okay to you?
=> [Core] Refactor activation and normalization layers

src/diffusers/utils/outputs.py, tests/others/test_outputs.py
Identical to https://github.com/huggingface/transformers/pull/25358, this PR should unblock the similar issue. Additionally, this, among other fixes, aims to unblock PT2 exports for models that outputs `BaseOutput` subclasses.
=> Register BaseOutput subclasses as supported torch.utils._pytree nodes

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py
This PR fix the bug reported in https://github.com/huggingface/diffusers/issues/5447 and allow users to 2nd order schedulers for ensemble of experts approach
I'm using an toy example to quickly illustrate the error we are having
* e.g. we have 4 inference steps: `3, 2, 1, 0`
* in `set_timesteps`, we repeat the index for 2nd order update (steps in `[]` are 2nd order update) : `3, [2], 2, [1], 1, [0], 0`
* now we split these timesteps between base and refiner, if the cutoff point is `1`, we will have
* base: `3, [2], 2`
* refiner `[1], 1, [0], 0`
-> You can see that the timesteps for refiner is wrong now, should be `2, [1], 1, [0], 0`
this script now works
```python
import torch
from diffusers import StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline
from diffusers import …
```
=> fix a bug in 2nd order schedulers when using in ensemble of experts config

examples/community/README.md, examples/community/latent_consistency_img2img.py
This PR adds an img2img pipeline for Latent Consistency Models: https://github.com/luosiallen/latent-consistency-model/issues/8#issuecomment-1773970030
examples/community/latent_consistency_img2img.py
which can be called like this
import torch
"SimianLuo/LCM_Dreamshaper_v7", custom_pipeline="latent_consistency_txt2img", custom_revision="main")
pipe.to(torch_device="cuda", torch_dtype=torch.float32)
img2img=LatentConsistencyModelPipeline_img2img(
vae=pipe.vae,
text_encoder=pipe.text_encoder,
tokenizer=pipe.tokenizer,
unet=pipe.unet,
#scheduler=pipe.scheduler,
scheduler=None,
safety_checker=None,
feature_extractor=pipe.feature_extractor,
requires_safety_checker=False,
)
img = Image.open("thisismyimage.png") …
=> Add a new community pipeline

PHILOSOPHY.md
=> Fix missing punctuation in PHILOSOPHY.md

src/diffusers/loaders.py
The following code snippet will throw `TypeError` for now:
```python
import torch
from diffusers import ControlNetModel
controlnet = ControlNetModel.from_single_file(
"./control_sd15_canny.pth", torch_dtype=torch.float16, local_files_only=True
)
```
which gives us:
```bash
File "D:\AI\diffusers_test.py", line 5, in <module>
controlnet = ControlNetModel.from_single_file(
File "D:\Programming\miniconda3\lib\site-packages\diffusers\loaders.py", line 2665, in from_single_file
controlnet.to(torch_dtype=torch_dtype)
File "D:\Programming\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1141, in to
device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
TypeError: to() received an invalid combination of arguments - …
```
=> fix a bug on `torch_dtype` argument in `from_single_file` of ControlNetModel

examples/text_to_image/train_text_to_image_flax.py
@patrickvonplaten @pcuenca
Tested with `--from_pt`, and it worked as expected:
```
ranran@t1v-n-aad126dc-w-0:~/diffusers/examples/text_to_image$ export TPU_PREMAPPED_BUFFER_SIZE=4294967296 && JAX_PLATFORMS=tpu,cpu python3 train_text_to_image_flax.py --pretrained_model_name_or_path=stabilityai/stable-diffusion-2-1 --dataset_name=lambdalabs/pokemon-blip-captions --resolution=256 --center_crop --random_flip …
```
=> Add from_pt flag to enable model from PT

tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py
This PR speeds up the expert of mixture tests
=> [Tests] Speed up expert of mixture tests

tests/pipelines/controlnet/test_controlnet_img2img.py
- Enhanced test speed by adjusting the `block_out_channels` to reduce the depth of UNet, ControlNetModel, and AutoencoderKL.
Fixes #5264
=> [Tests] Optimize test configurations for faster execution

examples/dreambooth/train_dreambooth.py
This PR simply fixes two typos in comments. Thus, no global changes (such as tests or documentation amendments) are needed :)
=> Update train_dreambooth.py - fix typos

docs/source/en/_toctree.yml, docs/source/en/api/internal_classes_overview.md
From this [comment](https://github.com/huggingface/diffusers/pull/5493#discussion_r1368983480), this PR reorders some of the more experimental APIs into an internal helper section. I left some of the more important classes like `Configuration` and `Outputs` in the main classes for higher visibility, but let me know if you want to move those as well.
=> [docs] Internal classes API

src/diffusers/pipelines/blip_diffusion/modeling_ctx_clip.py
Transformers moved _expand_mask to another file. Let's make sure we don't run into import errors here
=> Fix moved _expand_mask function

.github/workflows/push_tests.yml
As per title.
Currently PEFT slow tests are not being tested on main push. This PR adds a new job in the slow tests workflow to make sure we test PEFT slow tests on main 
cc @patrickvonplaten @DN6 @sayakpaul 
I am also happy to push this change on a dummy branch on hf repo to test the implementation
=> [`PEFT` / `Tests`] Add peft slow tests on push

src/diffusers/loaders.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
It wasn't possible to use from_single_file in the STableDiffusionXLAdapterPipeline since the adapter was not to send through the loaders it was checked only for controlnet pipeline so I added the adapter parameter and handle it internally.
=> add fix to be able use StableDiffusionXLAdapterPipeline.from_single_file

src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, tests/schedulers/test_scheduler_dpm_multi.py
Fixes #5433 
When using DPM++ for SDXL (especially when using the SDE variant, i.e., DPM++2M SDE), for steps < 50, we usually get visual artifacts, and the results are even worse than Euler's method. This PR fixes this issue and ensures DPM++ can generate better and more detailed images than Euler's method.
In a word, it is because of the numerical instability near $t=0$ (i.e., small noises / clean images). When we use second-order solvers for $t$ near to $0$, the solver becomes numerically unstable and causes unsatisfied artifacts, as in #5433 .
To address such an issue, this PR proposes two methods:
1. Add a new config, `use_lu_lambdas`, for setting step sizes during sampling. This setting uses *uniform intervals for log-SNR* (i.e., $\lambda(t)$), which is used in the original …
=> Stabilize DPM++, especially for SDXL and SDE-DPM++

src/diffusers/utils/constants.py
Fixes: https://github.com/huggingface/diffusers/issues/5522
In fact we need to force users to use transformers version greater than 4.33.3 which is the last minor version before 4.34.0 to include: https://github.com/huggingface/transformers/pull/25721
cc @sayakpaul @patrickvonplaten
=> [`core` / `PEFT` ]Bump transformers min version for PEFT integration

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
Sets `sigma` to be at least 1e-10.
- Schedulers: @williamberman and @patrickvonplaten
=> Fix divide by zero RuntimeWarning

examples/kandinsky2_2/text_to_image/train_text_to_image_lora_prior.py
fixing a mistake in kandinsky2.2 training script. Thanks @kashif for catching it:)
=> fix a mistake in text2image training script for kandinsky2.2

docs/source/en/api/pipelines/stable_diffusion/overview.md, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md
Adds a usage tip to the SDXL docs about using Lu lambdas and fixes a table 🤞
=> [docs] Lu lambdas

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen_text_image.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py, tests/pipelines/test_pipelines_common.py
Propagates changes in #4514 updating CPU model offloading to use `maybe_free_model_hooks()` to more diffusion pipelines, and adds a test to ensure all offloading-enabled pipeline components are returned to the CPU after a pipeline call is finished.
=> Update final CPU offloading code for more diffusion pipelines

src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py
Fixes https://github.com/huggingface/diffusers/issues/5516 
Additionally, adds SLOW tests for SDXL T2i adapters.
Hello, 
as requested here is a PR to fix the #5516, WIth it's corresponding tests.
I have a few questions : 
- The test seem to fail when this is removed from the pipeline initialization : `torch_dtype=torch.float16`,  But your PR that inspired mine didn't have it(https://github.com/huggingface/diffusers/pull/4666/files).
This is the error that I get with it : 
`  RuntimeError: Input type (float) and bias type (c10::Half) should be the same`
- I get this warning when I add `.to("CPU")` to the pipeline and the adapter : 
`Pipelines loaded with 'torch_dtype=torch.float16' cannot run with 'cpu' device. It is not recommended to move them to 'cpu' as running them will fail. Please …
=>  [Core] enable lora for sdxl adapters too and add slow tests.

examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
Reverts huggingface/diffusers#5382
=> Revert "Fix the order of width and height of original size in SDXL training script"

src/diffusers/utils/peft_utils.py, tests/lora/test_lora_layers_peft.py
Fixes: https://github.com/huggingface/diffusers/issues/5606
The fix is simply to ignore the processing of `network_alpha_dict` in case that dictionary is empty. 
Also confirmed that I got the same generation with that checkpoint on main vs with this branch, hence added a slow test for it 
cc @sayakpaul @patrickvonplaten
=> [`PEFT` / `LoRA`] Fix civitai bug when network alpha is an empty dict

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/kandinsky.md, docs/source/en/api/pipelines/kandinsky_v22.md, docs/source/en/using-diffusers/kandinsky.md
Part of the ongoing effort to make the API docs more lightweight (similar to #4428) for some of the pipelines that are more complex and less straightforward to use. This'll also improve #4290.
Since Kandinsky 2.2 usage is so similar to 2.1, do you think it'd make sense to combine the two on a page? I think this can really avoid duplicating content shared by both pipelines. We can copy this [code snippet](https://huggingface.co/docs/datasets/loading#slice-splits) switching thing from the Datasets docs. The only thing we'd have to make super clear is: 
1. don't use `prompt` in the decoding pipeline for Kandinsky 2.2
2. have a separate section for ControlNet with Kandinsky 2.2
=> [docs] Kandinsky guide

tests/pipelines/test_pipelines_common.py
=> [Tests] Fix cpu offload test

docs/source/en/conceptual/contribution.md, docs/source/en/conceptual/ethical_guidelines.md, docs/source/en/conceptual/evaluation.md, docs/source/en/conceptual/philosophy.md, docs/source/en/using-diffusers/controlling_generation.md
Hi! Thank you for this awesome library!
I am new to open source. Firstly, I am reading the documentation. Secondly, I will read the codebase. Thirdly, I plan to make documentation and code contributions. I am open to your guidance.
I would be grateful for your feedback. @stevhliu @yiyixuxu @patrickvonplaten
=> [Docs] Fix typos, improve, update at Conceptual Guides page

src/diffusers/pipelines/auto_pipeline.py, tests/pipelines/test_pipelines_auto.py
fix a bug https://github.com/huggingface/diffusers/issues/5593
this PR will now enable user to use the AutoPipeline's `from_pipe` method to use existing controlnet pipeline to create a new controlnet pipeline for same or different task! optionally with a new controlnet model too! 
so you can do something like this (this would previously throw an error, see more https://github.com/huggingface/diffusers/issues/5593)
```python
controlnet_pipe1 = AutoPipelineForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5", controlnet=canny)
controlnet_pipe2 = AutoPipelineForImage2Image.from_pipe(controlnet_pipe1, controlnet=pose)
```
also added relevant tests :)
=> fix a bug in `AutoPipeline.from_pipe()` when creating a controlnet pipeline from an existing controlnet

docs/source/en/api/pipelines/latent_consistency_models.md, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_text2img.py
=> [Easy] clean up the LCM docstrings.

src/diffusers/models/modeling_utils.py
This PR moves an unchanging operation out of a loop for a speed benefit during model loading. It does not change the functional behaviour in any way.
The following code was used to profile model loading:
```python
import cProfile
from diffusers import UNet2DConditionModel
def main():
with cProfile.Profile() as pr:
unet = UNet2DConditionModel.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="unet")
pr.dump_stats("unet_load.prof")
if __name__ == "__main__":
main()
```
**Before:**
The resultant .prof file can be visualized with `snakeviz`. This revealed that a significant amount of time was being spent on redundant calls to `inspect.signature(....)`:
**After:**
After the improvement in this PR, the time spent on calls to `inspect.signature(....)` was reduced from 0.0340s to …
=> Model loading speed optimization

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, src/diffusers/pipelines/paint_by_example/pipeline_paint_by_example.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
This PR revives the great work done by @slep0v in https://github.com/huggingface/diffusers/pull/4891 to add inference support for Img2Img pipelines with the tiny Autoencoder. 
We have had a couple of requests from the community members about this (#5619 for example). Our very own @radames also requested for it. I think this will enable many cool UI use cases.
=> [Core] support for tiny autoencoder in img2img

src/diffusers/pipelines/pipeline_utils.py
This PR makes sure that community pipelines can correctly load revision-specific code from checkpoints. It fixes the following edge case: https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7#usage-deprecated
=> [Custom Pipelines] Make sure that community pipelines can use repo revision

src/diffusers/pipelines/auto_pipeline.py
Looks like LCM was added to the AutoPipelineText2Image lookup for 0.22 but not Pixart. This fixes that. Only T2I since pixart doesnt have premade I2I pipes yet.
=> Add Pixart to AUTO_TEXT2IMAGE_PIPELINES_MAPPING

src/diffusers/models/attention_processor.py
`CustomDiffusionAttnProcessor2_0` does not work when using mixed precision training when running `train_custom_diffusion.py` 
This PR:
Updates the `CustomDiffusionAttnProcessor2_0` to properly set dtypes in the KV layers to support mixed precision training.  
#5502
=> Update custom diffusion attn processor

src/diffusers/models/attention.py
Change in the BasicTransformer block is breaking AnimateDiff generations, by failing to apply the second set of position embeddings required for generation. 
This PR introduces a fix for this issue. 
=> Fix Basic Transformer Block

.github/workflows/pr_flax_dependency_test.yml, .github/workflows/pr_torch_dependency_test.yml
Dependency tests aren't catching import issues caused when certain soft dependencies are introduced via Mixins (see #5668) 
This PR tests soft dependencies when either torch or flax is installed, so that these import issues can be be caught. 
=> Explicit torch/flax dependency check

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py, tests/pipelines/pixart/test_pixart.py
So that the following works:
```python
from transformers import T5EncoderModel
from diffusers import PixArtAlphaPipeline
import torch
import gc
def flush():
gc.collect()
def bytes_to_giga_bytes(bytes):
return bytes / 1024 / 1024 / 1024
text_encoder = T5EncoderModel.from_pretrained(
"PixArt-alpha/PixArt-XL-2-1024-MS",
subfolder="text_encoder",
).to("cuda")
pipe = PixArtAlphaPipeline.from_pretrained(
"PixArt-alpha/PixArt-XL-2-1024-MS",
text_encoder=text_encoder, # pass the previously instantiated 8bit text encoder
transformer=None,
).to("cuda")
prompt = "cute cat"
with torch.no_grad(): prompt_embeds, negative_embeds = pipe.encode_prompt(prompt)
del text_encoder
del pipe
flush()
pipe = PixArtAlphaPipeline.from_pretrained( …
```
=> [PixArt-Alpha] fix `mask_feature` so that precomputed embeddings work with a batch size > 1

src/diffusers/loaders.py, src/diffusers/models/lora.py, src/diffusers/pipelines/latent_consistency_models/__init__.py, src/diffusers/pipelines/pixart_alpha/__init__.py
Fixes https://github.com/huggingface/diffusers/issues/5661. 
I think we need to make a patch release for this one. 
While reviewing, could y'all please go over [this comment](https://github.com/huggingface/diffusers/issues/5661#issuecomment-1797391247) too and verify things on your ends?
=> Make sure DDPM and `diffusers` can be used without Transformers

src/diffusers/models/transformer_2d.py, tests/pipelines/pixart/test_pixart.py
Fixes: https://github.com/huggingface/diffusers/issues/5670
=> [PixArt-Alpha] Support non-square images

src/diffusers/schedulers/scheduling_lcm.py, tests/schedulers/test_scheduler_lcm.py
This PR makes the following improvements to `LCMScheduler`:
1. `LCMScheduler.step` no longer adds noise to `prev_sample` on the final timestep of the `timestep` schedule. This should make `LCMScheduler` more compatible with pipelines outside of the LCM pipelines.
2. The timestep scaling factor used when computing the `c_skip` and `c_out` boundary scalings in `LCMScheduler.get_scalings_for_boundary_condition_discrete` is now configurable as `LCMScheduler.timestep_scaling`. …
=> Improve LCMScheduler

docs/source/en/using-diffusers/conditional_image_generation.md, docs/source/en/using-diffusers/depth2img.md, docs/source/en/using-diffusers/img2img.md, docs/source/en/using-diffusers/inpaint.md, docs/source/en/using-diffusers/unconditional_image_generation.md
Kandinsky doesn't want fp16 due to deprecation; ogkalu and kohbanye don't have .safetensor; add make_image_grid for better visualization.
@stevhliu @yiyixuxu @DN6 
=> [`Docs`] Fix typos, improve, update at Using Diffusers' Task page

tests/pipelines/shap_e/test_shap_e.py, tests/pipelines/shap_e/test_shap_e_img2img.py, tests/pipelines/test_pipelines_common.py
This PR speed up the fast tests for shap-e by skipping the rendering part
=> speed up Shap-E fast test 

src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py
There was misalignment in docstring example between import and usage.
If use the DiffusionPipeline, it would fail with "unexpected argument image" error, but with AutoPipelineForImage2Image, which states in current import, it works fine
- [v] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [v] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [v] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
=> Fix the misaligned pipeline usage in dreamshaper docstrings

src/diffusers/pipelines/pipeline_utils.py
Fixes #4665 
@patrickvonplaten @DN6
=> Fixed is_safetensors_compatible() handling of windows path separators

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py, tests/pipelines/pixart/test_pixart.py
https://github.com/huggingface/diffusers/pull/5677 actually broke the default behavior and was leading to crappy results. This PR fixes that. 
Sincere apologies for rushing here. 
=> [PixArt-Alpha] fix mask feature condition.

docs/source/en/tutorials/using_peft_for_inference.md
Added code example and section about fusing the LoRA into the weights of the model
I've also taken the liberty to change the title to be a bit more descriptive (easier to find on Google if someone is googling "how to use loras with diffusers" - and also explicitly mention "LoRA" as a synonym of adapter as this is the community used name
=> Add adapter fusing + PEFT to the docs

src/diffusers/models/attention_processor.py
Fixes #5504 
Related PR: https://github.com/huggingface/diffusers/pull/5506
=> [Bugfix] fix error of peft lora when xformers enabled

examples/consistency_distillation/README.md, examples/consistency_distillation/README_sdxl.md, examples/consistency_distillation/requirements.txt, examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py, examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py, examples/consistency_distillation/train_lcm_distill_sd_wds.py, examples/consistency_distillation/train_lcm_distill_sdxl_wds.py
=> Add LCM Scripts

docs/source/en/training/lora.md
`pipe()` is run twice.  One is with `cross_attention_kwargs` and the other (next line) removes it.  This appears to be a typo.
- Docs: @stevhliu and @yiyixuxu
=> [Docs] Clarify that these are two separate examples

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py
fix https://github.com/huggingface/diffusers/issues/5254#issuecomment-1794421205
=> Controlnet Img2img: pass `height` and `width` to `image_processor.preprocess`

examples/community/stable_diffusion_controlnet_reference.py
When used in the latest version, the forward receives the `scale` kwarg:
```
File "C:\Code\xxx\example_diffusers.py", line 28, in <module>
result_img = pipe(
File "C:\Users\Jannchie\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
return func(*args, **kwargs)
File "C:\Code\xxx\reference_only_pipe.py", line 935, in __call__
self.unet(
File "C:\Users\Jannchie\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "C:\Users\Jannchie\anaconda3\lib\site-packages\diffusers\models\unet_2d_condition.py", line 1076, in forward
sample, res_samples = downsample_block(hidden_states=sample, temb=emb, scale=lora_scale)
File …
```
=> fix: fix forward function signature of controlnet reference_only pipeline example

examples/research_projects/realfill/requirements.txt, examples/research_projects/realfill/train_realfill.py
We removed the `ToImageTensor()` transform in torchvision 0.16 in favor of `ToImage()`, so this PR updates that. It also replaces the now deprecated `ConvertImageDtype()` with `ToDtype()`.
CC @thuanz123 as original author and original reviewer @patrickvonplaten  (https://github.com/huggingface/diffusers/pull/5456)
=> Fix realfill example compatibility with latest torchvision version

docs/source/en/using-diffusers/custom_pipeline_overview.md
Follows up on #5620 with a few suggestions and improvements 🙂 
1. Start by introducing and clarifying what community components are instead of discussing the more technical aspects of it (need to add Python modules for them).
2. Gradually reveal to the user they're loading a community UNet and pipeline.
3. Clarify a bit more that the users themselves aren't **implementing** the UNet, and they're just loading a custom one that we've already provided (same with the pipeline)
=> [docs] Custom community components

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Previously the `download_from_original_stable_diffusion_ckpt` function, when run with a SDXL model, would default to a `StableDiffusionPipeline` pipeline class. This would lead to downstream errors because the SDXL model has a `text_encoder_2` which is not recognized in the `StableDiffusionPipeline`.
A few lines below, the function checks if the model is a SDXL or SDXL-Refiner and sets the `model_type` variable accordingly.  
I moved the initialization of the default pipeline (when None is set specifically) below this detection if the model is SDXL or SDXL-Refiner and initialize the correct default pipeline. This makes it easier for users who for example run the `convert_original_stable_diffusion_to_diffusers.py` script.
**_This issue came to my attention only a few hours ago and I …
=> download_from_original_stable_diffusion_ckpt initializes correct default pipeline for SDXL

src/diffusers/pipelines/pipeline_utils.py
Issues #5714 
```
import torch
from diffusers import DiffusionPipeline, UNet2DConditionModel, AutoencoderKL
from peft import LoraConfig, get_peft_model
prompt = 'a man'
unet = UNet2DConditionModel.from_pretrained(
"stabilityai/stable-diffusion-xl-base-1.0", subfolder='unet', torch_dtype=torch.float16)
unet = get_peft_model(unet, LoraConfig(target_modules=["to_q", "to_v", "query", "value"]))
vae = AutoencoderKL.from_pretrained(
'madebyollin/sdxl-vae-fp16-fix',
)
'stabilityai/stable-diffusion-xl-base-1.0', unet=unet, vae=vae, torch_dtype=torch.float16)
pipe.to('cuda')
image = pipe(
prompt,
num_inference_steps=50,
width=1024,
height=1024,
).images[0]
image.save('demo.png')
```
This code raised following error.
``` …
```
=> [Enhacne] Support maybe_raise_or_warn for peft

src/diffusers/pipelines/pipeline_utils.py
This PR unwraps models everywhere in `pipeline_utils.py`.
Follow-up of #5556
=> Unwrap models everywhere

src/diffusers/models/resnet.py, src/diffusers/models/unet_3d_blocks.py, src/diffusers/models/unet_3d_condition.py, tests/pipelines/text_to_video_synthesis/test_text_to_video.py, tests/pipelines/text_to_video_synthesis/test_video_to_video.py
1. Reduces the size of the 3D UNet in the TextToVideo and Video2Video tests
2. Certain layers in the the 3D blocks had hardcoded values for the number of groups. This changes it so that they can be configured from the 3D UNet so that the model size can be reduced
3. Moves the slow `test_attention_slicing_forward_pass` from CPU to GPU  
Time taken for old tests
`== 12 passed, 11 skipped, 1 warning in 81.92s (0:01:21) ==`
New Time
`== 11 passed, 12 skipped, 1 warning in 10.23s =` …
=> Make Video Tests faster

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_sdxl.py, tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py
This PR adds support for LCM in:
- `StableDiffusionControlNetPipeline`
- `StableDiffusionXLControlNetPipeline`
- `StableDiffusionAdapterPipeline`
- `StableDiffusionXLAdapterPipeline`
Also added fast tests for LCMs with these pipelines.
=> Support LCM in ControlNet and Adapter pipelines.

README.md, docs/source/en/optimization/memory.md, docs/source/en/tutorials/basic_training.md, docs/source/en/using-diffusers/write_own_pipeline.md, docs/source/ko/optimization/fp16.md, docs/source/ko/tutorials/basic_training.md, docs/source/ko/using-diffusers/write_own_pipeline.md
- [Creating tensors directly on the GPU is ~22 times, and creating them directly as half-precision is ~4 times faster.](https://github.com/standardAI/ML-Practices/blob/main/PyTorch/PyTorch%20Tricks/PyTorch_tricks.ipynb)
-- Experiment environment:
-- CPU: AMD Ryzen 5 3550H
-- GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
-- Platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
-- Python version: 3.10.12
-- PyTorch version: 2.1.1
Of course, at the end of the day, the time for creating tensors in the docs doesn't create a visible difference, but I edited them as best practices.
- Removed .long() castings because the tensors were already created .long() format by default. …
=> [`Docs`] Update and make improvements

docs/source/en/_toctree.yml
Adds back the missing Tutorial section title
=> [docs] Fix title

examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_flax.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/research_projects/colossalai/train_dreambooth_colossalai.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py, examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py, scripts/convert_consistency_decoder.py, setup.py, src/diffusers/dependency_versions_table.py
Related to https://github.com/huggingface/transformers/issues/27034 and https://github.com/huggingface/huggingface_hub/pull/1782.
**TL;DR:** `hashlib` is not a secure library for cryptography-related stuff. We are only using `hashlib` for non-security-related purposes in `diffusers` so it's fine. From Python 3.9 we can set `usedforsecurity=False` in any `hashlib` method which is mandatory for companies that forbid the use of `hashlib` for security purposes. This PR fixes that.
**Note:** before merging this we need to release a new tokenizers version that would allow the newest `huggingface_hub` version (see https://github.com/huggingface/tokenizers/pull/1385). Otherwise it might create friction to users that want to install `diffusers` + `tokenizers` at the same time.
=> Set `usedforsecurity=False` in hashlib methods (FIPS compliance)

src/diffusers/utils/peft_utils.py
1. Speed up the peft lora unload
2. PR https://github.com/huggingface/peft/pull/1106 should be merged first
=> Speed up the peft lora unload

src/diffusers/models/modeling_flax_utils.py
An upcoming change to JAX will include non-local (addressable) CPU devices in jax.devices() when JAX is used multicontroller-style, where there are multiple Python processes.
This change preserves the current behavior by replacing uses of jax.devices("cpu"), which previously only returned local devices, with jax.local_devices("cpu"), which will return local devices both now and in the future.
This change is always safe (i.e., it should always preserve the previous behavior), but it may sometimes be unnecessary if code is never used in a multicontroller setting.
For a similar PR in `transformers` see huggingface/transformers#27593.
=> [JAX] Replace uses of jax.devices("cpu") with jax.local_devices(backend="cpu")

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
Adds a new _advanced_ version of `train_dreambooth_lora_sdxl.py`. 
- This advanced version builds up on enhancements and features added in [this PR](https://github.com/huggingface/diffusers/pull/5508)
- In addition, it includes support for **[pivotal tuning](https://arxiv.org/abs/2106.05744)**: 
> Pivotal Tuning combines training Textual Inversion with regular training. For Dreambooth, it is customary that you provide a rare token to be your trigger word, say "an sks dog", however, those tokens usually have other semantic meaning associated with them and can affect your results. The sks example, popular in the community, is actually associated with a weapons brand.
> 
> To tackle that issue with pivotal tuning, instead of re-using an existing token, we insert new tokens into the text …
=> Adds an advanced version of the SD-XL DreamBooth LoRA training script supporting pivotal tuning 

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_text2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py, src/diffusers/schedulers/scheduling_lcm.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py, tests/schedulers/test_scheduler_lcm.py
This PR adds custom `timesteps` support to `LCMScheduler.set_timesteps` and pipelines which support `LCMScheduler` (e.g. `LatentConsistencyModelPipeline`, `StableDiffusionPipeline`, `StableDiffusionXLPipeline`). This gives users the flexibility to try out timestep schedules beyond the "standard" LCM inference schedule (as calculated when `num_inference_steps` is given to `LCMScheduler.set_timesteps`). …
=> Add Custom Timesteps Support to LCMScheduler and Supported Pipelines

examples/textual_inversion/textual_inversion.py
if use cpu ipex. error like
File "/home/ywan171/diffusers/examples/textual_inversion/textual_inversion.py", line 989, in <modu
main()
File "/home/ywan171/diffusers/examples/textual_inversion/textual_inversion.py", line 756, in main
text_encoder, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
File "/home/ywan171/miniconda3/envs/diffuser/lib/python3.9/site-packages/accelerate/accelerator.py
args = self._prepare_ipex(*args)
File "/home/ywan171/miniconda3/envs/diffuser/lib/python3.9/site-packages/accelerate/accelerator.py
model, optimizer = ipex.optimize(model, optimizer=optimizer, dtype=dtype, inplace=True, level="O
File "/home/ywan171/miniconda3/envs/diffuser/lib/python3.9/site-packages/intel_extension_for_pytor
assert …
=> set the model to train state before accelerator prepare

examples/community/README.md, examples/community/dps_pipeline.py
This PR is a Community Pipeline with update of examples/comumunity/README.md and a new file examples/community/dps_pipeline.py. This pipeline implements the paper [ICLR 2023] Diffusion Posterior Sampling for General Noisy Inverse Problems:
* The paper deals with zero-shot conditional sampling from unconditional diffuision models, with the corrupted signal and corrunpting operator known. It is kind of magical, as it can do super-resolution, deblurring without any any training or finetuning.
* For example, using google's unconditional ddpm on celebahq dataset, we can reconstruct 
* Reconstructed image:
* ![dps_generated_image](https://github.com/tongdaxu/Images/assets/22267548/b74f084d-93f4-4845-83d8-44c0fa758a5f)
* from x4 downsampled image:
* Downsampled image: 
* …
=> [Community Pipeline] Diffusion Posterior Sampling for General Noisy Inverse Problems

docs/source/en/api/pipelines/kandinsky3.md
Fixes #5936
@patrickvonplaten @yiyixuxu
=> added doc for Kandinsky3.0

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, tests/pipelines/controlnet/test_controlnet_inpaint.py
This PR adds support of the ip-adapter to the StableDiffusionControlNetInpaintPipeline. The ip-adapter was added in #5713 and help was asked in #5884 I think it is very cool to have this support (see example below).
This PR refers to #5884
This is how it works:
```py
StableDiffusionControlNetInpaintPipeline,
ControlNetModel,
LCMScheduler,
)
import torch
import cv2
def get_canny_filter(image):
if not isinstance(image, np.ndarray):
image = np.array(image) 
image = cv2.Canny(image, 100, 200)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)
return canny_image
controlnet = ControlNetModel.from_pretrained( …
```
=> Support of ip-adapter to the StableDiffusionControlNetInpaintPipeline

docs/source/en/_toctree.yml, docs/source/en/training/lcm_distill.md
A first draft of the training docs for LCM. Please feel free to add more details where necessary and suggest any clarifications! ❤️ 
Complementary to the LCM inference docs in #5782
=> [docs] LCM training

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/stable_diffusion/sdxl_turbo.md, docs/source/en/using-diffusers/sdxl_turbo.md
=> [SDXL Turbo] Add some docs

docs/source/en/using-diffusers/svd.md
Temporary fix for the video link hosted on the Hub
=> [docs] Fix video link

examples/community/llm_grounded_diffusion.py
This PR makes `requires_safety_checker` a keyword argument so it doesn't collide with `StableDiffusionPipeline.image_encoder` in the parameter order.
Fixes #5992
@TonyLianLong
=> Fix LLMGroundedDiffusionPipeline super class arguments

docs/source/en/using-diffusers/svd.md
Fixes the video link from the Hub to use a more supported format - `webm` - for Chrome, and the `mp4` file is able to play without any issues in Safari :)
=> [docs] Fix SVD video

src/diffusers/utils/logging.py
Fixes #519. It seems that this issue was closed without resolving.
=> [`logging`] Fix assertion bug

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
fix this https://github.com/huggingface/diffusers/issues/5981
we refactored `add_noise` method to calculate based on sigmas in https://github.com/huggingface/diffusers/pull/5158, but `self.sigmas` is only created when you run `set_timesteps()`
this will cause error when the `add_noise` method is used without `set_timesteps()`, i.e. typical when used in training. In this PR we will create `self.sigmas` during `__init__`.
=> [schedulers] create `self.sigmas` during __init__

examples/community/README.md, examples/community/llm_grounded_diffusion.py
As discussed with @yiyixuxu  in #5993, we would like to inherit from `DiffusionPipeline` rather than `StableDiffusionPipeline`.
This PR also fixes the PEFT issue mentioned by @stevhliu .
This PR updates the example to use the `main` revision so that it uses the fixed pipeline without requiring `diffusers` update.
Tested locally that it works with `diffusers==0.24.0` with `peft==0.6.2` and without peft.
@yiyixuxu @stevhliu
=> LLMGroundedDiffusionPipeline: inherit from DiffusionPipeline and fix peft

examples/community/stable_diffusion_tensorrt_img2img.py, examples/community/stable_diffusion_tensorrt_inpaint.py, examples/community/stable_diffusion_tensorrt_txt2img.py
This PR makes `requires_safety_checkera`  keyword argument so it doesn't collide with StableDiffusionPipeline.image_encoder in the parameter order. 
Similar to the issue #[5992](https://github.com/huggingface/diffusers/issues/5992) 
@asfiyab-nvidia
=> fix StableDiffusionTensorRT super args error

docs/source/en/using-diffusers/kandinsky.md, src/diffusers/pipelines/kandinsky3/pipeline_kandinsky3.py
Adds text2image and image2image code snippets for Kandinsky 3 to the inference guide, fixes API doc parameters and adds docstrings
=> [docs] Add Kandinsky 3

examples/community/README.md, examples/community/pipeline_demofusion_sdxl.py
fix import on community pipeline #6022 
cc @RuoyiDu 
=> Fix demofusion

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
fix to save the embeddings also without `push_to_hub`
=> [advanced_dreambooth_lora_sdxl_tranining_script] save embeddings locally fix

examples/consistency_distillation/README.md, examples/consistency_distillation/README_sdxl.md, examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py, examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py, examples/consistency_distillation/train_lcm_distill_sd_wds.py, examples/consistency_distillation/train_lcm_distill_sdxl_wds.py
Had to make some adjustments to make it work with CC12M, as the metadata field names in the json are different. In particular, if no `pwatermark` field exists all images were rejected.
cc @stevhliu @sayakpaul @patil-suraj 
Fixes #5868, #5770.
Possibly fixes #5743 for other datasets.
=> Use CC12M for LCM WDS training example

.github/workflows/pr_test_fetcher.yml
Test Fetcher appears to be working correctly, but I noticed that a bunch of unrelated tests are being fetched for PRs. There are a few imports causing this issue
1. The `diffusers.pipelines.stable_diffusion.convert_from_ckpt` is directly imported in the FromSingleFileMixin, triggering all tests for all pipelines using that Mixin whenever the StableDiffusionPipeline is changed. 
2. StableDiffusionPipeline is directly imported into `test_pipelines_common.py` so all tests importing from this file are also triggered.
3. A change made to any of the pipelines imported in AutoPipeline also triggers tests for the other pipelines in auto pipeline.    
Proposing to pause test fetcher for now until these import issues are resolved. 
[documentation …
=> Disable Tests Fetcher

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
This PR adds the ability to cache the latents of the images so that redundant VAE passes are avoided
=> [Advanced Diffusion Training] Cache latents to avoid VAE passes for every training step

src/diffusers/schedulers/scheduling_euler_discrete.py
Fixes typing inconsistency in the Euler discrete scheduler. Depending on the interpolation type, sigmas is set to either be a numpy array (interpolation_type == "linear") or a torch tensor (interpolation_type == "log_linear"). This should consistently be a numpy array. 
@yiyixuxu
=> Fix typing inconsistency in Euler discrete scheduler

tests/models/test_models_prior.py, tests/models/test_models_unet_2d_condition.py, tests/models/test_models_vae.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion.py
Device to clear cache isn't set correctly on the device agnostic tests.  This PR fixes the issue.  
=> Fix clearing backend cache from device agnostic testing

src/diffusers/schedulers/scheduling_euler_discrete.py, tests/schedulers/test_scheduler_euler.py
Adds support for the `rescale_betas_zero_snr` config option to EulerDiscreteScheduler. Currently it works equivelently to DDIM with the concession that the final alpha_cumprod is patched to 2 ** -24 to resolve the `inf` issue, similar to what ComfyUI does.
~~This does not follow the 'curve' so to speak, and a value closer to 0 would be more appropriate, however lower values such as 2 ** -24 run into precision issues on fp16/bf16 inference. A more proper fix would be finding exactly where the precision issues lie in the pipeline code and resolving them (upcast?).  don't think I am math enough for this; 2 ** -16 is satisfactory from my benchmark images on the model "ptx0/terminus-xl-gamma-training".~~
I have fixed the precision issues by upcasting the sample for the duration of the step() …
=> EulerDiscreteScheduler add `rescale_betas_zero_snr`

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, tests/pipelines/controlnet/test_controlnet_img2img.py
Part of #5884 
@yiyixuxu @patrickvonplaten
=> IP-Adapter for StableDiffusionControlNetImg2ImgPipeline

src/diffusers/image_processor.py
Correct type annotation for `VaeImageProcessor.numpy_to_pil` from `(np.ndarray) -> PIL.Image.Image` to `(np.ndarray) -> List[PIL.Image.Image]`.
=> Correct type annotation for `VaeImageProcessor.numpy_to_pil`

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
This pr changes the final pipeline loading for inference to be inside the if block, to save memory when validation_prompt is not provided 
cc @apolinario
=> [advanced dreambooth lora sdxl training script] load pipeline for inference only if validation prompt is used

docs/source/en/training/lora.md
Adds missing `\`. Without it the command is called with only some of the arguments.
=> [docs] Add missing `\` in lora.md

tests/lora/test_lora_layers_old_backend.py, tests/lora/test_lora_layers_peft.py
Fixes for failings LoRA slow tests in the CI.  
=> LoRA test fixes

examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py, examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py, examples/consistency_distillation/train_lcm_distill_sd_wds.py, examples/consistency_distillation/train_lcm_distill_sdxl_wds.py
This PR cleans up and improves the comments in the LCM and LCM-LoRA distillation scripts. Includes a few small bug fixes.
@patil-suraj
@sayakpaul
=> Clean Up Comments in LCM(-LoRA) Distillation Scripts.

src/diffusers/loaders/lora.py
Potentially fixes: https://github.com/huggingface/diffusers/issues/6089. https://github.com/huggingface/diffusers/issues/6110 is related too. I decided to throw an error rather than trying to engineer a solution. I think that's best here because `_best_guess_weight_name()` solves a particular use case and I don't think we should overengineer it.
=> [LoRA] add an error message when dealing with _best_guess_weight_name ofline

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py
A follow-up of https://github.com/huggingface/diffusers/pull/6030.
Allow the main SD and SDXL pipelines to benefit from horizontal fusion of attention projection matrices. 
Related to: https://github.com/huggingface/sdxl-fast.
=> [Core] feat: enable fused attention projections for other SD and SDXL pipelines

benchmarks/base_classes.py
This PR fixes how the LCM benchmark numbers are reported.
=> [Benchmarks] fix: lcm benchmarking reporting

examples/text_to_image/README.md
Fix the test script in `examples/text_to_image/README.md`.
=> Fix the test script in examples/text_to_image/README.md

docs/source/en/training/unconditional_training.md
The `--mixed_precision` flag is already passed for this command, so no need to have it here (see line 192)
=> Nit fix to training params

src/diffusers/loaders/single_file.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Some refinements to `from_single_file` for the SDXL Inpainting model that allows it to work with the SDXL Refiner checkpoint. 
Also cleans up a lot of redundant checks and object creation in the `download_from_original_stable_diffusion_ckpt` function.
https://github.com/huggingface/diffusers/issues/6001
=> Fix SDXL Inpainting from single file with Refiner Model

scripts/convert_diffusers_to_original_stable_diffusion.py
Properly rename specific vae keys.
When extracting a sd 1.5 .safetensors using the from_single_file and then save_pretrained methods (as found in the convert_original_stable_diffusion_to_diffusers.py script), a handful of the vae keys are not properly renamed. 
This fixes that issue.
I determined this by first extracting and then re-compiling the v1-5-pruned-emaonly.safetensors file using the stock script, then re-compiling it the same way.
I then did a diff of the keys from the two checkpoints, and noted the differences this change fixes.
After applying this patch, the keys between the two models were almost exactly the same, with the exception of a handful of other keys that don't appear to be related to the actual model weights.
- [ x] This PR fixes a typo or improves …
=> Fix possible re-conversion issues after extracting from safetensors

src/diffusers/pipelines/shap_e/pipeline_shap_e_img2img.py, src/diffusers/pipelines/unclip/pipeline_unclip.py, src/diffusers/pipelines/unclip/pipeline_unclip_image_variation.py, tests/pipelines/animatediff/test_animatediff.py, tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py
Fixes some of small issues in certain pipelines caught by the slow test runner.  Should make slow pipeline tests in the CI green again.  
=> Slow Test for Pipelines minor fixes

docs/source/en/using-diffusers/controlnet.md
In the old code example, the masked region of images is filled with 1.0.
However, doc string and implementation require filling in with -1.0.
https://github.com/huggingface/diffusers/blob/aedd78767c99f7bc26a532622d4006280cc6c00d/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py#L75
https://github.com/huggingface/diffusers/blob/aedd78767c99f7bc26a532622d4006280cc6c00d/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py#L221
Core library:
- Docs: @stevhliu and @yiyixuxu
=> [Docs] Fix a code example in the ControlNet Inpainting documentation

examples/text_to_image/train_text_to_image_lora_sdxl.py
Referring to [commit](https://github.com/lvzii/diffusers/commit/288ceebea51abb439ca81684d642852c7fcc044a) ,
Fixes # (6086) in `train_text_to_image_lora_sdxl.py`, and Fixes # (4619) in `train_text_to_image_lora_sdxl.py` during fixing the former error.
=> fix: unscale fp16 gradient problem & potential error (#6086)

src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_diffedit/__init__.py, src/diffusers/pipelines/stable_diffusion_diffedit/pipeline_stable_diffusion_diffedit.py
Moves the DiffEdit pipeline out of `StableDiffusion` folder to reduce slow test timings. DiffEdit because its usage is very low. 
There will be follow-up PRs to this. This PR might help as a concrete reference.
=> [Refactor] move diffedit out of stable_diffusion

src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_gligen/__init__.py, src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen.py, src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen_text_image.py
Similar to https://github.com/huggingface/diffusers/pull/6260.
=> [Refactor] move gligen out of stable diffusion.

src/diffusers/pipelines/stable_diffusion/__init__.py
Since Pix2Pix Zero is a deprecated pipeline, it doesn't make sense to have it included inside `__init__.py` of `stable_diffusion`.
=> [Deprecated pipelines] remove pix2pix zero from init

docs/source/en/api/pipelines/stable_diffusion/ldm3d_diffusion.md, src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_ldm3d/__init__.py, src/diffusers/pipelines/stable_diffusion_ldm3d/pipeline_stable_diffusion_ldm3d.py
Similar to https://github.com/huggingface/diffusers/pull/6260.
=> [Refactor] move ldm3d out of stable_diffusion.

tests/lora/test_lora_layers_peft.py
Currently the `test_lora_layers_peft.py` file is being executed in the old lora backend runner. This is causing some confusion  when looking at CI results. This PR changes it so that PEFT tests do not run in the old lora backend runner. 
=> Remove peft tests from old lora backend tests

examples/dreambooth/train_dreambooth_lora_sdxl.py
Re-adds the exact same Prodigy-related parameters to the SDXL Dreambooth training script that were removed in the PEFT integration commit - see here: https://github.com/huggingface/diffusers/commit/c2717317f03b12535cfd02b477ace61189e10e4b#diff-21097f487be9184775f962c08b5cd60b92a31a99da8f3e0d8caf7867f50644d9L1197-L1216
This removal at first glance doesn't seem related to PEFT, and can affect how the prodigyopt works. 
@sayakpaul , @younesbelkada
=> Fix Prodigy optimizer in SDXL Dreambooth script

tests/lora/test_lora_layers_peft.py
Fixes: https://github.com/huggingface/diffusers/actions/runs/7313626946/job/19925422754#step:6:1994
=> fix: lora peft dummy components

examples/controlnet/test_controlnet.py, examples/custom_diffusion/test_custom_diffusion.py, examples/dreambooth/test_dreambooth.py, examples/dreambooth/test_dreambooth_lora.py, examples/instruct_pix2pix/test_instruct_pix2pix.py, examples/text_to_image/test_text_to_image.py, examples/text_to_image/test_text_to_image_lora.py, examples/textual_inversion/test_textual_inversion.py, examples/unconditional_image_generation/test_unconditional.py
Speeds up the example CPU tests by:
* Removing validation inference from textual inversion (since we don't do that for other example tests)
* Reduce the number of training steps whenever applicable without affecting the logical correctness 
Before this PR: https://huggingface.co/datasets/sayakpaul/sample-datasets/blob/main/reports/tests_torch_example_cpu_durations.txt
After this PR: https://huggingface.co/datasets/sayakpaul/sample-datasets/blob/main/reports-speed/tests_torch_example_cpu_durations.txt
=> [Tests] Speed up example tests

examples/consistency_distillation/README.md, examples/consistency_distillation/README_sdxl.md
This PR changes the SD and SD-XL LCM-LoRA README examples to use a learning rate of `1e-4` (instead of `1e-6`) to match the script defaults. (`1e-4` is also a better learning rate value.)
Fixes #6288.
@patil-suraj
@sayakpaul
@Zeqiang-Lai
=> Change LCM-LoRA README Script Example Learning Rates to 1e-4

src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_parallel.py, tests/schedulers/test_scheduler_ddpm.py, tests/schedulers/test_scheduler_ddpm_parallel.py
This PR adds a `rescale_betas_zero_snr` argument to `DDPMScheduler`.
@williamberman
@yiyixuxu
=> Add rescale_betas_zero_snr Argument to DDPMScheduler

docs/source/en/api/pipelines/animatediff.md
1. The AnimateDiff official checkpoint is sensitive to the choice of `beta_schedule` with  `linear` giving the best results. This PR adds that information to the docs page.
2. Updates the docs examples so that they use fp16.   
=> Update Animatediff docs

examples/instruct_pix2pix/README_sdxl.md
It replaces the wandb run with the correct link in `README_sdxl.md` for instructpix2pix training. The new link for wandb run is from the [diffusers/sdxl-instructpix2pix-768](https://huggingface.co/diffusers/sdxl-instructpix2pix-768) model page. (The old one was pointing to SD1.5 instructpix2pix run)
I think there is a typo on the model page as well. It says that batch size per GPU is 8 (x4 gradient accumulation=32) but in the wandb run, I see that it's 4 (x4 gradient accumulation=16).
Besides, I observe that some parameters differ from the script on `README_sdxl`. For example, the `diffusers/sdxl-instructpix2pix-768` model is trained with `learning_rate=5e-06` and `conditioning_dropout_prob=0.1` whereas the script defaults are `5e-05` and `0.05`. Hyperparameters differ from [SD1.5 IP2P …
=> [SDXL-IP2P] Update README_sdxl, Replace the link for wandb log with the correct run

src/diffusers/image_processor.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
This PR adds two auto1111 features to the inpainting pipeline, aiming to improve the "visible mask border" issue discussed here https://github.com/huggingface/diffusers/issues/5808
I simply added this to image processor, the user can blur the mask before passing it to the pipeline
```python
mask_blurred = pipe_inpaint.mask_processor.blur(mask, blur_factor=32)
out = pipe_inpaint(..., mask_image=mask_blurred, ...)
```
this feature corresponding to the inpaint area = "only masked" option in auto1111
It is quite interesting! when this is selected, it will:
-  crop out a rectangle area around the mask (based on a `padding` parameter user specified)
-  crop out the same area from the image
-  upscale both image and mask to full resolution and inpaint with them
-  size them back and overlay the …
=> adding auto1111 features to inpainting pipeline

src/diffusers/schedulers/scheduling_ddim_inverse.py, tests/schedulers/test_scheduler_ddim_inverse.py
Remove unused parameters for `DDIMInverseScheduler` and fix the `FutureWarning` about accessing the instance directly with `self`.
```
FutureWarning: Accessing config attribute `num_train_timesteps` directly via 'DDIMInverseScheduler' object attribute is deprecated. Please access 'num_train_timesteps' over 'DDIMInverseScheduler's config object instead, e.g. 'scheduler.config.num_train_timesteps'.
deprecate("direct config name access", "1.0.0", deprecation_message, standard_warn=False)
```
=> Remove unused parameters and fixed `FutureWarning`

examples/dreambooth/train_dreambooth_lora_sdxl.py, src/diffusers/utils/state_dict_utils.py
Reported by @apolinario. Internal thread: https://huggingface.slack.com/archives/C05GX934Z98/p1703334768186119. 
Currently, our LoRA trainers use `peft`. To load those LoRAs you need `peft` to be installed. However, we want those LoRAs to be loadable without `peft` too (or so I'd think?). 
This PR fixes that. 
* Colab to train a dummy LoRA with `peft`: https://colab.research.google.com/gist/sayakpaul/cc0886ada3ecdd5c3b305cf9862d2c72/scratchpad.ipynb
* Colab to load the dummy LoRA where `peft` isn't installed: https://colab.research.google.com/gist/sayakpaul/41c60a6bfb921108faf572508bc15469/scratchpad.ipynb
@apolinario does this work for you?
=> [LoRA] make LoRAs trained with `peft` loadable when `peft` isn't installed

examples/community/stable_diffusion_tensorrt_img2img.py
=> fix: use retrieve_latents

src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py
MPS doesn't support float64
Makes diffusers work on OSX using MPS
=> Fix support for MPS in KDPM2AncestralDiscreteScheduler

docs/source/en/tutorials/fast_diffusion.md
I ran the experiments FP16 again and found out that `torchao` is performing well without numerical problems in FP16. So, adding a note about it.
=> [Docs] add note on fp16 in fast diffusion

examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py
Fixes a problem in SDXL LoRA training script that ignores gradient checkpointing option.
Fixes #6388
* No, this PR fixes only a bug in implementation. No docs affected.
* https://github.com/huggingface/diffusers/issues/6388
* No docs needs update.
* I don't have good way to test this bugfix.
=> Fix gradient-checkpointing option is ignored in SDXL+LoRA training. (#6388)

docs/source/en/using-diffusers/inpaint.md
We just merged a PR https://github.com/huggingface/diffusers/pull/6072 that introduced a new method `apply_overlay` on`VaeImageProcessor`.
This is just a utility function to perform the "keep the unmasked area unchanged" task for inpaint pipeline. I'm updating the doc accordingly
=> [doc] update inpaint doc to use `apply_overlay`

src/diffusers/pipelines/pipeline_utils.py
Should close https://github.com/huggingface/diffusers/issues/6168.
This PR adds two behaviors:
- if offline mode is activated (i.e. `HF_HUB_OFFLINE=1`), we catch the error raised by `huggingface_hub` and default back to using the local files.
- if a ConnectionError happens while fetching model info, we catch the error and also default back to local files
In both cases, if local files don't exist an error will be raised later in the code (as we can't load the pipeline).
This PR should definitely settle the problems for users with slow/low connections. cc @sayakpaul with whom we discussed it at some point.
=> Respect offline mode when loading pipeline

examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py, examples/consistency_distillation/train_lcm_distill_lora_sdxl.py, examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py, examples/consistency_distillation/train_lcm_distill_sd_wds.py, examples/consistency_distillation/train_lcm_distill_sdxl_wds.py, src/diffusers/training_utils.py
This PR makes further improvements to the LCM-(LoRA) distillation scripts.
Changelist:
1. For all scripts, make the interpolation function when rescaling configurable via the `--interpolation_type` argument.
2. For the LCM-LoRA scripts, make the `lora_alpha` (which controls LoRA scaling) and `lora_dropout` parameters configurable via the `--lora_alpha` and `--lora_dropout` arguments respectively.
3. For the LCM-LoRA scripts, the LoRA target modules can be made configurable via the `--lora_target_modules` argument.
4. For all scripts, make the VAE encoding batch size configurable via the `--vae_encode_batch_size` argument.
5. For all scripts, refactor the `scalings_for_boundary_conditions` function to use the `timestep_scaling` argument (instead of it being hardcoded to `10.0`) and make …
=> Improve LCM(-LoRA) Distillation Scripts

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
Fixes the bug described in [#6444](https://github.com/huggingface/diffusers/issues/6444) that occurs when both
(`--checkpointing_steps < --max_train_steps`) and `--train_text_encoder_ti` is enabled. 
When enabling pivotal tuning, since we optimize the embeddings but we don't modify the text encoder weights, we shouldn't be saving text encoder lora layers in each checkpoint (which is what cause the error). This PR modifies `save_model_hook` such that they're saved only when full text encoder fine tuning is performed
=> [bug fix] fixes #6444 - checkpointing save issue in advanced dreambooth lora sdxl script 

tests/lora/test_lora_layers_old_backend.py
Hopefully the last in line for https://github.com/huggingface/diffusers/pull/6358.
=> [LoRA depcrecation] LoRA depcrecation trilogy

src/diffusers/pipelines/pipeline_utils.py
Setting a pipeline component to a compiled module and then calling `save_pretrained` results in an incorrect `model_index.json` file being created for the pipeline. This is because the compiled module isn't unwrapped before registering to config. 
This PR:
Moves a block of code in `register_modules` into a helper function that correctly unwraps the compiled module and extracts the correct library and class name. We can then apply this function everywhere that is needed to extract the library, class tuple. 
So it should also handle pipeline modules like MultiControlNet. 
#5617
[here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source- …
=> Correctly handle creating model index json files when setting compiled modules in pipelines. 

setup.py, src/diffusers/dependency_versions_table.py
Follow-up PR after https://github.com/huggingface/diffusers/pull/6456 (cc @sayakpaul).
In https://github.com/huggingface/diffusers/pull/6456, I added support for offline mode. However I forgot to update `huggingface_hub` version in the dependencies as highlighted by @voytez in https://github.com/huggingface/diffusers/pull/6456#issuecomment-1877767481.
This PR fixes this by making `huggingface_hub>=0.20.2` the minimal version. This shouldn't cause any problem as diffusers is already compatible with `0.20.2` and I'm not aware of any library pinning `huggingface_hub<0.20`.
(for the record, setting `HF_HUB_OFFLINE=1` doesn't raise an error when calling `model_info(...)` on versions <0.20.x)
=> Fix offline mode import

examples/dreambooth/train_dreambooth_lora_sdxl.py
Makes the DreamBooth SDXL LoRA compatible with `torch.compile()`. This has been requested by the community for a while. 
My `accelerate` config:
```bash
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_config:
dynamo_backend: INDUCTOR
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
I think this PR can definitely serve as a reference for contributors willing to do this for the other scripts (I will create an issue for that later).
=> [Training] make DreamBooth SDXL LoRA training script compatible with torch.compile

docs/source/en/tutorials/fast_diffusion.md
Follow up PR to #6311 with some small doc improvements, the main change is nesting the miscellaneous sections (no graph break and remove GPU sync) under the `torch.compile` section because they're related to compilation.
=> [docs] Fast diffusion

docs/source/en/api/loaders/peft.md, src/diffusers/loaders/peft.py
Follow up to #6416 with some minor edits for consistency :)
=> [docs] PEFT adapter API

docs/source/en/using-diffusers/svd.md
Updates the SVD doc with some minor improvements, mainly:
- removing the large duplicate source image on top of the side-by-side image/gif
- removing the `<Tip>` about reducing memory usage since this is repeated in a later section
=> [docs] Stable video diffusion

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, tests/pipelines/controlnet/test_controlnet_sdxl_img2img.py
Add IP-Adapter to StableDiffusionXLControlNetImg2ImgPipeline as it was missing so far.
=> Add IP-Adapter to StableDiffusionXLControlNetImg2ImgPipeline

docs/source/en/using-diffusers/inpaint.md
Follow up PR to #6364 to add `mask_blur` and `padding_mask_crop` to the docs.
=> [docs] mask_blur and padding_mask_crop

examples/consistency_distillation/train_lcm_distill_sd_wds.py, examples/consistency_distillation/train_lcm_distill_sdxl_wds.py
This PR fixes a bug in the LCM distillation scripts where the student `unet` config is not properly updated with `args.unet_time_cond_proj_dim` when `teacher_unet.config.time_cond_proj_dim` is `None`.
Fixes #6518.
@sayakpaul
@patil-suraj
=> Fix bug in LCM Distillation Scripts when args.unet_time_cond_proj_dim is used

examples/community/README.md, examples/community/pipeline_sdxl_style_aligned.py
Adds the SDXL implementation of Style Aligned.
Code: https://github.com/google/style-aligned
Paper: https://style-aligned-gen.github.io/data/StyleAligned.pdf
Project page: https://style-aligned-gen.github.io/
Fixes #6063.
Some results can be found in the [Colab](https://drive.google.com/file/d/15X2E0jFPTajUIjS0FzX50OaHsCbP2lQ0/view?usp=sharing) notebook.
GPU support generously provided by [ModelsLab](https://modelslab.com/).
@sayakpaul @patrickvonplaten @amirhertz
=> [Community] StyleAligned Pipeline

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py, src/diffusers/utils/torch_utils.py
With the current version of SVD, one cannot do:
```python
import torch
from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video
pipe = StableVideoDiffusionPipeline.from_pretrained(
"stabilityai/stable-video-diffusion-img2vid-xt", torch_dtype=torch.float16, variant="fp16"
)
image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png")
image = image.resize((1024, 576))
generator = torch.Generator(device="cuda").manual_seed(42)
frames = pipe(image, decode_chunk_size=8, generator=generator).frames[0]
export_to_video(frames, "generated.mp4", fps=7)
```
It leads to:
```bash
File "/home/sayak/svd.py", line 16, in …
```
=> [SVD] support generators that are created on GPU

docs/source/en/using-diffusers/svd.md, src/diffusers/utils/loading_utils.py
I removed the conversion to RGB in src/diffusers/utils/loading_utils.py. I spent hours trying to figure out why my RGBA images were getting a black background upon loading. I then realized that this function internally converts images to RGB, which should not be the case because this function is only responsible for loading the image. It's up to the user to decide which mode they want to convert their images to after loading them.
members/contributors who may be interested in your …
=> Remove conversion to RGB

examples/dreambooth/train_dreambooth_lora.py
=> Make Dreambooth SD LoRA Training Script torch.compile compatible

examples/controlnet/train_controlnet.py
Partially fixes #6503 concerning ControlNet's Training Script. Followed along with #6483 and #6511.
@sayakpaul @patrickvonplaten
=> Make ControlNet SD Training Script `torch.compile` compatible

examples/text_to_image/train_text_to_image.py
This PR makes `train_text_to_image.py` compatible with  `torch.compile()` as requested in #6503
=> SD text-to-image torch compile compatible

examples/dreambooth/train_dreambooth.py
=> Make Dreambooth SD Training Script `torch.compile` compatible

examples/dreambooth/train_dreambooth_lora_sdxl.py, src/diffusers/loaders/lora.py, src/diffusers/training_utils.py
Tries to solve issues like https://github.com/huggingface/diffusers/issues/6442 in a clean way. Limits the changes to the DreamBooth SDXL LoRA script for now. 
First run
```bash
CUDA_VISIBLE_DEVICES=0 accelerate launch train_dreambooth_lora_sdxl.py \
--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0 \
--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix \
--instance_data_dir="dog" \
--mixed_precision="fp16" \
--instance_prompt="a photo of sks dog" \
--output_dir="lora-trained-sdxl" \
--resolution=1024 \
--gradient_accumulation_steps=4 --gradient_checkpointing \
--learning_rate=1e-4 \
--lr_scheduler="constant" \
--lr_warmup_steps=0 \
--max_train_steps=4 --checkpointing_steps=2 --checkpoints_total_limit=2 \
--use_8bit_adam \ …
```
=> [Training] fix training resuming problem when using FP16 (SDXL LoRA DreamBooth)

examples/consistency_distillation/train_lcm_distill_lora_sdxl.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, src/diffusers/training_utils.py
We upcast the training parameters in the LoRA training scripts to prevent unscaling errors. This PR modularizes the LoCs responsible for doing that.
=> [Training Utils] create a utility for casting the lora params during training.

examples/text_to_image/train_text_to_image_lora.py
=> Make text-to-image SD LoRA Training Script torch.compile compatible

examples/text_to_image/train_text_to_image_lora_sdxl.py
=> Make text-to-image SDXL LoRA Training Script torch.compile compatible

examples/instruct_pix2pix/train_instruct_pix2pix.py
Part of #6503 for `instruct pix2pix`
@sayakpaul 🔢
=> Make InstructPix2Pix Training Script torch.compile compatible 

examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
Fixes a problem mentioned in https://github.com/huggingface/diffusers/pull/4632#issuecomment-1681650226. For now, the crop condition is problematic because of the flip operation.
First, the following lines should be changed from
```
image = crop(image, y1, x1, h, w)
if args.random_flip and random.random() < 0.5:
x1 = image.width - x1 # here, image.width is not in original state, but in cropped image state
image = train_flip(image)
```
to
```
orig_width = image.width
image = crop(image, y1, x1, h, w)
if args.random_flip and random.random() < 0.5:
x1 = orig_width - x1 # the width should be in original state
image = train_flip(image)
```
Then, to avoid confusion about the coordinates order, it is elegant to conduct flip before crop.
```
if args.random_flip and random.random() < 0.5:
image = …
```
=> Fix a bug of flip in SDXL training script

examples/community/README.md, examples/community/pipeline_animatediff_controlnet.py
Multicontrolnet did not work on community AnimateDiff+Controlnet pipeline due to incorrect `check_inputs()` implementation and a few missing statements. This PR fixes it.
Context: https://github.com/huggingface/diffusers/pull/5928#issuecomment-1888767581
Now you can do this:
<details>
<summary> Code </summary>
```python
import torch
from diffusers import AutoencoderKL, ControlNetModel, MotionAdapter
from diffusers.pipelines import DiffusionPipeline
from diffusers.schedulers import DPMSolverMultistepScheduler
motion_id = "guoyww/animatediff-motion-adapter-v1-5-2"
adapter = MotionAdapter.from_pretrained(motion_id)
controlnet1 = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", torch_dtype=torch.float16)
controlnet2 = …
```
=> [AnimateDiff+Controlnet] Fix multicontrolnet support

examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py
Fixes #6570.
In `StableDiffusionXLInstructPix2PixPipeline`, a shape discrepancy between `image_latents` and `latents` can occur if the `height` and `width` parameters are not explicitly initialized by the user.
Therefore, to tackle this problem, this PR enables image resizing to adjust its height and width.
@sayakpaul
=> Enable image resizing to adjust its height and width in StableDiffusionXLInstructPix2PixPipeline

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
Fixes #6482
Part of #6552 
Train
```
!accelerate launch scripts/train_dreambooth_lora_sdxl_advanced_orig.py \
--report_to="wandb" \
--pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
--pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
--dataset_name="./training_set" \
--output_dir="father_lora_v21" \
--cache_dir="./dataset_cache_dir" \
--caption_column="prompt" \ …
```
=> Fixes training resuming: Advanced Dreambooth LoRa Training

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py, tests/pipelines/stable_video_diffusion/test_stable_video_diffusion.py
This PR updates the `__call__()` method of `StableVideoDiffusionPipeline` to use a `np.ndarray` for the `frames` field of the returned `StableVideoDiffusionPipelineOutput` when the `output_type` arg is set to `np.ndarray` which matches the expected behavior described in [code comments](https://github.com/huggingface/diffusers/blob/3be7c96e28495d2e45af5a5f8488a9bb41d66ccb/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py#L64). The change is implemented by modifying the `tensor2vid()` helper function to stack the list of outputs into a single `np.ndarray` when `output_type` is set to `np`.
Fixes #6506  …
=> [SVD] Return np.ndarray when output_type="np"

docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile, docs/source/en/using-diffusers/sdxl.md, docs/source/en/using-diffusers/sdxl_turbo.md
As pointed out by @NielsRogge.
=> remove omegaconf from the residues 👋

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, tests/pipelines/controlnet/test_controlnet.py
Allow passing multiple image conditionings in a single batch for `StableDiffusionControlNetPipeline`. This feature was mentioned in the comments, but not implemented. 
See #6286 
@patrickvonplaten @sayakpaul
=> [Fix] Multiple image conditionings in a single batch for `StableDiffusionControlNetPipeline`

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
fixes the 3 issues with the advanced dreambooth lora sdxl training script, as described in #6486:
1. redundant retraction of embeddings when performing pivotal tuning 
2. zeroing of text encoder params (when pivoting halfway we only optimize the embeddings during the first X% of steps - to handle correctly (accelerate wise) the param change midway for the optimizer, we set the relevant params to zero) only happens for one step
3. incorrect casting of text encoder params to float32
=> [bug fix] advanced dreambooth lora sdxl - fixes bugs described in #6486

src/diffusers/utils/testing_utils.py
Using pathlib with URLs will remove the necessary `//` from `https://` strings. This is causing tests that rely on `load_hf_numpy` to fail. This function is only used in tests so we don't need to use Posix here. 
=> Fix failing tests due to Posix Path

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fixes: https://github.com/huggingface/diffusers/issues/6615.
Adds missing reading of config yaml file contents
=> Update convert_from_ckpt.py / read checkpoint config yaml contents

examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py
Partially fixes #6545 regarding InstructPix2Pix SDXL.
@sayakpaul
=> Modularize InstructPix2Pix SDXL inferencing during and after training in examples

docs/source/en/api/models/autoencoderkl.md, examples/text_to_image/README_sdxl.md, examples/text_to_image/train_text_to_image_lora_sdxl.py
When using DeepSpeed in the accelerate library to train a model, I encountered an issue while saving the checkpoint. I found that the model in save_model_hook is of type DeepSpeedEngine, which led to an "unexpected save model" error. To resolve this, I needed to unwrap the model, ensuring that it can be compared using isinstance for model type. After making these modifications, the model could be saved correctly.
fix this bug
after fix this bug ckpt can be saved
```
Steps:   4%|███▊                                                                                            | 80/2000 [03:38<53:16,  1.66s/it, lr=0.0001, step_loss=0.0303]01/18/2024 20:54:31 - INFO - accelerate.accelerator - Saving current state to sd-pokemon-model-lora-sdxl/checkpoint-80
01/18/2024 20:54:31 - …
```
=> Fixed the bug related to saving DeepSpeed models.

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
Add padding_mask_crop to inpaint pipelines: SDXL, ControlNet, ControlNet SDXL
Fixes #6345  (issue)
=> add padding_mask_crop to all inpaint pipelines

src/diffusers/pipelines/animatediff/pipeline_animatediff.py, src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py, tests/pipelines/animatediff/test_animatediff.py, tests/pipelines/text_to_video_synthesis/test_text_to_video.py, tests/pipelines/text_to_video_synthesis/test_video_to_video.py
This PR 
1. Standardises the output for the following pipelines by making them all use the same `tensor2vid` function to postprocess the 3D tensor output with shape (batch size, channels, num frames, height, width). 
TextToVideoSDPipeline
AnimateDiff
StableVideoDiffusionPipeline
2. Updates TextToVideoSDPipeline tests so that shapes of expected numpy array match the output from new postprocessing. 
TextToVideoZeroPipeline and TextToVideoZeroSDXLPipeline are excluded because they make use of 2D UNets, and produce an output with shape (batch size, channels, height, width) where the batch size == number of frames generated.   …
=> Standardise outputs for video pipelines

docs/source/ja/_toctree.yml, docs/source/ja/tutorials/autopipeline.md
**Changes included in this pull request**
Related to #6309
What is this PR about ?
I translated the following files to implified Japanese:
- _toctree.yml
- docs/ja/tutorials/autopipeline.md
here is the web page which is translated
https://huggingface.co/docs/diffusers/tutorials/autopipeline
What should you check ?
Grammar and orthograph
If my pull requests follows GitHub/open source contribution good practices (I am a beginner)
[Error with Doc-Builder: Error 404 on Section Pages in Doc-Builder Preview
](https://discuss.huggingface.co/t/error-with-doc-builder-error-404-on-section-pages-in-doc-builder-preview/68379/1) …
=> [Docs] update: tutorials ja | AUTOPIPELINE.md

examples/research_projects/controlnetxs/pipeline_controlnet_xs_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
Fixes a upcasting bug. 
Let's have a quick review here.
```
if self.vae.dtype == torch.float16 and self.vae.config.force_upcast:
self.upcast_vae()
latents = latents.to(next(iter(self.vae.post_quant_conv.parameters())).dtype)
if not output_type == "latent":
needs_upcasting = self.vae.dtype == torch.float16 and self.vae.config.force_upcast
if needs_upcasting:
self.upcast_vae()
latents = latents.to(next(iter(self.vae.post_quant_conv.parameters())).dtype)
image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False)[0]
if needs_upcasting:
self.vae.to(dtype=torch.float16)
```
Assuming that we set our model to float16. At the first `if`, the vae and latents are upcasted to float32 for avoiding overflow. Then, `needs_upcasting` is False as the vae is in float32 now. The …
=> [Fix bugs] pipeline_controlnet_sd_xl.py

src/diffusers/schedulers/scheduling_consistency_models.py, src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
Correcting the incorrect PR [here](https://github.com/huggingface/diffusers/pull/6173#issuecomment-1907948784).
Pretty big mistake on my side here - schedulers are no `nn.Modules` so every attribute is a tensor and therefore nothing is set in-place. Tensors have to manually be set.
It doesn't make a difference though in practice because the sigmas are **always on CPU** anyways. For the most important schedulers that I tested in #6173 (Euler & DPMSolverMultistep) `self.sigmas` should never be set to CUDA/GPU anyways so this PR shouldn't really change anything in practice, but is "correct" and ensures that scheduler sigmas are never on GPU.
=> Correct sigmas cpu settings

docs/source/en/api/pipelines/animatediff.md
Seems like we missed a spot as vid2vid was not reflected in the docs. Also example was broken as reported by someone on discord due to float16 not usable on cpu.
@DN6 @yiyixuxu
=> [docs] AnimateDiff Video-to-Video

examples/custom_diffusion/train_custom_diffusion.py
It fixes custom diffusion training script in the setup "concept list + synthetic regularization dataset". Currently, it fails / works incorrectly if class_prompt specified in multi concept scenario. See the linked issue for more information.
Fixes #6709
[here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation). (This is not needed)
@sayakpaul 
@nupurkmr9
=> fix custom diffusion training with concept list

src/diffusers/pipelines/onnx_utils.py
Introduces Posix to provide stronger support for Windows compatibility. Changes the instance of os.path.join() to Path(...).as_posix().
Fixes #6585 
@sayakpaul
=> Change os.path to pathlib Path

src/diffusers/loaders/textual_inversion.py
Fixes #6013 
@apolinario @sayakpaul
=> Add unload_textual_inversion method

examples/text_to_image/train_text_to_image_lora_sdxl.py
Fixes https://github.com/huggingface/diffusers/issues/6442
Part of https://github.com/huggingface/diffusers/issues/6552
training:
```
CUDA_VISIBLE_DEVICES=0 accelerate launch train_text_to_image_lora_sdxl.py \
--pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix \
--dataset_name="lambdalabs/pokemon-blip-captions" \
--mixed_precision="fp16" \
--output_dir="text_to_image_example" \
--resolution=1024 \
--gradient_accumulation_steps=4 --gradient_checkpointing \ …
```
=> Fix mixed precision fine-tuning for text-to-image-lora-sdxl example.

src/diffusers/utils/export_utils.py
Recently merged #6626 which uses a new `tensor_to_vid` function to output video frames. Frames in the `np` format are scaled to 0-1, which is causing an issue  with `export_to_video` since it expects numpy arrays scaled between 0-255. 
This PR: 
1. Adds a check to `export_to_video` to see if a numpy array has been passed in and scales it to 0-255 before writing to video. 
#6681
=> Update export to video to support new `tensor_to_vid` function in video pipelines

src/diffusers/schedulers/scheduling_ddim.py, src/diffusers/schedulers/scheduling_ddim_parallel.py, src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_parallel.py, src/diffusers/schedulers/scheduling_lcm.py, src/diffusers/schedulers/scheduling_pndm.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unclip.py
In my stable diffusion training workload, I am adding noise to the input image latents at each training step. From some analysis on the flamegraph, it seems that the `self.alpha_cumprod.to` operation in `DDPMScheduler.add_noise` takes a lot of time and becomes a bottleneck. 
This PR moves the tensor to the sample's device at the first time, then the `.to` operations in the following `add_noise` calls will be noop. The flamegraph after this change indicates that `add_noise` calls take much less time.
This might not be the most elegant solution, but it did reduce a huge overhead.
Before:
After:
[here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/doc …
=> [DDPMScheduler] Load `alpha_cumprod` to device to avoid redundant data movement.

src/diffusers/schedulers/scheduling_ddpm.py
Fixes #6732 to add missing `trained_betas` parameter to the docstring.
=> [docs] Add missing parameter

src/diffusers/training_utils.py
=> fix torchvision import

examples/community/stable_diffusion_reference.py, examples/community/stable_diffusion_xl_reference.py, src/diffusers/models/attention.py
fix https://github.com/huggingface/diffusers/issues/6838
I also fixed some other error in the sd reference community pipelines while I'm at it (so also fix https://github.com/huggingface/diffusers/issues/5028#issuecomment-1925483097)
we should deprecate these params too
=> add `self.use_ada_layer_norm_*` params back to `BasicTransformerBlock`

docs/source/en/api/pipelines/i2vgenxl.md, docs/source/en/api/pipelines/pia.md, docs/source/en/api/pipelines/text_to_video.md, src/diffusers/pipelines/animatediff/pipeline_output.py, src/diffusers/pipelines/i2vgen_xl/pipeline_i2vgen_xl.py, src/diffusers/pipelines/pia/pipeline_pia.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_output.py
Noticed a few small issues scattered throughout the video docs like missing example snippets, incorrect alt text etc. 
This PR:
1. Fixes these issues
2. Updates the docstrings for the pipeline outputs for each of the video pipelines that use the new `tensor_to_vid` export to explicity communicate that the frames are indexed based on the batch size.  
=> Multiple small fixes to Video Pipeline docs

src/diffusers/models/unets/unet_motion_model.py
We updated `UNet2dCondition` when introducing multi-ip-adapter https://github.com/huggingface/diffusers/pull/6573. However, we forgot to make the same change to `UnetMotionModel`, so currently ip-adapter + AnimteDiff is not working
this PR fix IP-adapter + AnimateDiff
```python
import torch
from diffusers import AnimateDiffPipeline, DDIMScheduler, MotionAdapter
from diffusers.utils import export_to_gif
adapter = MotionAdapter.from_pretrained("guoyww/animatediff-motion-adapter-v1-5-2", torch_dtype=torch.float16)
pipeline = AnimateDiffPipeline.from_pretrained("emilianJR/epiCRealism", motion_adapter=adapter, torch_dtype=torch.float16)
scheduler = DDIMScheduler.from_pretrained(
"emilianJR/epiCRealism",
subfolder="scheduler",
clip_sample=False, …
```
=> update IP-adapter code in UNetMotionModel

src/diffusers/utils/testing_utils.py
Switching `load_hf_numpy` in `testing_utils` breaks our model tests. This function is only used in the test suite, so it doesn't necessarily need to use a posix path. Reverting the change. 
=> Fix posix path issue in testing utils

src/diffusers/models/unets/unet_i2vgen_xl.py, src/diffusers/pipelines/i2vgen_xl/pipeline_i2vgen_xl.py
Follow-up of https://github.com/huggingface/diffusers/pull/6665. 
FYI @patrickvonplaten 
I didn't address https://github.com/huggingface/diffusers/pull/6665/files#r1471447995 because I don't think the resizing scheme should be made a part of `image_processor` as it's quite specific I2VGenXL. 
I will run the slow test of I2VGenXL once things look good just to be sure.
=> [I2vGenXL] clean up things

tests/pipelines/deepfloyd_if/test_if.py, tests/pipelines/deepfloyd_if/test_if_img2img.py, tests/pipelines/deepfloyd_if/test_if_img2img_superresolution.py, tests/pipelines/deepfloyd_if/test_if_inpainting.py, tests/pipelines/deepfloyd_if/test_if_inpainting_superresolution.py, tests/pipelines/deepfloyd_if/test_if_superresolution.py
The Deepfloyd IF slow tests runs all pipelines in a single test. This is a bit difficult to debug when there are timeouts/failed tests. Splitting these into individual tests.  
=> Refactor Deepfloyd IF tests. 

docs/source/en/using-diffusers/callback.md
On [this tutorial](https://huggingface.co/docs/diffusers/using-diffusers/callback) there is a function defined and then used inside `callback_on_step_end` argument, but the name was not correct (mismatch). Also the property name is `num_timesteps` not `num_timestep`.
@stevhliu, @yiyixuxu
=> fix: typo in callback function name and property

src/diffusers/loaders/ip_adapter.py
```python
import torch
from diffusers import AutoPipelineForText2Image
pipeline = AutoPipelineForText2Image.from_pretrained(
)
pipeline.load_ip_adapter(
"h94/IP-Adapter", 
subfolder="sdxl_models", 
weight_name=["ip-adapter-plus_sdxl_vit-h.safetensors", "ip-adapter-plus-face_sdxl_vit-h.safetensors"]
)
print(f" testing scale = 0.7")
try:
pipeline.set_ip_adapter_scale(0.7)
except Exception as e:
print(f"Error: {e}")
print(f" testing scale = [0.7]")
try:
pipeline.set_ip_adapter_scale([0.7])
except Exception as e:
print(f"Error: {e}")
print(f" testing scale = [0.7, 0.6]")
try:
pipeline.set_ip_adapter_scale([0.7, 0.6])
except Exception as e:
print(f"Error: {e}"
)
print(f" testing scale = [0.7, 0.5, 0.6]")
try: …
```
=> [ip-adapter] make sure length of `scale` is same as number of ip-adapters when using  `set_ip_adapter_scale`

examples/consistency_distillation/train_lcm_distill_lora_sdxl.py
Part of #6552 for [SDXL Consistency Distillation](https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_lora_sdxl.py)
First run this:
```{bash}
accelerate launch train_lcm_distill_lora_sdxl.py \
--pretrained_teacher_model="stabilityai/stable-diffusion-xl-base-1.0"  \
--pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
--output_dir="pokemons-lora-lcm-sdxl" \
--mixed_precision="fp16" \
--dataset_name="lambdalabs/pokemon-blip-captions" \
--gradient_accumulation_steps=1 …
```
=> Fix: training resume from fp16 for SDXL Consistency Distillation

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fixes a regression in using the `yaml` module for reading the config file when converting a checkpoint to diffusers format.  If no original config file is passed, `original_config_file` is set to a config yaml string.  This PR updates the else branch to do the same thing there.
Fixes #6899
@sayakpaul
=> Fix bug when converting checkpoint to diffusers format

src/diffusers/utils/export_utils.py
This PR introduces an fps (frames per second) argument to the export_to_gif function in the Diffusers library, with a default value of 10 fps. This feature allows users to specify the frame rate of the GIFs they generate, providing greater control over the animation's speed.
@patrickvonplaten @DN6
[Pillow documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif)
> duration
May not be present. …
=> Add fps argument to export_to_gif function.

src/diffusers/utils/loading_utils.py
`load_image` should support `PIL.Image`.
Fixes https://github.com/huggingface/diffusers/pull/6479#issuecomment-1933440898
- https://github.com/huggingface/diffusers/pull/6479
=> fix: load_image should support PIL Image

examples/textual_inversion/textual_inversion_sdxl.py
The `<cat-toy>` validation prompt is a default choice for the example task in the README. But no other part of `textual_inversion_sdxl.py` references the cat toy and `textual_inversion.py` has a default validation prompt of `None` as well.
So bring `textual_inversion_sdxl.py` in line with `textual_inversion.py` and change default validation prompt to `None`
@jiqing-feng @sayakpaul 
=> Remove <cat-toy> validation prompt from examples/textual_inversion/textual_inversion_sdxl.py

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
Fixes #6870 
@patrickvonplaten and @sayakpaul
=> Add vae tiling and slicing in img2img and inpaint

examples/controlnet/train_controlnet_flax.py
#6891 for [ControlNet flax](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_flax.py)
Example notebook
https://huggingface.co/camaro/test-model-card-template-controlnet-flax
@sayakpaul
=> Standardize model card for Controlnet flax

src/diffusers/models/attention_processor.py
fix https://github.com/huggingface/diffusers/issues/6700
also solve this issue discussed here: https://github.com/huggingface/diffusers/issues/6814
allowing attention processor with different signatures to be mixed and mathed together
=> allow attention processors to have different signatures 

examples/text_to_image/train_text_to_image_sdxl.py
Related issue: #6891 for [T2I Sdxl](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py)
Notebook link: [test_model_card_template_t2i_sdxl.ipynb](https://huggingface.co/cosmo3769/test-model-template-card-t2i-sdxl/blob/main/test_model_card_template_t2i_sdxl.ipynb)
Generated model card link: [test-model-card-template-t2i-sdxl](https://huggingface.co/cosmo3769/test-model-template-card-t2i-sdxl)
@sayakpaul
=> [Model Card] standardize T2I Sdxl model card

src/diffusers/pipelines/pipeline_utils.py
Fixes # Non CUDA devices with `enable_model_cpu_offload`
Target is DirectML and IPEX / XPU devices.
When re-enabling enable_model_cpu_offload in maybe_free_model_hooks, device is not used and enable_model_cpu_offload defaults to cuda.
This PR adds `self._offload_device` and passes it to enable_model_cpu_offload in maybe_free_model_hooks.
`self._offload_device` is also being set in `enable_sequential_cpu_offload` for compatibility reasons.
members/contributors who may be interested in …
=> Pass device to enable_model_cpu_offload in maybe_free_model_hooks

examples/t2i_adapter/train_t2i_adapter_sdxl.py
Related issue: #6891 for [T2I Adapter Sdxl](https://github.com/huggingface/diffusers/blob/main/examples/t2i_adapter/train_t2i_adapter_sdxl.py)
Notebook link: [test_model_card_template_t2i_adapter_sdxl.ipynb](https://huggingface.co/cosmo3769/test-model-card-template-t2i-adapter-sdxl/blob/main/test_model_card_template_t2i_adapter_sdxl.ipynb)
Generated model card link: [test-model-card-template-t2i-adapter-sdxl](https://huggingface.co/cosmo3769/test-model-card-template-t2i-adapter-sdxl)
@sayakpaul
=> [Model Card] standardize T2I Adapter Sdxl model card

docs/source/en/using-diffusers/custom_pipeline_overview.md, src/diffusers/pipelines/pipeline_utils.py
Addresses the comment [here](https://github.com/huggingface/diffusers/issues/6832#issuecomment-1925602071):
➕ how to load from a local file
➕ how to load from a specific version and specify community pipelines are loaded from the latest stable version rather than `main` 
➕ update `custom_revision` docstring
=> [docs] Community pipelines

src/diffusers/loaders/autoencoder.py, src/diffusers/loaders/single_file_utils.py
The scaling factor isn't correctly set when calling `AutoencoderKL.from_single_file` for SDXL models. It defaults to the SD scaling factor, leading to a washed out effect on the final image. 
Additionally [SD.Next uses the `config_file`](https://github.com/vladmandic/automatic/blob/418769285216d6add2e35a66a1a97c8d39397e45/modules/sd_vae.py#L193) argument to pass in the path to the original config file, rather than the `original_config_file` argument. This is missing in the current Mixin. 
This PR:
1. Allows setting VAE `scaling_factor` from the VAESingleFileMixin  
2. Update so that `AutoencoderKL.from_single_file` can accept a `config_file` argument as well.   
#6923
[here are tips on …
=> Fix configuring VAE from single file mixin

src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
For `lower_order_final=True` and `solver_order=2`, we would expect the order for the last step to be `1`, currently in`DPMSolverSinglestepScheduler` it does not work as expected for an even number of steps 
this is the `get_order_list` method of DPMSolverSinglestepScheduler, (see my comments in code below) https://github.com/huggingface/diffusers/blob/0a1daadef865f179895b6a2a679bb9db9b0ee8f3/src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py#L216
currently `lower_order_final=True` and `lower_order_final=False` have exactly same result
```python
def get_order_list(self, num_inference_steps: int) -> List[int]:
steps = num_inference_steps
order = self.config.solver_order
if self.config.lower_order_final:
if order == 3:
...
elif order == 2:
if steps % 2 == 0:
orders = [1, 2] * (steps …
```
=> [DPMSolverSinglestepScheduler] correct `get_order_list` for `solver_order=2`and `lower_order_final=True` 

src/diffusers/loaders/controlnet.py
=> Allow passing `config_file` argument to ControlNetModel when using `from_single_file`

docs/source/en/_toctree.yml, docs/source/en/api/loaders/ip_adapter.md, docs/source/en/using-diffusers/ip_adapter.md, docs/source/en/using-diffusers/loading_adapters.md, src/diffusers/loaders/ip_adapter.py
This (WIP) PR creates a more detailed and centralized guide for all things IP-Adapter related:
➖  removes non-loading related IP-Adapter content from the loading adapters guide
➕ adds IP-Adapter guide to the Techniques section
➕ adds `set_ip_adapter_scale` to the API docs
➕ IP-Adapter guide is largely divided based on tasks (text-to-image, image-to-image, image-to-video, etc.) and specific use cases (face models, instant generation, controllable generation, etc.)
=> [docs] IP-Adapter

tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py
update test since we changed the expected behavior of `unload_ip_adapter` with this PR  https://github.com/huggingface/diffusers/pull/6868
=> fix IPAdapter unload_ip_adapter test 

docs/source/en/using-diffusers/ip_adapter.md, src/diffusers/loaders/ip_adapter.py, src/diffusers/loaders/unet.py
This PR adds `low_cpu_mem_usage` support in `load_ip_adapter()` to speed up loading time. 
Script to test:
```python
from diffusers import AutoPipelineForText2Image
import torch
import time
import argparse
image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/load_neg_embed.png")
def run_sd(low_cpu_mem_usage):
start = time.time()
pipeline = AutoPipelineForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipeline.load_ip_adapter(
"h94/IP-Adapter", subfolder="models", weight_name="ip-adapter_sd15.bin", low_cpu_mem_usage=low_cpu_mem_usage
)
end = time.time()
print(f"Loading time -- {(end - start):.3f} seconds")
_ = pipeline(
prompt="best quality, high …
```
=> [IP Adapters] feat: allow low_cpu_mem_usage in ip adapter loading

docs/source/en/_toctree.yml, docs/source/en/api/attnprocessor.md, docs/source/en/api/pipelines/stable_diffusion/svd.md, docs/source/en/api/pipelines/text_to_video.md, docs/source/en/using-diffusers/text-img2vid.md
A more detailed text/image-to-video generation task guide similar to the existing ones we have. It also:
➕  adds `CrossFrameAttnProcessor` and Stable Video Diffusion to the API sections
➕ adds tip about `enable_forward_chunking` to the appropriate video pipelines (SVD, ModelscopeT2V) - closes #3935 
➕ adds I2VGen-XL
todo:
=> [docs] Video generation

src/diffusers/models/attention_processor.py
https://github.com/huggingface/diffusers/issues/6966#issuecomment-1950984337
=> start depcrecation cycle for lora_attention_proc 👋

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py
Adds documentation for `strength` parameter in `Controlnet_img2img` pipeline. 
The docstring is copied from the `Stable Diffusion img2img` pipeline. A (pressumably) deprecated docstring was also updated with this same docstring for the `Controlnet_SDXL_img2img` pipeline.
Fixes #6784 
@yiyixuxu
=> Add documentation for `strength` parameter in `Controlnet_img2img` pipelines

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
fix https://github.com/huggingface/diffusers/issues/6574
when user passes `image` input as a tensor with range `[0,1]` (not normalized), we still have to pass it through the CLIP Image Processor before encode it with image encoder 
this script now works as expected
```python
import torch
from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video
pipe = StableVideoDiffusionPipeline.from_pretrained(
"stabilityai/stable-video-diffusion-img2vid-xt", torch_dtype=torch.float16, variant="fp16"
)
image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png")
image = image.resize((1024, 576))
image = pipe.image_processor.pil_to_numpy(image)  # to np
image = …
```
=> [SVD] fix a bug when passing image as tensor

src/diffusers/utils/outputs.py
Fixes issue #7000. The latest PyTorch version (2.2) introduced a deprecation warning for `torch.utils._pytree._register_pytree_node` as used in `src/diffusers/utils/outputs.py`, suggesting the use of `torch.utils._pytree.register_pytree_node` (without the leading underscore). This PR updates the usage to align with the PyTorch recommendation, while also ensuring backward compatibility with older versions of PyTorch.
@yiyixuxu
=> Fix deprecation warning for torch.utils._pytree._register_pytree_node in PyTorch 2.2

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
Having this optional could really help use cases like [MGIE](https://github.com/apple/ml-mgie) to save further memory.
=> [IP2P] Make text encoder truly optional in InstructPi2Pix

tests/pipelines/pixart_alpha/test_pixart.py
Fixes precision related issues in the Pixart Slow tests. 
=> Fix Pixart Slow Tests 

src/diffusers/loaders/autoencoder.py, src/diffusers/loaders/controlnet.py, src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_utils.py
fix https://github.com/huggingface/diffusers/issues/4894
=> [from_single_file] pass `torch_dtype` to `set_module_tensor_to_device`

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py
Fixes #6866 and also an extension of PR: #6941
Added `IPAdapterMixin` loader to `StableDiffusionXLControlNetInpaintPipeline` to allow for `.load_ip_adapter` in pipeline.
Example snippet code:
```python
image_encoder = CLIPVisionModelWithProjection.from_pretrained(
"h94/IP-Adapter",
subfolder="models/image_encoder",
cache_dir=CACHE_DIR
).to(device)
pipe = StableDiffusionXLControlNetInpaintPipeline.from_pretrained(
weight_path,
cache_dir=CACHE_DIR,
vae=sd_vae,
controlnet=controlnet, 
image_encoder=image_encoder,
).to(device)
pipe.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter-plus_sdxl_vit-h.safetensors", cache_dir=CACHE_DIR)
images = pipe(
image=room_image,
ip_adapter_image=style_image, …
```
=> Supper IP Adapter weight loading in StableDiffusionXLControlNetInpaintPipeline

src/diffusers/loaders/single_file_utils.py
Small fix for `load_model_dict_into_meta` in ControlNet single file loading. It is  using `torch_dtype` instead of `dtype` 
=> Fix `load_model_dict_into_meta` for ControlNet `from_single_file`

tests/pipelines/stable_video_diffusion/test_stable_video_diffusion.py
`disable_full_determinism` is called on this single xformers test for StableVideoDiffusion. It doesn't seem necessary here since the test can run with full determinism enabled and none of the other `xformers` tests use this approach either.    
=> Remove `disable_full_determinism` from StableVideoDiffusion xformers test. 

examples/text_to_image/README.md, examples/text_to_image/README_sdxl.md, examples/text_to_image/test_text_to_image.py, examples/text_to_image/test_text_to_image_lora.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_flax.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
This pull request updates the copyright information in the text_to_image examples and fixes some typos in the code.
@sayakpaul
=> Fix typos in text_to_image examples

src/diffusers/models/unets/unet_2d_blocks.py, src/diffusers/models/unets/unet_2d_condition.py, src/diffusers/pipelines/deprecated/versatile_diffusion/modeling_text_unet.py
we accidentally reverted this PR in a merge conflict, adding it back 
https://github.com/huggingface/diffusers/pull/6478
=> re-add unet refactor PR 

examples/community/stable_diffusion_tensorrt_inpaint.py, examples/community/stable_diffusion_tensorrt_txt2img.py
fix the bug when I use custom pipeline: TensorRTStableDiffusionPipeline:
```
File "exchange_torch2trt.py", line 93, in <module>
gen_image(pipe=pipe, prompt=prompt, negative_prompt=neg_prompt)
File "exchange_torch2trt.py", line 72, in gen_image
image = pipe(prompt, negative_prompt=negative_prompt).images[0]
File "/usr/local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/.cache/huggingface/modules/diffusers_modules/local/stable_diffusion_tensorrt_txt2img.py", line 885, in __call__
self.guidance_scale = guidance_scale
File "/usr/local/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 622, in __setattr__
super().__setattr__(name, value)
AttributeError: …
```
=> fix: TensorRTStableDiffusionPipeline cannot set guidance_scale

src/diffusers/models/attention_processor.py
=> Fix head_to_batch_dim for IPAdapterAttnProcessor

docs/source/en/api/attnprocessor.md, docs/source/en/optimization/fp16.md, docs/source/en/optimization/torch2.0.md, docs/source/en/training/lora.md, docs/source/en/using-diffusers/stable_diffusion_jax_how_to.md
From internal discussion [here](https://huggingface.slack.com/archives/C041M7M98JV/p1707979651155499), this PR:
➕ some relevant links in the optimization guides (distilled model, PyTorch 2.0 optimizations, JAX)
➖ remove `LoRAAttnProcessor` from the training guide and API docs since it is no longer used
=> [docs] Minor updates

examples/community/README.md, examples/community/pipeline_animatediff_controlnet.py, examples/community/pipeline_animatediff_img2video.py
Addresses the issue mentioned [here](https://github.com/huggingface/diffusers/pull/6509#issuecomment-1960529248) that was caused due to UNet refactor. Also updates IPAdapter implementation to the latest as used by other pipelines.
@DN6 @Skquark
=> [Community] Bug fix + Latest IP-Adapter impl. for AnimateDiff img2vid/controlnet

src/diffusers/models/unets/unet_motion_model.py
Fixes #6958 also addresses #6125
@yiyixuxu @DN6
=> Pass use_linear_projection parameter to mid block in UNetMotionModel

scripts/convert_dance_diffusion_to_diffusers.py
Dance diffusion uses an `os.system` call to download the necessary checkpoint files for conversion. File downloads should use `requests` 
=> Small change to download in dance diffusion convert script

src/diffusers/loaders/lora.py, tests/lora/test_lora_layers_peft.py
As per title 
Fixes: https://github.com/huggingface/diffusers/issues/7054
There should be no reason to not copy the state dict of the lora layers if one passes a dict into `load_lora_weights`, therefore avoiding to sliently modifying the passed state_dict in-place. Added also a nice test with a state dict pushed under hf-internal-testing
cc @yiyixuxu @sayakpaul @pacman100
=> FIX [`PEFT` / `Core`] Copy the state dict when passing it to `load_lora_weights`

examples/controlnet/README_sdxl.md, examples/controlnet/train_controlnet.py, examples/controlnet/train_controlnet_sdxl.py
This PR adds another call to the `log_validation()` function after the serialization of the trained ControlNet checkpoint. This helps to validate if the training was effective and catch issues like https://github.com/huggingface/diffusers/issues/7080.
=> [Examples] Multiple enhancements to the ControlNet training scripts

docker/diffusers-flax-cpu/Dockerfile, docker/diffusers-flax-tpu/Dockerfile, docker/diffusers-onnxruntime-cpu/Dockerfile, docker/diffusers-onnxruntime-cuda/Dockerfile, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile
This PR updates the Dockerfiles to use `uv` for package resolution and installation. Once this PR is merged and the new Dockerfiles are pushed (should be done by Wednesday, hopefully) will update the actions to make use of `uv`.
=> move to `uv` in the Dockerfiles.

tests/models/autoencoders/test_models_vae.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_sdxl.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_upscale.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
The UI frameworks for SD rely extensively on the single file format. To ensure more robust support for these communities, we should check to make sure the pipeline components that are returned using `from_pretrained` and `from_single_file` are aligned. 
This PR adds a set of tests to the pipelines that use `from_single_file` to ensure that the components loaded using a `from_single_file` checkpoint and those loaded using the diffusers format version of the same checkpoint are configured the same way. 
This is useful to catch issues such as 
#6753 
#6964  …
=> Add tests to check configs when using single file loading 

src/diffusers/models/autoencoders/autoencoder_kl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
This PR adapts SDXL pipeline slightly to denormalize `latents` with mean and std if available in the vae config. We could also consider having these arguments in the vae `__init__` if more models starts doing this.
=> denormalize latents with the mean and std if available

docker/diffusers-flax-tpu/Dockerfile
Fixes https://github.com/huggingface/diffusers/actions/runs/8063137238/job/22024350346. 
Raised an issue: https://github.com/astral-sh/uv/issues/2010.
=> [Dockerfile] remove uv from docker jax tpu

src/diffusers/__init__.py, src/diffusers/schedulers/__init__.py, src/diffusers/schedulers/scheduling_edm_euler.py, src/diffusers/schedulers/scheduling_utils.py, src/diffusers/utils/dummy_pt_objects.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_latent_upscale.py, tests/schedulers/test_scheduler_edm_euler.py, tests/schedulers/test_schedulers.py
This PR is based on #4481 by @dg845 !
This PR adds Euler scheduler with EDM formulation. The difference between this and `EulerDiscreteScheduler` is that
- `EulerDiscreteScheduler` was essentially designed for DDPM models to use euler-style sampling algorithms with discrete timesteps. 
- `EDMEulerScheduler` follows the EDM formulation as closely as possible and is solely intended for models that use EDM formulation, like SVD. It does not support epsilon scaling as that's already covered by `EulerDiscreteScheduler`. So models that still DDPM (the alphas and betas schedules) should keep using `EulerDiscreteScheduler`
**Why add a new scheduler class ?**
While it is possible to support this in  `EulerDiscreteScheduler` by introducing an argument maybe called `scaling_type`, which could …
=> Add EDMEulerScheduler

examples/dreambooth/train_dreambooth_lora.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, tests/schedulers/test_scheduler_dpm_multi.py
Effectively identical to the implementation for EulerDiscrete in https://github.com/huggingface/diffusers/pull/6024
TL;DR:
- `rescale_zero_terminal_snr` function copied from DDIM
- Fudge the last cumprod to `2**-24` from `0` when using zsnr so it doesn't produce an `inf` sigma
- Upcast samples to `torch.float32` for the duration of `step()` because the zsnr sigmas are substantially less numerically stable and the performance hit is negligible.
- Also has the side effect of producing *slightly* better images overall
- `use_karras_sigmas=True` still produces strange results as it does in EulerDiscrete. Might be worth investigating separately?
- Simple true/false UT for the new config value
Demo images
`use_karras_sigmas` also seems to just generally produce bad/noisy results even without …
=> DPMSolverMultistep add `rescale_betas_zero_snr`

utils/stale.py
currently, our StaleBot isn't working as expected:
1. it does not re-open issues - it is supposed to open the issue if someone other than Stalebot commented but it does not do that
* if you go through our staled PR you can find lots of examples https://github.com/huggingface/diffusers/pull/6595
3. it will close an issue even if we had remove the "stale" label manually, e.g https://github.com/huggingface/diffusers/issues/6248#issuecomment-1964390412
However, I think the expected behavior of the StaleBot to automatically re-open an issue after someone comments is a little bit questionable. e.g., if we leave a comment asking, "Can we close this now?" - it will trigger the StaleBot to reopen the issue. for example, here https://github.com/huggingface/diffusers/issues/6695
Maybe we should come …
=> [stalebot] don't close the issue if the stale label is removed

src/diffusers/models/unets/unet_2d_condition.py
Addresses https://github.com/huggingface/diffusers/pull/7044#discussion_r1506473969 along with some other minor type annotation changes.
@yiyixuxu
=> [docs] unet type hints

scripts/convert_animatediff_motion_module_to_diffusers.py
`save_pretrained` doesn't actually use `torch_dtype` to convert the checkpoint to `fp16` before saving. This PR adds a fix to the convert script so that `fp16` weights are saved correctly for AnimateDiff models
=> Fix setting fp16 dtype in AnimateDiff convert script.  

.github/workflows/build_docker_images.yml, docker/diffusers-flax-cpu/Dockerfile, docker/diffusers-flax-tpu/Dockerfile, docker/diffusers-onnxruntime-cpu/Dockerfile, docker/diffusers-onnxruntime-cuda/Dockerfile, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile
https://github.com/huggingface/diffusers/pull/7113 introduced `uv` in our Docker containers. This run confirmed that everything worked with `uv` (version 0.1.11): https://github.com/huggingface/diffusers/actions/runs/8063807103. 
However, the currently version (0.1.13) is breaking it: https://github.com/huggingface/diffusers/actions/runs/8104362499. 
Hence, this PR pins the `uv` version for now. Related thread on `uv`: https://github.com/astral-sh/uv/issues/2010.
=> [Urgent][Docker CI] pin `uv` version for now and a minor change in the Slack notification

.github/workflows/benchmark.yml, benchmarks/base_classes.py
The LCM LoRA benchmark test current fails: https://github.com/huggingface/diffusers/actions/runs/8105285148/job/22153378360#step:8:52. This PR fixes that. Additionally, makes benchmarking workflow dispatchable.
=> Fix LCM benchmark test

.github/workflows/push_tests.yml
We don't need to set the max parallel parameter on the slow test runners anymore since we're using the large pool of runners available to all OS projects.   
=> [CI] Remove max parallel flag on slow test runners 

examples/text_to_image/train_text_to_image_sdxl.py
The hash used as new fingerprint when computing the VAE encodings in train_text_to_image_sdxl.py should change if the VAE changes.
Previously if someone used different VAEs using this script, it would always reload the first result in the dataset cache instead of recomputing using the different VAE.
I haven't checked in other examples for similar cases, maybe it can be worth checking.
@sayakpaul
=> Fix vae_encodings_fn hash in train_text_to_image_sdxl.py

utils/stale.py
had a bug in the PR i did yesterday, fixing it 
https://github.com/huggingface/diffusers/actions/runs/8098086020/job/22130683011#step:5:14
=> [stalebot] fix a bug 

src/diffusers/pipelines/animatediff/pipeline_animatediff.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video.py, src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_text2img.py, src/diffusers/pipelines/pia/pipeline_pia.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion_ldm3d/pipeline_stable_diffusion_ldm3d.py, src/diffusers/pipelines/stable_diffusion_panorama/pipeline_stable_diffusion_panorama.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
Allows the use of 4D tensors to be able to pass embeds made with the IP Adapter PLUS versions
Fixes #7168
How to test:
```py
import torch
from diffusers import AutoPipelineForText2Image
pipeline = AutoPipelineForText2Image.from_pretrained(
"stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16"
)
pipeline.load_ip_adapter(
"h94/IP-Adapter",
subfolder="sdxl_models",
weight_name=[
"ip-adapter_sdxl_vit-h.safetensors",
"ip-adapter-plus_sdxl_vit-h.safetensors",
"ip-adapter-plus-face_sdxl_vit-h.safetensors",
],
image_encoder_folder="models/image_encoder",
)
pipeline.set_ip_adapter_scale([0.1, 0.7, 0.3])
pipeline.to("cuda")
face_image = load_image("https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/women_input.png …
```
=> [ip-adapter] fix problem using embeds with the plus version of ip adapters

docs/source/en/tutorials/using_peft_for_inference.md
Buttons up the `torch.compile()` section in the PEFT inference guide. 
Single adapter example:
```python
import torch
pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")
pipe.load_lora_weights("nerijs/pixel-art-xl", weight_name="pixel-art-xl.safetensors", adapter_name="pixel")
pipe.fuse_lora(adapter_names=["pixel"])
pipe.unload_lora_weights()
pipe.unet.to(memory_format=torch.channels_last)
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
prompt = "toy_face of a hacker with a hoodie, pixel art"
image = pipe(prompt, num_inference_steps=30, generator=torch.manual_seed(0)).images[0]
image = pipe(prompt, num_inference_steps=30, …
```
=> [Docs] more elaborate example for peft `torch.compile`

src/diffusers/pipelines/stable_diffusion_ldm3d/pipeline_stable_diffusion_ldm3d.py
=> adding `callback_on_step_end` for `StableDiffusionLDM3DPipeline`

src/diffusers/configuration_utils.py
fix https://github.com/huggingface/diffusers/issues/7183
this script now runs expected
```pythn
from diffusers import DiffusionPipeline, EulerAncestralDiscreteScheduler, LCMScheduler, AutoencoderKL
import torch
model_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(model_id, variant="fp16", torch_dtype=torch.float16)
#print correct value
print(f" test1: should print EulerAncestralDiscreteScheduler")
print(pipe.scheduler.config._class_name)
print(pipe.scheduler)
print(pipe.scheduler.config._class_name)
pipe.scheduler = LCMScheduler.from_config(pipe.scheduler.config)
#gives Euler not LCM
print(f" test2: shuld print LCMScheduler")
print(pipe.scheduler.config._class_name)
print(pipe.scheduler)
print(pipe.scheduler.config._class_name)
pipe.scheduler = …
```
=> fix a bug in `from_config`

src/diffusers/schedulers/scheduling_euler_discrete.py
PyTorch's FakeTensorMode does not support `.numpy()` or `numpy.array()` calls.
This PR replaces `sigmas` numpy tensor by a PyTorch tensor equivalent
Repro
```python
with torch._subclasses.FakeTensorMode() as fake_mode, ONNXTorchPatcher():
fake_model = DiffusionPipeline.from_pretrained(model_name, low_cpu_mem_usage=False)
```
that otherwise would fail with
`RuntimeError: .numpy() is not supported for tensor subclasses.`
Fixes https://github.com/huggingface/diffusers/issues/7152
=> Enable PyTorch's FakeTensorMode for EulerDiscreteScheduler scheduler

src/diffusers/pipelines/pipeline_loading_utils.py, src/diffusers/pipelines/pipeline_utils.py
Currently, our `pipeline_utils.py` file has got a lot of code filled with many utility methods. As maintainers, we often have to deal with this file to verify things. It gets convoluted at times to scroll through the entire file. 
To that end, this PR moves all the utilities to a `pipeline_loading_utils.py` file to keep the `pipeline_utils.py` contents relatively manageable and to the point.
=> [Core] move out the utilities from pipeline_utils.py

examples/dreambooth/README_sdxl.md, examples/dreambooth/train_dreambooth_lora_sdxl.py
adding DoRA feature to the canonical dreambooth lora training script (at the moment was added to the advanced script only)
Following up on: https://github.com/huggingface/diffusers/pull/7072 & https://github.com/huggingface/peft/pull/1474
=> add DoRA training feature to sdxl dreambooth lora script

src/diffusers/pipelines/stable_cascade/pipeline_stable_cascade.py
It is currently not possible to use the `bfloat16` dtype with the SD Cascade decoder pipeline when torch version < 2.2
This PR adds a check that raises an error when this is attempted. 
=> Raise an error when trying to use SD Cascade Decoder with dtype bfloat16 and torch < 2.2

docs/source/en/_toctree.yml, docs/source/en/tutorials/using_peft_for_inference.md, docs/source/en/using-diffusers/loading_adapters.md, docs/source/en/using-diffusers/merge_loras.md
Continuation of #7110 to implement [option 3](https://github.com/huggingface/diffusers/pull/7110#pullrequestreview-1904781705) for combining all merge methods into one doc and cleaning up the other docs to focus on loading or basic usage.
=> [docs] Merge LoRAs

examples/community/rerender_a_video.py
fixes rerender_a_video.py pipeline to use self.device instead of cuda
@SingleZombie
=> use self.device

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, tests/pipelines/test_pipelines_common.py
Fixes: https://github.com/huggingface/diffusers/actions/runs/8186113762/job/22383917960#step:8:4060
=> [Tests] fix: VAE tiling tests when setting the right device

examples/dreambooth/train_dreambooth_lora_sdxl.py
Easy. 
As pointed out by @ritwikraha through Whatsapp.
=> [Easy] fix: save_model_card utility of the DreamBooth SDXL LoRA script

src/diffusers/models/unets/unet_2d_condition_flax.py
Currently `FlaxUNet2DConditionModel` requires a mid block. However, certain UNet architectures drop the mid block entirely, e.g. [tiny-sd](https://huggingface.co/segmind/tiny-sd). It would be nice to have this optional.
Without this PR:
```python
from diffusers import FlaxUNet2DConditionModel
unet, params = FlaxUNet2DConditionModel.from_pretrained('segmind/tiny-sd', subfolder='unet', from_pt=True)
```
With this PR, the above should convert properly.
@pcuenca
=> Make mid block optional for flax UNet

examples/community/README.md, examples/community/marigold_depth_estimation.py
The Marigold pipeline has no option to disable generation of the colormap. This PR disables the colormap when passing `color_map=None`.
Fixes #6928 
Tagging original author & reviwer:
- @markkua
- @sayakpaul
=> [Community Pipeline] Skip Marigold `depth_colored` with `color_map=None`

src/diffusers/models/modeling_utils.py
=> [Chore] remove tf mention

examples/community/README.md, examples/community/rerender_a_video.py
users cannot change `gmflow_dir`
since every time
custom pipeline gets downloaded
and overrides user changes
this fixes that
@SingleZombie
=> Fix gmflow_dir

examples/community/rerender_a_video.py
inlines `InputPadder` class from `gmflow/utils`
because I cannot get `utils.utils` to import:  
`ModuleNotFoundError: No module named 'utils.utils'; 'utils' is not a package`. 
but the `gmflow` module works just fine?!
@SingleZombie
=> Inline InputPadder

src/diffusers/loaders/single_file_utils.py, src/diffusers/loaders/unet.py, src/diffusers/models/unets/unet_stable_cascade.py, tests/models/unets/test_models_unet_stable_cascade.py
Adds single file support to the StableCascadeUNet, which allows users to load in checkpoints published in the original format. 
The single file loading logic and mappings are defined within the UNet without a Mixin, since the mapping functions have be accessible to the `from_single_file` method somehow. It relies on fetching the configs from a hosted repo of configs hosted on the diffusers org. 
This is a more practical approach, since a single file pipeline checkpoint would be quite large (~34GB) to load. Single File loading with combined pipelines is also not something we support at the moment and it is particularly challenging with Cascade due to the dtype restrictions in the Prior (Stage C) pipeline, which cannot work with float16, while the decoder (Stage B) can.  …
=> Add single file support for Stable Cascade

src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_utils.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
`set_additional_components` for SDXL refiner based pipelines in `from_single_file` is breaking because no checkpoint argument is passed in. 
This PR
1. Passes in the checkpoint to `infer_model_type` so that the `edm_mean` and `edm_std` checks for Playground type models doesn't fail. 
2. Makes checkpoint a required argument for `infer_model_type` 
=> Fix loading Img2Img refiner components in `from_single_file`

src/diffusers/loaders/unet.py
As pointed about by @vladmandic in https://github.com/huggingface/diffusers/pull/7274#issuecomment-1993303978.
=> [Chore] clean residue from copy-pasting in the UNet single file loader

.github/workflows/notify_slack_about_release.yml, .github/workflows/pypi_publish.yaml, utils/fetch_latest_release_branch.py, utils/notify_slack_about_release.py
This PR adds utilities to semi-automate the process of publishing a new release on PyPI and notifying our internal Slack channel about it. 
[`setup.py`](https://github.com/huggingface/diffusers/blob/main/setup.py) clearly lays out the steps needed in order for us to prepare a new library and publish it on PyPI. Steps from 1 - 6 need careful inspection and might often require manual intervention. But steps 7 - 9 and making an announcement on Slack about the release don't require it IMO and can be systematically automated. 
1. As mentioned earlier, the PR assumes that we need some level of babysitting till step 6 of the publishing process. So, the workflow, `pypi_publish.yaml` starts after it. More specifically, it gets triggered after a tag is created and pushed. It then does the …
=> [PyPI publishing] feat: automate the process of pypi publication to some extent.

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/inference_with_tcd_lora.md
@sayakpaul 
Hi Sayak, I've updated an intro page for TCD. Please have a review.
=> Add Intro page of TCD

src/diffusers/models/unets/unet_2d_condition.py
This pull request adresses a typo and some formatting in the documentation for the `UNet2DConditionModel`. It contains 3 commits:
- One to solve an inconsistency between the default behavior and documentation.
- Two to address some formatting problems in the documentation.
=> Fix typos in `UNet2DConditionModel` documentation

src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
Resolves #5705 by adding additional checks on number of `order` parameters according to @vladmandic recommendation [here](https://github.com/huggingface/diffusers/issues/5705#issuecomment-1810976803).
Additionally follows directive from @patrickvonplaten [here](https://github.com/huggingface/diffusers/issues/5705#issuecomment-1821016791) and raises `valueError` if `order > 3`.
=> update get_order_list if statement

.github/workflows/nightly_tests.yml
Add the `pytest-reportlog` dependency. Otherwise, https://github.com/huggingface/diffusers/actions/runs/8273408523/job/22637123355 happens. 
Created a simple yet reasonable test suite: 
```python
#
#
#
import gc
import unittest
import torch
DiffusionPipeline,
LCMScheduler,
)
from diffusers.utils.import_utils import is_accelerate_available, is_peft_available
from diffusers.utils.testing_utils import (
load_image,
numpy_cosine_similarity_distance,
require_torch_gpu,
slow,
)
if is_accelerate_available():
from accelerate.utils import release_memory
if is_peft_available():
pass
@slow
@require_torch_gpu
class LoraSDXLIntegrationTests(unittest.TestCase):
def tearDown(self):
super().tearDown()
gc.collect()
def …
```
=> add: pytest log installation

docs/source/en/_toctree.yml, docs/source/en/api/edm_multistep_dpm_solver.md, docs/source/en/api/schedulers/edm_euler.md, docs/source/en/api/schedulers/edm_multistep_dpm_solver.md
Adds the edm schedulers in docs.
=> add edm schedulers in doc

tests/models/unets/test_models_unet_stable_cascade.py, tests/pipelines/stable_cascade/test_stable_cascade_decoder.py, tests/pipelines/stable_cascade/test_stable_cascade_prior.py
Update cascade tests after model PR merge. 
=> Update Cascade Tests

src/diffusers/pipelines/auto_pipeline.py
Just adds
- `AUTO_TEXT2IMAGE_PIPELINES_MAPPING["cascade"] = StableCascadeCombinedPipeline`
- `_AUTO_TEXT2IMAGE_DECODER_PIPELINES_MAPPING["cascade] = StableCascadeDecoderPipeline`
So you can run
```python
pipe = AutoPipelineForText2Image.from_pretrained("stabilityai/stable-cascade")
```
Works in my diffusers CLI app, performing equivalent to `StableCascadeCombinedPipeline` in my limited tests. LMK if there's something else I need to do to validate the privated decoder mapping.
=> Add Cascade to Auto T2I + Decoder mappings

docs/source/en/_toctree.yml, src/diffusers/models/unets/unet_2d_condition.py
The changes should be self-explanatory. But let me know in case of any explanation. 
I think we should maybe do a patch release for this.
=> [LoRA] pop the LoRA scale so that it doesn't get propagated to the weeds

src/diffusers/loaders/ip_adapter.py, src/diffusers/loaders/lora.py, src/diffusers/loaders/textual_inversion.py, src/diffusers/loaders/unet.py, src/diffusers/models/modeling_utils.py
`torch.load` implicitly uses pickle unless `weights_only` is set to `True`. This is potentially unsafe. 
This PR:
Replaces any `torch.load` calls with `load_state_dict` that sets the `weights_only=True` argument for torch versions > 1.13, This is similar to what has been done in transformers
https://github.com/huggingface/transformers/blob/c852d4fba6a46f8b71c608041a10691b66f174e5/src/transformers/modeling_utils.py#L531
members/contributors who may be interested in …
=> Remove insecure `torch.load` calls

CITATION.cff, README.md
Updates our citation to include Dhruv, Yiyi, Will, Steven, and myself. Discussed this with @LysandreJik internally too. 
@patil-suraj for awareness.
=> [Chore] add: fives names to citations.

src/diffusers/pipelines/animatediff/pipeline_animatediff.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video.py, src/diffusers/pipelines/free_init_utils.py, src/diffusers/pipelines/pia/pipeline_pia.py
Fixes: https://github.com/huggingface/diffusers/pull/6874#discussion_r1493756055
Also removes some of the old but unused code from FreeInit refactor.
@DN6
=> [refactor] Fix FreeInit behaviour

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py
=> diffusers#7426 fix stable diffusion xl inference on MPS when dtypes shift unexpectedly due to pytorch bugs

src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py, src/diffusers/pipelines/stable_cascade/pipeline_stable_cascade_combined.py, src/diffusers/pipelines/wuerstchen/pipeline_wuerstchen_combined.py
Combined pipelines doesn't have the device argument from the inherited DiffusionPipeline.
This causes `got an unexpected keyword argument 'device'` errors if we don't add a special case for these pipelines and locks offloading to `cuda` devices.
This PR adds device argument to `enable_model_cpu_offload` and `enable_sequential_cpu_offload` found in `Stable Cascade`, `Wuerstchen` and `Kandinsky 2.2` combined pipelines.
- [*] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [*] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)? …
=> Add device arg to offloading with combined pipelines

tests/lora/utils.py
`test_lora_fuse_nan` fails on mps due to a pytorch bug - see issue #7417. This PR skips the test on mps.
Fixes #7417
- JAX and MPS: @pcuenca
=> Skip `test_lora_fuse_nan` on mps

examples/controlnet/train_controlnet_sdxl.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
Adds MPS bugfixes to the SDXL example training scripts.
I haven't really completed this yet, I'm looking for comments on the approach, or whether it should be done at all.
On an M3 Max, I get reasonable speeds for training.
=> apple mps: training support for SDXL (ControlNet, LoRA, Dreambooth, T2I)

src/diffusers/utils/testing_utils.py, tests/pipelines/animatediff/test_animatediff.py, tests/pipelines/animatediff/test_animatediff_video2video.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_img2img.py, tests/pipelines/controlnet/test_controlnet_sdxl.py, tests/pipelines/controlnet/test_controlnet_sdxl_img2img.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models_img2img.py, tests/pipelines/pia/test_pia.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py, tests/pipelines/stable_diffusion_panorama/test_stable_diffusion_panorama.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py, tests/pipelines/test_pipelines_common.py
Currently, the fast pipeline tests take about 20 minutes to fully execute. https://github.com/huggingface/diffusers/actions/runs/8430950874/artifacts/1358187212 gives an idea. 
Below are the tests that take more than 10 seconds to run:
```bash
slowest durations
20.46s call     tests/pipelines/pia/test_pia.py::PIAPipelineFastTests::test_inference_batch_single_identical
20.17s call     tests/pipelines/animatediff/test_animatediff.py::AnimateDiffPipelineFastTests::test_inference_batch_single_identical
19.71s call     tests/pipelines/animatediff/test_animatediff.py::AnimateDiffPipelineFastTests::test_vae_slicing
19.43s call     tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py::StableDiffusionAttendAndExcitePipelineFastTests::test_karras_schedulers_shape
14.49s …
```
=> [Tests] Speed up some fast pipeline tests

src/diffusers/loaders/lora.py
Due to a typo in the merged PR #7352, an error will always be logged. Currently, the validation code expects a "uent" parameter, which is a typo for unet.
(But the unet scale dict is still handled correctly.)
Thanks @asomoza for spotting!
cc @sayakpaul
=> Quick-Fix for #7352 block-lora

src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/schedulers/test_scheduler_unipc.py
Effectively the same trick as DDIM's `set_alpha_to_one` and DPM's `final_sigma_type='zero'` where the extra concatenated sigma is simply zero instead of the prior sigma. Completely fixes the goofy residual noise, particularly with lower step counts.
1st and 2nd order UniPC without the patch
1st and 2nd order UniPC with `final_sigma_zero=True`
Third order errors out for me even on a clean `main` branch so that's fun. I'll monkey with it later...
Currently `False` by default but maybe this should be `True` like DDIM/DPM?
This could also be represented as the same `final_sigma_type='zero'|'sig_min'` that DPM uses, but I don't really see why it needs to be a string with only two options. *Personally* I find this scheme much more intuitive.
No UT right now as I didn't see anything for …
=> Add `final_sigma_zero` to UniPCMultistep

examples/community/README.md, examples/community/pipeline_stable_diffusion_xl_differential_img2img.py
Adds [Differential Diffusion](https://github.com/exx8/differential-diffusion) as a community pipeline as discussed [here](https://github.com/huggingface/diffusers/pull/7442#issuecomment-2027753744), this is the SDXL img2img version.
More information and original PR [here](https://github.com/huggingface/diffusers/pull/7442). I'll add the documentation to the README after the initials reviews.
Once this one is merged I plan to do also:
Note: It works with turbo and lighting variations, but IMO the only half good one is the lighting 8 steps, with less steps the model can't properly do the inpaint and even with 8, the inpainting isn't that good.
Fixes #7038 
Paper: https://differential-diffusion.github.io/paper.pdf
Project site: https://differential-diffusion.github.io/
Code: …
=> [Community pipeline] SDXL Differential Diffusion Img2Img Pipeline

tests/pipelines/test_pipelines_common.py
FreeU tests in the common pipeline tests expect numpy arrays when running comparisons. Some of our pipeline tests return torch tensors are as output type which is causing these tests to fail. This PR 
1. Changes the freeU tests to always set the output type to `np` so that the comparison is done properly. 
=> Fix FreeU tests

.github/workflows/nightly_tests.yml, setup.py
This PR makes the nightly tests workflow dispatchable. The idea is to manually trigger the torch nightly tests before making a release. The tests that are known to fail at the moment (https://github.com/huggingface/diffusers/issues/7334, for example) will be ignored during this check. 
For releases, @DN6 and I think it's okay to just stick to the torch tests. 
Once the PR is approved, will add a note in our setup.py about running this test.
Cc: @yiyixuxu for awareness.
=> [Release tests] make nightly workflow dispatchable.

src/diffusers/models/attention.py, src/diffusers/models/attention_processor.py, src/diffusers/models/downsampling.py, src/diffusers/models/embeddings.py, src/diffusers/models/resnet.py, src/diffusers/models/transformers/transformer_2d.py, src/diffusers/models/unets/unet_stable_cascade.py, src/diffusers/models/upsampling.py, src/diffusers/pipelines/wuerstchen/modeling_wuerstchen_common.py, src/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py
It's time. 
I know @younesbelkada will be very happy.
=> [Chore] remove class assignments for linear and conv.

tests/pipelines/animatediff/test_animatediff.py, tests/pipelines/controlnet/test_controlnet_blip_diffusion.py, tests/pipelines/controlnet/test_controlnet_inpaint_sdxl.py, tests/pipelines/kandinsky3/test_kandinsky3_img2img.py, tests/pipelines/pia/test_pia.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py, tests/pipelines/stable_diffusion_gligen_text_image/test_stable_diffusion_gligen_text_image.py, tests/pipelines/test_pipelines_common.py, tests/pipelines/text_to_video_synthesis/test_text_to_video.py, tests/pipelines/unidiffuser/test_unidiffuser.py
Follow-up of https://github.com/huggingface/diffusers/pull/7477. 
This PR targets the `test_dict_tuple_outputs_equivalent()` method we run for all pipelines. I took the top 10 time-consuming tests from the lot and decided to use static slices ONLY for them. This is because of the rest of the tests, it's under a second. So, it doesn't matter that much. 
The next PR will be similar to this but for `test_inference_batch_single_identical()`.
=> [Tests] Speed up fast pipelines part II

src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/schedulers/test_scheduler_unipc.py
As I found in #7517, UniPC with order=3 was erring on step 3 due to one of the tensors not being the correct dtype and device. This PR corrects that and updates the fp16 test to check every combination of order, solver, prediction to ensure they all work against half precision.
I verified working on both FP16 and BF16 on CUDA, and the updated test will correctly fail if you checkout to the first commit 036e33e before I fixed the `rhos_p` typings.
The test might be a bit over-comprehensive as it stands. Right now I don't think its possible for all the parameters to create incompatible tensors but in my mind by just checking everything it should catch future refactors.
Should merge cleanly on top of #7531
@yiyixuxu
=> UniPC Multistep fix tensor dtype/device on order=3

src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/schedulers/test_scheduler_unipc.py
Mostly the same strategy as DPM and Euler with the patched final alpha cumprod and simple config check UT.
No force upcast this time as BF16 + ZSNR doesn't seem to break down on this sampler. I'm assuming because it upcasts for some steps already? We could still force an upcast in `step()` and possibly remove the other individual recasts as a result but the difference is pretty small from my limited test.
Should merge cleanly on top of #7532
Demos using `dark photograph of a baby panther in the forest at night`
DPM++ 2nd order, UniPC 1st order, UniPC 2nd order on `diffusers/main`
DPM++ 2nd order, UniPC 1st order, UniPC 2nd order with this PR
BF16
BF16 w/upcast (not in PR)
@yiyixuxu
=> UniPC Multistep add `rescale_betas_zero_snr`

.github/workflows/pr_test_peft_backend.yml, .github/workflows/pr_tests.yml, .github/workflows/push_tests_fast.yml
Additionally, this PR changes the `docker-cpu` runners to a a better one.
=> [Chore] increase number of workers for the tests.

tests/models/autoencoders/test_models_vae.py, tests/models/autoencoders/test_models_vq.py, tests/models/unets/test_models_unet_1d.py, tests/models/unets/test_models_unet_2d.py, tests/models/unets/test_models_unet_2d_condition.py, tests/models/unets/test_models_unet_3d_condition.py, tests/models/unets/test_models_unet_motion.py, tests/models/unets/test_models_unet_spatiotemporal.py
In some cases, changing the number of groups is simply not possible because internally it's hard-coded. So, I haven't touched those (UNetSpatioTemporal for example).
=> [Tests] reduce block sizes of UNet and VAE tests

tests/models/test_attention_processor.py
disable test_conversion_when_using_device_map test for now
=> disable test_conversion_when_using_device_map 

src/diffusers/image_processor.py, src/diffusers/models/attention_processor.py, tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py, tests/pipelines/test_pipelines_common.py
Image masking is currently supported by passing a mask and an image for each IP Adapter in the pipeline.
This PR extends this usage by allowing multiple masks and images to be passed to a single IP Adapter. Scales must be passed accordingly.
Discussed in #7419 
=> Multi-image masking for single IP Adapter

.github/workflows/update_metadata.yml, utils/update_metadata.py
Internal discussion: https://huggingface.slack.com/archives/C02EMARJ65P/p1711968668812989.
Locally ran the `update_metadata.py` script and here's the result: https://huggingface.co/datasets/huggingface/diffusers-metadata. 
Cc: @osanseviero for awareness.
=> add utilities for updating diffusers pipeline metadata.

src/diffusers/models/transformers/transformer_2d.py
Refactors the `forward()` of `Transformers2DModel` for easier readability. 
More specifically, the PR refactors the `forward()` method of `Transformers2DModel` to have the following unified structure:
```python
def forward(self):
...
if self.is_input_continuous:
... = self._operate_on_continuous_inputs(...)
elif self.is_input_vectorized:
... = self.latent_image_embedding(...) # for vectorized inputs only this is needed.
elif self.is_input_patches:
... = self._operate_on_patched_inputs(...)
for block in self.transformer_blocks:
...
if self.is_input_continuous:
... = self._get_output_for_continuous_inputs(...)
elif self.is_input_vectorized:
output = self._get_output_for_vectorized_inputs(...)
elif self.is_input_patches:
output = self._get_output_for_patched_inputs(...)
return output
``` …
=> [Core] refactor `transformer_2d` forward logic into meaningful conditions.

src/diffusers/models/autoencoders/autoencoder_tiny.py, src/diffusers/models/autoencoders/vae.py
1. Provide other options for the upsampling function of the Tiny VAE's decoder (default is nearest), which will be used in [SDXS](https://github.com/IDKiro/sdxs).
=> add the option of upsample function for tiny vae

tests/pipelines/stable_diffusion/test_stable_diffusion.py
Reduces the model sizes in the Stable Diffusion fast tests. My plan is to have this PR as a reference and open the rest of the tests that would benefit from this to the community. Hope that makes sense. 
Cc: @yiyixuxu for visibility.
=> [Tests] reduce the model sizes in the SD fast tests

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/stable_diffusion/adapter.md, docs/source/en/using-diffusers/t2i_adapter.md
Refactors the T2I-Adapter API page to only show API reference and moves the other material into a standalone guide.
todo:
=> [docs] T2I

src/diffusers/pipelines/deepfloyd_if/pipeline_if.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_combined.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py, src/diffusers/pipelines/kandinsky3/pipeline_kandinsky3.py, src/diffusers/pipelines/kandinsky3/pipeline_kandinsky3_img2img.py
This PR cleans up the cpu_offloading code for kandinsky & IF
This should fix all cpu offload tests failure related to IF and Kandisnky, e.g  https://github.com/huggingface/diffusers/actions/runs/8594679447/job/23548137528#step:9:17
https://github.com/huggingface/diffusers/actions/runs/8594679447/job/23548137612#step:9:60
https://github.com/huggingface/diffusers/actions/runs/8594679447/job/23548137335#step:9:17
I still have a few tests related to `from_pipe` I'm fixing here https://github.com/huggingface/diffusers/pull/7564 - but they are edge cases so don't have to worry about too much for now
=> Fix cpu offload related slow tests

src/diffusers/loaders/unet.py, src/diffusers/pipelines/pipeline_utils.py
`logging.warn` and `logging.Logger.warn` are deprecated in favor of `logging.warning` and `logging.Logger.warning`, which are functionally equivalent. (https://docs.python.org/3/library/logging.html#logging.warning)
Pull Request section?
to it if that's the case.
[documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
@sayakpaul
=> fix: Replaced deprecated `logger.warn` with `logger.warning`

.github/workflows/build_docker_images.yml
Actions are failing otherwise: https://github.com/huggingface/diffusers/actions/runs/8639436027/job/23685736471
=> make docker-buildx mandatory.

.github/workflows/update_metadata.yml
In our `update_metadata.yml` workflow, we're using the token of a user that's not a part of the `huggingface` org on the Hub. So, this PR updates it with my token. 
Will merge once the CI is green.
=> fix: metadata token

setup.py, src/diffusers/dependency_versions_table.py, src/diffusers/models/modeling_utils.py, src/diffusers/pipelines/pipeline_loading_utils.py, tests/models/test_attention_processor.py
enable the `DeprecatedAttentionBlockTests` again
follow up on https://github.com/huggingface/diffusers/pull/7620
we disabled the test because of [this issue](https://github.com/huggingface/accelerate/issues/2640), which is now fixed by [this PR](https://github.com/huggingface/accelerate/pull/2641) and that's already in the latest release
=> adding back test_conversion_when_using_device_map

docs/source/en/api/pipelines/auto_pipeline.md, docs/source/en/tutorials/autopipeline.md, docs/source/en/using-diffusers/loading.md
Refactors the `from_pipe` API from the AutoPipeline tutorial to link to the [Reuse a pipeline](https://huggingface.co/docs/diffusers/main/en/using-diffusers/loading#reuse-a-pipeline) section and cleans up the AutoPipeline API doc.
=> [docs] AutoPipeline

utils/update_metadata.py
This PR:
* Fixes the JSON line ordering so the sorting is always consistent. 
* Adds a couple lines of code to check if there's any need to update the metadata on the Hub (see https://github.com/huggingface/transformers/pull/30344/).
=> [Metadat utils] fix: json lines ordering.

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py, src/diffusers/pipelines/pixart_alpha/pipeline_pixart_sigma.py
=> [PixArt] fix small nits in pixart sigma
