huggingface/diffusers

src/diffusers/models/unet.py, src/diffusers/models/unet_glide.py, src/diffusers/models/unet_ldm.py
@patil-suraj - please have a look here - I removed lots of LDM code. This seems to be ok though since all tests still pass
=> [Clean up] Clean up unused code

src/diffusers/models/resnet.py, src/diffusers/models/vae.py
Put general ResNet block into VAE (cc @patil-suraj)
=> [ResNet] Refactor resnet from VAE

src/diffusers/models/resnet.py, src/diffusers/models/unet.py, src/diffusers/models/unet_glide.py, src/diffusers/models/unet_grad_tts.py, src/diffusers/models/unet_ldm.py, src/diffusers/models/unet_sde_score_estimation.py, src/diffusers/models/vae.py
Resnet should be called Resnet2D and not just Resnet
=> Resnet => Resnet2D

examples/README.md
Helpful info for https://github.com/huggingface/diffusers/issues/125
=> Add a step about accelerate config to the examples

README.md
line 23, 24 and 25: Remove "that" because "that" is unnecessary in these three sentences.
line 33: Rewrite this sentence and make it more straightforward.
line 34: This first sentence is incomplete.
line 117: “focusses" -> "focuses"
line 118: "continuous" -> "continuous"
line 119: "consise" -> "concise"
=> fix some errors and rewrite sentences in README.md

MANIFEST.in
=> Fix manifest to include model card

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
The final result will be similar to https://github.com/huggingface/transformers/issues/new/choose or https://github.com/huggingface/huggingface_hub/issues/new/choose but simpler
=> Add issue templates for feature requests and bug reports

README.md
Since adding a package to conda-forge cannot be done from this repository, it was taken care of by the following PR.
- https://github.com/conda-forge/staged-recipes/pull/19751
This PR updates the README to add conda install instruction.
Closes #126
=> Added `diffusers` to conda-forge and updated README for installation instruction

src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py, src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
This PR fixes `accepts_eta` check in LDM pipeline.
=> [LDM pipeline] fix eta condition.

src/diffusers/__init__.py, src/diffusers/schedulers/__init__.py, src/diffusers/schedulers/scheduling_pndm.py, src/diffusers/utils/dummy_scipy_objects.py
Thanks a mile for spotting @pcuenca
=> [K-LMS Scheduler] fix import

README.md
https://github.com/CompVis/stable-diffusion
=> Match params with official Stable Diffusion lib

README.md
Using the URL for v1-3 for now.
=> Update README for 0.2.3 release

.github/workflows/test.yml, tests/test_scheduler.py
Hopefully this is useful for running tests via github workflows
=> added test workflow and fixed failing test

setup.py, src/diffusers/dependency_versions_table.py
Same issue in `transformers` for reference: https://github.com/huggingface/transformers/pull/17918
=> Pin black==22.3 to keep a stable --preview flag

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Adding this already now so that we can get them collaborators going. Mostly copy-paste from Transformers. @anton-l @patil-suraj please feel free to open a PR to change it / adapt it if you don't like it :-)
=> [Docs] Add some guides

.github/workflows/push_tests.yml, setup.py
Same strategy as in `transformers`, some dependencies can be a defaulted for tests
cc @patil-suraj @patrickvonplaten
=> Add datasets + transformers + scipy to test deps

src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
Refers to issue #287 
@anton-l would you mind checking it? Thanks!
=> [Type hint] Latent Diffusion Uncond pipeline

src/diffusers/models/unet_blocks.py
=> Fix typo in unet_blocks.py

src/diffusers/schedulers/scheduling_ddpm.py
Refers to 15, 16, and 17 of issue https://github.com/huggingface/diffusers/issues/287
@patrickvonplaten  could you check it?
Thanks :)
=> [Type Hint] DDPM schedulers

src/diffusers/models/vae.py
Based on 3, 4, 7, 10, and 11 of issue https://github.com/huggingface/diffusers/issues/287
@anton-l could you check it?
Thanks :)
=> [Type Hints] VAE models

src/diffusers/schedulers/scheduling_ddim.py
Refers to 12, 13, and 14 of issue #287 
@anton-l would you mind checking it? Thanks!
=> [Type hint] scheduling ddim

src/diffusers/schedulers/scheduling_karras_ve.py
Refers to 18, 19, and 20 of issue #287 
@patrickvonplaten would you mind checking it? Thanks!
=> [Type hint] scheduling karras ve

src/diffusers/schedulers/scheduling_karras_ve.py, src/diffusers/schedulers/scheduling_lms_discrete.py
Refers to 21, 22, and 23 of issue #287 
@patrickvonplaten would you mind checking it? Thanks!
=> [Type hint] scheduling lms discrete

src/diffusers/models/vae.py
Based on 8 of issue https://github.com/huggingface/diffusers/issues/287
@anton-l could you check it?
Thanks :)
=> [Type Hint] VAE models

docs/source/api/pipelines/latent_diffusion_uncond.mdx, src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
=> [Pipeline Docs] Unconditional Latent Diffusion

docs/source/api/logging.mdx, src/diffusers/__init__.py
=> [Docs] Logging

docs/source/api/pipelines/pndm.mdx, src/diffusers/pipelines/pndm/pipeline_pndm.py
=> added pndm docs

docs/source/optimization/mps.mdx
=> Docs: optimization / special hardware

docs/source/_toctree.yml
=> Docs: fix undefined in toctree

README.md
Same as #413 but for unconditional diffusers example.
=> Improve unconditional diffusers example

docs/source/installation.mdx
very small PR 
Based on a typo pointed out by @utsavnandi https://github.com/huggingface/diffusers/issues/293#issuecomment-1242437102
=> Docs: fix installation typo

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
=> Fix `disable_attention_slicing` in pipelines

src/diffusers/models/resnet.py
=> Remove the usage of numpy in up/down sample_2d

src/diffusers/schedulers/scheduling_ddim.py
Reverts huggingface/diffusers#456
=> Revert "adding more typehints to DDIM scheduler"

setup.py, src/diffusers/dependency_versions_table.py
Previous PR: https://github.com/huggingface/diffusers/pull/512 requires new hub version
=> [Hub] Update hub version

setup.py
Needed for the examples tests in particular, but also for fresh installs with notebooks
=> Add torchvision to training deps

src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_flax.py
=> docs: fix `Berkeley` ref

src/diffusers/pipelines/stable_diffusion/README.md
the result of running the pipeline is stored in StableDiffusionPipelineOutput.images
=> fix docs: change sample to images

examples/dreambooth/README.md, examples/dreambooth/requirements.txt
Update installation instructions
=> [dreambooth] update install section

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_onnx.py
The onnx pipeline should be numpy-based to work
cc @kashif
=> Fix onnx tensor format

examples/textual_inversion/textual_inversion.py
Hi! I added a way to save during training
=> Added script to save during textual inversion training. Issue 524

src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
=> refactor: update ldm-bert `config.json` url closes #675

src/diffusers/models/unet_2d.py, src/diffusers/models/unet_2d_condition_flax.py
=> [Docs] fix docstring for issue #709

src/diffusers/models/resnet.py, src/diffusers/models/unet_2d_condition.py
There were casting operations before, they are now gone.
=> Remove comments no longer appropriate

docs/source/training/text_inversion.mdx, examples/dreambooth/README.md, examples/dreambooth/train_dreambooth.py, examples/textual_inversion/README.md, examples/textual_inversion/textual_inversion.py, src/diffusers/pipelines/stable_diffusion/README.md
Remove `use_auth_token` from remaining examples and readme.
=> remove use_auth_token from remaining places

examples/dreambooth/train_dreambooth.py, examples/textual_inversion/textual_inversion.py, examples/unconditional_image_generation/train_unconditional.py
Fix push_to_hub calls (dreambooth + textual_inversion) based on  https://github.com/huggingface/diffusers/pull/356#discussion_r988316114
=> Fix push_to_hub for dreambooth and textual_inversion

src/diffusers/schedulers/scheduling_ddpm.py
needed to move #54 fully into a google colab
=> add sigmoid betas

examples/dreambooth/train_dreambooth.py
Not sure if this is on purpose. Don't want to ruin the fun.
=> Eventually preserve this typo? :)

examples/text_to_image/train_text_to_image.py
As discussed in https://github.com/huggingface/diffusers/pull/813#issuecomment-1276400347 and https://github.com/huggingface/diffusers/pull/813#issuecomment-1276404302. @patil-suraj, please have a look!
=> Fix fine-tuning compatibility with deepspeed

setup.py, src/diffusers/__init__.py
Patch release for: https://github.com/huggingface/diffusers/commit/effe9d66ebad017d54b47e11c79f347fa7556ecf
Version is up!
=> Release 0 5 1

examples/community/lpw_stable_diffusion.py, examples/community/lpw_stable_diffusion_onnx.py
Fix previous incorrect pad_tokens_and_weights in lpw_stable_diffusion piplines
=> [Community Pipelines] Fix pad_tokens_and_weights in lpw_stable_diffusion

src/diffusers/pipelines/ddpm/pipeline_ddpm.py
just a small typo in the comment
=> fix a small typo in pipeline_ddpm.py

examples/dreambooth/train_dreambooth.py
This PR enables specify the revision of the pretrained model
=> Add --pretrained_model_name_revision option to train_dreambooth.py

examples/text_to_image/train_text_to_image.py
remove tensor_format in the new version
=> fix a bug in the new version

examples/dreambooth/train_dreambooth.py
Make `input_args` optional in `parse_args`
Thanks a lot for the reporting this @ssotabe
=> fix dreambooth script.

examples/dreambooth/train_dreambooth.py
=> [DreamBooth] Set train mode for text encoder

examples/unconditional_image_generation/train_unconditional.py, src/diffusers/hub_utils.py
Deprecates `init_git_repo` in favor of the `huggingface_hub.Repository` workflow implemented in other training examples.
Closes #81
=> Deprecate `init_git_repo`, refactor `train_unconditional.py`

examples/unconditional_image_generation/train_unconditional.py
=> Add `--dataloader_num_workers` to the DDPM training example

docs/source/optimization/fp16.mdx
I modified speedup ratios correctly.
`speedup = original_latency / latency`
=> Fix speedup ratio in fp16.mdx

src/diffusers/models/embeddings_flax.py
updated time embedding with features from pytorch version.
=> [Flax] time embedding

examples/dreambooth/train_dreambooth_flax.py
Will fixes #1088. 
cc @patil-suraj @camenduru @patrickvonplaten
=> [Flax] Fix sample batch size DreamBooth 

examples/README.md
fix 404 errors.
https://github.com/huggingface/diffusers/tree/main/examples
=> fix 404 link in example/README.mb

src/diffusers/models/unet_2d_blocks.py
Duplicate PR as #977 because I deleted the head repository of that PR by mistake :(
=> fix the parameter naming in `self.downsamplers`

src/diffusers/pipeline_utils.py
We haven't tested it in depth, but it now works (doesn't crash).
=> Remove warning about half precision on MPS

examples/dreambooth/train_dreambooth_flax.py, examples/text_to_image/train_text_to_image_flax.py, examples/textual_inversion/textual_inversion_flax.py
Related to [comment](https://github.com/huggingface/diffusers/pull/1001#discussion_r1013984296).
cc @patil-suraj @skirsten
=> [Flax examples] Load text encoder from subfolder

src/diffusers/configuration_utils.py
=> Fix small typo

examples/dreambooth/train_dreambooth_flax.py
=> [Flax] fix extra copy pasta 🍝

examples/community/clip_guided_stable_diffusion.py
This PR adds support for `DDIMScheduler` in `CLIPGuidedStableDiffusion`
Should be merged after #1189 
Fixes #1152
=> [CLIPGuidedStableDiffusion] support DDIM scheduler

scripts/convert_ldm_original_checkpoint_to_diffusers.py
Correct diffusers layer names.
cc @patil-suraj @patrickvonplaten
=> Fix layer names convert LDM script

.github/workflows/push_tests.yml, tests/test_scheduler_flax.py
These are taken straight from docker now
=> [Tests] Adjust TPU test values

src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py, tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint_legacy.py
This PR refactors all the PyTorch Stable Diffusion pipelines in an attempt to close https://github.com/huggingface/diffusers/issues/551
=> Finalize stable diffusion refactor

src/diffusers/models/unet_2d_condition.py, src/diffusers/models/unet_2d_condition_flax.py
=> doc string args shape fix

examples/community/imagic_stable_diffusion.py, examples/community/lpw_stable_diffusion.py, examples/community/lpw_stable_diffusion_onnx.py, examples/textual_inversion/textual_inversion.py, examples/textual_inversion/textual_inversion_flax.py
Community pipelines fail because they are retrieved from `main`
=> Temporary local test for PIL_INTERPOLATION

src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
Casting latents to torch tensors to support the Euler and EulerA steps
Fixes #1249
=> [ONNX] Support Euler schedulers

examples/community/README.md
=> Update README.md: IMAGIC example code snippet misspelling

setup.py, src/diffusers/__init__.py
=> Version 0.9.0.dev0

src/diffusers/models/unet_2d_blocks.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py, src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_dual_guided.py, src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_image_variation.py, src/diffusers/pipelines/versatile_diffusion/pipeline_versatile_diffusion_text_to_image.py, tests/pipelines/altdiffusion/test_alt_diffusion.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion.py
Supports attention slicing for `attention_head_dim` defined as a list of head dims, as in Stable Diffusion 2.
Also adds tests for SD2 text2image.
=> Support SD2 attention slicing

examples/community/clip_guided_stable_diffusion.py
New transformers version requires a potentially retrieving from a dict
=> fix clip guided

scripts/convert_stable_diffusion_checkpoint_to_onnx.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py
Makes the conversion script and pipelines compatible with the changes of the past 2 days
Fixes #1407
=> Fix ONNX conversion and inference

src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_flax.py
=> added initial v-pred support to DPM-solver

src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint_legacy.py
Applies the same hotfix as in https://github.com/huggingface/diffusers/pull/1416
See the comments in https://github.com/huggingface/diffusers/pull/1416 for more details on the reasons for some rollbacks.
Fixes https://github.com/huggingface/diffusers/issues/1445
=> Hotfix for AttributeErrors in OnnxStableDiffusionInpaintPipelineLegacy

examples/unconditional_image_generation/train_unconditional_ort.py
Removes `init_git_repo, push_to_hub`
=> Replace deprecated hub utils in `train_unconditional_ort`

src/diffusers/models/attention.py
This simplifies `AttentionBlock` by always making q,k,v a 3D tensors like we do in `CrossAttention`. This way we can also leverage sliced attention and xformers attention  in this block.
=> simplyfy AttentionBlock

examples/dreambooth/README.md, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_flax.py
Added some additional docs to the README and the cli args
re: https://github.com/huggingface/diffusers/issues/1281
=> [docs] [dreambooth training] num_class_images clarification

examples/text_to_image/README.md
#1463
Just added documentation to add `training` packages.
=> Fix training docs to install datasets

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
Those were left unset when inputs are not PIL images
=> Fixed mask+masked_image in sd inpaint pipeline

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
Fixes: https://github.com/huggingface/diffusers/issues/1462#issuecomment-1335383371
=> [Stable Diffusion Inpaint] Allow tensor as input image & mask

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_upscale.py
Fixes: https://github.com/huggingface/diffusers/issues/1478
=> [Upscaling] Fix batch size

src/diffusers/models/unet_2d_condition.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
Docs for `encoder_hidden_states` were wrong. Thanks @rousseau ! 
Fixes comment here: https://github.com/huggingface/diffusers/issues/1522#issuecomment-1336142488
=> [Docs] Correct docs

examples/dreambooth/README.md
re: https://github.com/huggingface/diffusers/issues/1228
=> [docs] [dreambooth training] default accelerate config

examples/community/stable_diffusion_mega.py
=> Mega community pipeline

examples/community/lpw_stable_diffusion.py, examples/community/lpw_stable_diffusion_onnx.py
Make it compatible with Diffusers v0.10.0
Make onnx pipeline compatible with more schedulers.
Fixes #1536 #1500 #1363
=> [Community Pipeline] fix lpw_stable_diffusion

src/diffusers/models/attention.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_v_pred.py
fix upcasting attention in sliced mode and add a test.
=> fix upcast in slice attention

src/diffusers/models/unet_2d_blocks.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
=> Make cross-attention check more robust

src/diffusers/hub_utils.py
fixed #1685 - disables telemetry when DISABLE_TELEMETRY and HF_HUB_OFFLINE is set
=> Disable telemetry when DISABLE_TELEMETRY is set

examples/unconditional_image_generation/train_unconditional_ort.py
Reflects changes made to train_unconditional.py in train_unconditional_ort.py as of December 13, 2022
=> manually update train_unconditional_ort

README.md
Specify that we don't actively monitor the conda scripts
=> [Readme] Clarify package owners

src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_onnx_stable_diffusion.py, tests/pipelines/stable_diffusion/test_onnx_stable_diffusion_img2img.py
=> Fix ONNX img2img preprocessing and add fast tests coverage

src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py, tests/pipelines/latent_diffusion/test_latent_diffusion.py
Had a couple of LDM test failures on the CI, so just updated the whole suite, why not :smile:
=> Fix/update the LDM pipeline and tests

examples/unconditional_image_generation/train_unconditional.py
Add logger flag to choose between tensorboard and wandb for a minimal implementation
Removed remainder of logging code to rediscuss for future.
Hyperlinked is a commit which will show an example utilizing an extended form of the wandb logger which can log images and model checkpoints:
LINK to branch: https://github.com/ash0ts/diffusers/tree/add-wandb-unconditional-image/examples/unconditional_image_generation
Refers to this PR: https://github.com/huggingface/diffusers/pull/1245
=> [Examples] Update train_unconditional.py to include logging argument for Wandb

examples/community/imagic_stable_diffusion.py, examples/community/lpw_stable_diffusion.py, examples/community/lpw_stable_diffusion_onnx.py, setup.py, src/diffusers/__init__.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_img2img.py, src/diffusers/pipelines/ddim/pipeline_ddim.py, src/diffusers/pipelines/ddpm/pipeline_ddpm.py, src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion_superresolution.py, src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint_legacy.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py, src/diffusers/schedulers/scheduling_ddim.py, src/diffusers/schedulers/scheduling_ddim_flax.py, src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_flax.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_flax.py, tests/pipelines/ddpm/test_ddpm.py, tests/test_config.py, tests/test_scheduler.py, tests/test_scheduler_flax.py
Bumping all of the deprecations to avoid any depreaction-related issues during the holidays, when we might not be available to answer quickly
=> Bump to 0.12.0.dev0

src/diffusers/models/attention.py
Only test for xformers when you turn them on. Fix for issue #1773
=> Only test for xformers when enabling them #1773

src/diffusers/schedulers/scheduling_ddpm_flax.py
=> Fix OOM when using PyTorch with JAX installed.

examples/textual_inversion/textual_inversion.py
No hardcoded names anymore in textual inversion.
=> Remove hardcoded names from PT scripts

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
Fix inconsistencies between code and comments in the function 'preprocess'
=> fix small mistake in annotation: 32 -> 64

src/diffusers/models/attention.py
This PR fixes versatile diffusion dual guided.
=> [Versatile Diffusion] Fix cross_attention_kwargs

examples/dreambooth/train_dreambooth.py, examples/textual_inversion/textual_inversion.py
=> [examples] update loss computation

examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py
Thanks a lot @sanghyun0927 for noticing!
=> Fix typo in train_dreambooth_inpaint

examples/dreambooth/train_dreambooth.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_flax.py, examples/textual_inversion/textual_inversion.py
=> Fixes to the help for `report_to` in training scripts

src/diffusers/commands/env.py, src/diffusers/utils/__init__.py
This should help us a bit with the peculiar accelerate and xformers-related issues
=> Add accelerate and xformers versions to `diffusers-cli env`

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py
=> Fixes in comments in SD2 D2I

Makefile, docs/source/en/_toctree.yml, utils/check_doc_toc.py
`make style` now automatically sorts the schedulers and pipelines API according to alphabetic order.
=> Add automatic doc sorting

examples/research_projects/colossalai/train_dreambooth_colossalai.py
- update the API to latest colossalai == 0.2.0
=> update to latest colossalai

src/diffusers/pipelines/ddim/pipeline_ddim.py
=> allow loading ddpm models into ddim

examples/community/clip_guided_stable_diffusion.py
Fix #1896
TypeError: Size should be int or sequence. Got <class 'dict'>
=> Update CLIPGuidedStableDiffusion.feature_extractor.size to fix TypeError

examples/research_projects/colossalai/README.md
Fix several typos. Ready to merge.
=> [Docs] Update README.md

examples/test_examples.py
=> Example tests

examples/dreambooth/README.md
Minor fixes. I saw these while reviewing the LORA PR :)
=> Fix a couple typos in Dreambooth readme

scripts/convert_original_stable_diffusion_to_diffusers.py
Adds possibility to convert from safetensors.
Solves: #1928 .
=> [Conversion] Improve safetensors

examples/unconditional_image_generation/train_unconditional.py
=> [train_unconditional] fix LR scheduler init

setup.py, src/diffusers/__init__.py, src/diffusers/dependency_versions_table.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/utils/__init__.py, src/diffusers/utils/import_utils.py
=> Check k-diffusion version is at least 0.0.12

examples/community/README.md, examples/community/stable_unclip.py
related issue: https://github.com/huggingface/diffusers/issues/1808
Combine `UnCLIPPipeline` and `StableDiffusionImageVariationPipeline`, create new lightweight text2image model.
=> add community pipeline: StableUnCLIPPipeline

src/diffusers/pipelines/paint_by_example/image_encoder.py, src/diffusers/pipelines/paint_by_example/pipeline_paint_by_example.py
Fixes: https://github.com/huggingface/diffusers/issues/2026
=> [Paint by example] Fix cpu offload for paint by example

examples/dreambooth/train_dreambooth.py
documenting default random crop behavior
=> [docs] [dreambooth] note random crop

examples/text_to_image/requirements.txt
As pointed out by @jtoy in https://github.com/huggingface/diffusers/pull/1884#issuecomment-1402437565
=> Remove wandb from text_to_image requirements.txt

docs/source/en/api/pipelines/stable_diffusion/pix2pix.mdx, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
This PR updates the doc example for pix2pix.
=> [doc] update example for pix2pix

examples/dreambooth/train_dreambooth_lora.py, examples/text_to_image/train_text_to_image_lora.py
=> Add `lora` tag to the model tags

src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/utils/import_utils.py
Transformers 4.26.0 has been released which allows us to improve the version handling here
=> Improve transformers versions handling

src/diffusers/models/cross_attention.py
re: https://github.com/huggingface/diffusers/issues/1891
I ran the unCLIP integration tests as well and verified they still passed. Thanks for the catch @Birch-san!
=> fuse attention mask

src/diffusers/training_utils.py
Possible typo introduced in 7c82a16fc14840429566aec40eb9e65aa57005fd
=> fix typo in EMAModel's load_state_dict()

examples/text_to_image/README.md
=> [examples] Fix CLI argument in the launch script command for text2image with LoRA

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/kerascv.mdx
As internally [discussed](https://huggingface.slack.com/archives/C03UQJENJTV/p1674886674724979).
=> add: guide on kerascv conversion tool.

docs/source/en/optimization/xformers.mdx
=> Update xFormers docs

docs/source/en/using-diffusers/schedulers.mdx
=> Docs: short section on changing the scheduler in Flax

docs/source/en/conceptual/philosophy.mdx
Internal discussion: https://huggingface.slack.com/archives/C03UQJENJTV/p1675360217450969?thread_ts=1675357538.372939&cid=C03UQJENJTV
=> removes `~`s in favor of full-fledged links.

examples/dreambooth/train_dreambooth_lora.py, examples/text_to_image/train_text_to_image_lora.py
Fixes: https://github.com/huggingface/diffusers/issues/2132
=> [LoRA] Make sure validation works in multi GPU setup

src/diffusers/pipelines/pipeline_utils.py
=> Show error when loading safety_checker `from_flax`

examples/research_projects/colossalai/train_dreambooth_colossalai.py
- fix #2221 for suit colossalai lastest version
=> fix distributed init twice

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
=> Fix typo in load_pipeline_from_original_stable_diffusion_ckpt() method

tests/pipelines/versatile_diffusion/test_versatile_diffusion_dual_guided.py, tests/pipelines/versatile_diffusion/test_versatile_diffusion_image_variation.py, tests/pipelines/versatile_diffusion/test_versatile_diffusion_mega.py
Fix versatile diffusion tests by moving test image to internal folders. Official repo has been refactored and official image has been moved out
=> [Versatile Diffusion] Fix tests

tests/pipelines/unclip/test_unclip_image_variation.py
we re-uploaded weights under kakaobrain repo
=> karlo image variation use kakaobrain upload

examples/dreambooth/train_dreambooth.py, examples/test_examples.py
re: https://github.com/huggingface/diffusers/issues/2332
Added test to run dreambooth with checkpointing, resuming training from checkpoint, and running inference from checkpoint.
Also updated cli help message to point to docs about how to run inference from checkpoint
=> dreambooth checkpointing tests and docs

src/diffusers/utils/__init__.py, src/diffusers/utils/testing_utils.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py, tests/pipelines/unclip/test_unclip.py, tests/pipelines/unclip/test_unclip_image_variation.py
=> [Tests] Add MPS skip decorator

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py, examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py, examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py, examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, examples/unconditional_image_generation/train_unconditional.py
checkpointing_steps_total_limit was a bad name for the cli arg since it implies it's a total limit for the number of checkpoint steps instead of the number of checkpoints. Sorry for noticing after merge
Fast follow of -> https://github.com/huggingface/diffusers/pull/2367
=> checkpointing_steps_total_limit->checkpoints_total_limit

examples/community/checkpoint_merger.py
Not sure how this was supposed to work before but I needed to make this fix for it to find the 3rd file
=> Fix 3-way merging with the checkpoint_merger community pipeline

examples/test_examples.py, examples/text_to_image/train_text_to_image.py
Fix https://github.com/huggingface/diffusers/issues/2312 in train_text_to_image script
Also added tests for both ema and not ema checkpointing
=> train_text_to_image EMAModel saving

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py
Reverts huggingface/diffusers#2383
=> Revert "[Pix2Pix0] Add utility function to get edit vector"

docs/source/en/api/pipelines/stable_diffusion/pix2pix_zero.mdx
To accompany: https://github.com/huggingface/diffusers/pull/2397
=> add: inversion to pix2pix zero docs.

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_flax.py, examples/dreambooth/train_dreambooth_lora.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_flax.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, examples/textual_inversion/textual_inversion_flax.py, examples/unconditional_image_generation/train_unconditional.py, setup.py, src/diffusers/__init__.py
This reverts commit 024c4376fb19caa85275c038f071b6e1446a5cad.
=> Revert "Release: v0.13.0"

docs/source/en/optimization/torch2.0.mdx, src/diffusers/models/cross_attention.py
I noticed this when adapting the code for the benchmark 😅
=> Fix typo in AttnProcessor2_0 symbol

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py
Add warning message for xformers version 0.0.16 to training scripts
re: https://github.com/huggingface/diffusers/issues/2324
=> add xformers 0.0.16 warning message

examples/unconditional_image_generation/train_unconditional.py
Fixes #2468 (tensorboard logging fails on `accelerate@main`. Reference: https://github.com/huggingface/accelerate/pull/1109
In addition, I think we should install `accelerate` from pip in the CI environment, we can do that in a separate PR.
=> Fix test `train_unconditional`

docs/source/en/using-diffusers/controlling_generation.mdx
Added MultiDiffusion into the controlling generation doc.
@sayakpaul
=> add MultiDiffusion to controlling generation

.github/workflows/pr_tests.yml, .github/workflows/push_tests.yml, .github/workflows/push_tests_fast.yml
I'm disabling the ONNX tests for now as they are failing and I don't think anybody has time to look into it soon.
cc @anton-l @echarlaix
=> Disable ONNX tests

src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/test_pipeline_utils.py
documented, tested, and refactored is_safetensors_compatible
This is my understanding of the logic from reading the function, please double check it!
=> is_safetensors_compatible refactor

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fix error when converting stable diffusion 768 checkpoint to diffusers (#1979)
=> Fix convert SD to diffusers error (#1979)

docs/source/en/api/pipelines/overview.mdx
Add missing Open In Colab svg for controlnet
=> Fix: controlnet docs format

examples/text_to_image/train_text_to_image_flax.py
=> Support revision in Flax text-to-image training

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/controlling_generation.mdx, docs/source/en/using-diffusers/weighted_prompts.mdx, setup.py, src/diffusers/dependency_versions_table.py, src/diffusers/utils/import_utils.py, src/diffusers/utils/testing_utils.py, tests/test_pipelines.py
This PR adds a test and docs to use weight prompting with diffusers and the compel library. 
Thanks a lot for making this library @damian0815 and for merging the PRs so quickly.
=> [Docs] Weight prompting using compel

.github/workflows/pr_quality.yml
re: https://github.com/huggingface/diffusers/issues/2589
example of failed run: https://github.com/huggingface/diffusers/actions/runs/4357407523/jobs/7616683553
=> add deps table check updated to ci

.github/workflows/build_documentation.yml, docs/source/_config.py
This PR adds functionality for building a Colab notebook from Markdown :)
=> [docs] Build notebooks from Markdown

examples/research_projects/lora/README.md, examples/research_projects/lora/requirements.txt, examples/research_projects/lora/train_text_to_image_lora.py
This is from https://github.com/huggingface/diffusers/pull/2479, move into `research_project`. @patrickvonplaten
=> Support LoRA for text encoder

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
`load_pipeline_from_original_stable_diffusion_ckpt` fails on my system (arch linux) because it is unable to find the download config file. it also unnecessarily persists the file to disk and re-loads from disk for no apparent reason.
=> fix: un-existing tmp config file in linux, avoid unnecessary disk IO

scripts/convert_original_controlnet_to_diffusers.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
re: https://github.com/huggingface/diffusers/issues/2581
=> controlnet sd 2.1 checkpoint conversions

src/diffusers/pipelines/pipeline_utils.py, tests/test_pipelines.py
We don't need the send_telemetry after all.
=> [Pipeline loading] Remove send_telemetry

tests/pipelines/stable_diffusion/test_stable_diffusion_controlnet.py
=> controlnet integration tests num_inference_steps=3

docs/source/en/using-diffusers/inpaint.mdx
fix https://github.com/huggingface/diffusers/issues/2689
=> fix image link in inpaint doc

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_model_editing.py
Added documentation for StableDiffusionModelEditingPipeline's edit_model method.
=> StableDiffusionModelEditingPipeline documentation

tests/pipelines/stable_diffusion/test_onnx_stable_diffusion_img2img.py
updated failing onnx slow cuda test
=> updated onnx pndm test

CONTRIBUTING.md, docs/source/en/conceptual/contribution.mdx
=> [Docs] Correct phrasing

tests/models/test_models_unet_3d_condition.py
This speeds up the Unet3D tests and hopefully also fixes the `nan` issue: https://github.com/huggingface/diffusers/actions/runs/4574686731/jobs/8076605716
=> [Tests] Speed up test

examples/controlnet/train_controlnet.py, examples/controlnet/train_controlnet_flax.py
fix https://github.com/huggingface/diffusers/issues/2772
=> allow use custom local dataset for controlnet training scripts 

examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py
https://github.com/huggingface/diffusers/issues/2444
@PatrickSchrML
=> The variable name has been updated.

docs/source/en/api/pipelines/alt_diffusion.mdx, docs/source/en/api/pipelines/spectrogram_diffusion.mdx, docs/source/en/api/pipelines/stable_diffusion_safe.mdx, docs/source/en/api/pipelines/versatile_diffusion.mdx
Managing API Pipelines path link and current Using Diffusers path.
=> docs: Link Navigation Path API Pipelines

src/diffusers/schedulers/scheduling_ddim.py, src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/schedulers/test_scheduler_dpm_multi.py
=> dynamic threshold sampling bug fixes and docs

src/diffusers/schedulers/scheduling_ddpm.py
=> ddpm scheduler variance fixes

src/diffusers/models/attention_processor.py
=> add missing AttnProcessor2_0 to AttentionProcessor union

examples/controlnet/requirements.txt, examples/dreambooth/requirements.txt, examples/instruct_pix2pix/requirements.txt, examples/research_projects/dreambooth_inpaint/requirements.txt, examples/research_projects/intel_opts/textual_inversion/requirements.txt, examples/research_projects/lora/requirements.txt, examples/research_projects/mulit_token_textual_inversion/requirements.txt, examples/research_projects/multi_subject_dreambooth/requirements.txt, examples/research_projects/onnxruntime/text_to_image/requirements.txt, examples/research_projects/onnxruntime/textual_inversion/requirements.txt, examples/research_projects/onnxruntime/unconditional_image_generation/requirements.txt, examples/text_to_image/requirements.txt, examples/textual_inversion/requirements.txt, examples/unconditional_image_generation/requirements.txt
re: https://github.com/huggingface/diffusers/issues/2571
This class was introduced in accelerate 0.16.0
=> accelerate min version for ProjectConfiguration import

src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion_controlnet.py
remove `from_pt` in flax controlnet pipeline doc string example
=> doc string example remove from_pt

src/diffusers/pipelines/pipeline_utils.py
Make sure deprecation warning is correctly thrown. Fixes #3085
=> Throw deprecation warning for return_cached_folder

examples/text_to_image/train_text_to_image_flax.py
https://github.com/huggingface/diffusers/issues/2957
=> remvoe one line as requested by gc team 

docs/source/en/using-diffusers/reproducibility.mdx
Fixes #3061 with an update on how to enable deterministic algorithms on PyTorch for reproducibility.
=> [docs] Deterministic algorithms

docs/source/en/training/custom_diffusion.mdx, src/diffusers/loaders.py, tests/models/test_lora_layers.py
=> Update custom_diffusion.mdx to credit the author

examples/dreambooth/train_dreambooth_lora.py
=> Fix bug in train_dreambooth_lora

examples/community/lpw_stable_diffusion.py
Adapt to the latest version of diffusers and fixes #3008
=> [Community Pipelines] Update lpw_stable_diffusion pipeline

examples/community/lpw_stable_diffusion.py
Reverts huggingface/diffusers#3197
=> Revert "[Community Pipelines] Update lpw_stable_diffusion pipeline"

examples/controlnet/train_controlnet.py
Essentially copied @yiyixuxu's implementation from the Flax training script.
Addresses #3115.
=> Write model card in controlnet training script

docs/source/en/api/pipelines/repaint.mdx
update interface in example to accommodate to #1701
=> [docs] Update interface in repaint.mdx

examples/community/lpw_stable_diffusion.py
Reverts huggingface/diffusers#3201
=> Revert "Revert "[Community Pipelines] Update lpw_stable_diffusion pipeline""

docs/source/zh/_toctree.yml, docs/source/zh/index.mdx, docs/source/zh/installation.mdx
Chinese docs translated from the newest English docs, also fix some typo.
=> [Docs]zh translated docs update

docs/source/en/using-diffusers/write_own_pipeline.mdx
The tutorial has a typo in the code example.
=> Typo in tutorial

.github/workflows/build_documentation.yml
@yiyixuxu @stevhliu see: https://huggingface.slack.com/archives/C04F8N7FQNL/p1683052702080589
=> Correct doc build for patch releases

examples/text_to_image/train_text_to_image.py
I made the issue [here](https://github.com/huggingface/diffusers/issues/3293)
=> Added input pretubation

docs/source/en/using-diffusers/inpaint.mdx
=> Inpainting: typo in docs

docs/source/en/stable_diffusion.mdx
Fix typo in last code block. Correct "prommpts" to "prompt"
=> [Docs] Fix stable_diffusion.mdx typo

src/diffusers/pipelines/pipeline_utils.py
Small fix as wrong error message is displayed for this error: https://github.com/huggingface/diffusers/issues/3403
=> fix warning message pipeline loading

examples/dreambooth/train_dreambooth_lora.py
Python's `try and except` logic is a better fit here in my opinion so that we can make the script more robust to prevent weird failures such as the following: https://github.com/huggingface/diffusers/issues/3454
=> Make dreambooth lora more robust to orig unet

tests/models/test_models_vae.py
I was getting an error here locally when running tests.
=> parameterize pass single args through tuple

src/diffusers/models/unet_2d_blocks.py
The Kandinsky PR broke the slow test for the vq model, this PR fixes that
=> fix broken change for vq pipeline

examples/dreambooth/train_dreambooth.py
Convert attention mask to torch tensor to fix attention mask bug
=> fix dreambooth attention mask

src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py
re: https://github.com/huggingface/diffusers/issues/3391
=> [IF super res] correctly normalize PIL input

docs/source/en/tutorials/basic_training.mdx
update the broken links for training folder doc
=> [docs] update the broken links

src/diffusers/models/attention_processor.py
=> remove print statements from attention processor.

examples/community/ mixture.py, examples/community/README.md
https://github.com/huggingface/diffusers/issues/3583
=> [Community] Support StableDiffusionTilingPipeline  

examples/community/README.md, examples/community/stable_diffusion_controlnet_reference.py, examples/community/stable_diffusion_reference.py
・add tricks in README based on https://github.com/huggingface/diffusers/issues/3566
・minor fix for reference adain
=> [Community, Enhancement] Add reference tricks in README

docs/source/en/training/instructpix2pix.mdx, examples/instruct_pix2pix/README.md
FYI @patrickvonplaten @stevhliu.
=> [Docs] include the instruction-tuning blog link in the InstructPix2Pix docs

examples/community/README.md, examples/community/mixture_tiling.py
@patrickvonplaten , @sayakpaul
=> [Community Doc] Updated the filename and readme file.

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py
Unwrap model so that script can run in multi-GPU env: https://github.com/huggingface/diffusers/issues/3651
Fixes: https://github.com/huggingface/diffusers/issues/3651
cc @williamberman @sayakpaul
=> Correct multi gpu dreambooth

src/diffusers/loaders.py
=> Fix from_ckpt not working properly on windows

src/diffusers/utils/dynamic_modules_utils.py
Inspired by https://stackoverflow.com/questions/12255554/sort-versions-in-python . Solves: https://github.com/huggingface/diffusers/issues/3703
=> Fix custom releases

examples/controlnet/train_controlnet.py, examples/controlnet/train_controlnet_flax.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_flax.py, examples/dreambooth/train_dreambooth_lora.py, examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_flax.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, examples/textual_inversion/textual_inversion_flax.py, examples/unconditional_image_generation/train_unconditional.py, setup.py, src/diffusers/__init__.py, src/diffusers/loaders.py, src/diffusers/models/cross_attention.py, src/diffusers/pipelines/pipeline_utils.py, src/diffusers/utils/hub_utils.py, tests/pipelines/test_pipelines.py
Post release. Bump many deprecations because we're not there yet and remove those that can be removed.
=> Post 0.17.0 release

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_k_diffusion.py
=> Added LoRA loading to `StableDiffusionKDiffusionPipeline`

examples/text_to_image/README.md
re: https://github.com/huggingface/diffusers/issues/3694
=> [train text to image] add note to loading from checkpoint

tests/pipelines/audio_diffusion/test_audio_diffusion.py
Fix broken audio_diffusion tests (see [PR #3841](https://github.com/huggingface/diffusers/pull/3841))
=> fix audio_diffusion tests

docs/source/en/using-diffusers/write_own_pipeline.mdx
This PR fixed the broken document address in `write_own_pipline.mdx` file. And it was already checked locally by using Huggingface doc-builder. And v0.17.x and v0.16.x version of document has the same issue too.
=> fix/docs: Fix the broken doc links

docs/source/en/tutorials/basic_training.mdx
Same issue with https://github.com/huggingface/accelerate/issues/1559 in the basic training tutorial. So, we need to update the parameter to the `project_dir`.
=> fix/doc-code: Updating to the latest version parameters

docs/source/en/stable_diffusion.mdx
=> fix/doc: no import torch issue

tests/pipelines/test_pipelines_common.py
=> Fix failing np tests

docs/source/en/api/pipelines/audio_diffusion.mdx
=> Fix code snippet for Audio Diffusion

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, tests/pipelines/test_pipelines_common.py, tests/pipelines/text_to_video/test_text_to_video.py
This PR fixes some slow tests. cc @pcuenca 
=> [Tests] Fix some slow tests

src/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py
=> Minor nits to Dance DIffusion

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
Fix SD-XL seq offload by making text_encoder optional for img2img
=> [SDXL] Fix all sequential offload

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
Forgot this one in #4019, sorry.
cc @patrickvonplaten @williamberman
=> Remove remaining `not` in upscale pipeline

CONTRIBUTING.md
=> Fixed wrong link in CONTRIBUTING.md

.github/workflows/build_documentation.yml
Fixes typo in https://huggingface.co/docs/diffusers/api/pipelines/diffedit
```python
import torch
from diffusers import DDIMScheduler, DDIMInverseScheduler, StableDiffusionPix2PixZeroPipeline
sd_model_ckpt = "stabilityai/stable-diffusion-2-1"
pipeline = StableDiffusionDiffEditPipeline.from_pretrained(
sd_model_ckpt,
safety_checker=None,
)
pipeline.scheduler = DDIMScheduler.from_config(pipeline.scheduler.config)
pipeline.inverse_scheduler = DDIMInverseScheduler.from_config(pipeline.scheduler.config)
pipeline.enable_model_cpu_offload()
pipeline.enable_vae_slicing()
generator = torch.manual_seed(0)
```
The import pipeline was wrong. 
```python
import torch
from diffusers import DDIMScheduler, DDIMInverseScheduler, StableDiffusionDiffEditPipeline
sd_model_ckpt = …
```
=> Fix diffedit doc typo

src/diffusers/pipelines/kandinsky/pipeline_kandinsky_prior.py
Fixed pipeline parameter descriptions.
None
=> Fixed pipeline parameter descriptions.

examples/controlnet/train_controlnet.py, examples/controlnet/train_controlnet_flax.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_flax.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_flax.py, examples/text_to_image/train_text_to_image_lora.py, examples/textual_inversion/textual_inversion.py, examples/textual_inversion/textual_inversion_flax.py, examples/unconditional_image_generation/train_unconditional.py, setup.py, src/diffusers/__init__.py
Move "main" branch to 0.19.0dev0.
=> move to 0.19.0dev

src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_img2img.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_inpaint.py, tests/pipelines/kandinsky/test_kandinsky.py, tests/pipelines/kandinsky/test_kandinsky_img2img.py, tests/pipelines/kandinsky/test_kandinsky_inpaint.py
Makes sure kandinsky models can be correctly offloaded. Thanks for the find @vladmandic
=> Fix kandinsky remove safety

README.md
=> add kandinsky to readme table

examples/dreambooth/requirements_sdxl.txt
=> fix requirement in SDXL

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.mdx
Internal discussions 
* https://huggingface.slack.com/archives/C041M7M98JV/p1689173068371059
* https://huggingface.slack.com/archives/C041M7M98JV/p1689173143139949
=> fix: minor things in the SDXL docs.

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.mdx, examples/dreambooth/requirements_sdxl.txt, setup.py, src/diffusers/dependency_versions_table.py, src/diffusers/utils/import_utils.py
Make sure all wordings and requirements have correct version: https://pypi.org/project/invisible-watermark/
=> [Invisible watermark] Correct version

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
=> [Stable Diffusion Inpaint ]Fix dtype inpaint 

src/diffusers/loaders.py
Fixes: https://github.com/huggingface/diffusers/issues/3718
=> [From ckpt] replace with os path join

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Make sure that controlnet is not set to True accidentally
=> [From single file] Make sure that controlnet stays False for from_single_file

examples/controlnet/train_controlnet_sdxl.py
Stable Diffusion Controlnet Pipeline has no safety checker
=> [ControlNet Training] Remove safety from controlnet

examples/dreambooth/README.md
Fixes a minor typo in the dreambooth README.md
=> docs: Typo in dreambooth example README.md

src/diffusers/loaders.py
Was just reading the code and thought this behavior was inconsistent.
@sayakpaul 
@williamberman
=> [fix] `network_alpha` when loading unet lora from old format

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py
Fixes #4236
Thanks for finding this quickly @abhishekkrthakur and @sayakpaul
=> [SDXL] Fix sd xl encode prompt

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, tests/pipelines/controlnet/test_controlnet_sdxl.py
Align SD-XL Controlnet more with original SD-XL .
cc @sayakpaul
=> [SD-XL] Fix sdxl controlnet inference

examples/textual_inversion/README.md
Adds a missing `import torch` to the example textual_inversion inference example.
=> docs: Add missing import statement in textual_inversion inference example

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py
re: https://github.com/huggingface/diffusers/issues/3808
=> do not pass list to accelerator.init_trackers

examples/dreambooth/README_sdxl.md
=> Update README_sdxl.md to change the note on default hyperparameters

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.mdx
Fixes the broken images in #4264
=> [docs] Fix image in SDXL docs

examples/dreambooth/train_dreambooth_lora_sdxl.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
Primarily fixes https://github.com/huggingface/diffusers/issues/4256.
=> [SDXL DreamBooth LoRA] multiple fixes

src/diffusers/loaders.py, src/diffusers/pipelines/alt_diffusion/__init__.py, src/diffusers/pipelines/controlnet/__init__.py, src/diffusers/pipelines/kandinsky/__init__.py, src/diffusers/pipelines/kandinsky2_2/__init__.py, src/diffusers/pipelines/latent_diffusion/__init__.py, src/diffusers/pipelines/paint_by_example/__init__.py, src/diffusers/pipelines/semantic_stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_safe/__init__.py, src/diffusers/pipelines/stable_diffusion_xl/__init__.py, src/diffusers/pipelines/vq_diffusion/__init__.py
Fixes: https://github.com/huggingface/diffusers/issues/4265
=> Fix all missing optional import statements from pipeline folders

docs/source/en/api/pipelines/auto_pipeline.md, docs/source/en/api/pipelines/kandinsky.md, docs/source/en/api/pipelines/kandinsky_v22.md
update the kandinsky doc to
1.  include introduction of the end-to-end pipelines
2.  breaking change on mask format for inpainting pipeline
outlined here: 
https://github.com/huggingface/diffusers/issues/4291
=> update Kandinsky doc

examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py
=> fix validation option for dreambooth training example

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
Removes duplicate lines which I believe is excessive and was introduced by accident in one of the previous PRs (#4156).
- Pipelines:  @patrickvonplaten and @sayakpaul
- Authors of the previous PR #4156 : @apolinario, @patrickvonplaten, @sayakpaul
=> Clean up duplicate lines in encode_prompt

tests/pipelines/test_pipelines_common.py
fix this issue:
https://github.com/huggingface/diffusers/issues/3906
=> fix test_float16_inference

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py
Fixes https://github.com/huggingface/diffusers/issues/4376.
Created a [separate thread](https://github.com/huggingface/diffusers/issues/4405) to see if the community will be interested to contribute it. Or, we will do it.
As pointed out in https://github.com/huggingface/diffusers/issues/4376#issuecomment-1659259847, SDXL doesn't actually have textual inversion support yet.
=> remove mentions of textual inversion from sdxl.

tests/pipelines/altdiffusion/test_alt_diffusion.py, tests/pipelines/altdiffusion/test_alt_diffusion_img2img.py, tests/pipelines/audio_diffusion/test_audio_diffusion.py, tests/pipelines/consistency_models/test_consistency_models.py, tests/pipelines/dance_diffusion/test_dance_diffusion.py, tests/pipelines/dit/test_dit.py, tests/pipelines/karras_ve/test_karras_ve.py, tests/pipelines/paint_by_example/test_paint_by_example.py, tests/pipelines/pndm/test_pndm.py, tests/pipelines/score_sde_ve/test_score_sde_ve.py, tests/pipelines/spectrogram_diffusion/test_spectrogram_diffusion.py, tests/pipelines/versatile_diffusion/test_versatile_diffusion_image_variation.py, tests/pipelines/vq_diffusion/test_vq_diffusion.py
Moves certain pipelines out of slow tests to nightly tests based on this list
https://github.com/huggingface/diffusers/pull/4431#issuecomment-1662018064
=> move tests to nightly

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
Fix the typo that causes `omegaconf.errors.ConfigAttributeError: Missing key parms`
=> Fix bug caused by typo

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py
Delete one duplicated line which was introduced by accident in one of previous PRs(https://github.com/huggingface/diffusers/pull/3770), I believe the variable has been declared repeatedly.
=> Delete the duplicate code for the contolnet img 2 img

src/diffusers/pipelines/kandinsky/pipeline_kandinsky_combined.py
This fix the code quality test failure on main that's caused by a PR I just merged in
=> fix-format

examples/community/README.md, examples/community/stable_diffusion_tensorrt_inpaint.py
Fixes in README for the TensorRT Inpainting community pipeline
- [x ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
=> TensorRT Inpaint pipeline: minor fixes

tests/models/test_lora_layers.py
Hopefully, we will sleep a little better at night. 
~[DON'T merge yet].~
=> [Tests] Adds integration tests for SDXL LoRAs

examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py
Add a data_dir parameter to the load_dataset method. For the local huggingface dataset, sometimes someone will pass in the relative path using data_dir to implement "_generate_examples".
For example in my dataset
```python
def _generate_examples(self):
data_path = os.path.join(self.config.data_dir, "data")
for label in os.listdir(data_path):
```
Training examples: @sayakpaul and @patrickvonplaten
=> Add a data_dir parameter to the load_dataset method.

docs/source/en/training/lora.md
=> Update lora.md to clarify SDXL support 

examples/dreambooth/train_dreambooth_lora_sdxl.py
This PR makes sure the training script also works for  batch size > 1.
Without this fix, the batch size of prompt embeds keeps getting bigger at every iteration.
=> [SDXL LoRA] fix batch size lora

examples/dreambooth/train_dreambooth_lora_sdxl.py
=> move pipeline only when running validation

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_combined.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_controlnet_img2img.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth_img2img.py
=> Fix misc typos

examples/community/stable_diffusion_reference.py
Fix for issue in the `StableDiffusionReferencePipeline`
#4306
=> fix indexing issue in sd reference pipeline

setup.py, src/diffusers/dependency_versions_table.py
Latest version of `ruff` breaks some code quality checks. This PR pins the `ruff` so that QC tests pass. 
=> pin ruff version for quality checks

scripts/convert_original_controlnet_to_diffusers.py
Fixes # 
fix the typo error: contrlnet -> controlnet.
=> fix some typo error

docs/source/en/optimization/fp16.md, docs/source/en/optimization/torch2.0.md, docs/source/en/quicktour.md, docs/source/en/stable_diffusion.md, docs/source/en/training/adapt_a_model.md, docs/source/en/training/controlnet.md, docs/source/en/training/custom_diffusion.md, docs/source/en/training/distributed_inference.md, docs/source/en/training/dreambooth.md, docs/source/en/training/instructpix2pix.md, docs/source/en/training/lora.md, docs/source/en/training/text2image.md, docs/source/en/training/text_inversion.md, docs/source/en/using-diffusers/conditional_image_generation.md, docs/source/en/using-diffusers/contribute_pipeline.md, docs/source/en/using-diffusers/control_brightness.md, docs/source/en/using-diffusers/custom_pipeline_examples.md, docs/source/en/using-diffusers/custom_pipeline_overview.md, docs/source/en/using-diffusers/depth2img.md, docs/source/en/using-diffusers/img2img.md, docs/source/en/using-diffusers/inpaint.md, docs/source/en/using-diffusers/loading.md, docs/source/en/using-diffusers/other-formats.md, docs/source/en/using-diffusers/reproducibility.md, docs/source/en/using-diffusers/reusing_seeds.md, docs/source/en/using-diffusers/schedulers.md, docs/source/en/using-diffusers/textual_inversion_inference.md, docs/source/en/using-diffusers/unconditional_image_generation.md, docs/source/en/using-diffusers/using_safetensors.md, docs/source/en/using-diffusers/write_own_pipeline.md
Based on this internal Slack [discussion](https://huggingface.slack.com/archives/C03HBN1C8CW/p1689947608968689), I think it'd be nice to update existing code samples in the docs with the `use_safetensors=True` flag.
=> [docs] Add safetensors flag

examples/text_to_image/train_text_to_image_lora_sdxl.py
Fixes: https://github.com/huggingface/diffusers/issues/4529#
=> [Examples] fix: network_alpha -> network_alphas

docs/source/en/api/utilities.md, docs/source/en/stable_diffusion.md, docs/source/en/tutorials/basic_training.md, docs/source/en/using-diffusers/other-formats.md, docs/source/en/using-diffusers/stable_diffusion_jax_how_to.md, docs/source/en/using-diffusers/textual_inversion_inference.md, examples/controlnet/train_controlnet_flax.py, examples/controlnet/train_controlnet_sdxl.py, examples/research_projects/intel_opts/textual_inversion_dfq/textual_inversion.py, examples/text_to_image/train_text_to_image.py, src/diffusers/pipelines/controlnet/pipeline_flax_controlnet.py, src/diffusers/utils/__init__.py, src/diffusers/utils/pil_utils.py
=> [Utility] adds an image grid utility

examples/text_to_image/train_text_to_image_lora_sdxl.py
Removed a duplicate assignment operation, possibly due to a clerical error in sdxl finetune example.
=> An invalid clerical error in sdxl finetune

src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/schedulers/test_scheduler_unipc.py
Fixes an exception when using the unipc scheduler with use_karras_sigmas=True
Fixes #4580
Core library:
- Schedulers: @williamberman and @patrickvonplaten
=> Fix unipc use_karras_sigmas exception - fixes huggingface/diffusers#4580

examples/research_projects/controlnet/train_controlnet_webdataset.py
This PR adds `train_controlnet_webdataset.py` script in `research_projects`. This is the script that was used for training SDXL canny and depth ControlNet models.
=> [research_projects] SDXL controlnet script

docs/source/en/_toctree.yml, docs/source/en/api/models/overview.md, docs/source/en/using-diffusers/push_to_hub.md, examples/research_projects/controlnet/train_controlnet_webdataset.py, src/diffusers/utils/hub_utils.py
This PR adds a short guide on using `push_to_hub` for models, schedulers, and pipelines.
=> [docs] PushToHubMixin

docs/source/en/training/controlnet.md
=> [Docs] Fix docs controlnet missing /Tip

docs/source/ko/training/dreambooth.md
=> Fix all docs

docs/source/en/api/pipelines/audioldm2.md, src/diffusers/pipelines/audioldm2/modeling_audioldm2.py, src/diffusers/pipelines/audioldm2/pipeline_audioldm2.py
Doc fixes:
1. Fix links to AudioLDM2 UNet / Projection model classes
2. Update checkpoint info with more details
3. Only use one end-to-end example (as recommended by @sayakpaul)
=> [AudioLDM2] Doc fixes

examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/test_examples.py
Similar to https://github.com/huggingface/diffusers/pull/4632
=> [Examples] fix sdxl dreambooth lora checkpointing.

examples/community/clip_guided_images_mixing_stable_diffusion.py
=> fix bug of progress bar in clip guided images mixing

docs/source/en/conceptual/evaluation.md
This PR fixes broken link of CLIP documentation used in evaluation documentation.
@sayakpaul
=> Fixed broken link of CLIP doc in evaluation doc

examples/dreambooth/train_dreambooth_lora.py
re: https://github.com/huggingface/diffusers/issues/4753
=> instance_prompt->class_prompt

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py
Fixes #https://github.com/huggingface/diffusers/issues/4160 .
=> [SDXL] Add docs about forcing passed embeddings to be 0

src/diffusers/loaders.py
Internal discussion: https://huggingface.slack.com/archives/C04DBJ0HLH1/p1692972160827609
=> [Tests] Tighten up LoRA loading relaxation 

src/diffusers/image_processor.py, tests/others/test_image_processor.py
@patrickvonplaten @sayakpaul @yiyixuxu 
Fixed https://github.com/huggingface/diffusers/issues/4816
=> VaeImageProcessor: Allow image resizing also for torch and numpy inputs

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md
=> Fix link from API to using-diffusers

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py
This PR fix https://github.com/huggingface/diffusers/issues/4835
=> fix a bug in sdxl-controlnet-img2img when using MultiControlNetModel

src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
This PR adds the `adapter_conditioning_factor` argument to `StableDiffusionXLAdapterPipeline`. This argument controls the fraction of initial timestamps for which the adapter should be applied.
=> [StableDiffusionXLAdapterPipeline] add adapter_conditioning_factor

src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py
allow negative micro conds in  `StableDiffusionXLAdapterPipeline`
=> [StableDiffusionXLAdapterPipeline] allow negative micro conds

examples/t2i_adapter/train_t2i_adapter_sdxl.py, examples/test_examples.py
Closes https://github.com/huggingface/diffusers/issues/4945.
=> [Tests] add: tests for t2i adapter training.

.github/workflows/pr_tests.yml, .github/workflows/push_tests.yml, .github/workflows/push_tests_mps.yml, src/diffusers/loaders.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py, tests/models/test_lora_layers.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py
follow up from: https://github.com/huggingface/diffusers/pull/4927
=> Revert revert and install accelerate main

src/diffusers/utils/__init__.py, src/diffusers/utils/import_utils.py, utils/check_repo.py
Diffusers does not have Tensorflow
=> [Core] Remove TF import checks

src/diffusers/__init__.py
Lazy import accidentally adds GLIGEN pipeline twice to the import structure. 
This PR removes the duplicated pipeline.  
Flagged by a user here
https://github.com/huggingface/diffusers/pull/4829#issuecomment-1714923036
=> remove extra gligen in import

src/diffusers/pipelines/wuerstchen/pipeline_wuerstchen.py, src/diffusers/pipelines/wuerstchen/pipeline_wuerstchen_combined.py, src/diffusers/pipelines/wuerstchen/pipeline_wuerstchen_prior.py
Fix the `prompt_embeds` to take the `image_embeddings` size when generating `num_images_per_prompt` > 1
cc @dome272 
also added `prompt_embed` and `negative_prompt_embeds` to the prior pipeline
=> [Wuerstchen] fix combined pipeline's num_images_per_prompt

tests/pipelines/stable_diffusion/test_stable_diffusion_image_variation.py
This PR fixes the following error in the Stable Diffusion Image Variation Pipeline Slow Tests
```
tests/pipelines/stable_diffusion/test_stable_diffusion_image_variation.py::StableDiffusionImageVariationPipelineSlowTests::test_stable_diffusion_img_variation_intermediate_state - ValueError: Trying to set a tensor of shape torch.Size([768, 1024]) in "weight" (which has shape torch.Size([512, 1024])), this look incorrect.
```
members/contributors who may be interested …
=> fix image variation slow test

tests/models/test_models_unet_2d_condition.py
Fixes failing model test with custom diffusion attention processor
```
FAILED tests/models/test_models_unet_2d_condition.py::UNet2DConditionModelTests::test_custom_diffusion_save_load - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
```
=> fix custom diffusion tests

src/diffusers/pipelines/pipeline_utils.py
Fixes: `tests/pipelines/semantic_stable_diffusion/test_semantic_diffusion.py::SafeDiffusionPipelineFastTests::test_semantic_diffusion_no_safety_checker`
=> [Flax->PT] Fix flaky testing

src/diffusers/pipelines/stable_diffusion_safe/__init__.py, src/diffusers/pipelines/text_to_video_synthesis/__init__.py, src/diffusers/pipelines/vq_diffusion/__init__.py, src/diffusers/pipelines/wuerstchen/__init__.py
Corrects some typos of the import structure
=> [Import] Add missing settings / Correct some dummy imports

src/diffusers/schedulers/scheduling_dpmsolver_sde.py
this PR add some small modification to `DPMSolverSDEScheduler`
1. add `_step_index` 
2. set `noise_sampler = None` inside `set_timesteps`. This fix https://github.com/huggingface/diffusers/issues/4875
=> add step_index and clear noise_sampler at begining of each loop

tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py
Adds Fast Tests specifically for the SDXL refiner
#5031
=> Add SDXL refiner only tests

docs/source/en/using-diffusers/sdxl.md, docs/source/en/using-diffusers/textual_inversion_inference.md
Adds better docs on how to use textual inversion with diffusers. Also cc @apolinario
=> [SDXL, Docs] Textual inversion

docs/source/en/api/pipelines/wuerstchen.md, src/diffusers/pipelines/wuerstchen/__init__.py
=> [Wuerstchen] fix typos in docs

examples/t2i_adapter/train_t2i_adapter_sdxl.py
Fixes https://github.com/huggingface/diffusers/issues/5037. 
Colab: https://colab.research.google.com/gist/sayakpaul/d8d07dcbaa9a0de134836acc53cd8f58/scratchpad.ipynb
=> fix: validation_image arg

tests/pipelines/audioldm2/test_audioldm2.py, tests/pipelines/kandinsky/test_kandinsky_inpaint.py, tests/pipelines/kandinsky_v22/test_kandinsky_controlnet.py, tests/pipelines/latent_diffusion/test_latent_diffusion.py, tests/pipelines/latent_diffusion/test_latent_diffusion_superresolution.py, tests/pipelines/shap_e/test_shap_e.py, tests/pipelines/shap_e/test_shap_e_img2img.py, tests/pipelines/stable_diffusion/test_cycle_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_ldm3d.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_flax.py, tests/pipelines/unclip/test_unclip.py, tests/pipelines/unclip/test_unclip_image_variation.py, tests/pipelines/unidiffuser/test_unidiffuser.py
Moves the slow tests to nightly for low usage pipelines based on 
https://huggingface.co/spaces/diffusers/pipeline_stats
=> Move to slow tests to nightly

examples/controlnet/train_controlnet_flax.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py
Implements #5096 for the rest of the example scripts that currently implement SNR gamma.
=> SNR gamma fixes for v_prediction training

src/diffusers/pipelines/controlnet/pipeline_controlnet_blip_diffusion.py
Fix a minor error in the docs of BLIP Diffusion.
=> [docs] Add missing parenthesis in the sample code of BLIP Diffusion

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
After the docs refactor we recently tackled.
=> SDXL: update links to refine docs

src/diffusers/pipelines/pipeline_utils.py
Make sure the repo_id is valid before sending it to huggingface_hub to get a more understandable error message.
Fixes #5110
@patrickvonplaten  @sayakpaul
=> [pipeline utils] sanitize pretrained_model_name_or_path

docs/source/en/api/pipelines/wuerstchen.md
This PR correctly formats a bibtext entry and fixes the doc builder
=> [Docs] Try to fix doc builder

examples/controlnet/train_controlnet_flax.py, examples/kandinsky2_2/text_to_image/train_text_to_image_decoder.py, examples/kandinsky2_2/text_to_image/train_text_to_image_lora_decoder.py, examples/kandinsky2_2/text_to_image/train_text_to_image_lora_prior.py, examples/kandinsky2_2/text_to_image/train_text_to_image_prior.py, examples/research_projects/onnxruntime/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
After extensive testing, it turns out that the upstream v-prediction fix isn't enough to actually fix the SNR issue. Using terminal SNR with Epsilon also has a problem, that this resolves.
I'm not sure of the Python-specific reasoning that this is required, but I'm assuming it's because an Inf positional value cannot have 1 added to it, as, adding 1 to Infinity does not equate to 1.
=> Min-SNR Gamma: follow-up fix for zero-terminal SNR models on v-prediction or epsilon

src/diffusers/image_processor.py
Fix `VaeImageProcessor` docstring
```
do_binarize (`bool`, *optional*, defaults to `True`)
|
v
do_binarize (`bool`, *optional*, defaults to `False`)
```
@yiyixuxu @patrickvonplaten @stevhliu
=> fix-VaeImageProcessor-docstring

docs/source/en/using-diffusers/conditional_image_generation.md
As requested in #4758, this updates the text-to-image guide to be more extensive and in-depth.
=> [docs] Improved text-to-image guide

src/diffusers/models/attention_flax.py
=> Wrap lines in docstring

tests/schedulers/test_scheduler_consistency_model.py, tests/schedulers/test_scheduler_ddim.py, tests/schedulers/test_scheduler_ddim_parallel.py, tests/schedulers/test_scheduler_ddpm.py, tests/schedulers/test_scheduler_ddpm_parallel.py, tests/schedulers/test_scheduler_deis.py, tests/schedulers/test_scheduler_dpm_multi.py, tests/schedulers/test_scheduler_dpm_single.py, tests/schedulers/test_scheduler_euler.py, tests/schedulers/test_scheduler_euler_ancestral.py, tests/schedulers/test_scheduler_heun.py, tests/schedulers/test_scheduler_kdpm2_ancestral.py, tests/schedulers/test_scheduler_kdpm2_discrete.py, tests/schedulers/test_scheduler_lms.py, tests/schedulers/test_scheduler_unipc.py, tests/schedulers/test_schedulers.py
this PR adds a fast test to test `add_nosie` function of all schedulers that have this function
=> Add `test_full_loop_with_noise` tests to all scheduler with `add_nosie` function 

src/diffusers/loaders.py, src/diffusers/models/attention_processor.py, src/diffusers/models/autoencoder_kl.py, src/diffusers/models/controlnet.py, src/diffusers/models/prior_transformer.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/models/unet_3d_condition.py, src/diffusers/pipelines/audioldm2/modeling_audioldm2.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py, tests/lora/test_lora_layers_old_backend.py
Fixes https://github.com/huggingface/diffusers/issues/5135
=> [LoRA, Xformers] Fix xformers lora

src/diffusers/models/attention_flax.py, src/diffusers/models/unet_2d_blocks_flax.py, src/diffusers/models/unet_2d_condition_flax.py, src/diffusers/pipelines/pipeline_flax_utils.py
Related: #5181 
cc @entrpn feel free to review!
=> Trickle down `split_head_dim`

examples/t2i_adapter/README_sdxl.md
Correct file name in t2i adapter training readme
=> Correct file name in t2i adapter training readme

src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py
It adds the missing inverse scale multiplication before decoding them with vqvae in unconditional LDM.
Fixes  (https://github.com/huggingface/diffusers/issues/5166)
=> fixed vae scaling

tests/pipelines/audio_diffusion/test_audio_diffusion.py, tests/pipelines/audioldm/test_audioldm.py, tests/pipelines/kandinsky_v22/test_kandinsky_controlnet_img2img.py, tests/pipelines/latent_diffusion/test_latent_diffusion_uncond.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_k_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_model_editing.py, tests/pipelines/stable_diffusion/test_stable_diffusion_paradigms.py, tests/pipelines/stable_diffusion/test_stable_diffusion_sag.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_diffedit.py, tests/pipelines/stable_unclip/test_stable_unclip.py, tests/pipelines/stable_unclip/test_stable_unclip_img2img.py, tests/pipelines/text_to_video/test_text_to_video_zero.py, tests/pipelines/text_to_video/test_video_to_video.py
Move more slow tests to nightly based on this list:
https://github.com/huggingface/diffusers/issues/4527 
=> Move more slow tests to nightly

docs/source/ko/using-diffusers/unconditional_image_generation.md
=> Fix doc KO unconditional_image_generation.md

examples/research_projects/sdxl_flax/README.md, examples/research_projects/sdxl_flax/sdxl_single.py, examples/research_projects/sdxl_flax/sdxl_single_aot.py
This PR adds an example of how to run SDXL in Flax on TPUv5
=> [Research folder] Add SDXL example

src/diffusers/schedulers/scheduling_ddim.py, src/diffusers/schedulers/scheduling_ddim_parallel.py, src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_parallel.py, src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
Fix failing tests for the UniPC 1D scheduler (cc @sayakpaul thanks for the ping on Slack)
=> Fix UniPC scheduler for 1D

docker/diffusers-pytorch-cuda/Dockerfile
Recent torch 2.1 release is breaking the CI. Pin version in docker torch cuda image for now. 
=> pin torch version

tests/pipelines/shap_e/test_shap_e_img2img.py
Fix failing ShapE pipeline fast test by slighting bumping up tolerance.  
=> Bump tolerance on shape test

examples/dreambooth/train_dreambooth_lora.py
=> fix typo in train dreambooth lora description

src/diffusers/models/activations.py, src/diffusers/models/resnet.py
Fixes #5249.
Improves type hints and docs in the following files:
- [diffusers/models/activations.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/activations.py)
- [diffusers/models/resnet.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py)
@patrickvonplaten @yiyixuxu
=> Improve typehints and docs in `diffusers/models`

docs/source/en/using-diffusers/sdxl.md
Fixes a minor mistake in the docs for `StableDiffusionXLImg2ImgPipeline` creation in the sdxl tutorial.
=> Fix `StableDiffusionXLImg2ImgPipeline` creation in sdxl tutorial

utils/stale.py
Just like: https://github.com/huggingface/peft/pull/1016/. 
Thanks @BenjaminBossan.
=> [Bot] FIX stale.py uses timezone-aware datetime

examples/unconditional_image_generation/train_unconditional.py
Fixes: https://github.com/huggingface/diffusers/issues/5274
=> [Examples] fix unconditioning generation training example for mixed-precision training

docs/source/en/tutorials/basic_training.md, docs/source/ko/tutorials/basic_training.md
@Wauplin 
I have replied to your comments directly on https://github.com/huggingface/diffusers/pull/5393
=> [Examples] Follow up of #5393

docs/source/en/training/create_dataset.md, docs/source/en/training/lora.md, docs/source/en/using-diffusers/img2img.md, docs/source/en/using-diffusers/inpaint.md, docs/source/en/using-diffusers/reproducibility.md, docs/source/en/using-diffusers/write_own_pipeline.md, examples/community/README.md
This PR fix the typo seen in multiple files
```pesudo
offical > official
propotions > proportions
intialized > initialized
varibale > variable
dose > does
Pipline > Pipeline
unlimted > unlimited
```
=> Chore: Typo fixed in multiple files

utils/fetch_torch_cuda_pipeline_test_matrix.py
The pipeline fetcher for the slow tests throws an error when trying to fetch a community pipeline from diffusers. 
This PR skips trying to fetch the pipeline tests if the pipeline isn't present in the diffusers package.  
=> Fix pipe fetcher for slow tests

examples/text_to_image/train_text_to_image_sdxl.py
=> style(sdxl): remove identity assignments

docs/source/en/api/pipelines/kandinsky_v22.md
correct a checkpoint in kandinsky 2.2 doc. 
Thanks @sayakpaul for noticing this!
=> correct checkpoint in kandinsky2.2 doc page

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml, docs/source/pt/_toctree.yml, docs/source/pt/index.md, docs/source/pt/installation.md, docs/source/pt/quicktour.md
=> docs: initial pt translation

src/diffusers/pipelines/pipeline_utils.py
Fixes #5553.
@patrickvonplaten @sayakpaul
=> Fix incorrect loading of custom pipeline

examples/community/stable_diffusion_ipex.py
Add `TextualInversionLoaderMixin` as parent class of `StableDiffusionIPEXPipeline`.
To get rid of the error while loading textural inversion:
```
File "/root/sd_ipex_pipeline2.py", line 32, in <module>
pipe.load_textual_inversion("./cat-toy")
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.conda/envs/sd/lib/python3.11/site-packages/diffusers-0.19.3-py3.11.egg/diffusers/configuration_utils.py", line 137, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionIPEXPipeline' object has no attribute 'load_textual_inversion'
```
=> [Community Pipelines] add textual inversion support for stable_diffusion_ipex

docker/diffusers-pytorch-xformers-cuda/Dockerfile
`xformers` has been updated to work with CUDA 12.1 and Torch 2.1. This updates the xformers test image so that the Cuda errors are fixed. 
=> Update docker image for xformers

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/custom_pipeline_overview.md
@stevhliu FYI. Feel free to open a follow-up PR for fixes.
=> [remote code] document trust remote code.

docs/source/en/api/pipelines/animatediff.md
=> Update animatediff docs to include section on Motion LoRAs

src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models_img2img.py
This PR does some cleanup of the LCM pipeline and testing code. In particular, the changes are as follows:
1. Made a correction to the `expected_slice` for `LatentConsistencyModelPipelineFastTests.test_lcm_multistep` and tightened the test tolerance to `1e-3`.
2. Also tightened `LatentConsistencyModelImg2ImgPipelineFastTests::test_lcm_multistep`'s tolerance to `1e-3`.
3. Added a `check_inputs` method to `LatentConsistencyModelImg2ImgPipeline`.
4. Removed some redundant code in `LatentConsistencyModelImg2ImgPipeline.__call__`.
Anyone in the community is free to review the …
=> Clean up LCM Pipeline and Test Code.

docs/source/en/training/distributed_inference.md, docs/source/en/using-diffusers/control_brightness.md, docs/source/en/using-diffusers/freeu.md, docs/source/en/using-diffusers/reusing_seeds.md, docs/source/en/using-diffusers/textual_inversion_inference.md, docs/source/en/using-diffusers/weighted_prompts.md
Fix typos, improve, update; add visualizations.
Stable Diffusion Conceptualizer -> Runtime error:
- https://huggingface.co/docs/diffusers/main/en/using-diffusers/textual_inversion_inference#:~:text=concepts%20in%20the-,Stable%20Diffusion%20Conceptualizer,-.
- https://huggingface.co/docs/diffusers/main/en/using-diffusers/weighted_prompts#:~:text=Stable%20Diffusion%20Conceptualizer
Wandb link: "It looks like you’ve landed on a locked or empty page.":
- https://huggingface.co/docs/diffusers/main/en/using-diffusers/freeu#:~:text=Comes%20from%20%0A%23-,https%3A//wandb.ai,-/nasirk24/UNET%2DFreeU
@stevhliu @yiyixuxu @DN6 …
=> [`Docs`] Fix typos, improve, update at Using Diffusers' Tecniques page

tests/pipelines/test_pipelines_common.py
=> tests for callbacks

tests/models/test_modeling_common.py
We have a few failing slow model tests because a couple of xformers tests were grouped in with the torch attention tests. 
This PR moves the xformers tests into their own dedicated test 
=> Model tests xformers fixes

src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_combined.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_img2img.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_inpaint.py, src/diffusers/pipelines/kandinsky/pipeline_kandinsky_prior.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_prior.py, src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_prior_emb2emb.py, src/diffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_latent_upscale.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py
We have failing slow pipeline tests related to `model_cpu_offload`, where not all components are moved back to cpu after inference because they do not use `maybe_free_model_hooks`. This PR updates the pipelines to offload all components correctly after inference.   
=> Update free model hooks

src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip.py, src/diffusers/pipelines/unclip/pipeline_unclip.py, src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py
This PR fixes "make fix-copies" on current main.
=> Fix styling issues

src/diffusers/pipelines/animatediff/pipeline_animatediff.py, tests/pipelines/animatediff/test_animatediff.py
Small bug in AnimateDiff doesn't allow prompt to be None in `__call__`. This PR fixes that. 
=> Fix prompt bug in AnimateDiff

.github/workflows/pr_tests.yml
=> Install accelerate from PyPI in PR test runner

src/diffusers/models/autoencoder_asym_kl.py, src/diffusers/models/autoencoder_tiny.py, src/diffusers/models/consistency_decoder_vae.py, tests/models/test_models_vae.py
Follow-up PR to clean up some things
=> Correct consist dec

examples/text_to_image/train_text_to_image_flax.py, examples/text_to_image/train_text_to_image_lora_sdxl.py
The PR was resubmitted and the original branch was deleted. https://github.com/huggingface/diffusers/pull/4655#issuecomment-1805305638
@yiyixuxu
=> add load_datasete data_dir parameter

examples/community/README.md, examples/community/llm_grounded_diffusion.py
Thanks to the HF team for the invitation! LMD+ is implemented as a pipeline in diffusers in this PR.
This PR adds [LLM-grounded Diffusion](https://llm-grounded-diffusion.github.io/) (LMD+). The added `llm-grounded-diffusion` pipeline (`LLMGroundedDiffusionPipeline`) is a simplified pipeline of LMD+.
* Text Prompt: `a waterfall and a modern high speed train in a beautiful forest with fall foliage`
* Layout: two boxes specified in the code
* Code:
```python
import torch
"longlian/lmd_plus",
custom_pipeline="llm-grounded-diffusion",
variant="fp16", torch_dtype=torch.float16
)
prompt = "a waterfall and a modern high speed train in a beautiful forest with fall foliage"
boxes = …
```
=> Add LLM-grounded Diffusion (LMD+) pipeline

examples/research_projects/realfill/train_realfill.py
Correct code for distributed training of RealFill
=> Correct code for distributed training of RealFill

src/diffusers/schedulers/scheduling_lcm.py
Better error message for LCM. Fixes: https://github.com/huggingface/diffusers/issues/5711
=> [LCM] Better error message

src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py
=> fix exception around NSFW filter on flax stable diffusion

src/diffusers/utils/constants.py
See #5765. Was unable to reopen the original PR after force pushing.
@younesbelkada
=> Use greater than or equal to in version comparisons for peft

examples/community/ddim_noise_comparative_analysis.py, examples/community/iadb.py, examples/community/mixture_canvas.py, examples/community/mixture_tiling.py, examples/community/pipeline_fabric.py, examples/community/stable_diffusion_controlnet_img2img.py, examples/community/stable_diffusion_controlnet_inpaint.py, examples/community/stable_diffusion_ipex.py
@stevhliu ,
I fixed the import errors.
https://github.com/huggingface/diffusers/issues/5380
=> 🔧 Fix import codes in diffusers library

examples/text_to_image/train_text_to_image_flax.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, src/diffusers/models/consistency_decoder_vae.py
Small fix of Consistency Decoder documentation
@stevhliu @yiyixuxu
=> Fixed documentation of consistency decoder

examples/community/lpw_stable_diffusion_xl.py
the community lpw_stable_diffusion_xl added by PR https://github.com/huggingface/diffusers/pull/4661 can't handle num_images_per_prompt>1 case. I fixed script to make num_images_per_prompt work well.
Fixes https://github.com/huggingface/diffusers/issues/5081
original PR contributor, @xhinker may review this
=> fix: enabled num_images_per_prompt>1 for lpw_stable_diffusion_xl (community pipeline)

docs/source/en/using-diffusers/custom_pipeline_overview.md
=> [Docs] add: japanese sdxl as a reference

setup.py, src/diffusers/dependency_versions_table.py
=> [PEFT] Unpin peft

.github/workflows/pr_test_peft_backend.yml
Fixes a typo that led never downloading peft from source
cc @patrickvonplaten @sayakpaul @DN6
=> [`test` / `peft`] Fix silent behaviour on PR tests

src/diffusers/pipelines/musicldm/pipeline_musicldm.py
Fixes #5835 to use a compatible checkpoint
=> [docs] MusicLDM

examples/dreambooth/train_dreambooth_lora_sdxl.py
minor change to fix metadata tags in readme
=> [bug fix] fix small bug in readme template of sdxl lora training script

src/diffusers/models/transformer_2d.py
Fixes https://github.com/huggingface/diffusers/issues/5862
=> [Core] add support for gradient checkpointing in transformer_2d

examples/community/stable_diffusion_ipex.py
enhance IPEX pipeline to suport latest LoRA feature.
=> add  LoRA weights load and fuse support for IPEX pipeline

.github/workflows/pr_test_fetcher.yml, .github/workflows/push_tests_fast.yml, .github/workflows/push_tests_mps.yml
Let's make sure to not run PRs after one added already a new commit
=> [Tests] Make sure that we don't run tests multiple times

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py
Fix a minor typo in the docstring for the Pixart-alpha pipeline.
=> fix: minor typo in docstring

docs/source/en/api/pipelines/overview.md
Updates the pipeline overview list with Kandinsky 3
=> [docs] Update pipeline list

examples/wuerstchen/text_to_image/requirements.txt, examples/wuerstchen/text_to_image/train_text_to_image_lora_prior.py
Updated the script to use PEFT as per PR #5388 that fixes #5441
=> [Wuerstchen] Adapt lora training example scripts to use PEFT

docs/source/en/using-diffusers/svd.md
=> Fix SVD doc

src/diffusers/pipelines/stable_diffusion/__init__.py
I think that this is a simple typo because the line removed exactly same as the line above. 
This PR fixes it.
- Docs: @stevhliu
=> Remove a duplicated line?

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
fix minor issue with readme
cc @apolinario
=> [advanced_dreambooth_lora_sdxl_tranining_script] readme fix 

CONTRIBUTING.md, Makefile
`setup.py` file can be changed again. Would it be better to put a constant link to show the supported Python versions such as https://huggingface.co/docs/diffusers/main/en/installation?
@stevhliu @yiyixuxu
=> [`Docs`] Update a link

docs/source/en/conceptual/contribution.md
Adds a brief section about the `#Copied from` mechanism as requested in https://github.com/huggingface/diffusers/pull/5993#issuecomment-1834286902.
=> [docs] `#Copied from` mechanism

setup.py, src/diffusers/dependency_versions_table.py
Pins `ruff` to match transformers 
https://github.com/huggingface/transformers/pull/27849/files
=> Pin Ruff Version

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
=> [Advanced Diffusion Script] Add Widget default text

docs/source/en/_toctree.yml, docs/source/en/api/loaders/ip_adapter.md
Adds `IPAdapterMixin` to the API docs
=> [docs] IP-Adapter API doc

setup.py
Example CUDA tests are failing because PEFT is not installed in the runner. 
This PR:
Updates `setup.py` to include PEFT in the training deps. 
=> Add PEFT to training deps

examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py
@patrickvonplaten any objections?
=> [Training] remove depcreated method from lora scripts.

docs/source/en/training/t2i_adapters.md
Fix t2i blog URL
@stevhliu, @yiyixuxu
=> Fix t2i. blog url

src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_zero.py, src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_zero_sdxl.py, tests/pipelines/text_to_video_synthesis/test_text_to_video_zero_sdxl.py
I don't know what made me give this PR a thumbs up: https://github.com/huggingface/diffusers/pull/4695 - it was very much not mergeable. This PR cleans up the mess now.
=> [Text-to-Video] Clean up pipeline

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
This PR makes sure that SVD can correctly compile its VAE. Fixes: https://github.com/huggingface/diffusers/pull/6103#issuecomment-1852114412
=> [Torch Compile] Fix torch compile for svd vae

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
=> [SVD] Fix guidance scale

src/diffusers/models/controlnetxs.py, tests/pipelines/controlnetxs/test_controlnetxs.py
Currently ControlNetXS does not work with the PEFT backend. This PR fixes that and also addresses some precision issues in the slow tests. 
=> ControlNetXS fixes. 

.github/workflows/push_tests_fast.yml
Otherwise: https://github.com/huggingface/diffusers/actions/runs/7257347281/job/19771026520
Cc: @younesbelkada
=> add peft dependency to fast push tests

docs/source/en/using-diffusers/reusing_seeds.md
Clarifies the correct way to create batched seeds based on feedback [here](https://github.com/huggingface/diffusers/issues/6218#issuecomment-1861854211)
=> [docs] Batched seeds

examples/text_to_image/train_text_to_image_lora_sdxl.py
check #6207 again , remove the missed depcreated method. @sayakpaul
=> [Training] remove depcreated method from lora scripts again

src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_sag/__init__.py, src/diffusers/pipelines/stable_diffusion_sag/pipeline_stable_diffusion_sag.py
Similar to https://github.com/huggingface/diffusers/pull/6260.
=> [Refactor] move sag out of `stable_diffusion`

src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_attend_and_excite/__init__.py, src/diffusers/pipelines/stable_diffusion_attend_and_excite/pipeline_stable_diffusion_attend_and_excite.py, src/diffusers/pipelines/stable_diffusion_diffedit/__init__.py
Similar to https://github.com/huggingface/diffusers/pull/6260
=> [Refactor]  move attend and excite out of `stable_diffusion`.

tests/lora/test_lora_layers_peft.py
One more fix to PEFT lora tests to address failing test. 
=> LoRA Unfusion test fix

src/diffusers/pipelines/controlnet/pipeline_controlnet.py
Fixing typos in the not-supported `ValueError` messages for a nested image list as `StableDiffusionControlNetPipeline` input.
> A single batch of multiple conditionings ~~are~~ **is not** supported at the moment.
=> Fix typos in the `ValueError` for a nested image list as `StableDiffusionControlNetPipeline` input.

examples/community/stable_diffusion_tensorrt_img2img.py
=> fix: cannot set guidance_scale

docs/source/en/_toctree.yml, docs/source/en/tutorials/fast_diffusion.md
Adds a doc page to complement: https://github.com/huggingface/diffusion-fast.
=> [Diffusion fast] add doc for diffusion fast

scripts/convert_animatediff_motion_lora_to_diffusers.py, scripts/convert_animatediff_motion_module_to_diffusers.py
Add AnimateDiff conversion scripts for motion module and motion LoRAs. 
=> Add AnimateDiff conversion scripts

docs/source/en/using-diffusers/svd.md
Fixes the video rendering issues on https://huggingface.co/docs/diffusers/main/en/using-diffusers/svd.
=> [Docs] fix: video rendering on svd.

src/diffusers/models/attention.py
One of the FF layers in SVD chunking was incorrect, resulting degraded output. 
#6258
=> Fix chunking in SVD

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
Small fix to align it with the other scripts
=> Fix keys for lora format on advanced training scripts

docs/source/en/tutorials/fast_diffusion.md
Adds details on the changes that were more specific to `diffusers`:
* Reducing GPU <-> CPU sync
* Removing graph breaks
=> [docs] add details concerning diffusers-specific bits.

examples/research_projects/multi_subject_dreambooth_inpainting/README.md
The link to the weights & baises report was broken. It has been fixed now. 
@patrickvonplaten and @sayakpaul
=> changed w&b report link

tests/lora/test_lora_layers_peft.py
=> [LoRA] remove unnecessary components from lora peft test suite

src/diffusers/utils/__init__.py
Small fix that should've belonged to #6395
=> Add new WebUI conversion state_dict_utils to __init__ utils

docs/source/en/tutorials/fast_diffusion.md
Add short details on CUDA graphs.
=> add: CUDA graph details.

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
* Fixes wrong type assignment to `noise_aug_strength` in SVD pipeline
=> [svd] fix noise_aug_strength type in svd pipe

examples/research_projects/controlnetxs/controlnetxs.py, src/diffusers/loaders/lora.py, src/diffusers/models/attention_processor.py, src/diffusers/models/autoencoders/autoencoder_kl.py, src/diffusers/models/autoencoders/autoencoder_kl_temporal_decoder.py, src/diffusers/models/autoencoders/consistency_decoder_vae.py, src/diffusers/models/controlnet.py, src/diffusers/models/prior_transformer.py, src/diffusers/models/unet_2d_condition.py, src/diffusers/models/unet_3d_condition.py, src/diffusers/models/unet_motion_model.py, src/diffusers/models/uvit_2d.py, src/diffusers/pipelines/audioldm2/modeling_audioldm2.py, src/diffusers/pipelines/deprecated/versatile_diffusion/modeling_text_unet.py, src/diffusers/pipelines/wuerstchen/modeling_wuerstchen_prior.py, tests/lora/test_lora_layers_old_backend.py
Follow up of: https://github.com/huggingface/diffusers/pull/6369. Unblocks https://github.com/huggingface/diffusers/pull/6358.
=> [LoRA deprecation] handle rest of the stuff related to deprecated lora stuff.

examples/dreambooth/README_sdxl.md
So that people don't have this confusion: https://github.com/huggingface/diffusers/issues/6413
=> Update README_sdxl.md to update the LR

.github/workflows/push_tests.yml
Context: https://huggingface.slack.com/archives/C065E480NN9/p1704276517314299
=> disable running peft non-peft lora test in the peft env.

tests/lora/test_lora_layers_old_backend.py
Internal thread: https://huggingface.slack.com/archives/C065E480NN9/p1704343187572879
=> [LoRA tests] fix stuff related to assertions arising from the recent changes. 

docs/source/en/tutorials/fast_diffusion.md
Fixes #6439 which is returning `404` for local links
=> [docs] Fix local links

src/diffusers/models/unet_2d_condition.py, src/diffusers/models/unet_3d_condition.py, src/diffusers/pipelines/deprecated/versatile_diffusion/modeling_text_unet.py, tests/lora/test_lora_layers_old_backend.py
Context: https://github.com/huggingface/diffusers/pull/6426/files#r1440273570. 
I think it's now time for us to revisit https://github.com/huggingface/diffusers/pull/5958 after this.
=> [feat] introduce `unload_lora()`.

examples/research_projects/diffusion_dpo/REAMDE.md, examples/research_projects/diffusion_dpo/requirements.txt, examples/research_projects/diffusion_dpo/train_diffusion_dpo.py, examples/research_projects/diffusion_dpo/train_diffusion_dpo_sdxl.py
Based on the amazing work done by @bram-w here for Diffusion DPO: https://github.com/bram-w/trl/blob/dpo/. The ultimate goal is to have it in `trl`. 
Uses this toy dataset for training validation: https://huggingface.co/datasets/kashif/pickascore. 
Training command:
```bash
CUDA_VISIBLE_DEVICES=0 accelerate launch train_diffusion_dpo.py \
--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5  \
--output_dir="diffusion-dpo" \
--mixed_precision="fp16" \
--dataset_name=kashif/pickascore \
--train_batch_size=16 \
--gradient_accumulation_steps=2 \
--gradient_checkpointing \
--use_8bit_adam \
--rank=8 \
--learning_rate=1e-5 \
--report_to="wandb" \
--lr_scheduler="constant" \
--lr_warmup_steps=0 \
--max_train_steps=10000 \
--checkpointing_steps=2000 \
--run_validation …
```
=> [Experimental] Diffusion LoRA DPO training

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/stable_diffusion/k_diffusion.md, src/diffusers/__init__.py, src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion_k_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion_k_diffusion/pipeline_stable_diffusion_k_diffusion.py, src/diffusers/pipelines/stable_diffusion_k_diffusion/pipeline_stable_diffusion_xl_k_diffusion.py, src/diffusers/utils/dummy_torch_and_transformers_and_k_diffusion_objects.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_k_diffusion.py
this PR add k-diffusion pipeline for sdxl 
```python
import torch
from diffusers import StableDiffusionXLKDiffusionPipeline
seed = 33
model_id = "frankjoshua/juggernautXL_version6Rundiffusion"
pipe = StableDiffusionXLKDiffusionPipeline.from_pretrained(
model_id,
use_safetensors=True,
).to("cuda")
pipe.set_scheduler("sample_dpmpp_2m_sde")
prompt = "Adorable infant playing with a variety of colorful rattle toys."
generator = torch.Generator(device="cuda").manual_seed(seed)
image = pipe(
prompt, 
generator=generator, 
guidance_scale=3.0,
num_inference_steps=25, 
use_karras_sigmas=True,
height=768,
width=1344,
noise_sampler_seed =0,
).images[0]
image.save("yiyi_test_1_out.png")
```
=> add `StableDiffusionXLKDiffusionPipeline`

docs/source/en/using-diffusers/callback.md
Minor updates to the interruption callback docs (make the section header more concise, make the supported pipelines more concise and fix the links there).
=> [docs] Callbacks

examples/research_projects/diffusion_dpo/train_diffusion_dpo.py, examples/research_projects/diffusion_dpo/train_diffusion_dpo_sdxl.py
Add argument for custom tracker name
=> [DPO Training] pass tracker name as argument

examples/controlnet/train_controlnet_sdxl.py
Part of #6503 for `Controlnet SDXL`
@sayakpaul
After #6511 is done!
=> Make ControlNet SDXL Training Script torch.compile compatible

examples/text_to_image/train_text_to_image_sdxl.py
This PR makes train_text_to_image_sdxl.py compatible with torch.compile() as requested in #6503
=> SDXL text-to-image torch compatible

examples/t2i_adapter/train_t2i_adapter_sdxl.py
Part of #6503 for `T2I_adapter SDXL`
Last one @sayakpaul
=> Make T2I Adapter SDXL Training Script torch.compile compatible

docs/source/en/using-diffusers/controlnet.md
The indent of Controlnet currently looks quite weird - see here: https://huggingface.co/docs/diffusers/using-diffusers/controlnet#multicontrolnet
=> [Docs] Fix controlnet indent

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py
hi
@yiyixuxu 
#6516
I added code to it
=> :bug: fix ip-adapter controlnet img2img missing code

src/diffusers/loaders/lora.py
Part of #6585 for lora.py
@sayakpaul @patrickvonplaten
=> change to posix for better Windows support for lora loaders

src/diffusers/utils/testing_utils.py
Part of #6585 
@sayakpaul are we required to make changes in testing_utils too?
=> Use of Posix to better support Windows compatibility in testing_utils

examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
Fixes torch.compile() compatible training for the Advanced Dreambooth LoRa trainer.
=> Fixes torch.compile() compatible training

.github/workflows/pr_test_peft_backend.yml
Only 1 process for GPU testing
=> Update pr_test_peft_backend.yml to use 1 process for testing

docs/source/en/api/models/autoencoderkl.md
Attempts to fix missing functions from the API docs.
=> [docs] Fix missing API function

examples/research_projects/diffusion_dpo/train_diffusion_dpo_sdxl.py
Applies the micro-conditioning fixes from #6547 to the diffusion DPO SDXL LoRA script. Thanks to @haofanwang.
=> [Diffusion DPO] apply fixes from #6547

utils/fetch_torch_cuda_pipeline_test_matrix.py
Makes sure IP Adapter are always tested when running slow tests. 
=> Add IP Adapters to slow tests

examples/research_projects/diffusion_dpo/train_diffusion_dpo_sdxl.py
Fixes https://github.com/huggingface/diffusers/issues/6741.
=> correct hflip arg

docs/source/en/tutorials/using_peft_for_inference.md
Fixes: https://github.com/huggingface/diffusers/issues/6602.
=> add note about serialization

docker/diffusers-onnxruntime-cpu/Dockerfile, docker/diffusers-onnxruntime-cuda/Dockerfile, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile, setup.py, src/diffusers/dependency_versions_table.py
CI is currently breaking because the torch has been updated on PyPI to version 2.2. Pinning the versions for now so that the CI can run. 
Will open a follow up to correctly install the latest torch version.    
=> Pin torch < 2.2.0 in test runners

tests/pipelines/kandinsky2_2/test_kandinsky_inpaint.py
Check https://huggingface.slack.com/archives/C065E480NN9/p1706602235715929
=> [Kandinsky tests] add `is_flaky` to test_model_cpu_offload_forward_pass 

examples/research_projects/diffusion_dpo/train_diffusion_dpo.py
Add some alternative pref-tuning losses to script
=> add ipo, hinge and cpo loss to dpo trainer

src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_utils.py
Bug in `from_single_file` is preventing VAE scaling factor from being set correctly. This PR allows correctly setting `scaling_factor`  
#6753 
=> Fix setting scaling factor in VAE config

src/diffusers/utils/testing_utils.py
Fixes test collection on MPS.
Fixes #6807
Core library:
- JAX and MPS: @pcuenca
=> [Contributor Experience] Fix test collection on MPS

examples/dreambooth/train_dreambooth_lora_sdxl.py
FIxes: https://github.com/huggingface/diffusers/issues/6146#issuecomment-1882534795
One should always unwrap the model to access the model's attributes
cc @sayakpaul
=> Fixes LoRA SDXL training script with DDP + PEFT

examples/community/ip_adapter_face_id.py
Fixes #6832
I tried also multi-image input as is done in the core, but I didn't add to this PR. Should I?
=> Bugfix in IPAdapterFaceID

src/diffusers/pipelines/pia/pipeline_pia.py
1. Add single file support to PIA pipeline
2. Fix issue with using IP adapters with PIA pipeline (UNetMotionModel was updated, but the pipeline needed to be updated as well) 
Addresses the single file issue raised in #6827 
=> Add single file and IP Adapter support to PIA Pipeline 

src/diffusers/models/autoencoders/autoencoder_tiny.py
When using slicing with AutoencoderTiny, the encoder mistakenly encodes the entire batch for every image in the batch.
=> Fix `AutoencoderTiny` with `use_slicing`

examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py
Fix keyword argment name mis-match at #6729.
Should be fixed before #6891.
@sayakpaul
=> fix: keyword argument mismatch

scripts/convert_diffusers_sdxl_lora_to_webui.py
Now this conversion script has named parameters like in documentation at the top of the file.
@sayakpaul @linoytsaban @apolinario
=> changed positional parameters to named parameters like in docs

examples/community/pipeline_stable_diffusion_xl_instantid.py
https://github.com/huggingface/diffusers/issues/6758
=> fix examples/community/pipeline_stable_diffusion_xl_instantid.py

examples/controlnet/train_controlnet_sdxl.py
#6891 for [ControlNet SDXL](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sdxl.py)
Example notebook
https://huggingface.co/camaro/test-model-card-template-controlnet-sdxl
@sayakpaul
=> Standardize model card for Controlnet SDXL

examples/controlnet/train_controlnet.py
#6891 for [ControlNet](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py)
Example notebook
https://huggingface.co/camaro/test-model-card-template-controlnet
@sayakpaul
=> Standardize model card for Controlnet

tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py
Spoke too soon about IPAdapter tests. This should hopefully finally fix all of them. If we see further issues, we should consider adding  the `flaky` decorator. 
=> More IPAdapter test fixes

examples/text_to_image/train_text_to_image.py
Related issue: #6891 for [T2I](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)
Notebook link: [test_model_card_template_t2i.ipynb](https://huggingface.co/cosmo3769/test-model-card-template-t2i/blob/main/test_model_card_template_t2i.ipynb)
Generated model card link: [test-model-card-template-t2i](https://huggingface.co/cosmo3769/test-model-card-template-t2i)
@sayakpaul
=> [Model Card] standardize T2I model card

examples/text_to_image/train_text_to_image_lora.py
Related issue: #6891 for [T2I Lora](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py)
Notebook link: [test_model_card_template_t2i.ipynb](https://huggingface.co/cosmo3769/test-model-card-template-t2i-lora/blob/main/test_model_card_template_t2i_lora.ipynb)
Generated model card link: [test-model-card-template-t2i-lora](https://huggingface.co/cosmo3769/test-model-card-template-t2i-lora)
@sayakpaul
=> [Model Card] standardize T2I Lora model card

examples/text_to_image/train_text_to_image_lora_sdxl.py
Related issue: #6891 for [T2I SDXL LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py)
Notebook link: [test_model_card_template_t2i_sdxl_lora.ipynb](https://huggingface.co/cosmo3769/test-model-template-card-t2i-sdxl-lora/blob/main/test_model_card_template_t2i_sdxl_lora.ipynb)
Generated model card link: [test-model-card-template-t2i-sdxl-lora](https://huggingface.co/cosmo3769/test-model-template-card-t2i-sdxl-lora)
@sayakpaul
=> [Model Card] standardize T2I Sdxl Lora model card

examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_sdxl.py
As discussed in this comment [here](https://github.com/huggingface/diffusers/pull/6942#pullrequestreview-1874511689), I have fixed type annotations in these respective files: 
* [T2I](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)
* [T2I SDXL](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py)
* [T2I LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py)
@sayakpaul
=> [Type annotations] fixed in save_model_card

tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py
Add `is_flaky` decorate to the `test_multi` IP Adapter test and update the expected slice so it passes. 
=> Fix flaky IP Adapter test

tests/lora/test_lora_layers_peft.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py
Since we now need PEFT to load LoRAs, we should move this SDXL T2I Adapter test into the PEFT runner. It's failing because PEFT isn't installed in the Pipelines test runner. 
https://github.com/huggingface/diffusers/actions/runs/7876381153/job/21491557538#step:7:3311  
=> Move SDXL T2I Adapter lora test into PEFT workflow 

docs/source/en/using-diffusers/ip_adapter.md
Fixes a broken callout in the IP-Adapter docs.
=> [docs] Fix callout

docs/source/en/api/pipelines/animatediff.md
Alt text and image links in AnimateLCM docs page need to be updated
=> Fix alt text and image links in AnimateLCM docs

tests/pipelines/controlnet/test_controlnet_inpaint.py
#6975 makes it so that the StableDiffusionControlNetInpaintPipeline defaults to using 9 channels for the UNet config. 
This PR updates the `StableDiffusionControlNetInpaintPipeline` test to use the 9 channel UNet checkpoint when running the `from_single_file` test.   
=> Update ControlNet Inpaint single file test 

docs/source/en/using-diffusers/write_own_pipeline.md
=> Change images to image. The variable images is not used anywhere

.github/ISSUE_TEMPLATE/bug-report.yml, .github/PULL_REQUEST_TEMPLATE.md
=> [Easy] edit issue and PR templates

docs/source/en/using-diffusers/loading_adapters.md
=> Fix imports on loading_adapters.md

examples/dreambooth/train_dreambooth_lora_sdxl.py
=> fix kwarg in the SDXL LoRA DreamBooth

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml
No need to run documentation workflows for changes unrelated.
=> limit documentation workflow runs for relevant changes.

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml
https://github.com/huggingface/diffusers/pull/7125 introduced bug. The filter wasn't specified properly. This PR fixes that. 
@DN6 FYI.
=> [CI] fix path filtering in the documentation workflows

examples/dreambooth/train_dreambooth_lora_sdxl.py
Fixes: https://github.com/huggingface/diffusers/issues/7133
Such a silly mistake 🥹
=> fix: loading problem for sdxl lora dreambooth

examples/wuerstchen/text_to_image/requirements.txt
Internal message: https://huggingface.slack.com/archives/C03Q18WK18T/p1709529892062479
FYI @kashif
=> Update requirements.txt to remove huggingface-cli

docker/diffusers-onnxruntime-cuda/Dockerfile
Cuda and Torch versions were not updated for ONNX. 
=> FIx torch and cuda version in ONNX tests

examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py, examples/controlnet/train_controlnet.py, examples/controlnet/train_controlnet_flax.py, examples/controlnet/train_controlnet_sdxl.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/kandinsky2_2/text_to_image/train_text_to_image_decoder.py, examples/kandinsky2_2/text_to_image/train_text_to_image_lora_decoder.py, examples/kandinsky2_2/text_to_image/train_text_to_image_lora_prior.py, examples/kandinsky2_2/text_to_image/train_text_to_image_prior.py, examples/research_projects/controlnet/train_controlnet_webdataset.py, examples/research_projects/lora/train_text_to_image_lora.py, examples/research_projects/onnxruntime/textual_inversion/textual_inversion.py, examples/research_projects/realfill/train_realfill.py, examples/t2i_adapter/train_t2i_adapter_sdxl.py, examples/text_to_image/train_text_to_image.py, examples/text_to_image/train_text_to_image_lora.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py, examples/textual_inversion/textual_inversion.py, examples/textual_inversion/textual_inversion_sdxl.py, examples/wuerstchen/text_to_image/train_text_to_image_lora_prior.py, examples/wuerstchen/text_to_image/train_text_to_image_prior.py
This PR adds:
- `diffusers-training` tags to training scripts
- +`dora` tag to dreambooth lora scripts
=> [training scripts] add tags of diffusers-training

tests/models/autoencoders/test_models_vae.py
Scaling constant is wrong in this test, so the test is failing. 
=> [Tests] Fix incorrect constant in VAE scaling test. 

.github/workflows/pypi_publish.yaml
So that it doesn't happen: https://github.com/huggingface/diffusers/actions/runs/8283556088/job/22667016651#step:7:107
=> add: torch to the pypi step.

docs/source/en/api/pipelines/stable_diffusion/overview.md
Adds docs for `gradio.Interface.from_pipeline()` which is an integration in Gradio that supports all of the StableDiffusion pipelines.
=> Adds docs for `gradio.Interface.from_pipeline()` 

docs/source/en/_toctree.yml, src/diffusers/loaders/lora_conversion_utils.py
Cleans the duplicated code and improves the readability a little bit. Have run the tests too.
=> [LoRA] Clean Kohya conversion utils

docs/source/ko/optimization/fp16.md, docs/source/ko/using-diffusers/write_own_pipeline.md, examples/community/stable_diffusion_ipex.py, examples/community/stable_diffusion_tensorrt_txt2img.py, scripts/convert_if.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_img2img_superresolution.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting.py, src/diffusers/pipelines/deepfloyd_if/pipeline_if_inpainting_superresolution.py, src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_upscale.py, src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen.py, src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen_text_image.py, src/diffusers/schedulers/scheduling_consistency_models.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, tests/models/unets/test_models_unet_2d_condition.py, tests/others/test_config.py, tests/pipelines/dance_diffusion/test_dance_diffusion.py
This pull request updates the access of configuration attributes in the codebase to remove deprecation warnings.
@sayakpaul
=> Update access of configuration attributes

tests/others/test_config.py
This pull request updates the loading of config from a file in the test_config.py file to remove deprecation warning.
@sayakpaul
=> Update loading of config from a file in test_config.py

docs/source/en/api/pipelines/animatediff.md
Add example outputs to FreeInit blocks in docs. 
#7375
=> Add FreeInit Outputs to Docs Page

docs/source/en/_toctree.yml, src/diffusers/schedulers/scheduling_tcd.py
=> [docs] Add missing copied from statements in TCD Scheduler

src/diffusers/models/controlnet.py
Recreate from #7173 
@sayakpaul , @yiyixuxu
=> Fix ControlNetModel.from_unet do not load add_embedding

.github/workflows/push_tests.yml
=> clean dep installation step in push_tests

docs/source/en/using-diffusers/loading.md
As discussed internally. 
Cc: @muellerzr for viz.
=> add: space for calculating memory usagee.

setup.py, src/diffusers/utils/testing_utils.py, tests/others/test_utils.py
Fixes https://github.com/huggingface/diffusers/issues/7441. 
Thanks to @muellerzr for the implementation of `str_to_bool` in https://github.com/huggingface/accelerate/pull/1964.
=> Remove `distutils`

tests/pipelines/deepfloyd_if/test_if.py, tests/pipelines/deepfloyd_if/test_if_img2img.py, tests/pipelines/deepfloyd_if/test_if_img2img_superresolution.py, tests/pipelines/deepfloyd_if/test_if_inpainting.py, tests/pipelines/deepfloyd_if/test_if_inpainting_superresolution.py, tests/pipelines/deepfloyd_if/test_if_superresolution.py, tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py, tests/pipelines/kandinsky/test_kandinsky.py, tests/pipelines/kandinsky/test_kandinsky_img2img.py, tests/pipelines/kandinsky/test_kandinsky_inpaint.py, tests/pipelines/kandinsky2_2/test_kandinsky.py, tests/pipelines/kandinsky2_2/test_kandinsky_controlnet.py, tests/pipelines/kandinsky2_2/test_kandinsky_controlnet_img2img.py, tests/pipelines/kandinsky2_2/test_kandinsky_img2img.py, tests/pipelines/kandinsky2_2/test_kandinsky_inpaint.py, tests/pipelines/kandinsky3/test_kandinsky3.py, tests/pipelines/kandinsky3/test_kandinsky3_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/test_pipelines_common.py, tests/pipelines/text_to_video_synthesis/test_text_to_video.py, tests/pipelines/text_to_video_synthesis/test_text_to_video_zero.py, tests/pipelines/text_to_video_synthesis/test_text_to_video_zero_sdxl.py
Certain tests in our CI are running into timeout issues. The failure routinely seems to happen at the `to(device)` assignment step. This could be potentially due to memory not being cleared properly after each test. 
This PR:
- Adds a memory clean up `setUp` step before running each test to further ensure the CUDA cache is clear before the test is run
- Switches to `enable_model_cpu_offload` for certain tests that are hitting OOM errors.    
Example tests before and after 
Before:
https://github.com/huggingface/diffusers/actions/runs/8368709863/job/22913258160#step:8:527
After:
https://github.com/huggingface/diffusers/actions/runs/8388234973/job/22972025248?pr=7404#step:8:470
[here are …
=> Additional Memory clean up for slow tests

src/diffusers/utils/testing_utils.py
`parse_flag_from_env` is executed before `str_to_bool` is defined leading to an error
https://github.com/huggingface/diffusers/actions/runs/8416161389/job/23042415047#step:6:95
This PR moves the definition before `parse_flag_from_env` to resolve the issue. 
=> Fix for `str_to_bool` definition in testing utils 

src/diffusers/utils/testing_utils.py, tests/models/test_modeling_common.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/test_pipelines.py
See https://github.com/huggingface/diffusers/issues/7441#issuecomment-2016881427.
=> [tests] skip dynamo tests when python is 3.12.

examples/dreambooth/README_sdxl.md, examples/dreambooth/train_dreambooth_lora_sdxl.py
As discussed internally: https://huggingface.slack.com/archives/C03UQJENJTV/p1711032178861949?thread_ts=1710772328.073359&cid=C03UQJENJTV. 
@apolinario could you check if the [output LoRA](https://huggingface.co/sayakpaul/kohya-format-sdxl-lora/blob/main/pytorch_lora_weights_kohya.safetensors) is working? Other info (such as trigger word) is available [here](https://huggingface.co/sayakpaul/kohya-format-sdxl-lora/). 
@yiyixuxu for awareness. Will open it up for the community for other scripts once this gets merged.
=> [Training utils] add kohya conversion dict.

examples/community/llm_grounded_diffusion.py, src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen.py
This PR adds missing raise statements in `check_inputs` in `StableDiffusionGLIGENPipeline` and `LLMGroundedDiffusionPipeline`.
This PR fixes #7456.
Fixes #7456
=> Fix missing raise statements in check_inputs

setup.py
=> [chore] make the istructions on fetching all commits clearer.

examples/advanced_diffusion_training/README.md
Fix Colab notebook links in README.md
=> [Chore] Fix Colab notebook links in README.md

src/diffusers/loaders/single_file_utils.py
=> [Modeling utils chore] import load_model_dict_into_meta only once

.github/workflows/pr_test_peft_backend.yml, .github/workflows/pr_tests.yml
Ccing @pcuenca too because we have had contributors asking about a solution when seeing quality check failures. Hopefully this will help.
=> add: a helpful message when quality and repo consistency checks fail.

tests/pipelines/test_pipelines_common.py
Typo is the CPU offload test is causing it to fail. This PR fixes it.
=> Fix typo in CPU offload test

tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/test_pipelines_common.py
Skip `test_freeu_enabled ` on MPS
Fixes #7569
Core library:
- JAX and MPS: @pcuenca
- General functionalities: @sayakpaul @DN6
=> Skip `test_freeu_enabled ` on MPS

docs/source/en/using-diffusers/callback.md
I found some code bugs when I read callback docs, this PR fix them.
=> [Docs] fix bugs in callback docs

examples/text_to_image/train_text_to_image_sdxl.py
Super simple fix, train script for SDXL forgets to restore original U-Net parameters after each intermediate validation step.
Fixes #7549
@bghira
=> Add missing restore() EMA call in train SDXL script

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/weighted_prompts.md
This PR converts #7321 (prompt enhancing with offset noise and GPT2) into a section in the prompt docs and adds a brief section about how to write a good prompt.
cc @asomoza
=> [docs] Prompt enhancer

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
Fixes: https://github.com/huggingface/diffusers/issues/7616.
=> [Core] fix img2img pipeline for Playground

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
=> Fixed YAML loading.

src/diffusers/loaders/lora.py, tests/lora/test_lora_layers_sd.py
Fix a bug that causes the the call to set_lora_device to ignore the DoRA parameters. A test was added that fails with the current code and passes with the fix.
Note: Not sure if this qualifies as a `@slow` test -- it doesn't download anything new and there is no training/inference, so I'd say no.
@sayakpaul
=> FIX Setting device for DoRA parameters

.github/workflows/pr_test_peft_backend.yml
See: https://github.com/huggingface/diffusers/pull/7650#issuecomment-2054737470
=> don't install peft from the source with uv for now.

.github/workflows/push_tests.yml
=> Don't install PEFT with UV in slow tests

.github/workflows/pr_tests.yml
Refer here for more context: https://github.com/huggingface/diffusers/pull/7543#discussion_r1547317131
=> [Workflows] remove installation of redundant modules from flax PR tests

docs/source/en/optimization/tgate.md
This PR fixes a bug in the code snippet of PixArt and improves the readability of the rest codes.
@stevhliu
=> [Docs] Update TGATE in section `optimization`.

.github/workflows/push_tests.yml
=> Add tailscale action to push_test

src/diffusers/models/controlnet_xs.py, src/diffusers/pipelines/controlnet_xs/pipeline_controlnet_xs_sd_xl.py, tests/pipelines/controlnet_xs/test_controlnetxs.py
Clean up a couple of things in ControlNetXS that were missed in the initial review and update one failing GPU fast test. 
cc: @UmerHA 
=> Cleanup ControlnetXS

tests/pipelines/wuerstchen/test_wuerstchen_prior.py
One of the Wuerscheten tests needs a slight precision bump to pass on the T4 runner. 
=> Update Wuerschten Test

tests/pipelines/kandinsky/test_kandinsky.py, tests/pipelines/kandinsky2_2/test_kandinsky.py, tests/pipelines/kandinsky2_2/test_kandinsky_controlnet.py, tests/pipelines/kandinsky2_2/test_kandinsky_controlnet_img2img.py, tests/pipelines/kandinsky2_2/test_kandinsky_img2img.py, tests/pipelines/kandinsky2_2/test_kandinsky_inpaint.py
Fix a bunch of failing Kandinksy V22 tests after switching to new runners
=> Fix Kandinksy V22 tests

src/diffusers/loaders/ip_adapter.py, tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py
=> Restore AttnProcessor2_0 in unload_ip_adapter

tests/pipelines/test_pipelines_common.py
=> Fix failing VAE tiling test

tests/models/autoencoders/test_models_vae.py
=> Fix test for consistency decoder.

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py
=> Fix CPU offload in docstring

.github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml
Using `ubuntu-latest` as the image for the test fetcher means that all objects imported from `diffusers` are actually dummies since no dependencies like torch/transformers are installed. This leads the CI to attempt to run a job called `utils` (since all dummy objects are in the utils module)
https://github.com/huggingface/diffusers/actions/runs/8889188919/job/24407192775
Also pipelines outside of the core "always test" list are not being fetched because of this. This PR updates so that we use a docker image with the required dependencies needed to fetch the correct modules for the pipelines. 
[here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/do …
=> Fix for pipeline slow test fetcher 

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_instruct_pix2pix.py
fix https://github.com/huggingface/diffusers/issues/7799
this works now 
```python
import torch
from diffusers import StableDiffusionInstructPix2PixPipeline
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
"timbrooks/instruct-pix2pix", torch_dtype=torch.float16, variant="fp16"
)
pipe.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter_sd15.bin")
pipe.set_ip_adapter_scale(0.6)
def download_image(url):
return Image.open(BytesIO(response.content)).convert("RGB")
img_url = "https://huggingface.co/datasets/diffusers/diffusers-images-docs/resolve/main/mountain.png"
image = download_image(img_url).resize((512, 512))
url = …
```
=> [ip-adapter] fix ip-adapter for StableDiffusionInstructPix2PixPipeline

.github/workflows/push_tests.yml
Quick fix for #7824. I forgot that with the new runners we need to specify the image as well as the runner type. 
=> Fix hanging pipeline fetching

tests/pipelines/stable_diffusion/test_stable_diffusion.py
These tests download the `v1-5-pruned-emaonly.ckpt` for SD 1.5, however we've updated our `torch.load` to default to use the `weights_only=True` which is causing issues with this checkpoint since it can't load the serialized PT lightning callbacks. Updating the tests to use the safetensors files instead.  
=> Update download diff format tests

.github/workflows/push_tests.yml
Running the failing tests that have cache issues on our SSH runner which uses `/mnt/cache/.cache/huggingface:/mnt/cache/` and the tests are passing. Updating the cache here to match. It also matches the cache used by transformers. 
=> Update CI cache

.github/workflows/pr_test_fetcher.yml
=> move to new runners

.github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml
=> Change GPU Runners

.github/workflows/push_tests.yml
Remove step where python is being installed in the container. It's not needed since we switched images. 
=> Remove installing python again in container

.github/workflows/push_tests.yml
Set max parallel T4 jobs used in slow pipeline tests so that we don't exhaust the pool. 
=> Set max parallel jobs on slow test runners

examples/text_to_image/train_text_to_image_sdxl.py
1.Fixes a bug related to saving the model when using deepspeed, also similar to https://github.com/huggingface/diffusers/pull/7816.
2.Fixes an out-of-memory bug when handling data.
In the following code, data processing will occur on a single GPU or NPU. Assuming you have eight GPUs and are using gradient accumulation of 4, the batch size will be magnified by 8 * 4 times. so, processing data on a single GPU can easily lead to out-of-memory errors during data processing.
```
train_dataset_with_vae = train_dataset.map(
compute_vae_encodings_fn,
batched=True,
batch_size=args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps,
new_fingerprint=new_fingerprint_for_vae,
)
```
I encountered this issue on an 8xA100 machine. As shown in the figure, the memory usage on …
=> fix bugs when using deepspeed in sdxl

src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
adds custom sigmas and timesteps for StableDiffusionXLControlNet pipeline; users can specify these two arguments in the forward call in accordance with https://github.com/huggingface/diffusers/pull/7817.
- [] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
@yiyixuxu
=> add custom sigmas and timesteps for StableDiffusionXLControlNet pipeline

src/diffusers/loaders/lora.py, src/diffusers/loaders/textual_inversion.py
Fixes issues like https://github.com/huggingface/diffusers/issues/7914.
=> [Core] fix offload behaviour when device_map is enabled.

src/diffusers/models/model_loading_utils.py, src/diffusers/models/modeling_utils.py
=> [Core] separate the loading utilities in modeling similar to pipelines.

tests/single_file/test_stable_diffusion_single_file.py
Fixes https://github.com/huggingface/diffusers/actions/runs/9072995854/job/24929390692#step:7:20090
=> [tests] decorate StableDiffusion21PipelineSingleFileSlowTests with slow.

.github/workflows/push_tests_mps.yml
=> move to GH hosted M1 runner

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py, src/diffusers/pipelines/pixart_alpha/pipeline_pixart_sigma.py
=> Fix the text tokenizer name in logger warning of PixArt pipelines

docs/source/en/optimization/fp16.md
=> Fix typo in "attention"

src/diffusers/models/autoencoders/autoencoder_kl.py
=> Make VAE compatible to torch.compile()

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
SVD input images are not being properly resized in the video processor, and is leading to a test failure since the image latents shape does not match the latents shape.  
https://github.com/huggingface/diffusers/actions/runs/9162762521/job/25190510711#step:9:402 
=> Fix resize issue in SVD pipeline with VideoProcessor

src/diffusers/commands/env.py
The minimum Python version required for this method is 3.10. 
https://docs.python.org/3/library/platform.html#platform.freedesktop_os_release
Diffusers is meant to support Python versions >=3.8. So this would break on older python versions. 
Add an additional check to ensure the command only runs with Python >=3.10. 
=> Use `freedesktop_os_release()` in diffusers cli for Python >=3.10

src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_model.py
Same as https://github.com/huggingface/diffusers/pull/7843 but looks like I forgot those 2 occurrences.
=> Respect `resume_download` deprecation V2

docs/source/en/api/loaders/single_file.md
Clean up some miscellaneous stuff in the docs that was missed in the original PR
=> Clean up `from_single_file` docs

docker/diffusers-doc-builder/Dockerfile
Install zip step is failing on doc builder on main. Adding it to the image for now so that the workflow can run. 
=> Add zip package to doc builder image

docker/diffusers-doc-builder/Dockerfile
https://github.com/huggingface/diffusers/actions/runs/9254346165/job/25455942402
=> install wget.

docs/source/en/conceptual/philosophy.md
Fixes typo in `philosophy.md`
: **future complete** -> **feature-complete**
From discussion [#8278](https://github.com/huggingface/diffusers/discussions/8278#discussioncomment-9583110)
Thank you for your review!
@stevhliu
=> Fix typo in `philosophy.md`

setup.py
=> change to yiyi's address.

docs/source/en/_toctree.yml, docs/source/en/advanced_inference/outpaint.md
This PR adapts @asomoza's outpaint [blog post 3](https://huggingface.co/blog/OzzyGT/outpainting-inpaint-model) for the docs.
=> [docs] Outpaint

docs/source/en/_toctree.yml, docs/source/en/api/models/hunyuan_transformer_2d.md, docs/source/en/api/pipelines/hunyuandit.md
Hi @yiyixuxu @sayakpaul :
This is the updated doc for HunyuanDiT, please have a look.
Thanks
=> Tencent Hunyuan Team - Updated Doc for HunyuanDiT

src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py
The previous example code in pipeline_stable_unclip_img2img.py caused an error when run, this PR updates the example code to run without errors. 
Anyone, but @sayakpaul and @stevhliu are probably the most relevant! 
Core library:
- Schedulers: @yiyixuxu 
- Pipelines:  @sayakpaul @yiyixuxu @DN6
- Training examples: @sayakpaul 
- Docs: @stevhliu and @sayakpaul
- JAX and MPS: @pcuenca
- Audio: @sanchit-gandhi
- General functionalities: @sayakpaul @yiyixuxu @DN6
Integrations:
- deepspeed: HF Trainer/Accelerate: @pacman100
HF projects:
- accelerate: [different …
=> Update code example in pipeline_stable_unclip_img2img.py EXAMPLE_DOC_STRING

.github/workflows/mirror_community_pipeline.yml
=> Fix mirror community pipeline

src/diffusers/models/attention_processor.py
Fixes [**#7033**](https://github.com/huggingface/diffusers/issues/7033) and duplicate issue [**#7695**](https://github.com/huggingface/diffusers/issues/7695)
For testing, please follow the IP adapter masking section of the docs [**here**](https://huggingface.co/docs/diffusers/main/en/using-diffusers/ip_adapter?tasks=Text-to-image#ip-adapter-masking). You will no longer see the warning message spam the console.
@sayakpaul @yiyixuxu @DN6 requesting review, thank you! …
=> 🤫 Quiet IP Adapter Mask Warning

src/diffusers/models/transformers/transformer_sd3.py
Check https://huggingface.slack.com/archives/C065E480NN9/p1718228629552419
FYI @apolinario
=> fix warning log for Transformer SD3

src/diffusers/pipelines/auto_pipeline.py
Only T2I as that appears to be all that's supported.
CC @yiyixuxu
=> Add Hunyuan AutoPipe mapping

src/diffusers/models/attention_processor.py, utils/update_metadata.py
Duplicate codes in SD3's JointAttnProcessor have been corrected.
Fixes #8515 
=> Fix duplicate variable assignments in SD3's JointAttnProcessor

setup.py, src/diffusers/dependency_versions_table.py
Reference: https://github.com/huggingface/diffusers/issues/8494#issuecomment-2166419905
=> pin accelerate to 0.31.0

docker/diffusers-doc-builder/Dockerfile, docker/diffusers-flax-cpu/Dockerfile, docker/diffusers-flax-tpu/Dockerfile, docker/diffusers-onnxruntime-cpu/Dockerfile, docker/diffusers-onnxruntime-cuda/Dockerfile, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile
Numpy 2.0.0 update is breaking the CI. Pin it temporarily so that the fast tests can pass. 
=> Temporarily pin Numpy in the CI

docs/source/en/training/controlnet.md
Syntax error pipe -> pipeline
Syntax error in readme example "pipe" -> "pipeline"
=> Syntax error in readme example "pipe" -> "pipeline"

examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py, src/diffusers/training_utils.py
Follow-up of https://github.com/huggingface/diffusers/pull/8528. Thanks to @Slickytail for contributing the functional weighting schemes generously.
=> [SD3 training] refactor the density and weighting utilities.

docs/source/en/training/text2image.md
A backslash is missing from the run command
=> A backslash is missing from the run command

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md, src/diffusers/models/autoencoders/autoencoder_tiny.py
Refer to https://github.com/huggingface/diffusers/pull/8607#discussion_r1643483268. 
@madebyollin FYI.
=> [Core] Add `shift_factor` to SD3 tiny autoencoder

src/diffusers/loaders/single_file_utils.py
fix https://github.com/huggingface/diffusers/issues/8546
=> fix from_single_file for checkpoints with t5

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py
Fixes the typo of doc_string in pipelines StableDiffusion3
=> Fix Typo in StableDiffusion3

src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py
Fixes Pillow import from this [comment](https://github.com/huggingface/diffusers/issues/8638#issuecomment-2178981546)  in the `StableDiffusionXLControlNetInpaintPipeline` example.
=> [docs] Fix Pillow import

scripts/convert_sd3_to_diffusers.py
fix https://github.com/huggingface/diffusers/issues/8588
=> add sd3 conversion script

src/diffusers/models/autoencoders/vq_model.py, src/diffusers/models/vq_model.py
Similar to https://github.com/huggingface/diffusers/pull/8698.
=> [Chore] perform better deprecation for vqmodeloutput

tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py, tests/pipelines/kandinsky/test_kandinsky_combined.py, tests/pipelines/latent_consistency_models/test_latent_consistency_models_img2img.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py, tests/pipelines/stable_diffusion_adapter/test_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/test_pipelines_common.py
Fixes for various precision related issues in the slow pipeline tests.
=> [Tests] Fix precision related issues in slow pipeline tests

utils/fetch_torch_cuda_pipeline_test_matrix.py
To further help with debugging issues with the slow test CI, we should ensure that the pipeline slow tests are run in the same order every time. 
This PR sorts the fetched pipeline matrix alphabetically so that jobs are executed in the same order. 
=> Enforce ordering when running Pipeline slow tests 

docs/source/en/using-diffusers/other-formats.md
In the loading locally section `snapshot_download` is using `allowed_patterns` as an argument. It should be `allow_patterns` 
=> Fix mistake in Single File Docs page

src/diffusers/models/attention_processor.py
Fixes what is failing in https://github.com/huggingface/diffusers/pull/8796
Related to https://github.com/huggingface/diffusers/pull/8796.
=> Fix the `added_proj_bias` default value

src/diffusers/models/autoencoders/autoencoder_kl.py
Enable tiling in the SD3 AutoencoderKL model. 
#8788
=> Add VAE tiling option for SD3

src/diffusers/models/embeddings.py
fix code annotation
The dimension of the vector returned by get_1d_rotary_pos_embed changes with the variation of the use_real variable.
=> [fix code annotation] Adjust the dimensions of the rotary positional embedding.

utils/fetch_torch_cuda_pipeline_test_matrix.py
Latest version of the hub api removes the `ModelFilter` object. This breaks our pipeline fetching script in the CI for the slow/nightly tests. Updating to the script to work with the latest hub version
=> Update pipeline test fetcher

docs/source/en/tutorials/basic_training.md
=> Added Code for Gradient Accumulation to work for basic_training

src/diffusers/pipelines/audioldm2/pipeline_audioldm2.py
Fixes failing AudioLDM2 test as [reported](https://huggingface.slack.com/archives/C03HBN1C8CW/p1721873385289799) by @sayakpaul.
=> [AudioLDM2] Fix cache pos for GPT-2 generation

src/diffusers/models/transformers/auraflow_transformer_2d.py
Removes all "i"s from AuraFlow. Residual from debugging, sorry.
=> [Chore] remove all is from auraflow.

.github/workflows/nightly_tests.yml
Placed `max-parallel` argument in the wrong location. Fixing it here. 
=> [CI] Fix parallelism in nightly tests

.github/workflows/nightly_tests.yml
=> [CI] Nightly Test Runner explicitly set runner for Setup Pipeline Matrix 

src/diffusers/pipelines/pia/pipeline_pia.py
=> [docs] fix pia example

.github/workflows/nightly_tests.yml
=> Fix Nightly Deps

docs/source/en/using-diffusers/controlnet.md
This should be the possessive form, not a contraction.
=> Fix grammar mistake.

examples/dreambooth/train_dreambooth_lora_sd3.py
=> fix train_dreambooth_lora_sd3.py loading hook

docs/source/en/api/pipelines/stable_audio.md
=> Fix a dead link

examples/text_to_image/train_text_to_image_lora_sdxl.py
Fixes a typo in sdxl lora example : )
=> Errata - fix typo

docs/source/en/training/distributed_inference.md
=> Update distributed_inference.md to include a fuller example on distributed inference

src/diffusers/pipelines/stable_diffusion_k_diffusion/pipeline_stable_diffusion_k_diffusion.py
If Karras is not enabled, a device inconsistency error will occur. This is due to the fact that sigmas were not moved to the specified device. This PR fixed this issue
=> fix(pipeline): k sampler sigmas device

docs/source/en/api/pipelines/controlnet_sd3.md, docs/source/en/api/pipelines/kolors.md, docs/source/en/api/pipelines/pag.md, examples/dreambooth/README_flux.md, src/diffusers/pipelines/latte/pipeline_latte.py, src/diffusers/pipelines/lumina/pipeline_lumina.py
This pull request fixes the CPU offloading usage in the code. It ensures that the CPU offloading is used correctly and optimizes memory consumption. And, some errata.
@stevhliu
=> [`Docs`] Fix CPU offloading usage

tests/models/transformers/test_models_transformer_lumina.py
Improves test suite coverage for Lumina
Part of https://github.com/huggingface/diffusers/issues/8907
@DN6 @sayakpaul
Not all of my tests are passing
I am facing dimension issues:
Can someone help me with it please.
Thanks
=> [Tests] Improve transformers model test suite coverage - Lumina

examples/textual_inversion/README.md
=> Add loading text inversion

.github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml
Adds `fail-fast=False` to torch cuda tests to prevent other tests from being cancelled if there's an issue with another test in the matrix. 
=> [CI] Add `fail-fast=False` to CUDA nightly and slow tests

src/diffusers/pipelines/pipeline_loading_utils.py
fix a regression introduced in https://github.com/huggingface/diffusers/pull/8967
thanks @a-r-r-o-w for cathing it!
=> fix _identify_model_variants

src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py
Note: Merge PR: https://github.com/huggingface/diffusers/pull/9243 before merging this one since the only single file pipeline checkpoints out now seem to be from Comfy. 
=> [Single File] Add Flux Pipeline Support 

.github/workflows/push_tests.yml
=> [CI] Run Fast + Fast GPU Tests on release branches. 

src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py
https://github.com/huggingface/diffusers/blob/2d9ccf39b53325d95036776df0a8acfc39352256/src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_combined.py#L550
This should be:
```python
image = [image] if isinstance(image, PIL.Image.Image) else image
```
---
=> Bugfix in `pipeline_kandinsky2_2_combined.py`: Image type check mismatch

.github/workflows/release_tests_fast.yml
Create dedicated workflow for release tests. 
=> [CI] Update Release Tests

.github/workflows/nightly_tests.yml
Some of our nightly tests are failing because they cannot access gates repos. Update the HF Token in the nightly runner to use the new Diffuser CI Bot Token which does have access to these repos. 
=> [CI] Update Hub Token on nightly tests

.github/workflows/push_tests.yml
=> [CI] Add option to dispatch Fast GPU tests on main 

src/diffusers/models/controlnet_sd3.py
Fix the bug of sd3 controlnet training when using gradient checkpointing. Please refer to the issue #9496.
=> Fix the bug of sd3 controlnet training when using gradient checkpointing.

docs/source/en/api/pipelines/text_to_video_zero.md, docs/source/en/optimization/coreml.md
Fix the issue https://github.com/huggingface/diffusers/issues/9471#issue-2536677047 
cc: @stevhliu
=> [Doc] Fix path and and also import imageio

docs/source/en/_toctree.yml, docs/source/en/training/distributed_inference.md
Adds doc about model sharding (selectively loading/unloading components, `device_map`) based on @sayakpaul's write up!
=> [docs] Model sharding

docs/source/en/api/schedulers/overview.md, src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
This PR extends #9509 to other schedulers where `use_karras_sigmas` is supported, and updates the documentation.
cc @asomoza @yiyixuxu
=> Add beta sigmas to other schedulers and update docs

docs/source/en/optimization/xdit.md
Fixed xDiT document image damage
@stevhliu and @sayakpaul
=> [docs] Fix xDiT doc image damage

tests/lora/utils.py
Refer to https://github.com/huggingface/diffusers/pull/9608#issuecomment-2408698645
Cc: @a-r-r-o-w
=> [Tests] increase transformers version in `test_low_cpu_mem_usage_with_loading`

setup.py
Only pinned until we figure out what's going on with torch 2.5.0
Context: https://huggingface.slack.com/archives/C065E480NN9/p1729230272869569
#9691, #9704
- https://github.com/huggingface/diffusers/actions/runs/11398910363/job/31721831848?pr=9691
- https://github.com/huggingface/diffusers/actions/runs/11398910363/job/31721832317?pr=9691
=> [CI] pin max torch version to fix CI errors

docker/diffusers-onnxruntime-cuda/Dockerfile, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile
See here: https://github.com/huggingface/diffusers/pull/9720#issuecomment-2424590210
=> [Docker] pin torch versions in the dockerfiles.

docs/source/en/api/pipelines/controlnet_flux.md
=> [Docs] docs to xlabs controlnets.

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
=> [Docs] fix docstring typo in SD3 pipeline

examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py
=> [Fix] train_dreambooth_lora_flux_advanced ValueError: unexpected save model: <class 'transformers.models.t5.modeling_t5.T5EncoderModel'>

docs/source/en/api/pipelines/controlnet_sd3.md
[ControlNet with Stable Diffusion 3](https://huggingface.co/docs/diffusers/en/api/pipelines/controlnet_sd3) documentation is missing [Depth ControlNet](https://huggingface.co/InstantX/SD3-Controlnet-Depth) from the InstantX team. Since it already have other 3 ControlNet by InstantX team.  Could you please add the last missing one? Someone might look for depth control for sd3, like me.
Docs: @stevhliu and @sayakpaul
=> add depth controlnet sd3 pre-trained checkpoints to docs

docs/source/en/api/pipelines/flux.md
=> [Docs] add: missing pipelines from the spec.

docs/source/en/api/pipelines/cogvideox.md
The CogVideoX docs seem to not be rendered properly
=> [docs] Fix CogVideoX table

src/diffusers/pipelines/allegro/pipeline_allegro.py, src/diffusers/pipelines/pag/pipeline_pag_pixart_sigma.py, src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py, src/diffusers/pipelines/pixart_alpha/pipeline_pixart_sigma.py
=> Fix multi-prompt inference

src/diffusers/pipelines/stable_audio/pipeline_stable_audio.py
Quick follow up for #10109 - [workflow didn't run](https://github.com/huggingface/diffusers/pull/10109/checks) on the PR so `make style` issues missed.
=> Fix `pipeline_stable_audio` formating

src/diffusers/models/attention_processor.py
fix https://github.com/huggingface/diffusers/issues/10025#issuecomment-2518335274
=> pass attn mask arg for flux

docs/source/en/using-diffusers/loading_adapters.md
As discussed on [Slack](https://huggingface.slack.com/archives/C03UQJENJTV/p1732000519909929), this PR adds docs about `load_lora_adapter`.
=> [docs] load_lora_adapter

tests/single_file/test_stable_diffusion_upscale_single_file.py
https://github.com/huggingface/diffusers/actions/runs/12170808354/job/33946510373#step:6:2722
Should close https://github.com/huggingface/diffusers/issues/7334
=> [Tests] xfail incompatible SD configs.

docs/source/en/api/models/autoencoder_dc.md, src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, tests/single_file/test_model_autoencoder_dc_single_file.py
=> [Single File] Add single file support for AutoencoderDC

.github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml
=> Ci update tpu

examples/community/README_community_scripts.md, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
Fixes #9906
@yiyixuxu @asomoza
=> Remove `negative_*` from SDXL callback

.github/workflows/push_tests.yml
Missed a formatting issue on the push_test.yml PR: #10197. 
=> Fix format issue in push_test yml

src/diffusers/pipelines/controlnet/pipeline_controlnet_union_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl_img2img.py
=> Fix ControlNetUnion _callback_tensor_inputs

src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet.py
Non-human subjects are preferable for examples.
ControlNet Image
Output (prompt = `A bird in space`)
=> Use non-human subject in StableDiffusion3ControlNetPipeline example

src/diffusers/pipelines/cogview3/pipeline_cogview3plus.py
Checkpoint is `THUDM/CogView3-Plus-3B` not `THUDM/CogView3Plus-3B`
=> Fix checkpoint in CogView3PlusPipeline example

examples/community/regional_prompting_stable_diffusion.py
Fixes https://github.com/huggingface/diffusers/pull/9874#issuecomment-2543158403
Hi
I apologize for the issue. 
There's a bug in my code where an error occurs when prompts is a `str` and negative_prompts is a `list` due to a typo I made.
I've fixed the affected line.
=> [Community Pipeline] Fix typo that cause error on regional prompting pipeline

src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/models/transformers/transformer_mochi.py
=> [Single File] Add single file support for Mochi Transformer

tests/lora/test_lora_layers_flux.py
Forgot to club in https://github.com/huggingface/diffusers/pull/10259
=> [Tests] add integration tests for lora expansion stuff in Flux.

.github/workflows/push_tests_mps.yml
https://github.com/huggingface/diffusers/actions/runs/12434081176/job/34717003928#step:5:36
=> Fix push_tests_mps.yml

src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/models/transformers/transformer_hunyuan_video.py
- Add single file support support for hunyuan. 
- Change passing revision to `load_config` and instead use `config_revision` option. This is because revision is passed to both the checkpoint downloading and config downloading steps. But if you're downloading a checkpoint from one repo and loading the config from another there is a mismatch. Since we haven't shipped revision for configs yet, this is a safe change. 
=> [Single File] Add Single File support for HunYuan video

src/diffusers/loaders/single_file_utils.py
Made a mistake while merging single file for Hunyuan which is breaking SF loading. 
=> [Single File] Fix loading

tests/lora/utils.py
Fixes https://github.com/huggingface/diffusers/actions/runs/12461857058/job/34781970659#step:6:6619.
=> [LoRA] test fix

.github/workflows/pypi_publish.yaml
Context: https://huggingface.slack.com/archives/C065E480NN9/p1734969425280119?thread_ts=1734948562.680789&cid=C065E480NN9
=> fix test pypi installation in the release workflow

docs/source/en/community_projects.md
Added [model search](https://github.com/huggingface/diffusers/tree/main/examples/model_search) to the Community Projects section of the documentation
cc: @stevhliu
=> [Docs] Added `model search` to community_projects.md

docs/source/en/api/pipelines/hunyuan_video.md, docs/source/en/api/pipelines/hunyuandit.md
Fixes Broken links in `hunyuandit.md` and `hunyuan_video.md` 
Fixes #10375 
@sayakpaul
=> [Fix] Broken links in hunyuan docs

src/diffusers/models/transformers/sana_transformer.py
This PR fix the Positional Embedding bug for Sana 1K and 2K models
Cc: @yiyixuxu @a-r-r-o-w @sayakpaul
=> [Sana] 1k PE bug fixed

src/diffusers/models/embeddings.py
=> fix bug for ascend npu

examples/community/rerender_a_video.py
@hlky I have to create a different pr for rerender a video py. Please review and merge the pr.
=> add pythor_xla support for render a video

examples/community/rerender_a_video.py
=> Update rerender_a_video.py fix dtype error

docs/source/en/api/models/allegro_transformer3d.md, docs/source/en/api/models/cogvideox_transformer3d.md, docs/source/en/api/models/cogview3plus_transformer2d.md, docs/source/en/api/models/mochi_transformer3d.md
=> Update variable names correctly in docs

.github/workflows/nightly_tests.yml, .github/workflows/release_tests_fast.yml
Typo in the test command is preventing the tests from running.  
=> [CI] Torch Min Version Test Fix

src/diffusers/schedulers/scheduling_ddim_inverse.py
Changed the number of the referenced table from 1 to 2 in a comment of the set_timesteps() method of the DDIMInverseScheduler class (also according to the description of the 'timestep_spacing' attribute of its __init__ method).
@stevhliu
=> Typo fix in the table number of a referenced paper 

src/diffusers/pipelines/flux/pipeline_flux.py, tests/pipelines/flux/test_pipeline_flux.py
As discussed here: https://github.com/huggingface/diffusers/pull/10531#discussion_r1911873151.
=> [Flux] Improve true cfg condition

src/diffusers/pipelines/auto_pipeline.py
This PR adds `SanaPipeline` and `SanaPAGPipeline` into `AutoPipelineForText2Image`
Cc: @yiyixuxu @a-r-r-o-w
=> [Sana] add Sana to auto-text2image-pipeline;

.github/workflows/push_tests.yml
The current token in the Fast GPU tests cannot access gates repos. Switch to  the Diffusers CI Bot Token that does have gated read access.  
=> [CI] Update HF Token in Fast GPU Tests 

examples/dreambooth/train_dreambooth_lora_sana.py
Add vae tiling option to avoid OOM
Without vae tiling, memory will significantly increase and break the process during validation process, if the memory is not enough
=> [Sana 4K] Add vae tiling option to avoid OOM

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md
Updated ip_adapter model_id to [guiyrt/InstantX-SD3.5-Large-IP-Adapter-diffusers](https://huggingface.co/guiyrt/InstantX-SD3.5-Large-IP-Adapter-diffusers), so that the example is in working state while #9966 is open.
@hlky @yiyixuxu
=> [Docs] Update SD3 ip_adapter model_id to diffusers checkpoint

examples/text_to_image/train_text_to_image_lora.py
We already set the unet to requires grad false at line 506 
=> removing redundant requires_grad = False

src/diffusers/schedulers/scheduling_ddpm.py
Adds sigmoid scheduler in docs
@stevhliu and @sayakpaul
=> Add sigmoid scheduler in `scheduling_ddpm.py` docs

src/diffusers/pipelines/lumina/pipeline_lumina.py
=> fix check_inputs func in LuminaText2ImgPipeline

src/diffusers/pipelines/aura_flow/pipeline_aura_flow.py
Fixes #10673  check_inputs function in Auraflow Pipeline
@yiyixuxu
=> [FIX] check_inputs function in Auraflow Pipeline

docs/source/en/using-diffusers/img2img.md
As previously discussed, I have updated the documentation to ensure it works correctly. Please let me know if any improvements are needed and I will make the necessary changes.
Fixes #9566 
@stevhliu
=> Fix Documentation about Image-to-Image Pipeline

docs/source/en/using-diffusers/img2img.md, examples/community/README.md
I've added 4 notebooks for the community scripts and are linked to the ReadMe as per advice given in #9905. I have also made some changes to the example scripts to ensure that they work.
Please let me know if any further corrections are needed and I will make the necessary changes.
@stevhliu
=> Notebooks for Community Scripts-6

src/diffusers/pipelines/pipeline_loading_utils.py, src/diffusers/pipelines/pipeline_utils.py
A follow up of this pr https://github.com/huggingface/diffusers/pull/10661
Not sure if my update is correct, feel free to fix!
=> add provider_options in from_pretrained

.github/workflows/trufflehog.yml
Truffle Hog check is failing because of it's catching an unverified token in our staging test. The token only works in staging environment, so it's safe to leave it here. 
=> [CI] Fix Truffle Hog failure

docs/source/en/training/custom_diffusion.md
Fixes #10791
This PR updates the Custom Diffusion documentation to correctly demonstrate multiple concept inference
- Initializing the pipeline from a proper foundation model (e.g., "CompVis/stable-diffusion-v1-4") instead of a fine-tuned model.
- Defining model_id explicitly to avoid NameError.
- Correcting method calls for loading attention processors and textual inversion embeddings.
@stevhliu and @sayakpaul
=> Update Custom Diffusion Documentation for Multiple Concept Inference to resolve issue #10791

src/diffusers/pipelines/lumina2/pipeline_lumina2.py
Fixes #10782  check_inputs function in Lumina2 Pipeline
@yiyixuxu
=> [FIX] check_inputs function in lumina2

src/diffusers/loaders/lora_conversion_utils.py
Fixes: https://github.com/huggingface/diffusers/issues/10562.
=> [LoRA] improve lora support for flux.

examples/README.md, examples/community/README.md
I've added 6 notebooks for the community scripts and are linked to the ReadMe as per advice given in https://github.com/huggingface/diffusers/pull/9905. I also made some changes to the example scripts to ensure that they work and filled in the missing notebook links for the examples ReadMe.
Please let me know if any further corrections are needed and I will make the necessary changes.
@stevhliu
=> Notebooks for Community Scripts-7

src/diffusers/__init__.py, src/diffusers/pipelines/auto_pipeline.py, src/diffusers/utils/dummy_torch_and_transformers_objects.py
=> Add SD3 ControlNet to AutoPipeline

examples/dreambooth/train_dreambooth_lora_sdxl.py
=> [Fix] fp16 unscaling in train_dreambooth_lora_sdxl

docs/source/en/_toctree.yml
CI is complaining about a sorting issue in the toctree. It's leading to the quality checks failing on other PRs. 
https://github.com/huggingface/diffusers/actions/runs/13506488502/job/37737141072?pr=10859
Just ran make style on it to fix. 
=> [Docs] Fix toctree sorting 

.github/workflows/pr_style_bot.yml
Ensure only admins can trigger the style bot. 
=> [CI] Update Stylebot Permissions

src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_inpaint.py
Applies `make fix-copies` to prevent the following:
https://github.com/huggingface/diffusers/actions/runs/13622290017/job/38073697477?pr=10909
=> [chore] fix-copies to flux pipelines

examples/dreambooth/train_dreambooth_lora.py
Part of #8384
* Fixed LR schedulers when `num_train_epoch` is passed on distributed training environment for `train_dreambooth_lora.py` 
@sayakpaul
=> [train_dreambooth_lora.py] Fix the LR Schedulers when `num_train_epochs` is passed in a distributed training env

.github/workflows/pr_tests.yml
Otherwise, the PRs will only trigger tests when there are changes on the PRs not when the PRs are opened
=> [CI] remove synchornized.

src/diffusers/loaders/ip_adapter.py
=> Fix SD3 IPAdapter feature extractor

src/diffusers/pipelines/flux/pipeline_flux_controlnet.py
https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Canny
Add base_model config.
=> Fix pipeline_flux_controlnet.py

src/diffusers/pipelines/wan/pipeline_wan_i2v.py
=> WanI2V encode_image

tests/quantization/bnb/test_mixed_int8.py
pytest -rA tests/quantization/bnb/test_mixed_int8.py::BnB8bitTrainingTests::test_training **pass**
=> enable 1 case on XPU

docs/source/en/api/pipelines/sana_sprint.md
Just a minor update to change the title.
@yiyixuxu FYI.
=> minor update to sana sprint docs.

docs/source/en/using-diffusers/loading.md
=> [docs] minor updates to dtype map docs.

docs/source/en/_toctree.yml, docs/source/en/api/models/auto_model.md
=> [docs] AutoModel

src/diffusers/utils/import_utils.py
https://github.com/huggingface/diffusers/issues/11267
=> add onnxruntime-qnn & onnxruntime-cann

src/diffusers/loaders/single_file_utils.py
=> Fix LTX 0.9.5 single file

docs/source/en/community_projects.md
As discussed in https://github.com/huggingface/diffusers/discussions/11158#discussioncomment-12681691
cc @stevhliu
=> Add `skrample` section to `community_projects.md`

docs/source/en/api/loaders/lora.md, utils/check_support_list.py
Fix LoRA regex so that all LoraLoaderMixins can be documented.
=> [chore] fix lora docs utils

src/diffusers/models/transformers/transformer_hidream_image.py
fix https://github.com/huggingface/diffusers/issues/11362
=> update output for Hidream transformer

src/diffusers/models/transformers/transformer_hidream_image.py, src/diffusers/pipelines/hidream_image/pipeline_hidream_image.py
fix https://github.com/huggingface/diffusers/issues/11382
=> [HiDream] move deprecation to 0.35.0

docs/source/en/api/pipelines/flux.md
IP-Adapter example had a wrong argument. Fix `true_cfg` -> `true_cfg_scale`
=> Fix Flux IP adapter argument in the pipeline example

examples/text_to_image/train_text_to_image_lora.py
=> [train_text_to_image_lora] Better image interpolation in training scripts follow up

examples/dreambooth/train_dreambooth_lora_hidream.py
=> [Hi-Dream LoRA] fix bug in validation

examples/controlnet/train_controlnet_flux.py
=> Set LANCZOS as the default interpolation for image resizing in ControlNet training

src/diffusers/pipelines/stable_diffusion/__init__.py
moved the pipelines that are no longer in this folder
=> clean up the __Init__ for stable_diffusion

src/diffusers/models/transformers/transformer_cosmos.py
See: https://huggingface.slack.com/archives/C065E480NN9/p1746711026447089
=> Conditionally import torchvision in Cosmos transformer

src/diffusers/pipelines/audioldm2/pipeline_audioldm2.py
https://github.com/huggingface/transformers/pull/36719/ broke the AudioLDM2 tests:
https://github.com/huggingface/diffusers/actions/runs/14898116106/job/41844553322?pr=11508#step:6:34900
This PR fixes that.
Cc: @eustlb
=> [tests] fix audioldm2 for transformers main.

examples/research_projects/diffusion_orpo/train_diffusion_orpo_sdxl_lora_wds.py
Fix small typo in LR scaling code
replace 'args.learning_rat' with 'args.learning_rate'
Anyone
=> Fix typo in train_diffusion_orpo_sdxl_lora_wds.py

docs/source/en/using-diffusers/inpaint.md
=> Doc update

src/diffusers/loaders/single_file_utils.py
Fix single file loading for LTX 0.9.7 transformer model if a VAE isn't present in the checkpoint. GGUF versions of the checkpoint don't have a VAE.  
#11574
=> [Single File] Fix loading for LTX 0.9.7 transformer

src/diffusers/pipelines/pipeline_utils.py
Pipeline type annotations with List type do not show up in expected type because the check for `inspect.isclass(v.annotation)` cannot handle nested annotated types such as `List[float]`. 
This results in a an error when running the following check for expected types:
https://github.com/huggingface/diffusers/blob/375ec930863ee74d0a0d5209f5627a5c89c752c2/src/diffusers/pipelines/pipeline_utils.py#L1025 
The expected key isn't present during the check. 
This PR: 
- Updates `_get_signature_types` to account for List and Dict type annotations.        
Anyone in the …
=> Type annotation fix

src/diffusers/models/transformers/transformer_flux.py
=> removing unnecessary else statement

docs/source/en/quantization/torchao.md
Benchmarking script: https://gist.github.com/sayakpaul/155a199ebfd10a2751266143611f6e1c.
Cc: @a-r-r-o-w @drisspg
=> [docs] mention fp8 benefits on supported hardware.

examples/dreambooth/train_dreambooth_lora_hidream.py
add deepspeed support to lora hidream
=> [training] add ds support to lora hidream

src/diffusers/pipelines/hidream_image/pipeline_hidream_image.py, src/diffusers/pipelines/hidream_image/pipeline_output.py
=> Add missing HiDream license

src/diffusers/pipelines/ltx/pipeline_ltx_latent_upsample.py
Missing `model_cpu_offload_seq` class attribute in pipeline
https://github.com/huggingface/diffusers/actions/runs/15748061998/job/44388052120#step:7:756
=> Fix failing cpu offload test for LTX Latent Upscale

src/diffusers/pipelines/wan/pipeline_wan_vace.py
Fixes #11779 
- [ x ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ x ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
=> [Wan] Fix mask padding in Wan VACE pipeline.

src/diffusers/pipelines/omnigen/pipeline_omnigen.py, src/diffusers/pipelines/omnigen/processor_omnigen.py
Fix https://github.com/huggingface/diffusers/actions/runs/15850715220/job/44683243046#step:7:251
=> guard omnigen processor.

tests/pipelines/test_pipelines_common.py
- CogVideo: https://github.com/huggingface/diffusers/actions/runs/15975958887/job/45058560527
- CogView4: https://github.com/huggingface/diffusers/actions/runs/15975958887/job/45058560535#step:7:238
- Hunyuan: https://github.com/huggingface/diffusers/actions/runs/15975958887/job/45058560644#step:7:883
- Wan: https://github.com/huggingface/diffusers/actions/runs/15975958887/job/45058560915#step:7:900
- Sana:  https://github.com/huggingface/diffusers/actions/runs/15975958887/job/45058560604#step:7:785
=> [tests] Fix failing float16 cuda tests

docs/source/en/api/pipelines/amused.md, docs/source/en/api/pipelines/attend_and_excite.md, docs/source/en/api/pipelines/audioldm.md, docs/source/en/api/pipelines/blip_diffusion.md, docs/source/en/api/pipelines/controlnetxs.md, docs/source/en/api/pipelines/controlnetxs_sdxl.md, docs/source/en/api/pipelines/dance_diffusion.md, docs/source/en/api/pipelines/diffedit.md, docs/source/en/api/pipelines/i2vgenxl.md, docs/source/en/api/pipelines/musicldm.md, docs/source/en/api/pipelines/paint_by_example.md, docs/source/en/api/pipelines/panorama.md, docs/source/en/api/pipelines/pia.md, docs/source/en/api/pipelines/self_attention_guidance.md, docs/source/en/api/pipelines/semantic_stable_diffusion.md, docs/source/en/api/pipelines/stable_diffusion/gligen.md, docs/source/en/api/pipelines/stable_diffusion/k_diffusion.md, docs/source/en/api/pipelines/stable_diffusion/ldm3d_diffusion.md, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_safe.md, docs/source/en/api/pipelines/text_to_video.md, docs/source/en/api/pipelines/text_to_video_zero.md, docs/source/en/api/pipelines/unclip.md, docs/source/en/api/pipelines/unidiffuser.md, docs/source/en/api/pipelines/wuerstchen.md
Adds a warning for deprecated pipelines
=> [docs] Deprecated pipelines

examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py
I broke the style test in this PR https://github.com/huggingface/diffusers/pull/10011/files
=> fix style 

docs/source/en/index.md
Updates `index.md` since we've moved a bit away from the older layout of tutorials/guides/conceptual guides/reference.
=> [docs] Update index

.github/workflows/mirror_community_pipeline.yml, src/diffusers/commands/fp16_safetensors.py
Somehow I missed two files from the changes made in #11994
There shouldn't be anymore `huggingface-cli` commands.
=> [Fix] huggingface-cli to hf missed files

.github/workflows/benchmark.yml, .github/workflows/nightly_tests.yml, .github/workflows/pr_tests_gpu.yml, .github/workflows/push_tests.yml, .github/workflows/release_tests_fast.yml
Propagate @paulinebm's https://github.com/huggingface/diffusers/pull/12059.
=> enable all gpus when running ci.

.github/workflows/nightly_tests.yml, .github/workflows/pr_tests_gpu.yml, .github/workflows/push_tests.yml, .github/workflows/release_tests_fast.yml, .github/workflows/run_tests_from_a_pr.yml
Was missed in the previous PR. My bad.
=> fix the rest for all GPUs in CI

src/diffusers/pipelines/audioldm2/pipeline_audioldm2.py, tests/pipelines/audioldm2/test_audioldm2.py
Check https://github.com/huggingface/diffusers/actions/runs/16741781555/job/47391568164?pr=12027#step:6:32090
=> [tests] deal with the failing AudioLDM2 tests

tests/quantization/gguf/test_gguf.py
@DN6 @a-r-r-o-w , pls help review, thx very much.
=> make test_gguf all pass on xpu

docs/source/en/quicktour.md
Adds link to https://huggingface.co/spaces/diffusers/optimized-diffusers-code in the Quickstart, one of our highest vis pages :)
=> [docs] Optimized code snippets

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/custom_pipeline_overview.md
Refreshes the community pipeline docs by removing some of the bloat from it.
=> [docs] Community pipelines

src/diffusers/models/transformers/transformer_qwenimage.py
Harmless change to take advantage of methods like `set_attn_processor()`.
@naykun okay with you?
=> add attentionmixin to qwen image

docs/source/en/tutorials/using_peft_for_inference.md
Fix formatting in using_peft_for_inference.md
=> Fix typo in LoRA

tests/quantization/quanto/test_quanto.py
Quanto Tests are running twice (once in quantization tests and once in big GPU tests). The tests don't need the big gpu since they use the tiny flux model for testing. Removing the requirement. 
=> [CI] Remove big accelerator requirements from Quanto Tests

src/diffusers/models/transformers/transformer_wan_vace.py
This PR enables `WanVACETransformer3DModel` to use methods from `AttentionMixin`, such as `set_attn_processor()`.
#12186 
I would like to express my sincere gratitude to the Hugging Face team for your continuous efforts, which make it easier and faster for researchers and developers to enjoy deep learning every day.
At your convenience, I would be grateful if you could review this, @DN6
=> Add AttentionMixin to WanVACETransformer3DModel

docs/source/en/api/pipelines/cogvideox.md, docs/source/en/api/pipelines/hunyuan_video.md, docs/source/en/using-diffusers/text-img2vid.md
Companion docs to #12234 to update examples with single model on pipeline-level quantization
=> [docs] components_to_quantize

examples/text_to_image/requirements.txt, examples/text_to_image/requirements_sdxl.txt
Fixes #12433  Fixes Text to image training peft version
@stevhliu @sayakpaul
=> [FIX] Text to image training peft version
