huggingface/diffusers

tests/models/unets/test_models_unet_controlnetxs.py
tests/models/unets/test_models_unet_controlnetxs.py::UNetControlNetXSModelTests::test_forward_no_control seems to be a little flaky. So, mark it as one. 
Reference:
https://github.com/huggingface/diffusers/actions/runs/8815084068/job/24196330530?pr=7767#step:8:3336
=> [Tests] mark UNetControlNetXSModelTests::test_forward_no_control to be flaky

src/diffusers/pipelines/auto_pipeline.py
Changes the PixArt auto pipeline mappings from
```python
("pixart", PixArtAlphaPipeline)
```
to
```python
("pixart-alpha", PixArtAlphaPipeline)
("pixart-sigma", PixArtSigmaPipeline)
```
I verified correct detection locally on my diffusers CLI.
@yiyixuxu
=> Add PixArtSigmaPipeline to AutoPipeline mapping

docs/source/en/using-diffusers/ip_adapter.md
Adds an example of image masking using multiple masks for a single IP Adapter and fixes Face ID examples
- Docs: @stevhliu @sayakpaul @yiyixuxu
=> [Docs] Update image masking and face id example

examples/text_to_image/README.md, examples/text_to_image/train_text_to_image.py, src/diffusers/training_utils.py
A new function compute_dream_and_update_latents has been added to the training utilities that allows you to do DREAM rectified training in line with the paper https://arxiv.org/abs/2312.00210. The method can be used with an extra argument in the train_text_to_image.py script.
Ported from @RossM's webui MR with help from @RossM.
=> Add DREAM training

examples/community/clip_guided_stable_diffusion_img2img.py, examples/community/latent_consistency_img2img.py, examples/community/stable_diffusion_controlnet_img2img.py, examples/community/stable_diffusion_controlnet_inpaint_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, src/diffusers/pipelines/shap_e/pipeline_shap_e_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
=> Check for latents, before calling prepare_latents - sdxlImg2Img

src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
Fixes #[Issue](https://github.com/huggingface/diffusers/issues/7773#issuecomment-2078411517)
it should repeat latents before concatenate do_classifier_free_guidance latents to align with the CFG process after noise_pred.
@sayakpaul @yiyixuxu @DN6 
=> [Pipeline] Fix error of SVD pipeline when num_videos_per_prompt > 1

tests/pipelines/ddim/test_ddim.py
Reduces the model sizes in the DDIM fast tests.
Tagging Issue: https://github.com/huggingface/diffusers/issues/7677
CC: @sayakpaul for visibility.
=> [Tests] reduce the model size in the ddim fast test

tests/pipelines/ddpm/test_ddpm.py
Reduces the model sizes in the DDPM fast tests.
Tagging Issue: https://github.com/huggingface/diffusers/issues/7677
CC: @sayakpaul for visibility.
=> [Tests] reduce the model size in the ddpm fast test

examples/community/pipeline_demofusion_sdxl.py, src/diffusers/loaders/lora.py, src/diffusers/loaders/textual_inversion.py, src/diffusers/loaders/unet.py, src/diffusers/pipelines/dit/pipeline_dit.py, src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/pixart_alpha/test_pixart.py, tests/pipelines/pixart_sigma/test_pixart.py, tests/pipelines/test_pipelines_common.py
follow up on this https://github.com/huggingface/accelerate/issues/2701
when the sequential CPU offloading method is enabled for the pipeline, accelerate will try to install an `AlignDevicesHook` to each model component; if the model contains a buffer, it will install a `SequentialHook` with two `AlignDevicesHook`; 
currently, we assume that the model is sequentially offloaded only the hook is an `AlignDevicesHook.` In this PR I updated logic to include the scenario when`SequentialHook` is created
=> update the logic of `is_sequential_cpu_offload`

tests/pipelines/audioldm/test_audioldm.py
Reduces the model sizes in the AudioLDM fast tests.
Tagging Issue: https://github.com/huggingface/diffusers/issues/7677
CC: @sayakpaul for visibility.
=> [Tests] reduce the model size in the audioldm fast test

tests/pipelines/blipdiffusion/test_blipdiffusion.py
Reduces the model sizes in the BLIP-Diffusion fast tests.
Tagging Issue: https://github.com/huggingface/diffusers/issues/7677
CC: @sayakpaul for visibility.
=> [Tests] reduce the model size in the blipdiffusion fast test

src/diffusers/utils/peft_utils.py, tests/lora/test_lora_layers_sdxl.py
When using some LoRAs, for example [sd_xl_offset_example-lora_1.0.safetensors](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_offset_example-lora_1.0.safetensors) with blockwise scales we get this error:
```
RuntimeError: No LoRA weight found for module down_blocks.0.resnets.0.conv1
```
This PR makes it so if the layer is not found, it returns the weight (scale) of the block enabling the use of these LoRAs with blockwise scales.
e.g.,
```python
offset_scales = {
"unet": {
"down": {"block_1": [0.0, 0.5], "block_2": [1.0, 1.0]},
"mid": 1.0,
"up": {"block_0": [1.0, 1.0, 1.0], "block_1": [1.0, 1.0, 1.0]},
},
"text_encoder": 1.0,
"text_encoder_2": 1.0,
}
```
- If `down_blocks.0.resnets.0.conv1` is not found, returns the `scale` of `1.0` as a default.
- If …
=> Fix for "no lora weight found module" with some loras

src/diffusers/schedulers/scheduling_ddpm_flax.py
`model_output.shape` may only have rank 1.
There are warnings related to use of random keys.
```
tests/schedulers/test_scheduler_flax.py: 13 warnings
/Users/phillypham/diffusers/src/diffusers/schedulers/scheduling_ddpm_flax.py:268: FutureWarning: normal accepts a single key, but was given a key array of shape (1, 2) != (). Use jax.vmap for batching. In a future JAX version, this will be an error.
noise = jax.random.normal(split_key, shape=model_output.shape, dtype=self.dtype)
tests/schedulers/test_scheduler_flax.py::FlaxDDPMSchedulerTest::test_betas
/Users/phillypham/virtualenv/diffusers/lib/python3.9/site-packages/jax/_src/random.py:731: FutureWarning: uniform accepts a single key, but was given a key array of shape (1,) != (). Use jax.vmap for batching. In a future JAX version, this …
```
=> Check shape and remove deprecated APIs in scheduling_ddpm_flax.py

src/diffusers/pipelines/stable_cascade/pipeline_stable_cascade_combined.py, tests/pipelines/stable_cascade/test_stable_cascade_combined.py
currently, `StableCascadeCombinedPipeline` is missing  `_optional_components` so the combined pipeline is not able to get the correct list of expected modules, i.e. `_get_signature_keys` (https://github.com/huggingface/diffusers/blob/c1c42698c955959d7ef34af129428f64c6e363bf/src/diffusers/pipelines/pipeline_utils.py#L1555) will not include the optional components in `expected_modules`, which will then cause  errors in methods using this methods, such as `components` and `to`
this fix https://github.com/huggingface/diffusers/issues/7598
=> fix `_optional_components` in `StableCascadeCombinedPipeline`

src/diffusers/image_processor.py
part of https://github.com/huggingface/diffusers/pull/7776
the test only fails on cpu, so I ran test suits here https://github.com/huggingface/diffusers/pull/7903
=> fix test failure [part of video processor PR]

examples/text_to_image/train_text_to_image_sdxl.py
Adds NPU flash attention support for SDXL, similar to #7816
- Training examples: @sayakpaul
=> Add Ascend NPU support for SDXL.

src/diffusers/models/unets/unet_motion_model.py
Makes it possible to load a pipeline with an IP Adapter into an AnimateDiff pipeline with from_pipe()
Fixes #7661 
- Pipelines:  @sayakpaul @yiyixuxu @DN6
=> fix AnimateDiff creation with a unet loaded with IP Adapter

tests/lora/test_lora_layers_sdxl.py
Similar to https://github.com/huggingface/diffusers/pull/7899.
=> [LoRA] Fix LoRA tests (side effects of RGB ordering) part ii

.github/workflows/build_docker_images.yml
Similar to https://github.com/huggingface/peft/pull/1723/files.
@younesbelkada thanks and FYI.
=> update to use hf-workflows for reporting the Docker build statuses

.github/workflows/run_test_from_pr.yml
Currently, we manually run the SLOW tests for PRs where applicable to ensure the changed components are robust enough to merge. This is burdensome. 
How about a workflow that we can trigger with a few clicks and run the desired tests within our CI runner?
This PR adds such a workflow.
=> [Workflows] add a workflow that can be manually triggered on a PR.

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
Add `cross_attention_kwargs` to `__call__` method of `StableDiffusionInstructPix2PixPipeline`, which are passed to UNet.
Implements https://github.com/huggingface/diffusers/issues/7962 
Adding ability to pass custom cross-attention arguments for UNet. This allows all the same functionality with cross-attention manipulations as inside `StableDiffusionPipeline`: LoRAs, custom adapters, etc.
@sayakpaul @patil-suraj
=> Passing `cross_attention_kwargs` to `StableDiffusionInstructPix2PixPipeline`

docs/source/en/api/video_processor.md, src/diffusers/video_processor.py
Investigates why the `VideoProcessor` doc fails to build. I think it may have to do with how the `video` parameter is formatted in the docstring (related to #7937).
=> [docs] VideoProcessor

.github/workflows/benchmark.yml, .github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml, .github/workflows/push_tests_mps.yml, .github/workflows/update_metadata.yml
This PR defines the env variable [`HF_TOKEN`](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hftoken) instead of `HUGGING_FACE_HUB_TOKEN` in `diffusers`'s CI.  The later is not wrong but is now deprecated in favor of the first one. Goal is to be consistent everywhere in the HF ecosystem.
**NOTE: before merging this, a `HF_TOKEN` github secret must be added to the repo settings!**
=> Use HF_TOKEN env var in CI

src/diffusers/loaders/single_file_utils.py
File "/workspace/hbot-backend-anime/src/main.py", line 7, in <module>
from core import generate_anime_image
File "/workspace/hbot-backend-anime/src/core.py", line 18, in <module>
pipe = StableDiffusionPipeline.from_single_file("./anime/anyhentai.safetensors", torch_dtype=torch.float16, safety_checker=None,text_encoder=text_encoder)
File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/single_file.py", line 491, in from_single_file
loaded_sub_model = load_single_file_sub_model(
File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/single_file.py", line 100, in load_single_file_sub_model
loaded_sub_model …
=> fix: Attribute error in Logger object (logger.warning)

docs/source/en/api/pipelines/i2vgenxl.md
Adds additional information about 1-stage variant of I2VGen-XL model in the docs. 
PR submitted based on [this discussion](https://github.com/huggingface/diffusers/discussions/7952).
@sayakpaul
=> Add details about 1-stage implementation in I2VGen-XL docs

docs/source/en/using-diffusers/marigold_usage.md, src/diffusers/pipelines/marigold/marigold_image_processing.py
Add an example for using marigold depth prediction with controlnet.
Note: I only added  the `Depth Prediction with Controlnet` section, the rest of the changes were made with the `make style` automatically.
@toshas Feel free to add or change any text that you think will match better the overall style of the documentation.
@yiyixuxu @stevhliu @toshas
=> [docs] Add controlnet example to marigold

src/diffusers/loaders/lora.py, src/diffusers/loaders/lora_conversion_utils.py, src/diffusers/utils/state_dict_utils.py
Fixes https://github.com/huggingface/diffusers/issues/8237.
```python
import torch
pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")
pipe.load_lora_weights("sayakpaul/diffusers-8237-lora", weight_name="lora.safetensors", adapter_name="engraving")
lora_scale= 0.9
prompt = "Engravings Henri Meyer"
image = pipe(
prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
).images[0]
image
```
@BenjaminBossan I am seeing some unexpected warnings when running the above:
```bash
Loading adapter weights from None led to unexpected keys not found in the model:  ['text_projection.lora.down.weight', …
```
=> [LoRA] attempt at fixing onetrainer lora.

examples/community/kohya_hires_fix.py
Adds Kohya fix to Stable Diffusion pipeline. Fixes https://github.com/huggingface/diffusers/issues/7265.
Here is a minimal example to test the pipeline. You can disable the fix by setting with_high_res_fix to False which passes None to the pipline as high_res_fix argument.
```
import torch
generator = torch.manual_seed(42)
with_high_res_fix = True
high_res_fix = [{'timestep': 600, 'scale_factor': 0.5, 'block_num': 1}]
pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", 
custom_pipeline="/home/sajad/Desktop/hugging_face/diffusers/examples/community/kohya_hires_fix.py",
generator=generator,
torch_dtype=torch.float16, 
use_safetensors=True, 
high_res_fix=high_res_fix if with_high_res_fix else None) …
```
=> Add Kohya fix to SD pipeline for high resolution generation 

src/diffusers/utils/logging.py
Fix a recurring problem when using diffusers without console, e.g. using `pythonw.exe` in windows, since there's no `sys.stderr`.
I can make a more advanced solution like using a `FileHandler` instead if there's no `sys.stderr` but don't know if it's worth the effort here. Users should implement their own error handling for this.
Fixes #3290
=> Fix object has no attribute 'flush' when using without a console

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/image_quality.md, docs/source/en/using-diffusers/scheduler_features.md, docs/source/en/using-diffusers/schedulers.md
Continuation of #7817 (see comment [here](https://github.com/huggingface/diffusers/pull/7817#pullrequestreview-2048708715)) that refactors scheduler features for inference to their own doc. It includes:
- custom `timesteps` and `sigmas` showcasing AYS
- Karras sigmas
- `rescale_betas_zero_snr`
=> [docs] Scheduler features

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_alpha.py, src/diffusers/pipelines/pixart_alpha/pipeline_pixart_sigma.py
Fix PixArt-Sigma negative-prompt handling.
Prompt and negative_prompt can be either `str` or `list`.
Pipeline already correctly handles `prompt`, this makes sure that `negative_prompt` gets converted to list ONLY if its `str`, otherwise use it as-is.
Without this, if negative_prompt is already a list, pipeline creates list-of-lists and causes a RuntimeError later  in `text = text.lower().strip()` as list has no method `lower`.
=> fix pixart-sigma negative prompt handling

docs/source/en/training/dreambooth.md
Fixes #7734 where some training info for DeepFloyd IF got lost when I refactored the DreamBooth docs.
=> [docs] DeepFloyd training

examples/text_to_image/train_text_to_image_lora.py
In a distributed training scenario, passing the argument `--num_train_epochs` to any of the training scripts disrupts the functioning of the learning rate scheduler. Essentially, the learning rate decays `num_processes` times slower than expected. Related issues #8236, #3954, and PR #3983 shed further light on this.
In our training setup, we utilize `accelerator` instead of PyTorch's native [DistributedSampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.distributed.DistributedSampler) when creating the `train_dataloader`. This means we create the `train_dataloader` directly as if for standalone training and subsequently employ `accelerator.prepare` to shard the samples across different processes.
When referencing `step` in training scripts such as `lr_warmup_steps`, …
=> fix(training): lr scheduler doesn't work properly in distributed scenarios

.github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml, .github/workflows/ssh-runner.yml
Sync the container settings across ssh into runner, nightly and slow tests actions so that they are the same. Now they all use the same share memory size, gpus and diffusers specific cache. It should make it easier to reproduce CI issues.  
Additionally, I think we can remove the Tailscale action from the slow test runner since we now use the SSH into runner workflow for debugging purposes.  
=> Update slow test actions

src/diffusers/models/autoencoders/autoencoder_asym_kl.py
Fix incorrect call to `self.decode()` within `AsymmetricAutoencoderKL.forward()`:
```diff
- dec = self.decode(z, sample, mask).sample
+ dec = self.decode(z, generator, sample, mask).sample
```
related to: [issue#8317](https://github.com/huggingface/diffusers/issues/8317)
=> Fix AsymmetricAutoencoderKL forward

src/diffusers/models/transformers/hunyuan_transformer_2d.py, tests/pipelines/hunyuan_dit/test_hunyuan_dit.py
Test code:
```python
import torch 
from diffusers import HunyuanDiTPipeline
id = "Tencent-Hunyuan/HunyuanDiT-Diffusers"
pipeline = HunyuanDiTPipeline.from_pretrained(
id, 
).to("cuda")
pipeline.set_progress_bar_config(disable=True)
pipeline.transformer.fuse_qkv_projections()
prompt = "一个宇航员在骑马"
image = pipeline(
prompt=prompt,
generator=torch.manual_seed(1),
).images[0]
image.save("fused_qkv.png")
```
Result:
Cc: @gnobitab
=> [Hunyuan DiT] feat: enable fusing qkv projections when doing attention

docs/source/en/api/pipelines/hunyuandit.md, src/diffusers/pipelines/hunyuandit/pipeline_hunyuandit.py
This PR adds the changes necessary to help run Hunyuan DiT under 6GB for GPU VRAM. 
Code:
```python
from diffusers import HunyuanDiTPipeline
from transformers import T5EncoderModel
import torch 
import gc 
def flush():
gc.collect()
def bytes_to_giga_bytes(bytes):
return bytes / 1024 / 1024 / 1024
id = "Tencent-Hunyuan/HunyuanDiT-Diffusers"
text_encoder_2 = T5EncoderModel.from_pretrained(
id,
subfolder="text_encoder_2",
load_in_8bit=True,
device_map="auto",
)
pipeline = HunyuanDiTPipeline.from_pretrained(
id, 
text_encoder_2=text_encoder_2,
transformer=None,
vae=None,
device_map="balanced",
)
with torch.no_grad():
prompt = "一个宇航员在骑马"
prompt_embeds, negative_prompt_embeds, prompt_attention_mask, negative_prompt_attention_mask = …
```
=> [Hunyuan] allow Hunyuan DiT to run under 6GB for GPU VRAM

src/diffusers/loaders/unet.py, src/diffusers/pipelines/pag_utils.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
I fixed the IP-adapter compatibility issue of the proposed [PAG Mixin](https://github.com/huggingface/diffusers/pull/7944).
First, I found that `load_ip_adapter` overwrites the loaded `PAGIdentitySelfAttnProcessor2_0` with `AttnProcessor` or `AttnProcessor2_0` (see `uent.py`). So, I changed the code to keep the original processor if it is not a cross-attention processor.
Second, I also found that even if I use PAG only (not using CFG), the image embeddings of the IP-adapter are only applied to one of `noise_pred_uncond` or `noise_pred_perturb` (I can't remember the exact variable 😭). I checked this by changing `_apply_perturbed_attention_guidance` in `pag_utils.py` line 133 to use only `noise_pred_uncond` or `noise_pred_perturb`. If I do not use classifier-free guidance, the results …
=> fix compatability issue between PAG and IP-adapter

src/diffusers/models/modeling_utils.py
Otherwise, this would fail:
```python
from diffusers import Transformer2DModel
import torch
weight_dtype = torch.float16
transformer = Transformer2DModel.from_pretrained(
"PixArt-alpha/PixArt-Sigma-XL-2-1024-MS",
subfolder='transformer',
torch_dtype=weight_dtype,
use_safetensors=True,
)
```
Can do a patch release for this.
=> [Core] fix: legacy model mapping

.github/workflows/mirror_community_pipeline.yml
Merged https://github.com/huggingface/diffusers/pull/8417 without noticing. This PR updates the workflow name.
=> Fix mirror_community_pipeline.yml name

src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
=> Fix spelling in scheduling_flow_match_euler_discrete.py

.github/workflows/mirror_community_pipeline.yml
Follow-up PR after https://github.com/huggingface/diffusers/pull/8417.
When `github.ref` is a tag (e.g. `refs/tags/v0.29.0`), the logic to determine `PATH_IN_REPO` (e.g. `v0.29.0`) is incorrect. See [example](https://github.com/huggingface/diffusers/actions/runs/9489094498/job/26149588467) where files have been hosted at the root of the folder. This PR fixes this. Sorry about that, I did not realize how github action inject values in the bash command. This time I tested it properly and it should work correctly.
**EDIT:** in parallel I also opened a PR to clean the mess in the dataset repo: https://huggingface.co/datasets/diffusers/community-pipelines-mirror/discussions/2
**EDIT 2:**:  I also triggered a manual deployment to correctly push `v0.29.0` (see …
=> Fix `PATH_IN_REPO` on new release in mirror_community_pipeline.yaml 

docs/source/en/api/loaders/single_file.md, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md, src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_utils.py
Update so that the SD3 pipeline can load the single file checkpoint with the T5 model included in it. 
Also fixes a bug when loading single file checkpoints with just the CLIP models.   
=> Expand Single File support in SD3 Pipeline  

setup.py
Related to https://github.com/huggingface/diffusers/issues/8495. 
Upgrading `diffusers` should also upgrade `transformers` and in turn upgrade `tokenizers`.
=> pin transformers to the latest

examples/dreambooth/requirements_sd3.txt
add `sentencepiece` to requirements.txt for SD3 dreambooth
sd3 dreambooth requires `sentencepiece` but it's not in the requirements.
@sayakpaul
=> add `sentencepiece` to requirements.txt for SD3 dreambooth

examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py
Fixes #8511 (issue)
If text encoder training is not enabled, and the text encoders are not needed during training, they are deleted, and garbage collection/cuda cache clear are run to free up the memory. Previously the deletion only included the lists referencing the text encoders and tokenizers, but because they are also referenced directly in their own variables, the referenced models weren't actually being deleted. This fix is a crude attempt to delete all references to the text encoders, so they can actually be removed from memory.
Anyone in the community is free to …
=> Fix the deletion of SD3 text encoders for Dreambooth/LoRA training if the text encoders are not being trained

examples/dreambooth/README_sd3.md, examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py
Adds a command line argument `max_sequence_length` for the SD3 training scripts to change the token limit for the T5 text encoder.
I left it at 256 to be consistent with the inference token limit.
Fixes https://github.com/huggingface/diffusers/issues/8557
@sayakpaul @AmericanPresidentJimmyCarter
=> [SD3 Training] T5 token limit 

examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py
Though it's not as obvious when training on small batch sizes, it's really obvious at large batch sizes that the timestep distribution is not correct.
When reflecting upon the SD3 paper, I saw that they use `rf/lognorm(0,1)` as their ideal weighting formulation.
It doesn't really do much to save the model or make it any more easily trainable, unfortunately. But, it keeps it from collapsing. Might seem like that contradicts what I just said, but people who have tried training SD 2.0 will know what I mean.
Anyone in the community is free to review the PR once the tests have …
=> SD3: update default training timestep / loss weighting distribution to logit_normal

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md
Add a section in the SD3 docs for the SD3 Tiny AutoEncoder 
@sayakpaul @stevhliu  @madebyollin
=> [SD3] TAESD3 docs

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md
Corrected the documentation title to "Loading the single file checkpoint with T5". Previously, it incorrectly stated "Loading the single file checkpoint without T5" which contradicted the code snippet showing how to load the SD3 checkpoint with the T5 model.
=> [SD3 Docs] Corrected title about loading model with T5 "without" -> "with"

docs/source/en/training/controlnet.md, src/diffusers/models/controlnet_xs.py
The [time_embedding](https://github.com/huggingface/diffusers/blob/eeb70033a6224f58eae3f0f1121384c160a5a61b/src/diffusers/models/controlnet_xs.py#L347) in `ControlNetXSAdapter` is set to None, when not learning the time embedding. But the [ctrl_time_embedding](https://github.com/huggingface/diffusers/blob/eeb70033a6224f58eae3f0f1121384c160a5a61b/src/diffusers/models/controlnet_xs.py#L598C14-L598C33) in `UNetControlNetXSModel` is not set to None, when not learning. This will result in `unused_parameters` when computing the backward gradients during training.
SD1.5 set [use_linear_projection](https://github.com/huggingface/diffusers/blob/eeb70033a6224f58eae3f0f1121384c160a5a61b/src/diffusers/models/controlnet_xs.py#L155C21-L155C42) to `False`, but SD2.1 set this parameter to `True`. Instead …
=> add sd1.5 compatibility to controlnet-xs and fix unused_parameters error during training

src/diffusers/models/transformers/transformer_sd3.py
When gradient checkpointing is enabled for SD3, in the example dreambooth script with default arguments, various modules fail with "expected Tensor, not tuple". This is because the gradient checkpointing codepath doesn't deconstruct the hidden states tuple. This fixes that issue.
@sayakpaul
=> Fix gradient checkpointing issue for Stable Diffusion 3

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py
This PR is trying to fix the bug when you specified any number greater than 1 in `num_images_per_prompt` when you call `StableDiffusion3Pipeline` . An expection occurs when you create the pipeline without T5 text encoder (set `text_encoder_3=None`)
Reproduction (follow the documentation [here](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_3)):
```python
import torch
from diffusers import StableDiffusion3Pipeline
pipe = StableDiffusion3Pipeline.from_single_file(
'./stable-diffusion-3-medium/sd3_medium_incl_clips.safetensors',
text_encoder_3=None
)
image = pipe(
"a picture of a cat holding a sign that says hello world",
negative_prompt="",
num_images_per_prompt=4,
num_inference_steps=28, …
```
=> [SD3] Fix mis-matched shape when num_images_per_prompt > 1 using without T5 (text_encoder_3=None)

examples/dreambooth/README_sd3.md, examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py
@bghira had done it original but #8591 changed that -- that is my fault. This PR fixes it and recognizes @bghira's contributions for discovering that "logit_normal" should be defaulted to all times.
=> Change the default `weighting_scheme` in the SD3 scripts

tests/schedulers/test_scheduler_flax.py
Get rid of https://github.com/huggingface/diffusers/actions/runs/9581481596/job/26418408857?pr=8639#step:9:270. 
I tested it locally within our `diffusers-flax-cpu` Docker image and it passed. So, not sure why it'd fail. I think it's better to relax the tolerance in this case. 
Cc: @DN6 @yiyixuxu
=> [Flax tests] reduce tolerance for a flax test

examples/consistency_distillation/train_lcm_distill_lora_sdxl.py
Part of #8384 
Test script
````
export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
export OUTPUT_DIR="sdxl_lcm"
accelerate launch train_lcm_distill_lora_sdxl.py \
--pretrained_teacher_model=$MODEL_NAME \
--mixed_precision=fp16 \
--lora_rank=64 \
--learning_rate=1e-4 --loss_type="huber" --adam_weight_decay=0.0 \
--num_train_epochs=100 \
--dataloader_num_workers=8 \
--dataset_name="lambdalabs/naruto-blip-captions" \
--validation_steps=200 \
--checkpointing_steps=200 --checkpoints_total_limit=10 \
--train_batch_size=2 \
--gradient_checkpointing --enable_xformers_memory_efficient_attention \
--gradient_accumulation_steps=1 \
--use_8bit_adam \
--resume_from_checkpoint=latest \
--report_to=tensorboard \
--seed=453645634
````
[documentation …
=> [train_lcm_distill_lora_sdxl.py] Fix the LR schedulers when num_train_epochs is passed in a distributed training env

docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md
Adds a `[!TIP]` in the SD3 single file code example to require using torch 2.3 as suggested [here](https://github.com/huggingface/diffusers/issues/8537#issuecomment-2171460924).
=> [docs] Add note for float8

tests/pipelines/marigold/test_marigold_depth.py
Failing tests:
https://github.com/huggingface/diffusers/actions/runs/9657639279/job/26637320084?pr=8691#step:7:16012
=> [Marigold tests] add `is_flaky` decorator to some Marigold tests

tests/models/test_modeling_common.py, tests/pipelines/controlnet_sd3/test_controlnet_sd3.py
SD3 only supports using the `JointAttnProcessor`.  xformers tests are failing because we're attempting to set a default attn processor (which the SD3 transformer does not support yet) and use the `xFormersAttnProcessor` with joint attention (also not supported by the SD3 transformer) 
https://github.com/huggingface/diffusers/actions/runs/9667879876/job/26670701141#step:9:1
Skip these tests for SD3. 
=> Update xformers SD3 test

src/diffusers/models/unets/unet_3d_blocks.py, src/diffusers/models/unets/unet_motion_model.py, tests/models/unets/test_models_unet_motion.py
- allow to use a different number of layers per block
- allow to use a different number of transformer per layers per block
- allow a different number of motion attention head per block
- allow to pass the dropout argument
These modifications are needed for some custom trained model that follow the SDXL architecture more closely (less down block) and more Transformer block per layers.
New arguments / tuple instead of int can now be used, as in the following example :
```python
adapter = MotionAdapter(
block_out_channels=(320, 640, 1280),  # to be checked with the base model unet for compatibility
motion_layers_per_block=2,  # to be checked with the base model unet for compatibility
motion_transformer_per_layers=(1, 2, 6),  # free to choose
motion_mid_block_layers_per_block=1, …
```
=> Motion Model / Adapter versatility

src/diffusers/models/embeddings.py, src/diffusers/models/transformers/hunyuan_transformer_2d.py
We slightly changed the `hunyuandit_transformers_2d.py` and `embeddings.py` to support Hunyuan-DiT v1.2 inference.
It adds additional logic to avoid using `style_embedder` and `image_meta_size` (as they are not effective in the current inference framework anyway).
Please have a look. Thank you.
Test script:
```py
from diffusers import HunyuanDiTPipeline
import torch
pipe = HunyuanDiTPipeline.from_pretrained("Tencent-Hunyuan/HunyuanDiT-v1.2-Diffusers", torch_dtype=torch.float16)
pipe.to('cuda')
prompt = "一个宇航员在骑马"
#prompt = "An astronaut riding a horse"
generator=torch.Generator(device="cuda").manual_seed(0)
image = pipe(height=1024, width=1024, prompt=prompt, generator=generator, num_inference_steps=50, guidance_scale=5.0).images[0]
image.save("img.png")
```
=> [Tencent Hunyuan Team] Add HunyuanDiT-v1.2 Support

src/diffusers/utils/hub_utils.py
cc @sayakpaul it's always good practice to raise exceptions `from` the action exception. This should make the stacktrace easier to investigate. This PR does this in `_get_model_file`. It should help investigate why https://github.com/huggingface/diffusers/actions/runs/9731468292/job/26855960103?pr=8743#step:7:1780 failed.
=> Always raise from previous error

src/diffusers/models/controlnet_sd3.py
Solve https://github.com/huggingface/diffusers/issues/8723.
Currently, in `SD3ControlNetModel.from_transformer()`, the `num_layers` is None by default. If we don't set num_layers manually, it will lead to size mismatch error at the last block. Some explanations can be found [here](https://github.com/huggingface/diffusers/issues/8723#issuecomment-2199480483).
=> Allow from_transformer in SD3ControlNetModel

examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py
I believe an indentation mistake in the validation step is causing this issue: #8732
This PR corrects the indentation of the pipeline validation step. 
=> Fix indent in dreambooth lora advanced  SD 15 script 

scripts/convert_hunyuandit_controlnet_to_diffusers.py, scripts/convert_hunyuandit_to_diffusers.py, src/diffusers/models/controlnet_hunyuan.py
Hi, 
This PR adds the conversion scripts for HunyuanDiT.
I also slightly modified HunyuanDiT-ControlNet to make it compatible with v1.2 model.
Thanks. @yiyixuxu @sayakpaul
=> [Tencent Hunyuan Team] Add checkpoint conversion scripts and changed controlnet

tests/pipelines/stable_diffusion_3/test_pipeline_stable_diffusion_3_img2img.py
vae image processor takes inputs in range [0, 1] for images. previously, we had an additional line that makes the range [0.5, 1]. while that works, i think this is the more correct thing to do.
context: https://github.com/huggingface/diffusers/pull/8709#discussion_r1661780194
@yiyixuxu
=> Fix minor bug in SD3 img2img test

examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
There seems to be an issue with 
1. Saving Kohya style weights in the dreambooth advanced lora script. The save path can output a weird directory when using a relative path. e.g. setting `output_dir=../checkpoints/my-dog-model` will result in the following line creating a path like 
`'../checkpoints/my-dog-model/../checkpoints/my-dog-model.safetensors'`
https://github.com/huggingface/diffusers/blob/610a71d7d467e4cc892c824db882071ff0d282e1/examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py#L1984
I've changed this to save the kohya weight as `args.output_dir/kohya_lora_weights.safetensors` but I'm open to any better naming. 
2. When passing in the `train_text_encoder` argument, I believe there is a missing `else` statement resulting in an ValueError always being …
=> Fix saving text encoder weights and kohya weights in advanced dreambooth lora script

src/diffusers/models/model_loading_utils.py, src/diffusers/utils/hub_utils.py, tests/models/unets/test_models_unet_2d_condition.py
needed for this https://github.com/huggingface/diffusers/pull/8796
=> fix loading sharded checkpoints from subfolder

src/diffusers/pipelines/lavender_flow/pipeline_lavender_flow.py, src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
part of https://github.com/huggingface/diffusers/pull/8796
you can use this to test once this PR is fixed https://github.com/huggingface/diffusers/pull/8798
```python
from diffusers import LavenderFlowPipeline, LavenderFlowTransformer2DModel
import torch
repo = "AuraDiffusion/auradiffusion-v0.1a0"
dtype = torch.float16
transformer = LavenderFlowTransformer2DModel.from_pretrained(
repo,
revision="refs/pr/1",
torch_dtype=dtype,
subfolder="transformer"
) 
pipeline = LavenderFlowPipeline.from_pretrained(
"AuraDiffusion/auradiffusion-v0.1a0", 
revision="refs/pr/1",
transformer=transformer,
).to("cuda")
images = pipeline(
prompt="a cute cat with tiger like looks",
height=512,
width=512,
num_inference_steps=50, 
generator=torch.Generator().manual_seed(666), …
```
=> [lavender-flow] use flow match euler scheduler

src/diffusers/schedulers/scheduling_ddim.py, src/diffusers/schedulers/scheduling_ddpm.py, src/diffusers/schedulers/scheduling_ddpm_parallel.py
Fixes typos:
- 1 return type doc string typo in `scheduling_ddim.py`
- 1 static type checking typo in `scheduling_ddpm.py`
=> Fix static typing and doc typos

src/diffusers/models/embeddings.py
The original docstring formatting was off (looks like a bad line-wrap mangling the parameters), but I figured I might as well reformat to match the same docstring style as the rest of the file.
=> Reformat docstring for `get_timestep_embedding`

docs/source/en/api/pipelines/animatediff.md, src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/models/unets/unet_motion_model.py, tests/single_file/test_model_motion_adapter_single_file.py
Single File loading for AnimateDiff has been a long pending request. This PR adds support to load AnimateDiff checkpoints in their original format into the Diffusers MotionAdapter.    
=> Add single file loading support for AnimateDiff 

docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile
Suggestion from https://github.com/pytorch/pytorch/issues/129351#issuecomment-2199306381.
=> [Docker] include python3.10 dev and solve header missing problem

src/diffusers/utils/hub_utils.py, tests/models/test_modeling_common.py
This is relevant for models when sharded checkpoints become an absolute necessity for loading in machines with limited RAM. With this change, we can serialize the shards in FP16 properly. 
Note that this was supported before but the filename of the shard index file was incorrectly formatted. This PR fixes that and also adds a test for it.
=> [Core] fix: shard loading and saving when variant is provided.

src/diffusers/models/transformers/auraflow_transformer_2d.py, src/diffusers/pipelines/aura_flow/pipeline_aura_flow.py
Otherwise, we run into a shape broadcasting problem during `torch.compile()`. Note that this doesn't happen when the internal [AuraDiffusion/auradiffusion-v0.1a0](https://huggingface.co/AuraDiffusion/auradiffusion-v0.1a0/) variant. 
<details>Benchmarking script
<summary><h2>Benchmarking script</h2></summary>
```python
import torch 
torch.set_float32_matmul_precision("high")
from diffusers import AuraFlowPipeline
import time
id = "fal/AuraFlow" # "AuraDiffusion/auradiffusion-v0.1a0"
pipeline = AuraFlowPipeline.from_pretrained(
id, 
).to("cuda")
pipeline.set_progress_bar_config(disable=True)
torch._inductor.config.conv_1x1_as_mm = True
torch._inductor.config.coordinate_descent_tuning = True
torch._inductor.config.epilogue_fusion = False …
```
=> [Chore] allow auraflow latest to be torch compile compatible.

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/latte.md
It turns out we missed adding the pipeline docs in the Latte PR, and only added it for the Latte Transformer 3D model. @maxin-cn Let me know if you want anything else to be added.
Maybe a line about #8842 (ff-chunked inference) could be added once that's merged.
@yiyixuxu
=> [docs] pipeline docs for latte

.github/workflows/ssh-pr-runner.yml
Add additional workflow to SSH into PR CPU runners. 
=> Add option to SSH into CPU runner. 

src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py, src/diffusers/pipelines/kolors/pipeline_kolors_img2img.py, src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py, src/diffusers/pipelines/pag/pipeline_pag_sd_xl_img2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py, src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
Fixes one specific use case for SDXL image to image where we pass multiple generators but only one image. This PR expands the image tensor so it matches the number of generators. 
To reproduce the error without this PR:
```python
import torch
from diffusers import StableDiffusionXLImg2ImgPipeline
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
"stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16"
).to("cuda")
source_image = load_image(
"https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/kolors/bunny_source.png"
)
generator = torch.Generator(device="cpu").manual_seed(43)
generator_2 = torch.Generator(device="cpu").manual_seed(44)
image = pipe(
prompt="high quality photo", …
```
=> [SDXL] Fix uncaught error with image to image

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_edm_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_ipndm.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
Fix typing of the `timesteps` argument of schedulers taking an integer to also allow tensors. The timestep is passed to `_init_step_index` which deals with this case.
I did not change the docstrings to "`int` or `torch.Tensor`", I can do it if you want (but most other schedulers that already support tensors do not mention it in the docstring).
Note: I kept this PR minimal and did not try to change any actual code, but the typing of timesteps in schedulers is a bit messy. For instance several schedulers [initialize `self.timesteps` as a floating-point tensor](https://github.com/huggingface/diffusers/blob/3f1411767bc0f1837adb6f289713807f18599db3/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L274-L275) but [use an integer tensor in …
=> allow tensors in several schedulers step() call

scripts/generate_logits.py
Related to github.com/huggingface-internal/moon-landing/pull/10713 (server-side, internal link). Let's use `model_info.id` instead of `model.modelId` which is more future-proof cc @julien-c
=> Use model_info.id instead of model_info.modelId

examples/dreambooth/README_sd3.md, examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py
Fixes https://github.com/huggingface/diffusers/issues/8887 and https://github.com/huggingface/diffusers/issues/8708. 
Additionally, it adds an option to control the pre-conditioning behavior on the model outputs. Multiple folks have reported that for rectified-flows we are better off without it. 
@yiyixuxu for awareness. 
@bghira FYI. 
Pinging @haofanwang for awareness as well.
=> [Training] SD3 training fixes

examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py
Textual Inversion Embeddings were being saved using `f"{output_dir}/{args.output_dir}` which can give weird paths when using relative path names. Updating to use just the directory name with `Path`. e.g. `f"{args.output_dir}/{Path(args.output_dir).name}`
#8909
=> Fix name when saving text inversion embeddings in dreambooth advanced scripts

tests/models/test_modeling_common.py, tests/pipelines/test_pipelines.py
We have a couple of flaky tests related to the number of GET requests being performed when fetching a model. The issue only seems to happen in the when the test is triggered via CI and it is not reproducible when SSHing into the runner and running the same tests or the entire test suite. 
Since we're migrating to new runner groups soon, let's skip these tests for now and re-enable with the new machines to see if it fixes it.    
members/contributors who may be …
=> [CI] Skip flaky download tests in PR CI

tests/pipelines/controlnet/test_controlnet_inpaint_sdxl.py, tests/pipelines/controlnet/test_controlnet_sdxl.py, tests/pipelines/controlnet/test_controlnet_sdxl_img2img.py, tests/pipelines/controlnet_sd3/test_controlnet_sd3.py, tests/pipelines/i2vgen_xl/test_i2vgenxl.py, tests/pipelines/kandinsky/test_kandinsky_combined.py, tests/pipelines/kandinsky/test_kandinsky_prior.py, tests/pipelines/kandinsky2_2/test_kandinsky_combined.py, tests/pipelines/kandinsky2_2/test_kandinsky_prior.py, tests/pipelines/kandinsky2_2/test_kandinsky_prior_emb2emb.py, tests/pipelines/pag/test_pag_controlnet_sdxl.py, tests/pipelines/pag/test_pag_sdxl.py, tests/pipelines/pag/test_pag_sdxl_img2img.py, tests/pipelines/pag/test_pag_sdxl_inpaint.py, tests/pipelines/shap_e/test_shap_e.py, tests/pipelines/stable_cascade/test_stable_cascade_prior.py, tests/pipelines/stable_diffusion_image_variation/test_stable_diffusion_image_variation.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_adapter.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py, tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py, tests/pipelines/stable_unclip/test_stable_unclip_img2img.py, tests/pipelines/test_pipelines_common.py, tests/pipelines/text_to_video_synthesis/test_text_to_video_zero_sdxl.py, utils/overwrite_expected_slice.py
As discussed [internally](https://huggingface.slack.com/archives/C065E480NN9/p1721823725964289?thread_ts=1721800193.407419&cid=C065E480NN9). 
Following test slices have been updated:
```bash
tests/pipelines/controlnet/test_controlnet_sdxl.py::StableDiffusionXLControlNetPipelineFastTests::test_controlnet_sdxl_guess
tests/pipelines/kandinsky2_2/test_kandinsky_combined.py::KandinskyV22PipelineCombinedFastTests::test_kandinsky
tests/pipelines/kandinsky/test_kandinsky_combined.py::KandinskyPipelineCombinedFastTests::test_kandinsky
tests/pipelines/controlnet/test_controlnet_sdxl.py::StableDiffusionXLControlNetPipelineFastTests::test_ip_adapter_single
tests/pipelines/kandinsky2_2/test_kandinsky_combined.py::KandinskyV22PipelineImg2ImgCombinedFastTests::test_kandinsky …
```
=> [Tests] fix slices of 26 tests (first half)

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
fix guidance_scale value not equal to the value in comments
----
default guidance_scale value:
----
comment guidance_scale value:
=> fix guidance_scale value not equal to the value in comments

examples/community/lpw_stable_diffusion.py, examples/community/lpw_stable_diffusion_xl.py
handle lora scale in cross_attention_kwargs and clip skip
=> handle lora scale and clip skip in lpw sd and sdxl community pipelines

src/diffusers/loaders/peft.py, src/diffusers/models/unets/unet_motion_model.py
As internally reported by @a-r-r-o-w:
https://huggingface.slack.com/archives/C065E480NN9/p1722091746614339
I don't know much about the AnimateDiff LoRA tests but I think we should consider how we can catch these in PRs. So, I will defer to @DN6 here.
=> [LoRA] fix: animate diff lora stuff.

src/diffusers/pipelines/stable_audio/pipeline_stable_audio.py, tests/models/autoencoders/test_models_vae.py, tests/pipelines/stable_audio/test_stable_audio.py
Follows #8716
Dependent on the [hub PR](https://huggingface.co/stabilityai/stable-audio-open-1.0/discussions/39) that adds the stable audio open weights to the main repository.
cc @sayakpaul and @yiyixuxu
=> Fix Stable Audio repository id

.github/workflows/nightly_tests.yml
Install test dependencies on pipeline test fetcher. Needed for pipelines that have externals dependencies such as Kolors. 
=> Updates deps for pipeline test fetcher

src/diffusers/models/attention_processor.py
Minor typing fix. `None` is valid for `get_attention_scores`, should be typed as such.
Minor nonfunctional change, I guess:
- General functionalities: @sayakpaul @yiyixuxu @DN6
=> type `get_attention_scores` as optional in `get_attention_scores`

src/diffusers/models/attention_processor.py
- Applies QK-norm in some of the attention processors that currently support it, and newly in the default AttentionProcessor2_0 and FusedAttentionProcessor2_0 (for you know what :eyes:).
- I think we should also refactor some of the attention processors and determine if we need these many.
- We should also probably re-order these in alphabetical order to make it easier to read, and group the normal and fused variants together.
Happy to take it up in this PR if we're okay with it.
=> [refactor] apply qk norm in attention processors

docs/source/en/_toctree.yml, docs/source/en/community_projects.md
We have a lot of great community projects built with Diffusers. Propose adding a community projects section to highlight them. 
I put this in it's own section for now, but I'm happy to move it to a more appropriate place if needed.  
=> [Docs] Add community projects section to docs

src/diffusers/pipelines/animatediff/pipeline_animatediff.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_controlnet.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video.py, src/diffusers/pipelines/pag/pipeline_pag_sd_animatediff.py
Missed this. For chunked decoding of video we should use `decode_chunk_size` as the argument like we do for SVD. 
=> Freenoise change `vae_batch_size` to `decode_chunk_size`

docs/source/en/_toctree.yml, docs/source/en/optimization/fp16.md
Regroups models in the toctree as one of Transformers, UNets, VAEs, and ControlNets. Also adds a brief note that other tiny autoencoders are available for SD3, SDXL, and SD.
=> [docs] Organize model toctree

docs/source/en/using-diffusers/merge_loras.md
Replaces internal syntax to PEFT functions with Markdown link. For some reason, the doc-builder is unable to find the PEFT functions.
`set_adapters` wasn't working because it moved to `PeftAdapterMixin` from `UNet2DConditionLoadersMixin`, so the doc-builder was unable to find it.
=> [docs] Resolve internal links to PEFT

src/diffusers/models/transformers/auraflow_transformer_2d.py
Adds simple Positional Embedding selection logic to have width, height of variable length. This is for auraflow v0.3
=> Add Learned PE selection for Auraflow

src/diffusers/utils/loading_utils.py
Noticed that our `load_video` util cannot handle URLs with query parameters, and could use some small improvements. 
This PR 
- Updates to parse the URL in a more robust way. 
- Adds a check to raise an error if we get a non-200 response code. 
- Iterates over the raw video in chunks and write to file to avoid loading large videos into memory.   
=> Small improvements for video loading

src/diffusers/loaders/ip_adapter.py
IP Adapter FaceID model don't need the image encoder so it's not loaded and the image encoder its used to get the clip size for the Kolors version, this produces an error with FaceID models. This PR sets back the default 224 size for these models.
IMO it would be better to not load the `feature extractor` altogether if it's not used (not sure) but this was in the original implementation.
Fixes #9187
@sayakpaul @detkov @fabiorigano
=> [IP Adapter] Fix object has no attribute with image encoder

src/diffusers/pipelines/auto_pipeline.py
Doesn't appear to be an I2I pipe despite using a known VAE?
`quickdif 'bright dslr portrait photograph of a kitten in a flower garden' -m 'Alpha-VLLM/Lumina-Next-SFT-diffusers' --dtype bf16`
=> Add Lumina T2I Auto Pipe Mapping

src/diffusers/pipelines/auto_pipeline.py
I made a mistake in https://github.com/huggingface/diffusers/pull/9065/files#
fixing it! 
sanity check 
```python
from diffusers import AutoPipelineForText2Image, AutoPipelineForImage2Image
import torch
repo = "Kwai-Kolors/Kolors-diffusers"
pipe_txt2img = AutoPipelineForText2Image.from_pretrained(repo, variant="fp16", torch_dtype=torch.float16).to("cuda")
assert pipe_txt2img.__class__.__name__ == "KolorsPipeline"
pipe_txt2img_pag = AutoPipelineForText2Image.from_pretrained(repo, torch_dtype=torch.float16, variant="fp16", enable_pag=True).to("cuda")
assert pipe_txt2img_pag.__class__.__name__ == "KolorsPAGPipeline"
pipe_img2img = AutoPipelineForImage2Image.from_pretrained(repo, variant="fp16", torch_dtype=torch.float16).to("cuda")
assert pipe_img2img.__class__.__name__ == …
```
=> fix autopipeline for kolors img2img

src/diffusers/pipelines/flux/pipeline_flux.py
This is an attempt to add `enable_vae_slicing` and `enable_vae_tiling` to `pipeline_flux`. I have tested this locally and it seems to work. Looking to add flux to our roster of models, and this functionality would help.
@yiyixuxu and @asomoza
=> Add vae slicing and tiling to flux pipeline

examples/text_to_image/train_text_to_image_sdxl.py
Fixes #6879, and #9200 
I fixed the RuntimeError: expected mat1 and mat2 to have the same dtype, as well as the similar issues when processing model_pred by fixing the same dtype.
=> Fix dtype error for StableDiffusionXL

src/diffusers/loaders/single_file_utils.py
Fixes #9052 by making xl_inpaint available as an option in ```infer_diffusers_model_type```.
#9052 
=> Fix ```from_single_file``` for xl_inpaint

src/diffusers/pipelines/stable_cascade/pipeline_stable_cascade.py, src/diffusers/pipelines/stable_cascade/pipeline_stable_cascade_prior.py
Fixes # 
- scheduler.config has no attribute "clip_sample" with Stable Cascade Prior pipeline when using DPM sampler.  (Closes https://github.com/huggingface/diffusers/issues/7884)
- Adds support for custom sampler to Stable Cascade Decoder (LCM works really well).  
- Changes the "s" value in get_timestep_ratio_conditioning to 0.008 to reflect the original defaults.  
This PR is required for this model: https://huggingface.co/Disty0/sotediffusion-v2
members/contributors who may be …
=> Custom sampler support for Stable Cascade Decoder

src/diffusers/pipelines/auto_pipeline.py, src/diffusers/pipelines/pag/pipeline_pag_sd_xl_inpaint.py
Fixed the issue preventing model and inference with `StableDiffusionXLInpaintPipeline` class in UNet where `in_channels=9`.
**1. When loading models of the `StableDiffusionXLInpaintPipeline` class like `diffusers/stable-diffusion-xl-1.0-inpainting-0.1`, the load fails if `enable_pag=True`.**
error:
```bash
File /hdd/repo/diffusers/src/diffusers/pipelines/auto_pipeline.py:958, in AutoPipelineForInpainting.from_pretrained(cls, pretrained_model_or_path, **kwargs)
954     if enable_pag:
955         orig_class_name = config["_class_name"].replace("InpaintPipeline",
956                                                         "PAG3InpaintPipeline")
--> 958 inpainting_cls = _get_task_class(AUTO_INPAINT_PIPELINES_MAPPING, orig_class_name)
960 kwargs = {**load_config_kwargs, **kwargs}
961 return …
```
=> Fix StableDiffusionXLPAGInpaintPipeline

src/diffusers/pipelines/pipeline_loading_utils.py, src/diffusers/pipelines/pipeline_utils.py, tests/pipelines/test_pipeline_utils.py
we cannot run this script anymore because the repo contains additional folders like `vae_decoder` etc (discovered when I try to run the testing script from this PR https://github.com/huggingface/diffusers/pull/8990)
```python
import torch
from diffusers import  AutoPipelineForImage2Image
pipe = AutoPipelineForImage2Image.from_pretrained(
use_safetensors=True,
)
```
fixing here
=> fix a regression in `is_safetensors_compatible`

src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_utils.py
Legacy  kwargs `prediction_type` and `scheduler_type` will not be configured in single file loading if an appropriate model config is present in the users cache. This leads bad samples being generated if the user would like to change the prediction type for a particular model. 
This PR:
1. Adds an additional check to trigger legacy scheduler loading when these kwargs are passed in
2. Updates the deprecation message for these kwargs with examples to show how we expect the schedulers to be configured in single file loading going forward. 
#9171
Anyone in the …
=> [Single File] Fix configuring scheduler via legacy kwargs

src/diffusers/models/embeddings.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py
part of cogvideox refactor 
related https://github.com/huggingface/diffusers/pull/9263
a unit test here https://colab.research.google.com/drive/1qbFPAblW8wZvLoFCqV-sXzEZQLgujF2k?usp=sharing
cc @a-r-r-o-w
=> refactor 3d rope for cogvideox 

examples/dreambooth/train_dreambooth_flux.py
fixes https://github.com/huggingface/diffusers/issues/9204#issue
=> [Dreambooth flux] bug fix for dreambooth script (align with dreambooth lora)

src/diffusers/loaders/ip_adapter.py
This PR makes the loading of the `image_encoder` use the same `cache_dir` and `local_files_only` arguments from the IPA model loading which is the expected behavior. 
Fixes #9192
@yiyixuxu @jonahclarsen
=> [IP Adapter] Fix `cache_dir` and `local_files_only` for image encoder

src/diffusers/training_utils.py
to avoid "FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations"
@sayakpaul @yiyixuxu @DN6 @SunMarc
=> Replace transformers.deepspeed with transformers.integrations.deepspeed

src/diffusers/pipelines/free_noise_utils.py
Think enabling freenoise fails on checkpoints that don't use motion modules in the midblock. 
On main this snippet will throw an error
```python
import torch
from diffusers import MotionAdapter, AnimateDiffPipeline, DDIMScheduler
from diffusers.utils import export_to_gif
adapter = MotionAdapter.from_pretrained("diffusers/animatediff-motion-adapter-v1-5-3", torch_dtype=torch.float16)
pipe = AnimateDiffPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", motion_adapter=adapter, torch_dtype=torch.float16)
pipe.enable_free_noise()
```
```
File "/home/dhruv_huggingface_co/diffusers/../scripts/test_animatediff_prompt_travel.py", line 7, in <module>
pipe.enable_free_noise()
File "/home/dhruv_huggingface_co/diffusers/src/diffusers/pipelines/free_noise_utils …
```
=> Fix Freenoise for AnimateDiff V3 checkpoint.  

src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py
Flux uses the pooled CLIP prompt embeds, so it produces a 2D tensor (batch_size, dim) rather than a 3D tensor (batch_size, seq_len, dim). The current way of repeating the prompt embeds for `num_images_per_prompt` is incorrect. This PR corrects the behaviour  
#9215
=> Fix Flux CLIP prompt embeds repeat for num_images_per_prompt > 1

src/diffusers/pipelines/flux/pipeline_flux.py
To match the original code, 7.0 is too high
=> Change default for `guidance_scale`in FLUX

src/diffusers/loaders/lora_conversion_utils.py, src/diffusers/loaders/lora_pipeline.py
Fixes https://github.com/huggingface/diffusers/issues/9291. 
Fixes https://github.com/huggingface/diffusers/issues/9292 (potentially). 
@apolinario does this work for you? 
I decided to reuse https://github.com/kohya-ss/sd-scripts/blob/sd3/networks/convert_flux_lora.py (with appropriate credits to @kohya-ss) because the conversion utility won't have been too different if we were to write it anyway. 
@kohya-ss could I get your commit email address so that we could add you as a co-author of this PR? @Leommm-byte same for you as well. 
About tests, I think it might make sense to add a bit later to give the community a chance to play with it.
=> [LoRA] support kohya and xlabs loras for flux.

examples/custom_diffusion/train_custom_diffusion.py
Part of https://github.com/huggingface/diffusers/issues/8384
Test Script
```
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export OUTPUT_DIR="cat_model"
export INSTANCE_DIR="./data/cat"
accelerate launch train_custom_diffusion.py \
--pretrained_model_name_or_path=$MODEL_NAME  \
--instance_data_dir=$INSTANCE_DIR \
--class_data_dir=./real_reg/cat/ \
--with_prior_preservation --prior_loss_weight=1.0 \
--class_prompt="cat" --num_class_images=20 \
--instance_prompt="photo of a <new1> cat"  \
--resolution=512  \
--train_batch_size=2  \
--learning_rate=1e-5  \
--lr_warmup_steps=0 \
--num_train_epochs=5 \
--enable_xformers_memory_efficient_attention \
--scale_lr --hflip  \
--modifier_token "<new1>" \
--validation_prompt="<new1> cat sitting in a bucket" \ …
```
=> [train_custom_diffusion.py] Fix the LR schedulers when `num_train_epochs` is passed in a distributed training env

src/diffusers/models/embeddings.py
also made a slow tests for all pipelines using rotary embeddings
<details>
<summary>slow test for pipelines using rotary embedding</summary>
```python
from benchmarks.utils import benchmark_fn, flush, bytes_to_giga_bytes, BenchmarkInfo
import argparse
import torch
import os
from typing import Dict, Union
import csv
BENCHMARK_FIELDS = [
"pipeline_cls",
"repo_id",
"time (secs)",
"memory (gbs)",
]
def write_to_csv(file_name: str, data_dict: Dict[str, Union[str, bool, float]]):
"""Append a dictionary into a CSV file."""
file_exists = os.path.isfile(file_name)
with open(file_name, mode="a", newline="") as csvfile:
writer = csv.DictWriter(csvfile, fieldnames=BENCHMARK_FIELDS)
if not file_exists:
writer.writeheader()
writer.writerow(data_dict) …
```
=> rotary embedding refactor 2: update comments, fix dtype for use_real=False

src/diffusers/models/embeddings.py
fix https://github.com/huggingface/diffusers/issues/9299
=> refactor rotary embedding 3: so it is not on cpu

docs/source/en/api/pipelines/cogvideox.md
- Demonstrates serialization example with torchao (gist)
- int8 quantized inference
- benchmarks for different quantizations (gist)
@sayakpaul @stevhliu
=> [docs] Add a note on torchao/quanto benchmarks for CogVideoX and memory-efficient inference

src/diffusers/loaders/single_file_utils.py
use `Lykon/dreamshaper-8` for now - will update once we made a decision
for https://github.com/huggingface/diffusers/issues/9322#issuecomment-2319165753
=> update runway repo for single_file

src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
(cherry picked from commit bf890bca0e8aed875d6a207f9b826ce894901522)
Adds VAE encode memory optimizations from #9333 separately for a cleaner history of additions and because this is needed in #9302.
@DN6 @yiyixuxu
=> [core] CogVideoX memory optimizations in VAE encode

tests/models/test_modeling_common.py, tests/models/transformers/test_models_transformer_flux.py, tests/pipelines/flux/test_pipeline_flux.py, tests/pipelines/pag/test_pag_sd3.py, tests/pipelines/stable_audio/test_stable_audio.py
Add a check on `set_attention_processor_for_determinism` test that allows us to skip this test for models that don't use AttnProcessor or AttnProcessor_2
Skip xformers tests for models/pipelines without an xformers processor.  
=> [CI] More fixes for Fast GPU Tests on main

tests/models/autoencoders/test_models_vae.py
Hi, this PR makes 2 tests work on XPU. 
```bash
pytest -rA tests/models/autoencoders/test_models_vae.py::ConsistencyDecoderVAEIntegrationTests::test_encode_decode
pytest -rA tests/models/autoencoders/test_models_vae.py::ConsistencyDecoderVAEIntegrationTests::test_encode_decode_f16
```
Below are the results:
```bash
================================================ short test summary info =================================================
PASSED tests/models/autoencoders/test_models_vae.py::ConsistencyDecoderVAEIntegrationTests::test_encode_decode_f16
============================================= 1 passed, 2 warnings in 3.76s ==============================================
```
```bash
================================================ short test summary info …
```
=> [tests] make 2 tests device-agnostic  

tests/single_file/single_file_testing_utils.py, tests/single_file/test_stable_diffusion_controlnet_img2img_single_file.py, tests/single_file/test_stable_diffusion_controlnet_inpaint_single_file.py, tests/single_file/test_stable_diffusion_controlnet_single_file.py, tests/single_file/test_stable_diffusion_img2img_single_file.py, tests/single_file/test_stable_diffusion_inpaint_single_file.py, tests/single_file/test_stable_diffusion_single_file.py, tests/single_file/test_stable_diffusion_xl_adapter_single_file.py, tests/single_file/test_stable_diffusion_xl_controlnet_single_file.py
Update our single file nightly tests to account for runway repo being removed. Updates the repo ids and single file urls to use Lykon's dreamshaper 8
=> [CI] Update Single file Nightly Tests

src/diffusers/image_processor.py
Fixes a deprecation warning in the `VaeImagePreprocessor`.
`vae_latent_channels` was directly accessed where it should be access from `self.config`.
=> fix one uncaught deprecation warning for accessing vae_latent_channels in VaeImagePreprocessor

src/diffusers/models/embeddings.py
The [Squeeze operation](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/embeddings.py#L693) performed in FluxPosEmbed is a no op after the [change ](https://github.com/huggingface/diffusers/commit/c2916175186e2b6d9c2d09b13a753cc47f5d9e19#diff-68d4ddab9d9846465f7d3b0a8583b256f7293df93e60a04eaeaced3b85de15aaL367) to make txt_ids and img_ids into 2D tensors was committed. Can we remove the Squeeze op used this case? This class is currently only used in transformer_flux.py and controlnet_flux.py and both models accept 2D txt and img ids.
@sayakpaul …
=> FluxPosEmbed: Remove Squeeze No-op

docs/source/en/api/pipelines/animatediff.md
Adds documentation for AnimateDiff FreeNoise introduced in #9262
@stevhliu, @sayakpaul
=> [docs] AnimateDiff FreeNoise 

.github/workflows/benchmark.yml, .github/workflows/nightly_tests.yml, .github/workflows/pr_test_fetcher.yml, .github/workflows/pr_test_peft_backend.yml, .github/workflows/pr_tests.yml, .github/workflows/push_tests.yml, .github/workflows/push_tests_fast.yml, .github/workflows/push_tests_mps.yml, .github/workflows/release_tests_fast.yml
To prevent https://github.com/huggingface/diffusers/actions/runs/10826551058/job/30046968127?pr=9399.
=> [CI] update artifact uploader version

src/diffusers/pipelines/pipeline_utils.py
When using `.save_pretrained` to save different modeling components, we lose control over being able to specify max shard size. Being able to store smaller shards of all modeling components without saving each component individually would be a nice control to have. This is particularly useful in the case of CogVideoX where having both text encoder and transformer in shard size of 10GB results in OOM on a Colab CPU. One needs to save the smaller shards in order to make loading the components possible and create the pipeline, which can then be inferred with something like `enable_sequential_cpu_offload`.
=> Allow max shard size to be specified when saving pipeline

src/diffusers/pipelines/auto_pipeline.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py
Adds several fixes to Flux ControlNet pipelines
- Add txt2img<->img2img<->inpaint automappings
- Correct image encoding dtype as VAE may not be the same as main model (typically its not when using quantized model)
- Add guidance handling to main txt pipeline (now inline with img2img and inpaint that already had this)
Closes #9398
Closes #9370
CC: @yiyixuxu @sayakpaul
=> Several fixes to Flux ControlNet pipelines

tests/lora/test_lora_layers_cogvideox.py, tests/lora/test_lora_layers_flux.py, tests/lora/test_lora_layers_sd3.py, tests/lora/utils.py
Minor cleanup of the lora tests
=> [refactor] LoRA tests

tests/pipelines/lumina/test_lumina_nextdit.py
Reduces the model sizes in the Lumina tests.  
Part of: #7677 
CC: @sayakpaul @a-r-r-o-w
=> [Tests] Reduce the model size in the lumina test 

src/diffusers/schedulers/scheduling_euler_discrete.py
This PR adds [exponential sigmas](https://github.com/crowsonkb/k-diffusion/blob/686dbad0f39640ea25c8a8c6a6e56bb40eacefa2/k_diffusion/sampling.py#L26-L29). Added only to Euler for now, after initial review we will add it to other schedulers, and add the other schedulers in the linked issue in subsequent PRs.
The implementation is quite simple, we add `use_exponential_sigmas` parameter and `_convert_to_exponential` function.
Example usage:
```python
from diffusers import StableDiffusionXLPipeline, EulerDiscreteScheduler
import torch
pipeline: StableDiffusionXLPipeline = StableDiffusionXLPipeline.from_pretrained(
)
pipeline.scheduler = EulerDiscreteScheduler.from_config(
pipeline.scheduler.config, …
```
=> [Schedulers] Add exponential sigmas / exponential noise schedule

docs/source/en/api/schedulers/overview.md
As discussed in https://github.com/huggingface/diffusers/issues/9416#issuecomment-2368647232 this PR adds documentation for Noise Schedule/Schedule Type to Schedulers Overview documentation, specifically regarding the equivalent of `sgm_uniform` and `simple` Schedule types as they are known in the webuis. This section can be updated when other schedule types are supported as in #9499.
Also see https://github.com/huggingface/diffusers/issues/9416#issuecomment-2363793200 and #9490 for the reproduction/comparison.
Fixes #9416 
cc @yiyixuxu @stevhliu
=> Add Noise Schedule/Schedule Type to Schedulers Overview documentation

src/diffusers/loaders/single_file_utils.py, tests/lora/test_lora_layers_sd.py, tests/models/autoencoders/test_models_vae.py, tests/pipelines/controlnet/test_controlnet.py, tests/pipelines/controlnet/test_controlnet_img2img.py, tests/pipelines/controlnet/test_controlnet_inpaint.py, tests/pipelines/controlnet/test_flax_controlnet.py, tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py, tests/pipelines/ledits_pp/test_ledits_pp_stable_diffusion.py, tests/pipelines/pag/test_pag_sd.py, tests/pipelines/semantic_stable_diffusion/test_semantic_diffusion.py, tests/pipelines/stable_diffusion/test_onnx_stable_diffusion.py, tests/pipelines/stable_diffusion/test_onnx_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion.py, tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py, tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py, tests/pipelines/stable_diffusion_adapter/test_stable_diffusion_adapter.py, tests/pipelines/stable_diffusion_safe/test_safe_diffusion.py, tests/pipelines/test_pipelines_auto.py, tests/pipelines/text_to_video_synthesis/test_text_to_video_zero.py, tests/single_file/test_stable_diffusion_controlnet_img2img_single_file.py, tests/single_file/test_stable_diffusion_controlnet_inpaint_single_file.py, tests/single_file/test_stable_diffusion_controlnet_single_file.py, tests/single_file/test_stable_diffusion_img2img_single_file.py, tests/single_file/test_stable_diffusion_inpaint_single_file.py, tests/single_file/test_stable_diffusion_single_file.py
This PR:
1. update the reference repo for single file config from `Lykon/dreamshaper-8` to `stable-diffusion-v1-5/stable-diffusion-v1-5`. `Lykon/dreamshaper-8` actually has a different config than the original SD1.5, which caused test failures such as https://github.com/huggingface/diffusers/actions/runs/10985616735/job/30497746524#step:6:30045 
2. update the repo to `stable-diffusion-v1-5/stable-diffusion-v1-5` and "stable-diffusion-v1-5/stable-diffusion-inpainting", the "Jiali/stable-diffusion-1.5" does not contain variant, which caused failures such as https://github.com/huggingface/diffusers/actions/runs/10985616735/job/30497746524#step:6:30048
3. fix a bug where we modify the mapping dict in-inplace
did not fix this https://github.com/huggingface/diffusers/actions/runs/10985616735/job …
=> a few fix for SingleFile tests

docs/source/en/api/schedulers/overview.md, src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
This PR extends #9499 to other schedulers where `use_karras_sigmas` is supported, and updates the documentation.
cc @asomoza @yiyixuxu
=> Add exponential sigmas to other schedulers and update docs

docs/source/en/using-diffusers/callback.md
This PR fixes the latents_to_rgb function in the doc which will result in an error because the function only gets the first channel then performs permutation on 3 channels.
@stevhliu @sayakpaul
=> [Doc] Improved level of clarity for latents_to_rgb.

src/diffusers/schedulers/scheduling_euler_discrete.py
This PR adds [beta sigmas](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/a82d5d177c065f8a6251850e233dca97f15c13ac/modules/sd_schedulers.py#L119-L127) from [Beta Sampling is All You Need](https://huggingface.co/papers/2407.12173). Added only to Euler for now, after initial review we will add it to other schedulers. Documentation will be updated for this scheduler and any others implemented in a subsequent PR after the initial review and after they've been added to other schedulers.
The implementation is quite simple, we add `use_beta_sigmas` parameter and `_convert_to_beta` function.
Beta sigmas depends on `scipy` so we add a check with `is_scipy_available()`.
The check for `self.config.use_exponential_sigmas and self.config.use_karras_sigmas` is moved to schedule …
=> [Schedulers] Add beta sigmas / beta noise schedule

src/diffusers/pipelines/kolors/tokenizer.py
Transformers in the latest version added 'padding_side' as call time kwargs with this [PR](https://github.com/huggingface/transformers/pull/33385) that made the tests fail. This PR adds the argument to fix them.
=> [Tests] Fix ChatGLMTokenizer

tests/lora/utils.py
There's a lot of if/else magic involved when serializing a LoRA state dict (shout at me). This PR simplifies that.
=> [Tests] [LoRA] clean up the serialization stuff.

src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
As discussed internall in https://huggingface.slack.com/archives/C068ZAHJZCZ/p1725402937927749?thread_ts=1725360687.955529&cid=C068ZAHJZCZ
=> [refactor] remove conv_cache from CogVideoX VAE

examples/cogvideo/train_cogvideox_lora.py, examples/controlnet/train_controlnet_flux.py, examples/controlnet/train_controlnet_sd3.py, examples/dreambooth/train_dreambooth_lora_flux.py, examples/dreambooth/train_dreambooth_lora_sd3.py, src/diffusers/training_utils.py
My bad that in 
https://github.com/huggingface/diffusers/blob/534848c370dafddc3f9fb95151f472da39486206/src/diffusers/training_utils.py#L263
I assumed that the scope of `del` would carry forward but that is not the case. So, even when we call `del obj` it actually just deletes the local reference, it doesn't carry forward. So, we're better off without it and doing `del` explicitly (like the changes done in this PR). 
Thanks to @a-r-r-o-w for catching this. It didn't go to a release yet, so, I think this shouldn't have any issues.
=> [chore] fix: retain memory utility.

src/diffusers/loaders/lora_conversion_utils.py, tests/lora/test_lora_layers_flux.py
https://huggingface.co/cocktailpeanut has a bunch of very nice Flux LoRAs that were trained using Kohya but has text encoder components too. This PR adds support for fully loading those LoRAs. 
Test code (has a slow test in this PR too):
```python
from diffusers import FluxPipeline
import torch 
pipeline = FluxPipeline.from_pretrained(
"black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16
).to("cuda")
pipeline.load_lora_weights("cocktailpeanut/optimus", weight_name="optimus.safetensors")
prompts = [
"optimus is cleaning the house with broomstick",
"optimus is a DJ performing at a hip nightclub",
"optimus is competing in a bboy break dancing competition",
"optimus is playing tennis in a tennis court"
]
images = pipeline(
prompts, 
num_inference_steps=50,
guidance_scale=3.5, …
```
=> [LoRA] support Kohya Flux LoRAs that have text encoders as well

src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet_inpainting.py, src/diffusers/pipelines/pag/pipeline_pag_sd_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
for `1920 X 1080` should get an input error and ask user to resize to `1920 x 1072` (on current main will get an error on scheduler step)
```
ValueError: `height` and `width` have to be divisible by 16 but are 1920 and 1080.You can use height 1920 and width 1072.
```
```python
import torch
import argparse
from diffusers import StableDiffusion3Pipeline
def main(height, width):
device = torch.device("cuda:1")
pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)
pipe = pipe.to(device)
generator = torch.Generator(device=device).manual_seed(0)
image = pipe(
"A cat holding a sign that says hello world",
negative_prompt="",
num_inference_steps=28,
height=height,
width=width,
guidance_scale=7.0,
generator=generator, …
```
=> [sd3] make sure height and size are divisible by `16`

src/diffusers/loaders/lora_conversion_utils.py
Typo fixing for XLab FLUX LoRA conversion to diffusers.
In [its current version](https://github.com/huggingface/diffusers/blob/99f608218caa069a2f16dcf9efab46959b15aec0/src/diffusers/loaders/lora_conversion_utils.py#L635), this raises: `TypeError: slice indices must be integers or None or have an __index__ method` because `str.startswith` expects a tuple of strs or a single str.
(Unless I've missed an issue on this topic, I'm a bit surprised this typo has been here for over a month without anyone complaining)
Repro steps:
1. instanciate a flux pipeline
2. get a xlab lora safetensors
3. run `pipe.load_lora_weights(xlab_lora)` , passing the lora from step 2 …
=> fix xlabs FLUX lora conversion typo

examples/controlnet/train_controlnet_sd3.py
Issue https://github.com/huggingface/diffusers/issues/9560
Fix vae dtype when accelerate config using --mixed_precision="fp16".
@sayakpaul
=> fix vae dtype when accelerate config using --mixed_precision="fp16"

src/diffusers/utils/import_utils.py
Fixes #9567 
@a-r-r-o-w @stevhliu
=> refac: docstrings in import_utils.py

src/diffusers/pipelines/controlnet/pipeline_controlnet.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py
Make ControlNet pipeline support interrupt
Fixes #9619
@yiyixuxu and @asomoza
=> make controlnet support interrupt

.github/workflows/mirror_community_pipeline.yml, .github/workflows/notify_slack_about_release.yml, .github/workflows/pr_dependency_test.yml, .github/workflows/pr_flax_dependency_test.yml, .github/workflows/pr_test_peft_backend.yml, .github/workflows/pr_tests.yml, .github/workflows/pr_torch_dependency_test.yml, .github/workflows/pypi_publish.yaml, .github/workflows/stale.yml, .github/workflows/trufflehog.yml, .github/workflows/typos.yml
`ubuntu-latest` is now Ubuntu 24.04, which uses Python 3.12 and thus it looks for Python-3.12 compatible packages only. So, we change to `runs-on: ubuntu-22.04` instead of `ubuntu-latest`.
Thanks to @regisss for [this info](https://huggingface.slack.com/archives/C1RCG46LS/p1728616969079469) (internal link)!
Cc: @yiyixuxu @a-r-r-o-w @asomoza
=> [CI] replace ubuntu version to 22.04.

examples/text_to_image/train_text_to_image_sdxl.py
Improve the performance (FPS) while training, and suitable for NPU computing.
Selection for free memory for CUDA or NPU
=> Improve the performance and suitable for NPU computing

benchmarks/push_results.py
Fix https://github.com/huggingface/diffusers/actions/runs/11337922413/job/31530294519#step:7:25
=> [Chore] fix import of EntryNotFoundError.

src/diffusers/models/controlnet_flux.py, src/diffusers/models/transformers/transformer_flux.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py
Continue https://github.com/huggingface/diffusers/pull/9638 here since I cannot push into it directly
=> [authored by @Anghellia) Add support of Xlabs Controlnets #9638

examples/dreambooth/README_sd3.md, examples/dreambooth/test_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py, src/diffusers/utils/hub_utils.py
small updates to the dreambooth and dreamboath lora training scripts for SD3, including:
- adds `--cache_latents` and `--upcast_before_saving` features (similar to what we have for [flux scripts](https://github.com/huggingface/diffusers/blob/92d2baf643b6198c2df08d9e908637ea235d84d1/examples/dreambooth/train_dreambooth_lora_flux.py#L629))
- fixes mixed precision training bug (as done in https://github.com/huggingface/diffusers/pull/9565) 
- fixes text encoder training bug
=> [SD3 dreambooth-lora training] small updates + bug fixes 

src/diffusers/utils/peft_utils.py
In peft's unscale, it unnecessarily traverses modules even when weight is None. 
I think a modification like this PR would logically achieve the same behavior without traversing. 
It seems like a simple fix, but please review. 
- PEFT: @sayakpaul @BenjaminBossan
=> [peft] simple update when unscale 

src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
Fixes https://github.com/a-r-r-o-w/cogvideox-factory/issues/33#issuecomment-2413487035
@sayakpaul
=> [core] improve VAE encode/decode framewise batching

tests/pipelines/cogvideo/test_cogvideox_image2video.py
=> [tests] fix name and unskip CogI2V integration test

examples/advanced_diffusion_training/README_flux.md
minor updates and fixes to readme
=> [advanced flux lora script] minor updates to readme

examples/community/README_community_scripts.md
This PR adds prompt scheduling callback to community scripts.
Fixes #9470 
@asomoza
=> Add prompt scheduling callback to community scripts

.github/workflows/pr_test_peft_backend.yml, src/diffusers/dependency_versions_table.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
We missed this step (I did not know we had to do it) in #9709. Also contains a dummy change for now to trigger CI fast tests
=> `make  deps_table_update` to fix CI tests

src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py
Fixed typos in `pipeline_cogvideox_image2video.py` and  `pipeline_cogvideox.py`. 
The default fps is 8. You can refer to official implementation of [cogvideo repo](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo.py#L108).
@yiyixuxu
@asomoza
@stevhliu
@sayakpaul
=> Fix typo in cogvideo pipeline

src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py
fix the failing singlestep scheduler tests
thanks to @gfaires  to help identify this is only an issue with newer numpy version https://github.com/huggingface/diffusers/issues/9359
it comes down to this, this creates a numpy array in earlier versions (as expected), however it creates a pytorcn tensor in newer version - this is just really blizzard and I couln;t find relevant information about it 
```python
import torch
print(f"NumPy version: {np.__version__}")
ts = np.linspace(0, torch.tensor(999), 51)
print(type(ts))
```
=> fix singlestep dpm tests

examples/community/README.md, examples/community/matryoshka.py, src/diffusers/dependency_versions_table.py
[According to the latest fixes in the original repo.](https://github.com/apple/ml-mdm/pull/21)
@yiyixuxu @sayakpaul @pcuenca @a-r-r-o-w
@MultiPath @Shuangfei @luke-carlson
=> Fix `schedule_shifted_power` usage in 🪆Matryoshka Diffusion Models

examples/controlnet/README_sd3.md, examples/controlnet/train_controlnet_sd3.py
This is a follow-up PR for https://github.com/huggingface/diffusers/pull/9249 to use the make_image_grid() utility function from diffusers.utils and use checkpoint on the Hub.
=> Update sd3 controlnet example

src/diffusers/utils/hub_utils.py
When using sharded checkpoints with gated repositories we get an error because we don't pass the token to the `model_info` function. This PR fixes this.
=> [Fix] Using sharded checkpoints with gated repositories

docs/source/en/quantization/bitsandbytes.md, src/diffusers/models/model_loading_utils.py, src/diffusers/quantizers/__init__.py, src/diffusers/quantizers/auto.py, src/diffusers/quantizers/base.py, src/diffusers/quantizers/bitsandbytes/bnb_quantizer.py, tests/quantization/bnb/test_4bit.py, tests/quantization/bnb/test_mixed_int8.py
1. Takes care of https://github.com/huggingface/diffusers/pull/9213#discussion_r1802812384
2. Move the test repos to `hf-internal-testing`
3. Check bnb param shape
4. Other minor nits
=> [bitsandbbytes] follow-ups

src/diffusers/pipelines/pipeline_loading_utils.py, tests/pipelines/test_pipeline_utils.py
Caught during our release process. The following snippet fails 
```
python -c "from diffusers import DiffusionPipeline; pipe = DiffusionPipeline.from_pretrained('fusing/unet-ldm-dummy-update'); pipe()"
```
This is because:
https://huggingface.co/fusing/unet-ldm-dummy-update/tree/main
Doesn't have components in subfolders (which is what we usually expect for trying to load pipelines). The `is_safetensors_compatible` check was defaulting to True here because there were no components to iterate over. 
Changing so we have an additional check to handle this case by checking the main dir in the repo for safetensor files as well if there are no component folders. …
=> is_safetensors_compatible fix

src/diffusers/utils/testing_utils.py
We should check `accelerate` rather than `peft`. I think this is a typo. Please have a review. 
@sayakpaul
=> fix bug in `require_accelerate_version_greater`

examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_sd3.py
small updates to model card saving
=> [SD3-5 dreambooth lora] update model cards

.github/workflows/push_tests.yml, tests/lora/test_lora_layers_flux.py, tests/lora/test_lora_layers_sd.py, tests/lora/test_lora_layers_sdxl.py
* Mark LoRA integration tests as nightly. 
* Remove "slow" note from the job names as they are not slow tests.
=> Some minor updates to the nightly and push workflows

src/diffusers/models/attention_processor.py, src/diffusers/training_utils.py
The original code will output error that torch_npu has no attribute empty_cache
=> [bugfix] bugfix for npu free memory

examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py, examples/controlnet/train_controlnet_flux.py, examples/dreambooth/train_dreambooth_flux.py, examples/dreambooth/train_dreambooth_lora_flux.py, src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py, src/diffusers/pipelines/flux/pipeline_flux_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_inpaint.py
This PR refactors the FLUX-related pipelines to improve clarity and consistency, particularly in regards to height and width determination. The changes align the implementation more closely with other pipelines in the library, enhancing overall code coherence and maintainability.
The original code obscured the details of how latents packing affects resolution, but this change makes the process more transparent and easier to understand.
@yiyixuxu  @asomoza
=> [refactor] enhance readability of flux related pipelines

src/diffusers/models/autoencoders/autoencoder_kl_allegro.py
Quick fix for `local_batch_size` parameter. Forgot removing it for `forward`. I'm working on the refactor we discussed internally in a separate branch. Will push those changes later. This is to unblock #9808
@sayakpaul
=> Allegro VAE fix

examples/research_projects/flux_lora_quantization/train_dreambooth_lora_flux_miniature.py
* Adds `AdEMAMix`: https://hf.co/papers/2409.03137. 
* Multiple fixes and small nits.
=> [training] fixes to the quantization training script and add AdEMAMix optimizer as an option

examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py, examples/cogvideo/train_cogvideox_image_to_video_lora.py, examples/cogvideo/train_cogvideox_lora.py, examples/dreambooth/train_dreambooth_flux.py, examples/dreambooth/train_dreambooth_lora_flux.py, examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/dreambooth/train_dreambooth_sd3.py, examples/research_projects/flux_lora_quantization/train_dreambooth_lora_flux_miniature.py, examples/research_projects/scheduled_huber_loss_training/dreambooth/train_dreambooth_lora_sdxl.py, examples/research_projects/sd3_lora_colab/train_dreambooth_lora_sd3_miniature.py
=> [training] use the lr when using 8bit adam.

src/diffusers/training_utils.py, tests/others/test_ema.py
Fixes #9764 Fixes EMAModel "from_pretrained" method
@yiyixuxu
=> Fixes EMAModel "from_pretrained" method

src/diffusers/training_utils.py
Fixes #9567 
@a-r-r-o-w @stevhliu
=> Refac training utils.py

docs/source/en/training/distributed_inference.md
This commit removes a duplicated comma in distributed_inference.md, which causes syntax error.
@stevhliu  @sayakpaul
=> Fix: Remove duplicated comma in distributed_inference.md

examples/dreambooth/train_dreambooth_sd3.py
Fixes #9773
Updated `_encode_prompt_with_clip` and `encode_prompt in train_dreamboth_sd3` according to train_dreamboth_lora_sd3 for consistency
@sayakpaul @a-r-r-o-w
=> Updated _encode_prompt_with_clip and encode_prompt in train_dreamboth_sd3

src/diffusers/models/hooks.py, src/diffusers/pipelines/allegro/pipeline_allegro.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox_fun_control.py, src/diffusers/pipelines/pipeline_utils.py, src/diffusers/pipelines/pyramid_broadcast_utils.py
Introduces accelerate-like hook support, which would be useful for:
- Partial CPU Offloading
- Cache Offloading in VAE
- Pyramid Attention Broadcast (#9562) attention state caching
- Split inference across non-channel dims
- Intermediate layer output caching for conditions that don't change between inference steps
Internal discussion: https://huggingface.slack.com/archives/C03HBN1C8CW/p1730123963082119
(Most of the dicussion is private convo b/w Dhruv and me, so I'll summarize and share that soon)
This is just a prototype/test for how the hook-based implementation would look like for PAB. Taking a look at making compatible with `torch.compile` soon.
cc @DN6 @yiyixuxu @sayakpaul
=> Pyramid Attention Broadcast rewrite + introduce hooks

src/diffusers/utils/dynamic_modules_utils.py
Fixes #9798 Replaced shutil.copy with shutil.copyfile
=> [fix] Replaced shutil.copy with shutil.copyfile

src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py, src/diffusers/pipelines/flux/pipeline_flux_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_inpaint.py
Reverts huggingface/diffusers#9817
Because it breaks `enable_model_cpu_offload()` and `enable_sequential_cpu_offload()` for Flux. https://github.com/huggingface/diffusers/issues/9895
=> Revert "[Flux] reduce explicit device transfers and typecasting in flux."

src/diffusers/pipelines/mochi/pipeline_output.py
The autodocs are incorrect as a result of this oversight in the header
Mochi is the correct pipeline type
originally 
Co-authored-by: Dhruv Nair 
Co-authored-by: yiyixuxu 
@yiyixuxu 
@stevhliu @sayakpaul
=> Correct pipeline_output.py to the type Mochi

src/diffusers/loaders/textual_inversion.py
Closes the PR [#9087](https://github.com/huggingface/diffusers/pull/9087) and Issue [#9027](https://github.com/huggingface/diffusers/issues/9027). I've only updated the docstrings to not break anything. Please let me know if any improvements are needed and I will make the necessary changes.
cc: @yiyixuxu
=> Fixed Nits in Docs and Example Script

src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox_fun_control.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox_video2video.py
CogVideoX 1.5 models use a slightly different RoPE implementation compared to 1.0. When we merged the CogVideoX 1.5 PR, this was the status of RoPE implementations:
- 1.0 T2V and I2V used 1.0 RoPE implementation
- 1.5 I2V used 1.5 RoPE implementation
- 1.5 T2V used 1.0 RoPE implementation (inconsistent)
All models still worked as expected and there weren't any bugs. This PR just makes sure that 1.5 T2V uses 1.5 RoPE implementation (the reason why it still worked before is because linspace and slice implementation are equivalent at the 1360x768 resolution, which is the only resolution 1.5 T2V supports, but differ otherwise). The 1.5 T2V needs to use sliced implementation though to keep things consistent with the original code base (even though the outputs match with 1.0 implementation). …
=> Make CogVideoX RoPE implementation consistent

docker/diffusers-onnxruntime-cuda/Dockerfile, docker/diffusers-pytorch-compile-cuda/Dockerfile, docker/diffusers-pytorch-cpu/Dockerfile, docker/diffusers-pytorch-cuda/Dockerfile, docker/diffusers-pytorch-xformers-cuda/Dockerfile, setup.py, src/diffusers/dependency_versions_table.py
=> [CI] Unpin torch<2.5 in CI

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_sde.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_euler_discrete.py, src/diffusers/schedulers/scheduling_heun_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py, src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py, src/diffusers/schedulers/scheduling_lms_discrete.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unipc_multistep.py, tests/schedulers/test_scheduler_deis.py, tests/schedulers/test_scheduler_dpm_multi.py, tests/schedulers/test_scheduler_dpm_multi_inverse.py, tests/schedulers/test_scheduler_dpm_sde.py, tests/schedulers/test_scheduler_dpm_single.py, tests/schedulers/test_scheduler_euler.py, tests/schedulers/test_scheduler_heun.py, tests/schedulers/test_scheduler_kdpm2_ancestral.py, tests/schedulers/test_scheduler_kdpm2_discrete.py, tests/schedulers/test_scheduler_lms.py, tests/schedulers/test_scheduler_sasolver.py, tests/schedulers/test_scheduler_unipc.py
- `log_sigmas` moved out of `karras` branch
- `_convert_to_exponential` and `_convert_to_beta` return `np.ndarray` for consistency with `_convert_to_karras` and other code
- Just use `num_inference_steps` for input to `_convert_to_exponential` and `_convert_to_beta`, not all schedulers update `self.num_inference_steps`
Fixes #9951
=> Fix beta and exponential sigmas + add tests

examples/dreambooth/README_flux.md, examples/dreambooth/README_sd3.md, examples/dreambooth/README_sdxl.md
Fixes #7728
Currently, if there are network issues (e.g., using a network without VPN in certain regions) or if the user is not logged into W&B, the process can terminate unexpectedly without error messages (this may confuses some users). On one of my computers, it simply displayed "died," while on another, I encountered the following output:
This issue can be resolved by checking the network connection or logging into W&B (if required).
To improve user experience, I've added a few lines of code to provide better guidance for users who may not be familiar with W&B. This ensures that users encountering these issues are informed.
=> Add prompt about wandb in examples/dreambooth/readme.

src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
Add `beta`, `exponential` and `karras` sigmas to `FlowMatchEulerDiscreteScheduler`.
```python
from diffusers.schedulers import FlowMatchEulerDiscreteScheduler
def calculate_shift(
image_seq_len,
base_seq_len: int = 256,
max_seq_len: int = 4096,
base_shift: float = 0.5,
max_shift: float = 1.16,
):
m = (max_shift - base_shift) / (max_seq_len - base_seq_len)
b = base_shift - m * base_seq_len
mu = image_seq_len * m + b
return mu
image_seq_len = 4096
mu = calculate_shift(image_seq_len)
num_inference_steps = 8
sigmas = np.linspace(1.0, 1 / num_inference_steps, num_inference_steps)
flow_match = FlowMatchEulerDiscreteScheduler.from_pretrained("black-forest-labs/FLUX.1-dev", subfolder="scheduler", use_beta_sigmas=True)
flow_match.set_timesteps(sigmas=sigmas, mu=mu) …
```
=> Add `beta`, `exponential` and `karras` sigmas to `FlowMatchEulerDiscreteScheduler`

docs/source/en/api/pipelines/flux.md
We recently migrated the image_gen_aux library owner, this PR just changes the url to the correct one
@yiyixuxu @a-r-r-o-w
=> Change image_gen_aux repository URL

src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_control.py, src/diffusers/pipelines/flux/pipeline_flux_control_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py, src/diffusers/pipelines/flux/pipeline_flux_fill.py, src/diffusers/pipelines/flux/pipeline_flux_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_inpaint.py
This PR adds `sigmas` argument to Flux pipelines and removes `timesteps` argument as passing `timesteps` to `FlowMatch` schedulers is currently unsupported.
Fixes #10080
@yiyixuxu @asomoza
=> Add `sigmas` to Flux pipelines

docs/source/en/conceptual/evaluation.md
After reviewing #9023, I have made minor improvements to the scripts to ensure they run smoothly. Please let me know if any improvements are needed and I will make the necessary changes.
[documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
@stevhliu
@sayakpaul
=> Fixed Nits in Evaluation Docs 

docs/source/en/training/create_dataset.md, docs/source/ko/api/pipelines/stable_diffusion/stable_diffusion_xl.md, docs/source/ko/training/create_dataset.md, docs/source/ko/training/lora.md
Fix a link in the docs, which used to be `hf.co/docs/datasets` and will be directed to `https://huggingface.co/docs/diffusers/main/en/training/hf.co/docs/datasets`.
@stevhliu @sayakpaul
=> fix link in the docs

src/diffusers/models/controlnets/controlnet_sd3.py, src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet.py
1. this PR fix the offloading for sd3.5 controlnet, so it behaviors similar to other controlnet, (controlnet + transformer both stay in GPU during the entire denosing loop). Let me know if it is ok @vladmandic, if you want to offload/load controlnet on each iteration, I'm happy to run the experiment to see what's the trade off too, I think it will be very slow
2. I should have considered the offloading/device map use case and added the pos_embed weights to controlnet checkpoint so we do not handle this specially like this; made a note about this
3. device_map is not working for all controlnet, (all use cases when an components are passed to the from_pretrained). I will fix this in a follow up PR 
```python
import torch
from diffusers import StableDiffusion3ControlNetPipeline, …
```
=> fix offloading for sd3.5 controlnets

src/diffusers/loaders/single_file_utils.py
Pos Embed shape is different in SD 3.5 leading to #10016. This PR fixes it.  
=> [Single File] Fix SD3.5 single file loading

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
https://github.com/huggingface/diffusers/issues/10085#issuecomment-2511977629 for some further details.
Fixes #10085
cc @sayakpaul @japppie
=> Fix `num_images_per_prompt>1` with Skip Guidance Layers in `StableDiffusion3Pipeline`

src/diffusers/loaders/single_file_model.py
In the case where a user is not logged in and is passing token via `from_single_file`, auto fetching the config won't work for private or gated repos because we don't pass the token to `cls.load_config`. 
#10057
=> [Single File] Pass token when fetching interpreted config

src/diffusers/models/upsampling.py
Fixes #10040.
As described in https://github.com/pytorch/pytorch/issues/141831, there is a silent bug in PyTorch (CUDA) that causes the result of the upsampling operation to be wrong when the output size is beyond a threshold.
cc @sayakpaul @asomoza as they are involved in #10040. In addition to that issue, I think the silent failure mode could come up in other cases as well and would be difficult to track.
=> Interpolate fix on cuda for large output tensors

docs/source/en/tutorials/basic_training.md, docs/source/ko/tutorials/basic_training.md, src/diffusers/configuration_utils.py, src/diffusers/models/modeling_flax_utils.py, src/diffusers/models/modeling_utils.py, src/diffusers/pipelines/pipeline_flax_utils.py, src/diffusers/pipelines/pipeline_utils.py, src/diffusers/utils/hub_utils.py
Until now, all repos were public by default when created without passing the `private` argument. This meant that passing `private=False` or `private=None` was strictly the same. This is not the case anymore. Enterprise Hub offers organizations to set a default visibility setting for new repos. This is useful for organizations forbidding public repos for security matters. This PR mostly updates some docstrings + default values so that `private=None` is always passed when user don't set it manually.
This PR doesn't create any breaking change. The real update has been done server-side when introducing the new Enterprise Hub feature. Related to https://github.com/huggingface/huggingface_hub/pull/2679.
=> Let server decide default repo visibility

src/diffusers/pipelines/pipeline_utils.py
This is useful when exporting a pipeline, and allows a compiler to avoid trying to compile away tqdm when it is explicitly excluded.
=> Avoid compiling a progress bar.

tests/pipelines/stable_diffusion_3/test_pipeline_stable_diffusion_3.py, tests/pipelines/test_pipelines_common.py
This PR adds `test_skip_guidance_layers` to SD3 pipeline to check `skip_guidance_layers` with `num_images_per_prompt`.
=> Test `skip_guidance_layers` in SD3 pipeline

src/diffusers/pipelines/aura_flow/pipeline_aura_flow.py, src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet.py, src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet_inpainting.py, src/diffusers/pipelines/lumina/pipeline_lumina.py, src/diffusers/pipelines/pag/pipeline_pag_sd_3.py, src/diffusers/pipelines/pag/pipeline_pag_sd_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
Part of the fixes for #10113.
Pipelines in this PR all use FlowMatch scheduler which does not currently support passing timesteps so the timesteps argument is non-functional, we replace timesteps argument with `sigmas` which is currently supported by the scheduler. See #10080 #10112 for example use case of passing `sigmas`.
=> Add `sigmas` to pipelines using FlowMatch

src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video_controlnet.py, src/diffusers/pipelines/cogvideo/pipeline_cogvideox_video2video.py
Removes unnecessary duplicate checks on length of generator, as it is already checked in a previous condition
=> Remove duplicate checks for len(generator) != batch_size when generator is a list

src/diffusers/utils/torch_utils.py
when generating 1024*1024 image with bfloat16 dtype, there is an exception:
File "/opt/conda/lib/python3.10/site-packages/diffusers/utils/torch_utils.py", line 107, in fourier_filter
x_freq = fftn(x, dim=(-2, -1))
RuntimeError: Unsupported dtype BFloat16
fix a bug.
@hlky
=> fixed a dtype bfloat16 bug in torch_utils.py

src/diffusers/loaders/unet.py, tests/models/unets/test_models_unet_2d_condition.py
Should have been done in https://github.com/huggingface/diffusers/pull/9712 but somehow got missed.
=> [LoRA] depcrecate save_attn_procs().

src/diffusers/loaders/single_file_model.py
Revealed in #10135 that we can't load config from a provided revision. This is handy for testing single file changes on our weights PRs and has helped for both DCAE and LTX integration
=> [Single file] Support `revision` argument when loading single file config

src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/models/autoencoders/autoencoder_kl_ltx.py, src/diffusers/models/transformers/transformer_ltx.py
With Diffusers weights:
```python
import torch
from diffusers import LTXImageToVideoPipeline
from diffusers.utils import export_to_video, load_image
pipe = LTXImageToVideoPipeline.from_pretrained("Lightricks/LTX-Video", torch_dtype=torch.bfloat16, revision="refs/pr/32")
image = load_image("https://huggingface.co/datasets/a-r-r-o-w/tiny-meme-dataset-captioned/resolve/main/images/8.png")
prompt = "A young girl stands calmly in the foreground, looking directly at the camera, as a house fire rages in the background. Flames engulf the structure, with smoke billowing into the air. Firefighters in protective gear rush to the scene, a fire truck labeled '38' visible behind them. The girl's neutral expression contrasts sharply with the chaos of the fire, creating a poignant and …
```
=> [Single File] LTX support for loading original weights

src/diffusers/image_processor.py
Closes #10158 
* Use multiplication instead of division
* Add fast path when denormalizing all or none of the images
As suggested by @yiyixuxu, this is a smaller PR than #10159 and only adds the fast path in the all-or-nothing scenario. leaving the selective denormalization as-is in the heterogeneous case.
=> Improve post-processing performance

examples/community/pipeline_flux_rf_inversion.py
=> [community pipeline rf-inversion] - fix example in doc

setup.py, src/diffusers/dependency_versions_table.py, src/diffusers/pipelines/pipeline_loading_utils.py, src/diffusers/pipelines/pipeline_utils.py, src/diffusers/pipelines/transformers_loading_utils.py
This PR adds a workaround to load `transformers` components without passing DDUF entries to `transformers`.
As mentioned with @LysandreJik on [slack](https://huggingface.slack.com/archives/C0821RXC9T5/p1733412799640689?thread_ts=1733372897.316429&cid=C0821RXC9T5) (private), modifying `transformers` internals to load from a DDUF archive (https://github.com/huggingface/transformers/pull/35093) is going to be hard to scale. Also it makes `transformers` internals heavily depends on `diffusers`'s DDUF format which we don't even know yet if it will be adopted by the community ( :crossed_fingers: ). On slack we briefly discussed a way to update `transformers` in such a way that loading from a folder or a zip directory works the same but even that is a hazardous non-trivial change. After further …
=> DDUF - Load transformers components manually

src/diffusers/models/controlnets/__init__.py, src/diffusers/models/controlnets/controlnet_union.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl_img2img.py
https://github.com/huggingface/diffusers/pull/10131#issuecomment-2537167847
=> refactor  StableDiffusionXLControlNetUnion

examples/flux-control/README.md, examples/flux-control/train_control_flux.py, examples/flux-control/train_control_lora_flux.py
Set model offloading to be optional in args, which will reduce the training memory usage but also reduce the training speed.
@sayakpaul
=> Add offload option in flux-control training

docs/source/en/api/loaders/lora.md
We can easily catch these during the PRs with https://github.com/huggingface/diffusers/pull/7763.
=> [Docs] add rest of the lora loader mixins to the docs.

src/diffusers/pipelines/pag/pipeline_pag_sana.py
To match usages of `_apply_perturbed_attention_guidance` we pass `t` instead of `timestep` (which is expanded).
```
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```
=> Use `t` instead of `timestep` in `_apply_perturbed_attention_guidance`

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
Adds `dynamic_shifting` to SD3.
```python
import torch
from diffusers import StableDiffusion3Pipeline, FlowMatchEulerDiscreteScheduler
pipe = StableDiffusion3Pipeline.from_pretrained(
"stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16
)
pipe.scheduler = FlowMatchEulerDiscreteScheduler.from_config(pipe.scheduler.config, use_dynamic_shifting=True)
```
We can pass a custom `mu` value
```python
image = pipe(prompt, ..., mu=...).images[0]
```
When not provided `mu` is calculated the same as in Flux.
```python
import torch
from diffusers import StableDiffusion3Pipeline, FlowMatchEulerDiscreteScheduler, FlowMatchHeunDiscreteScheduler
prompt = "A cat holding a sign that says hello world"
pipe = StableDiffusion3Pipeline.from_pretrained( …
```
=> Add `dynamic_shifting` to SD3

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_dpmsolver_singlestep.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
Error when using `use_flow_sigmas` due to missing `.copy()`
```
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().)
```
=> Fix `use_flow_sigmas`

src/diffusers/pipelines/allegro/pipeline_allegro.py
Allegro doesn't support VAE without tiling and is missing `enable_vae_tiling` etc on the pipeline.
https://github.com/huggingface/diffusers/blob/cef0e3677e9a32fcf27cdfccfdf809f689a6f908/src/diffusers/models/autoencoders/autoencoder_kl_allegro.py#L851
Note that the default `num_inference_steps=100` is very slow (~1h on A40, only slightly faster on A6000 Ada) so the example could have the value changed as well.
=> Add enable_vae_tiling to AllegroPipeline, fix example

src/diffusers/schedulers/scheduling_repaint.py
Algorithm 1 Line 5 https://arxiv.org/pdf/2201.09865.pdf
$$x_{t-1}^{\text{known}} = \sqrt{\bar{\alpha}_t} x_0 + (1 - \bar{\alpha}_t) \epsilon$$
Current code
```python
prev_known_part = (alpha_prod_t_prev**0.5) * original_image + ((1 - alpha_prod_t_prev) ** 0.5) * noise
```
Square root of `(1 - alpha_prod_t_prev)` is incorrect.
Fixes #9900
cc @yiyixuxu
=> Fix RePaint Scheduler

src/diffusers/pipelines/auto_pipeline.py
```
from diffusers import AutoPipelineForText2Image, AutoPipelineForImage2Image, AutoPipelineForInpainting, ControlNetUnionModel
controlnet = ControlNetUnionModel.from_pretrained("OzzyGT/controlnet-union-promax-sdxl-1.0")
pipe_txt2img = AutoPipelineForText2Image.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", controlnet=controlnet)
print(type(pipe_txt2img))
pipe_img2img = AutoPipelineForImage2Image.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", controlnet=controlnet)
print(type(pipe_img2img))
pipe_inpainting2img = AutoPipelineForInpainting.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", controlnet=controlnet)
print(type(pipe_inpainting2img))
```
`from_pipe` will be done in a follow-up.
Anyone in the community is free to review the PR once the tests …
=> Add ControlNetUnion to AutoPipeline from_pretrained

docs/source/en/api/attnprocessor.md, src/diffusers/models/attention_processor.py
Adds missing `AttnProcessor` classes to the API docs.
=> [docs] Add missing AttnProcessors

tests/quantization/torchao/test_torchao.py
We decided to not support some quantization shorthands (such as `{dtype}_aXbY`). I forgot to remove/rename those in the tests, which will cause the tests to fail unless updated correctly
=> [tests] Remove/rename unsupported quantization torchao type

docs/source/en/tutorials/using_peft_for_inference.md
Addresses [comment](https://github.com/huggingface/diffusers/issues/9325#issuecomment-2542969464) about better documenting the `delete_adapters` function.
=> [docs] delete_adapters()

src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
```python
from diffusers import FlowMatchEulerDiscreteScheduler
scheduler = FlowMatchEulerDiscreteScheduler()
scheduler.set_timesteps(20)
print(scheduler.sigmas, scheduler.timesteps)
"""
tensor([1.0000, 0.9474, 0.8948, 0.8423, 0.7897, 0.7371, 0.6845, 0.6319, 0.5794,
0.5268, 0.4742, 0.4216, 0.3691, 0.3165, 0.2639, 0.2113, 0.1587, 0.1062,
0.0536, 0.0010, 0.0000]) tensor([1000.0000,  947.4211,  894.8421,  842.2632,  789.6843,  737.1052,
684.5263,  631.9474,  579.3684,  526.7895,  474.2105,  421.6316,
369.0526,  316.4737,  263.8947,  211.3158,  158.7368,  106.1579,
53.5789,    1.0000])
"""
scheduler.set_shift(7.0)
scheduler.set_timesteps(20)
print(scheduler.sigmas, scheduler.timesteps)
"""
tensor([1.0000, 0.9921, 0.9835, 0.9739, 0.9633, 0.9515, 0.9382, 0.9232, 0.9060,
0.8863, 0.8633, 0.8361, …
```
=> Add `set_shift` to FlowMatchEulerDiscreteScheduler

examples/community/pipeline_hunyuandit_differential_img2img.py, src/diffusers/models/embeddings.py, src/diffusers/pipelines/controlnet_hunyuandit/pipeline_hunyuandit_controlnet.py, src/diffusers/pipelines/hunyuandit/pipeline_hunyuandit.py, src/diffusers/pipelines/pag/pipeline_pag_hunyuandit.py
Refactors `get_2d_rotary_pos_embed` to use `torch` instead of `numpy`, and adds `device` argument so that tensors can be created on e.g. `cuda`.
Usage of `get_2d_rotary_pos_embed` in HunyuanDiT pipelines is updated to pass `device`.
`torch` and `numpy` versions match numerically.
<details>
<summary>Reproduction</summary>
```python
from diffusers.models.embeddings import get_2d_rotary_pos_embed
import torch
def get_resize_crop_region_for_grid(src, tgt_size):
th = tw = tgt_size
h, w = src
r = h / w
if r > 1:
resize_height = th
resize_width = int(round(th / h * w))
else:
resize_width = tw
resize_height = int(round(tw / w * h))
crop_top = int(round((th - resize_height) / 2.0))
crop_left = int(round((tw - resize_width) / 2.0))
return (crop_top, crop_left), (crop_top + resize_height, crop_left …
```
=> Use `torch` in `get_2d_rotary_pos_embed`

src/diffusers/schedulers/scheduling_deis_multistep.py, src/diffusers/schedulers/scheduling_dpmsolver_multistep_inverse.py, src/diffusers/schedulers/scheduling_sasolver.py, src/diffusers/schedulers/scheduling_unipc_multistep.py
`sigma_last` is concatenated in different places across schedulers so this was missed for some schedulers with the recent `use_flow_sigmas`, also missed with `use_exponential_sigmas` and `use_beta_sigmas` in `DPMSolverMultistepInverseScheduler`.
Fixes #10266
=> Fix sigma_last with use_flow_sigmas

src/diffusers/loaders/single_file_utils.py
=> [Single File] Add single file support for Flux Canny, Depth and Fill

examples/dreambooth/README_sana.md
As pointed out by @lawrence-cj.
=> [chore] Update README_sana.md to update the default model

src/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py, src/diffusers/models/transformers/transformer_hunyuan_video.py, tests/models/autoencoders/test_models_autoencoder_hunyuan_video.py
While training loras, found some things that slipped by when we merged HunyuanVideo
- Enables gradient checkpointing in transformer
- Fixes the `encode` implementation in VAE
- Lowers the default frame tile size. A tile size of 64 requires ~24 GB memory, while a tile size of 16 requires only ~8 GB at 768x512 resolution
- Adds docstring for transformer
=> Hunyuan VAE tiling fixes and transformer docs

src/diffusers/pipelines/auto_pipeline.py
https://github.com/huggingface/diffusers/pull/10192#issuecomment-2551372681
```python
from diffusers import AutoPipelineForText2Image, AutoPipelineForImage2Image, AutoPipelineForInpainting
import torch
pipe = AutoPipelineForInpainting.from_pretrained("black-forest-labs/FLUX.1-Depth-dev", torch_dtype=torch.bfloat16)
print(pipe.__class__.__name__)
pipe = AutoPipelineForImage2Image.from_pretrained("black-forest-labs/FLUX.1-Depth-dev", torch_dtype=torch.bfloat16)
print(pipe.__class__.__name__)
pipe = AutoPipelineForText2Image.from_pretrained("black-forest-labs/FLUX.1-Depth-dev", torch_dtype=torch.bfloat16)
print(pipe.__class__.__name__)
pipe = AutoPipelineForInpainting.from_pipe(pipe)
print(pipe.__class__.__name__)
pipe = AutoPipelineForImage2Image.from_pipe(pipe) …
```
=> Add Flux Control to AutoPipeline

src/diffusers/models/transformers/transformer_mochi.py
Thanks to @jmahajan117 for flagging. 
Ran this test on DGX and it passes 
https://github.com/huggingface/diffusers/blob/7667cfcb41dfeb8f217e4314dcf2d561b8ca41d2/tests/models/test_modeling_common.py#L1094
Example code: 
```python
import torch
from diffusers import MochiPipeline, MochiTransformer3DModel
model_id = "genmo/mochi-1-preview"
transformer = MochiTransformer3DModel.from_pretrained(
model_id,
subfolder="transformer",
device_map="auto",
max_memory={0: "24GB", 1: "24GB"}
)
print(transformer.hf_device_map)
pipe = MochiPipeline.from_pretrained(model_id,  transformer=transformer)
pipe.enable_vae_tiling()
with torch.autocast(device_type="cuda", dtype=torch.bfloat16, cache_enabled=False):
frames = pipe( …
```
=> Allow Mochi Transformer to be split across multiple GPUs

src/diffusers/utils/hub_utils.py
Discussed internally https://huggingface.slack.com/archives/C07S1S33BQD/p1734513644104739
Works if we just let `huggingface_hub` handle `local_files_only`. Also tested with the cases from #8913 and #8898
```python
from huggingface_hub import snapshot_download
from diffusers import UNet2DConditionModel
ckpt_path = snapshot_download("hf-internal-testing/unet2d-sharded-dummy-subfolder")
loaded_model = UNet2DConditionModel.from_pretrained(ckpt_path, subfolder="unet", local_files_only=True)
```
cc @yiyixuxu
=> Fix `local_files_only` for checkpoints with shards

tests/lora/utils.py
Sorry :/ I misread the failing tests. There were two failing tests in https://github.com/huggingface/diffusers/pull/10254 - one from wrong lora test changes and one from timeout. I only saw the timeout ones and missed the lora related ones, so CI was in a broken state.
The correct fix is to default the `subfolder` parameter to an empty string
=> Fix failing lora tests after HunyuanVideo lora

src/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py
The following error is raised on Hopper GPUs if the tensors are non-contiguous:
<details>
<summary> traceback </summary>
```bash
ERROR:finetrainers:An error occurred during training: Unsupported memory format for group normalization: ChannelsLast3d
ERROR:finetrainers:Traceback (most recent call last):
File "/fsx/aryan/finetrainers/train.py", line 34, in main
trainer.train()
File "/fsx/aryan/finetrainers/finetrainers/trainer.py", line 375, in train
latent_conditions = self.model_config["prepare_latents"](
File "/fsx/aryan/finetrainers/finetrainers/hunyuan_video/hunyuan_video_lora.py", line 168, in prepare_latents
latents = vae.encode(image_or_video).latent_dist.sample(generator=generator)
File "/fsx/aryan/diffusers/src/diffusers/utils/accelerate_utils.py", line 46, in wrapper
return …
```
=> Make tensors in ResNet contiguous for Hunyuan VAE

docs/source/en/api/pipelines/ltx_video.md, src/diffusers/loaders/single_file_utils.py
Some GGUF checkpoints remove the `model.diffusion_model` prefix from the original LTX file. This PR accounts for that change.  
=> [Single File] Add GGUF support for LTX

src/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video.py
docs: fix a mistake in docstring
=> docs: fix a mistake in docstring

src/diffusers/pipelines/stable_audio/pipeline_stable_audio.py
Parameter `initial_audio_waveforms` when passed `torch.Tensor` as described [here](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_audio#diffusers.StableAudioPipeline.__call__.initial_audio_waveforms) raises `TypeError: new_zeros(): argument 'size' failed to unpack the object at pos 3 with error "type must be tuple of ints,but got float"`
[Notebook to Reproduce the Error](https://colab.research.google.com/drive/1xrkJe7k4cfqRCye2kQScncRZmzkrBu46?usp=sharing)
In function `prepare_latents`:
```python
audio_vae_length = self.transformer.config.sample_size * self.vae.hop_length
```
`audio_vae_length` evaluates to a `float` because `self.transformer.config.sample_size` returns a `float`
```python
audio = initial_audio_waveforms.new_zeros(audio_shape)
``` …
=> [BUG FIX] [Stable Audio Pipeline] Resolve torch.Tensor.new_zeros() TypeError in function prepare_latents caused by audio_vae_length

scripts/convert_sana_to_diffusers.py
We release 2K model of Sana. So I add the ckpt and 2K related code into the conversion script.
Cc: @a-r-r-o-w @sayakpaul
=> [Sana]add 2K related model for Sana

tests/others/test_ema.py
[Torch CUDA Tests (others)](https://github.com/huggingface/diffusers/actions/runs/12434081220/job/34717007693#logs) has been failing from EMAModel.
```
FAILED tests/others/test_ema.py::EMAModelTests::test_from_pretrained - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
`ema_unet` is on the correct device as it's created from `unet` which is moved to `torch_device`
https://github.com/huggingface/diffusers/blob/a6288a5571dbc63a03dc761a4d5300fcec61a04b/tests/others/test_ema.py#L39-L41
`loaded_ema_unet` is on CPU.
This matches `torch.allclose` call with `original_param, loaded_param` and the order of the error `cuda:0 and cpu!`. …
=> Fix EMAModel test_from_pretrained

docs/source/en/api/models/autoencoder_kl_hunyuan_video.md, docs/source/en/api/models/hunyuan_video_transformer_3d.md, docs/source/en/api/pipelines/hunyuan_video.md, src/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video.py
Context: https://huggingface.slack.com/archives/C065E480NN9/p1734852065059239?thread_ts=1734672468.363879&cid=C065E480NN9
As we've been unable to merge the [diffusers-format](https://huggingface.co/tencent/HunyuanVideo/discussions/18) weights in for about a week now, we've uploaded the weights to a community org [here](https://huggingface.co/hunyuanvideo-community/HunyuanVideo) because we need it out before going into release. The PR will still remain open and hopefully we can establish better communication with the team for weights to be merged sooner.
=> Community hosted weights for diffusers format HunyuanVideo weights

src/diffusers/pipelines/kandinsky/pipeline_kandinsky_combined.py
[Torch Pipelines CUDA Tests (kandinsky)](https://github.com/huggingface/diffusers/actions/runs/12434081220/job/34717118294#logs) is failing due to `enable_sequential_cpu_offload` changing
```
FAILED tests/pipelines/kandinsky/test_kandinsky_combined.py::KandinskyPipelineInpaintCombinedFastTests::test_sequential_offload_forward_pass_twice - TypeError: KandinskyInpaintCombinedPipeline.enable_sequential_cpu_offload() got an unexpected keyword argument 'device'
```
The combined pipeline overrides `enable_sequential_cpu_offload` to set it on both components and had the outdated signature.
=> Fix enable_sequential_cpu_offload in test_kandinsky_combined

docs/source/en/api/models/sana_transformer2d.md, docs/source/en/api/pipelines/sana.md, scripts/convert_sana_to_diffusers.py, src/diffusers/models/transformers/sana_transformer.py, src/diffusers/pipelines/pag/pipeline_pag_sana.py, src/diffusers/pipelines/sana/pipeline_sana.py, tests/models/test_modeling_common.py
This PR fix the Positional Embedding missing bug. We re-introduce PE into > 2K resolution models. So we need to add PE back in `SanaTransformer2DModel`
Cc: @yiyixuxu @sayakpaul @a-r-r-o-w , thanks in advance for merging this PR to fix the bug.
Before the PR:
After the PR:
=> [Sana bug] bug fix for 2K model config

src/diffusers/models/model_loading_utils.py
Add missing `.shape` in the error message of `.from_single_file()`
@sayakpaul
=> `.from_single_file()` - Add missing `.shape`

examples/dreambooth/test_dreambooth_lora_sana.py, examples/dreambooth/train_dreambooth_lora_sana.py, tests/lora/test_lora_layers_sana.py, tests/pipelines/sana/test_sana.py
* Introduces a test suite for SANA LoRA fine-tuning.
* Fixes the SANA LoRA tests and SANA pipeline tests to use `Gemma2Model` instead of `Gemma2CausalLM`.
* Some QoL fixes to the SANA training script.
=> [SANA LoRA] sana lora training tests and misc.

src/diffusers/models/embeddings.py
Context: https://huggingface.slack.com/archives/C065E480NN9/p1734937335392109?thread_ts=1734935953.846629&cid=C065E480NN9
Fixes test: https://github.com/huggingface/diffusers/actions/runs/12461857058/job/34781970659#step:6:6623
This went uncaught in #10270 because it only happens when `.to()` is not called on a pipeline, or `torch_dtype` is not specified while loading transformer component. The failing lora test does neither, so the alternative branch of code was never tested.
`pos_embedding` is `torch.int64`, which casts `embeds` to `torch.int64` as well unless casted correctly in both branches
=> Fix failing CogVideoX LoRA fuse test

tests/lora/test_lora_layers_cogvideox.py, tests/lora/test_lora_layers_hunyuanvideo.py, tests/lora/test_lora_layers_mochi.py, tests/lora/utils.py, tests/models/test_attention_processor.py, tests/models/transformers/test_models_transformer_mochi.py, tests/models/transformers/test_models_transformer_sana.py
* https://github.com/huggingface/diffusers/pull/9442 should be closed after this PR is merged. 
* Partially fixes https://github.com/huggingface/diffusers/actions/runs/12464038013/job/34787444360#step:6:6735 and skips the SANA offload tests for now.
=> [Tests] Fix more tests sayak

src/diffusers/models/attention_processor.py
When we are working with more than one IP adapter and we apply a mask to the images of an IP adapter, we are required to pass a mask to all the IPs involved.
This PR makes it optional to pass the IP Adapter mask to the attention mechanism if there is no need to apply it to a specific IP Adapter. This solution has already been applied to the Xformers attention mechanism. This PR simply replicates the same solution for the standard SDP attention mechanisms.
This code reproduces both the problem and the solution.
If you run it without xformers active, you will receive the error in the log below.
For SDP you must provide a mask for the style IP (See the commented line in the pipeline call)
With the solution applied it will work for SDP as it already works for Xformers.
```python
import numpy …
```
=> Make passing the IP Adapter mask to the attention mechanism optional

tests/single_file/single_file_testing_utils.py, tests/single_file/test_stable_diffusion_controlnet_img2img_single_file.py, tests/single_file/test_stable_diffusion_controlnet_inpaint_single_file.py, tests/single_file/test_stable_diffusion_controlnet_single_file.py, tests/single_file/test_stable_diffusion_upscale_single_file.py, tests/single_file/test_stable_diffusion_xl_adapter_single_file.py, tests/single_file/test_stable_diffusion_xl_controlnet_single_file.py, tests/single_file/test_stable_diffusion_xl_img2img_single_file.py
The following test cases return `AssertionError: Torch not compiled with CUDA enabled` on XPU. This PR fixes this issue.
```bash
pytest -rA tests/single_file/test_stable_diffusion_xl_adapter_single_file.py::StableDiffusionXLAdapterPipelineSingleFileSlowTests::test_single_file_format_inference_is_same_as_pretrained
pytest -rA tests/single_file/test_stable_diffusion_xl_controlnet_single_file.py::StableDiffusionXLControlNetPipelineSingleFileSlowTests::test_single_file_format_inference_is_same_as_pretrained
pytest -rA tests/single_file/test_stable_diffusion_xl_img2img_single_file.py::StableDiffusionXLImg2ImgPipelineSingleFileSlowTests::test_single_file_format_inference_is_same_as_pretrained
pytest -rA tests/single_file/test_stable_diffusion_xl_img2img_single_file.py::StableDiffusionXLImg2ImgRe …
```
=> [tests] fix `AssertionError: Torch not compiled with CUDA enabled`

examples/flux-control/train_control_flux.py, examples/flux-control/train_control_lora_flux.py
Additionally registers the `out_channels` otherwise, it will be overwritten as the newly set `in_channels` value.
=> [training] fix: registration of out_channels in the control flux scripts.

.github/workflows/nightly_tests.yml, docs/source/en/quantization/torchao.md, src/diffusers/models/modeling_utils.py, src/diffusers/quantizers/torchao/torchao_quantizer.py, tests/quantization/torchao/test_torchao.py
Reverts part of https://github.com/huggingface/diffusers/pull/10256
Currently, we support:
- Serialization/Deserialization from the commonly tested TorchAO dtypes. All quantization types are not exhaustively tested
- Loading sharded/unsharded state dicts WITHOUT device_map. Using device_map calls into accelerate code but this is problematic for reasons stated here https://github.com/huggingface/diffusers/issues/10013, and so we error out. Will be tackled in future release
This PR:
- Errors out if device_map is used
- Skips the device_map tests because they didn't work correctly before, nor do we support it now. I didn't realize they didn't work because we were not checking the weights to be AffineQuantizedTensor's
- Improves the test to ensure both sharded and non-sharded checkpoints are …
=> Fix TorchAO related bugs; revert device_map changes

src/diffusers/pipelines/aura_flow/pipeline_aura_flow.py
=> Add torch_xla support to pipeline_aura_flow.py

src/diffusers/pipelines/sana/pipeline_sana.py
Added torch_xla support in pipeline_sana.py
Fixes #10357 Partially
@hlky @yiyixuxu
=> [Add] torch_xla support to pipeline_sana.py

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
Values like `vae_scale_factor` in pipelines are derived from configurations of component modules e.g. `self.vae_scale_factor = 2 ** (len(self.vae.config.block_out_channels) - 1)`, some pipelines are missing default values when the module is not loaded
```python
self.vae_scale_factor = (
2 ** (len(self.vae.config.block_out_channels) - 1) if hasattr(self, "vae") and self.vae is not None else 8
)
```
This PR adds default values in SD3 pipelines.
Reproduction
```python
from diffusers import StableDiffusion3Img2ImgPipeline
import torch
pipe = StableDiffusion3Img2ImgPipeline.from_pretrained(
"stabilityai/stable-diffusion-3.5-large",
vae=None, # or `tokenizer` or `transformer`
)
```
Anyone in the community is free to review the PR once the tests have passed. Feel free …
=> Default values in SD3 pipelines when submodules are not loaded

examples/dreambooth/train_dreambooth_lora_sd3.py
Fixes https://github.com/huggingface/diffusers/pull/10252. 
Cc: @leisuzz could you give this a try?
=> [training] add ds support to lora sd3.

docs/source/en/api/pipelines/allegro.md, docs/source/en/api/pipelines/aura_flow.md, docs/source/en/api/pipelines/cogvideox.md, docs/source/en/api/pipelines/flux.md, docs/source/en/api/pipelines/hunyuan_video.md, docs/source/en/api/pipelines/latte.md, docs/source/en/api/pipelines/ltx_video.md, docs/source/en/api/pipelines/lumina.md, docs/source/en/api/pipelines/mochi.md, docs/source/en/api/pipelines/sana.md, docs/source/en/api/pipelines/stable_audio.md, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md
Follows up on [discussion](https://huggingface.slack.com/archives/C041M7M98JV/p1730514150341379) about adding a quantization section for big models. Instead of adding it to the individual model doc (for example, `MochiTransformer3DModel`) and the pipeline doc, I think it's more discoverable/cleaner to add it only to the pipeline doc (for example, `MochiPipeline`).
Let me know if this works for you, and then I can add it to the other big models!
=> [docs] Quantization tip

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/text-img2vid.md
Updates video generation guide to showcase newer/modern models (CogVideoX, HunyuanVideo, LTX, Mochi-1).
=> [docs] Video generation update

examples/flux-control/train_control_lora_flux.py
When the training script `examples/flux-control/train_control_lora_flux.py` is resumed from checkpoint using the argument `--resume_from_checkpoint`, it fails with the following error
```
RuntimeError: Error(s) in loading state_dict for FluxTransformer2DModel:
size mismatch for x_embedder.lora_A.default.weight: copying a param with shape torch.Size([64, 128]) from checkpoint, the shape in current model is torch.Size([64, 64]).
```
This is because, while loading the LoRa, it doesn't increase the number of input channels required for Image Control in Flux.
This PR modifies the `load_model_hook` so the number of input channels for the `FluxTransformer2DModel` are doubled before loading the Lora checkpoint.
[documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), …
=> Add correct number of channels when resuming from checkpoint for Flux Control LoRa training

src/diffusers/loaders/lora_pipeline.py, tests/lora/test_lora_layers_flux.py
The current approach of checking for a key with a `base_layer` suffix may lead to a bug when multiple Lora models are loaded. If the first loaded Lora model does not have weights for layer `n`, and the second one does, loading the second model will lead to an error since the transformer state dict currently does not have key `n.base_layer.weight`. So I explicitly check for the presence of a key with the `base_layer` suffix.
@yiyixuxu
=> Fix Flux multiple Lora loading bug

src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, tests/pipelines/controlnet_sd3/test_controlnet_sd3.py
Inherit from `SD3IPAdapterMixin` to allow image prompting.
Fixes #10129
@hlky 
@yiyixuxu 
=> IP-Adapter support for `StableDiffusion3ControlNetPipeline`

src/diffusers/pipelines/ltx/pipeline_ltx.py, src/diffusers/pipelines/ltx/pipeline_ltx_image2video.py
I want to be able to do:
```py
pipe = LTXPipeline.from_pretrained(..., transformer=None, vae=None)
with torch.no_grad():
... = pipe.encode_prompt(...)
```
And then use the prompt embedding outputs for downstream tasks. 
Currently, LTX pipelines would fail to do this. This PR fixes that. 
In a separate PR, I can look into refactoring the test-suite to test `encode_prompt()` in isolation as it's widely used for many trainers and other applications (cc: @hlky).
=> [LTX-Video] fix attribute adjustment for ltx.

src/diffusers/models/transformers/transformer_flux.py
- Updates some docs and type hints
- Removes the access of attributes via config in transformer init
- torch.FloatTensor -> torch.Tensor because FloatTensor only exists for backward-compatibility reasons
=> Update Flux docstrings

docs/source/en/tutorials/using_peft_for_inference.md
Follow up to #10394 to fix all the internal links to `PeftAdapterMixin`.
=> [docs] Fix internal links

src/diffusers/pipelines/auto_pipeline.py
Flux IPAdapter introduced optional components `feature_extractor` and `image_encoder` to FluxPipeline, the changes have not yet been replicated to Img2Img/Inpaint pipelines, when checking for missing modules in `from_pipe` we consider the target pipeline's `expected_modules` and the source pipeline's `_optional_components`, we should also consider the target pipeline's optional components.
```python
from diffusers import FluxPipeline, AutoPipelineForInpainting, AutoPipelineForText2Image
import torch
pipe = FluxPipeline.from_pretrained(
"black-forest-labs/FLUX.1-schnell", torch_dtype=torch.bfloat16
)
pipe = AutoPipelineForInpainting.from_pipe(pipe)
pipe = AutoPipelineForText2Image.from_pipe(pipe)
```
```python
File Untitled-8:8
7 pipe = AutoPipelineForInpainting.from_pipe(pipe)
----> 8 …
```
=> Fix AutoPipeline `from_pipe` where source pipeline is missing target pipeline's optional components

src/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_zero.py
Replaces #10355
Note that `from_single_file` here requires no additional changes as the pipeline works with SD v1 models.
@sayakpaul @chaowenguo
=> Add torch_xla and from_single_file support to TextToVideoZeroPipeline

src/diffusers/loaders/unet.py
Adds PEFT version check for `lora_bias` support to `unet.load_attn_procs`. Loading LoRAs through `load_attn_procs` is scheduled to be deprecated by `0.40.0` and is replaced by `load_lora_weights`, this check is already present in `load_lora_weights`.
Fixes #10472
=> `lora_bias` PEFT version check in `unet.load_attn_procs`

src/diffusers/pipelines/ledits_pp/pipeline_leditspp_stable_diffusion.py, src/diffusers/pipelines/ledits_pp/pipeline_leditspp_stable_diffusion_xl.py
- Updates examples to use `variant="fp16"`, `load_image` from `diffusers.utils`, enable vae tiling, resize the image to 512x512 and 1024x1024 for XL
- Add `indexing="ij"` to `torch.meshgrid` to fix the warning
- Add `enable_vae_slicing`, `disable_vae_slicing`, `enable_vae_tiling`, `disable_vae_tiling`
- Check the input `height`/`width` parameters and the `image`'s height/width are a multiple of `32`.
| Original | LEditsPP |
|--------|--------|
| ![cherry_blossom](https://github.com/user-attachments/assets/5d274f13-887a-4cbe-a5b5-13a6d8f5dee7) | ![cherry_blossom](https://github.com/user-attachments/assets/da066a3b-36c8-4951-a2c0-6f86b957a7b6) | 
| Original | LEditsPP |
|--------|--------|
| ![tennis](https://github.com/user-attachments/assets/ac29881b-c1d4-4e23-87e0-8073f5aaf685) | …
=> LEditsPP - examples, check height/width, add tiling/slicing

docs/source/en/api/pipelines/flux.md, src/diffusers/loaders/lora_pipeline.py, tests/lora/test_lora_layers_flux.py
https://github.com/huggingface/diffusers/pull/10206 added support for properly unloading Control LoRA weights from Flux and allowing the pipeline to be used with `from_pipe()`. 
However, this led to the following problem. Say, if we do:
```py
...
pipeline.load_lora_weights("black-forest-labs/FLUX.1-Canny-dev-lora")
pipeline.fuse_lora()
pipeline.unload_lora_weights()
...
```
[This](https://github.com/huggingface/diffusers/blob/83da817f73776aa61086683f55432bf2915d0748/src/diffusers/loaders/lora_pipeline.py#L2324C21-L2331C26) would revert the `transformer` config back to the original (`in_channels=64`), rendering [this line](https://github.com/huggingface/diffusers/blob/83da817f73776aa61086683f55432bf2915d0748/src/diffusers/pipelines/flux/pipeline_flux_control.py#L764) to output 8 (whereas …
=> [LoRA] fix: lora unloading when using expanded Flux LoRAs.

src/diffusers/models/transformers/transformer_hunyuan_video.py
Fixes #10453
Reproducer:
```python
import torch
from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
model_id = "hunyuanvideo-community/HunyuanVideo"
transformer = HunyuanVideoTransformer3DModel.from_pretrained(
model_id, subfolder="transformer", torch_dtype=torch.bfloat16
)
pipe = HunyuanVideoPipeline.from_pretrained(model_id, transformer=transformer, torch_dtype=torch.float16)
pipe.vae.enable_tiling()
output = pipe(
prompt="A cat walks on the grass, realistic",
height=320,
width=512,
num_frames=61,
num_inference_steps=30,
num_videos_per_prompt=2,
).frames[0]
export_to_video(output, "output.mp4", fps=15)
```
<table align=center>
<tr>
<td align=center><video …
=> Fix hunyuan video attention mask dim

src/diffusers/loaders/single_file_utils.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py, tests/single_file/test_stable_diffusion_single_file.py
Replaces #10355
`from_single_file` changes were determined by comparing [v1-5-pruned.safetensors](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/blob/main/v1-5-pruned.safetensors) to [instruct-pix2pix-00-22000.safetensors](https://huggingface.co/timbrooks/instruct-pix2pix/blob/main/instruct-pix2pix-00-22000.safetensors)
```python
import safetensors
from huggingface_hub import hf_hub_download
pix2pix = safetensors.safe_open(hf_hub_download("timbrooks/instruct-pix2pix", filename="instruct-pix2pix-00-22000.safetensors"), framework="pt")
v1 = safetensors.safe_open(hf_hub_download("stable-diffusion-v1-5/stable-diffusion-v1-5", filename="v1-5-pruned.safetensors"), framework="pt")
extra_keys = set(pix2pix.keys()) - set(v1.keys())
print(extra_keys)
for key in pix2pix.keys(): …
```
=> Add torch_xla and from_single_file to instruct-pix2pix

src/diffusers/models/transformers/transformer_hunyuan_video.py
`NaN` tracked to 
https://github.com/huggingface/diffusers/blob/811560b1d7daba48221317759ce0ed004513ea4f/src/diffusers/models/transformers/transformer_hunyuan_video.py#L117-L135
Specifically, some elements of `encoder_hidden_states`.
The dimensions of query, key, value and mask are large which suggests versions <2.5 used 32-bit indexing, this tracks with #10314 if ROCm versions are still using 32-bit indexing, this may also close that issue, awaiting confirmation from user.
Tested on CUDA 2.4.1
https://github.com/user-attachments/assets/63b05836-e9a9-4f4d-9169-d71194b5e071
<details>
<summary>Code</summary>
```python
import torch
from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
model_id = …
```
=> Fix HunyuanVideo produces NaN on PyTorch<2.5

src/diffusers/pipelines/sana/pipeline_sana.py
Due to SanaPipeline's support of multiple languages, changing the default clean_caption from True to False is better for better performance.
Cc: @yiyixuxu
=> [Sana][bug fix]change clean_caption from True to False.

.github/workflows/pr_tests.yml
`tokenizers` bumped on `transformers` https://github.com/huggingface/transformers/pull/34972 [broke](https://github.com/huggingface/diffusers/actions/runs/12184486183/job/33988635096?pr=10131) `pr_test_peft_backend` workflow.
=> Update tokenizers in `pr_test_peft_backend`

src/diffusers/models/modeling_utils.py, src/diffusers/pipelines/pipeline_utils.py
This PR fixes an device issue with the pipeline when we load a diffusers model separately with `device_map` in a single gpu case. We can't move the whole pipeline to device as the diffusers model have hooks on it (as we set `force_hooks=True`) and the following check raise an error : 
```python 
def module_is_sequentially_offloaded(module):
if not is_accelerate_available() or is_accelerate_version("<", "0.14.0"):
return False
return hasattr(module, "_hf_hook") and (
isinstance(module._hf_hook, accelerate.hooks.AlignDevicesHook)
or hasattr(module._hf_hook, "hooks")
and isinstance(module._hf_hook.hooks[0], accelerate.hooks.AlignDevicesHook)
)
pipeline_is_sequentially_offloaded = any(
module_is_sequentially_offloaded(module) for _, module in self.components.items()
)
```
The model shouldn't …
=> Fix compatibility with pipeline when loading model with device_map on single gpu

.github/workflows/pr_tests.yml
https://github.com/huggingface/diffusers/pull/10132
[Tokenizers Installation](https://github.com/huggingface/tokenizers?tab=readme-ov-file#installation)
=> Fix tokenizers install from main in LoRA tests

src/diffusers/models/unets/unet_2d.py, tests/models/unets/test_models_unet_2d.py
`mid_block_type` is unsupported in `UNet2DModel` despite appearing in documentation.
https://github.com/huggingface/diffusers/blob/b5726358cf125f2fa1a596dce321e91a225a57e4/src/diffusers/models/unets/unet_2d_blocks.py#L274-L322
Of these `UNet2DModel` only works with `UNetMidBlock2D`. `None` can also be supported and is added in this PR.
Fixes #10460
@sayakpaul
=> UNet2DModel mid_block_type

docs/source/en/api/pipelines/sana.md
`AutoModel` instead of `AutoModelForCausalLM` in the `SanaPipeline` quantization example at https://huggingface.co/docs/diffusers/main/en/api/pipelines/sana#quantization
Fixes #10489
@sayakpaul @lawrence-cj @stevhliu
=> AutoModel instead of AutoModelForCausalLM

src/diffusers/schedulers/scheduling_dpmsolver_multistep.py, src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
Fixes #10416 by adding missing parameters in `FlowMatchEulerDiscreteScheduler` and `DPMSolverMultistepScheduler `.
=> [docs] Fix missing parameters in docstrings

src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_modular.py
Adds Stable Diffusion XL ControlNet Union to Modular Diffusers
<details><summary>Modular</summary>
<p>
```python
import torch
from diffusers import ModularPipeline
from diffusers.pipelines.modular_pipeline import SequentialPipelineBlocks
from diffusers.pipelines.components_manager import ComponentsManager
from diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl_modular import (
StableDiffusionXLTextEncoderStep,
StableDiffusionXLDecodeLatentsStep,
StableDiffusionXLInputStep,
StableDiffusionXLAutoSetTimestepsStep,
StableDiffusionXLAutoPrepareLatentsStep,
StableDiffusionXLAutoPrepareAdditionalConditioningStep,
StableDiffusionXLControlNetUnionDenoiseStep,
StableDiffusionXLAutoVaeEncoderStep,
) …
```
=> [modular] Stable Diffusion XL ControlNet Union

src/diffusers/models/attention_processor.py, src/diffusers/models/transformers/cogvideox_transformer_3d.py
Pass kwargs to custom attention processor is preferable when implementing layout control, attention replacing or introducing side effect to attention computation. Now this feature is supported by sd, sdxl, FLUX, sd3 series, but not CogVideoX. This PR fix the problem, and may support future training-free experiments in CogVideoX series models.
Example code:
```Python
class CustomCogVideoXAttnProcessor2_0:
def __init__(self, **custom_args):
super().__init__()
def __call__(self, ..., added_argu=None) -> torch.FloatTensor:
custom_processor = CustomCogVideoXAttnProcessor2_0(**custom_args)
pipe.transformer.set_attn_processor(custom_processor) # cogvideox pipeline
attention_kwargs = {"added_argu": 100} # prepare passing added_argu to attention processor
pipe.transformer(..., …
```
=> Support pass kwargs to cogvideox custom attention processor

tests/lora/test_lora_layers_sd3.py, tests/quantization/bnb/test_mixed_int8.py
Some tests were left to be updated in the previous PRs. This PR updates the assertion slices. 
Note the slice in one of the quantization tests is being changed to match what we're getting in our CI runner. If we follow the environment as mentioned [here](https://github.com/huggingface/diffusers/tree/main/tests/quantization/bnb), it will pass.
=> [CI] Match remaining assertions from big runner

src/diffusers/models/autoencoders/autoencoder_dc.py, src/diffusers/pipelines/pag/pipeline_pag_sana.py, src/diffusers/pipelines/sana/pipeline_sana.py, tests/pipelines/sana/test_sana.py
This PR will add tiling support for DC-AE (Deep Compression Autoencoder for Efficient High-Resolution Diffusion Models) into the diffusers lib, in order to reduce memory consumption for encoding and decoding super-high-resolution images like 4096x4096. 
Could you please have a look? Thanks! @sayakpaul @yiyixuxu 
=> [DC-AE] support tiling for DC-AE

tests/models/autoencoders/test_models_vq.py, tests/models/unets/test_models_unet_1d.py, tests/models/unets/test_models_unet_2d.py, tests/models/unets/test_models_unet_controlnetxs.py, tests/pipelines/wuerstchen/test_wuerstchen_combined.py, tests/schedulers/test_scheduler_ddim_inverse.py, tests/schedulers/test_scheduler_deis.py, tests/schedulers/test_scheduler_dpm_multi.py, tests/schedulers/test_scheduler_dpm_single.py, tests/schedulers/test_scheduler_edm_dpmsolver_multistep.py, tests/schedulers/test_scheduler_flax.py, tests/schedulers/test_scheduler_ipndm.py, tests/schedulers/test_scheduler_pndm.py, tests/schedulers/test_scheduler_unclip.py, tests/schedulers/test_scheduler_vq_diffusion.py
=> [Tests] skip tests properly with `unittest.skip()`

src/diffusers/hooks/group_offloading.py, src/diffusers/models/transformers/transformer_ltx.py
See #10503 for more details.
<details>
<summary> Code </summary>
```python
import argparse
import gc
import os
import time
os.environ["TORCH_LOGS"] = "+recompiles_verbose"
import types
types.MethodType
import torch
import torch._dynamo
import torch._dynamo.utils
from diffusers import LTXPipeline
from diffusers.hooks import apply_group_offloading
torch._dynamo.config.cache_size_limit = 4
def cleanup():
gc.collect()
torch.cuda.reset_peak_memory_stats()
def benchmark_fn(f, *args, **kwargs):
torch.cuda.synchronize()
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)
start.record()
output = f(*args, **kwargs)
end.record()
torch.cuda.synchronize()
elapsed_time = …
```
=> Group offloading with cuda stream prefetching

src/diffusers/pipelines/ltx/pipeline_ltx.py
LTX-Video pipeline uses the original `torch.randn` to create a random tensor. `torch.randn` requires `generator` and `latents` on the same device, while the wrapped function `randn_tensor` does not have this issue.
Fix the running issue when the `generator` and `latents` on different devices. For example, if you use CPU's random seed to generate a video on CUDA, the original pipeline will raise an error.
- [] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhugg …
=> Use `randn_tensor` to replace `torch.randn`

src/diffusers/pipelines/latte/pipeline_latte.py
We use `latent` and not `latents` for output_type across all pipelines. Currently, if one passes `latent`, it does not work as expected
=> Fix Latte output_type

src/diffusers/loaders/single_file_utils.py, tests/single_file/single_file_testing_utils.py, tests/single_file/test_stable_diffusion_single_file.py
https://github.com/huggingface/diffusers/actions/runs/12738450237/job/35500790623
We add `instruct-pix2pix` to `DIFFUSERS_TO_LDM_DEFAULT_IMAGE_SIZE_MAP` and introduce `single_file_kwargs` to `SDSingleFileTesterMixin`, this is to pass `extract_ema=True` to `convert_ldm_unet_checkpoint` and match inference results with the checkpoint at `timbrooks/instruct-pix2pix` which is created from `extract_ema=True`.
=> Fix StableDiffusionInstructPix2PixPipelineSingleFileSlowTests

examples/research_projects/sd3_lora_colab/train_dreambooth_lora_sd3_miniature.py
=> Fix train_dreambooth_lora_sd3_miniature

.github/workflows/nightly_tests.yml, setup.py, src/diffusers/dependency_versions_table.py, src/diffusers/pipelines/audioldm2/pipeline_audioldm2.py, tests/pipelines/audioldm2/test_audioldm2.py
https://github.com/huggingface/diffusers/actions/runs/12738450237/job/35517796258
`test_cpu_offload_forward_pass_twice`/`test_model_cpu_offload_forward_pass` by updating signature of overridden `enable_model_cpu_offload`
`test_dict_tuple_outputs_equivalent` fails ~1e-5 over tolerance, `AssertionError: np.float32(0.00021260581) not less than 0.0002`, it's already noted that tolerance is increased due to large composite model so should be ok to increase it a bit more.
`test_audioldm2_tts` should pass with `phonemizer` installed.
Leaving `test_sequential_offload_forward_pass_twice - NotImplementedError: Cannot copy out of meta tensor; no data!` as a TODO.
members/contributors who may be interested …
=> Fix Nightly AudioLDM2PipelineFastTests

src/diffusers/loaders/peft.py
In case, `inject_adapter_in_model()` fails midway for whatever reason before injecting `peft_config` into the base model, we should handle have a proper guard. This PR adds hat guard.
=> [LoRA] improve failure handling for peft.

docs/source/en/api/pipelines/flux.md
Found a tiny mistake in the documentation of FluxPipeline, more specifically the part showing how the Flux model can be loaded in a quantized way. In the code example the text encoder model is passed to the wrong argument in the FluxPipeline.from_pretrained function.
Anyone in the community is free to review the PR once the tests have passed. @stevhliu will be interested?
=> Fix documentation for FluxPipeline

src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet_inpainting.py, tests/pipelines/controlnet_sd3/test_controlnet_inpaint_sd3.py
Adds support for image prompting via IP-Adapter for `StableDiffusion3ControlNetInpaintingPipeline`.
Part of #9966 
@hlky @yiyixuxu
I mentioned in #9966 that I didn't find an inpainting controlnet for SD3.5 Large, and the only IP-Adapter available is for SD3.5 Large afaik, so we can't really test it properly if that's the case.
=> Added IP-Adapter for `StableDiffusion3ControlNetInpaintingPipeline`

tests/quantization/torchao/test_torchao.py
To detect cases like this: https://github.com/huggingface/diffusers/issues/10470
Accelerate PR needs to be merged first: https://github.com/huggingface/accelerate/pull/3332
=> Test sequential cpu offload for torchao quantization

src/diffusers/models/transformers/transformer_hunyuan_video.py
=> Fix batch > 1 in HunyuanVideo

.github/workflows/push_tests.yml
Missed this token when opening: #10568
=> [CI] Update HF Token on Fast GPU Model Tests

src/diffusers/loaders/textual_inversion.py
Allows passing HF_TOKEN to load_textual_inversion explicitly using the argument ``hf_token`` as suggested in the linked issue.
Fixes duplicate parameter name conflict caused by kwargs usage, as ``token`` is used by this method to denote a lexical token and not an authentication token.
Fixes #7689
@sayakpaul
=> allow passing hf_token to load_textual_inversion

src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py, tests/pipelines/stable_diffusion_3/test_pipeline_stable_diffusion_3_inpaint.py
Part of #9966. Unlike #10561, this pipeline doesn't use a controlnet for inpainting, so we can test this pipeline. I tested with [stabilityai/stable-diffusion-3.5-large](https://huggingface.co/stabilityai/stable-diffusion-3.5-large), which wasn't fine-tuned for inpainting, but actually got decent results. Here are a few example outputs:
<details>
<summary>Inference code</summary>
```python
import torch
from torchvision import transforms
from diffusers import StableDiffusion3InpaintPipeline
from transformers import SiglipVisionModel, SiglipImageProcessor
def preprocess_image(image):
image = image.convert("RGB")
image = transforms.CenterCrop((image.size[1] // 64 * 64, image.size[0] // 64 * 64))(image)
image = transforms.ToTensor()(image)
image = …
```
=> IP-Adapter for `StableDiffusion3InpaintPipeline`

tests/quantization/bnb/test_mixed_int8.py
To prevent from https://github.com/huggingface/diffusers/issues/10550. Only adds this test to 8bit. 4bit has issues and I will open a follow-up in a bit.
Slightly related: https://github.com/huggingface/diffusers/issues/10550.
=> [Tests] add: test to check 8bit bnb quantized models work with lora loading.

src/diffusers/models/normalization.py
Added NPU RMSNorm function to get the better performance for NPU devices
=> NPU adaption for RMSNorm

examples/flux-control/train_control_flux.py
Sets rest of the Flux blocks to non-trainable when only targeting `transformer_blocks`.
=> [training] set rest of the blocks with `requires_grad` False.

docs/source/en/api/pipelines/mochi.md, scripts/convert_consistency_decoder.py, src/diffusers/optimization.py, src/diffusers/pipelines/pag/pag_utils.py, src/diffusers/video_processor.py
=> chore: remove redundant words

examples/dreambooth/train_dreambooth_flux.py
When using BF16 for training, the script raises the error of `RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same` due to accelerator's FP32 wrapper. This wrapper needs to be removed for evaluation.
@sayakpaul 
Integrations:
- deepspeed: HF Trainer/Accelerate: @SunMarc
- PEFT: @sayakpaul @BenjaminBossan
HF projects:
- accelerate: [different …
=> Remove the FP32 Wrapper when evaluating

src/diffusers/models/transformers/sana_transformer.py, tests/models/test_modeling_common.py, tests/models/transformers/test_models_transformer_sana.py
this PR:
1. fix the gpu offload tests
2. refator sana tranformer so it can work with device map "auto"
=> fix offload gpu tests etc

src/diffusers/utils/hub_utils.py
Similar to https://github.com/huggingface/transformers/pull/35810.
This PR makes some cleaning in the `src/diffusers/utils/hub_utils.py` file. The "move_cache" has been introduced in [`v0.14.0`](https://github.com/huggingface/diffusers/releases/tag/v0.14.0) (Feb 2023). IMO, we can safely assume everyone got their cache moved by now. Worse case, someone that did not update `diffusers` for 2y will have to redownload some models if they update. 
Less dead code to maintain :)
=> Remove cache migration script

src/diffusers/quantizers/quantization_config.py
Improves TorchAO error message when using float qtypes on GPUs with cuda capability lower than 8.9. Thanks to @DN6 for pointing it out!
Also fixes a mistake in the docstring of `__repr__`.
=> Improve TorchAO error message

.github/workflows/nightly_tests.yml, .github/workflows/push_tests.yml, .github/workflows/release_tests_fast.yml
We can safely replace `HF_TOKEN` with the `DIFFUSERS_HF_HUB_READ_TOKEN` in all workflows. 
=> [CI] Update HF_TOKEN in all workflows

src/diffusers/utils/import_utils.py
The onnxruntime check would fail if only onnxruntime-migraphx was installed. Added to the list of candidates.
Core library:
- General functionalities: @sayakpaul @yiyixuxu @DN6
=> add onnxruntime-migraphx as part of check for onnxruntime in import_utils.py

tests/schedulers/test_scheduler_flax.py
Changes the slices for the failing Flax test:
https://github.com/huggingface/diffusers/actions/runs/12920732113/job/36033718428?pr=10624#step:8:320
I haven't intentionally dove deeper into why this is failing as I think the usage of the underlying scheduler is quite low. But can do it if we think otherwise.
=> [Tests] modify the test slices for the failing flax test

docs/source/en/optimization/para_attn.md
=> [docs] fix image path in para attention docs

docs/source/en/installation.md
Proposes adding uv install instructions (see Slack [thread](https://huggingface.slack.com/archives/C01N44FJDHT/p1737377177709279) for more context) if you're also interested!
=> [docs] uv installation

docs/source/en/api/pipelines/flux.md
Pending https://huggingface.co/datasets/huggingface/documentation-images/discussions/424
=> Add IP-Adapter example to Flux docs

scripts/extract_lora_from_model.py
As discussed internally. https://huggingface.co/finetrainers/cakeify-v0 presents a successful example. 
Cc: @linoytsaban @apolinario for awareness.
=> [chore] add a script to extract loras from full fine-tuned models

src/diffusers/pipelines/controlnet/pipeline_controlnet_union_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl_img2img.py
e.g. `'controlnet_conditioning_scale': [0.5, 0.8]`
Removes unneeded check that was copied from other controlnet as controlnet union supports multiple inputs with the same controlnet model.
@vladmandic
=> ControlNet Union controlnet_conditioning_scale for multiple control inputs

examples/dreambooth/README.md, examples/dreambooth/convert_to_imagefolder.py
Image-text pairs e.g. `01.jpg` `01.txt` are common in the community. This PR adds documentation and a script to create `ImageFolder`'s `metadata.jsonl` from these image-text pairs.
Fixes #10655
=> [training] Convert to ImageFolder script

src/diffusers/pipelines/onnx_utils.py
As per issue this adds `provider_options` to `OnnxRuntimeModel`'s `load_model` which is in turn passed to `onnxruntime`'s `InferenceSession`.
Fixes #10658
cc @xieofxie
=> Add provider_options to OnnxRuntimeModel

src/diffusers/pipelines/controlnet/pipeline_controlnet_union_inpaint_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl_img2img.py
when ``control_image``  is passed a list, ``__call__``
modifies its content, since it is pass by reference the list passed by the caller gets its content modified unexpectedly
make a copy at method intro so this does not happen
@yiyixuxu @asomoza
=> SDXL ControlNet Union pipelines, make control_image argument immutible

src/diffusers/schedulers/scheduling_repaint.py
Reverts 'fix' introduced by pull request #10185; the PR adjusted the code accordingly to Algorithm 1 Line 5 of the RePaint paper ([https://arxiv.org/pdf/2201.09865.pdf](https://arxiv.org/pdf/2201.09865.pdf)), however that line is reported incorrectly in the paper itself.
Algorithm 1 Line 5 refers to formula 8a of the same paper
$$x_{t-1}^{\text{known}} \sim \mathcal{N}(\sqrt{\bar{\alpha}} x_0, (1 - \bar{\alpha}) \mathbf{I})$$
which tells to sample from a Gaussian distribution $\mathcal{N}(\mu, \sigma^2)$ with $\mu = \sqrt{\bar{\alpha}} x_0$ and $\sigma^2 = (1 - \bar{\alpha})$. In order to obtain this result, the standard Gaussian distribution $\epsilon \sim \mathcal{N}(\mathbf{0}, \mathbf{I})$ should be stretched by a factor $\sigma$ and translated by a factor $\mu$ (source: …
=> Revert RePaint scheduler 'fix'

src/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py
AutoencoderKLHunyuanVideo._encode is currently refering to `use_framewise_decoding`, instead of `use_framewise_encoding`. Fixed it to `use_framewise_encoding`
=> [fix] refer use_framewise_encoding on AutoencoderKLHunyuanVideo._encode

examples/community/stable_diffusion_xl_controlnet_reference.py, examples/community/stable_diffusion_xl_reference.py
When using one of the SDXL reference pipelines, configuring the pipeline with the `torch_dtype` parameter set to `torch.float16` and using a VAE with the `force_upcast` configuration, an upcast of the VAE to `torch.float32` is performed during inference. However, it is never downcast to `torch.float16` which leads to side effects.
Indeed, the dtype of the pipeline is defined in `pipelines/pipeline_utils.py` as:
```
@property
def dtype(self) -> torch.dtype:
r"""
Returns:
`torch.dtype`: The torch dtype on which the pipeline is located.
"""
module_names, _ = self._get_signature_keys(self)
modules = [getattr(self, n, None) for n in module_names]
modules = [m for m in modules if isinstance(m, torch.nn.Module)]
for module in modules:
return module.dtype
return torch.float32
```
When the VAE …
=> Fix pipeline dtype unexpected change when using SDXL reference community pipelines in float16 mode

src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_adapter.py
Adds support for ``from_single_file`` to ``StableDiffusionAdapterPipeline`` by inheriting ``FromSingleFileMixin``
```python
import diffusers
import torch
image = load_image(
"https://huggingface.co/datasets/diffusers/docs-images/resolve/main/t2i-adapter/color_ref.png"
)
color_palette = image.resize((8, 8))
color_palette = color_palette.resize((512, 512), resample=Image.Resampling.NEAREST)
adapter = diffusers.T2IAdapter.from_pretrained("TencentARC/t2iadapter_color_sd14v1", torch_dtype=torch.float16)
pipe = diffusers.StableDiffusionAdapterPipeline.from_single_file(
'impressionismOil_sd15.safetensors',
adapter=adapter, torch_dtype=torch.float16)
pipe.to('cuda')
output = pipe(
prompt='impressionist oil painting of a sunset', …
```
=> support StableDiffusionAdapterPipeline.from_single_file

src/diffusers/models/attention_processor.py
Fix enable memory efficient attention on ROCm while calling CK implementation
https://github.com/facebookresearch/xformers/blob/main/xformers/ops/fmha/ck.py#L157
Bug cause: the only supported dtypes by the op are float16 and bfloat16, and by default the input tensor is initialized as float32, which prevents using memory efficient attention on ROCm
Bug fix: pick a supported dtype when a custom attention op is passed as an argument
Note: attention op is not a Callable but a pair of (forward, backward) op implementations
https://github.com/facebookresearch/xformers/blob/main/xformers/ops/fmha/__init__.py#L202
https://github.com/facebookresearch/xformers/blob/main/xformers/ops/fmha/common.py#L469
[documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs …
=> Fix enable memory efficient attention on ROCm

examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py
Fixes #10697 
I'm using solution from https://github.com/pytorch/vision/issues/9#issuecomment-1193373938
=> Fix inconsistent random transform in instruct pix2pix

src/diffusers/training_utils.py
the `compute_density_for_timestep_sampling` function is defaulting to CPU-based tensor operations, which limits flexibility when working with GPUs. the function also lacks support for a generator, which made it difficult to ensure reproducibility in sampling.
No API-breaking changes; existing calls without `device` or `generator` params will default to CPU-based execution.
@a-r-r-o-w @sayakpaul
=> feat(training-utils): support device and dtype params in compute_density_for_timestep_sampling

docs/source/en/using-diffusers/write_own_pipeline.md
This PR fixes a minor grammatical error in the readme file "write_own_pipeline" where the structure of a sentence was slightly off.
@stevhliu, @sayakpaul please have a look.
=> Fixed grammar in "write_own_pipeline" readme

examples/text_to_image/train_text_to_image.py
Running `python train_text_to_image.py -h`  to see the command help fails with the following error:
```
File "/home/jovyan/scene-text-translation/scene_text_translation/training/patches_generation/text_to_image.py", line 1156, in <module>
main()
File "/home/jovyan/scene-text-translation/scene_text_translation/training/patches_generation/text_to_image.py", line 523, in main
args = parse_args()
File "/home/jovyan/scene-text-translation/scene_text_translation/training/patches_generation/text_to_image.py", line 506, in parse_args
args = parser.parse_args()
File "/opt/conda/lib/python3.10/argparse.py", line 1833, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "/opt/conda/lib/python3.10/argparse.py", line 1866, in parse_known_args
namespace, args = …
```
=> Fix train_text_to_image.py --help

src/diffusers/pipelines/pipeline_utils.py
Fixes #10707  Added Self in from_pretrained method so  inference will correctly recognize pipeline
Anyone in the community is free to review the PR once the tests have passed. @yiyixuxu 
Before this fix pyright inferred the return type as Any, leading to incorrect type checking:
```python
import torch
from diffusers.pipelines.flux.pipeline_flux import FluxPipeline
from diffusers.utils.loading_utils import load_image
pipe = FluxPipeline.from_pretrained(
"black-forest-labs/FLUX.1-dev",
)
reveal_type(pipe)
```
```
/content/my_script.py …
```
=> [Fix] Type Hint in from_pretrained() to Ensure Correct Type Inference

src/diffusers/loaders/transformer_flux.py
https://github.com/huggingface/diffusers/issues/10337#issuecomment-2637042638
<details><summary>Code (4bit)</summary>
<p>
```python
from diffusers import BitsAndBytesConfig as DiffusersBitsAndBytesConfig
from transformers import BitsAndBytesConfig as TransformersBitsAndBytesConfig
import torch
from diffusers import FluxTransformer2DModel, FluxPipeline
from transformers import T5EncoderModel
quant_config = TransformersBitsAndBytesConfig(
load_in_4bit=True,
bnb_4bit_quant_type="nf4",
bnb_4bit_compute_dtype=torch.float16,
)
text_encoder_2_4bit = T5EncoderModel.from_pretrained(
"black-forest-labs/FLUX.1-dev",
subfolder="text_encoder_2",
quantization_config=quant_config,
)
quant_config = DiffusersBitsAndBytesConfig( …
```
=> Quantized Flux with IP-Adapter

src/diffusers/schedulers/scheduling_edm_euler.py
Support passing `sigmas` to `set_timesteps` in `EDMEulerScheduler` and support `final_sigmas_type`.
```python
from diffusers import EDMEulerScheduler
import torch
scheduler = EDMEulerScheduler(
sigma_min=0.002,
sigma_max=80,
sigma_data=0.5,
sigma_schedule="karras",
num_train_timesteps=1000,
prediction_type="epsilon",
rho=7.0,
final_sigmas_type="sigma_min",
)
num_inference_steps = 35
sigmas = torch.arange(num_inference_steps + 1) / num_inference_steps
scheduler.set_timesteps(sigmas=sigmas)
print(scheduler.sigmas)
```
@yiyixuxu
=> EDMEulerScheduler accept sigmas, add final_sigmas_type

src/diffusers/models/modeling_utils.py
Follow up to #10714 for `ModelMixin`'s `from_pretrained`
```python
from diffusers import AutoencoderKL
model = AutoencoderKL.from_pretrained("")
```
```
(variable) model: Any
```
With the change
```
(variable) model: AutoencoderKL
```
@yiyixuxu
=> Add `Self` type hint to `ModelMixin`'s `from_pretrained`

tests/models/autoencoders/test_models_autoencoder_oobleck.py, tests/models/test_modeling_common.py, tests/models/unets/test_models_unet_1d.py
Probably a no brainer at this point?
=> [Tests] Test layerwise casting with training

src/diffusers/models/autoencoders/autoencoder_kl_hunyuan_video.py, tests/models/autoencoders/test_models_autoencoder_hunyuan_video.py
The original causal attention mask generation for the hunyuan encoder is very slow, especially when the tensor is created on the GPU, because it needs to make 1000s of calls (for loop over sequence length).
I tried to compile it...which works and makes it fast too, but compilation unfortunately also takes a long time when using a long sequence length.
This implementation is ~20-70x faster depending on the sequence lengths and since it is re-created for every SDPA, this accumulates to multiple seconds per step for larger videos
This PR is a duplicate of the PR to the original HunyuanVideo repository https://github.com/Tencent/HunyuanVideo/pull/208 …
=> speedup hunyuan encoder causal mask generation

examples/community/README.md, examples/community/mixture_tiling_sdxl.py
This PR add a new community pipeline for SDXL support of Mixture-of-Diffusers, tiling version only. See original project: (https://github.com/albarji/mixture-of-diffusers). We already have pipeline for SD 1.5.
I already published a demo app for this:  <p><a href='https://huggingface.co/spaces/elismasilva/mixture-of-diffusers-sdxl-tiling'><img src='https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue'></a></p>
``` python
import torch
from diffusers import DPMSolverMultistepScheduler, AutoencoderKL
from mixture_tiling_sdxl import StableDiffusionXLTilingPipeline
device="cuda"
vae = AutoencoderKL.from_pretrained(
"madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16
).to(device)
model_id="stablediffusionapi/yamermix-v8-vae"
scheduler = …
```
=> feat: new community mixture_tiling_sdxl pipeline for SDXL

src/diffusers/utils/peft_utils.py
The previous code iterated through `model.named_modules()` **for each adapter**, which can be very costly when the number of adapters reaches hundreds.
I've slightly changed the logic to iterate over `model.named_modules()` **only once**, setting the adapters for each submodule within that pass.
I haven't run extensive qualitative tests yet, but in my local experiment (Flux with 150+ adapters 😅) this change is significantly faster.
members/contributors who may be interested in your …
=> Faster set_adapters

docs/source/en/api/pipelines/lumina2.md, src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/models/transformers/transformer_lumina2.py, tests/single_file/test_lumina2_transformer.py
=> [Single File] Add Single File support for Lumina Image 2.0 Transformer

src/diffusers/schedulers/scheduling_dpmsolver_multistep.py
`.round()` was applied with `use_lu_lambdas` and `use_karras_sigmas`, this seems to give incorrect `_step_index` from `index_for_timestep` as multiple timesteps are the same.
<details><summary>Reproduction</summary>
<p>
```python
from diffusers import DPMSolverMultistepScheduler
import torch
def dummy_model():
def model(sample, t, *args):
if isinstance(t, torch.Tensor):
num_dims = len(sample.shape)
t = t.reshape(-1, *(1,) * (num_dims - 1)).to(
sample.device, dtype=sample.dtype
)
return sample * t / (t + 1)
return model
def dummy_sample_deter():
batch_size = 4
num_channels = 3
height = 8
width = 8
num_elems = batch_size * num_channels * height * width
sample = torch.arange(num_elems)
sample = sample.reshape(num_channels, height, width, batch_size)
sample = sample / num_elems
sample = …
```
=> Fix `use_lu_lambdas` and `use_karras_sigmas` with `beta_schedule=squaredcos_cap_v2` in `DPMSolverMultistepScheduler`

src/diffusers/models/__init__.py, src/diffusers/models/controlnets/__init__.py, src/diffusers/models/controlnets/multicontrolnet_union.py, src/diffusers/pipelines/controlnet/pipeline_controlnet_union_sd_xl.py
New `MultiControlNetUnionModel` wrapper class to handle multiple `ControlNetUnionModel`s, similarly to `MultiControlNetModel`. Addressed in #10656 to control start, end and scale of each condition image.
<details>
<summary>Input</summary>
<table>
<thead>
<tr>
<th>Segmentation</th>
<th>Pose</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<summary>Inference code</summary>
```python
import torch
from diffusers import StableDiffusionXLControlNetUnionPipeline
from diffusers.models import ControlNetUnionModel, AutoencoderKL
model_id = "stabilityai/stable-diffusion-xl-base-1.0"
controlnet_id = "brad-twinkl/controlnet-union-sdxl-1.0-promax"
controlnet = ControlNetUnionModel.from_pretrained( …
```
=> `MultiControlNetUnionModel` on SDXL

src/diffusers/models/transformers/cogvideox_transformer_3d.py
Fixes #10566.
I overlooked this part during the integration. Since we're operating on the embedding dimension, there's no need to concatenate across the sequence dimension
=> Refactor CogVideoX transformer forward

src/diffusers/models/transformers/transformer_lumina2.py, src/diffusers/pipelines/lumina2/pipeline_lumina2.py, tests/models/transformers/test_models_transformer_lumina2.py
This PR:
1. refactor and simplify ROPE: removed all the logic related to different image sizes (we do not need to support this for inference)
2. for now, I switched the default for `use_mask_in_transformer` to be `False` because:
* for single prompt (most common use case), the outputs are identical and we are getting a performance gain with `use_mask_in_transformer=False` (see details https://github.com/huggingface/diffusers/pull/10776#discussion_r1953806298)
* for list of prompts, mask should be used (see context  https://github.com/huggingface/diffusers/pull/10642#issuecomment-2654861362) - I think maybe we can remove this argument from pipeline, and automatically set to use mask when a list of prompts are passed (and otherwise set to be False)
=> follow-up refactor on lumina2

setup.py
We rely on https://huggingface.co/spaces/lysandre/github-release to fetch release notes but sometimes, it can be confusing to determine the appropriate tag and branch to obtain the release notes. 
This changed Space (https://huggingface.co/spaces/sayakpaul/auto-release-notes-diffusers) bypasses this need by automatically fetching the appropriate tag and branch so that we don't have to struggle. It also has a token secret, so, we don't have sweat that part.
=> [chore] update notes generation spaces

examples/community/pipeline_flux_differential_img2img.py, examples/community/pipeline_flux_rf_inversion.py, examples/community/pipeline_flux_semantic_guidance.py, examples/community/pipeline_flux_with_cfg.py, src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_control.py, src/diffusers/pipelines/flux/pipeline_flux_control_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_control_inpaint.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py, src/diffusers/pipelines/flux/pipeline_flux_fill.py, src/diffusers/pipelines/flux/pipeline_flux_img2img.py, src/diffusers/pipelines/flux/pipeline_flux_inpaint.py, src/diffusers/pipelines/ltx/pipeline_ltx.py, src/diffusers/pipelines/ltx/pipeline_ltx_image2video.py, src/diffusers/pipelines/lumina2/pipeline_lumina2.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py, src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_inpaint.py
This PR updates the max_shift value in flux to 1.15 for consistency across the codebase. In addition to modifying max_shift in flux, all related functions that copy and use this logic, such as calculate_shift in `src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py`, have also been updated to ensure uniform behavior.
Fixes #10675
@yiyixuxu and @asomoza
=> Fix max_shift value in flux and related functions to 1.15 (issue #10675)

src/diffusers/loaders/single_file.py, src/diffusers/loaders/single_file_model.py, src/diffusers/pipelines/pipeline_utils.py
Related to #10714 #10742 
```python
from diffusers import FluxPipeline
pipe = FluxPipeline.from_pretrained("").to("cuda")
```
```
(variable) pipe: Any
```
With the change
```
(variable) pipe: FluxPipeline
```
Also for `from_single_file` in `FromSingleFileMixin` and `FromOriginalModelMixin`.
=> DiffusionPipeline mixin `to`+FromOriginalModelMixin/FromSingleFileMixin `from_single_file` type hint

src/diffusers/quantizers/gguf/utils.py
Adds a missing isinstance check as part of getting torch.compile working with GGUFParameter (#10795)
@DN6
=> Add missing `isinstance` for arg checks in GGUFParameter

src/diffusers/models/activations.py
Fixes https://github.com/huggingface/diffusers/pull/10822. The activations function were stored in a dict, so if we load a models with hooks that contains activation function then we load a new model without hooks, the new model still ends up with hooks on the activation layers. This is because the same activation were used. To fix the issue, we just need to make sure to instantiate from the class.
=> store activation cls instead of function

src/diffusers/pipelines/pipeline_utils.py
^
The patch enable downloading the `generation_config.json` for transformer models in diffusers pipeline
=> fix: support transformer models' `generation_config` in pipeline

src/diffusers/loaders/transformer_flux.py, src/diffusers/loaders/transformer_sd3.py, src/diffusers/loaders/unet.py, src/diffusers/utils/import_utils.py
=> `device_map` in `load_model_dict_into_meta`

src/diffusers/models/model_loading_utils.py
FIxes https://github.com/huggingface/diffusers/issues/10863
This PR removes the format check that was recently introduced as it is not might not be compatible with single file format. For diffusers format there should be no issues. If you think it is still worth to add it for diffusers checkpoints, I can modify a bit the PR.
=> remove format check for safetensors file

docs/source/en/using-diffusers/weighted_prompts.md
Based on discussion in #10735, we're replacing Compel with sd_embed which has better support for long prompts, weighting, and more models.
=> [docs] Update prompt weighting docs

docs/source/en/api/pipelines/flux.md
From discussion in #10840, this PR adds an example of group offloading to the Flux docs as well as a note on memory requirements.
=> [docs] Flux group offload

docs/source/en/_toctree.yml, docs/source/en/api/schedulers/ddim_cogvideox.md, docs/source/en/api/schedulers/multistep_dpm_solver_cogvideox.md
Adds CogVideoX DDIM and DPM schedulers to the docs
=> [docs] Add CogVideoX Schedulers

src/diffusers/models/attention_processor.py, src/diffusers/models/controlnets/controlnet_sd3.py, src/diffusers/models/transformers/transformer_sd3.py
Refactors SD3:
- Removes `F.scaled_dot_product_attention` check which is already done in the processor (see [here](https://github.com/huggingface/diffusers/blob/9c7e205176c30b27c5f44ec7650a8dfcc12dde86/src/diffusers/models/attention_processor.py#L1410))
- Accesses parameters directly instead of via `self.config` for init methods
- Updates docs
- Updates type hints from FloatTensor -> Tensor since the former is deprecated
=> [refactor] SD3 docs & remove additional code

src/diffusers/models/transformers/transformer_flux.py
Some minor refactors to make implementations consistent.
- We already check for `F.scaled_dot_product_attention` in the attention processor init method (see [here](https://github.com/huggingface/diffusers/blob/9c7e205176c30b27c5f44ec7650a8dfcc12dde86/src/diffusers/models/attention_processor.py#L2265))
- Removes docstrings from intermediate blocks since they are explained in the main transformer implementation
- Additionally should we consider [this](https://github.com/huggingface/diffusers/pull/9751#issuecomment-2677129361) comment and remove the NPU related logic in FluxSingleTransformerBlock? It might be backwards breaking though
=> [refactor] Remove additional Flux code

.github/workflows/pr_tests_gpu.yml, src/diffusers/models/modeling_utils.py, utils/extract_tests_from_mixin.py
Conditional GPU tests on PR is a good idea but I think the current way might be making the PR CI too noisy/slow. This PR
Adds a dedicated workflow for conditional GPU tests that
1. Sets the pipeline fetcher cutoff to a very high number so that only the always-test pipelines run on PRs
2. Adds a utility script to fetch the methods of the core testing Mixins e.g PipelineTesterMixin, ModelTesterMixin and injects those methods as filter keys so only core functionality is tested.
3. Removes single file testing (it always downloads large models to run the tests)      …
=> [CI] Improvements to conditional GPU PR tests

.github/workflows/pr_style_bot.yml
I hope I understand well and do it right here.
=> Security fix

tests/lora/test_lora_layers_lumina2.py
This went unnoticed becaused it's xfailed on CPUs. So, it only got caught here:
https://github.com/huggingface/diffusers/actions/runs/13544909753/job/37854074489?pr=10909
Have verified the fix by running on a GPU.
=> [Tests] fix: lumina2 lora fuse_nan test

.github/workflows/pr_tests_gpu.yml, src/diffusers/pipelines/pipeline_utils.py
IP Adapter testing is showing a failures when no tests run because the test pattersn extracted from PipelineTesterMixin are not available in any of the IP Adapter tests. This PR
1. Skips applying test patterns for IP Adapter Pipeline tests. 
=> [CI] Fix for failing IP Adapter test in Fast GPU PR tests

scripts/convert_wan_to_diffusers.py, src/diffusers/models/__init__.py, src/diffusers/models/transformers/transformer_wan.py, src/diffusers/pipelines/wan/__init__.py, src/diffusers/pipelines/wan/pipeline_wan.py, src/diffusers/pipelines/wan/pipeline_wan_i2v.py, src/diffusers/utils/dummy_pt_objects.py, src/diffusers/utils/dummy_torch_and_transformers_objects.py, tests/models/transformers/test_models_transformer_wan.py
<details>
<summary> comparison script </summary>
```python
#
#
#
import math
from typing import Any, Dict, List, Optional, Tuple, Union
import torch
import torch.nn as nn
import torch.nn.functional as F
from diffusers.loaders import FromOriginalModelMixin
from diffusers.configuration_utils import ConfigMixin, register_to_config
from diffusers.loaders import PeftAdapterMixin
from diffusers.utils import USE_PEFT_BACKEND, logging, scale_lora_layers, unscale_lora_layers
from diffusers.models.attention import FeedForward
from diffusers.models.attention_processor import Attention, AttentionProcessor
from diffusers.models.cache_utils import CacheMixin
from diffusers.models.modeling_outputs import Transformer2DModelOutput
from diffusers.models.modeling_utils import ModelMixin
logger = …
```
=> [refactor] [wip] Wan transformer/pipeline

tests/remote/test_remote_decode.py
Optimized endpoints are live, updates VAE decode endpoints from test versions to production
=> Update VAE Decode endpoints

src/diffusers/pipelines/animatediff/pipeline_animatediff.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_controlnet.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_sparsectrl.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video.py, src/diffusers/pipelines/animatediff/pipeline_animatediff_video2video_controlnet.py
from_single_file can be test with:
motion_adapter = diffusers.MotionAdapter.from_pretrained('chaowenguo/AnimateLCM', torch_dtype=torch.float16, variant='fp16', use_safetensors=True)
pipe = diffusers.AnimateDiffPipeline.from_single_file('https://huggingface.co/chaowenguo/pal/blob/main/chilloutMix-Ni.safetensors', config='chaowenguo/stable-diffusion-v1-5', safety_checker=None, use_safetensors=True, torch_dtype=torch.float16, motion_adapter=motion_adapter)
@yiyixuxu @hlky 
Anyone in the community is free to review the PR once the tests have passed. Feel free to …
=> add from_single_file to animatediff 

src/diffusers/models/unets/unet_2d.py
**Problem:**
In UNet2DModel, the variable prev_output_channel is assigned twice in a redundant manner.
**Fixes:**
Removing the second assingnement
=> Fix redundant prev_output_channel assignment in UNet2DModel

src/diffusers/quantizers/quantization_config.py, tests/quantization/torchao/test_torchao.py
Passing `MappingType` for `TorchAoConfig` is invalid
```
File "/workspace/volume/zty/diffusers/src/diffusers/configuration_utils.py", line 123, in register_to_config
logger.debug(f"Updating config from {previous_dict} to {internal_dict}")
^^^^^^^^^^^^^^^
File "/workspace/volume/zty/diffusers/src/diffusers/quantizers/quantization_config.py", line 671, in __repr__
return f"{self.__class__.__name__} {json.dumps(config_dict, indent=2, sort_keys=True)}\n"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/__init__.py", line 238, in dumps
**kw).encode(obj)
^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 202, in encode
chunks = list(chunks)
^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 432, in _iterencode
yield from _iterencode_dict(o, …
```
=> [Quantization]  support pass MappingType for TorchAoConfig

src/diffusers/quantizers/quantization_config.py
Missing parentheses when calling ```is_torchao_available()``` will result in an import error in systems without ```torchao```.
=> Fix the missing parentheses when calling is_torchao_available in quantization_config.py.

examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py, examples/cogvideo/train_cogvideox_image_to_video_lora.py, examples/cogvideo/train_cogvideox_lora.py, examples/custom_diffusion/train_custom_diffusion.py, examples/dreambooth/train_dreambooth_flux.py, examples/dreambooth/train_dreambooth_lora.py, examples/dreambooth/train_dreambooth_lora_flux.py, examples/dreambooth/train_dreambooth_lora_lumina2.py, examples/dreambooth/train_dreambooth_lora_sana.py, examples/dreambooth/train_dreambooth_lora_sd3.py, examples/dreambooth/train_dreambooth_lora_sdxl.py, examples/dreambooth/train_dreambooth_sd3.py, examples/text_to_image/train_text_to_image_lora_sdxl.py, examples/text_to_image/train_text_to_image_sdxl.py
When args.seed is set to 0, the condition if args.seed else None evaluates to None because 0 is considered a falsy value in Python. This results in None being assigned instead of 0, which can cause unintended behavior when initializing the random generator.
@sayakpaul
=> Fix incorrect seed initialization when args.seed is 0

examples/community/README.md, examples/community/mod_controlnet_tile_sr_sdxl.py
This PR implements a community pipeline that leverages ControlNet Tile and Mixture-of-Diffusers techniques, integrating tile diffusion directly into the latent space denoising process. Designed to overcome the limitations of conventional pixel-space tile processing, this pipeline delivers Super Resolution (SR) upscaling for higher-quality images, reduced processing time, and greater adaptability.
**See Gradio Demo:**
<a href='https://huggingface.co/spaces/elismasilva/mod-control-tile-upscaler-sdxl'><img src='https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue'></a><br>
**More details of implementation**
https://github.com/DEVAIEXP/mod-control-tile-upscaler-sdxl
```python
import torch
from diffusers import ControlNetUnionModel, AutoencoderKL, UniPCMultistepScheduler
from …
```
=> feat: add Mixture-of-Diffusers ControlNet Tile upscaler Pipeline for SDXL

src/diffusers/pipelines/cogview4/pipeline_cogview4.py
https://github.com/huggingface/diffusers/issues/10962
allow prompt_embeds and negative_prompt_embeds to have different sequence length
=> update check_input for cogview4

tests/remote/test_remote_decode.py
Add slow test with various resolutions
=> Add VAE Decode endpoint slow test

.github/workflows/pr_style_bot.yml
This PR updates the style bot workflow to use the newly added GH action in `huggingface_hub` in https://github.com/huggingface/huggingface_hub/pull/2898. I tested the workflow in a diffusers fork here: https://github.com/hanouticelina/diffusers/pull/2 and it works as expected :) 
cc @Wauplin for viz
=> use style bot GH Action from `huggingface_hub`

src/diffusers/loaders/lora_conversion_utils.py
=> Fix loading OneTrainer Flux LoRA

src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_control.py, src/diffusers/pipelines/flux/pipeline_flux_fill.py
Note: I just fixed the docstrings so they match the actual params.
I did not check what the actual values should be for each pipeline. Also there is discrepancy with the values used in the examples at the top of the files.
=> fix default values of Flux guidance_scale in docstrings

src/diffusers/pipelines/flux/pipeline_flux_controlnet.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py, src/diffusers/pipelines/flux/pipeline_flux_controlnet_inpainting.py
```._callback_tensor_inputs``` of Flux controlnet related pipelines are missing some important elements.
This PR is to fix it.
I'll be very appreciated if you can have a check.
@asomoza
=> Fix Flux Controlnet Pipeline _callback_tensor_inputs Missing Some Elements

examples/community/README.md, examples/community/cogvideox_ddim_inversion.py
Add CogVideoX DDIM inversion to community pipelines, as shown in the videos below.
This PR does the same thing as [THUDM/CogVideo#709](https://github.com/THUDM/CogVideo/pull/709), which has been approved.
Inverse and reconstruct with an empty prompt:
https://github.com/user-attachments/assets/cfa69482-8112-4786-8792-6ec14b95152b
Inverse and reconstruct with an editing prompt:
https://github.com/user-attachments/assets/d64e88ca-7e06-4d80-bfaa-acefc19bea9b
members/contributors who may …
=> Add CogVideoX DDIM Inversion to Community Pipelines

src/diffusers/pipelines/wan/pipeline_wan.py, src/diffusers/pipelines/wan/pipeline_wan_i2v.py
I fix some bug in wan i2v pipeline and add a new example
=> fix wan i2v pipeline bugs

src/diffusers/models/transformers/transformer_cogview4.py
Eliminate this:
```
t]V0304 10:24:23.421000 3131076 torch/_dynamo/guards.py:2813] [0/4] [__recompiles] Recompiling function forward in /home/zeyi/repos/diffusers/src/diffusers/models/transformers/transformer_cogview4.py:374
V0304 10:24:23.421000 3131076 torch/_dynamo/guards.py:2813] [0/4] [__recompiles]     triggered by the following guard failure(s):
V0304 10:24:23.421000 3131076 torch/_dynamo/guards.py:2813] [0/4] [__recompiles]     - 0/3: ___check_obj_id(L['self'].rope.freqs_h, 139976127328032)    
V0304 10:24:23.421000 3131076 torch/_dynamo/guards.py:2813] [0/4] [__recompiles]     - 0/2: ___check_obj_id(L['self'].rope.freqs_h, 139976107780960)    
V0304 10:24:23.421000 3131076 torch/_dynamo/guards.py:2813] [0/4] [__recompiles]     - 0/1: ___check_obj_id(L['self'].rope.freqs_h, …
```
=> Fix Graph Breaks When Compiling CogView4

src/diffusers/loaders/peft.py
There's some uncertainty around https://github.com/huggingface/peft/pull/2382. So, we decided to remove the full-key prefix thingy from `diffusers` until https://github.com/huggingface/peft/pull/2382 is merged with a specific direction.
=> [LoRA] remove full key prefix from peft.

src/diffusers/models/transformers/transformer_wan.py
When running on multiple GPUs, currently WAN will crash because the `shift` and `scale` parameters are GPU 0 while the `hidden_states` from the main blocks end up on the last GPU.
```py
shift, scale = (self.scale_shift_table + temb.unsqueeze(1)).chunk(2, dim=1)
hidden_states = (self.norm_out(hidden_states.float()) * (1 + scale) + shift).type_as(hidden_states)`
```
The fix is pretty simple -- ensure shift and scale are on the correct GPU by doing a `.to` to being them to the same device as `hidden_states`.
You can verify the bug by attempting to do inference with multiple GPUs and accelerate:
```py
model_id = "Wan-AI/Wan2.1-I2V-14B-720P-Diffusers"
transformer = WanTransformer3DModel.from_pretrained(model_id,
subfolder="transformer",
device_map="balanced", …
```
=> Fix for multi-GPU WAN inference

src/diffusers/utils/import_utils.py
We have some boilerplate code related to checking for package availability. Refactor so that it uses a function instead.  
=> [Refactor] Clean up import utils boilerplate

src/diffusers/models/attention_processor.py, src/diffusers/models/autoencoders/autoencoder_dc.py, src/diffusers/models/autoencoders/autoencoder_kl_allegro.py, src/diffusers/models/autoencoders/autoencoder_kl_mochi.py, src/diffusers/models/controlnets/controlnet_sparsectrl.py, src/diffusers/models/embeddings.py, src/diffusers/models/transformers/latte_transformer_3d.py, src/diffusers/models/transformers/prior_transformer.py, src/diffusers/models/unets/unet_3d_condition.py, src/diffusers/models/unets/unet_i2vgen_xl.py, src/diffusers/models/unets/unet_motion_model.py, src/diffusers/models/unets/unet_spatio_temporal_condition.py
https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html
> output_size ([int](https://docs.python.org/3/library/functions.html#int), optional) – Total output size for the given axis ( e.g. sum of repeats). If given, it will avoid stream synchronization needed to calculate output shape of the tensor.
=> Use `output_size` in `repeat_interleave`

src/diffusers/pipelines/wan/pipeline_wan_i2v.py
Output changed slightly with #10998 due to where scaling was applied, it has to be applied before `retrieve_latents`. We may want to consider refactoring to allow returning from `encode` before `posterior`/`DiagonalGaussianDistribution`.
https://github.com/user-attachments/assets/5f4f597e-f766-4985-87f6-f19d08b89b30
https://github.com/user-attachments/assets/62680333-25a0-4fac-b5ab-370744b325a5
https://github.com/user-attachments/assets/32feb165-d26b-40a1-bfca-b64f25d367d4
Type hint for Image encoder updated to [`CLIPVisionModelWithProjection`](https://huggingface.co/Wan-AI/Wan2.1-I2V-14B-480P-Diffusers/blob/main/image_encoder/config.json) as there's a warning.
In multi-generator path `latents` is overwritten by `latent_condition`: `latents = latent_condition = …
=> Wan Pipeline scaling fix, type hint warning, multi generator fix

src/diffusers/loaders/lora_base.py, src/diffusers/loaders/peft.py, tests/lora/utils.py
Context: https://github.com/huggingface/diffusers/pull/10187#issuecomment-2717789396
=> [LoRA] change to warning from info when notifying the users about a LoRA no-op

src/diffusers/loaders/lora_conversion_utils.py
https://github.com/huggingface/diffusers//issues/11025 added support for the 14B I2V non-diffusers LoRAs. This adds support for 1.3B T2V non-diffusers LoRAs.
=> [LoRA] feat: support non-diffusers wan t2v loras.

src/diffusers/hooks/group_offloading.py
To understand the issue firstly, here's the output of running Wan T2V with group offloading on 1-frame:
<details>
<summary> code </summary>
```python
import torch
from diffusers import AutoencoderKLWan, WanPipeline, UniPCMultistepScheduler
from diffusers.hooks import apply_group_offloading
from diffusers.utils.logging import set_verbosity_debug
set_verbosity_debug()
model_id = "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
scheduler = UniPCMultistepScheduler(num_train_timesteps=1000, prediction_type="flow_prediction", use_flow_sigmas=True, flow_shift=3.0)
vae = AutoencoderKLWan.from_pretrained(model_id, subfolder="vae", torch_dtype=torch.float32)
pipe = WanPipeline.from_pretrained(model_id, vae=vae, torch_dtype=torch.bfloat16)
onload_device = …
```
=> Group offloading improvements

src/diffusers/models/resnet.py
Fixes https://github.com/huggingface/diffusers/issues/11083
explanation:
When using Torch's distributed training, the Diffusers code will display a "stride mismatch" warning. Simply adding `.contiguous()` in the code can resolve this issue.
=> Resolve stride mismatch in UNet's ResNet to support Torch DDP

.github/workflows/pr_tests_gpu.yml
+ Make the other test jobs in the PR GPU workflow dependent on the styling checks to pass. Sorry for missing it in the previous PR.
=> [CI] uninstall deps properly from pr gpu tests.

src/diffusers/hooks/group_offloading.py, src/diffusers/models/modeling_utils.py
Add a `low_cpu_mem_usage` option to group offloading so that pinning to CPU memory happens when a group is onloaded. The CPU RAM usage should be similar to sequential offloading. 
Benchmarked by running 5 forward passes through the Flux Transformer. Although I am observing that using this approach with blocks increases the inference time much more significantly than when using with leaf level offloading. I haven't dug in much deeper but I suspect pinning and moving a larger number of tensors to GPU is slower than pinning and moving tensors individually with prefetching?
Results:
```
| Config       | offload_type | low_cpu_mem_usage| Runtime (s) | GPU VRAM (GB) | CPU RAM (GB)|
|--------------|--------------|------------------|-------------|---------------|-------------|
| Baseline     | …
```
=> Provide option to reduce CPU RAM usage in Group Offload

docs/source/en/api/pipelines/sana_sprint.md
@lawrence-cj FYI.
@yiyixuxu this is just doc-changes. Okay to merge?
=> [docs] add a note about max_timesteps

src/diffusers/pipelines/sana/pipeline_sana_sprint.py
1. This PR remove used multi-scale bin in pipeline script.
2. Change the sample prompt to non text rendering one.
Cc: @yiyixuxu
=> [SANA-Sprint] remove used multi-scale bin

scripts/convert_sana_to_diffusers.py
This PR fix the bug in sana conversion script;
Cc: @yiyixuxu @sayakpaul
=> [fix SANA-Sprint]

docs/source/ko/training/controlnet.md
* Fixes Controlnet Korean document to make it in sync with the English one.
---
This header translates to `dataset that fills the circle`, which doesn't match the context of the following paragraph, which explains about using other stable diffusion model versions that can be used(v1.4 and 2.1) and how to use custom datasets.
Also, if we see the English version of the same part, the doc only mentions about using custom datasets.
---
So we need to delete the paragraph about other stable diffusion model options so that the doc is in sync with the English one.
@stevhliu and …
=> [doc] Fix Korean Controlnet Train doc

src/diffusers/models/transformers/sana_transformer.py, src/diffusers/pipelines/sana/pipeline_sana.py
This PR add a `timestep_scale` for SANA-Sprint's teacher model
This timestep_scale will be applied to flow matching timesteps and rescales them form [1~1000] to [0~1]
Cc: @yiyixuxu
=> add a timestep scale for sana-sprint teacher model

src/diffusers/loaders/peft.py
This PR changes the behavior of the PeftAdapterMixin interface class so that LoRA modules loaded with `load_lora_adapter` set the `self._hf_peft_config_loaded` flag to True after successful injection. This change fixes issue #11148.
Previously, the `self._hf_peft_config_loaded` flag was not set in `load_lora_adapter()`, only in `add_adapter()` and `add_adapters()`. Some functions within the PEFT code such as `{enable,disable}_adapters()` depend on this flag being set before they will function properly. I believe this change should bring parity between the `add_adapter()`/`add_adapters()` and `load_lora_adapter()` functions.
Since the PeftAdapterMixin class is used by many classes, such as SD3Transformer2DModel (which I was using when I encountered the original issue), this could …
=> Set self._hf_peft_config_loaded to True when LoRA is loaded using `load_lora_adapter` in PeftAdapterMixin class

src/diffusers/models/transformers/latte_transformer_3d.py
`temp_pos_embed` is in `float32`, `hidden_states` is in the appropriate dtype before `hidden_states = hidden_states + self.temp_pos_embed` then it becomes `float32`. `temp_pos_embed` is cast to `hidden_states.dtype` instead.
Fixes #11137
=> Fix LatteTransformer3DModel dtype mismatch with enable_temporal_attentions

src/diffusers/pipelines/wan/pipeline_wan.py, src/diffusers/pipelines/wan/pipeline_wan_i2v.py
Fixes #11163.
Raises a warning if the number of frames to be generated is not a multiple of 4K + 1. The reason for it being that way is because the VAE applies a 4x temporal downscaling/upscaling and the latents are created respecting that.
It is mentioned in the [docs](https://github.com/huggingface/diffusers/blob/617c208bb4cc68fe4518164fee7cbdf5aa44ff78/docs/source/en/api/pipelines/wan.md?plain=1#L408).
=> Raise warning and round down if Wan num_frames is not 4k + 1

docs/source/en/installation.md
Fix environment variables in `installation.md`
See https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables
=> [Docs] Fix environment variables in `installation.md`

tests/quantization/bnb/test_mixed_int8.py
As the title suggest, this PR enables the case to run on XPU. test tesult is shown as below:
```bash
PASSED tests/quantization/bnb/test_mixed_int8.py::BnB8bitBasicTests::test_device_and_dtype_assignment
```
cc @hlky
=> [tests] no hard-coded cuda 

src/diffusers/utils/testing_utils.py
**why do this**
In CUDA implementation,  `reset_max_memory_allocated` is directly routed to `reset_peak_memory_stats` implicitly, as in code https://github.com/pytorch/pytorch/blob/main/torch/cuda/memory.py#L471. So, for pytorch xpu, we didn't implement `reset_max_memory_allocated` and suggest users to directly use `reset_peak_memory_stats` explicitly.
=> map BACKEND_RESET_MAX_MEMORY_ALLOCATED to reset_peak_memory_stats on XPU

src/diffusers/pipelines/pipeline_utils.py
This PR correct the verification of mandatory and optional pipeline components. Currently, if a mandatory component is not informed, an exception is generated due to an operation on incompatible types. The adjustment matches the type of the list of optional components so that the operation is executed correctly and the correct treatment is given to the user.
```
Pipeline <class 'diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl.StableDiffusionXLControlNetPipeline'> expected ['controlnet', 'feature_extractor', 'image_encoder', 'scheduler', 'text_encoder', 'text_encoder_2', 'tokenizer', 'tokenizer_2', 'unet', 'vae'], but only {'tokenizer_2', 'scheduler', 'tokenizer', 'text_encoder', 'vae', 'text_encoder_2', 'unet'} were passed.
File …
```
=> fix: for checking mandatory and optional pipeline components

src/diffusers/models/modeling_utils.py, tests/pipelines/test_pipelines_common.py
https://github.com/huggingface/diffusers/pull/10301/files/8f713111acff4361605df037f576cf6a97a09567#diff-6a3b9a08c1d37dbc341131632415fea800af242a84fb31f1bcd40d725e2eeeeb
=> Revert `save_model` in ModelMixin save_pretrained and use safe_serialization=False in test

docs/source/en/using-diffusers/loading.md
=> [docs] `torch_dtype` map

src/diffusers/pipelines/cogview4/pipeline_cogview4.py, src/diffusers/pipelines/cogview4/pipeline_cogview4_control.py
With  `enable_sequential_cpu_offload` doing `.to(self.text_encoder.device)` does not work as `text_encoder`'s `device` is `meta` until it is actually used, we should use `device` (`device or self._execution_device`) instead.
Tested with `.to("cuda")`, `.enable_sequential_cpu_offload()` and `.enable_model_cpu_offload()`.
Fixes #10958
=> Fix enable_sequential_cpu_offload in CogView4Pipeline

src/diffusers/configuration_utils.py, src/diffusers/schedulers/scheduling_utils.py
Related #10714 #10742
```python
from diffusers import EulerDiscreteScheduler
scheduler = EulerDiscreteScheduler.from_pretrained("")
```
```
(variable) scheduler: Any
```
With the change
```
(variable) scheduler: EulerDiscreteScheduler
```
=> SchedulerMixin from_pretrained and ConfigMixin Self type annotation

src/diffusers/models/transformers/transformer_ltx.py, src/diffusers/models/transformers/transformer_wan.py, src/diffusers/pipelines/ltx/pipeline_ltx.py, src/diffusers/pipelines/ltx/pipeline_ltx_condition.py, src/diffusers/pipelines/ltx/pipeline_ltx_image2video.py
=> Add CacheMixin to Wan and LTX Transformers

examples/community/README.md, examples/community/pipeline_faithdiff_stable_diffusion_xl.py
This PR implements a pipeline for **(CVPR 2025) FaithDiff: Unleashing Diffusion Priors for Faithful Image Super-resolution** 
[[Project Page](https://jychen9811.github.io/FaithDiff_page/)]  &emsp; [[Paper](https://arxiv.org/abs/2411.18824)]
I think this can complement #9740, with a step 1 where it is possible to restore low quality images, in addition to it also allowing a great upscale. For more details see the project links above.
Thanks to @JyChen9811 for his amazing work! Questions about the paper can be directed to him directly.
This example upscale and restores a low-quality image. The input image has a resolution of 512x512 and will be upscaled at a scale of 2x, to a final resolution of 1024x1024. It is possible to upscale to a larger scale, but it is recommended that the input …
=> feat: [Community Pipeline] - FaithDiff Stable Diffusion XL Pipeline

src/diffusers/pipelines/kolors/pipeline_kolors.py
The KolorsPipeline inherits from `StableDiffusionXLLoraLoaderMixin` which expects the pipeline to have two text encoders, whereas Kolors only uses one. This causes an error when trying to load LoRA weights on the pipeline.
Falling back to `StableDiffusionLoraLoaderMixin` fixes the issue.
(1st contribution here, sorry if I did something wrong)
=> Change KolorsPipeline LoRA Loader to StableDiffusion

examples/instruct_pix2pix/train_instruct_pix2pix.py, examples/research_projects/instructpix2pix_lora/train_instruct_pix2pix_lora.py, examples/research_projects/promptdiffusion/convert_original_promptdiffusion_to_diffusers.py, scripts/convert_dance_diffusion_to_diffusers.py, scripts/convert_vae_pt_to_diffusers.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py, src/diffusers/utils/constants.py, src/diffusers/utils/loading_utils.py, src/diffusers/utils/testing_utils.py, utils/fetch_latest_release_branch.py, utils/notify_slack_about_release.py
Fixed requests.get() function call by adding configurable env variable timeout (default is 60 seconds).
Co-authored with @Sai-Suraj-27.
Fixes #7730 
FYI: @DN6 and @asomoza 
=> Fixed requests.get function call by adding timeout parameter.

src/diffusers/loaders/single_file_utils.py
Changes to the LTX VAE for 0.9.5 caused single file loading to break for the 0.9.1 version VAE. This is because we didn't have a `timestep_scale_multiplier` attribute in the decoder and removed it from the checkpoint during conversion. Although I think this might be a mistake because the parameter does exist in the 0.9.1 checkpoint and the [VAE config](https://huggingface.co/diffusers/LTX-Video-0.9.1/blob/a248b564f0d86b8537474efe2b9f0e05a63e087c/vae/config.json#L54) seems to imply that it should be used. 
The changes for 0.9.5 added the `timestep_scale_multiplier` attribute but since we were removing it in the conversion function, the model loading fails when trying to load the 0.9.1 checkpoint. This PR just skips removing the key from the checkpoint during conversion.     …
=> Fix Single File loading for LTX VAE 

src/diffusers/models/autoencoders/autoencoder_kl_mochi.py, tests/models/autoencoders/test_models_autoencoder_mochi.py
This PR fixes `MochiEncoder3D` is missing the `gradient_checkpointing` attribute in current [main:src/src/diffusers/models/autoencoders/autoencoder_kl_mochi.py](https://github.com/huggingface/diffusers/blob/1d37f4205531ab44b34d54726505839c3f7048cd/src/diffusers/models/autoencoders/autoencoder_kl_mochi.py#L438) causing the [forward pass to fail](https://github.com/huggingface/diffusers/blob/1d37f4205531ab44b34d54726505839c3f7048cd/src/diffusers/models/autoencoders/autoencoder_kl_mochi.py#L514) with `AttributeError: 'MochiEncoder3D' object has no attribute 'gradient_checkpointing'`. We simply added `self.gradient_checkpointing = False` in `MochiEncoder3D`.
Also a limited set of tests were added for `AutoencoderKLMochi`: there are a number of tests we skip, but we feel fixing those are not …
=> Add missing MochiEncoder3D.gradient_checkpointing attribute

src/diffusers/pipelines/pixart_alpha/pipeline_pixart_sigma.py
Simple fix to diffused latent dtype not matching vae weights dtype. See error below. I had this issue when loading pipeline in bfloat16 and using accelerate.
```
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/workspace/PixArt-sigma/diffusion/utils/image_evaluation.py", line 150, in generate_images
batch_images = pipeline(
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/workspace/diffusers/src/diffusers/pipelines/pixart_alpha/pipeline_pixart_sigma.py", line 866, in __call__
image = self.vae.decode(latents / …
```
=> ensure dtype match between diffused latents and vae weights

docs/source/en/api/pipelines/deepfloyd_if.md, docs/source/en/api/pipelines/flux.md, docs/source/en/api/pipelines/kolors.md, docs/source/en/api/pipelines/ltx_video.md, docs/source/en/api/pipelines/sana.md, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_3.md, docs/source/en/api/pipelines/stable_diffusion/stable_diffusion_xl.md, docs/source/en/optimization/mps.md
Implements solution proposed in #5894
=> [docs] MPS update

examples/controlnet/train_controlnet_sd3.py
Fixes https://github.com/huggingface/diffusers/issues/11225
=> fix: SD3 ControlNet validation so that it runs on a A100.

tests/pipelines/flux/test_pipeline_flux_redux.py, tests/pipelines/test_pipelines_common.py
`pytest -rA tests/pipelines/flux/test_pipeline_flux_redux.py::FluxReduxSlowTests::test_flux_redux_inference` fail on XPU.
After comparing the output btw XPU and A100, we can confirm the image is similar perceptually.
XPU:
A100:
So, I changed the XPU expectation to make it pass.
I also update the model per legacy comments.
test status:
A100: before this PR **pass**, after this PR **pass**
XPU: before this PR **fail**, after this PR **pass**
=> fix FluxReduxSlowTests::test_flux_redux_inference case failure on XPU

src/diffusers/models/controlnets/controlnet_flux.py
Before this if txt_ids was 3d tensor, line with txt_ids[:1] concat txt_ids by batch dim. Now we first check that txt_ids is 2d tensor (or take first batch element) and then concat by token dim
=> fix flux controlnet bug

tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py
**test case**
`pytest -rA tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py::StableDiffusionInpaintPipelineAsymmetricAutoencoderKLSlowTests::test_stable_diffusion_inpaint_fp16 `
The output image are perceptually same btw XPU and A100.
**XPU**
**A100**
**PR impact**
XPU: before this PR **fail**, after this PR **pass**
A100: before this PR **pass**, after this PR **pass**
=> make test_stable_diffusion_inpaint_fp16 pass on XPU

tests/pipelines/i2vgen_xl/test_i2vgenxl.py
**test case**
`pytest -rA tests/pipelines/i2vgen_xl/test_i2vgenxl.py::I2VGenXLPipelineFastTests::test_dict_tuple_outputs_equivalent`
**symptom on XPU**
> tests/pipelines/test_pipelines_common.py:1337: in test_dict_tuple_outputs_equivalent self.assertLess(max_diff, expected_max_difference) E   AssertionError: 0.008003175 not less than 0.008
**fix**
loose to `expected_max_difference` to 0.009, since XPU has a 0.000004+ w/ current 0.008 threshold.
@hlky, pls help review, thx.
=> make test_dict_tuple_outputs_equivalent pass on XPU

tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py
**test case**
`pytest -rA tests/pipelines/ip_adapters/test_ip_adapter_stable_diffusion.py::IPAdapterSDXLIntegrationTests::test_instant_style_multiple_masks`
**XPU**
**A100**
**PR impact**
XPU: before PR **fail**, after PR **pass**
A100: before PR **fail**, after PR **pass**
=> make test_instant_style_multiple_masks pass on XPU

tests/lora/utils.py
Removes repetitive code for checks and uses a function instead. As a result:
```
53 additions and 249 deletions.
```
=> [Tests] Cleanup lora tests utils

tests/pipelines/unclip/test_unclip.py
Relax tolerance further for the annoying
https://github.com/huggingface/diffusers/actions/runs/14371483535/job/40295293280?pr=11243#step:6:33183
I don't think unCLIP is used much and is worth investigating further. The test without the relaxed tolerance passes with `transformers` latest and `main` locally on my end (tested on both CPU and GPU).
=> [CI] relax tolerance for unclip further

utils/notify_slack_about_release.py
Similar to https://github.com/huggingface/diffusers/pull/11252/
=> do not use `DIFFUSERS_REQUEST_TIMEOUT` for notification bot

src/diffusers/models/autoencoders/autoencoder_kl_mochi.py
This PR fixes an inconsistency in the calculation of `tile_latent_min_width` inside the AutoencoderKLMochi decoder.
Previously, `tile_latent_min_width` was incorrectly calculated using `self.tile_sample_stride_width`:
```python
tile_latent_min_width = self.tile_sample_stride_width // self.spatial_compression_ratio
```
This led to a mismatch with the corresponding height calculation, which correctly used `self.tile_sample_min_height`. The corrected line now uses `self.tile_sample_min_width`.
This discrepancy did not raise errors under default settings (e.g., 848x480 resolution), but could cause incorrect conditional evaluations in edge cases, such as when profiling or testing different resolutions.
Fixes #11291.
@a-r-r-o-w
=> Fix incorrect tile_latent_min_width calculation in AutoencoderKLMochi

src/diffusers/schedulers/scheduling_flow_match_lcm.py
Most cutting-edge image generative models (<a href="https://github.com/Stability-AI/sd3.5?ysclid=m8sp05sq5j831299212">SD3.5</a>, 
<a href="https://github.com/black-forest-labs/flux?ysclid=m8sp107j7777915043">FLUX</a>) are formulated using <a href="https://arxiv.org/abs/2403.03206">flow matching</a>. Moreover, some state-of-the-art distillation methods (<a href="https://github.com/tianweiy/DMD2/tree/main">DMD2</a>, <a href="https://github.com/luosiallen/latent-consistency-model">CD</a>) use stochastic multistep sampling (<a href="https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_lcm.py">LCM scheduler</a>). However, there is no realization of the LCM scheduler for the flow matching formulation. 
Thus, this PR provides a ```scheduling_flow_match_lcm.py``` …
=> flow matching lcm scheduler

tests/pipelines/kandinsky2_2/test_kandinsky_combined.py
loose `expected_max_diff` from `5e-1` to `8e-1` to make KandinskyV22PipelineInpaintCombinedFastTests::test_float16_inference pass on XPU.
=> make KandinskyV22PipelineInpaintCombinedFastTests::test_float16_inference pass on XPU

tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_k_diffusion.py
**test case**
`pytest -rA tests -k "StableDiffusionXLKPipelineIntegrationTests and test_stable_diffusion_karras_sigmas"`
**XPU**
**A100**
**Results**
XPU:    before this PR **fail**, after this PR **pass**
A100:  before this PR **pass**, after this PR **pass**
=> make test_stable_diffusion_karras_sigmas pass on XPU

tests/pipelines/kolors/test_kolors.py
Since there is no difference can be seen from the images generated with single and batched inputs, I adjusted the expected maximum difference from 5e-4 to 5e-3 to make the test pass on both XPU and CUDA.
pls help review it. Thanks! @hlky
=> make `KolorsPipelineFastTests::test_inference_batch_single_identical` pass on XPU

src/diffusers/__init__.py, src/diffusers/schedulers/__init__.py, src/diffusers/utils/dummy_pt_objects.py
use 
```python
from diffusers import FlowMatchLCMScheduler
```
instead of 
```python
from diffusers.schedulers.scheduling_flow_match_lcm import FlowMatchLCMScheduler
```
=> import for FlowMatchLCMScheduler

src/diffusers/models/autoencoders/vae.py
Reproduction
```python
from diffusers.models.autoencoders.vae import Decoder
decoder = Decoder(
up_block_types=["ResnetUpsampleBlock2D"],
)
```
Fixes #11275
=> Fix vae.Decoder prev_output_channel

src/diffusers/__init__.py
I had to switch systems to do the `fix-copies` and somehow this was not included to the original PR.
@yiyixuxu
=> another fix for FlowMatchLCMScheduler forgotten import

src/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video_image2video.py
We need to manually expand the `text_input_ids` to include the token ids for the image. The function responsible for it in transformers has been deprecated, and the logic in the current `LLaVAProcessor` isn't compatible with the way `max_sequence_length` should be applied in this model.  
This PR
1. Adds an `_expand_input_ids_with_image_tokens` function to replicate some of the behaviour in the LLava model in transformers<4.47.1
https://github.com/huggingface/transformers/blob/241c04d36867259cdf11dbb4e9d9a60f9cb65ebc/src/transformers/models/llava/modeling_llava.py#L302
This should keep backwards compatibility and work with the newer transformers versions, provided the prompt template and token indices for the image token do not change (seems unlikely?) 
#11118 …
=> Fix Hunyuan I2V for `transformers>4.47.1`  

docker/diffusers-onnxruntime-cpu/Dockerfile
To fix https://github.com/huggingface/diffusers/actions/runs/14399112217/job/40380687509#step:8:94
=> unpin torch versions for onnx Dockerfile

docs/source/en/api/pipelines/aura_flow.md
@AstraliteHeart could you also review?
=> [docs] add a snippet for compilation in the auraflow docs.

src/diffusers/models/transformers/transformer_hunyuan_video.py, src/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video_image2video.py, tests/pipelines/hunyuan_video/test_hunyuan_image2video.py
Didn't update the Hunyuan Fast tests to account for the fix in #11293, so the PR CI is currently failing. Additionally, a fix for a typo when passing `pixel_values` to the text encoder. 
=> Hunyuan I2V fast tests fix

docs/source/en/_toctree.yml, utils/check_doc_toc.py
Model section and Pipeline section are not properly ordered at the moment [see here](https://github.com/huggingface/diffusers/blob/main/docs/source/en/_toctree.yml)
@stevhliu
=> [BUG] fixed _toctree.yml alphabetical ordering

docs/source/en/api/pipelines/aura_flow.md
=> [docs] add note about use_duck_shape in auraflow docs.

src/diffusers/loaders/lora_pipeline.py
* Propagates `hotswap` in `load_lora_weights()` where it was missing.
* Simplifies the docstrings.
* Fixes some type-annotations.
=> [LoRA] Propagate `hotswap` better

tests/quantization/bnb/test_mixed_int8.py, tests/quantization/utils.py
**test cases**
1. tests/quantization/bnb/test_mixed_int8.py::SlowBnb8bitTests::test_pipeline_cuda_placement_works_with_mixed_int8 PASS
2. tests/quantization/bnb/test_4bit.py::BnB4BitBasicTests::test_model_memory_usage FAIL, but it's ipex issue, validated success when ipex fixed, so still enable and once ipex fixed, it will naturally pass w/o modify test case.
**questions**
1. for `tests/quantization/bnb/test_mixed_int8.py`, I changed the hard-coding `"cuda"` to `device`. I tried directly it's OK to directly use `torch_device`, but I guess the reason you didn't use it is that maybe "rocm" system cannot work under "rocm" `to()`, but work on "cuda" `to`, so I added `+        device = torch_device if torch_device != "rocm" else "cuda"` to workaround. This is just a guess, @hlky, let me know …
=> enable 2 test cases on XPU

src/diffusers/pipelines/pipeline_utils.py
Fixes tests/quantization/bnb/test_mixed_int8.py::SlowBnb8bitTests::test_moving_to_cpu_throws_warning due to this PR.
The issue is that since we used dispatch_model, when we load a 8-bit model, hooks will be attached to it (this is not the case for 4-bit). Due to that, `pipeline_is_sequentially_offloaded` is `True` -> `is_offloaded` also True. Thus, we didn't log the following : 
```python
if (
module.dtype == torch.float16
and str(device) in ["cpu"]
and not silence_dtype_warnings
and not is_offloaded
):
logger.warning(
"Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It"
" is not recommended to move them to `cpu` as running them will fail. Please make"
" sure to use an accelerator to run the pipeline in inference, due to the lack of"
" support for`float16` …
```
=> [BNB] Fix test_moving_to_cpu_throws_warning 

docs/source/en/api/pipelines/wan.md, scripts/convert_wan_to_diffusers.py, src/diffusers/models/transformers/transformer_wan.py, src/diffusers/pipelines/wan/pipeline_wan_i2v.py, tests/pipelines/wan/test_wan_image_to_video.py
will merge once we upload our checkpoint to an official repo :)
```python
import torch
import torchvision.transforms.functional as TF
from diffusers import AutoencoderKLWan, WanImageToVideoPipeline
from diffusers.utils import export_to_video, load_image
from transformers import CLIPVisionModel
model_id = "YiYiXu/Wan2.1-FLF2V-14B-720P-Diffusers"
image_encoder = CLIPVisionModel.from_pretrained(model_id, subfolder="image_encoder", torch_dtype=torch.float32)
vae = AutoencoderKLWan.from_pretrained(model_id, subfolder="vae", torch_dtype=torch.float32)
pipe = WanImageToVideoPipeline.from_pretrained(
model_id, vae=vae, image_encoder=image_encoder, torch_dtype=torch.bfloat16
)
first_frame = load_image("https://huggingface.co/datasets/huggingface/documentation-imag …
```
=> support Wan-FLF2V

examples/community/pipeline_stable_diffusion_xl_controlnet_adapter_inpaint.py
Fixes the community pipeline for [T2I-Adapter](https://github.com/TencentARC/T2I-Adapter) `StableDiffusionXLControlNetAdapterInpaintPipeline` implemented in [pipeline_stable_diffusion_xl_controlnet_adapter_inpaint.py](https://github.com/huggingface/diffusers/blob/eef3d6595456e69a48989c2cc44c739792341e07/examples/community/pipeline_stable_diffusion_xl_controlnet_adapter_inpaint.py), which incorrectly inherited [`StableDiffusionLoraLoaderMixin`](https://github.com/huggingface/diffusers/blob/eef3d6595456e69a48989c2cc44c739792341e07/src/diffusers/loaders/lora_pipeline.py#L117) instead of [`StableDiffusionXLLoraLoaderMixin`](https://github.com/huggingface/diffusers/blob/eef3d6595456e69a48989c2cc44c739792341e07/src/diffusers/loaders/lora_pipeline.py#L571), although this pipeline uses SDXL, not …
=> Fix: `StableDiffusionXLControlNetAdapterInpaintPipeline` incorrectly inherited `StableDiffusionLoraLoaderMixin`

src/diffusers/pipelines/wan/pipeline_wan_i2v.py
`dtype` is set to `torch.float32` when `prepare_latents` is called. This works if the VAE is loaded in `torch.float32` (as done in the docstring). But, loading the VAE in any other dtype fails with a dtype mismatch error.
=> Fix Wan I2V prepare_latents dtype

src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py
This PR adds stochastic sampling to FlowMatchEulerDiscreteScheduler based on https://github.com/Lightricks/LTX-Video/commit/b1aeddd7ccac85e6d1b0d97762610ddb53c1b408 `ltx_video/schedulers/rf.py`, which was added with th release of 0.9.6-distilled. I decoupled the next and current sigma to try to get closer to the `rf.py` implementation of the stochastic sampling, but a second pair of eyes on this would be great.
To try it: 
```py
import torch
from diffusers import LTXVideoTransformer3DModel, FlowMatchEulerDiscreteScheduler, LTXPipeline
transformer = LTXVideoTransformer3DModel.from_pretrained(
"multimodalart/ltxv-2b-0.9.6-distilled",
subfolder="transformer",
variant="bf16"
)
scheduler = …
```
=> Add stochastic sampling to FlowMatchEulerDiscreteScheduler

src/diffusers/hooks/group_offloading.py, tests/hooks/test_group_offloading.py
Fixes #11307 
The previous implementation assumed that the layers were instantiated in order of invocation. This is not true for HiDream (caption projection layers are instantiated after transformer layers).
The new implementation makes sure to first capture invocation order and then apply group offloading. In the case of `use_stream=True`, it does not really make sense to onload more than 1 block at a time, so we also now raise an error if `num_blocks_per_group != 1` when `use_stream=True`
Another possible fix is to simply move the initialization of the caption layers above the transformer blocks.
@sayakpaul @asomoza Could you verify if this fixes it for you?
=> Fix group offloading with block_level and use_stream=True

examples/dreambooth/train_dreambooth_flux.py
This PR will add LANCZOS as a default interpolation mode for the image resizing in the training script for dreambooth flux and if the users prefers they can choose BILINEAR.
Fixes #11390 
@asomoza
=> [train_dreambooth_flux] Add LANCZOS as the default interpolation mode for image resizing

src/diffusers/pipelines/flux/pipeline_flux_controlnet_image_to_image.py
=> [Feature] Added Xlab Controlnet support

examples/community/pipeline_controlnet_xl_kolors.py, examples/community/pipeline_controlnet_xl_kolors_img2img.py, examples/community/pipeline_controlnet_xl_kolors_inpaint.py, examples/community/pipeline_kolors_inpainting.py, scripts/convert_wan_to_diffusers.py, src/diffusers/loaders/lora_conversion_utils.py, src/diffusers/pipelines/pipeline_flax_utils.py, src/diffusers/pipelines/pipeline_loading_utils.py, tests/pipelines/stable_diffusion_2/test_stable_diffusion_diffedit.py
These are primarily ControlNet pipelines for Kolors.
Adapted from: https://github.com/Kwai-Kolors/Kolors
For direct use with diffusers existing `ControlNetModel` + an additional pipeline for inpainting.
Compatibility with diffusers `ControlNetModel` is accomplished via temporary patching of the `ControlNetModel` instance, (no global side effects such as modifying the class itself)
This supports `MultiControlNetModel` as well.
Pipelines here:
KolorsControlNetPipeline
KolorsControlNetImg2ImgPipeline
KolorsControlNetInpaintPipeline
KolorsInpaintPipeline
Complete doc with example strings, but could use a look over.
Wish to contribute these to community pipelines, these could be of reference (or adapted) to implement these pipelines in mainline diffusers if desired.
I wrote these for …
=> Kolors additional pipelines, community contrib

examples/dreambooth/train_dreambooth_lora.py
It makes LANCZOS the default interpolation mode for the image resizing. It fixes https://github.com/huggingface/diffusers/issues/11390.
@asomoza
=> [train_dreambooth_lora.py] Set LANCZOS as default interpolation mode for resizing

tests/models/test_modeling_common.py
Not really sure how it was passed.
=> [tests] fix import.

examples/text_to_image/train_text_to_image.py
=> [train_text_to_image] Better image interpolation in training scripts follow up

src/diffusers/hooks/group_offloading.py
Addresses: https://github.com/huggingface/diffusers/pull/11375#discussion_r2061990877
Note that you could use `num_blocks_per_group > 1` when using streams (the previous implementation allowed that, but only if the initialization order of blocks was the same as invocation order), but typically the computation of a single block completes before the next block finishes onloading, so setting it to `1` and only supporting that case seems reasonable.
=> Raise warning instead of error for block offloading with streams

tests/pipelines/marigold/test_marigold_intrinsics.py
@a-r-r-o-w @DN6 , pls help review, thx.
=> enable marigold_intrinsics cases on XPU

src/diffusers/models/transformers/transformer_hunyuan_video.py
Fixes https://github.com/huggingface/diffusers/pull/11431#pullrequestreview-2798005237
Will run the full model for testing in some time.
<details>
<summary> testing code </summary>
```python
import torch
from diffusers import HunyuanVideoTransformer3DModel
@torch.no_grad()
def main():
device = "cuda"
dtype = torch.bfloat16
batch_size = 1
num_channels = 4
num_frames = 2
height = 4
width = 4
sequence_length = 8
transformer = HunyuanVideoTransformer3DModel(
in_channels=4,
out_channels=4,
num_attention_heads=2,
attention_head_dim=10,
num_layers=2,
num_single_layers=2,
num_refiner_layers=1,
patch_size=1,
patch_size_t=1,
guidance_embeds=True,
text_embed_dim=16,
pooled_projection_dim=8,
rope_axes_dim=(2, 4, 4),
).to(device=device, dtype=dtype)
hidden_states = torch.randn(batch_size, …
```
=> `torch.compile` fullgraph compatibility for Hunyuan Video

tests/pipelines/test_pipelines_common.py, tests/pipelines/unidiffuser/test_unidiffuser.py
w/ `pytest -rA tests/pipelines/unidiffuser/test_unidiffuser.py`, all cases passed except below 2:
> tests/pipelines/unidiffuser/test_unidiffuser.py::UniDiffuserPipelineFastTests::test_cpu_offload_forward_pass_twice
tests/pipelines/unidiffuser/test_unidiffuser.py::UniDiffuserPipelineFastTests::test_model_cpu_offload_forward_pass
these 2 cases fail both on cuda and xpu, track through this issue https://github.com/huggingface/diffusers/issues/11443.
=> enable unidiffuser test cases on xpu

tests/pipelines/stable_diffusion_safe/test_safe_diffusion.py
`pytest -rA tests/pipelines/stable_diffusion_safe/test_safe_diffusion.py` all 7 cases passed on XPU and A100.
=> make safe diffusion test cases pass on XPU and A100

tests/models/transformers/test_models_transformer_hunyuan_video.py
=> [test_models_transformer_hunyuan_video] help us test torch.compile() for impactful models

examples/controlnet/train_controlnet_sdxl.py
=> Add LANCZOS as default interplotation mode.

src/diffusers/models/transformers/transformer_wan.py, tests/models/transformers/test_models_transformer_wan.py
Merged https://github.com/huggingface/diffusers/pull/11451 into this PR to keep it complete. Part of https://github.com/huggingface/diffusers/issues/11430
To test, run the following in a GPU machine:
```bash
RUN_SLOW=1 RUN_COMPILE=1 pytest tests/models/transformers/test_models_transformer_wan.py -k "test_torch_compile_recompilation_and_graph_break"
```
@tongyu0924 FYI.
=> [WAN] fix recompilation issues

src/diffusers/utils/import_utils.py
pr <https://github.com/huggingface/diffusers/pull/11161> refactored `_is_package_available`,  
but it introduced a major performance regression.    
diffusers load now takes up to **~5sec** while it was taking **~0.5sec** earlier.  
```py
import time
t0 = time.time()
import torch # preload torch so its not part of diffusers import time
t1 = time.time()
print(f'torch: {t1-t0:.3f}')
import diffusers.utils.import_utils
t2 = time.time()
print(f'utils: {t2-t1:.3f}')
```
this is due to very expensive call to `importlib_metadata.packages_distributions()` which is done for every single installed package (each call can be ~0.2sec and it quickly adds up).
this pr simply changes the logic so the call is done once and cached.
result is that diffusers startup is back to 0.5sec as usual.
cc @yiyixuxu …
=> cache packages_distributions

examples/dreambooth/train_dreambooth_lora_lumina2.py
Fixes #11390 
This PR sets LANCZOS as the default interpolation method for image resizing during training, improving visual quality and preserving fine details in training inputs.
Users can still override it with --image_interpolation_mode bilinear for faster processing if needed.
=> [train_dreambooth_lora_lumina2] Add LANCZOS as the default interpolation mode for image resizing

examples/dreambooth/README_hidream.md, examples/dreambooth/train_dreambooth_lora_hidream.py, src/diffusers/quantizers/quantization_config.py
This PR adds support to apply quantization from `bitsandbytes` to the _base_ model before we attach LoRA params to it and train them. This helps reduce the memory consumption quite a bit:
```bash
(with quantization)
Memory (before device placement): 9.085089683532715 GB.
Memory (after device placement): 34.59585428237915 GB.
Memory (after backward): 36.90267467498779 GB.
(without quantization)
Memory (before device placement): 0.0 GB.
Memory (after device placement): 57.6400408744812 GB.
Memory (after backward): 59.932212829589844 GB.
```
With `--offload`, we can reduce further. The reason why we see some memory before device placement in the case of quantization is because, by default bnb quantized models are placed on the GPU first.
Quick test:
```bash
export …
```
=> [training] feat: enable quantization for hidream lora training.

examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py
=> Set LANCZOS as the default interpolation method for image resizing.

examples/text_to_image/train_text_to_image_lora_sdxl.py
Updates the training script for txt to img sdxl with lora support as per #11390
@asomoza
=> Update training script for txt to img sdxl with lora supp with new interpolation.

.github/workflows/pr_tests.yml, src/diffusers/dependency_versions_table.py
We run the dependency versioning check when an update is just for `setup.py` like in https://github.com/huggingface/diffusers/pull/11502. Hence it went unnoticed.
=> update dep table.

src/diffusers/loaders/lora_base.py, src/diffusers/loaders/lora_pipeline.py, src/diffusers/loaders/peft.py
We have multiple recurrences of using the following patterns in our LoRA codebase:
* `k.replace(f"{prefix}.", "")`
* `k[len(f"{prefix}.") :]`
It's just mind-twisting sometimes and I think `removeprefix()` just makes it easier.
I have run the integration tests and ensured they are passing.
=> [LoRA] use `removeprefix` to preserve sanity.

src/diffusers/loaders/lora_conversion_utils.py
Fixes #11441
I tried to keep changeset somehow minimal, while doing it the same way as it's already done.
@sayakpaul would be the most relevant I suppose.
=> [lora_conversion] Enhance key handling for OneTrainer components in LORA conversion utility (#11441)

src/diffusers/loaders/lora_conversion_utils.py, src/diffusers/loaders/lora_pipeline.py
Fixes: https://github.com/huggingface/diffusers/issues/11383
To check:
```py
from transformers import PreTrainedTokenizerFast, LlamaForCausalLM
import torch 
repo_id = "HiDream-ai/HiDream-I1-Full"
tokenizer_4 = PreTrainedTokenizerFast.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
text_encoder_4 = LlamaForCausalLM.from_pretrained(
"meta-llama/Meta-Llama-3.1-8B-Instruct",
output_hidden_states=True,
output_attentions=True,
)
pipeline = DiffusionPipeline.from_pretrained(
repo_id, 
tokenizer_4=tokenizer_4,
text_encoder_4=text_encoder_4,
torch_dtype=torch.bfloat16
).to("cuda")
pipeline.load_lora_weights("sayakpaul/different-lora-from-civitai", weight_name="486_hidream.safetensors")
```
Cc: @vladmandic
=> [LoRA] support non-diffusers hidream loras

src/diffusers/pipelines/ltx/pipeline_ltx.py
The [LTX Video HuggingFace Documentation](https://huggingface.co/docs/diffusers/main/en/api/pipelines/ltx_video) states:
> Note: The recommended dtype is for the transformer component. The VAE and text encoders can be either torch.float32, torch.bfloat16 or torch.float16 but the recommended dtype is torch.bfloat16 as used in the original repository.
This implies that the VAE dtype can be different than the rest of the pipeline. e.g. the VAE could be in fp32 while the transformer is in fp16.
However, when running with fp32 VAE and fp16 transformer, I hit the following error.
```bash
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
```
I believe the proper fix should be to ensure that the latents tensor (input) is the same dtype as the VAE (bias?). We can ensure …
=> [LTXPipeline] Update latents dtype to match VAE dtype

tests/pipelines/dit/test_dit.py
for `test_dit_512` case, both A100 and XPU don't pass with current pixel delta criteria(yes, as we noticed many times, there 2 have similar numerical behavior), I propose to use cosine similarity as some of other cases used(like `controlnet_impaint`). With proposed changes, both XPU and A100 passed.
@DN6 @a-r-r-o-w , pls help review, thx.
=> enable dit integration cases on xpu

src/diffusers/models/transformers/transformer_hunyuan_video_framepack.py
See https://github.com/huggingface/diffusers/pull/11520#issuecomment-2862940794
=> Change Framepack transformer layer initialization order

src/diffusers/models/transformers/transformer_hunyuan_video_framepack.py, tests/models/transformers/test_models_transformer_hunyuan_video_framepack.py
@a-r-r-o-w the following two model splitting tests are failing:
```bash
FAILED tests/models/transformers/test_models_transformer_hunyuan_video_framepack.py::HunyuanVideoTransformer3DTests::test_model_parallelism - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argumen...
FAILED tests/models/transformers/test_models_transformer_hunyuan_video_framepack.py::HunyuanVideoTransformer3DTests::test_sharded_checkpoints_device_map - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument
```
Could you take a look when you have time? There are similar failures in HunuyanVideo transformer model, too, just as an FYI. Also, cc: @SunMarc
=> [tests] add tests for framepack transformer model.

docs/source/en/_toctree.yml, docs/source/en/api/pipelines/framepack.md, docs/source/en/api/pipelines/hunyuan_video.md, src/diffusers/pipelines/hunyuan_video/pipeline_hunyuan_video_framepack.py
Example:
```python
import torch
from diffusers import HunyuanVideoFramepackPipeline, HunyuanVideoFramepackTransformer3DModel
from diffusers.hooks import apply_group_offloading
from diffusers.utils import export_to_video, load_image
from transformers import SiglipImageProcessor, SiglipVisionModel
transformer = HunyuanVideoFramepackTransformer3DModel.from_pretrained(
"lllyasviel/FramePack_F1_I2V_HY_20250503", torch_dtype=torch.bfloat16
)
feature_extractor = SiglipImageProcessor.from_pretrained(
"lllyasviel/flux_redux_bfl", subfolder="feature_extractor"
)
image_encoder = SiglipVisionModel.from_pretrained(
"lllyasviel/flux_redux_bfl", subfolder="image_encoder", torch_dtype=torch.float16
)
pipe = HunyuanVideoFramepackPipeline.from_pretrained(
"hunyuanvideo-community/HunyuanVideo", …
```
=> Hunyuan Video Framepack F1

tests/pipelines/dance_diffusion/test_dance_diffusion.py, tests/pipelines/kandinsky2_2/test_kandinsky_controlnet.py, tests/pipelines/kandinsky2_2/test_kandinsky_controlnet_img2img.py, tests/pipelines/latent_diffusion/test_latent_diffusion.py, tests/pipelines/musicldm/test_musicldm.py, tests/pipelines/shap_e/test_shap_e.py, tests/pipelines/shap_e/test_shap_e_img2img.py
incl:
1. kandinsky2_2
2. latent_diffusion
3. dance_diffusion
4. musicldm
5. shap_e
PASSED
@a-r-r-o-w  @DN6 , pls help review, thx very much.
=> enable several pipeline integration tests on XPU

docs/source/en/api/models/hidream_image_transformer.md, src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/models/transformers/transformer_hidream_image.py, src/diffusers/pipelines/hidream_image/pipeline_hidream_image.py, tests/quantization/gguf/test_gguf.py
Adding single file support for the HiDream transformer so that it can load GGUF checkpoints.  
#11344
=> [Single File] GGUF/Single File Support for HiDream

src/diffusers/quantizers/gguf/utils.py
This helps with torch.compile compilation latency. Avoiding unnecessary computation should also lead to a slightly improved eager latency.
=> [gguf] Refactor __torch_function__ to avoid unnecessary computation

docs/source/en/optimization/torch2.0.md
https://github.com/huggingface/accelerate/pull/3529
=> [docs] Regional compilation docs

src/diffusers/utils/testing_utils.py
by following transformers practice: https://github.com/huggingface/transformers/blob/main/src/transformers/testing_utils.py#L2977
@a-r-r-o-w @DN6 , pls help review, thx.
=> enhance value guard of _device_agnostic_dispatch

src/diffusers/loaders/lora_base.py
Reverts back from a raised error to a warning if a LoRA repository contains multiple `*.safetensors` files. 
Pros: 
1. Avoids applications breaking if a 3rd party does an action, scenario: a LoRA repo had a single LoRA, so the codebase works. Then, the LoRa repo author uploads a second LoRA to the repo. Now the app breaks due to the action of the 3rd party 
2. More Hub-centric: users can just pass the Hub nicename of a LoRA without worrying too much about weight-names (not an obvious interaction on the Hub to get weight names)
I know there are pros and cons and I'm sure this has been discussed before. But this is such a simple PR that I just did it in case it's helpful. Feel free to reject/close if not aligned and happy to further discuss in case we can find some other solution. …
=> Revert error to warning when loading LoRA from repo with multiple weights

src/diffusers/loaders/lora_conversion_utils.py
Doesn't handle non-zero `diff` and `diff_b` keys yet.
=> [WIP][LoRA] start supporting kijai wan lora.

src/diffusers/loaders/lora_pipeline.py, tests/lora/utils.py
Fixes https://github.com/huggingface/diffusers/issues/11592
Additionally, adds a test to check the following flow of operations work as expected:
`load_lora_weights()` -> `delete_adapters()` -> `load_lora_weights()`.
=> [LoRA] minor fix for `load_lora_weights()` for Flux and a test

examples/advanced_diffusion_training/README.md, examples/advanced_diffusion_training/README_flux.md, examples/dreambooth/README_flux.md
address #11564 by adding notes to README files to install prodigy
=> [training docs] smol update to README files 

src/diffusers/utils/torch_utils.py
I added npu selection for get_device, otherwise the npu cannot be used for "pipe.enable_model_cpu_offload()" when doing the inference task
=> Adding NPU for get device function

src/diffusers/models/transformers/transformer_wan.py
An issue was reported in PyTorch regarding dtype compat in the Wan model (see https://github.com/pytorch/pytorch/issues/148670) when using MPS as the backend. The issue is that Wan's RoPE implementation uses float64, which isn't a supported dtype on MPS and results in `TypeError: Trying to convert ComplexDouble to the MPS backend but it does not have support for that dtype.`
This PR proposes to downcast freqs on MPS backends. Looking at prior PRs (#10776, #9133, etc) this seems to be the preferred method, but please let me know if there's a different approach you'd like me to take and I'll amend as needed.
FYI; There's a separate issue with Wan when using MPS backends outlined in https://github.com/pytorch/pytorch/issues/148670#issuecomment-2928499989. My hunch is that this bug is a …
=> Use float32 RoPE freqs in Wan with MPS backends

docs/source/en/_toctree.yml, docs/source/en/api/cache.md, docs/source/en/optimization/cache.md
Make the caching docs more visible and give a little more context behind the methods.
=> [docs] Caching methods

src/diffusers/__init__.py
Lets us do `from diffusers import PipelineQuantizationConfig` instead of `from diffusers.quantizers import PipelineQuantizationConfig`.
=> [chore] bring PipelineQuantizationConfig at the top of the import chain.

tests/models/test_modeling_common.py
Only makes sense to have one after https://github.com/huggingface/diffusers/pull/11605. To run: 
`RUN_SLOW=1 RUN_COMPILE=1 pytest tests/models/ -k "test_compile_with_group_offloading"`.
Cc: @stevhliu do you think we should document this thing in our `torch.compile()` documentation section?
=> [tests] add test for torch.compile + group offloading

tests/models/transformers/test_models_transformer_flux.py, tests/models/transformers/test_models_transformer_hunyuan_video.py, tests/models/transformers/test_models_transformer_ltx.py, tests/models/transformers/test_models_transformer_wan.py, tests/models/unets/test_models_unet_2d_condition.py
The way compiler test mixin classes were added to the actual model test classes was flawed as it was making the non-compilation tests dependent on the flags required to be True by the compiler test mixins. 
If we run `pytest tests/models/unets/test_models_unet_2d_condition.py -k "device_map"`, for example, from the `main` it will be entirely skipped. This shouldn't happen.
This PR fixes this behavior.
=> [tests] Fix how compiler mixin classes are used

src/diffusers/pipelines/flux/pipeline_flux_inpaint.py
This fixes pipeline_flux_inpaint.py to appropriately return the entire finished image instead of just the inpainted area when padding_mask_crop is used.
@yiyixuxu 
@asomoza
=> Update pipeline_flux_inpaint.py to fix padding_mask_crop returning only the inpainted area

src/diffusers/utils/dynamic_modules_utils.py, tests/pipelines/test_pipelines.py
When the repo path for a model containing custom code contains `.`, the code fails to import it correctly because `.` is interpreted by the Python import machinery as a module separator. This issue was reported in Transformers (https://github.com/huggingface/transformers/issues/28919) and was fixed in https://github.com/huggingface/transformers/pull/29175. The same issue exists in Diffusers, so this PR brings over that fix with minor changes to account for how Diffusers names the cache directory.
@yiyixuxu @sayakpaul @asomoza
=> Allow remote code repo names to contain "."

src/diffusers/pipelines/wan/pipeline_wan_video2video.py
While integrating SkyReels-V2 models, I came across this:  Major Wan-related repos including [Wan-Video/Wan2.1](https://github.com/Wan-Video/Wan2.1/blob/ec902046f6f8b264cff94bd8b2cb1d44c10090e3/wan/modules/vae.py#L535-L542), [modelscope/DiffSynth-Studio](https://github.com/modelscope/DiffSynth-Studio/blob/ef2a7abad478d6f91c0839be8f491587e36fda9f/diffsynth/models/wan_video_vae.py#L542-L550), and [SkyworkAI/SkyReels-V2](https://github.com/SkyworkAI/SkyReels-V2/blob/04253950ee88d884ba714e9da5110885cf93457f/skyreels_v2_infer/modules/vae.py#L495-L501) prefer `sample_mode == "argmax"` for the encoding's output of their VAEs. Also, at the other Wan pipelines in `diffusers`, too. Am I correct?
Also, fixes a typo.
<table>
<tbody>
<tr>
<td align="center" colspan="2"><strong>Input …
=> [`Wan`] Fix VAE sampling mode in `WanVideoToVideoPipeline`

src/diffusers/utils/import_utils.py
Set a default value for _torch_version if torch is disabled. This fixes an ImportError in hub_utils.py when it tries to import [_torch_version](https://github.com/huggingface/diffusers/blob/main/src/diffusers/utils/hub_utils.py#L61). This is not riased for Jax and Flax because they already set `_jax_version = "N/A"` as a default.
```
ImportError: cannot import name '_torch_version' from 'diffusers.utils.import_utils'
```
Core library:
- General functionalities: @sayakpaul @yiyixuxu @DN6
=> Set _torch_version to N/A if torch is disabled.

src/diffusers/pipelines/flux/pipeline_flux.py
(discussed with @sayakpaul in Slack) I have been optimizing inference performance for the Flux model and saw a DtoH sync point in the performance trace coming from the use of nonzero() followed by item() in the scheduler's `index_for_timestep()` logic: https://github.com/huggingface/diffusers/blob/b0f7036d9af75c5df0f39d2d6353964e4c520534/src/diffusers/schedulers/scheduling_flow_match_euler_discrete.py#L351-L363
This sync causes a minor but non-negligible gap in GPU utilization during the first timestep, especially when torch.compile is utilized (due to cpu-side Dynamo cache lookup overhead after the sync point), as shown here:
AFAICT this can be avoided by manually calling `scheduler.set_begin_index(0)`, so this PR does that for `FluxPipeline`. Locally, I was able to see the sync point go …
=> Avoid DtoH sync from access of nonzero() item in scheduler

src/diffusers/loaders/lora_conversion_utils.py
Fixes #11702.
@apolinario Could you give it a try?
=> Support Wan AccVideo lora

src/diffusers/loaders/lora_conversion_utils.py
Fixes #11709
```python
import torch
import PIL.Image
from diffusers import AutoencoderKLWan, WanVACEPipeline, GGUFQuantizationConfig, AutoModel, WanTransformer3DModel
from diffusers.schedulers.scheduling_unipc_multistep import UniPCMultistepScheduler
from diffusers.utils import export_to_video, load_image
from transformers import UMT5EncoderModel
vae = AutoencoderKLWan.from_pretrained(
"Wan-AI/Wan2.1-VACE-14B-diffusers",
subfolder="vae",
torch_dtype=torch.float32,
)
pipe = WanVACEPipeline.from_pretrained(
"Wan-AI/Wan2.1-VACE-14B-diffusers",
vae=vae,
torch_dtype=torch.bfloat16
) 
flow_shift = 5.0  # 5.0 for 720P, 3.0 for 480P
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config, flow_shift=flow_shift)
pipe.load_lora_weights(
"Kijai/WanVideo_comfy", …
```
=> Support more Wan loras (VACE)

examples/advanced_diffusion_training/README_flux.md, examples/advanced_diffusion_training/test_dreambooth_lora_flux_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py, examples/dreambooth/README_flux.md
follow up on: #11324 and #11707
=> [LoRA training] update metadata use for lora alpha + README

tests/pipelines/wan/test_wan_vace.py
Wan VACE encoded latetents are always in FP32. Skip these tests since they are not designed to account for mixed dtype inputs. 
=> [CI] Fix WAN VACE tests

tests/pipelines/sana/test_sana_controlnet.py, tests/pipelines/sana/test_sana_sprint_img2img.py
Fix random tensor init in SANA tests so that device is properly set. 
=> [CI] Fix SANA tests

docs/source/en/_toctree.yml, docs/source/en/optimization/memory.md, docs/source/en/optimization/speed-memory-optims.md
Follows up on #11670 and #11672 to document combinations of quantization, torch.compile, and offloading.
=> [docs] Quantization + torch.compile + offloading

docs/source/en/api/loaders/lora.md, src/diffusers/loaders/lora_base.py, src/diffusers/loaders/peft.py, src/diffusers/loaders/unet.py
* Fix docstrings examples.
* Add missing docstrings.
* Organize the position of the methods and properties.
=> [docs] minor cleanups in the lora docs.

tests/pipelines/amused/test_amused_inpaint.py, tests/pipelines/test_pipelines_common.py
1. fix CI failure imported in https://github.com/huggingface/diffusers/pull/11759
2. adjust criteria for test case: `tests/pipelines/amused/test_amused_inpaint.py::AmusedInpaintPipelineSlowTests::test_amused_512_fp16`
=> adjust tolerance criteria for `test_float16_inference` in unit test

docs/source/en/api/pipelines/flux.md, src/diffusers/pipelines/flux/pipeline_flux_kontext.py
Fixes the content filter import to match the latest implementation and a mistake in the pipeline docstring
=> Kontext fixes

src/diffusers/pipelines/flux/pipeline_flux.py, src/diffusers/pipelines/flux/pipeline_flux_kontext.py
Similar to https://github.com/huggingface/diffusers/pull/11696.
We're working on bringing Kontext to https://github.com/huggingface/flux-fast/.
Cc: @jbschlosser
=> remove syncs before denoising in Kontext

src/diffusers/loaders/unet_loader_utils.py
Resolves #11816
The following call proved to be a bottleneck when setting a lot of LoRA adapters in diffusers:
https://github.com/huggingface/diffusers/blob/cdaf84a708eadf17d731657f4be3fa39d09a12c0/src/diffusers/loaders/peft.py#L482
This is because we would repeatedly call `unet.state_dict()`, even though in the standard case, it is not necessary:
https://github.com/huggingface/diffusers/blob/cdaf84a708eadf17d731657f4be3fa39d09a12c0/src/diffusers/loaders/unet_loader_utils.py#L55
This PR fixes this by deferring this call, so that it is only run when it's necessary, not earlier.
Note: This PR doesn't change the fact that `set_adapters` becomes slower the more adapters are already loaded, but since it speeds up the whole process by a factor of approximately 10x, `set_adapters` is much less …
=> ENH: Improve speed of function expanding LoRA scales

examples/flux-control/train_control_lora_flux.py
This PR fixes an issue in `examples/flux-control/train_control_lora_flux.py` where `train_norm_layers` **_(if set)_** were unintentionally disabled (`requires_grad = False`) after calling `flux_transformer.add_adapter(transformer_lora_config)`. As a result, the normalization layers were not being trained as expected.
This PR fixes that.
@sayakpaul — Appreciate it if you could take a look.
=> fix norm not training in train_control_lora_flux.py

src/diffusers/configuration_utils.py, src/diffusers/guiders/auto_guidance.py, src/diffusers/guiders/perturbed_attention_guidance.py, src/diffusers/guiders/skip_layer_guidance.py, src/diffusers/guiders/smoothed_energy_guidance.py, src/diffusers/hooks/layer_skip.py, src/diffusers/hooks/smoothed_energy_guidance_utils.py
Adds support for serializing/deserializing custom config objects. LMK if this approach does not sound good.
@yiyixuxu Could you elaborate on https://github.com/huggingface/diffusers/pull/11862#issuecomment-3037797375?
> (I think we probably just don't need the special config class now that it is a ConfigMixin, but it is up to you)
Do you mean we completely get rid of LayerSkipConfig? And if so, how do we provide the users with the option to conditionally skip different layers/attention scores?
Testing code:
```python
import json
import torch
from diffusers import AutoGuidance, SkipLayerGuidance, ClassifierFreeGuidance, SmoothedEnergyGuidance, SmoothedEnergyGuidanceConfig, AdaptiveProjectedGuidance, PerturbedAttentionGuidance, ClassifierFreeZeroStarGuidance, …
```
=> Modular custom config object serialization

src/diffusers/pipelines/controlnet/pipeline_controlnet_blip_diffusion.py
`transformers` has likely introduced a breaking change which is what is causing [this](https://github.com/huggingface/diffusers/actions/runs/16109620596/job/45450689391?pr=11876#step:8:3354):
```
FAILED tests/pipelines/controlnet/test_controlnet_blip_diffusion.py::BlipDiffusionControlNetPipelineFastTests::test_attention_slicing_forward_pass - TypeError: CLIPEncoder.forward() got an unexpected keyword argument 'return_dict'
```
But in retrospect, we should deprecate the BLIP ControlNet pipeline anyway. This PR does that.
=> [chore] deprecate blip controlnet pipeline.

docs/source/en/optimization/fp16.md, docs/source/en/optimization/speed-memory-optims.md
Light refactor of the regional compilation docs and adds the https://pytorch.org/blog/presenting-flux-fast-making-flux-go-brrr-on-h100s/ blog post.
=> [docs] torch.compile blog post

examples/controlnet/train_controlnet_sd3.py
This PR addresses issue #11867  by modifying vae processing during training to match the inference pipeline.
=> Fix: Align VAE processing in ControlNet SD3 training with inference

tests/pipelines/flux/test_pipeline_flux.py
Cleaner error reports when using unittest asserts instead of raw asserts
=> [tests] Improve Flux tests

src/diffusers/loaders/single_file_model.py, src/diffusers/loaders/single_file_utils.py, src/diffusers/loaders/transformer_flux.py, src/diffusers/loaders/transformer_sd3.py, src/diffusers/loaders/unet.py, src/diffusers/models/modeling_utils.py
Should fix: https://huggingface.slack.com/archives/C03UQJENJTV/p1752491900178599
When this change was added, I was under the impression that the synchronization must be used when using non_blocking data transfer. This is true if the non_blocking device transfer was async in respect to other cuda ops (i.e. if we were using a non-default stream for data transfer). It is not the case here, so it seems like we don't need a sync.
=> Remove device synchronization when loading weights

src/diffusers/commands/custom_blocks.py, src/diffusers/modular_pipelines/modular_pipeline.py, src/diffusers/modular_pipelines/modular_pipeline_utils.py
1. Updates ModularPipelineBlock serialization so that type hint, repo, subfolder, variant information gets saved when calling `block.save_pretrained`. Useful for when you have custom pipeline blocks that have components that use `from_pretrained`
2. Pass `trust_remote_code` to `hub_kwargs` so that it gets passed through to model loading. Useful when loading custom pipeline blocks with models that also have custom code. e.g. Florence2 in transformers
3. Makes subfolder default value an empty string in ComponentSpec because passing `subfolder=None` to transformer Auto classes does not work. [We also substitute `None` for an empty string](https://github.com/huggingface/diffusers/blame/9c13f8657986e68f5f05987912c54432fd28d86f/src/diffusers/models/modeling_utils.py#L1096) when running …
=> [Modular] Updates for Custom Pipeline Blocks

src/diffusers/models/attention_dispatch.py, src/diffusers/models/modeling_utils.py
- Fixes #11959
- Instead of raising warning with logger and erroring out with a NoneType exception, we now check the imports during runtime and error out instead
```python
import torch
from diffusers import FluxPipeline
pipe = FluxPipeline.from_pretrained(
"black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16
).to("cuda")
image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/flux_ip_adapter_input.jpg").resize((1024, 1024))
pipe.load_ip_adapter(
"XLabs-AI/flux-ip-adapter",
weight_name="ip_adapter.safetensors",
image_encoder_pretrained_model_name_or_path="openai/clip-vit-large-patch14"
)
pipe.set_ip_adapter_scale(1.0)
pipe.transformer.set_attention_backend("_flash_3") # errors out if you don't …
```
=> Remove logger warnings for attention backends and hard error during runtime instead

tests/models/test_modeling_common.py
Should enforce this for 
https://github.com/huggingface/diffusers/blob/7ae6347e330a2b12da0b563370b6605a18bf0ed2/tests/quantization/test_torch_compile_utils.py#L26
But I will open a separate PR for that.
=> [tests] enforce torch version in the compilation tests.

src/diffusers/hooks/group_offloading.py
If compiling with `fullgraph=True`, we first need to remove the `torch.compiler.disable` calls we have. Once this is done, Dynamo will error out on the logger statements because they can't be traced. We can conditionally log them to fix this error (what this PR does). We will then hit an error because of using context manager for pinning tensors. We can move the body of that function into the functions directly to avoid using context managers. We will then error out on the call to `tensor.is_pinned()` because Dynamo cannot trace it, which seems like a problem that needs to be fixed on pytorch-side.
If compiling with `fullgraph=False`, we add a lot of unnecessary guards and have some more graph breaks. By only conditionally doing the logging, we can avoid some of them.
See this comment: …
=> [compile] logger statements create unnecessary guards during dynamo tracing

src/diffusers/pipelines/skyreels_v2/pipeline_skyreels_v2_i2v.py, src/diffusers/pipelines/wan/pipeline_wan_i2v.py
```py
import torch
from diffusers import WanImageToVideoPipeline, AutoencoderKLWan, ModularPipeline
model_id = "Wan-AI/Wan2.2-TI2V-5B-Diffusers"
dtype = torch.bfloat16
device = "cuda:2"
vae = AutoencoderKLWan.from_pretrained(model_id, subfolder="vae", torch_dtype=torch.float32)
pipe = WanImageToVideoPipeline.from_pretrained(model_id, vae=vae, torch_dtype=dtype)
pipe.enable_model_cpu_offload(device=device)
image_processor = ModularPipeline.from_pretrained("YiYiXu/WanImageProcessor", trust_remote_code=True)
image = image_processor(
image="https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/wan_i2v_input.JPG",
max_area=1280*704, output="processed_image")
height, width = image.height, image.width
print(f"height: …
```
=> [wan2.2] add 5b i2v

src/diffusers/pipelines/wan/pipeline_wan_i2v.py
https://huggingface.co/posts/a-r-r-o-w/278025275110164
currently this cache does not work with the latest diffusers. the reason being is the cache context not being properly initialised in the WanImageToVideoPipeline.
Fixes #12012 (which was prematurely closed)
@yiyixuxu  @asomoza @a-r-r-o-w  @DN6
=> wan2.2 i2v FirstBlockCache fix

examples/advanced_diffusion_training/train_dreambooth_lora_flux_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py, examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py, examples/dreambooth/train_dreambooth_flux.py, examples/dreambooth/train_dreambooth_lora_flux.py, examples/dreambooth/train_dreambooth_lora_sana.py
Similar to: https://github.com/huggingface/transformers/pull/39635.
Used the following scripts (thanks to o4 for pairing) to automate:
https://gist.github.com/sayakpaul/7f1f171d55c1122379ab0f5bdd4bd3dc
=> [training-scripts] Make pytorch examples UV-compatible

src/diffusers/models/autoencoders/autoencoder_kl_wan.py
fix https://github.com/huggingface/diffusers/issues/12034
```py
import torch
from diffusers import WanImageToVideoPipeline, AutoencoderKLWan, ModularPipeline
model_id = "Wan-AI/Wan2.2-TI2V-5B-Diffusers"
dtype = torch.bfloat16
device = "cuda:1"
vae = AutoencoderKLWan.from_pretrained(model_id, subfolder="vae", torch_dtype=torch.float32)
pipe = WanImageToVideoPipeline.from_pretrained(model_id, vae=vae, torch_dtype=dtype)
pipe.to(device)
image_processor = ModularPipeline.from_pretrained("YiYiXu/WanImageProcessor", trust_remote_code=True)
image = image_processor(
image="https://cloud.inference.sh/u/4mg21r6ta37mpaz6ktzwtt8krr/01k1g7k73eebnrmzmc6h0bghq6.png",
max_area=1280*704, output="processed_image")
height, width = image.height, …
```
=> [wan2.2] fix vae patches

src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
Allow SD pipeline to use newer schedulers, eg: FlowMatch,
by skipping attribute that doesnt exist there
(scale_model_input)
I am currently experimenting with SD + FlowMatchEuler, and had to do
an ugly hand hack in my training code to get the pipeline to continue:
```
print("HAND HACKING FLOWMATCH MODULE")
from diffusers import FlowMatchEulerDiscreteScheduler
def scale_model_input(self, sample, timestep):
return sample
FlowMatchEulerDiscreteScheduler.scale_model_input = scale_model_input
```
Would be nice to have core diffusers handle this so I can share training results with people cleanly.
- Pipelines and pipeline callbacks: @yiyixuxu and @asomoza
=> Allow SD pipeline to use newer schedulers, eg: FlowMatch

docs/source/en/api/pipelines/wan.md, src/diffusers/loaders/lora_conversion_utils.py
Fixes https://github.com/huggingface/diffusers/issues/12037
@luke14free, could you give this PR a try? I tested it with the following snippet:
```py
import torch
from huggingface_hub import hf_hub_download
"Wan-AI/Wan2.1-I2V-14B-480P-Diffusers",
torch_dtype=torch.bfloat16
)
lora_path = hf_hub_download(
repo_id="Kijai/WanVideo_comfy",
filename="Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank128_bf16.safetensors"
)
pipe.load_lora_weights(lora_path)
image_url = "https://cloud.inference.sh/u/4mg21r6ta37mpaz6ktzwtt8krr/01k1g7k73eebnrmzmc6h0bghq6.png"
response = requests.get(image_url)
input_image = …
```
=> [LoRA] support lightx2v lora in wan

src/diffusers/models/autoencoders/autoencoder_kl.py
Corrects the type specification of argument `force_upcast` in `AutoencodeKL` by changing it from `float` to `bool`.
=> Fix type of force_upcast to bool

docs/source/en/_toctree.yml, docs/source/en/api/models/autoencoderkl_qwenimage.md, docs/source/en/api/models/qwenimage_transformer2d.md, docs/source/en/api/pipelines/qwenimage.md, src/diffusers/models/autoencoders/autoencoder_kl_qwenimage.py, src/diffusers/models/transformers/transformer_qwenimage.py, src/diffusers/pipelines/qwenimage/pipeline_qwenimage.py, tests/pipelines/qwenimage/test_qwenimage.py
=> tests + minor refactor for QwenImage

src/diffusers/models/transformers/transformer_wan.py
Adds the cross attention module to the Wan Attention Class
Mirrors the previous Attention class and allows us to distinguish between attention instances
=> Cross attention module to Wan Attention

src/diffusers/models/autoencoders/autoencoder_kl_qwenimage.py
This PR update the license of the VAE model file.
We gratefully acknowledge the Wan Team for their outstanding contributions.
QwenImageVAE is further fine-tuned from the Wan Video VAE to achieve improved performance.
For more information about the Wan VAE, please refer to:
- GitHub: https://github.com/Wan-Video/Wan2.1 
- arXiv: https://arxiv.org/abs/2503.20314 
cc @yiyixuxu @a-r-r-o-w
=> fix(qwen-image): update vae license

docs/source/en/installation.md, src/diffusers/__init__.py
Refactors the installation guide, main change is to add a few copy/pasteable examples and primarily use `uv`.
=> [docs] Install

docs/source/en/api/loaders/lora.md, examples/dreambooth/README_qwen.md, examples/dreambooth/test_dreambooth_lora_qwenimage.py, examples/dreambooth/train_dreambooth_lora_qwen_image.py, src/diffusers/loaders/__init__.py, src/diffusers/loaders/lora_pipeline.py, src/diffusers/loaders/peft.py, src/diffusers/pipelines/qwenimage/pipeline_qwenimage.py, tests/lora/test_lora_layers_qwenimage.py
Still testing. Needs a custom token to test (refer Slack). We support quantization through the `bnb_quantization_config_path` CLI argument. 
<details>
<summary>test command</summary>
```bash
export MODEL_NAME="Qwen/Qwen-Image"
export INSTANCE_DIR="linoyts/3d_icon"
export OUTPUT_DIR="trained-qwen-image-lora"
accelerate launch train_dreambooth_lora_qwen_image.py \
--pretrained_model_name_or_path=$MODEL_NAME  \
--dataset_name=$INSTANCE_DIR \
--mixed_precision="bf16" \
--instance_prompt="3dicon" \
--caption_column="prompt"\
--validation_prompt="a 3dicon, a llama eating ramen" \
--resolution=1024 \
--gradient_accumulation_steps=4 \
--use_8bit_adam \
--rank=8 \
--learning_rate=2e-4 \
--report_to="wandb" \
--lr_scheduler="constant_with_warmup" \ …
```
=> [wip] feat: support lora in qwen image and training script

src/diffusers/models/transformers/transformer_flux.py
FluxSingleTransformerBlock:
The output type should be Tuple[torch.Tensor, torch.Tensor], not torch.Tensor.
=> fix flux type hint

src/diffusers/loaders/lora_conversion_utils.py
Saw some Flux.DEV loras in our DB with keys like
```
transformer.single_transformer_blocks.0.attn.to_k.alpha : Tensor @ torch.Size([])
transformer.single_transformer_blocks.0.attn.to_k.lora_down.weight : Tensor @ torch.Size([10, 3072])
transformer.single_transformer_blocks.0.attn.to_k.lora_up.weight : Tensor @ torch.Size([3072, 10])
transformer.single_transformer_blocks.0.attn.to_q.alpha : Tensor @ torch.Size([])
transformer.single_transformer_blocks.0.attn.to_q.lora_down.weight : Tensor @ torch.Size([8, 3072])
transformer.single_transformer_blocks.0.attn.to_q.lora_up.weight : Tensor @ torch.Size([3072, 8])
transformer.single_transformer_blocks.0.attn.to_v.alpha : Tensor @ torch.Size([])
transformer.single_transformer_blocks.0.attn.to_v.lora_down.weight : Tensor @ torch.Size([8, 3072]) …
```
=> lora_conversion_utils: replace lora up/down with a/b even if `transformer.` in key

src/diffusers/modular_pipelines/stable_diffusion_xl/before_denoise.py
importing `MultiControlNetModel` from `...pipelines.controlnet.multicontrolnet` is deprecated but it is used in this file with that import, this PR fix this so it's also imported from `...models.controlnets.multicontrolnet` 
@yiyixuxu
=> Fix MultiControlNet import

docs/source/en/api/pipelines/qwenimage.md, src/diffusers/loaders/lora_conversion_utils.py, src/diffusers/loaders/lora_pipeline.py
<details>
<summary>Code to test</summary>:
```py
from diffusers import DiffusionPipeline, FlowMatchEulerDiscreteScheduler
import torch 
import math
ckpt_id = "Qwen/Qwen-Image"
scheduler_config = {
"base_image_seq_len": 256,
"base_shift": math.log(3),  # We use shift=3 in distillation
"invert_sigmas": False,
"max_image_seq_len": 8192,
"max_shift": math.log(3),  # We use shift=3 in distillation
"num_train_timesteps": 1000,
"shift": 1.0,
"shift_terminal": None,  # set shift_terminal to None
"stochastic_sampling": False,
"time_shift_type": "exponential",
"use_beta_sigmas": False,
"use_dynamic_shifting": True,
"use_exponential_sigmas": False,
"use_karras_sigmas": False,
}
scheduler = FlowMatchEulerDiscreteScheduler.from_config(scheduler_config) …
```
=> [lora] support loading loras from `lightx2v/Qwen-Image-Lightning`

src/diffusers/loaders/single_file_model.py
`from_single_file` can lead to errors in training model:
```
File "/home/dongziyi/miniconda3/envs/pt25/lib/python3.11/site-packages/diffusers/loaders/single_file_model.py", line 447, in from_single_file                                       
dispatch_model(model, **device_map_kwargs)                                                                                                                                        
File "/home/dongziyi/miniconda3/envs/pt25/lib/python3.11/site-packages/accelerate/big_modeling.py", line 502, in dispatch_model                                                     
model.to(device)                                                                                                                                                                  
File …
```
=> Add low_cpu_mem_usage option to from_single_file to align with from_pretrained

docs/source/en/_toctree.yml, docs/source/en/stable_diffusion.md, src/diffusers/__init__.py
Refreshes the [Effective and efficient](https://huggingface.co/docs/diffusers/main/en/stable_diffusion) guide as a basic performance guide. They should be easy/simple steps for users just getting started to optimize inference. There is a link to the Inference Optimization section for the latest and more advanced methods.
=> [docs] Refresh effective and efficient doc

src/diffusers/pipelines/wan/pipeline_wan_vace.py, tests/lora/test_lora_layers_wanvace.py
Fix problem with vae, when vae's dtype != float32
Fixes https://github.com/huggingface/diffusers/issues/12141
@yiyixuxu and @asomoza
Maybe:
@DN6 @a-r-r-o-w
-->
=> Fix bf15/fp16 for pipeline_wan_vace.py

docs/source/en/_toctree.yml, docs/source/en/quicktour.md, docs/source/en/stable_diffusion.md
Refactors the Quickstart to provide a more complete snapshot of what Diffusers offers rather than focusing on how the components in a pipeline works. It was a good opportunity to include/link to some of the cool optimization stuff @sayakpaul and @a-r-r-o-w have been working on, which I consider to be a pretty important aspect of the library. 
This is a pretty high visibility doc, so let me know if there is anything else you think we should include or is missing. For example, should we include Hybrid inference and Modular Diffusers, or are these more experimental still?
=> [docs] Quickstart

src/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py
Fixing an emergent bug related to output image shape calculation.
cc @yiyixuxu @a-r-r-o-w @sayakpaul
=> Emergency fix for Qwen-Image-Edit

docs/source/zh/_toctree.yml, docs/source/zh/community_projects.md, docs/source/zh/modular_diffusers/auto_pipeline_blocks.md, docs/source/zh/modular_diffusers/loop_sequential_pipeline_blocks.md, docs/source/zh/modular_diffusers/modular_diffusers_states.md, docs/source/zh/modular_diffusers/modular_pipeline.md, docs/source/zh/modular_diffusers/overview.md, docs/source/zh/modular_diffusers/pipeline_block.md, docs/source/zh/modular_diffusers/quickstart.md, docs/source/zh/modular_diffusers/sequential_pipeline_blocks.md
Translate part documents into zh
n/A
=> translate document to zh

tests/pipelines/bria/test_pipeline_bria.py
@a-r-r-o-w @DN6 , pls help review, thx very much
=> enable bria integration test on xpu, passed

docs/source/en/api/pipelines/overview.md, docs/source/en/using-diffusers/callback.md
Refreshes the callback docs and adds API references for the officially supported callbacks
=> [docs] Pipeline callbacks

tests/pipelines/qwenimage/test_qwenimage_controlnet.py
This PR adds a fast test for the Qwen-Image ControlNet pipeline, following the existing [example ](https://github.com/huggingface/diffusers/blob/main/tests/pipelines/qwenimage/test_qwenimage.py)and controlnet [example ](https://github.com/huggingface/diffusers/blob/main/tests/pipelines/controlnet_flux/test_controlnet_flux.py)
Closes #[12222](https://github.com/huggingface/diffusers/issues/12222)
=> added a fast test for Qwen-Image Controlnet Pipeline

docs/source/en/using-diffusers/other-formats.md
Fixed two typos in 
https://huggingface.co/docs/diffusers/en/using-diffusers/other-formats
Fix no 1:
Original Markdown:
```py linenos
turbo_pipeline.scheduler = EulerDiscreteScheduler.from_config(
turbo_pipeline.scheduler.config,
timestep+spacing="trailing"
)
```
The issue is the `` + `` symbol in the `` timestep+spacing ``. Replaced the `` +  `` symbol with  `` _ ``
Update Markdown:
```py 
turbo_pipeline.scheduler = EulerDiscreteScheduler.from_config(
turbo_pipeline.scheduler.config,
timestep_spacing="trailing"
)
```
Fix no 2:
Original Markdown:
```py {numberLines=true}
from huggingface_hub import export_folder_as_dduf
import torch 
pipe = DiffusionPipeline.from_pretrained("black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16)
save_folder = …
```
=> docs: correct typos in using-diffusers/other-formats

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/reusing_seeds.md
Refreshes the reproducibility docs with a better explanation of whats happening when calling `enable_full_determinism()` and also removes a duplicate entry in the `toctree`.
=> [docs] Reproducibility

src/diffusers/modular_pipelines/modular_pipeline.py, src/diffusers/utils/constants.py, src/diffusers/utils/dynamic_modules_utils.py
Based on discussion here:
https://github.com/huggingface/diffusers/discussions/12033
Add an option to globally disable any downloading of remote code via an env variable. This is a bit of a guard against wrapper code around diffusers that might automatically download remote code without the user knowing. 
Note. It's not 100% foolproof since wrapper code could also override the env variable before doing any diffusers imports. I don't have a great solution for this at the moment. For now, I've added a warning for every time remote code is downloaded so that the user is at least alerted when this is happening.   
cc: @JoeGaffney …
=> [Modular] Provide option to disable custom code loading globally via env variable

src/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py
Adds the missing `image` input entry to `QwenImageEditPipeline`’s `__call__` method.
cc @yiyixuxu @sayakpaul @naykun
=> [QwenImageEditPipeline] Add image entry in __call__ function

docs/source/en/_toctree.yml, docs/source/en/using-diffusers/push_to_hub.md
Updates the `Push files to the Hub` docs with additional option to login from the command line
=> [docs] Sharing pipelines/models

src/diffusers/models/autoencoders/autoencoder_kl_wan.py
Fix autoencoder_kl_wan.py bugs for Wan2.2 VAE.
1. When using the Wan2.2 VAE, the spatial compression ratio calculated here is incorrect. It should be 16 instead of 8. Pass it in directly via the config to ensure it’s correct here.
2. When using enable_tiling with the Wan2.2 VAE, the input is not patchified beforehand, which leads to incorrect results.
=> Fix autoencoder_kl_wan.py bugs for Wan2.2 VAE

examples/server/README.md, examples/server/requirements.in, examples/server/requirements.txt
This pull request fixes the server example's dependencies and installation instructions. 
```py
pip install .
pip install -f requirements.txt
pip install diffusers
pip install -r requirements.txt
```
Dependency Updates:
* Updated `huggingface-hub` to version `0.35.0` in `requirements.txt` to ensure compatibility with recent features and bug fixes.
* Added `accelerate` to `requirements.in` to support efficient model inference and hardware utilization.
* Note: This follows the server-async instructions.
Installation Instructions:
* Updated the installation commands in `README.md` to explicitly install `diffusers` and corrected the requirements file flag to `-r` for clarity and correctness.
- Docs: @stevhliu and @sayakpaul
=> Fix example server install instructions

tests/models/test_modeling_common.py
=> Don't skip Qwen model tests for group offloading with disk

tests/models/test_modeling_common.py
Low priority.
I noticed that the test should be for the option check_compiled="ignore" but it was using check_compiled="warn". This has been fixed, now the correct argument is passed.
However, the fact that the test passed means that it was incorrect to begin with. The way that logs are collected does not collect the logger.warning call here (not sure why). To amend this, I'm now using assertNoLogs. With this change, the test correctly fails when the wrong argument is passed. Note that assertNoLogs requires Python 3.10+ (3.9 is EOL since yesterday :tada:).
=> FIX: Test to ignore warning for enable_lora_hotswap

docs/source/ko/conceptual/ethical_guidelines.md
Adds the **Korean translation** of the `ethical_guidelines.md` file under `docs/source/ko/conceptual/`.
This update improves accessibility for Korean developers and researchers by providing an accurate, up-to-date translation of the Diffusers ethical guidelines.  
It aligns with Hugging Face’s commitment to open collaboration and responsible AI.
Fixes #9396
@stevhliu (Docs)
@sayakpaul (General)
---
This PR is part of the ongoing Korean i18n improvement efforts in the Diffusers documentation.  
Previously, some files under `docs/source/ko` were marked “in progress.”  
This PR completes and updates one of those documents (`ethical_guidelines.md`) based on the latest English content.
=> [i18n-KO] Fix typo and update translation in ethical_guidelines.md

src/diffusers/modular_pipelines/flux/before_denoise.py, src/diffusers/modular_pipelines/flux/denoise.py, src/diffusers/modular_pipelines/flux/encoders.py, src/diffusers/modular_pipelines/flux/inputs.py, src/diffusers/modular_pipelines/flux/modular_blocks.py
As the title goes. 
Next plan is to incorporate these changes in https://github.com/huggingface/diffusers/pull/12269/. 
I tested with the code snippet from https://github.com/huggingface/diffusers/pull/12419#issuecomment-3369922849. 
For img2img, I did:
```py
import torch 
from diffusers import ModularPipeline
repo_id = "black-forest-labs/FLUX.1-dev"
pipe = ModularPipeline.from_pretrained(repo_id)
pipe.load_components(torch_dtype=torch.bfloat16)
url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"
init_image = load_image(url).resize((1024, 1024))
output = pipe(
prompt="a dog sitting by the see waiting for its companion to come",
image=init_image, …
```
=> Align Flux modular more and more with Qwen modular
